---@diagnostic disable: undefined-global
local _, addon = ...

addon.combatProtected = {
  -- List of cvars that can't be modified in combat
  ["alwaysShowActionBars"] = true,
  ["colorblindSimulator"] = true,
  ["colorblindWeaknessFactor"] = true,
  ["daltonize"] = true,
  ["fullSizeFocusFrame"] = true,
  ["garrisonCompleteTalent"] = true,
  ["garrisonCompleteTalentType"] = true,
  ["nameplateClassResourceTopInset"] = true,
  ["nameplateGlobalScale"] = true,
  ["NamePlateHorizontalScale"] = true,
  ["nameplateLargeBottomInset"] = true,
  ["nameplateLargerScale"] = true,
  ["nameplateLargeTopInset"] = true,
  ["nameplateMaxAlpha"] = true,
  ["nameplateMaxAlphaDistance"] = true,
  ["nameplateMaxDistance"] = true,
  ["nameplateMaxScale"] = true,
  ["nameplateMaxScaleDistance"] = true,
  ["nameplateMinAlpha"] = true,
  ["nameplateMinAlphaDistance"] = true,
  ["nameplateMinScale"] = true,
  ["nameplateMinScaleDistance"] = true,
  ["nameplateMotion"] = true,
  ["nameplateMotionSpeed"] = true,
  ["nameplateOtherAtBase"] = true,
  ["nameplateOtherBottomInset"] = true,
  ["nameplateOtherTopInset"] = true,
  ["nameplateOverlapH"] = true,
  ["nameplateOverlapV"] = true,
  ["NameplatePersonalHideDelayAlpha"] = true,
  ["nameplatePersonalHideDelaySeconds"] = true,
  ["nameplatePersonalShowAlways"] = true,
  ["nameplatePersonalShowInCombat"] = true,
  ["nameplatePersonalShowWithTarget"] = true,
  ["nameplateResourceOnTarget"] = true,
  ["nameplateSelectedAlpha"] = true,
  ["nameplateSelectedScale"] = true,
  ["nameplateSelfAlpha"] = true,
  ["nameplateSelfBottomInset"] = true,
  ["nameplateSelfScale"] = true,
  ["nameplateSelfTopInset"] = true,
  ["nameplateShowAll"] = true,
  ["nameplateShowEnemies"] = true,
  ["nameplateShowEnemyGuardians"] = true,
  ["nameplateShowEnemyMinions"] = true,
  ["nameplateShowEnemyMinus"] = true,
  ["nameplateShowEnemyPets"] = true,
  ["nameplateShowEnemyTotems"] = true,
  ["nameplateShowFriendlyGuardians"] = true,
  ["nameplateShowFriendlyMinions"] = true,
  ["nameplateShowFriendlyNPCs"] = true,
  ["nameplateShowFriendlyPets"] = true,
  ["nameplateShowFriendlyTotems"] = true,
  ["nameplateShowFriends"] = true,
  ["nameplateShowSelf"] = true,
  ["nameplateTargetBehindMaxDistance"] = true,
  ["NamePlateVerticalScale"] = true,
  ["showArenaEnemyFrames"] = true,
  ["showArenaEnemyPets"] = true,
  ["showPartyPets"] = true,
  ["showTargetOfTarget"] = true,
  ["splashScreenBoost"] = true,
  ["splashScreenNormal"] = true,
  ["targetOfTargetMode"] = true,
  ["uiScale"] = true,
  ["uiScaleMultiplier"] = true,
  ["UnitNameGuildTitle"] = true,
  ["useCompactPartyFrames"] = true,
  ["useUiScale"] = true,
}

addon.hiddenOptions = {
  -- 姓名
  ["UnitNameOwn"] = { prettyName = UNIT_NAME_OWN, description = OPTION_TOOLTIP_UNIT_NAME_OWN, type = "boolean" },
  ["UnitNameNPC"] = { prettyName = UNIT_NAME_NPC, description = OPTION_TOOLTIP_UNIT_NAME_NPC, type = "boolean" },
  ["UnitNameNonCombatCreatureName"] = { prettyName = UNIT_NAME_NONCOMBAT_CREATURE, description = OPTION_TOOLTIP_UNIT_NAME_NONCOMBAT_CREATURE, type = "boolean" },
  ["UnitNamePlayerGuild"] = { prettyName = UNIT_NAME_GUILD, description = OPTION_TOOLTIP_UNIT_NAME_GUILD, type = "boolean" },
  ["UnitNameGuildTitle"] = { prettyName = UNIT_NAME_GUILD_TITLE, description = OPTION_TOOLTIP_UNIT_NAME_GUILD_TITLE, type = "boolean" },
  ["UnitNamePlayerPVPTitle"] = { prettyName = UNIT_NAME_PLAYER_TITLE, description = OPTION_TOOLTIP_UNIT_NAME_PLAYER_TITLE, type = "boolean" },
  ["UnitNameFriendlyPlayerName"] = { prettyName = UNIT_NAME_FRIENDLY, description = OPTION_TOOLTIP_UNIT_NAME_FRIENDLY, type = "boolean" },
  ["UnitNameFriendlyPetName"] = { prettyName = UNIT_NAME_FRIENDLY_PETS, description = OPTION_TOOLTIP_UNIT_NAME_FRIENDLY_PETS, type = "boolean" },
  ["UnitNameFriendlyGuardianName"] = { prettyName = UNIT_NAME_FRIENDLY_GUARDIANS, description = OPTION_TOOLTIP_UNIT_NAME_FRIENDLY_GUARDIANS, type = "boolean" },
  ["UnitNameFriendlyTotemName"] = { prettyName = UNIT_NAME_FRIENDLY_TOTEMS, description = OPTION_TOOLTIP_UNIT_NAME_FRIENDLY_TOTEMS, type = "boolean" },
  ["UnitNameFriendlyMinionName"] = { prettyName = UNIT_NAME_FRIENDLY_MINIONS, description = "", type = "boolean" },
  ["UnitNameEnemyPlayerName"] = { prettyName = UNIT_NAME_ENEMY, description = OPTION_TOOLTIP_UNIT_NAME_ENEMY, type = "boolean" },
  ["UnitNameEnemyPetName"] = { prettyName = UNIT_NAME_ENEMY_PETS, description = OPTION_TOOLTIP_UNIT_NAME_ENEMY_PETS, type = "boolean" },
  ["UnitNameEnemyGuardianName"] = { prettyName = UNIT_NAME_ENEMY_GUARDIANS, description = OPTION_TOOLTIP_UNIT_NAME_ENEMY_GUARDIANS, type = "boolean" },
  ["UnitNameEnemyTotemName"] = { prettyName = UNIT_NAME_ENEMY_TOTEMS, description = OPTION_TOOLTIP_UNIT_NAME_ENEMY_TOTEMS, type = "boolean" },
  ["UnitNameEnemyMinionName"] = { prettyName = UNIT_NAME_ENEMY_MINIONS, description = "", type = "boolean" },
  ["UnitNameForceHideMinus"] = { prettyName = UNIT_NAME_HIDE_MINUS, description = OPTION_TOOLTIP_UNIT_NAME_HIDE_MINUS, type = "boolean" },
  ["UnitNameFriendlySpecialNPCName"] = { prettyName = NPC_NAMES_DROPDOWN_TRACKED, description = NPC_NAMES_DROPDOWN_TRACKED_TOOLTIP, type = "boolean" },
  ["UnitNameHostleNPC"] = { prettyName = "敵對NPC", description = "顯示敵對NPC的名稱", type = "boolean" },
  ["UnitNameInteractiveNPC"] = { prettyName = "可互動NPC", description = "顯示可互動NPC的名稱", type = "boolean" },
  -- 名條
  ["nameplateShowFriends"] = { prettyName = UNIT_NAMEPLATES_SHOW_FRIENDS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_FRIENDS, type = "boolean" },
  ["nameplateShowFriendlyPets"] = { prettyName = UNIT_NAMEPLATES_SHOW_FRIENDLY_PETS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_FRIENDLY_PETS, type = "boolean" },
  ["nameplateShowFriendlyGuardians"] = {
    prettyName = UNIT_NAMEPLATES_SHOW_FRIENDLY_GUARDIANS,
    description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_FRIENDLY_GUARDIANS,
    type = "boolean",
  },
  ["nameplateShowFriendlyTotems"] = { prettyName = UNIT_NAMEPLATES_SHOW_FRIENDLY_TOTEMS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_FRIENDLY_TOTEMS, type = "boolean" },
  ["nameplateShowFriendlyNPCs"] = { prettyName = "友方NPC", description = "永遠顯示友方NPC的名條", type = "boolean" },
  ["nameplateShowEnemies"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMIES, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMIES, type = "boolean" },
  ["nameplateShowEnemyPets"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMY_PETS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMY_PETS, type = "boolean" },
  ["nameplateShowEnemyGuardians"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMY_GUARDIANS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMY_GUARDIANS, type = "boolean" },
  ["nameplateShowEnemyTotems"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMY_TOTEMS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMY_TOTEMS, type = "boolean" },
  ["nameplateShowEnemyMinus"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMY_MINUS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMY_MINUS, type = "boolean" },
  ["nameplateOtherAtBase"] = {
    prettyName = "名條於底部",
    description = "將其他名條置於底部，而不是頭頂。2=單位下方，0=單位上方",
    type = "boolean",
  },
  ["nameplateOverlapH"] = { prettyName = "名條重疊（水平）", description = "名條水平重疊的百分比", type = "number" },
  ["nameplateOverlapV"] = { prettyName = "名條重疊（垂直）", description = "名條垂直重疊的百分比", type = "number" },
  ["nameplateMaxDistance"] = { prettyName = "名條距離", description = "顯示名條的最大距離。", type = "number" },
  ["nameplateTargetBehindMaxDistance"] = {
    prettyName = "目標名條後方距離",
    description = "當目標位於鏡頭後方時，顯示目標名條的最大距離。",
    type = "number",
  },
  ["nameplateGlobalScale"] = {
    prettyName = "名條整體縮放",
    description = "對非自身名條應用整體縮放，此縮放將在選擇、最小和最大縮放後應用。",
    type = "number",
  },
  ["nameplateMinScale"] = { prettyName = "名條最小縮放", description = "名條的最小縮放比例。", type = "number" },
  ["nameplateMaxScale"] = { prettyName = "名條最大縮放", description = "名條的最大縮放比例。", type = "number" },
  ["nameplateLargerScale"] = { prettyName = "名條較大縮放", description = "重要怪物的額外縮放修改器。", type = "number" },
  ["nameplateMinScaleDistance"] = {
    prettyName = "名條最小縮放距離",
    description = "從最大距離開始，名條將達到其最小縮放比例的距離。",
    type = "number",
  },
  ["nameplateMaxScaleDistance"] = {
    prettyName = "名條最大縮放距離",
    description = "從鏡頭開始，名條將達到其最大縮放比例的距離",
    type = "number",
  },
  ["nameplateMinAlpha"] = { prettyName = "名條最小透明度", description = "名條的最小透明度。", type = "number" },
  ["nameplateMaxAlpha"] = { prettyName = "名條最大透明度", description = "名條的最大透明度。", type = "number" },
  ["nameplateMinAlphaDistance"] = {
    prettyName = "名條最小透明度距離",
    description = "從最大距離開始，名條將達到其最小透明度的距離。",
    type = "number",
  },
  ["nameplateMaxAlphaDistance"] = {
    prettyName = "名條最大透明度距離",
    description = "從鏡頭開始，名條將達到其最大透明度的距離。",
    type = "number",
  },
  ["nameplateSelectedScale"] = { prettyName = "名條選定縮放", description = "選定名條的縮放比例。", type = "number" },
  ["nameplateSelectedAlpha"] = { prettyName = "名條選定透明度", description = "選定名條的透明度。", type = "number" },
  ["nameplateSelfScale"] = { prettyName = "自身名條縮放", description = "自身名條的縮放比例。", type = "number" },
  ["nameplateSelfAlpha"] = { prettyName = "自身名條透明度", description = "自身名條的透明度。", type = "number" },
  ["nameplateSelfBottomInset"] = {
    prettyName = "自身名條底部間距",
    description = "自身名條被限制在底部的間距量（以螢幕百分比表示）。",
    type = "number",
  },
  ["nameplateSelfTopInset"] = {
    prettyName = "自身名條頂部間距",
    description = "自身名條被限制在頂部的間距量（以螢幕百分比表示）。",
    type = "number",
  },
  ["nameplateOtherBottomInset"] = {
    prettyName = "其他名條底部間距",
    description = "非自身名條被限制在底部的間距量（以螢幕百分比表示）。",
    type = "number",
  },
  ["nameplateOtherTopInset"] = {
    prettyName = "其他名條頂部間距",
    description = "非自身名條被限制在頂部的間距量（以螢幕百分比表示）。",
    type = "number",
  },
  ["nameplateLargeBottomInset"] = {
    prettyName = "大型名條底部間距",
    description = "大型名條被限制在底部的間距量（以螢幕百分比表示）。",
    type = "number",
  },
  ["nameplateLargeTopInset"] = {
    prettyName = "大型名條頂部間距",
    description = "大型名條被限制在頂部的間距量（以螢幕百分比表示）。",
    type = "number",
  },
  ["nameplateClassResourceTopInset"] = {
    prettyName = "名條職業資源頂部間距",
    description = "當職業資源顯示在名條上時，名條被限制在頂部的間距量（以螢幕百分比表示）。",
    type = "number",
  },
  ["NamePlateHorizontalScale"] = { prettyName = "名條水平縮放", description = "應用於所有名條的水平大小。", type = "number" },
  ["NamePlateVerticalScale"] = { prettyName = "名條垂直縮放", description = "應用於所有名條的垂直大小。", type = "number" },
  ["nameplateResourceOnTarget"] = { prettyName = "目標名條資源", description = "名條職業資源覆蓋模式。0=自身，1=目標", type = "number" },
  ["nameplateShowSelf"] = { prettyName = "顯示名條資源條", description = "顯示職業資源條。0=關閉 1=開啟", type = "number" },
  ["nameplateShowAll"] = { prettyName = "永遠顯示名條", description = "始終顯示名條。", type = "number" },
  ["nameplateMotion"] = { prettyName = "名條移動類型", description = "0 = 重疊 - 1 = 堆疊", type = "number" },
  ["namePlateFriendlySize"] = { prettyName = "", description = "", type = "number" },
  ["namePlateEnemySize"] = { prettyName = "", description = "", type = "number" },
  ["namePlateSelfClickThrough"] = { prettyName = "", description = "", type = "number" },
  ["namePlateFriendlyClickThrough"] = { prettyName = "", description = "", type = "number" },
  ["namePlateEnemyClickThrough"] = { prettyName = "", description = "", type = "number" },
  ["nameplatePersonalShowAlways"] = { prettyName = "", description = "始終顯示個人名條", type = "boolean" },
  ["nameplatePersonalShowInCombat"] = { prettyName = "", description = "戰鬥中始終顯示個人名條", type = "boolean" },
  ["nameplatePersonalShowWithTarget"] = { prettyName = "", description = "始終顯示具有敵對目標的個人名條", type = "boolean" },
  ["nameplatePersonalHideDelaySeconds"] = { prettyName = "", description = "隱藏個人名條之前的等待延遲", type = "boolean" },
  ["ShowNamePlateLoseAggroFlash"] = { prettyName = nil, description = "啟用後，如果您是坦克職業並且失去仇恨，名條將會短暫閃爍。", type = "boolean" },
  ["ShowClassColorInNameplate"] = { prettyName = SHOW_CLASS_COLOR_IN_V_KEY, description = OPTION_TOOLTIP_SHOW_CLASS_COLOR_IN_V_KEY, type = "boolean" },
  ["ShowClassColorInFriendlyNameplate"] = { prettyName = "職業顏色友方名條", description = "友方名條的職業顏色", type = "boolean" },

  ["nameplateTargetRadialPosition"] = { prettyName = nil, description = "當目標在螢幕外時，將其名條徑向放置在側面和底部", type = "number" },
  ["nameplateOccludedAlphaMult"] = { prettyName = nil, description = "被遮擋目標的名條Alpha乘數", type = "number" },

  ["reverseCleanupBags"] = { prettyName = REVERSE_CLEAN_UP_BAGS_TEXT, description = OPTION_TOOLTIP_REVERSE_CLEAN_UP_BAGS, type = "boolean" },
  ["lootLeftmostBag"] = { prettyName = REVERSE_NEW_LOOT_TEXT, description = OPTION_TOOLTIP_REVERSE_NEW_LOOT, type = "boolean" },
  ["stopAutoAttackOnTargetChange"] = { prettyName = STOP_AUTO_ATTACK, description = OPTION_TOOLTIP_STOP_AUTO_ATTACK, type = "boolean" },
  ["assistAttack"] = { prettyName = ASSIST_ATTACK, description = OPTION_TOOLTIP_ASSIST_ATTACK, type = "boolean" },
  ["autoSelfCast"] = { prettyName = AUTO_SELF_CAST_TEXT, description = OPTION_TOOLTIP_SELF_CAST_TEXT, type = "boolean" },
  ["ActionButtonUseKeyDown"] = { prettyName = ACTION_BUTTON_USE_KEY_DOWN, description = OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN, type = "boolean" },
  ["mapFade"] = { prettyName = MAP_FADE_TEXT, description = OPTION_TOOLTIP_MAP_FADE, type = "boolean" },
  ["trackQuestSorting"] = { type = "table", options = { "proximity", "top" } },
  ["removeChatDelay"] = { prettyName = REMOVE_CHAT_DELAY_TEXT, description = OPTION_TOOLTIP_REMOVE_CHAT_DELAY_TEXT, type = "boolean" },
  ["secureAbilityToggle"] = { prettyName = SECURE_ABILITY_TOGGLE, description = OPTION_TOOLTIP_SECURE_ABILITY_TOGGLE, type = "boolean" },
  ["scriptErrors"] = { prettyName = SHOW_LUA_ERRORS, description = OPTION_TOOLTIP_SHOW_LUA_ERRORS, type = "boolean" },
  ["lootUnderMouse"] = { prettyName = LOOT_UNDER_MOUSE_TEXT, description = OPTION_TOOLTIP_LOOT_UNDER_MOUSE_TEXT, type = "boolean" },
  ["ShowQuestUnitCircles"] = { prettyName = "任務單位圓圈", description = "確定與任務相關的單位是否在地面上顯示指示器", type = "boolean" },
  ["autoLootDefault"] = { prettyName = AUTO_LOOT_DEFAULT_TEXT, description = OPTION_TOOLTIP_AUTO_LOOT_DEFAULT, type = "boolean" },
  ["threatShowNumeric"] = { prettyName = SHOW_NUMERIC_THREAT, description = OPTION_TOOLTIP_SHOW_NUMERIC_THREAT, type = "boolean" },
  ["showLootSpam"] = { prettyName = SHOW_LOOT_SPAM, description = OPTION_TOOLTIP_SHOW_LOOT_SPAM, type = "boolean" },
  ["advancedWatchFrame"] = { prettyName = ADVANCED_OBJECTIVES_TEXT, description = OPTION_TOOLTIP_ADVANCED_OBJECTIVES_TEXT, type = "" },
  ["watchFrameIgnoreCursor"] = { prettyName = OBJECTIVES_IGNORE_CURSOR_TEXT, description = OPTION_TOOLTIP_OBJECTIVES_IGNORE_CURSOR, type = "boolean" },
  ["guildMemberNotify"] = { prettyName = GUILDMEMBER_ALERT, description = OPTION_TOOLTIP_GUILDMEMBER_ALERT, type = "boolean" },
  ["autoClearAFK"] = { prettyName = nil, description = OPTION_TOOLTIP_CLEAR_AFK, type = "boolean" },
  ["colorblindWeaknessFactor"] = { prettyName = nil, description = OPTION_TOOLTIP_ADJUST_COLORBLIND_STRENGTH, type = "boolean" },
  ["autoLootRate"] = { prettyName = "自動拾取速度", description = "自動拾取勾選的速度（以毫秒為單位）", type = "number" },
  ["ChatAmbienceVolume"] = { prettyName = nil, description = "", type = "boolean" },
  ["rightActionBar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_MULTIBAR3, type = "boolean" },
  ["emphasizeMySpellEffects"] = { prettyName = nil, description = OPTION_TOOLTIP_EMPHASIZE_MY_SPELLS, type = "boolean" },
  ["chatBubblesParty"] = { prettyName = nil, description = OPTION_TOOLTIP_PARTY_CHAT_BUBBLES, type = "boolean" },
  ["enableTwitter"] = { prettyName = nil, description = OPTION_TOOLTIP_SOCIAL_ENABLE_TWITTER_FUNCTIONALITY, type = "boolean" },
  ["threatPlaySounds"] = { prettyName = nil, description = OPTION_TOOLTIP_PLAY_AGGRO_SOUNDS, type = "boolean" },
  -- 通知訊息 嗯...通知訊息。
  ["showToastOnline"] = { prettyName = SHOW_TOAST_ONLINE_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_ONLINE, type = "boolean" },
  ["showToastOffline"] = { prettyName = SHOW_TOAST_OFFLINE_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_OFFLINE, type = "boolean" },
  ["showToastBroadcast"] = { prettyName = SHOW_TOAST_BROADCAST_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_BROADCAST, type = "boolean" },
  ["showToastFriendRequest"] = { prettyName = SHOW_TOAST_FRIEND_REQUEST_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_FRIEND_REQUEST, type = "boolean" },
  ["showToastConversation"] = { prettyName = SHOW_TOAST_CONVERSATION_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_CONVERSATION, type = "boolean" },
  ["showToastWindow"] = { prettyName = SHOW_TOAST_WINDOW_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_WINDOW, type = "boolean" },
  ["toastDuration"] = { prettyName = nil, description = OPTION_TOOLTIP_TOAST_DURATION, type = "number" },

  ["enableMouseSpeed"] = { prettyName = ENABLE_MOUSE_SPEED, description = OPTION_TOOLTIP_ENABLE_MOUSE_SPEED, type = "boolean" },
  ["mouseInvertPitch"] = { prettyName = INVERT_MOUSE, description = OPTION_TOOLTIP_INVERT_MOUSE, type = "boolean" },
  ["enableWoWMouse"] = { prettyName = WOW_MOUSE, description = OPTION_TOOLTIP_WOW_MOUSE, type = "boolean" },
  ["autointeract"] = { prettyName = CLICK_TO_MOVE, description = OPTION_TOOLTIP_CLICK_TO_MOVE, type = "boolean" },
  ["mouseSpeed"] = { prettyName = MOUSE_SENSITIVITY, description = OPTION_TOOLTIP_MOUSE_SENSITIVITY, type = "number" },

  ["wholeChatWindowClickable"] = { prettyName = nil, description = OPTION_TOOLTIP_CHAT_WHOLE_WINDOW_CLICKABLE, type = "boolean" },
  ["useEnglishAudio"] = { prettyName = nil, description = OPTION_TOOLTIP_USE_ENGLISH_AUDIO, type = "boolean" },
  ["ChatSoundVolume"] = { prettyName = nil, description = "", type = "number" },
  --["reducedLagTolerance"] = { prettyName = "自定義延遲容忍度", description = OPTION_TOOLTIP_REDUCED_LAG_TOLERANCE, type = "boolean" },
  ["EnableMicrophone"] = { prettyName = nil, description = OPTION_TOOLTIP_ENABLE_MICROPHONE, type = "boolean" },
  ["autoOpenLootHistory"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_OPEN_LOOT_HISTORY, type = "boolean" },
  ["showVKeyCastbarOnlyOnTarget"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_CASTBAR_IN_V_KEY_ONLY_ON_TARGET, type = "boolean" },
  ["displaySpellActivationOverlays"] = { prettyName = nil, description = OPTION_TOOLTIP_DISPLAY_SPELL_ALERTS, type = "boolean" },
  ["hdPlayerModels"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_HD_MODELS, type = "boolean" },
  ["autoLootKey"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_LOOT_KEY, type = "boolean" }, -- TODO 類型
  ["SpellQueueWindow"] = {
    prettyName = SPELL_QUEUE_WINDOW,
    description = "決定在允許將法術請求發送到伺服器之前，法術隊列窗口可以領先“法術結束”開始恢復法術系統多長時間。即，這控制了技能排隊系統的內置延遲。",
    type = "number",
  },
  ["advancedCombatLogging"] = { prettyName = nil, description = OPTION_TOOLTIP_ADVANCED_COMBAT_LOGGING, type = "boolean" },
  ["disableServerNagle"] = { prettyName = nil, description = OPTION_TOOLTIP_OPTIMIZE_NETWORK_SPEED, type = "boolean" },
  -- 鏡頭
  ["cameraYawSmoothSpeed"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_FOLLOW_SPEED, type = "number" },
  ["cameraWaterCollision"] = { prettyName = nil, description = OPTION_TOOLTIP_WATER_COLLISION, type = "boolean" },
  ["cameraBobbing"] = { prettyName = nil, description = OPTION_TOOLTIP_HEAD_BOB, type = "boolean" },
  ["cameraPivot"] = { prettyName = nil, description = OPTION_TOOLTIP_SMART_PIVOT, type = "boolean" },
  ["cameraDistanceMaxZoomFactor"] = { prettyName = MAX_FOLLOW_DIST, description = OPTION_TOOLTIP_MAX_FOLLOW_DIST, type = "number" },
  ["cameraYawMoveSpeed"] = { prettyName = MOUSE_LOOK_SPEED, description = OPTION_TOOLTIP_MOUSE_LOOK_SPEED, type = "number" },
  ["cameraTerrainTilt"] = { prettyName = nil, description = OPTION_TOOLTIP_FOLLOW_TERRAIN, type = "boolean" },
  ["cameraHeadMovementStrength"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraHeadMovementWhileStanding"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraHeadMovementRange"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraHeadMovementSmoothRate"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraDynamicPitch"] = { prettyName = nil, description = nil, type = "number" },
  -- ["cameraDynamicPitchBaseFovPad"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraDynamicPitchBaseFovPadFlying"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraDynamicPitchSmartPivotCutoffDist"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraOverShoulder"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraLockedTargetFocusing"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraDistanceMoveSpeed"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraPitchMoveSpeed"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraBobbingSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraFoVSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraDistanceSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraGroundSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraHeightSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraPitchSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraTargetSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
  -- ["cameraFlyingMountHeightSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraViewBlendStyle"] = { prettyName = nil, description = nil, type = "number" },
  ["camerasmooth"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraSmoothPitch"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraSmoothYaw"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraSmoothStyle"] = { prettyName = nil, description = nil, type = "number" },
  ["cameraSmoothTrackingStyle"] = { prettyName = nil, description = nil, type = "number" },

  ["chatBubbles"] = { prettyName = nil, description = OPTION_TOOLTIP_CHAT_BUBBLES, type = "boolean" },
  ["autoDismountFlying"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_DISMOUNT_FLYING, type = "boolean" },
  ["bottomRightActionBar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_MULTIBAR2, type = "boolean" },
  ["showPartyBackground"] = { prettyName = SHOW_PARTY_BACKGROUND_TEXT, description = OPTION_TOOLTIP_SHOW_PARTY_BACKGROUND, type = "boolean" },
  ["showPartyPets"] = { prettyName = SHOW_PARTY_PETS_TEXT, description = OPTION_TOOLTIP_SHOW_PARTY_PETS, type = "boolean" },
  ["showArenaEnemyFrames"] = { prettyName = SHOW_ARENA_ENEMY_FRAMES_TEXT, description = OPTION_TOOLTIP_SHOW_ARENA_ENEMY_FRAMES, type = "boolean" },
  ["showArenaEnemyCastbar"] = { prettyName = SHOW_ARENA_ENEMY_CASTBAR_TEXT, description = OPTION_TOOLTIP_SHOW_ARENA_ENEMY_CASTBAR, type = "boolean" },
  ["showArenaEnemyPets"] = { prettyName = SHOW_ARENA_ENEMY_PETS_TEXT, description = OPTION_TOOLTIP_SHOW_ARENA_ENEMY_PETS, type = "boolean" },
  ["fullSizeFocusFrame"] = { prettyName = FULL_SIZE_FOCUS_FRAME_TEXT, description = OPTION_TOOLTIP_FULL_SIZE_FOCUS_FRAME, type = "boolean" },
  ["spamFilter"] = { prettyName = nil, description = OPTION_TOOLTIP_SPAM_FILTER, type = "boolean" },
  ["profanityFilter"] = { prettyName = nil, description = OPTION_TOOLTIP_PROFANITY_FILTER, type = "boolean" },
  ["EnableVoiceChat"] = { prettyName = nil, description = OPTION_TOOLTIP_ENABLE_VOICECHAT, type = "boolean" },
  ["rightTwoActionBar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_MULTIBAR4, type = "boolean" },
  ["rotateMinimap"] = { prettyName = nil, description = OPTION_TOOLTIP_ROTATE_MINIMAP, type = "boolean" },
  ["blockTrades"] = { prettyName = nil, description = OPTION_TOOLTIP_BLOCK_TRADES, type = "boolean" },
  ["movieSubtitle"] = { prettyName = nil, description = OPTION_TOOLTIP_CINEMATIC_SUBTITLES, type = "boolean" },
  ["displayFreeBagSlots"] = { prettyName = nil, description = OPTION_TOOLTIP_DISPLAY_FREE_BAG_SLOTS, type = "boolean" },
  ["lockActionBars"] = { prettyName = nil, description = OPTION_TOOLTIP_LOCK_ACTIONBAR, type = "boolean" },
  ["screenEdgeFlash"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_FULLSCREEN_STATUS, type = "boolean" },
  ["showVKeyCastbar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_CASTBAR_IN_V_KEY, type = "boolean" },
  ["chatMouseScroll"] = { prettyName = CHAT_MOUSE_WHEEL_SCROLL, description = OPTION_TOOLTIP_CHAT_MOUSE_WHEEL_SCROLL, type = "boolean" },
  ["InboundChatVolume"] = { prettyName = nil, description = OPTION_TOOLTIP_VOICE_OUTPUT_VOLUME, type = "number" },
  ["spellActivationOverlayOpacity"] = { prettyName = nil, description = OPTION_TOOLTIP_SPELL_ALERT_OPACITY, type = "number" },
  ["PushToTalkSound"] = { prettyName = nil, description = OPTION_TOOLTIP_PUSHTOTALK_SOUND, type = "boolean" },
  ["countdownForCooldowns"] = { prettyName = nil, description = OPTION_TOOLTIP_COUNTDOWN_FOR_COOLDOWNS, type = "boolean" },
  ["VoiceActivationSensitivity"] = { prettyName = nil, description = OPTION_TOOLTIP_VOICE_ACTIVATION_SENSITIVITY, type = "number" },
  ["alwaysShowActionBars"] = { prettyName = nil, description = OPTION_TOOLTIP_ALWAYS_SHOW_MULTIBARS, type = "boolean" },
  ["OutboundChatVolume"] = { prettyName = nil, description = OPTION_TOOLTIP_VOICE_INPUT_VOLUME, type = "number" },
  ["autoQuestWatch"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_QUEST_WATCH, type = "boolean" },
  ["SpellTooltip_DisplayAvgValues"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_POINTS_AS_AVG, type = "boolean" },
  ["bottomLeftActionBar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_MULTIBAR1, type = "boolean" },
  ["showVKeyCastbarSpellName"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_CASTBAR_IN_V_KEY_SPELL_NAME, type = "boolean" },
  ["buffDurations"] = { prettyName = SHOW_BUFF_DURATION_TEXT, description = OPTION_TOOLTIP_SHOW_BUFF_DURATION, type = "boolean" },
  ["showDispelDebuffs"] = { prettyName = SHOW_DISPELLABLE_DEBUFFS_TEXT, description = OPTION_TOOLTIP_SHOW_DISPELLABLE_DEBUFFS, type = "boolean" },
  ["showCastableBuffs"] = { prettyName = SHOW_CASTABLE_BUFFS_TEXT, description = OPTION_TOOLTIP_SHOW_CASTABLE_BUFFS, type = "boolean" },
  ["deselectOnClick"] = { prettyName = nil, description = OPTION_TOOLTIP_GAMEFIELD_DESELECT, type = "boolean" },
  ["autoQuestProgress"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_QUEST_PROGRESS, type = "boolean" },
  ["UberTooltips"] = { prettyName = USE_UBERTOOLTIPS, description = OPTION_TOOLTIP_USE_UBERTOOLTIPS, type = "boolean" },
  ["chatClassColorOverride"] = { prettyName = "停用職業顏色", description = "停用聊天中的職業顏色", type = "boolean" },
  -- Sound
  ["Sound_EnableAllSound"] = { prettyName = ENABLE_SOUND, description = OPTION_TOOLTIP_ENABLE_SOUND, type = "boolean" },
  ["Sound_EnableDSPEffects"] = { prettyName = ENABLE_DSP_EFFECTS, description = OPTION_TOOLTIP_ENABLE_DSP_EFFECTS, type = "boolean" },
  ["Sound_SFXVolume"] = { prettyName = SOUND_VOLUME, description = OPTION_TOOLTIP_SOUND_VOLUME, type = "number" },
  ["Sound_ZoneMusicNoDelay"] = { prettyName = ENABLE_MUSIC_LOOPING, description = OPTION_TOOLTIP_ENABLE_MUSIC_LOOPING, type = "boolean" },
  ["Sound_EnableDialog"] = { prettyName = ENABLE_DIALOG, description = OPTION_TOOLTIP_ENABLE_DIALOG, type = "boolean" },
  ["Sound_EnableSoundWhenGameIsInBG"] = { prettyName = ENABLE_BGSOUND, description = OPTION_TOOLTIP_ENABLE_BGSOUND, type = "boolean" },
  ["Sound_EnableEmoteSounds"] = { prettyName = ENABLE_EMOTE_SOUNDS, description = OPTION_TOOLTIP_ENABLE_EMOTE_SOUNDS, type = "boolean" },
  ["Sound_EnableAmbience"] = { prettyName = ENABLE_AMBIENCE, description = OPTION_TOOLTIP_ENABLE_AMBIENCE, type = "boolean" },
  ["Sound_DialogVolume"] = { prettyName = DIALOG_VOLUME, description = OPTION_TOOLTIP_DIALOG_VOLUME, type = "number" },
  ["Sound_EnablePetBattleMusic"] = { prettyName = ENABLE_PET_BATTLE_MUSIC, description = OPTION_TOOLTIP_ENABLE_PET_BATTLE_MUSIC, type = "boolean" },
  ["Sound_MusicVolume"] = { prettyName = MUSIC_VOLUME, description = OPTION_TOOLTIP_MUSIC_VOLUME, type = "number" },
  ["Sound_EnableReverb"] = { prettyName = ENABLE_REVERB, description = OPTION_TOOLTIP_ENABLE_REVERB, type = "boolean" },
  ["Sound_MasterVolume"] = { prettyName = MASTER_VOLUME, description = OPTION_TOOLTIP_MASTER_VOLUME, type = "number" },
  ["Sound_EnableMusic"] = { prettyName = ENABLE_MUSIC, description = OPTION_TOOLTIP_ENABLE_MUSIC, type = "boolean" },
  ["Sound_AmbienceVolume"] = { prettyName = AMBIENCE_VOLUME, description = OPTION_TOOLTIP_AMBIENCE_VOLUME, type = "number" },
  ["Sound_EnableErrorSpeech"] = { prettyName = ENABLE_ERROR_SPEECH, description = OPTION_TOOLTIP_ENABLE_ERROR_SPEECH, type = "boolean" },
  ["Sound_EnableSFX"] = { prettyName = ENABLE_SOUNDFX, description = OPTION_TOOLTIP_ENABLE_SOUNDFX, type = "boolean" },
  ["Sound_ListenerAtCharacter"] = { prettyName = ENABLE_SOUND_AT_CHARACTER, description = OPTION_TOOLTIP_ENABLE_SOUND_AT_CHARACTER, type = "boolean" },
  ["Sound_EnablePetSounds"] = { prettyName = ENABLE_PET_SOUNDS, description = OPTION_TOOLTIP_ENABLE_PET_SOUNDS, type = "boolean" },
  ["Sound_EnablePositionalLowPassFilter"] = { prettyName = ENABLE_SOFTWARE_HRTF, description = OPTION_TOOLTIP_ENABLE_SOFTWARE_HRTF, type = "boolean" },

  ["showTargetOfTarget"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_OF_TARGET, type = "boolean" },
  ["showTutorials"] = { prettyName = SHOW_TUTORIALS, description = OPTION_TOOLTIP_SHOW_TUTORIALS, type = "boolean" },
  ["lossOfControl"] = { prettyName = nil, description = OPTION_TOOLTIP_LOSS_OF_CONTROL, type = "boolean" },
  ["blockChannelInvites"] = { prettyName = nil, description = OPTION_TOOLTIP_BLOCK_CHAT_CHANNEL_INVITE, type = "boolean" },
  ["showTargetCastbar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_CASTBAR, type = "boolean" },
  ["enablePetBattleCombatText"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_PETBATTLE_COMBAT, type = "boolean" },
  ["colorblindMode"] = { prettyName = nil, description = OPTION_TOOLTIP_USE_COLORBLIND_MODE, type = "boolean" },
  ["useIPv6"] = { prettyName = USEIPV6, description = OPTION_TOOLTIP_USEIPV6, type = "boolean" },
  ["interactOnLeftClick"] = { prettyName = INTERACT_ON_LEFT_CLICK_TEXT, description = OPTION_TOOLTIP_INTERACT_ON_LEFT_CLICK, type = "boolean" },
  ["enableMovePad"] = { prettyName = MOVE_PAD, description = OPTION_TOOLTIP_MOVE_PAD, type = "boolean" },
  ["colorblindSimulator"] = { prettyName = nil, description = OPTION_TOOLTIP_COLORBLIND_FILTER, type = "boolean" },

  ["noBuffDebuffFilterOnTarget"] = { prettyName = "目標上無增益減益過濾器", description = "不要過濾目標上的任何增益或減益", type = "boolean" },
  ["showHonorAsExperience"] = { prettyName = nil, description = "將榮譽條顯示為常規經驗條，以代替聲望", type = "boolean" },
  -- 標籤目標選擇
  ["TargetNearestUseNew"] = { prettyName = nil, description = "使用7.2“最近目標”功能", type = "boolean" },
  --["TargetPriorityAllowAnyOnScreen"] = { prettyName = nil, description = "如果設定，並且沒有100％正確的目標可用，則允許選擇任何有效的範圍內目標（2 = 也包括範圍外）", type = "boolean" },
  ["TargetPriorityCombatLock"] = {
    prettyName = nil,
    description = "1=從戰鬥中目標開始時鎖定到戰鬥中目標。2=進一步限制與玩家戰鬥。",
    type = "boolean",
  },
  ["TargetPriorityCombatLockHighlight"] = {
    prettyName = nil,
    description = "1=從戰鬥中目標開始時鎖定到戰鬥中目標。2=進一步限制與玩家戰鬥。（在按住目標時）",
    type = "boolean",
  },
  --["TargetPriorityHoldHighlightDelay"] = { prettyName = nil, description = "按住按鈕時優先目標高亮顯示開始前的延遲（以毫秒為單位）", type = "number" },
  --["TargetPriorityIncludeBehind"] = { prettyName = nil, description = "如果設定，則在優先目標選擇中包括玩家身後的目標", type = "boolean" },
  ["TargetPriorityPvp"] = {
    prettyName = nil,
    description = "在PvP中，優先考慮玩家和重要的PvP目標（2 = 所有PvP目標，3 = 僅限玩家）",
    type = "boolean",
  },
  --["TargetPriorityPvpLock"] = { prettyName = nil, description = "從PvP目標開始時鎖定到重要的PvP目標。", type = "boolean" },
  --["TargetPriorityPvpLockHighlight"] = { prettyName = nil, description = "在PvP中從玩家目標開始時鎖定到玩家。（在按住目標時）", type = "boolean" },
  --["TargetPriorityValueBank"] = { prettyName = nil, description = "選擇用於計算目標優先順序的評分值庫", type = "boolean" },
  ["TargetPriorityCombatLockContextualRelaxation"] = {
    prettyName = nil,
    description = "1=根據狀況啟用放寬戰鬥鎖定（例如，前面沒有戰鬥中目標）",
    type = "number",
  },

  ["unitClutter"] = { prettyName = nil, description = "啟用/停用單位雜亂", type = "boolean" },
  ["unitClutterInstancesOnly"] = { prettyName = nil, description = "是否僅在副本中使用單位雜亂（0 或 1）", type = "boolean" },
  ["unitClutterPlayerThreshold"] = { prettyName = nil, description = "必須在附近觸發單位雜亂的玩家數量", type = "boolean" },

  ["comboPointLocation"] = { prettyName = nil, description = "連擊點在介面的位置。1=目標，2=自身", type = "number" },
  ["doNotFlashLowHealthWarning"] = { prettyName = nil, description = "當您的生命值過低時，不要將螢幕閃爍為紅色。", type = "boolean" },
  ["findYourselfAnywhere"] = { prettyName = nil, description = "始終高亮顯示您的角色", type = "boolean" },
  ["findYourselfAnywhereOnlyInCombat"] = { prettyName = nil, description = "僅在戰鬥中高亮顯示您的角色", type = "boolean" },
  ["findYourselfInBG"] = { prettyName = nil, description = "始終在戰場中高亮顯示您的角色", type = "boolean" },
  ["findYourselfInBGOnlyInCombat"] = { prettyName = "僅在戰鬥中在戰場中高亮顯示您的角色", description = "", type = "boolean" },
  ["findYourselfInRaid"] = { prettyName = nil, description = "始終在團隊副本中高亮顯示您的角色", type = "boolean" },
  ["findYourselfInRaidOnlyInCombat"] = { prettyName = nil, description = "僅在戰鬥中在團隊副本中高亮顯示您的角色", type = "boolean" },
  ["findYourselfMode"] = { prettyName = nil, description = "高亮顯示您的角色。0 = 圓圈，1 = 圓圈和輪廓", type = "boolean" },
  ["flashErrorMessageRepeats"] = { prettyName = nil, description = "如果觸發了相同的消息，則將螢幕中央的紅色錯誤文本閃爍顯示。", type = "boolean" },
  -- 浮動戰鬥文字
  ["enableFloatingCombatText"] = { prettyName = SHOW_COMBAT_TEXT_TEXT, description = OPTION_TOOLTIP_SHOW_COMBAT_TEXT, type = "boolean" },
  ["floatingCombatTextAllSpellMechanics"] = { prettyName = nil, description = "", type = "boolean" },
  ["floatingCombatTextAuras"] = { prettyName = COMBAT_TEXT_SHOW_AURAS_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_AURAS, type = "boolean" },
  ["floatingCombatTextCombatDamage"] = { prettyName = SHOW_DAMAGE_TEXT_TEXT or SHOW_DAMAGE_TEXT, description = OPTION_TOOLTIP_SHOW_DAMAGE, type = "boolean" },
  ["floatingCombatTextCombatDamageAllAutos"] = { prettyName = nil, description = "顯示所有自動攻擊數字，而不是隱藏非事件數字", type = "boolean" },
  ["floatingCombatTextCombatDamageDirectionalOffset"] = { prettyName = nil, description = "方向性傷害數字開始時要偏移的量", type = "boolean" },
  ["floatingCombatTextCombatDamageDirectionalScale"] = {
    prettyName = "方向性縮放",
    description = "方向性傷害數字移動縮放（停用=無方向性數字）",
    type = "boolean",
  },
  ["floatingCombatTextCombatHealing"] = { prettyName = SHOW_COMBAT_HEALING_TEXT or SHOW_COMBAT_HEALING, description = OPTION_TOOLTIP_SHOW_COMBAT_HEALING, type = "boolean" },
  ["floatingCombatTextCombatHealingAbsorbSelf"] = {
    prettyName = SHOW_COMBAT_HEALING_ABSORB_SELF .. "（自身）",
    description = OPTION_TOOLTIP_SHOW_COMBAT_HEALING_ABSORB_SELF,
    type = "boolean",
  },
  ["floatingCombatTextCombatHealingAbsorbTarget"] = {
    prettyName = SHOW_COMBAT_HEALING_ABSORB_TARGET .. "（目標）",
    description = OPTION_TOOLTIP_SHOW_COMBAT_HEALING_ABSORB_TARGET,
    type = "boolean",
  },
  ["floatingCombatTextCombatLogPeriodicSpells"] = {
    prettyName = LOG_PERIODIC_EFFECTS_TEXT or LOG_PERIODIC_EFFECTS,
    description = OPTION_TOOLTIP_LOG_PERIODIC_EFFECTS,
    type = "boolean",
  },
  ["floatingCombatTextCombatState"] = { prettyName = COMBAT_TEXT_SHOW_COMBAT_STATE_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_COMBAT_STATE, type = "boolean" },
  ["floatingCombatTextComboPoints"] = { prettyName = COMBAT_TEXT_SHOW_COMBO_POINTS_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_COMBO_POINTS, type = "boolean" },
  ["floatingCombatTextDamageReduction"] = { prettyName = COMBAT_TEXT_SHOW_RESISTANCES_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_RESISTANCES, type = "boolean" },
  ["floatingCombatTextDodgeParryMiss"] = { prettyName = COMBAT_TEXT_SHOW_DODGE_PARRY_MISS_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_DODGE_PARRY_MISS, type = "boolean" },
  ["floatingCombatTextEnergyGains"] = {
    prettyName = COMBAT_TEXT_SHOW_ENERGIZE_TEXT .. " & " .. COMBAT_TEXT_SHOW_COMBO_POINTS_TEXT,
    description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_ENERGIZE,
    type = "boolean",
  },
  ["floatingCombatTextFloatMode"] = { prettyName = COMBAT_TEXT_FLOAT_MODE_LABEL, description = OPTION_TOOLTIP_COMBAT_TEXT_MODE, type = "number" },
  ["floatingCombatTextFriendlyHealers"] = { prettyName = COMBAT_TEXT_SHOW_FRIENDLY_NAMES_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_FRIENDLY_NAMES, type = "boolean" },
  ["floatingCombatTextHonorGains"] = { prettyName = COMBAT_TEXT_SHOW_HONOR_GAINED_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_HONOR_GAINED, type = "boolean" },
  ["floatingCombatTextLowManaHealth"] = { prettyName = COMBAT_TEXT_SHOW_LOW_HEALTH_MANA_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_LOW_HEALTH_MANA, type = "boolean" },
  ["floatingCombatTextPeriodicEnergyGains"] = {
    prettyName = COMBAT_TEXT_SHOW_PERIODIC_ENERGIZE_TEXT,
    description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_PERIODIC_ENERGIZE,
    type = "boolean",
  },
  ["floatingCombatTextPetMeleeDamage"] = {
    prettyName = SHOW_PET_MELEE_DAMAGE_TEXT or SHOW_PET_MELEE_DAMAGE,
    description = OPTION_TOOLTIP_SHOW_PET_MELEE_DAMAGE,
    type = "boolean",
  },
  ["floatingCombatTextPetSpellDamage"] = { prettyName = SHOW_PET_SPELL_DAMAGE, description = "在世界中顯示寵物法術傷害", type = "boolean" },
  ["floatingCombatTextReactives"] = { prettyName = COMBAT_TEXT_SHOW_REACTIVES_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_REACTIVES, type = "boolean" },
  ["floatingCombatTextRepChanges"] = { prettyName = COMBAT_TEXT_SHOW_REPUTATION_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_REPUTATION, type = "boolean" },
  ["floatingCombatTextSpellMechanics"] = { prettyName = SHOW_TARGET_EFFECTS, description = OPTION_TOOLTIP_SHOW_TARGET_EFFECTS, type = "boolean" },
  ["floatingCombatTextSpellMechanicsOther"] = { prettyName = SHOW_OTHER_TARGET_EFFECTS, description = OPTION_TOOLTIP_SHOW_OTHER_TARGET_EFFECTS, type = "boolean" },
  -- 狀態文字
  ["statusText"] = { prettyName = STATUS_TEXT, description = "狀態條是否顯示數值的健康/法力值", type = "boolean" },
  ["statusTextDisplay"] = { prettyName = STATUS_TEXT, description = OPTION_TOOLTIP_STATUS_TEXT_DISPLAY, type = "boolean" },
  ["playerStatusText"] = { prettyName = STATUS_TEXT_PLAYER, description = OPTION_TOOLTIP_STATUS_TEXT_PLAYER, type = "boolean" }, -- 已移除
  ["petStatusText"] = { prettyName = STATUS_TEXT_PET, description = OPTION_TOOLTIP_STATUS_TEXT_PET, type = "boolean" }, -- 已移除
  ["partyStatusText"] = { prettyName = STATUS_TEXT_PARTY, description = OPTION_TOOLTIP_STATUS_TEXT_PARTY, type = "boolean" }, -- 已移除
  ["targetStatusText"] = { prettyName = STATUS_TEXT_TARGET, description = OPTION_TOOLTIP_STATUS_TEXT_TARGET, type = "boolean" }, -- 已移除
  ["alternateResourceText"] = { prettyName = ALTERNATE_RESOURCE_TEXT, description = OPTION_TOOLTIP_ALTERNATE_RESOURCE, type = "boolean" }, -- 已移除
  ["xpBarText"] = { prettyName = XP_BAR_TEXT, description = OPTION_TOOLTIP_XP_BAR, type = "boolean" },

  ["violenceLevel"] = { prettyName = "暴力級別", description = "設定遊戲的暴力級別", type = "number" },
  ["ffxGlow"] = { prettyName = "特效發光", description = "全螢幕發光效果", type = "boolean" },
  ["ffxNether"] = { prettyName = "特效虛空", description = "全螢幕虛空/發光效果", type = "boolean" },
  ["releaseUITextures"] = { prettyName = "釋放介面材質", description = "預設情況下釋放隱藏的介面材質", type = "boolean" },
  ["alwaysCompareItems"] = { prettyName = "始終比較物品", description = "始終顯示物品比較浮動提示資訊", type = "boolean" },
  ["showSpenderFeedback"] = { prettyName = "顯示消耗反饋", description = "顯示/隱藏在資源條中消耗怒氣/法力等之後的閃光。", type = "boolean" },
  -- 失控UI
  ["lossOfControlFull"] = {
    prettyName = "失控：完整",
    description = "設定失控警報的類型。（0 = 關閉，1 = 僅警報，2 = 顯示完整持續時間）",
    type = "number",
  },
  ["lossOfControlSilence"] = {
    prettyName = "失控：沉默",
    description = "設定失控警報的類型。（0 = 關閉，1 = 僅警報，2 = 顯示完整持續時間）",
    type = "number",
  },
  ["lossOfControlInterrupt"] = {
    prettyName = "失控：打斷",
    description = "設定失控警報的類型。（0 = 關閉，1 = 僅警報，2 = 顯示完整持續時間）",
    type = "number",
  },
  ["lossOfControlDisarm"] = {
    prettyName = "失控：繳械",
    description = "設定失控警報的類型。（0 = 關閉，1 = 僅警報，2 = 顯示完整持續時間）",
    type = "number",
  },
  ["lossOfControlRoot"] = {
    prettyName = "失控：定身",
    description = "設定失控警報的類型。（0 = 關閉，1 = 僅警報，2 = 顯示完整持續時間）",
    type = "number",
  },
  ["synchronizeMacros"] = { prettyName = "同步巨集", description = "切換開啟/關閉與伺服器同步巨集", type = "boolean" },
  ["synchronizeConfig"] = { prettyName = "同步設定", description = "切換開啟/關閉與伺服器同步設定", type = "boolean" },
  ["cursorsizepreferred"] = { prettyName = "游標大小", description = "0 = 32x32, 1 = 48x48, 2 = 64x64, -1 = 自動偵測", type = "number" },
  ["ffxDeath"] = { prettyName = "特效死亡", description = "啟用全螢幕死亡效果", type = "boolean" },
  ["WorldTextScale"] = { prettyName = "世界文字縮放", description = "世界中傷害數字，經驗值獲取，神器能量獲取等的縮放比例", type = "number" },

  -- 7.1.5 dump (1/16/17)
  ["BrowserNavigateLog"] = { description = "啟用瀏覽器導航請求的日誌記錄（需要/reload）" },
  --["CACHE-WGOB-GameObjectsHotfixCount"] = {},
  --["CACHE-WGOB-GameObjectsRecordCount"] = {},
  --["CACHE-WQST-QuestObjectiveHotfixCount"] = {},
  --["CACHE-WQST-QuestObjectiveRecordCount"] = {},
  --["CACHE-WQST-QuestObjectiveXEffectHotfixCount"] = {},
  --["CACHE-WQST-QuestObjectiveXEffectRecordCount"] = {},
  --["CACHE-WQST-QuestV2HotfixCount"] = {},
  --["CACHE-WQST-QuestV2RecordCount"] = {},
  ["ChatMusicVolume"] = {},
  ["CombatHealingAbsorbSelf"] = {},
  ["DepthBasedOpacity"] = {},
  ["DesktopGamma"] = {},
  -- ["EJDungeonDifficulty"] = { description = "儲存上次在副本日誌中查看的副本難度" },
  -- ["EJLootClass"] = { description = "儲存上次在副本日誌中過濾掉戰利品的職業" },
  -- ["EJLootSpec"] = { description = "儲存上次在副本日誌中過濾掉戰利品的專精" },
  -- ["EJRaidDifficulty"] = { description = "儲存上次在副本日誌中查看的團隊副本難度" },
  ["EmitterCombatrange"] = { description = "在戰鬥中停止肩膀/武器發射的範圍" },
  -- ["ErrorFilter"] = {},
  -- ["ErrorLevelMax"] = {},
  -- ["ErrorLevelMin"] = {},
  -- ["Errors"] = {},
  ["FootstepSounds"] = { description = "播放腳步聲" },
  ["Gamma"] = {},
  ["LodLiquid"] = { description = "使用lod液體渲染" },
  ["M2ForceAdditiveParticleSort"] = { description = "強制所有粒子都按加法排序" },
  ["M2UseInstancing"] = { description = "使用硬體實例化" },
  ["M2UseLOD"] = { description = "使用模型lod" },
  ["M2UseThreads"] = { description = "多線程模型動畫" },
  ["MSAAAlphaTest"] = { description = "為alpha測試的幾何啟用MSAA" },
  ["MSAAQuality"] = { description = "多重採樣抗鋸齒品質" },
  ["MaxObservedPetBattles"] = { description = "觀察到的寵物對戰的最大數量" },
  ["NameplatePersonalHideDelayAlpha"] = {
    description = "確定在沒有滿足任何可見性條件後（在NameplatePersonalHideDelaySeconds指定的時間段內）個人名條的Alpha值。",
  },
  ["NonEmitterCombatRange"] = { description = "在戰鬥外停止肩膀/武器發射的範圍" },
  ["ObjectSelectionCircle"] = {},
  ["OutlineEngineMode"] = {},
  -- ["Outline"] = { description="輪廓模式" }, -- 不知道除了在設定時讓你閃爍之外，這有什麼作用
  ["POIShiftComplete"] = {},
  -- ["PraiseTheSun"] = {},
  ["PushToTalkButton"] = { description = "按下說話按鈕的字符串表示形式。" },
  ["RAIDDepthBasedOpacity"] = {},
  ["RAIDLightMode"] = {},
  ["RAIDOutlineEngineMode"] = {},
  ["RAIDSSAO"] = {},
  ["RAIDSSAOBlur"] = {},
  ["RAIDWaterDetail"] = {},
  ["RAIDcomponentTextureLevel"] = {},
  ["RAIDenvironmentDetail"] = {},
  ["RAIDfarclip"] = {},
  ["RAIDgraphicsQuality"] = {},
  ["RAIDgroundEffectDensity"] = {},
  ["RAIDgroundEffectDist"] = {},
  ["RAIDgroundEffectFade"] = { description = "團隊副本地面效果淡化" },
  ["RAIDhorizonStart"] = { description = "團隊副本地平線開始距離" },
  ["RAIDlodObjectCullDist"] = {},
  ["RAIDlodObjectCullSize"] = {},
  ["RAIDlodObjectMinSize"] = {},
  ["RAIDlodObjectFadeScale"] = {},
  ["RAIDparticleDensity"] = {},
  ["RAIDparticleMTDensity"] = {},
  ["RAIDprojectedTextures"] = {},
  ["RAIDreflectionMode"] = {},
  ["RAIDrefraction"] = {},
  ["RAIDrippleDetail"] = {},
  ["RAIDsettingsEnabled"] = { description = "團隊副本圖形設定可用" },
  ["RAIDsettingsInit"] = {},
  ["RAIDshadowMode"] = {},
  ["RAIDshadowSoft"] = {},
  ["RAIDshadowTextureSize"] = {},
  ["RAIDsunShafts"] = {},
  ["RAIDterrainLodDist"] = {},
  ["RAIDterrainMipLevel"] = {},
  ["RAIDterrainTextureLod"] = {},
  ["RAIDtextureFilteringMode"] = {},
  ["RAIDweatherDensity"] = {},
  ["RAIDwmoLodDist"] = {},
  ["RAIDworldBaseMip"] = {},
  ["RenderScale"] = { description = "渲染比例（用於超級採樣或欠採樣）" },
  ["ResampleQuality"] = { description = "重新採樣品質" },
  ["SSAO"] = {},
  ["SSAOBlur"] = {},
  ["SSAODistance"] = { description = "SSAO距離" },
  ["SkyCloudLOD"] = {},
  ["SoundPerf_VariationCap"] = { description = "限制聲音套件的變化，以減少32位計算機上的記憶體使用量和磁盤抖動" },
  ["SoundUseNewBusSystem"] = { description = "使用新的匯流排結構或回退到舊的結構" },
  ["Sound_DSPBufferSize"] = { description = "聲音緩衝區大小，預設為0" },
  ["Sound_EnableArmorFoleySoundForOthers"] = {},
  ["Sound_EnableArmorFoleySoundForSelf"] = {},
  ["Sound_EnableMixMode2"] = {},
  ["Sound_EnableMode2"] = {},
  ["Sound_MaxCacheSizeInBytes"] = { description = "最大緩存大小（以字節為單位）" },
  ["Sound_MaxCacheableSizeInBytes"] = { description = "將被緩存的最大聲音大小（以字節為單位），更大的文件將被串流" },
  ["Sound_NumChannels"] = {},
  ["Sound_OutputDriverIndex"] = {},
  ["Sound_OutputDriverName"] = {},
  ["Sound_OutputSampleRate"] = { description = "輸出採樣率" },
  ["Sound_VoiceChatInputDriverIndex"] = {},
  ["Sound_VoiceChatInputDriverName"] = {},
  ["Sound_VoiceChatOutputDriverIndex"] = {},
  ["Sound_VoiceChatOutputDriverName"] = {},
  ["SplineOpt"] = { description = "切換使用樣條線coll優化" },
  ["StartTalkingDelay"] = {},
  ["StartTalkingTime"] = {},
  ["StopTalkingDelay"] = {},
  ["StopTalkingTime"] = {},
  ["TargetPriorityValueBank"] = { description = "選擇活動目標值庫以計算目標優先級順序" },
  ["VoiceChatMode"] = { description = "按下說話(0) 或語音偵測(1)" },
  ["VoiceChatSelfMute"] = { description = "關閉您的說話能力。" },
  ["WorldTextCritScreenY"] = {},
  ["WorldTextGravity"] = {},
  ["WorldTextNonRandomZ"] = {},
  ["WorldTextRampDuration"] = {},
  ["WorldTextRampPow"] = {},
  ["WorldTextRampPowCrit"] = {},
  ["WorldTextRandomXY"] = {},
  ["WorldTextRandomZMax"] = {},
  ["WorldTextRandomZMin"] = {},
  ["WorldTextScreenY"] = {},
  ["WorldTextStartPosRandomness"] = {},
  -- ["accounttype"] = {},
  -- ["actionedAdventureJournalEntries"] = { description = "用戶對哪些標記有ADVENTURE_JOURNAL_HIDE_AFTER_ACTION的冒險日誌條目採取了行動" },
  -- ["activeCUFProfile"] = { description = "最後一個活動的CUF配置文件。" },
  -- ["addFriendInfoShown"] = { description = "已顯示添加好友的資訊" },
  -- ["advJournalLastOpened"] = { description = "冒險日誌上次打開的時間" },
  -- ["agentUID"] = { description = "Battle.net提供的要傳遞給Agent的UID" },
  ["allowCompareWithToggle"] = {},
  ["allowD3D9BackingStore"] = { description = "允許D3D9進行紋理備份以減少載入時間並增加記憶體不足崩潰的可能性" },
  ["animFrameSkipLOD"] = { description = "動畫將在遠處跳幀" },
  ["asyncHandlerTimeout"] = { description = "引擎選項：異步讀取主線程超時" },
  ["asyncThreadSleep"] = { description = "引擎選項：異步讀取線程休眠" },
  ["auctionDisplayOnCharacter"] = { description = "在試衣間紙娃娃上顯示拍賣物品" },
  ["audioLocale"] = { description = "設定音頻內容的遊戲區域設定" },
  ["autoCompleteResortNamesOnRecency"] = { description = "在自動完成列表中顯示您最近與之交談過的人。" },
  ["autoCompleteUseContext"] = { description = "例如，當您鍵入/gpromote時，系統只會顯示您公會中的人員。名稱也永遠不會被刪除。" },
  ["autoCompleteWhenEditingFromCenter"] = { description = "如果您通過在中心間距字符來編輯名稱，將會出現更智能的自動完成。" },
  ["autoDismount"] = { description = "在需要時自動下馬" },
  -- ["autoFilledMultiCastSlots"] = { description = "保存多播插槽是否已自動填充的位字段。" },
  -- ["autoQuestPopUps"] = { description = "保存當前彈出的自動獲取或完成的任務。" },
  ["autoStand"] = { description = "在需要時自動站立" },
  ["autoUnshift"] = { description = "在需要時自動離開變形形態" },
  ["autojoinBGVoice"] = { description = "自動加入戰場聊天中的語音會話" },
  ["autojoinPartyVoice"] = { description = "自動加入隊伍/團隊聊天中的語音會話" },
  -- ["bloatTest"] = {},
  -- ["bloatnameplates"] = {},
  -- ["bloatthreat"] = {},
  ["bodyQuota"] = { description = "一次看到的最多的組件實體數量" },
  ["breakUpLargeNumbers"] = { description = "切換在大數字中使用逗號" },
  ["bspcache"] = { description = "BSP節點緩存" },
  ["calendarShowBattlegrounds"] = { description = "戰場節日是否應顯示在行事曆中" },
  ["calendarShowDarkmoon"] = { description = "暗月馬戲團節日是否應顯示在行事曆中" },
  ["calendarShowLockouts"] = { description = "團隊副本鎖定是否應顯示在行事曆中" },
  ["calendarShowResets"] = { description = "團隊副本重置是否應顯示在行事曆中" },
  ["calendarShowWeeklyHolidays"] = { description = "每週節日是否應顯示在行事曆中" },
  ["cameraCustomViewSmoothing"] = {},
  ["cameraDistanceMax"] = {},
  ["cameraDistanceMaxFactor"] = {},
  ["cameraDistanceRateMult"] = {},
  ["cameraDive"] = {},
  ["cameraHeightIgnoreStandState"] = {},
  ["cameraPitchSmoothMax"] = {},
  ["cameraPitchSmoothMin"] = {},
  ["cameraPivotDXMax"] = {},
  ["cameraPivotDYMin"] = {},
  -- ["cameraSavedDistance"] = {},
  -- ["cameraSavedPetBattleDistance"] = {},
  -- ["cameraSavedPitch"] = {},
  -- ["cameraSavedVehicleDistance"] = {},
  -- ["cameraView"] = {},
  ["cameraYawSmoothMax"] = {},
  ["cameraYawSmoothMin"] = {},
  ["cameraZDamp"] = {},
  ["cameraZoomSpeed"] = {},
  -- ["characterFrameCollapsed"] = {},
  ["chatStyle"] = { description = '聊天框的編輯框樣式。有效值："classic", "im"' },
  ["checkAddonVersion"] = {},
  ["cloakFixEnabled"] = {},
  -- ["closedInfoFrames"] = { description = "用戶已確認的幫助框的位字段" },
  ["colorChatNamesByClass"] = { description = "如果啟用，聊天中玩家的名稱將根據其職業著色。" },
  ["combatLogReducedRetentionTime"] = { description = "當記憶體不足時保留戰鬥日誌條目的最長持續時間（以秒為單位）" },
  ["combatLogRetentionTime"] = { description = "保留戰鬥日誌條目的最長持續時間（以秒為單位）" },
  ["combatTextFloatMode"] = {},
  ["componentCompress"] = { description = "角色組件紋理壓縮" },
  ["componentEmissive"] = { description = "角色組件不發光/發光" },
  ["componentSpecular"] = { description = "7.0.3版本已停用 - 角色組件鏡面高光" },
  ["componentTexCacheSize"] = { description = "角色組件紋理緩存大小（以MB為單位）" },
  ["componentTexLoadLimit"] = { description = "每幀角色組件紋理載入限制" },
  ["componentTextureLevel"] = {},
  ["componentThread"] = { description = "多線程角色組件處理" },
  -- ["currencyCategoriesCollapsed"] = { description = "用於跟踪已折疊貨幣類別的內部CVar。" },
  -- ["currencyTokensBackpack1"] = { description = "背包上顯示的貨幣代幣類型。" },
  -- ["currencyTokensBackpack2"] = { description = "背包上顯示的貨幣代幣類型。" },
  -- ["currencyTokensUnused1"] = { description = "標記為未使用的貨幣代幣類型。" },
  -- ["currencyTokensUnused2"] = { description = "標記為未使用的貨幣代幣類型。" },
  ["daltonize"] = { description = "嘗試校正色盲（將colorblindSimulator設定為色盲類型）" },
  -- ["dangerousShipyardMissionWarningAlreadyShown"] = { description = "布爾值，指示是否已顯示造船廠的危險任務警告" },
  -- ["debugSoundPlayerSpellsOnlyOnPlayerBus"] = {},
  ["detailDoodadInstancing"] = { description = "細節doodad實例化" },
  ["digSites"] = { description = "如果啟用，將使用考古挖掘場系統。" },
  ["disableAutoRealmSelect"] = { description = "停用在登錄時自動選擇伺服器" },
  ["displayWorldPVPObjectives"] = { description = "是否顯示世界PvP目標" },
  -- ["displayedRAFFriendInfo"] = { description = "儲存我們是否已經告訴過被招募的人有關其新BattleTag好友的資訊" },
  ["dontShowEquipmentSetsOnItems"] = { description = "不顯示物品關聯的裝備套裝" },
  ["doodadLodDist"] = { description = "Doodad細節級別距離" },
  ["doodadUnloadDist"] = {},
  ["enableBGDL"] = { description = "後台下載（在異步網絡線程上）已啟用" },
  -- ["enableCombatText"] = {},
  ["enablePVPNotifyAFK"] = { description = "關閉AFK通知系統的功能" },
  ["enablePetBattleFloatingCombatText"] = { description = "是否顯示寵物對戰的浮動戰鬥文字" },
  -- ["engineSurvey"] = {},
  ["enterWorld"] = {},
  ["entityLodDist"] = { description = "實體細節級別距離" },
  ["environmentDetail"] = {},
  ["expandUpgradePanel"] = {},
  ["farclip"] = {},
  ["fctCombatState"] = {},
  -- ["fctFriendlyHealers"] = {},
  ["ffxAntiAliasingMode"] = { description = "抗鋸齒模式" },
  ["ffxRectangle"] = { description = "對全屏效果使用矩形紋理" },
  -- ["fla ggedTutorials"] = { description = "用於按順序保存已完成教程的內部cvar" },
  ["flightAngleLookAhead"] = { description = "啟用飛行時更動態的姿態調整" },
  -- ["floatingCombatTextCombatDamageStyle"] = { description = "不再使用" },
  ["forceEnglishNames"] = {},
  ["forceLODCheck"] = { description = "如果啟用，我們將跳過檢查DBC的LOD計數，並且每個m2都會掃描文件夾以查找皮膚配置文件" },
  -- ["friendInvitesCollapsed"] = { description = "好友邀請是否在好友列表中隱藏" },
  ["friendsSmallView"] = { description = "是否在好友列表中使用較小的按鈕" },
  ["friendsViewButtons"] = { description = "是否顯示好友列表視圖按鈕" },
  ["fullDump"] = { description = "當你崩潰時，生成完整的記憶體轉儲" },
  ["gameTip"] = {},
  ["garrisonCompleteTalent"] = {},
  ["garrisonCompleteTalentType"] = {},
  ["graphicsDepthEffects"] = { description = "圖形設定的UI值" },
  ["graphicsEnvironmentDetail"] = {},
  ["graphicsLightingQuality"] = { description = "圖形設定的UI值" },
  ["graphicsLiquidDetail"] = { description = "圖形設定的UI值" },
  ["graphicsOutlineMode"] = { description = "圖形設定的UI值" },
  ["graphicsParticleDensity"] = {},
  ["graphicsProjectedTextures"] = { description = "圖形設定的UI值" },
  ["graphicsQuality"] = {},
  ["graphicsSSAO"] = { description = "圖形設定的UI值" },
  ["graphicsShadowQuality"] = {},
  ["graphicsSunshafts"] = { description = "圖形設定的UI值" },
  ["graphicsTextureFiltering"] = {},
  ["graphicsTextureResolution"] = {},
  ["graphicsViewDistance"] = {},
  ["groundEffectDensity"] = {},
  ["groundEffectDist"] = {},
  ["groundEffectFade"] = { description = "地面效果淡化" },
  -- ["guildNewsFilter"] = { description = "儲存公會新聞過濾器" },
  ["guildRewardsCategory"] = { description = "顯示公會獎勵的類別" },
  ["guildRewardsUsable"] = { description = "僅顯示可用的公會獎勵" },
  -- ["guildRosterView"] = { description = "當前公會名冊顯示模式" },
  ["guildShowOffline"] = { description = "在公會介面中顯示離線公會成員" },
  ["gxAFRDevicesCount"] = { description = "強制設定AFR設備的數量" },
  ["gxAdapter"] = { description = "強制運行指定的適配器索引（-1表示讓客戶端選擇）" },
  -- ["gxApi"] = {},
  ["gxAspect"] = { description = "約束窗口縱橫比" },
  ["gxCursor"] = { description = "切換硬體游標" },
  ["gxDepthResolveHandleCaching"] = { description = "深度解析的目標控制代碼緩存" },
  ["gxFixLag"] = { description = "防止游標延遲" },
  ["gxFullscreenResolution"] = { description = "分辨率" },
  ["gxMaxFrameLatency"] = { description = "CPU可以領先GPU的最大幀數" },
  ["gxMaximize"] = {},
  ["gxMonitor"] = { description = "顯示器" },
  ["gxNewResolution"] = { description = "要設定的分辨率" },
  ["gxPreferWindowedFullscreen"] = { description = "首選哪種全屏模式進行切換" },
  -- ["gxRefresh"] = {},
  ["gxStereoConvergence"] = { description = "設定立體渲染匯聚深度" },
  ["gxStereoEnabled"] = { description = "啟用立體渲染" },
  ["gxStereoSeparation"] = { description = "設定立體渲染分離百分比" },
  ["gxTextureCacheSize"] = { description = "GX紋理緩存大小" },
  ["gxTripleBuffer"] = { description = "三重緩衝" },
  ["gxVSync"] = { description = "垂直同步開啟或關閉" },
  ["gxWindow"] = {},
  ["gxWindowedResolution"] = {},
  -- ["hardTrackedQuests"] = { description = "用於按順序保存硬（用戶手動選擇）跟踪任務的內部cvar" },
  -- ["hardTrackedWorldQuests"] = { description = "用於保存硬跟踪世界任務的內部cvar" },
  ["hbaoBias"] = { description = "HBAO偏差" },
  ["hbaoBlurSharp"] = { description = "HBAO模糊銳度" },
  ["hbaoNormals"] = { description = "將法線用於HBAO" },
  ["hbaoPowerExp"] = { description = "HBAO冪指數" },
  ["hbaoRadius"] = { description = "HBAO半徑" },
  -- ["heirloomCollectedFilters"] = { description = "在傳家寶日誌中應用的收集過濾器的位字段" },
  -- ["heirloomSourceFilters"] = { description = "在傳家寶日誌中應用的來源過濾器的位字段" },
  ["hideAdventureJournalAlerts"] = { description = "隱藏冒險日誌微型按鈕上顯示的警報" },
  ["horizonStart"] = {},
  ["hotReloadModels"] = {
    description = "允許在bin文件夾中檢測到新版本時重新載入活動模型。如果停用此選項，則只有在刪除使用該模型的所有遊戲對象後，才會刷新模型數據",
  },
  ["hwDetect"] = {},
  ["hwPCF"] = { description = "硬體PCF過濾" },
  ["incompleteQuestPriorityThresholdDelta"] = {},
  ["initialRealmListTimeout"] = { description = "在登錄失敗之前等待初始伺服器列表的時間（以秒為單位）" },
  ["installLocale"] = {},
  --["installType"] = {},
  -- ["lastAddonVersion"] = {},
  -- ["lastCharacterIndex"] = {},
  -- ["lastGarrisonMissionTutorial"] = { description = "儲存玩家上次接受的要塞任務教程" },
  -- ["lastReadEULA"] = {},
  -- ["lastReadTOS"] = {},
  -- ["lastReadTerminationWithoutNotice"] = {},
  -- ["lastTalkedToGM"] = { description = "儲存玩家上次與之交談的GM，以防他們在GM聊天窗口打開時重新載入UI。" },
  -- ["lastTransmogOutfitID"] = { description = "上次載入的幻化套裝的SetID" },
  -- ["lastVoidStorageTutorial"] = { description = "儲存玩家上次接受的虛空倉庫教程" },
  ["launchAgent"] = { description = "將此設定為讓客戶端啟動Agent" },
  -- ["lfGuildComment"] = { description = "儲存玩家的尋找公會評論" },
  -- ["lfGuildSettings"] = { description = "尋找公會玩家設定的位字段" },
  -- ["lfdCollapsedHeaders"] = { description = "儲存哪些LFD標題已折疊。" },
  -- ["lfdSelectedDungeons"] = { description = "儲存哪些LFD副本已選中。" },
  ["lfgAutoFill"] = { description = "在尋找隊伍時是否自動添加隊伍成員" },
  ["lfgAutoJoin"] = { description = "在尋找隊伍時是否自動加入隊伍" },
  -- ["lfgListSearchLanguages"] = { description = "一個簡單的位字段，用於我們要搜索的語言。" },
  -- ["lfgSelectedRoles"] = { description = "儲存玩家願意承擔的角色。" },
  ["lightMode"] = {},
  ["locale"] = { description = "設定遊戲區域設定" },
  ["lockedWorldMap"] = { description = "縮小尺寸時世界地圖是否鎖定" },
  ["lodObjectCullDist"] = {},
  ["lodObjectCullSize"] = {},
  ["lodObjectMinSize"] = {},
  ["lodTerrainDiv"] = { description = "地形lod除數" },
  ["mapAnimDuration"] = { description = "alpha動畫的持續時間" },
  ["mapAnimMinAlpha"] = { description = "玩家在世界地圖窗口打開時移動時要設定動畫的alpha值" },
  ["mapAnimStartDelay"] = { description = "alpha動畫的開始延遲" },
  ["mapQuestDifficulty"] = {},
  -- ["maxAnimThreads"] = {},
  ["maxFPS"] = { description = "設定FPS限制" },
  ["maxFPSBk"] = { description = "設定後台FPS限制" },
  ["maxLightCount"] = { description = "要渲染的最大燈光數量" },
  ["maxLightDist"] = { description = "渲染燈光的最遠距離" },
  ["miniWorldMap"] = { description = "世界地圖是否已切換為較小的尺寸" },
  ["minimapAltitudeHintMode"] = { description = "更改小地圖高度差顯示。0=無，1=變暗，2=箭頭" },
  ["minimapInsideZoom"] = { description = "當前室內小地圖縮放級別" },
  ["minimapPortalMax"] = { description = "小地圖要穿越的傳送門的最大數量" },
  -- ["minimapShapeshiftTracking"] = { description = "儲存上一次會話中處於活動狀態的變形特定跟踪法術。" },
  ["minimapShowArchBlobs"] = { description = "儲存是否在小地圖上顯示考古學圖示。" },
  ["minimapShowQuestBlobs"] = { description = "儲存是否在小地圖上顯示任務圖示。" },
  -- ["minimapTrackedInfo"] = {},
  -- ["minimapTrackedInfov2"] = { description = "儲存上一次會話中處於活動狀態的小地圖跟踪。" },
  ["minimapZoom"] = { description = "當前戶外小地圖縮放級別" },
  ["missingTransmogSourceInItemTooltips"] = { description = "是否顯示你是否收集了物品的外觀，但不是來自物品本身" },
  -- ["mountJournalFilters"] = { description = "在坐騎日誌中應用的收集過濾器的位字段" },
  -- ["mountJournalSourceFilters"] = { description = "在坐騎日誌中應用的來源過濾器的位字段" },
  ["mouseInvertYaw"] = {},
  ["mtParticles"] = { description = "粒子頂點的多線程構建" },
  ["nameplateMotionSpeed"] = { description = "控制名條動畫到其目標位置的速率[0.0-1.0]" },
  ["nameplateShowEnemyMinions"] = {},
  ["nameplateShowFriendlyMinions"] = {},
  ["nearclip"] = { description = "近剪切平面距離" },
  -- ["orderHallMissionTutorial"] = { description = "儲存有關玩家看過哪些職業大廳任務教程的資訊" },
  ["outdoorMinAltitudeDistance"] = { description = "當您也在戶外時，戶外物體的最小高度距離，然後才會顯示高度差標記" },
  ["outlineMouseOverFadeDuration"] = {},
  ["outlineSelectionFadeDuration"] = {},
  ["overrideArchive"] = { description = "客戶端是否載入替代數據" },
  ["particleDensity"] = {},
  ["particleMTDensity"] = {},
  ["partyBackgroundOpacity"] = { description = "隊伍背景的不透明度" },
  ["pathSmoothing"] = { description = "NPC將在地面路徑上繞過拐角" },
  -- ["pendingInviteInfoShown"] = { description = "已顯示待處理邀請的資訊" },
  -- ["petJournalFilters"] = { description = "在寵物日誌中應用的收集過濾器的位字段" },
  -- ["petJournalSort"] = { description = "寵物日誌的排序值" },
  -- ["petJournalSourceFilters"] = { description = "在寵物日誌中應用的來源過濾器的位字段" },
  -- ["petJournalTab"] = { description = "儲存上次打開寵物日誌的標籤" },
  -- ["petJournalTypeFilters"] = { description = "在寵物日誌中應用的類型過濾器的位字段" },
  ["physicsLevel"] = { description = "物理世界互動的級別" },
  ["playIntroMovie"] = {},
  --["playerStatLeftDropdown"] = { description = "左側下拉列表中選擇的玩家統計資訊" },
  --["playerStatRightDropdown"] = { description = "右側下拉列表中選擇的玩家統計資訊" },
  -- ["portal"] = { description = "要使用的Battle.net傳送門的名稱" },
  ["predictedHealth"] = { description = "是否在介面中使用預測的健康值" },
  ["preloadLoadingDistObject"] = { description = "載入時對象預先載入距離" },
  ["preloadLoadingDistTerrain"] = { description = "載入時地形預先載入距離" },
  ["preloadPlayerModels"] = { description = "將所有本地種族模型預先載入到記憶體中" },
  ["preloadStreamingDistObject"] = { description = "串流時對象預先載入距離" },
  ["preloadStreamingDistTerrain"] = { description = "串流時地形預先載入距離" },
  ["primaryProfessionsFilter"] = { description = "如果啟用，主職業世界任務圖標將顯示在世界地圖上" },
  ["processAffinityMask"] = { description = "設定WoW可以在哪些核心上執行 - 更改需要重新啟動才能生效" },
  ["projectedTextures"] = {},
  ["pvpBlacklistMaps0"] = { description = "黑名單PVP地圖" },
  ["pvpBlacklistMaps1"] = { description = "黑名單PVP地圖" },
  -- ["pvpSelectedRoles"] = { description = "儲存玩家在戰場中將扮演的角色。" },
  -- ["questLogCollapseFilter"] = {},
  -- ["questLogCollapseHeaderFilter"] = {},
  -- ["questLogOpen"] = { description = "任務日誌是否顯示在窗口化地圖的側面。" },
  ["questPOI"] = { description = "如果啟用，將使用任務POI系統。" },
  ["raidFramesDisplayAggroHighlight"] = { description = "是否在團隊框架上顯示仇恨高亮" },
  ["raidFramesDisplayClassColor"] = { description = "使用職業顏色為團隊框架著色" },
  ["raidFramesDisplayOnlyDispellableDebuffs"] = { description = "是否僅在團隊框架上顯示可驅散的減益效果" },
  ["raidFramesDisplayPowerBars"] = { description = "是否在團隊框架上顯示法力值，怒氣值等" },
  ["raidFramesHealthText"] = { description = "如何在團隊框架上顯示健康文本" },
  ["raidFramesHeight"] = { description = "單個團隊框架的高度" },
  ["raidFramesPosition"] = { description = "團隊框架應放置的位置" },
  ["raidFramesWidth"] = { description = "單個團隊框架的寬度" },
  ["raidGraphicsDepthEffects"] = {},
  ["raidGraphicsEnvironmentDetail"] = {},
  ["raidGraphicsGroundClutter"] = {},
  ["raidGraphicsLightingQuality"] = {},
  ["raidGraphicsLiquidDetail"] = {},
  ["raidGraphicsOutlineMode"] = {},
  ["raidGraphicsParticleDensity"] = {},
  ["raidGraphicsProjectedTextures"] = {},
  ["raidGraphicsSSAO"] = {},
  ["raidGraphicsShadowQuality"] = {},
  ["raidGraphicsSunshafts"] = {},
  ["raidGraphicsTextureFiltering"] = {},
  ["raidGraphicsTextureResolution"] = {},
  ["raidGraphicsViewDistance"] = {},
  ["raidOptionDisplayMainTankAndAssist"] = { description = "是否在團隊框架中顯示主坦克和主協助單位" },
  ["raidOptionDisplayPets"] = { description = "是否在團隊框架上顯示寵物" },
  ["raidOptionIsShown"] = { description = "是否顯示團隊框架" },
  ["raidOptionKeepGroupsTogether"] = { description = "對團隊框架進行分組的方式" },
  ["raidOptionLocked"] = { description = "團隊框架是否鎖定" },
  ["raidOptionShowBorders"] = { description = "在團隊框架周圍顯示邊框。" },
  ["raidOptionSortMode"] = { description = "對團隊框架進行排序的方式" },
  ["raidOrBattleCount"] = {},
  ["rawMouseAccelerationEnable"] = { description = "為原始滑鼠輸入啟用加速" },
  ["rawMouseEnable"] = { description = "啟用原始滑鼠輸入" },
  ["rawMouseRate"] = { description = "原始滑鼠更新速率" },
  ["rawMouseResolution"] = { description = "原始滑鼠分辨率" },
  --["readContest"] = {},
  --["readEULA"] = {},
  --["readScanning"] = {},
  --["readTOS"] = {},
  --["readTerminationWithoutNotice"] = {},
  -- ["realmName"] = {},
  ["reflectionDownscale"] = { description = "反射縮小" },
  ["reflectionMode"] = {},
  ["refraction"] = {},
  ["repositionfrequency"] = {},
  -- ["reputationsCollapsed"] = { description = "在“聲望”標籤中已折疊的聲望類別列表" },
  ["rippleDetail"] = {},
  ["sceneOcclusionEnable"] = { description = "場景軟體遮擋" },
  ["screenshotFormat"] = {},
  ["screenshotQuality"] = {},
  ["scriptProfile"] = { description = "是否啟用腳本分析" },
  ["scriptWarnings"] = { description = "介面是否顯示Lua警告" },
  ["secondaryProfessionsFilter"] = { description = "如果啟用，輔助職業世界任務圖標將顯示在世界地圖上" },
  -- ["seenAsiaCharacterUpgradePopup"] = { description = "已查看免費角色升級彈出窗口（亞洲）" },
  -- ["seenCharacterUpgradePopup"] = {},
  -- ["serverAlert"] = { description = "獲取URL的glue-string標籤" },
  -- ["serviceTypeFilter"] = { description = "要顯示的訓練師服務" },
  ["shadowCull"] = { description = "啟用陰影視錐剔除" },
  ["shadowInstancing"] = { description = "在渲染陰影貼圖時啟用實例化" },
  ["shadowMode"] = {},
  ["shadowScissor"] = { description = "在渲染陰影貼圖時啟用剪刀測試" },
  ["shadowSoft"] = {},
  ["shadowTextureSize"] = {},
  -- ["shipyardMissionTutorialAreaBuff"] = { description = "儲存玩家是否接受了第一個區域增益任務教程" },
  -- ["shipyardMissionTutorialBlockade"] = { description = "儲存玩家是否接受了第一個封鎖任務教程" },
  -- ["shipyardMissionTutorialFirst"] = { description = "儲存玩家是否接受了第一個任務教程" },
  ["showAllEnemyDebuffs"] = {},
  ["showArtifactXPBar"] = { description = "將神器經驗值顯示為優先於聲望" },
  ["showBattlefieldMinimap"] = { description = "是否顯示戰場小地圖" },
  ["showBuilderFeedback"] = { description = "在為建造者/消耗者條構建能量時顯示動畫" },
  ["showErrors"] = {},
  ["showKeyring"] = {},
  ["showNPETutorials"] = { description = "顯示NPE教程" },
  ["showNewbieTips"] = {},
  ["showQuestObjectivesOnMap"] = { description = "在主地圖上顯示任務POI。" },
  ["showQuestTrackingTooltips"] = { description = "在單位和對象浮動提示資訊中顯示任務跟踪資訊" },
  ["showSpectatorTeamCircles"] = { description = "確定在觀看或解說戰爭遊戲時團隊顏色圓圈是否可見" },
  ["showTamers"] = { description = "如果啟用，寵物對戰圖標將顯示在世界地圖上" },
  ["showTimestamps"] = { description = '聊天中時間戳的格式或"none"' },
  -- ["showTokenFrame"] = { description = "已顯示代幣UI" },
  -- ["showTokenFrameHonor"] = { description = "代幣UI已顯示榮譽" },
  -- ["showToolsUI"] = {},
  ["showfootprintparticles"] = { description = "切換腳印粒子的渲染" },
  ["simd"] = { description = "啟用SIMD功能（例如SSE）" },
  ["skipStartGear"] = { description = "我們是否應該在創建角色時顯示新手裝備" },
  ["smoothUnitPhasing"] = { description = "客戶端將嘗試在同一模型的不同階段之間平滑切換。" },
  ["smoothUnitPhasingActorPurgatoryTimeMs"] = { description = "如果客戶端演員顯示已消失，則在釋放它們之前將它們保留在煉獄中的時間（以毫秒為單位）" },
  ["smoothUnitPhasingAliveTimeoutMs"] = { description = "等待活動單位獲取其消失消息的時間（以毫秒為單位）" },
  ["smoothUnitPhasingDestroyedPurgatoryTimeMs"] = { description = "如果單位顯示已銷毀，則在釋放它們之前將它們保留在煉獄中的時間（以毫秒為單位）" },
  ["smoothUnitPhasingDistThreshold"] = { description = "啟用平滑單位相位的距離閾值。" },
  ["smoothUnitPhasingEnableAlive"] = { description = "如果匹配，則使用尚未消失的單位，希望消失消息稍後會出現。" },
  ["smoothUnitPhasingUnseenPurgatoryTimeMs"] = { description = "如果單位顯示只是不可見，則在釋放它們之前將它們保留在煉獄中的時間（以毫秒為單位）。" },
  ["smoothUnitPhasingVehicleExtraTimeoutMs"] = {
    description = "在車輛平滑相位後，釋放車輛之前的額外等待時間（以毫秒為單位）。這允許其乘客也能平滑相位。",
  },
  ["spellBookSort"] = {},
  ["spellClutter"] = { description = "啟用/停用法術雜亂" },
  ["spellClutterDefaultTargetScalar"] = { description = "起始目標標量值（最小0.1）" },
  ["spellClutterHostileScalar"] = { description = "我們應用於敵對生物法術的標量（最小0.001）" },
  ["spellClutterMinSpellCount"] = { description = "目標上最小法術數量，然後我們應用雜亂邏輯（最小0）" },
  ["spellClutterPartySizeScalar"] = { description = "根據隊伍規模與此的差異來縮放目標標量（最小1）" },
  ["spellClutterPlayerScalarMultiplier"] = { description = '以乘法方式增加“有趣”目標上的效果數量（最小0.1）' },
  ["spellClutterRangeConstant"] = { description = "在優先級加倍之前的距離（以碼為單位）（最小1.0）" },
  ["splashScreenBoost"] = { description = "顯示增強啟動畫面ID" },
  ["splashScreenNormal"] = { description = "顯示正常啟動畫面ID" },
  -- ["statCategoriesCollapsed"] = {},
  -- ["statCategoriesCollapsed_2"] = {},
  -- ["statCategoryOrder"] = {},
  -- ["statCategoryOrder_2"] = {},
  ["streamBeams"] = { description = "對光束使用頂點流（Gfx驅動程序解決方法）。0=自動檢測，1=永不流，2=始終流" },
  ["streamStatusMessage"] = { description = "是否在串流內容時顯示狀態消息" },
  ["streamingCameraLookAheadTime"] = { description = "串流的預讀時間。" },
  ["streamingCameraMaxRadius"] = { description = "串流鏡頭的最大半徑。" },
  ["streamingCameraRadius"] = { description = "串流鏡頭的基本半徑。" },
  ["sunShafts"] = {},
  ["superTrackerDist"] = {},
  ["synchronizeBindings"] = {},
  ["synchronizeChatFrames"] = {},
  ["synchronizeSettings"] = { description = "客戶端設定是否應存儲在伺服器上" },
  ["taintLog"] = {},
  -- ["talentFrameShown"] = { description = "已顯示天賦UI" },
  ["talentPointsSpent"] = { description = "玩家已花費天賦點" },
  ["targetOfTargetMode"] = { description = "應顯示目標的目標的條件" },
  ["terrainAlphaBitDepth"] = { description = "地形alpha貼圖位深度" },
  ["terrainHoles"] = { description = "地形孔影響遮擋" },
  ["terrainLodDist"] = {},
  ["terrainMipLevel"] = {},
  ["terrainTextureLod"] = {},
  ["test_cameraDynamicPitch"] = { description = "動態鏡頭" },
  ["test_cameraDynamicPitchBaseFovPad"] = { description = "動態鏡頭" },
  ["test_cameraDynamicPitchBaseFovPadDownScale"] = { description = "動態鏡頭" },
  ["test_cameraDynamicPitchBaseFovPadFlying"] = { description = "動態鏡頭" },
  ["test_cameraDynamicPitchSmartPivotCutoffDist"] = { description = "動態鏡頭" },
  ["test_cameraHeadMovementDeadZone"] = { description = "動態鏡頭" },
  ["test_cameraHeadMovementFirstPersonDampRate"] = { description = "動態鏡頭" },
  ["test_cameraHeadMovementMovingDampRate"] = { description = "動態鏡頭" },
  ["test_cameraHeadMovementMovingStrength"] = { description = "動態鏡頭" },
  ["test_cameraHeadMovementRangeScale"] = { description = "動態鏡頭" },
  ["test_cameraHeadMovementStandingDampRate"] = { description = "動態鏡頭" },
  ["test_cameraHeadMovementStandingStrength"] = { description = "動態鏡頭" },
  ["test_cameraHeadMovementStrength"] = { description = "動態鏡頭" },
  ["test_cameraLockedTargetFocusing"] = { description = "動態鏡頭" },
  ["test_cameraOverShoulder"] = { description = "動態鏡頭" },
  ["test_cameraTargetFocusEnemyEnable"] = { description = "動態鏡頭" },
  ["test_cameraTargetFocusEnemyStrengthPitch"] = { description = "動態鏡頭" },
  ["test_cameraTargetFocusEnemyStrengthYaw"] = { description = "動態鏡頭" },
  ["test_cameraTargetFocusInteractEnable"] = { description = "動態鏡頭" },
  ["test_cameraTargetFocusInteractStrengthPitch"] = { description = "動態鏡頭" },
  ["test_cameraTargetFocusInteractStrengthYaw"] = { description = "動態鏡頭" },
  ["textLocale"] = { description = "設定文本的遊戲區域設定" },
  ["textureFilteringMode"] = {},
  ["threatWarning"] = { description = "是否顯示威脅警告介面（0 = 關閉，1 = 在副本中，2 = 在隊伍/團隊中，3 = 始終）" },
  ["threatWorldText"] = { description = "是否在戰鬥中顯示威脅浮動器" },
  ["timeMgrAlarmEnabled"] = { description = "切換時間管理器的鬧鐘是否響起" },
  ["timeMgrAlarmMessage"] = { description = "時間管理器的鬧鐘消息" },
  ["timeMgrAlarmTime"] = { description = "時間管理器的鬧鐘時間（以分鐘為單位）" },
  ["timeMgrUseLocalTime"] = { description = "切換使用伺服器時間還是系統時間" },
  ["timeMgrUseMilitaryTime"] = { description = "切換顯示12小時制還是24小時制" },
  ["timingMethod"] = { description = "遊戲計時的期望方法" },
  -- ["timingTestError"] = { description = "計時驗證系統報告的錯誤" }, -- 只讀
  -- ["toyBoxCollectedFilters"] = { description = "在玩具箱中應用的收集過濾器的位字段" },
  -- ["toyBoxSourceFilters"] = { description = "在玩具箱中應用的來源過濾器的位字段" },
  -- ["trackedAchievements"] = { description = "用於按順序保存跟踪成就的內部cvar" },
  -- ["trackedQuests"] = { description = "用於按順序保存自動跟踪任務的內部cvar" },
  -- ["trackedWorldQuests"] = { description = "用於保存跟踪世界任務的內部cvar" },
  -- ["trackerFilter"] = {},
  -- ["trackerSorting"] = {},
  ["transmogCurrentSpecOnly"] = { description = "儲存幻化是應用於當前專精還是所有專精" },
  -- ["transmogrifyShowCollected"] = { description = "是否在幻化師處顯示收集的幻化" }, -- 只讀
  -- ["transmogrifyShowUncollected"] = { description = "是否在幻化師處顯示未收集的幻化" }, -- 只讀
  -- ["transmogrifySourceFilters"] = { description = "在幻化師的衣櫃中應用的來源過濾器的位字段" },
  ["twitterCharactersPerMedia"] = { description = "將媒體附加到Twitter帖子時需要的字元數" },
  -- ["twitterGetConfigTime"] = { description = "上次成功獲取Twitter配置數據的時間" },
  ["twitterShortUrlLength"] = { description = "非https URL縮短到的字元數" },
  ["twitterShortUrlLengthHttps"] = { description = "https URL縮短到的字元數" },
  ["uiScale"] = {},
  ["uiScaleMultiplier"] = {
    description = "預設UI比例的乘數。-1=根據系統/顯示器DPI確定，0.5-2.0=計算UI比例時使用的乘數。僅在useUIScale為0時應用。",
  },
  ["unitHighlights"] = { description = "是否應顯示單位周圍的高亮圓圈" },
  ["useCompactPartyFrames"] = { description = "對隊伍使用新的團隊框架" },
  ["useUiScale"] = {},
  ["videoOptionsVersion"] = {},
  -- ["wardrobeShowCollected"] = { description = "是否在衣櫃中顯示收集的幻化" }, -- 只讀
  -- ["wardrobeShowUncollected"] = { description = "是否在衣櫃中顯示未收集的幻化" }, -- 只讀
  -- ["wardrobeSourceFilters"] = { description = "在收集日誌的衣櫃中應用的來源過濾器的位字段" },
  ["warp"] = { description = "圖形設定的UI值" },
  ["warpScreenSize"] = { description = "物理顯示器尺寸" },
  ["warpViewDistance"] = { description = "從觀眾到顯示器的物理距離" },
  ["warpViewTilt"] = { description = "側面顯示器的角度（以弧度為單位）" },
  ["watchFrameBaseAlpha"] = { description = "目標框架不透明度。" },
  -- ["watchFrameState"] = { description = "儲存目標框架的鎖定和折疊狀態" },
  ["waterDetail"] = {},
  ["weatherDensity"] = {},
  ["webChallengeURLTimeout"] = { description = "等待網絡挑戰URL的時間（以秒為單位）。0表示永遠等待。" },
  ["whisperMode"] = { description = '預設情況下新耳語採取的操作："popout", "inline", "popout_and_inline"' },
  ["windowResizeLock"] = { description = "在窗口模式下防止調整大小" },
  ["wmoDoodadDist"] = { description = "Wmo doodad載入距離" },
  ["wmoLodDist"] = {},
  ["worldBaseMip"] = {},
  ["worldLoadSort"] = { description = "載入時按距離對對象進行排序" },
  ["worldMapOpacity"] = { description = "縮小尺寸時世界地圖的不透明度" },
  ["worldMaxMipLevel"] = { description = "世界最大紋理mipmap級別" },
  ["worldPoolUsage"] = { description = "使用靜態/動態/流" },
  ["worldPreloadHighResTextures"] = { description = "預先載入時需要在串流非關鍵半徑內載入高分辨率紋理" },
  ["worldPreloadNonCritical"] = { description = "預先載入時需要在串流非關鍵半徑內載入對象" },
  ["worldPreloadSort"] = { description = "預先載入時按距離對對象進行排序" },
  ["worldQuestFilterArtifactPower"] = { description = "如果啟用，地圖上將顯示具有神器能量獎勵的世界任務" },
  ["worldQuestFilterEquipment"] = { description = "如果啟用，地圖上將顯示具有裝備獎勵的世界任務" },
  ["worldQuestFilterGold"] = { description = "如果啟用，地圖上將顯示具有金幣獎勵的世界任務" },
  ["worldQuestFilterOrderResources"] = { description = "如果啟用，地圖上將顯示具有職業大廳資源獎勵的世界任務" },
  ["worldQuestFilterProfessionMaterials"] = { description = "如果啟用，地圖上將顯示具有專業材料獎勵的世界任務" },
  ["CastTimingEnhancements"] = { prettyName = nil, description = "按住鏈式預施法，並預測動畫定時施法", type = "boolean" },
  ["autoAcceptQuickJoinRequests"] = { prettyName = "自動接受快速加入請求", description = "", type = "boolean" },

  ["AimingStrafeLeftUsesMoveBackwards"] = { description = "在瞄準遠程武器並向左橫移時使用向後移動動畫" },
  ["DebugTorsoTwist"] = { description = "軀幹扭轉的調試可視化：1 = 玩家，2 = 目標，3 = 全部" },

  ["lodObjectFadeScale"] = {},
}

local CategoryNames = { -- not sure how meaningful these really are (/Blizzard_Console/Blizzard_Console_AutoComplete.lua Enum.ConsoleCategory)
  [0] = "Debug",
  [1] = "Graphics",
  [2] = "Console",
  [3] = "Combat",
  [4] = "Game",
  [5] = "Default",
  [6] = "Net",
  [7] = "Sound",
  [8] = "GM",
  [9] = "None",
}

--[[
  ConsoleGetAllCommands() returns a list of tables in this format:
    category: number from 0 to 9 representing a category above
    command: cvar name
    commandType: 0 seems to represent a cvar, 1 is a script command (like quit)
    help: cvar description text
--]]

-- Returns filtered list of CVars
function addon:GetCVars()
  local cvars = {}
  for _, info in ipairs(addon:GetAllCommands()) do
    if
      info.commandType == 0 -- cvar, rather than script
      and info.category ~= 0 -- ignore debug category
      and not strfind(info.command:lower(), "debug") -- a number of commands with "debug" in their name are inexplicably not in the "debug" category
      and info.category ~= 8 -- ignore GM category
      and addon:CVarExists(info.command) -- real cvar?
    then
      table.insert(cvars, info)
    end
  end
  return cvars
end

for _, info in pairs(addon:GetCVars()) do
  if not addon.hiddenOptions[info.command] then
    local optionTable = {
      -- prettyName = info.command, -- the api doesn't provide pretty names, so the only way to keep these would be to create a table for them
      description = info.help,
    }
    addon.hiddenOptions[info.command] = optionTable
  end
end

-- Allow case-insensitive lookup of cvars in our table (relatively slow, so match the case when possible)
local NoCase = {
  __index = function(t, mk) -- get
    if mk and mk.lower then
      local mk = mk:lower()
      for k, v in pairs(t) do
        if k:lower() == mk then
          return v
        end
      end
    end
  end,
  __newindex = function(t, mk, mv) -- set
    if mk and mk.lower then
      local mk = mk:lower()
      for k, v in pairs(t) do
        if k:lower() == mk then
          t[k] = mv
          return
        end
      end
    end
  end,
}
setmetatable(addon.hiddenOptions, NoCase)
