local LSM = LibStub("LibSharedMedia-3.0") 

-- ----- 
-- BACKGROUND 
-- ----- 

-- ----- 
--  BORDER 
-- ---- 

-- -----
--   FONT
-- -----

-- -----
--   SOUND
-- -----
LSM:Register("sound", "|cFFFF00001|r", [[Interface\Addons\SharedMedia_Causese\sound\1.ogg]])
LSM:Register("sound", "|cFFFF00002|r", [[Interface\Addons\SharedMedia_Causese\sound\2.ogg]])
LSM:Register("sound", "|cFFFF00003|r", [[Interface\Addons\SharedMedia_Causese\sound\3.ogg]])
LSM:Register("sound", "|cFFFF00004|r", [[Interface\Addons\SharedMedia_Causese\sound\4.ogg]])
LSM:Register("sound", "|cFFFF00005|r", [[Interface\Addons\SharedMedia_Causese\sound\5.ogg]])
LSM:Register("sound", "|cFFFF00006|r", [[Interface\Addons\SharedMedia_Causese\sound\6.ogg]])
LSM:Register("sound", "|cFFFF00007|r", [[Interface\Addons\SharedMedia_Causese\sound\7.ogg]])
LSM:Register("sound", "|cFFFF00008|r", [[Interface\Addons\SharedMedia_Causese\sound\8.ogg]])
LSM:Register("sound", "|cFFFF00009|r", [[Interface\Addons\SharedMedia_Causese\sound\9.ogg]])
LSM:Register("sound", "|cFFFE000010|r", [[Interface\Addons\SharedMedia_Causese\sound\10.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_1:16|t", [[Interface\Addons\SharedMedia_Causese\sound\01.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_2:16|t", [[Interface\Addons\SharedMedia_Causese\sound\02.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_3:16|t", [[Interface\Addons\SharedMedia_Causese\sound\03.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_4:16|t", [[Interface\Addons\SharedMedia_Causese\sound\04.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_5:16|t", [[Interface\Addons\SharedMedia_Causese\sound\05.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_6:16|t", [[Interface\Addons\SharedMedia_Causese\sound\06.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_7:16|t", [[Interface\Addons\SharedMedia_Causese\sound\07.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_8:16|t", [[Interface\Addons\SharedMedia_Causese\sound\08.ogg]])
LSM:Register("sound", "|cFFFF0000Add|r", [[Interface\Addons\SharedMedia_Causese\sound\Add.ogg]])
LSM:Register("sound", "|cFFFF0000Adds|r", [[Interface\Addons\SharedMedia_Causese\sound\Adds.ogg]])
LSM:Register("sound", "|cFFFF0000AoE|r", [[Interface\Addons\SharedMedia_Causese\sound\AoE.ogg]])
LSM:Register("sound", "|cFFFF0000Assist|r", [[Interface\Addons\SharedMedia_Causese\sound\Assist.ogg]])
LSM:Register("sound", "|cFFFF0000Avoid|r", [[Interface\Addons\SharedMedia_Causese\sound\Avoid.ogg]])
LSM:Register("sound", "|cFFFF0000Back|r", [[Interface\Addons\SharedMedia_Causese\sound\Back.ogg]])
LSM:Register("sound", "|cFFFF0000Backup|r", [[Interface\Addons\SharedMedia_Causese\sound\Backup.ogg]])
LSM:Register("sound", "|cFFFF0000Bait|r", [[Interface\Addons\SharedMedia_Causese\sound\Bait.ogg]])
LSM:Register("sound", "|cFFFF0000Beam|r", [[Interface\Addons\SharedMedia_Causese\sound\Beam.ogg]])
LSM:Register("sound", "|cFFFF0000Bloodlust|r", [[Interface\Addons\SharedMedia_Causese\sound\Bloodlust.ogg]])
LSM:Register("sound", "|cFFFF0000Blue|r", [[Interface\Addons\SharedMedia_Causese\sound\Blue.ogg]])
LSM:Register("sound", "|cFFFF0000Boss|r", [[Interface\Addons\SharedMedia_Causese\sound\Boss.ogg]])
LSM:Register("sound", "|cFFFF0000Break|r", [[Interface\Addons\SharedMedia_Causese\sound\Break.ogg]])
LSM:Register("sound", "|cFFFF0000Buff|r", [[Interface\Addons\SharedMedia_Causese\sound\Buff.ogg]])
LSM:Register("sound", "|cFFFF0000CC|r", [[Interface\Addons\SharedMedia_Causese\sound\CC.ogg]])
LSM:Register("sound", "|cFFFF0000CD|r", [[Interface\Addons\SharedMedia_Causese\sound\CD.ogg]])
LSM:Register("sound", "|cFFFF0000Center|r", [[Interface\Addons\SharedMedia_Causese\sound\Center.ogg]])
LSM:Register("sound", "|cFFFF0000Chain|r", [[Interface\Addons\SharedMedia_Causese\sound\Chain.ogg]])
LSM:Register("sound", "|cFFFF0000Charge|r", [[Interface\Addons\SharedMedia_Causese\sound\Charge.ogg]])
LSM:Register("sound", "|cFFFF0000Clear|r", [[Interface\Addons\SharedMedia_Causese\sound\Clear.ogg]])
LSM:Register("sound", "|cFFFF0000Collect|r", [[Interface\Addons\SharedMedia_Causese\sound\Collect.ogg]])
LSM:Register("sound", "|cFFFF0000Dance|r", [[Interface\Addons\SharedMedia_Causese\sound\Dance.ogg]])
LSM:Register("sound", "|cFFFF0000Debuff|r", [[Interface\Addons\SharedMedia_Causese\sound\Debuff.ogg]])
LSM:Register("sound", "|cFFFF0000Dispell|r", [[Interface\Addons\SharedMedia_Causese\sound\Dispell.ogg]])
LSM:Register("sound", "|cFFFF0000Dodge|r", [[Interface\Addons\SharedMedia_Causese\sound\Dodge.ogg]])
LSM:Register("sound", "|cFFFF0000Dont Move|r", [[Interface\Addons\SharedMedia_Causese\sound\Dont Move.ogg]])
LSM:Register("sound", "|cFFFF0000Dot|r", [[Interface\Addons\SharedMedia_Causese\sound\Dot.ogg]])
LSM:Register("sound", "|cFFFF0000Drop|r", [[Interface\Addons\SharedMedia_Causese\sound\Drop.ogg]])
LSM:Register("sound", "|cFFFF0000Enter|r", [[Interface\Addons\SharedMedia_Causese\sound\Enter.ogg]])
LSM:Register("sound", "|cFFFF0000Escort|r", [[Interface\Addons\SharedMedia_Causese\sound\Escort.ogg]])
LSM:Register("sound", "|cFFFF0000Exit|r", [[Interface\Addons\SharedMedia_Causese\sound\Exit.ogg]])
LSM:Register("sound", "|cFFFF0000Fixate|r", [[Interface\Addons\SharedMedia_Causese\sound\Fixate.ogg]])
LSM:Register("sound", "|cFFFF0000Front|r", [[Interface\Addons\SharedMedia_Causese\sound\Front.ogg]])
LSM:Register("sound", "|cFFFF0000Gate|r", [[Interface\Addons\SharedMedia_Causese\sound\Gate.ogg]])
LSM:Register("sound", "|cFFFF0000Gather|r", [[Interface\Addons\SharedMedia_Causese\sound\Gather.ogg]])
LSM:Register("sound", "|cFFFF0000Green|r", [[Interface\Addons\SharedMedia_Causese\sound\Green.ogg]])
LSM:Register("sound", "|cFFFF0000Healcd|r", [[Interface\Addons\SharedMedia_Causese\sound\Healcd.ogg]])
LSM:Register("sound", "|cFFFF0000Hide|r", [[Interface\Addons\SharedMedia_Causese\sound\Hide.ogg]])
LSM:Register("sound", "|cFFFF0000High Energy|r", [[Interface\Addons\SharedMedia_Causese\sound\High Energy.ogg]])
LSM:Register("sound", "|cFFFF0000High Stacks|r", [[Interface\Addons\SharedMedia_Causese\sound\High Stacks.ogg]])
LSM:Register("sound", "|cFFFF0000Immunity|r", [[Interface\Addons\SharedMedia_Causese\sound\Immunity.ogg]])
LSM:Register("sound", "|cFFFF0000In|r", [[Interface\Addons\SharedMedia_Causese\sound\In.ogg]])
LSM:Register("sound", "|cFFFF0000Interrupt|r", [[Interface\Addons\SharedMedia_Causese\sound\Interrupt.ogg]])
LSM:Register("sound", "|cFFFF0000Intermission|r", [[Interface\Addons\SharedMedia_Causese\sound\Intermission.ogg]])
LSM:Register("sound", "|cFFFF0000Invisibility|r", [[Interface\Addons\SharedMedia_Causese\sound\Invisibility.ogg]])
LSM:Register("sound", "|cFFFF0000Jump|r", [[Interface\Addons\SharedMedia_Causese\sound\Jump.ogg]])
LSM:Register("sound", "|cFFFF0000Knock|r", [[Interface\Addons\SharedMedia_Causese\sound\Knock.ogg]])
LSM:Register("sound", "|cFFFF0000Left|r", [[Interface\Addons\SharedMedia_Causese\sound\Left.ogg]])
LSM:Register("sound", "|cFFFF0000Linked|r", [[Interface\Addons\SharedMedia_Causese\sound\Linked.ogg]])
LSM:Register("sound", "|cFFFF0000LoS|r", [[Interface\Addons\SharedMedia_Causese\sound\LoS.ogg]])
LSM:Register("sound", "|cFFFF0000Melee|r", [[Interface\Addons\SharedMedia_Causese\sound\Melee.ogg]])
LSM:Register("sound", "|cFFFF0000Move|r", [[Interface\Addons\SharedMedia_Causese\sound\Move.ogg]])
LSM:Register("sound", "|cFFFF0000Next|r", [[Interface\Addons\SharedMedia_Causese\sound\Next.ogg]])
LSM:Register("sound", "|cFFFF0000Nuke|r", [[Interface\Addons\SharedMedia_Causese\sound\Nuke.ogg]])
LSM:Register("sound", "|cFFFF0000Orange|r", [[Interface\Addons\SharedMedia_Causese\sound\Orange.ogg]])
LSM:Register("sound", "|cFFFF0000Orb|r", [[Interface\Addons\SharedMedia_Causese\sound\Orb.ogg]])
LSM:Register("sound", "|cFFFF0000Out|r", [[Interface\Addons\SharedMedia_Causese\sound\Out.ogg]])
LSM:Register("sound", "|cFFFF0000Overlap|r", [[Interface\Addons\SharedMedia_Causese\sound\Overlap.ogg]])
LSM:Register("sound", "|cFFFF0000Phase2|r", [[Interface\Addons\SharedMedia_Causese\sound\Phase2.ogg]])
LSM:Register("sound", "|cFFFF0000Phase3|r", [[Interface\Addons\SharedMedia_Causese\sound\Phase3.ogg]])
LSM:Register("sound", "|cFFFF0000Pots|r", [[Interface\Addons\SharedMedia_Causese\sound\Pots.ogg]])
LSM:Register("sound", "|cFFFF0000Pull|r", [[Interface\Addons\SharedMedia_Causese\sound\Pull.ogg]])
LSM:Register("sound", "|cFFFF0000Purple|r", [[Interface\Addons\SharedMedia_Causese\sound\Purple.ogg]])
LSM:Register("sound", "|cFFFF0000Push|r", [[Interface\Addons\SharedMedia_Causese\sound\Push.ogg]])
LSM:Register("sound", "|cFFFF0000Range|r", [[Interface\Addons\SharedMedia_Causese\sound\Range.ogg]])
LSM:Register("sound", "|cFFFF0000Ready|r", [[Interface\Addons\SharedMedia_Causese\sound\Ready.ogg]])
LSM:Register("sound", "|cFFFF0000Red|r", [[Interface\Addons\SharedMedia_Causese\sound\Red.ogg]])
LSM:Register("sound", "|cFFFF0000Reflect|r", [[Interface\Addons\SharedMedia_Causese\sound\Reflect.ogg]])
LSM:Register("sound", "|cFFFF0000Right|r", [[Interface\Addons\SharedMedia_Causese\sound\Right.ogg]])
LSM:Register("sound", "|cFFFF0000Root|r", [[Interface\Addons\SharedMedia_Causese\sound\Root.ogg]])
LSM:Register("sound", "|cFFFF0000Seed|r", [[Interface\Addons\SharedMedia_Causese\sound\Seed.ogg]])
LSM:Register("sound", "|cFFFF0000Selfcd|r", [[Interface\Addons\SharedMedia_Causese\sound\Selfcd.ogg]])
LSM:Register("sound", "|cFFFF0000Shield|r", [[Interface\Addons\SharedMedia_Causese\sound\Shield.ogg]])
LSM:Register("sound", "|cFFFF0000Soak|r", [[Interface\Addons\SharedMedia_Causese\sound\Soak.ogg]])
LSM:Register("sound", "|cFFFF0000Soon|r", [[Interface\Addons\SharedMedia_Causese\sound\Soon.ogg]])
LSM:Register("sound", "|cFFFF0000Spawn|r", [[Interface\Addons\SharedMedia_Causese\sound\Spawn.ogg]])
LSM:Register("sound", "|cFFFF0000Spellsteal|r", [[Interface\Addons\SharedMedia_Causese\sound\Spellsteal.ogg]])
LSM:Register("sound", "|cFFFF0000Split|r", [[Interface\Addons\SharedMedia_Causese\sound\Split.ogg]])
LSM:Register("sound", "|cFFFF0000Spread|r", [[Interface\Addons\SharedMedia_Causese\sound\Spread.ogg]])
LSM:Register("sound", "|cFFFF0000Stack|r", [[Interface\Addons\SharedMedia_Causese\sound\Stack.ogg]])
LSM:Register("sound", "|cFFFF0000Stop|r", [[Interface\Addons\SharedMedia_Causese\sound\Stop.ogg]])
LSM:Register("sound", "|cFFFF0000Stopcast|r", [[Interface\Addons\SharedMedia_Causese\sound\Stopcast.ogg]])
LSM:Register("sound", "|cFFFF0000Switch|r", [[Interface\Addons\SharedMedia_Causese\sound\Switch.ogg]])
LSM:Register("sound", "|cFFFF0000Targeted|r", [[Interface\Addons\SharedMedia_Causese\sound\Targeted.ogg]])
LSM:Register("sound", "|cFFFF0000Taunt|r", [[Interface\Addons\SharedMedia_Causese\sound\Taunt.ogg]])
LSM:Register("sound", "|cFFFF0000Totem|r", [[Interface\Addons\SharedMedia_Causese\sound\Totem.ogg]])
LSM:Register("sound", "|cFFFF0000Transition|r", [[Interface\Addons\SharedMedia_Causese\sound\Transition.ogg]])
LSM:Register("sound", "|cFFFF0000Trap|r", [[Interface\Addons\SharedMedia_Causese\sound\Trap.ogg]])
LSM:Register("sound", "|cFFFF0000Turn|r", [[Interface\Addons\SharedMedia_Causese\sound\Turn.ogg]])
LSM:Register("sound", "|cFFFF0000Winds|r", [[Interface\Addons\SharedMedia_Causese\sound\Winds.ogg]])
LSM:Register("sound", "|cFFFF0000Yellow|r", [[Interface\Addons\SharedMedia_Causese\sound\Yellow.ogg]])
LSM:Register("sound", "|cFFFF0000Zone|r", [[Interface\Addons\SharedMedia_Causese\sound\Zone.ogg]])

-- -----
--   STATUSBAR
-- -----
