-- AUTO-GENERATED by packages/scraper/src/generate-embellishment-effects-lua.ts
-- Edit the scraper instead of this file.
--
-- Joins SimC's authoritative bonus_id / spell_id table with Wowhead's
-- catalog item IDs. The runtime uses byBonusId to identify which
-- embellishment is applied to an equipped carrier: parse the bonus_ids
-- out of the carrier's item link, look each one up here. bySpellId is
-- a secondary path via GetItemSpell.

-- wowhead scrapedAt: 2026-05-27
-- simc scrapedAt: 2026-05-27 (build 12.0.5.67602)

ClassCodexEmbellishmentEffects = ClassCodexEmbellishmentEffects or {}
ClassCodexEmbellishmentEffects.byItemId = {
  [240165] = { bonusId = 12385, spellIds = { 1241711 } }, -- Sunfire Silk Lining
  [240167] = { bonusId = 12384, spellIds = { 1283697 } }, -- Arcanoweave Lining
  [244604] = { bonusId = 12686, spellIds = { 1259060 } }, -- Blessed Pango Charm
  [244675] = { bonusId = 12685, spellIds = { 1244238 } }, -- Devouring Banding
  [245871] = { bonusId = 12705, spellIds = { 1245053 } }, -- Darkmoon Sigil: Blood
  [245874] = { bonusId = 13640, spellIds = { 1245052 } }, -- Darkmoon Sigil: Void
  [245876] = { bonusId = 12693, spellIds = { 1245054 } }, -- Darkmoon Sigil: Hunt
  [251488] = { bonusId = 13453, spellIds = { 1251906 } }, -- Prismatic Focusing Iris
  [251490] = { bonusId = 13454, spellIds = { 1251905 } }, -- Stabilizing Gemstone Bandolier
}

ClassCodexEmbellishmentEffects.byBonusId = {}
ClassCodexEmbellishmentEffects.bySpellId = {}
for itemId, data in pairs(ClassCodexEmbellishmentEffects.byItemId) do
  if data.bonusId then
    ClassCodexEmbellishmentEffects.byBonusId[data.bonusId] = itemId
  end
  if data.spellIds then
    for _, spellId in ipairs(data.spellIds) do
      ClassCodexEmbellishmentEffects.bySpellId[spellId] = itemId
    end
  end
end
