-- Generated by resolve:embellishments + generate:embellishments. Do not edit.
ClassCodexEmbellishmentEffects = ClassCodexEmbellishmentEffects or {}
ClassCodexEmbellishmentEffects.byItemId = {
  [237834] = { spellIds = { 1229662 } },
  [237840] = { spellIds = { 1229657 } },
  [239656] = { spellIds = { 1228950 } },
  [239661] = { spellIds = { 1228985 } },
  [239662] = { spellIds = { 1228986 } },
  [239664] = { spellIds = { 1228988, 1241529 } },
  [240167] = { spellIds = { 1228961, 1229511, 1230205, 1283697 } },
  [240892] = { spellIds = { 1230444 } },
  [240908] = { spellIds = { 1230468 } },
  [240949] = { spellIds = { 1230485 } },
  [240950] = { spellIds = { 1230486 } },
  [244610] = { spellIds = { 1237518 } },
  [244611] = { spellIds = { 1237519 } },
  [245770] = { spellIds = { 1230060 } },
  [245873] = { spellIds = { 1230077 } },
  [245876] = { spellIds = { 1230076 } },
  [248130] = { spellIds = { 1229916, 1246298, 1246299 } },
  [251487] = { spellIds = { 1230477, 1251906, 1252383, 1252389, 1252411 } },
  [251490] = { spellIds = { 1230478, 1251905 } },
  [251513] = { spellIds = { 1230479, 1251904 } },
}
