-- MSUF_Presets.lua
-- Preset snapshots used by the SlashMenu Home page (non-profile quick loads).
-- This file is loaded via .toc before MidnightSimpleUnitFrames_SlashMenu.lua.

local addonName, ns = ...
ns = ns or {}

ns.MSUF_PRESETS = {

  ["Minimal_NBX 1080p"] = {
    _msufWarning = "Loads a compact MSUF2 preset string (overwrites your current active profile).",
    _msufImportString = [[MSUF2:7VpNjNxWHfekpYpoCFAVtJuEKiVFCoJKJE2lLQhW8+mZ3fnw2p5dr4RYvbXfjK31+Lm2J5uNQIrEgQtHLnBBohD1ggQCQUSRSk+AFC6ce0GVegDUk31I9lDeh9/z86x3U9KiBil7SGbs9/z+7/f7/b+e57YaRmji+VBtwQmY+4kaggMfAeeXvSC0m8hHUXxLncIARsC/88bGNAKOB4Ok5UXQTjwUtPWe2jW3bBAnuyDqIHsem94MjiaTGCbW89a5/I4JoilMDBftGyH0/SGYwcy6kN8coqAXJDCK5mHi7fqQrtuMoLNu+yCOGyBqTBvKwA1NeCMxQmDDyFr6oSkvisdseU7iLv3GWsqvaz44gBGZklujGPIT2gHASzkpt30ceBMPOmJnadcB0d4AOTBdfKTY4LayGdJLTXZ/dB1vwnOgXhvDWYj2YWQkYAobvhfskVn3rinG1Ee7wB97hg18qEUQP6YF5gkaRsBzBnhJPMm7Cc+OF7bXhd7UTZ41S6bkZrxS+/KCjT0bBdxGcYuRUCCyrRgT8vR1z94jE9gSS5f13HjKA91BnG1AilcDxXG+2awP5hHooCAh9i4t6/kq8tLGbj6+uGgpGgEWMxqR1QIYxxgWjSvLSCIYTBP3cPXtu+Tvb8L6BrD3phGaBw7ZwTyCowZMsGouYnhv3gSRww0gKuuDBAb2QTr24XXo9wLHs0GCOF6KTuzC4F/34H4uhKw/jyGRGoocGGVlSUsiMqHjJUQWRgBC8r+KGc9UPJR8aVPFim1LvqCMJPNUH+2nG7sFmAz6M4a8aj7xlF6SzCbw5/Bw9d23/M+/5X9qI8ZPo6P5ctlmSQiFcsZkqIkS4Nd3YxTt1mcYyyTVKdXUL2AIIoJS/cXxEbclBKbWhUq5cwQFVcLHuTqUKtlaWJnEpiaa7QJMPKZMEJUd63PW8yMmRbYLvL9si1PSxcZsuV4C61GE9mNMYsWjNRSr5kjrtzvmeBEqFkP+uEmUHbe8GO+D6YG6wmv1K4erf/0x+ftJ/aVa/erh6jsv0b+CcEkpI7K5gRd4MxAS+LIBiQPt3NY4K4NcRDBd0gXXQNnSgpDjgt22Up7RggmwXcxRSdeyq2rSqsyQX1XsalvZmGCFu5257+vQ15AXJBxNYz6xUQQ7/jx2G3MH72kQn9IICA3JHbIBFRxXxtnhLvc5IznwYcvs9oZD7IpN4kgsAwmkRJYQGcL8IIGhu4t8ei81mHQ6ctRLpSyjK2YpIubwL9e+OpJSXwvtB+kaYa56PQ0EtosiEzURXpgMNktUc1LXBJTW/Td//ffPLgRqOWZWBIbtlWtbbsiSmQF9nLWgg5NYsg4POsxNNe4XJEQZCQyfLbFBNamTK5rwasqQyKye74t82NTNfmk6zeGbi9GwE+HLcbrmhpzhMxs+BE4pJT1xjAotRSfMz+MEzch0SnNqlmN4nYLbG9YHrPhYY2gTc7rjngZw/kgKZLfut779tSes5UUFiTqjhxl8dY68GFZRjzP8opfm4bRYYvv+W8o717a8AEcbL5jqMJZjTRd7B7VzICloHGIpSsjxYsQ672L9rGPchZYoNRTVTFRTRRQoqqkqiW2v9DjSZHDTBUEAfRPvME6PSXCVOXu7yM/YeJ3sP9NLaLGIcblUkx2NUnkBItVPQ6IoXVQ+WXU9pdZMGpFxILf3miRt8Xhco3G4Zi3n9yHwWZkiB22FDrr3daVfcBbeOPzTsz/9xvfsUyJSjkOH5gmskOvAP1z90c1/rL7//vtDFjPUHIB0IBImYW+jM+73d7T+2NjR2nqzPTR7E67c9j7JRYPEC5sHtk8yELzxdD/BM0nIciIUZt2JiIMBZrEIeiJkGC7Yg7wqOj3KS9giVavkCdjnR21L09uGsVXf3mmM+q1jg8kJBSGOMxOitDIS97/Zv3vXukARHu0HLbg7n0y6WAQ+EYLERJEccWb8F8uM1nIlo7RWavbrhmGdL4m6XJSlBtZHhEs5IvEBuIEVHMVPbbFEM8bGBwm+qmEHIUnnk9Y5bmTjvzBxKFRRSmdDDlJ1kM9TCYOQl8S67NQmInGX5xxNhiHbcryYXCUBuxdMkIkzBdZJnBUStbBE3/x3/IO73/nnrSLYdO+3vnDxCV3KY2Lt3F6VVovMIf8i49f0vdDA2LfI7qodrVHrEYfsk4CbDd0SgEzNvQCN5gkuZIqIU45Dm9KKnQgRguI97cbpo+1BuSQuslEBKc1G/UAqJM/KebgPJ9gdZ0WF1Wq8tpZ/xZF36e0OGTuPl7SW68l93GIcsp4/kqMs5ZimdlvkYgY0SwfPsFK2V5EDcOu02AtmmoCW185Hi77tlRfXmLdXx5ljOz5Lqeg/tpX1WTyf5E1Ebcho5nvOtMU83ppiPVR2T7gFmpdVSws3lVZRnj3iT2pM637ognsryjpt+DDsKIDtXR/HPi3GJfm8wCj+uUoMqnfWM/qhNWxlXfoBm5hRTaouipNMqtVUZS0IbSIznWTO5cXUU0iyn1C+2b93lg3WCJm9gOmAjEn7lKIcqyf1BOENEpUXkfa7CwcQX6JmaWRauti8bxTfecmjFZdYBcPjTIc8pqul60Tn+egv9tww/3i58tRChbxrley2LunCewW06WKKbe/T0PD7kl+doWhTtMTS1spEsslaGnRcVvqoiB87nM4/WktvHNmy9ZlmCJPflYFdPMQpMMweArNMwLBIQCVoBaiXuN2v1J4pI3gMWm/L7FwqwKoAPJNBezLHbOk5DtrKvQLgSxWgtWlddWepjNvi/iR9SDIcsBiUl7gfDlFZBtUSzCFc+UMZQfwtSvAyNAg0R53OcQKshjSt0nAlpBcLHZ5d9M0KYFs4OMSvS/0OxQyHktQgMZclNdPFBS05k6pJqYgPzCi+0hkRnO1Ch9/FuKMurj8TNytOZcTUYZh/YvniKdFKiREtErTvLJ/M+xH/KST9P9KBGuO1cEpb2alUQZn7EqUfVAi/rWK8cDGus+Xa4cmetVx7+WTX6kulSZy3/fkZdydPDg9wuxNSwEeAeQm9IrKeHMuwez6k/53sckIAJ/veyntSKDqK+ee6Uzyb1Jp3zudHyOy4j1QmUbppR1j0LvCI/+kgmLKe/Ps1RdGlszteeAzEcHrkfFmzi2flE2s1UoDuB2q+LOPX9ELcUBUPxJXPdUhAVV9k5oxl25p8lXRg5yc4pEiKs9Io+iB6qjRgT+Zl259HPiJtqhiU5vM6XhQnLRDYkO3ekCxq4caFHLPc+5YyDpjtuHWEPoS0jum1KgDZXtLGi5tiMByuvjuhf0c/lIy1cPPLN9sLJAKUmjJkA8UB/5L1QiVI1Mhiaiqb1Cb+IJiRGWDvFg4Cu8QLHU95+UqOn3SzsEQCmCGpi12IAH4qPwR7UEStcNQFL3/heC+XvfAhUutxxV1eyv7COmcXRzZ5ZyyEUlc2j97tIxRmmnSdnpZ8wpSujPkJW7ohz0exZie3Pu5UvvJeUVZURJMO7e+v3hZQdnkaTXsi56ZrRerO1BCSV3vJ622SXq/dVieej9mLi0eoDj3QiF/vosA/GOAiIF136NH/AEw9O9W9wPbnuCOi1+jxEh/QnEcx/pIPoGb02R0NeTEK0gH7hqdCgEfmN9tBhDvBdEDWI5PqZFNpm1rxWulphUlaflkccaUD0tNqMJqBgBxLWed2SINXv7qT73Dg4VY5gc7O9auZifIG33BBBJ0+OEDzJB3xqx02I+349MZtjYc9qk3iJbwKONX1cCSkXniOc6YMYnIuV4zNGVSG/PlsvazPHs9suJX75+1q28pjj7P0Z2ItYczCoqkgfAGv/1fahW5PJJyq/eXHan9k1M7auseEfPSEXDuGkFdqowcEIFbzP+bkoTg5U8HJBc5JrczJGc5J7QFOQqLWS48JeXSiFiHk6mNCHi1Crjwm5JEhBDd35P87Fzu40dDR/tMb4tVO/hoyTsWy9Dc25AdAJsKJx8UNlBaLV9qsaRQ/F6D9DJ2fqRHa34pA2GqNtoa0BStehGfrBHB+HvDcOoX6IF+Xb2GdvfGgL2syae/WeWGspAv2gjfOujNwgz7o9FG5WRc5T2z/nUW2rmQfts792ARdVuTC1yE7AOC/4so6U0xO4rKfomywn7Mx1Rn7XggzQ5ZDjmy6zl5tMZi3xIji5wv0xhoTGv1VjdEbqv02YYSeRJ05qu0F+Q5mIH51zn+ax7x0cMAN4KJ/ag0/Mb/46TGndFaweGWStYHjoKA1MMad1p4XOE3g+83JLDnViW0XzkDtPw==]],
  },
  ["Nooke 1440p"] = {
    _msufWarning = "Loads a compact MSUF3 preset string (overwrites your current active profile).",
    _msufImportString = [[MSUF3:7VtNjORGFXbvbqIQokCiHHpmw5LNQpQIENkfxAZBhv7vnm53e9ruGTdCGmrs6mlr3LZju3dmFgQbBZAQ4cYFbpCwSkAgTmi5QG6AFCIhcQp7SBQpB7hEYCPtTpSlflzlsrt7dxM2t5lDtu0uV7363ve+9165c7nh+e7IsmGjCkdgaocND+zbLjB/3XI8o+Larh9camxDB/rAvvJaJ4R7YRkYO6bvevGGAYJwC/h115gGmjWBvdEogKF+UvbcXehraKzsmrBbH3Q6m2qnpDY35ZKuP5w81nWdlhNC3596obVlQ7JaxYdm27BBEJSBX94uS/LYwxOpHjCgrxef18RF0ZgNywzHxXfWktsKDBMrJAVsBa6/VXKMsetjQ47oRTbKBvvUQDZ4bQsvJ4PQGDcVYknEtjdwrJEFzarlQyO0XCfWl8DUB4EaQmADZHjZ9U3ok4deKJ2WSmcLpTPXviTlV+MADaV1j9yq0O97FxAIlgn7hQGcEOjUEGzDsm05O/ipa+ckddt2t4A9sFQD2FDxIZqmdvrcuSe9rg8sUwb+DnrKugjv108Q4yqua5vuroP3OPCRA0MVGq5jBndpGasSi54qjHPmttBoZi7/SgNoqjDFbSipI+yHtmXs4Aea0Noeh8XH+8k+CCZkM0G8Bh0KVhAk+4472NS6i2xDlheX1PQZBknws6pc6paek64//e677xX6iR2icepWMmN6E/neRIgg+vjYHgcGwcHKdy++2fjNQ99UqRl0J8yQDKnUsbuL54oHNrwA7ZZjWgYIXZ8vSGdQsLENH5gWAjfqYyuQXy5YcLdGvjfjzjSAmMWEHrloEainQdMigaI6wMP/NtDO4wYaii9qJBgGGcJoMCAPRHzvQvRJvWQhvI+G7e5Ga1sp5tRDD6qiMcmD50/3MyxbB/YUHqy8+QD5E4KyL61nqFJm0xaXtQxRkokPVmJt83Xp4Eaf64IKPeBjUEvfGmQe4eDrD8+NEYYtp6TqQdvugglkPJLmEVw/pRcDNHXFnWyBEDEyhNyv8cJA1U/2qK9LREnQPuMN5qwmMmZjbIWw5PvuboDcO2dqxQ0aWk/p1OpaFy/fgcCkoRUP8hBSIfvPOgnfqhWgfWWF5WDlLz/Bfz8lAnOw8tZZ8pdyQOBUD68mW441AR5Zbg5ThtIqINqI0WsOWgrwEZOz7uB2vdUXSJSscqS5hUQGLxspAdr3NOAbD15sYAtK9XZMPlS71bhJPiAE4hb+1Bi7QRi3SaCi5VwH1rZslFqywKR8WKTdQyn7RBWGwBgjivSYq8rbJdsbg2vnJf1hgm5v16nCrelo1ESstTFzGcaF0tkUZoTxvyjGmdgVxUcRUKFAvT7Am9PcENiUNaWJO0UCMcdNQ2lthIJqXJ/adh/aims5YRVzRckrQnUbcX+VZkJ8vUZSqtIZqJtKrV+pdbUNy0EEtJztPgxE+jUR/fqtRlNTpyPD9WHdngbj8tREvpWDIwq2tSwwI1YScePaGHW3mISp4b4Nq1qz1e0iZatgPaAVQtxlpEH2TdEia1Nw0bJoyLXmGMbZzwsAMlHdm/qeDfVl5qXy+/CRihbzQ+hgNldsy1OxWpCta3gHiFnbPvKEmdhYU13bMvUl0wpIWrKtixeBb6JkH9Z9NEUQJzpfFxNctMo9pl+vPButa5n8lwTGUuGzve0kM6CyoYrycLQ6A49Co09zWa6O8nlWCNWOI0jc/bmBYuabo+zDpcLl+RVHudClm+R5LMMIEnh9fEfhTxOW8Hxp2TaviyodrZ95HHsiXs9zmaIbITbz7awJYNG5qOMWhJ0u9TH/pkHoTvActFzTstmaln2tbkmmc6WO27he/fY7985zHKp0lvLE5JVpC7numalrBXChm/ST63n1ZPlW0AmevfXlmdTHs1msHx8jOrYRwIya1AcEPvTtbJWHio2psQPDYFFhPmT6Jz6mghFMSsPilxfWgLrE5sRWVsbAcaCtIfDyi4mloej5JG9HtDVgnr+3OWIc0IT5BRSWZ7JB+mWXuzSVzvk8bxS0pGRHMlDBeiyICUqmhdaI8ai2i5M6ZcdMuZUY0yBlUuJaJmUDzySpH/HmArAPVn588c2VGzdubIw92ruo0EbchkRh2nC/Tg1VBOr38XyxHFpeZd+wcRUB9wpdh+gZ09q8RojkTSEEO1ANUTbfDsf3zPE5bQjIfM8VUIVHtfRg5ff0Qz+zTZrW/tzACGG7E23/5MysG8B3kM4nZPpYL2nc0kpPHWHuZnG6/pXOq6+uC9Jd99E6Mgh2lL179KW53iRlcQX1k+pMGiFbj8VUIIM9RFc/+GgTVxo07o5nSJWt2iNlzBIOr+M5z4be3sFX1W/89sZbP3iFe44hfbBy9VX899e+SHzNxeV8xJoGcT/xwr5Kl9I1dbwmUP9U/vqzl1IRa16vrrzxkb6Qotikqtgws02t2bzy5B0vlmr+JJH1Fq1RkYzG3XEm7dKoaDlubxqithRGG7ScoExCGCsoqHFpca+Mu9ZaAkAQz3Zs2QYlW5zOY7PYSgwP/vjPX37vv9IfJDG/duAojORJWu1Wyy+sJpeoBCpereOx06CoVMcW9v8nFnGXh0RSU/A6gyTBtGckaA1CsYfkIrGRVBQ4zlvOyNXQMiikg4gVSSjXGlAOintrM91+TLqEPu/o49mqe3iqn8lcNDwfH4gqnDZkJ2bORYaflgXoBl4qKAtKpJRzw+uVBwafn9sVoy52mt0vKRYbpGm0jBn6DY/yGheHhxpC7yExajE1qi5KZULb2ZBWHc/A36IAi3im5j17mhg61DP0v1eKKq3ItZZDPYjHRB0CfWLNsX7oIuMxswW9ao09hjmJDNLxR/yu/qiSnr3QcoM1e3U8vKlEDZhIyFo6Mnn443PjtI3VPln0idzRV7s+pk59NM+S2i4hwV6fxy93T0S6LoJKw2XV6a+EZfTi4yIU+qlk2PD8v2eMHh7NnzZVPBj+LgvlrVA79eGidmqO1Qy4EwuAuzoHuHgWuKcKR0Xgji3A7fv5I8s8aJTTyeFqFVE4eLlLpuJxe1cqzkryRVqZsztIHMSgJT1u8WsqVgoq0toYaQQ+/Doik2f5UZSgZulkaZnP723AyRY02SVKsm4TAjscx0nxcmU56/o5/hJd85gCsI3Iut6IHsQUUrI8JpBFpn1jktNnaYDU4xYcijmH8s6YS6BGoiW/QPVmWtsmhUEVJQvck1wrSeuz33Zc14sV4T4pL+9aE0e6gWKElzTh1oD1LxEPagSlH6JtEVGs9Or1BWR9+/ai/Pw1katHF8W4oGZ5mnYEPQ7iGsk6V4q39Hjq0ifuqEtTWchwaq4/807nAnC7ID9/eyA/khHSM/NBfqrQvAnKdZal3gewH1asfHBg7zR7i9f/X/Y2t9HzWKaunEzePFDJwaUbKpKF01r+AqLYtt0kfhGwfWFIgklRUYx0klwLyUxHhWv6YAeCCxAj1vgcXX4g2lLxkZyPgeXHspEUo7hECqLMKDIRngP1C/R+l24thDLqKWHPsfejgcHmajl94GxD4XWUhKwTjarh/RGjPkNX4ID+UMSF697TUpfeTpFa58shNc+sVyDrSbPo6VKyq7rlB2EVOAYkMCKg2Vw8YR2T6eOs6n/F6733hiR9sUcdxGeOB04GClICtqrL0rG//WOQd0N6jv72iPzhc0T28Qz/KHNz8FYf0j8112NkuXTj8XrOM4xFgzzuOdaIfqFvy/YdI8psXz94Ze/JY9+5cePvuE/edRoJsWkBoVlezE9RikUBIcr0Ku4grizdUl14dXj0tbkVXHwnhUaoBufKDNfrTGV3uxpzNa9Sqb7MU5/bqOmWCt1GgGZDLeL51oyCk27yzGW+uyar1GhDTcq4eDWtueKGB/Fb5fClGnbOucuNkWUjXIPLMu5PUSs9AQ4+jG2Y5C1F8FLbJO+DZLBtGVHTRQEv4yZcprerVgBBAKNkVGXqo4u+5Rj21IT0TRJ5Tx116ADFtQLXidrJCGwp+6rm+KgXjWS8BL5fwluLasSKFzIPpFYoyW3+PjzN1Pry5iSYoujaTHYoW6j5DKG5eeFM3EEcdqf4yMaH5st1hEnf3b2vE3i2RVyHwJZWJ2CPvqoJ7lul48nLN7WmlPolrYbfOyWSTSnH33c00ZNl8pyCH6eT0DH9ck/TevImGbdZHtTrah3V0LvhmB4VN9DnDR941Wpvo9tzk1OnOt1BVKdmXOZ6z5ghNS0k3kQ0GG/uVgzxqBWzRSYW88sum75DZo01dk1hSe4m9fYhUaB5aZFDfp46JEFfyoEbzQU3IkH4hUNsD4Pw5kFIO6BFPIkPebKAJ3W11W10PhhLGqpWqrRr1QwbMjzJUyNm1Mj5mBHkCCdIcZnXvcdnKcI7kR/dpkTTPu5QRm4i0TxcH7mZNx68M/FKdf3soUMOdf0Wuo55cuaQJ4c8uQ2enD7kySFPblEJBOTqCn1N13LYy/CY/FgQX2kuqhTG0I8zxi+Gh1u/uD76YEVpfOdIGb9fUsY3I6X+COMiBbOeZ+Tp9DApS0KV/3CB/8oziNr0p6fkIs7QBzOPnLnel/O1PAHBM1PID76JsftsDuLa9NdEMQuINXF1wmh6BkQ/igHSxv+wc+UT8+oh/TifTHABsyDn6A0+Nv3fEsi4NfqzZ0psddfy+CH78G4h7Gao36YbJl9HA+aNSeqA06O4TV+sk/f98byIrwHTdJ2qrA7q1R3LMSvAtiujSXikHhhjOAGF/wE=]],
  },
  ["Atrocity_Style 1440p"] = {
    _msufWarning = "Loads a compact MSUF2 preset string (overwrites your current active profile).",
    _msufImportString = [[MSUF2:7VpPjONWGU9ml4LQdimwSJndUm27lShURd3ZLZoi0WkSx0lm8sdjO5PkNHjil9iM4+fazvzZC3tBvXADocKRwlIOHLjtqVqpHEAqJ4TEoUKqkLgUbvZhdw7L++P3/OxkZqfVIlZocpiJn9+/7/d93+/7vvdyp+75cGw7oC6BsTFzwrpnHDrQMH/XdL1RFTrQD27XJ8AFvuHcfX9z4humDdxQsn0wCm3o1tRmvaH3R0YQ7hi+DEezQLenoDseByAcPD+4nLzRDX8CQs2C+5oHHKdjTEE8eDZ52YFu0w2B78+80N5xAFm36gNzY+QYQVAx/MqkUmxbng4OQs0zRsAflH6si4uiPn3bDK3SXxVjJ4D+TtkdWdBvQxMsDUpJT8UxDoGPJ0n2V2iN0QKWPHOcoXdwdE8rw/G3f3aPidNz7bENTC5sNFg2Zr4RaCEwHANttAJ9E/hku++WrxfKN4rllfvfLeQX5IAMC1seaarS9909JLRtArXYA1MP7gNfC40JqDi2u4tH3b95zIBKseMbttk2/F00xr4FLvZyaDSAPbHCr+iZnSS7eL3Yz22xOYIu2yJ/RXWWwjUsaGM8+4Y92sUD6BKlb6rJ3gkORIAg3gQuBSgIkq3HLYydDN0Q77e0rCariEtrO0n/tHFQUEwkJTIAH6/mgiBAqGh0erpDtgDfeMUY7U58OHNNvPmZD2oadGyz54A94DRd0x4ZIWRgFDa5UMS80OaeUfE+FB/s2WC/RlYy49YsANgSicrjrMULFqUD0w6x2Wmu4eH/daSvuI664gcJy8KlFDyl0E0mxC5Sd+B+tLmTYkeRvqCJiyYDi0oQGuEs4GIFv6oHaI6yvBGTL1JHihvkCzDMuIm/1S0YhLHgXGpxK2MO8/ZDkWabVYm+CVzAM3y8bPmV3pyrYy0iL19owQzWwbPEpbr7rgR2ZuNxAy3r4KWZVxXLN47W/vRz/PlFeeVo7ZMb5LPIsAdXGzvQIUqPjvXBwfNdajxlwhNI1LjPdNZAG+tbdgjKvg/3A6RlON0xQmTTIeAAKzCo612lVZP1Xh41wkHLxS9tEaEkO0BklyWJVBZMFkdr/6DipDYh2FIXK6ttu/bU8AiW6wZhNcyejV5TMXxExVnY0z1cUgUDSmY8l91wqqPjGHJYyI6QQGiMLKS2jP2LLqwIqyY7ObdAOOx2jHpV4CjQdkOGqjYbj6APZGcWWJWZiaRqB0vrlP2xljblXqu1rbR62rZSU6u1jt4m9si45WJnh/mpFh46QNIbzU4HuW8VGzwNahGTiwceHnQUjHpFcNEUHh672FIF/QS6wfPoMDQcamnlKeoSRgl1ySKTRi1XmPSinqHZRHeln3SF6CvBfTdax2oXl1SofeiwCpEfoC7xBiFP1A26oLbjoJ2uc9wHDyp271s5uheZdwHfDFdf6TJvqUzKjmcZ91cLHSxqC/ELjSRxBkLSouIWhRMBgZUHcNtxeIytqnorM5ykClt5VpV91BxEyCo4ahoa5YfAxQOwZUswDI6zU0Rh2B5mQQineAKi/EjPBgiaQjQ75TbNcpT8JqQJYrJFyhq+OFjO2xdPbJpIX2/NoB0AccdVx/Y0zItkqa28Uyd0vImRIbJwFDusq2gIgxLu2HQRf9nuRAVpeIiPydVQ3L9iGb65gZSB8o9bt9B3qi8CdaxNHLhjOD0bGYUDUGxEY2rXb9581VsUIoar32HrYFVULcN1gaMjkILomNC5MPoPC5ksb56wkhxFEEMTtZREmWhByEUCX2ahp/IpAs/ihKxe1JPUELlYFTu6MA0i+mKHun09ceGIOESavxBVMn+rE6gTlbd5rF3Mfa0QvcIUZPrQi9SMNdKU+OV2aHvVw5GDYxg4eLo5ZhZf28fBruMS+2PcyP1Ss4xdoIUoyExC63xjvMjR2sYBUq4fPFXHrzfAYbc2UNSapvXLw+1KtyUdSy8nJJqIecbY6HqeSQIv8qA9w3nwvdaHH/ZpbOihAW6IFleQfeI48cXB8kK9YMxq1VZZ0+YIn4gXbwnCyD7Ekwa7ygHyhkzgyyWDHU6imcjVTUqUNClSLGZWbKgisLiKX8SqaLE6xAkjixKKKFOsZuyDKvePaQkzQCXMm2vPOldW/347ZfnGA+nrP3yoClGHTdfAsQGvm+6Jafto7aMP8efPfcujBZcGHETQwEQ1EVazTNFuUuJHrBl3rIwDUdNqurA7C1E5AyJd4IO0BtTEoo5563xpkM2PCQX07QXshnKzBtIF4VDKgdUFGVwsRtIWGIdRe5pmWVLl3fXkEU1X+kjGfWdBSZEsZFDRsdQzKGw6PASyJmZ1WVM+WvvprY/XHj582DftAMuMUW26Y6ijuI2cNYhJRFV5iYfqqXx9mE/aMsFtLvUbrr7Ka/E0+Uv10MZT1hI7DHjagOjq8Gjt95/86Lm7m/9qC6j1vCg1sf4Dac87lz4PH3zwzA8+WFhuoQJplpWVpGh1UovYozkEh+d41MV+gSpv7xk1E4q2DGcGjtY+/jL5CEVNvbjueiMsHXKwiAdkHkhS4VshUSX9e/eyRhM3velSFdM+BP5kU+c30+o7ketragiRWNjUuftX33jjjablJYOuEWdR8DRxm4bnhIniuemQ2GkTzUMYx8h4aEOJ6yDxlg1M32yNhf6UPzmRLVq5P4eE8kO0EMG32pXlvNnV9gnJfKRyP+f6jEhRSbCpwyRF/Y2wl8F5EbLBtaTTcPWAQzK4lj/FqHpIAaVHYv1fBzV+ckB9vXjuFKiW3j4B1RpJCj4rrtH/FNe3PzWufzsdrqvvnMZY3zkB1sYEjcdx8O6VDj0o4KdbJU04OWCtT6tCI6fqubZhSVFoI44tfi6PVEc+4nbLsH3dQlkePg9b0oU5UBW2BzCA9Vdo6OtR6OlDlQ2O2qOkRMRci8phsReZCM8Rt+nMLIb8oetAnN7yTvEW3w6K86rhToCw30J5pSACIaEMGdd4xZ5LkQtBG6UVgDBxUyq9lllucHTv4PuFNwuFSi8vX3qY8s8x+eBUnX1d4V9FXGrYfgkuLye48J033czGC2TjxU0REaIJhAYbQpT8Ui8/f05X4vr0cPTQHUWDFxdqhCCRboRpRLb9IJRQXQ/IHiJBA3RTOIHdd+uJKdLTDd324iRDu7v8KK9f4c55KvcXHOKRbp/x9pxj/2WR98f1JEr/GmUradGYZN/Mfu6XC1vzb1sQerEitJMy7HObYk8YKKPwti409dgxQMSI5qVTEs1y8asnMk3EmOaFUxBNYZ5Vr+b45lJLKFWC5Pg2uaKRk9xlWUkTKKoSng4/ygwufUbyf37OCviSjzGqPi6lcPr/xmmUcjz5X5KQkQbv9cF0B5gEqQopLWEDGE5oxR0vaaNV/Hmh3Ge9ab6SXinwUy/eIT3tYU2RcI7G2zSc5dMqK40JEi4Bcs5/9eSQz6BZLv67HiAFoNpqdftxBn8BzoXKZ8q+lrGTU2v+C/nU4WRLEA3g84sNYHlJEvLLfPyXyYnPyh0uX4NpkF6zEM3F66nm47oH8KVi+F4Na+fmnfrYdhCywZ02Li0V4E8NFx8O1U1yFxK8t2GSK4S2MbFHUQO6zmEb19JJc3XmByBq0wfJDoCBHjdQXezMTHL1FrXoOwXaAXQjNXlF7yXIDSbrUXN9VFhGbbwEHlnGokU1sot3M1Omu1CSZn4dGnEkBpe3p8EMxeLtRMK2jYrHEJjbeytxC5kvnOHzFx+Yt7swOaqRac9Ipq/vMHNcYsZYaNiI1kjovcw0dFVheQy7vLvYDvAZHH/ssPlbZNpYZ890fdoaJdHyTCMnaOSXTCMFTpA5cKPF4BJrf+0M2yfG2mlBeKYQYP5WRpSswv0LrcBzbBI6MPbrU+OA3kcHF9Zpf3I/rNWUslrWa0rAz/lzOU8DjayQcQoeTiehfbqozzbptF3pybImT3y4H1r0xqeOvvd9w5Okbr9zrJXM6/8kc2F+Oih+FiuJk6TyzExO47fFExXxuPwWE+mNM4U8OUSKFbJyppAnSyHXzxTyxCgEFYH46e4LHVpIsjummPxQCD/pEAUZC9VXmRB4fITlWegjA+z/mxUMrjLlU1DlvAlcT2vtbD6j8ctZ/kO7INqgvwokD3EmGcFJDDkXvpDTeXtqBG/NAD+tIZs9ZBMSFae/gIhZbrUprk6So4gUyORrLOZaG/gfOwZ/jtnnkmCfgyt8MgFnJkVO0X3eN/3JLum3Sa+GqYFr+7bHD4aGTwkZ3JwLbFCBqQw9po1pqoDr43iDXh+Sy814UfJYM0wTulJb68nSru2aVcNxquNpuCQHIwtMjeJ/AA==]],
  },
  ["Rounded_Unitframes (MSUF2) 1440p"] = {
    _msufWarning = "Loads a compact MSUF2 preset string (overwrites your current active profile).",
    _msufImportString = [[MSUF2:7VpPjNxWGZ/ZpAiFdJWiIGazVWlJ+FNKodmk0oJEtzPjsWd2/nltz673tHjHb2as9diu7cnuhksuqAd6g0sruFAaFSQOXGCPReUAUrlwRL1USFzKDfuQ7KG8P37Pzx5PkkJzQbtSm7Hn+b3v+32/9/u+73nuSp7vjiwbSAIYGTM7lDzj2HYN87ctxxvWXdv1gzvSGDjAN+yT97fGvmFawAkFywfD0HKdhtKSmtrO0AjCfcMX3eEs0Kwp6I9GAQj1UtdzD4GvgaOw65pgSxx0OntyZ6DuyQ2l3uhp+tPJkz3XaTkh8P2ZF1r7NsBL131gtoe2EQQ1w6+Na+XuxENzqZ4xBL5eeUPj14VjdiwznFR+Lxv7gevvV53hxPXRwkt6JRkp28YxMYia2BnBBSbizLZ3vaPT99S//Uj4yV5Jv2LMfCPoHzq12WjUtMYTG/4XYrPerl4vV2+cbvzlTfT3VnXtdOPjG/hPX8FPqSEwbAN6UXN9E/j0oVL1Rrm6du/7pbw1DLDd0raHb9XJ9/1bEBHLBEp5AKYYSjU0xqBmW84BeurezZIyQr63reFBa+g6BIAXer5hmV3DP4APWLfB8iCHUxMgZy5oGTMSE9a/lTMPzUvNY19phj8GYYrjbknNGEJWqDyvJHZjDLDxQbwFHAJOECR+xh2Em+g6ITK3sqIkq/BLb/nuzDGBOXCscOQbUziRup9MkY7TS7IJ/YZk8ZEBDggCCJJKViRG0zWZLzVjeDDGsyN/Zj5oqK5tmQMb3AJ2yzGtoRG6PrOD+YmpCO29pCA7ZB/cssBhA69kxp1ZABBrMQPi7Abh2KcB08J7Q3UMD/0rwXjHEhyKLhqY/MxNfmf1kxnViXso2e5htLWf4knQv6jyqyYPluUgNMJZwPwKfiUFcI6q2I7xB6EnxE38ARhm3EKfpIkbhDG3E5XydoYijFJf1DL8oMbqq5nbXSMcTlAcMV2jQeZL5BCKZ6w/XbgXKMD603SHCmD/U+zRItJDCyvI0bo73TdCSNMQMHzihbtVf05foRSC2Oe82qGRbUKjdyZWCKq+7x4GkAsFq8huIGl9udMQtUEeWjzfSnlpGzssWIEH7KyypH4ihTnd+AdxNSUOx7g+crRrOdbU8DDOmwbWyR7cUs1BSzZ8qO/ZkHA2KBzLkhnPZQ1O47dIc3dLme3Ab3KZmz5Z8lyBF2gXUtVWgC27lhNS+HrIvw7kLlGuuLdPd6EaHttA0JqtXnPftfFmj9TZaOj6QLRnwaQ2MxE5g6VNkmaKUxZJaVSrllW4nB8CB8GHXBfcMIh7cPPX0W4hGTRWxra7b9gDC+5IG2wb9gycbnz0FPy79O821isIteuAxr4NtYjiyRIiS4Z9yqnauGp7E+PeeklG7tY4gYi1B0gaGqy5oWFXSYacwiFhRMPRn4UwswBtAsUNKWdZzquTMIZbUMsofcKCyk/7XHEguIdOtIkIxC8vE6Zpbt2F+MMh8c7EI8lcBTYsKIi6t8GxSLb+Jouyfv+PK2++lUs/vOwXaN3u+tcUVn+owDN8tNOqLzYR4sibKAMeZouC7shMdwigdGrLtlnhU1e0TuZxRIB4Ow+YiDNVBBnFGLNjWgGSMORqyxm5GgQjtLwgXrAr9JKC6DQLQneKJsFsiLRsdiK1TqtX7ZKKLFMZsS2Z4rlzXzjaOGX6NV97tWDYXpu5VgCKJB1WCdt5iUgywBYCBS/LAMxXDVy9o/KAJdLO+AgRGlnAZJhH+urE8M02jAMsgW7fhp9JqDDKsX5lLpGoUCptHJmFRY3O1Ag9UJ8YjgNsDZI7iBZkbWj1fOGxqHSTyn1SfJAdB3EiHEtrkSxEzGLKl1KPPC8luytibqZ6m7qpJQUo3P91tLe5ZAgzQ3nLZsJIvadqM/BMnJAgEW4Z9unGz25/tPHJJ5/QfSVhBUtizIte3bY8FToqIPFV+QKdhZNo7AA67MDcfyTDgCG9vdCFtK8fD22UBsHRExqLg3EA1BDmoXE4Od9jnM3KvIPXphob95OV020uT2hFQEsGaQQxherSb+iy0lDVneruXq3fERbKygMKXqg4uArNwnb/B50PPmiN6C5tHKK8r68UMgMXePVOVVXnBB8jEPMoQ9ggNf3gc80RyzzzZSFkZibTwJoU3m1cv3nzJS/tc3TU51y+/dH41b/fSSpjkVf0SOE3peaikjRKBsq8J7HMSb6CkI6VDF1IO/LnVHaa94VK6ZzCLTo3FQ386caHH6C/v25zMIi+iygUHMhHy6yoJDZl6++oRcoAqJFxb5IpDUlQWo6bpLtI4/Z/upN2LAcWapYzVkDAl2lNSEAssfNNSrYqx4rbRa1aI4EziDshJBBKzqbvehGfMTtgFEbdaVqXCbW3N5NLuGrlQxGNnQUVWZhA8kQLNVV/DldACusA447DyckyqXRbBc7FC9p4WG3NdZ9xURGwe22+PNxdf6lHLeVrAVr2QFk7Pt343cc/fuZk61/FEgr7fg6ogRflIp8rvFO27d5///Jvfl7Yx8HOa5bNv7g6lHCPYw3ndHL3HKuF0HaAHb53iQkxxitnBdctSeVNxxsiUsGNFbGcy1JzyrlOiINJ/n9yRSXlmtZySJDRmKiDI5FYdX4r7fQTx76khC70CzGbiWH9lVdeaU285KGreG/IaJqoS8iQ6E48Nx30O71FigyqwCJ6tClHEkjktY14RtcozAT58xtxQo4JVqFTfggXwgDX+6KY53DjEEvJHxS2rVlAI9ytYvwkNylGb3O26JUKj5l+NRm1u/4Nhol+NX9kUvdgBCoPBbsQ1fh/RzWmqEb/ParPPCqqHz4aqt8rn+NhPV+MauX1B6DawKpxcoWrhy88FGNGsJyj48U8Tk1YeyjSPMAvFISqCPOYMbcIukdmc0aZL84jvv6LDI+lBTxWUhZ+PY94cwwnQLJ6stojBw/smK2icicR9O6TCneTNSBz93Yrskxuojzh58pMZejDPDAxLJ/1kksaNwdsz28BBKr0IjlyGZAQk4s6fTjqDpNGEQlxEGVG4YnQHHGXzEzzzZ/6touqXzYo3mbmwJSvGM4YcPaWqmslHggBFtCo2SgPHIJcCLqwOQVYpVtC5eXMcvrpe0c/LL1aKtUGef/Sw5l/jvAfOo+iH9fYRx6XBiIwxuWFBBdmecvJGF7Chpe3eERwJCAa9BEc5G8O8vPnYsWvT05pj51hpF8rjAhGIjWERkS0/CAUYHcPsA0RFwFiFKrhDh0poSI5FdEsL076/JOVh4nAGhOBlOvXPvv9fzUnMe8Ubn4pyeDvwAog7ReTApTy5161tD3/bcd1vVjm7uMu7YktfqQbyMPwjsbdGtD+P/q0GXOlfP6B4h5RqVnmlebLxUJTmlfHZ3N6c7nDVetBUgUl75HEpK5Z5dT/STmttEh4WH39MEpcXpQX3ngUXnx7jhds4SJiXJt3/bnCZPxZJAYYtExmeHI+M3yXD9dTC8LFFSf5MAmQvsG7O2C6D0yMVA23n24TGHY44Y8o6LexWnBCuITxTd9zsBMx+lSUHgexW9wZG7vX85JP5IThvIAaiZPVgmogS4vsaeyFgvQtBTA+sNNZd3I0eX1xwcZVMJ9KPp6n0S8u1BhhaRRXlqxHpsTnM5T4woNLtkzZsFpMj5WljcUEWRbxQdLaXWZzk4aWvBPCIY03U57EkgfQiV34bgPF7uZdaWTZENDgbhc1rDLwp4aDzq8kE7+vCd5tm/hVRtcYW8Oo6Tr2cRe148nt+swPQNQlF4IVAANetmFTbs9M/O4w6pDvZNcK0KFF8hV5P4Jfv9IRDceHfWvURUugJ6vItaiBrXg7M2VqhZzcZu9y0+jpV/amwQzm8L3Ew64F+9MQmHu31uIO5LU7Qyc4PjDv9N2khxXJyEgkX/+SMqDENmuPDu3gEZFGr8lUyd0kYZ6B+zjAxcR9+Qzbx4It7vzOsH0AtndZ2/cVmrSWmhYsjHAhf4W1e9+RaVtEf4Gw3A3QiT+7zIUkXqAlpB47iwkwfy3C5KW4hxc7gWdbOG1D9EubU+OI/LoguLhJxuM3+mpDripVrSEH7EVLroZswidr+DkZPU4mIWOUWl/T+t09PG6vNhBFVRz77mE4Ia/uJPh5xzc8Qejv9B7KlUuUKqUiqqx+NlSJsTLeOGPKY8s6a2fYPjZsr59h+1hK0QBfnXy1R5on+pYrxj/iQVeaC9PLBPYwGUlbLJrMkjnNlFStWm83hP+3QOrP0vgRMMV8FK+zFwFxNjWp7KUm+wVcELXJ7/bwRZwkFfxeHqUjfIZ6MSf/3akRvDYD7FUCtvWYzocjm/6YIKZZcotfHKc58r4Vf4z5rNlG/9Aj42eKyhp9lU3GwUydyMV5h41Nf2OLx22Rn++RXKceWh47Ktn9HJeL57JhmzhMfBjQYExT/K+P4jZ5DYffEsZFZUDDME3XEbrqQBQOLMesG7ZdH03DJTEYTsDUKP8H]],
  },
  ["Minimal_Dark 1440p"] = {
    auras2 = {
      enabled = true,
      perUnit = {
        boss1 = {
          filters = {
            _msufA2_filtersMigrated_v2 = true,
            buffs = {
              includeBoss = false,
              includeStealable = false,
              onlyMine = false,
            },
            debuffs = {
              dispelCurse = false,
              dispelDisease = false,
              dispelEnrage = false,
              dispelMagic = false,
              dispelPoison = false,
              includeBoss = false,
              includeDispellable = false,
              onlyMine = false,
            },
            enabled = true,
            hidePermanent = false,
            onlyBossAuras = false,
          },
          layout = {
            cooldownTextSize = 14,
            iconSize = 23,
            offsetX = 0,
            offsetY = 0,
            spacing = 0,
            stackTextSize = 14,
          },
          layoutShared = {
          },
          overrideFilters = false,
          overrideLayout = true,
          overrideSharedLayout = false,
        },
        boss2 = {
          filters = {
            _msufA2_filtersMigrated_v2 = true,
            buffs = {
              includeBoss = false,
              includeStealable = false,
              onlyMine = false,
            },
            debuffs = {
              dispelCurse = false,
              dispelDisease = false,
              dispelEnrage = false,
              dispelMagic = false,
              dispelPoison = false,
              includeBoss = false,
              includeDispellable = false,
              onlyMine = false,
            },
            enabled = true,
            hidePermanent = false,
            onlyBossAuras = false,
          },
          layout = {
            cooldownTextSize = 14,
            iconSize = 23,
            offsetX = 0,
            offsetY = 0,
            spacing = 0,
            stackTextSize = 14,
          },
          layoutShared = {
          },
          overrideFilters = false,
          overrideLayout = true,
          overrideSharedLayout = false,
        },
        boss3 = {
          filters = {
            _msufA2_filtersMigrated_v2 = true,
            buffs = {
              includeBoss = false,
              includeStealable = false,
              onlyMine = false,
            },
            debuffs = {
              dispelCurse = false,
              dispelDisease = false,
              dispelEnrage = false,
              dispelMagic = false,
              dispelPoison = false,
              includeBoss = false,
              includeDispellable = false,
              onlyMine = false,
            },
            enabled = true,
            hidePermanent = false,
            onlyBossAuras = false,
          },
          layout = {
            cooldownTextSize = 14,
            iconSize = 23,
            offsetX = 0,
            offsetY = 0,
            spacing = 0,
            stackTextSize = 14,
          },
          layoutShared = {
          },
          overrideFilters = false,
          overrideLayout = true,
          overrideSharedLayout = false,
        },
        boss4 = {
          filters = {
            _msufA2_filtersMigrated_v2 = true,
            buffs = {
              includeBoss = false,
              includeStealable = false,
              onlyMine = false,
            },
            debuffs = {
              dispelCurse = false,
              dispelDisease = false,
              dispelEnrage = false,
              dispelMagic = false,
              dispelPoison = false,
              includeBoss = false,
              includeDispellable = false,
              onlyMine = false,
            },
            enabled = true,
            hidePermanent = false,
            onlyBossAuras = false,
          },
          layout = {
            cooldownTextSize = 14,
            iconSize = 23,
            offsetX = 0,
            offsetY = 0,
            spacing = 0,
            stackTextSize = 14,
          },
          layoutShared = {
          },
          overrideFilters = false,
          overrideLayout = true,
          overrideSharedLayout = false,
        },
        boss5 = {
          filters = {
            _msufA2_filtersMigrated_v2 = true,
            buffs = {
              includeBoss = false,
              includeStealable = false,
              onlyMine = false,
            },
            debuffs = {
              dispelCurse = false,
              dispelDisease = false,
              dispelEnrage = false,
              dispelMagic = false,
              dispelPoison = false,
              includeBoss = false,
              includeDispellable = false,
              onlyMine = false,
            },
            enabled = true,
            hidePermanent = false,
            onlyBossAuras = false,
          },
          layout = {
            cooldownTextSize = 14,
            iconSize = 23,
            offsetX = 0,
            offsetY = 0,
            spacing = 0,
            stackTextSize = 14,
          },
          layoutShared = {
          },
          overrideFilters = false,
          overrideLayout = true,
          overrideSharedLayout = false,
        },
        focus = {
          filters = {
            _msufA2_filtersMigrated_v2 = true,
            buffs = {
              includeBoss = false,
              includeStealable = false,
              onlyMine = false,
            },
            debuffs = {
              dispelCurse = false,
              dispelDisease = false,
              dispelEnrage = false,
              dispelMagic = false,
              dispelPoison = false,
              includeBoss = false,
              includeDispellable = false,
              onlyMine = false,
            },
            enabled = true,
            hidePermanent = false,
            onlyBossAuras = false,
          },
          layout = {
            offsetX = 1,
            offsetY = 0,
          },
          layoutShared = {
          },
          overrideFilters = false,
          overrideLayout = true,
          overrideSharedLayout = false,
        },
        player = {
          filters = {
            _msufA2_filtersMigrated_v2 = true,
            buffs = {
              includeBoss = false,
              includeStealable = false,
              onlyMine = false,
            },
            debuffs = {
              dispelCurse = false,
              dispelDisease = false,
              dispelEnrage = false,
              dispelMagic = false,
              dispelPoison = false,
              includeBoss = false,
              includeDispellable = false,
              onlyMine = false,
            },
            enabled = true,
            hidePermanent = false,
            onlyBossAuras = false,
          },
          layout = {
            offsetX = 0,
            offsetY = 0,
          },
          layoutShared = {
          },
          overrideFilters = false,
          overrideLayout = false,
          overrideSharedLayout = false,
        },
        target = {
          filters = {
            _msufA2_filtersMigrated_v2 = true,
            buffs = {
              includeBoss = false,
              includeStealable = false,
              onlyMine = false,
            },
            debuffs = {
              dispelCurse = false,
              dispelDisease = false,
              dispelEnrage = false,
              dispelMagic = false,
              dispelPoison = false,
              includeBoss = false,
              includeDispellable = false,
              onlyMine = false,
            },
            enabled = true,
            hidePermanent = false,
            onlyBossAuras = false,
          },
          layout = {
            cooldownTextSize = 14,
            iconSize = 26,
            offsetX = -1,
            offsetY = -2,
            spacing = 0,
            stackTextSize = 14,
          },
          layoutShared = {
          },
          overrideFilters = false,
          overrideLayout = true,
          overrideSharedLayout = false,
        },
      },
      shared = {
        _msufA2_migrated_v11f = true,
        bossEditTogether = true,
        buffOffsetY = 30,
        cooldownTextSize = 14,
        filters = {
          _msufA2_sharedFiltersMigrated_v1 = true,
          buffs = {
            includeBoss = false,
            includeStealable = false,
            onlyMine = false,
          },
          debuffs = {
            dispelCurse = false,
            dispelDisease = false,
            dispelEnrage = false,
            dispelMagic = false,
            dispelPoison = false,
            includeBoss = false,
            includeDispellable = false,
            onlyMine = false,
          },
          enabled = true,
          hidePermanent = false,
          onlyBossAuras = false,
        },
        growth = "RIGHT",
        hidePermanent = false,
        highlightDispellableDebuffs = true,
        highlightOwnBuffs = false,
        highlightOwnDebuffs = false,
        highlightStealableBuffs = true,
        iconSize = 26,
        layoutMode = "SINGLE",
        masqueEnabled = false,
        maxBuffs = 12,
        maxDebuffs = 12,
        maxIcons = 12,
        offsetX = 0,
        offsetY = 6,
        onlyMyBuffs = false,
        onlyMyDebuffs = false,
        perRow = 10,
        rowWrap = "UP",
        showBuffs = true,
        showCooldownSwipe = true,
        showDebuffs = true,
        showInEditMode = true,
        showStackCount = true,
        showTooltip = true,
        spacing = 2,
        stackCountAnchor = "TOPRIGHT",
        stackTextSize = 14,
      },
      showBoss = true,
      showFocus = false,
      showTarget = true,
    },
    bars = {
      barOutlineThickness = 2,
      embedPowerBarIntoHealth = true,
      powerBarHeight = 4,
      showBarBorder = true,
      showBossPowerBar = false,
      showFocusPowerBar = false,
      showPlayerPowerBar = false,
      showTargetPowerBar = true,
    },
    boss = {
      enabled = true,
      height = 35,
      hpOffsetX = -4,
      hpOffsetY = -4,
      hpTextSpacerEnabled = false,
      hpTextSpacerX = 135,
      nameFontSize = 11,
      nameOffsetX = 7,
      nameOffsetY = -4,
      offsetX = 617,
      offsetY = 575,
      portraitMode = "OFF",
      powerFontSize = 10,
      powerOffsetX = -4,
      powerOffsetY = 4,
      raidMarkerAnchor = "TOPLEFT",
      raidMarkerOffsetX = 21,
      raidMarkerOffsetY = 3,
      raidMarkerSize = 14,
      showHP = true,
      showInterrupt = true,
      showLevelIndicator = false,
      showName = true,
      showPower = true,
      showRaidMarker = true,
      spacing = -111,
      width = 264,
    },
    classColors = {
    },
    focus = {
      enabled = true,
      height = 27,
      hpFontSize = 10,
      hpOffsetX = -4,
      hpOffsetY = -4,
      hpTextSpacerEnabled = true,
      hpTextSpacerX = 143,
      nameFontSize = 12,
      nameOffsetX = 1,
      nameOffsetY = -12,
      offsetX = -158,
      offsetY = -83,
      portraitMode = "OFF",
      powerOffsetX = -4,
      powerOffsetY = 4,
      raidMarkerAnchor = "TOPLEFT",
      raidMarkerOffsetX = 21,
      raidMarkerOffsetY = 3,
      raidMarkerSize = 14,
      showHP = true,
      showInterrupt = true,
      showLevelIndicator = false,
      showName = true,
      showPower = false,
      showRaidMarker = true,
      width = 183,
    },
    gameplay = {
      combatFontSize = 24,
      combatOffsetX = -390.00006103516,
      combatOffsetY = -197,
      combatStateColorSync = false,
      combatStateDuration = 1,
      combatStateEnterColor = {
        ["1"] = 1,
        ["2"] = 1,
        ["3"] = 1,
      },
      combatStateEnterText = "+Combat",
      combatStateFontSize = 13,
      combatStateLeaveColor = {
        ["1"] = 0.7,
        ["2"] = 0.7,
        ["3"] = 0.7,
      },
      combatStateLeaveText = "-Combat",
      combatStateOffsetX = 0,
      combatStateOffsetY = 80,
      combatTimerColor = {
        ["1"] = 1,
        ["2"] = 1,
        ["3"] = 1,
      },
      cooldownIcons = false,
      crosshairInRangeColor = {
        ["1"] = 0,
        ["2"] = 1,
        ["3"] = 0,
      },
      crosshairOutRangeColor = {
        ["1"] = 1,
        ["2"] = 0,
        ["3"] = 0,
      },
      crosshairSize = 40,
      crosshairThickness = 2,
      enableCombatCrosshair = false,
      enableCombatCrosshairMeleeRangeColor = false,
      enableCombatStateText = true,
      enableCombatTimer = true,
      enableFirstDanceTimer = false,
      lockCombatState = true,
      lockCombatTimer = true,
      nameplateMeleeSpellID = 53,
      shownGameplayColorsTip = true,
    },
    general = {
      anchorName = "UIParent",
      anchorToCooldown = true,
      auraFontSize = 25,
      aurasDispelBorderColor = {
        ["1"] = 0.2,
        ["2"] = 0.6,
        ["3"] = 1,
      },
      aurasOwnBuffHighlightColor = {
        ["1"] = 1,
        ["2"] = 0.85,
        ["3"] = 0.2,
      },
      aurasOwnDebuffHighlightColor = {
        ["1"] = 1,
        ["2"] = 0.85,
        ["3"] = 0.2,
      },
      aurasStackCountColor = {
        ["1"] = 1,
        ["2"] = 1,
        ["3"] = 1,
      },
      aurasStealableBorderColor = {
        ["1"] = 0,
        ["2"] = 0.75,
        ["3"] = 1,
      },
      barBackgroundTexture = "Solid",
      barBorderStyle = "THIN",
      barMode = "dark",
      barTexture = "Solid",
      boldText = false,
      bossCastIconOffsetX = 0,
      bossCastIconOffsetY = 0,
      bossCastTextOffsetX = 0,
      bossCastTextOffsetY = 0,
      bossCastTimeOffsetX = 0,
      bossCastTimeOffsetY = 0,
      bossCastbarHeight = 12,
      bossCastbarOffsetX = 3,
      bossCastbarOffsetY = -49,
      bossCastbarWidth = 259,
      bossPreviewEnabled = true,
      castbarBackgroundTexture = "Solid",
      castbarBossMatchUnitWidth = false,
      castbarFillDirection = "RTL",
      castbarFocusBarHeight = 10,
      castbarFocusBarWidth = 182,
      castbarFocusIconOffsetX = 0,
      castbarFocusIconOffsetY = 0,
      castbarFocusMatchUnitWidth = false,
      castbarFocusOffsetX = 1,
      castbarFocusOffsetY = -38,
      castbarFocusShowIcon = true,
      castbarFocusShowSpellName = true,
      castbarFocusTextOffsetX = 0,
      castbarFocusTextOffsetY = 0,
      castbarFocusTimeOffsetX = 0,
      castbarFocusTimeOffsetY = 0,
      castbarGlobalHeight = 18,
      castbarGlobalWidth = 200,
      castbarIconOffsetX = 0,
      castbarIconOffsetY = 0,
      castbarInterruptColor = "red",
      castbarInterruptShake = true,
      castbarInterruptibleColor = "turquoise",
      castbarNonInterruptibleColor = "red",
      castbarOutlineThickness = 1,
      castbarPlayerBarHeight = 18,
      castbarPlayerBarWidth = 258,
      castbarPlayerIconOffsetX = 0,
      castbarPlayerIconOffsetY = 0,
      castbarPlayerMatchUnitWidth = false,
      castbarPlayerOffsetX = 0,
      castbarPlayerOffsetY = -43,
      castbarPlayerPreviewEnabled = true,
      castbarPlayerShowIcon = true,
      castbarPlayerShowSpellName = true,
      castbarPlayerTextOffsetX = 0,
      castbarPlayerTextOffsetY = 0,
      castbarPlayerTimeOffsetX = -2,
      castbarPlayerTimeOffsetY = 0,
      castbarShakeStrength = 4,
      castbarShowChannelTicks = false,
      castbarShowGlow = false,
      castbarShowIcon = true,
      castbarShowSpellName = true,
      castbarSpellNameFontSize = 0,
      castbarTargetBarHeight = 18,
      castbarTargetBarWidth = 258,
      castbarTargetIconOffsetX = 0,
      castbarTargetIconOffsetY = 0,
      castbarTargetMatchUnitWidth = false,
      castbarTargetOffsetX = 0,
      castbarTargetOffsetY = -43,
      castbarTargetShowIcon = true,
      castbarTargetShowSpellName = true,
      castbarTargetTextOffsetX = 0,
      castbarTargetTextOffsetY = 0,
      castbarTargetTimeOffsetX = -2,
      castbarTargetTimeOffsetY = 0,
      castbarTexture = "Solid",
      castbarUnifiedDirection = false,
      castbarUpdateInterval = 0.019999999552965,
      classBarBgB = 1,
      classBarBgG = 1,
      classBarBgR = 1,
      combatStateIndicatorPos = "TOPLEFT",
      darkBarGray = 0.07,
      darkBarTone = "black",
      darkBgBrightness = 0.25,
      darkMode = true,
      disableUnitInfoTooltips = true,
      editModeBgAlpha = 0.5,
      editModeGridStep = 16,
      editModeHideWhiteArrows = true,
      editModeSnapEnabled = false,
      editModeSnapMode = "grid",
      editModeSnapModeFrames = false,
      editModeSnapModeGrid = true,
      editModeSnapToGrid = false,
      empowerColorStages = true,
      empowerStageBlink = true,
      empowerStageBlinkTime = 0.25,
      enableAbsorbBar = true,
      enableBossCastbar = true,
      enableFocusCastbar = true,
      enableFocusKickIcon = false,
      enableGradient = false,
      enablePlayerCastbar = true,
      enableTargetCastbar = true,
      flashFullH = 732.00024414062,
      flashFullPoint = "TOPLEFT",
      flashFullRelPoint = "TOPLEFT",
      flashFullW = 877.08367919922,
      flashFullX = 346.99996948242,
      flashFullXpx = 185.0666600426,
      flashFullY = -141.41700744629,
      flashFullYpx = -75.422407904939,
      focusKickIconHeight = 41,
      focusKickIconOffsetX = 147,
      focusKickIconOffsetY = -5,
      focusKickIconWidth = 43,
      focusKickTextSize = 16,
      fontColor = "white",
      fontKey = "EXPRESSWAY_BOLD",
      fontSize = 14,
      frameUpdateInterval = 0.049999997019768,
      globalUiScalePreset = "1440p",
      globalUiScaleValue = 0.53333333333333,
      gradientDirDown = false,
      gradientDirLeft = false,
      gradientDirRight = true,
      gradientDirUp = false,
      gradientDirection = "RIGHT",
      gradientStrength = 0.45,
      highlightColor = "white",
      highlightEnabled = true,
      hpFontSize = 14,
      hpSpacerSelectedUnitKey = "focus",
      hpTextMode = "FULL_PLUS_PERCENT",
      hpTextSeparator = "-",
      hpTextSpacerEnabled = false,
      hpTextSpacerX = 140,
      incomingResIndicatorPos = "TOPRIGHT",
      leaderIconOffsetX = 0,
      leaderIconOffsetY = 3,
      levelIndicatorAnchor = "NAMERIGHT",
      levelIndicatorOffsetX = 0,
      levelIndicatorOffsetY = 0,
      linkEditModes = true,
      minimapIconDB = {
        hide = false,
        minimapPos = 220,
        radius = 80,
      },
      nameClassColor = true,
      nameFontSize = 14,
      noOutline = false,
      npcNameRed = false,
      playerCastbarOverrideB = 1,
      playerCastbarOverrideEnabled = true,
      playerCastbarOverrideG = 1,
      playerCastbarOverrideMode = "CLASS",
      playerCastbarOverrideR = 1,
      powerFontSize = 14,
      powerTextMode = "FULL_PLUS_PERCENT",
      powerTextSeparator = "-",
      raidMarkerSize = 14,
      roundedUnitframes = false,
      shortenNameClipSide = "LEFT",
      shortenNameFrontMaskPx = 14,
      shortenNameMaxChars = 6,
      showBossCastIcon = true,
      showBossCastName = true,
      showBossCastTime = true,
      showCombatStateIndicator = true,
      showFocusCastTime = true,
      showIncomingResIndicator = true,
      showLeaderIcon = true,
      showLevel = true,
      showMinimapIcon = true,
      showPlayerCastTime = true,
      showRaidMarker = true,
      showTargetCastTime = true,
      showTotalAbsorbAmount = false,
      statusIndicators = {
        showAFK = true,
        showDND = true,
        showDead = true,
        showGhost = true,
      },
      textBackdrop = false,
      tipCycleIndex = 3,
      unitInfoTooltipStyle = "classic",
      useBarBorder = true,
      useClassColors = false,
      useCustomFontColor = false,
    },
    npcColors = {
    },
    pet = {
      enabled = false,
      height = 30,
      hpOffsetX = -4,
      hpOffsetY = -4,
      hpTextSpacerEnabled = false,
      hpTextSpacerX = 140,
      nameOffsetX = 4,
      nameOffsetY = -4,
      offsetX = -260,
      offsetY = 135,
      portraitMode = "OFF",
      powerOffsetX = -4,
      powerOffsetY = 4,
      raidMarkerAnchor = "TOPLEFT",
      raidMarkerOffsetX = 21,
      raidMarkerOffsetY = 3,
      raidMarkerSize = 14,
      showHP = true,
      showInterrupt = true,
      showLevelIndicator = false,
      showName = true,
      showPower = true,
      showRaidMarker = true,
      width = 220,
    },
    player = {
      castbar = {
        channelTickCount = 5,
        channelTickPosPct = {
        },
        channelTickPreviewDuration = 2.5,
        channelTickPreviewLoop = true,
        channelTickUseCustom = false,
      },
      enabled = true,
      height = 27,
      hpOffsetX = -5,
      hpOffsetY = -5,
      hpTextSpacerEnabled = true,
      hpTextSpacerX = 197,
      nameOffsetX = 23,
      nameOffsetY = -4,
      offsetX = 14,
      offsetY = 0,
      portraitMode = "OFF",
      powerOffsetX = -4,
      powerOffsetY = 4,
      raidMarkerAnchor = "TOPLEFT",
      raidMarkerOffsetX = -19,
      raidMarkerOffsetY = -1,
      raidMarkerSize = 20,
      showHP = true,
      showInterrupt = true,
      showLevelIndicator = false,
      showName = false,
      showPower = false,
      showRaidMarker = true,
      width = 260,
    },
    shortenNames = false,
    target = {
      enabled = true,
      height = 27,
      hpOffsetX = -4,
      hpOffsetY = -4,
      hpTextSpacerEnabled = false,
      hpTextSpacerX = 140,
      leaderIconAnchor = "TOPRIGHT",
      nameOffsetX = 4,
      nameOffsetY = -4,
      offsetX = -16,
      offsetY = 0,
      portraitMode = "OFF",
      powerOffsetX = -4,
      powerOffsetY = 4,
      raidMarkerAnchor = "TOPRIGHT",
      raidMarkerOffsetX = 20,
      raidMarkerOffsetY = -2,
      raidMarkerSize = 20,
      showHP = true,
      showInterrupt = true,
      showLevelIndicator = false,
      showName = true,
      showPower = false,
      showRaidMarker = true,
      width = 260,
    },
    targettarget = {
      enabled = true,
      height = 27,
      hpOffsetX = -4,
      hpOffsetY = -4,
      hpTextSpacerEnabled = false,
      hpTextSpacerX = 140,
      nameOffsetX = 4,
      nameOffsetY = -4,
      offsetX = 122,
      offsetY = -40,
      portraitMode = "OFF",
      powerOffsetX = -4,
      powerOffsetY = 4,
      raidMarkerAnchor = "TOPLEFT",
      raidMarkerOffsetX = 21,
      raidMarkerOffsetY = 3,
      raidMarkerSize = 14,
      showHP = false,
      showInterrupt = true,
      showLevelIndicator = false,
      showName = true,
      showPower = false,
      showRaidMarker = true,
      showToTInTargetName = false,
      totInlineSeparator = ">>>",
      width = 183,
    },
  },
  ["Rounded_Unitframes 1440p"] = {
  _msufWarning = "Requires manual toggle: go to Modules → Styles and toggle the Rounded Unitframes module OFF/ON once after loading this preset.",
  auras2 = {
    enabled = true,
    perUnit = {
      boss1 = {
        filters = {
          _msufA2_filtersMigrated_v2 = true,
          buffs = {
            includeBoss = false,
            includeStealable = false,
            onlyMine = false,
          },
          debuffs = {
            dispelCurse = false,
            dispelDisease = false,
            dispelEnrage = false,
            dispelMagic = false,
            dispelPoison = false,
            includeBoss = false,
            includeDispellable = false,
            onlyMine = false,
          },
          enabled = true,
          hidePermanent = false,
          onlyBossAuras = false,
        },
        layout = {
          cooldownTextSize = 14,
          iconSize = 23,
          offsetX = 0,
          offsetY = 0,
          spacing = 0,
          stackTextSize = 14,
        },
        layoutShared = {
        },
        overrideFilters = false,
        overrideLayout = true,
        overrideSharedLayout = false,
      },
      boss2 = {
        filters = {
          _msufA2_filtersMigrated_v2 = true,
          buffs = {
            includeBoss = false,
            includeStealable = false,
            onlyMine = false,
          },
          debuffs = {
            dispelCurse = false,
            dispelDisease = false,
            dispelEnrage = false,
            dispelMagic = false,
            dispelPoison = false,
            includeBoss = false,
            includeDispellable = false,
            onlyMine = false,
          },
          enabled = true,
          hidePermanent = false,
          onlyBossAuras = false,
        },
        layout = {
          cooldownTextSize = 14,
          iconSize = 23,
          offsetX = 0,
          offsetY = 0,
          spacing = 0,
          stackTextSize = 14,
        },
        layoutShared = {
        },
        overrideFilters = false,
        overrideLayout = true,
        overrideSharedLayout = false,
      },
      boss3 = {
        filters = {
          _msufA2_filtersMigrated_v2 = true,
          buffs = {
            includeBoss = false,
            includeStealable = false,
            onlyMine = false,
          },
          debuffs = {
            dispelCurse = false,
            dispelDisease = false,
            dispelEnrage = false,
            dispelMagic = false,
            dispelPoison = false,
            includeBoss = false,
            includeDispellable = false,
            onlyMine = false,
          },
          enabled = true,
          hidePermanent = false,
          onlyBossAuras = false,
        },
        layout = {
          cooldownTextSize = 14,
          iconSize = 23,
          offsetX = 0,
          offsetY = 0,
          spacing = 0,
          stackTextSize = 14,
        },
        layoutShared = {
        },
        overrideFilters = false,
        overrideLayout = true,
        overrideSharedLayout = false,
      },
      boss4 = {
        filters = {
          _msufA2_filtersMigrated_v2 = true,
          buffs = {
            includeBoss = false,
            includeStealable = false,
            onlyMine = false,
          },
          debuffs = {
            dispelCurse = false,
            dispelDisease = false,
            dispelEnrage = false,
            dispelMagic = false,
            dispelPoison = false,
            includeBoss = false,
            includeDispellable = false,
            onlyMine = false,
          },
          enabled = true,
          hidePermanent = false,
          onlyBossAuras = false,
        },
        layout = {
          cooldownTextSize = 14,
          iconSize = 23,
          offsetX = 0,
          offsetY = 0,
          spacing = 0,
          stackTextSize = 14,
        },
        layoutShared = {
        },
        overrideFilters = false,
        overrideLayout = true,
        overrideSharedLayout = false,
      },
      boss5 = {
        filters = {
          _msufA2_filtersMigrated_v2 = true,
          buffs = {
            includeBoss = false,
            includeStealable = false,
            onlyMine = false,
          },
          debuffs = {
            dispelCurse = false,
            dispelDisease = false,
            dispelEnrage = false,
            dispelMagic = false,
            dispelPoison = false,
            includeBoss = false,
            includeDispellable = false,
            onlyMine = false,
          },
          enabled = true,
          hidePermanent = false,
          onlyBossAuras = false,
        },
        layout = {
          cooldownTextSize = 14,
          iconSize = 23,
          offsetX = 0,
          offsetY = 0,
          spacing = 0,
          stackTextSize = 14,
        },
        layoutShared = {
        },
        overrideFilters = false,
        overrideLayout = true,
        overrideSharedLayout = false,
      },
      focus = {
        filters = {
          _msufA2_filtersMigrated_v2 = true,
          buffs = {
            includeBoss = false,
            includeStealable = false,
            onlyMine = false,
          },
          debuffs = {
            dispelCurse = false,
            dispelDisease = false,
            dispelEnrage = false,
            dispelMagic = false,
            dispelPoison = false,
            includeBoss = false,
            includeDispellable = false,
            onlyMine = false,
          },
          enabled = true,
          hidePermanent = false,
          onlyBossAuras = false,
        },
        layout = {
          offsetX = 1,
          offsetY = 0,
        },
        layoutShared = {
        },
        overrideFilters = false,
        overrideLayout = true,
        overrideSharedLayout = false,
      },
      player = {
        filters = {
          _msufA2_filtersMigrated_v2 = true,
          buffs = {
            includeBoss = false,
            includeStealable = false,
            onlyMine = false,
          },
          debuffs = {
            dispelCurse = false,
            dispelDisease = false,
            dispelEnrage = false,
            dispelMagic = false,
            dispelPoison = false,
            includeBoss = false,
            includeDispellable = false,
            onlyMine = false,
          },
          enabled = true,
          hidePermanent = false,
          onlyBossAuras = false,
        },
        layout = {
          offsetX = 0,
          offsetY = 0,
        },
        layoutShared = {
        },
        overrideFilters = false,
        overrideLayout = false,
        overrideSharedLayout = false,
      },
      target = {
        filters = {
          _msufA2_filtersMigrated_v2 = true,
          buffs = {
            includeBoss = false,
            includeStealable = false,
            onlyMine = false,
          },
          debuffs = {
            dispelCurse = false,
            dispelDisease = false,
            dispelEnrage = false,
            dispelMagic = false,
            dispelPoison = false,
            includeBoss = false,
            includeDispellable = false,
            onlyMine = false,
          },
          enabled = true,
          hidePermanent = false,
          onlyBossAuras = false,
        },
        layout = {
          cooldownTextSize = 14,
          iconSize = 26,
          offsetX = -1,
          offsetY = -2,
          spacing = 0,
          stackTextSize = 14,
        },
        layoutShared = {
        },
        overrideFilters = false,
        overrideLayout = true,
        overrideSharedLayout = false,
      },
    },
    shared = {
      _msufA2_migrated_v11f = true,
      bossEditTogether = true,
      buffOffsetY = 30,
      cooldownTextSize = 14,
      filters = {
        _msufA2_sharedFiltersMigrated_v1 = true,
        buffs = {
          includeBoss = false,
          includeStealable = false,
          onlyMine = false,
        },
        debuffs = {
          dispelCurse = false,
          dispelDisease = false,
          dispelEnrage = false,
          dispelMagic = false,
          dispelPoison = false,
          includeBoss = false,
          includeDispellable = false,
          onlyMine = false,
        },
        enabled = true,
        hidePermanent = false,
        onlyBossAuras = false,
      },
      growth = "RIGHT",
      hidePermanent = false,
      highlightDispellableDebuffs = true,
      highlightOwnBuffs = false,
      highlightOwnDebuffs = false,
      highlightStealableBuffs = true,
      iconSize = 26,
      layoutMode = "SINGLE",
      masqueEnabled = false,
      maxBuffs = 12,
      maxDebuffs = 12,
      maxIcons = 12,
      offsetX = 0,
      offsetY = 6,
      onlyMyBuffs = false,
      onlyMyDebuffs = false,
      perRow = 10,
      rowWrap = "UP",
      showBuffs = true,
      showCooldownSwipe = true,
      showDebuffs = true,
      showInEditMode = true,
      showStackCount = true,
      showTooltip = true,
      spacing = 2,
      stackCountAnchor = "TOPRIGHT",
      stackTextSize = 14,
    },
    showBoss = true,
    showFocus = false,
    showTarget = true,
  },
  bars = {
    barOutlineThickness = 2,
    embedPowerBarIntoHealth = true,
    powerBarHeight = 4,
    showBarBorder = true,
    showBossPowerBar = false,
    showFocusPowerBar = false,
    showPlayerPowerBar = false,
    showTargetPowerBar = true,
  },
  boss = {
    enabled = true,
    height = 35,
    hpOffsetX = -4,
    hpOffsetY = -4,
    hpTextSpacerEnabled = false,
    hpTextSpacerX = 135,
    nameFontSize = 11,
    nameOffsetX = 27,
    nameOffsetY = -10,
    offsetX = 617,
    offsetY = 575,
    portraitMode = "OFF",
    powerFontSize = 10,
    powerOffsetX = -4,
    powerOffsetY = 4,
    raidMarkerAnchor = "TOPLEFT",
    raidMarkerOffsetX = 21,
    raidMarkerOffsetY = 3,
    raidMarkerSize = 14,
    showHP = true,
    showInterrupt = true,
    showLevelIndicator = false,
    showName = true,
    showPower = true,
    showRaidMarker = true,
    spacing = -111,
    width = 264,
  },
  classColors = {
  },
  focus = {
    enabled = true,
    height = 27,
    hpFontSize = 10,
    hpOffsetX = -19,
    hpOffsetY = -7,
    hpTextSpacerEnabled = true,
    hpTextSpacerX = 103,
    nameFontSize = 12,
    nameOffsetX = 71,
    nameOffsetY = -12,
    offsetX = -158,
    offsetY = -83,
    portraitMode = "OFF",
    powerOffsetX = -4,
    powerOffsetY = 4,
    raidMarkerAnchor = "TOPLEFT",
    raidMarkerOffsetX = 21,
    raidMarkerOffsetY = 3,
    raidMarkerSize = 14,
    showHP = true,
    showInterrupt = true,
    showLevelIndicator = false,
    showName = true,
    showPower = false,
    showRaidMarker = true,
    width = 183,
  },
  gameplay = {
    combatFontSize = 24,
    combatOffsetX = -390.00006103516,
    combatOffsetY = -197,
    combatStateColorSync = false,
    combatStateDuration = 1,
    combatStateEnterColor = {
      ["1"] = 1,
      ["2"] = 1,
      ["3"] = 1,
    },
    combatStateEnterText = "+Combat",
    combatStateFontSize = 13,
    combatStateLeaveColor = {
      ["1"] = 0.7,
      ["2"] = 0.7,
      ["3"] = 0.7,
    },
    combatStateLeaveText = "-Combat",
    combatStateOffsetX = 0,
    combatStateOffsetY = 80,
    combatTimerColor = {
      ["1"] = 1,
      ["2"] = 1,
      ["3"] = 1,
    },
    cooldownIcons = false,
    crosshairInRangeColor = {
      ["1"] = 0,
      ["2"] = 1,
      ["3"] = 0,
    },
    crosshairOutRangeColor = {
      ["1"] = 1,
      ["2"] = 0,
      ["3"] = 0,
    },
    crosshairSize = 40,
    crosshairThickness = 2,
    enableCombatCrosshair = false,
    enableCombatCrosshairMeleeRangeColor = false,
    enableCombatStateText = true,
    enableCombatTimer = true,
    enableFirstDanceTimer = false,
    lockCombatState = true,
    lockCombatTimer = true,
    nameplateMeleeSpellID = 53,
    shownGameplayColorsTip = true,
  },
  general = {
    anchorName = "UIParent",
    anchorToCooldown = true,
    auraFontSize = 25,
    aurasDispelBorderColor = {
      ["1"] = 0.2,
      ["2"] = 0.6,
      ["3"] = 1,
    },
    aurasOwnBuffHighlightColor = {
      ["1"] = 1,
      ["2"] = 0.85,
      ["3"] = 0.2,
    },
    aurasOwnDebuffHighlightColor = {
      ["1"] = 1,
      ["2"] = 0.85,
      ["3"] = 0.2,
    },
    aurasStackCountColor = {
      ["1"] = 1,
      ["2"] = 1,
      ["3"] = 1,
    },
    aurasStealableBorderColor = {
      ["1"] = 0,
      ["2"] = 0.75,
      ["3"] = 1,
    },
    barBackgroundTexture = "Solid",
    barBorderStyle = "THIN",
    barMode = "dark",
    barTexture = "Solid",
    boldText = false,
    bossCastIconOffsetX = 0,
    bossCastIconOffsetY = 0,
    bossCastTextOffsetX = 0,
    bossCastTextOffsetY = 0,
    bossCastTimeOffsetX = 0,
    bossCastTimeOffsetY = 0,
    bossCastbarHeight = 12,
    bossCastbarOffsetX = 3,
    bossCastbarOffsetY = -49,
    bossCastbarWidth = 259,
    bossPreviewEnabled = true,
    castbarBackgroundTexture = "Solid",
    castbarBossMatchUnitWidth = false,
    castbarFillDirection = "RTL",
    castbarFocusBarHeight = 10,
    castbarFocusBarWidth = 182,
    castbarFocusIconOffsetX = 0,
    castbarFocusIconOffsetY = 0,
    castbarFocusMatchUnitWidth = false,
    castbarFocusOffsetX = 1,
    castbarFocusOffsetY = -38,
    castbarFocusShowIcon = true,
    castbarFocusShowSpellName = true,
    castbarFocusTextOffsetX = 0,
    castbarFocusTextOffsetY = 0,
    castbarFocusTimeOffsetX = 0,
    castbarFocusTimeOffsetY = 0,
    castbarGlobalHeight = 18,
    castbarGlobalWidth = 200,
    castbarIconOffsetX = 0,
    castbarIconOffsetY = 0,
    castbarInterruptColor = "red",
    castbarInterruptShake = true,
    castbarInterruptibleColor = "turquoise",
    castbarNonInterruptibleColor = "red",
    castbarOutlineThickness = 1,
    castbarPlayerBarHeight = 18,
    castbarPlayerBarWidth = 258,
    castbarPlayerIconOffsetX = 0,
    castbarPlayerIconOffsetY = 0,
    castbarPlayerMatchUnitWidth = false,
    castbarPlayerOffsetX = 0,
    castbarPlayerOffsetY = -43,
    castbarPlayerPreviewEnabled = false,
    castbarPlayerShowIcon = true,
    castbarPlayerShowSpellName = true,
    castbarPlayerTextOffsetX = 0,
    castbarPlayerTextOffsetY = 0,
    castbarPlayerTimeOffsetX = -2,
    castbarPlayerTimeOffsetY = 0,
    castbarShakeStrength = 4,
    castbarShowChannelTicks = false,
    castbarShowGlow = false,
    castbarShowIcon = true,
    castbarShowSpellName = true,
    castbarSpellNameFontSize = 0,
    castbarTargetBarHeight = 18,
    castbarTargetBarWidth = 258,
    castbarTargetIconOffsetX = 0,
    castbarTargetIconOffsetY = 0,
    castbarTargetMatchUnitWidth = false,
    castbarTargetOffsetX = 0,
    castbarTargetOffsetY = -43,
    castbarTargetShowIcon = true,
    castbarTargetShowSpellName = true,
    castbarTargetTextOffsetX = 0,
    castbarTargetTextOffsetY = 0,
    castbarTargetTimeOffsetX = -2,
    castbarTargetTimeOffsetY = 0,
    castbarTexture = "Solid",
    castbarUnifiedDirection = false,
    castbarUpdateInterval = 0.019999999552965,
    classBarBgB = 1,
    classBarBgG = 1,
    classBarBgR = 1,
    combatStateIndicatorPos = "TOPLEFT",
    darkBarGray = 0.07,
    darkBarTone = "black",
    darkBgBrightness = 0.25,
    darkMode = true,
    disableUnitInfoTooltips = true,
    editModeBgAlpha = 0.5,
    editModeGridStep = 16,
    editModeHideWhiteArrows = true,
    editModeSnapEnabled = false,
    editModeSnapMode = "grid",
    editModeSnapModeFrames = false,
    editModeSnapModeGrid = true,
    editModeSnapToGrid = false,
    empowerColorStages = true,
    empowerStageBlink = true,
    empowerStageBlinkTime = 0.25,
    enableAbsorbBar = true,
    enableBossCastbar = true,
    enableFocusCastbar = true,
    enableFocusKickIcon = false,
    enableGradient = false,
    enablePlayerCastbar = true,
    enableTargetCastbar = true,
    flashFullH = 732.00024414062,
    flashFullPoint = "TOPLEFT",
    flashFullRelPoint = "TOPLEFT",
    flashFullW = 877.08367919922,
    flashFullX = 186.00001525879,
    flashFullXpx = 99.200013311704,
    flashFullY = -145.41703796387,
    flashFullYpx = -77.555757625577,
    focusKickIconHeight = 41,
    focusKickIconOffsetX = 147,
    focusKickIconOffsetY = -5,
    focusKickIconWidth = 43,
    focusKickTextSize = 16,
    fontColor = "white",
    fontKey = "EXPRESSWAY_BOLD",
    fontSize = 14,
    frameUpdateInterval = 0.049999997019768,
    globalUiScalePreset = "1440p",
    globalUiScaleValue = 0.53333333333333,
    gradientDirDown = false,
    gradientDirLeft = false,
    gradientDirRight = true,
    gradientDirUp = false,
    gradientDirection = "RIGHT",
    gradientStrength = 0.45,
    highlightColor = "white",
    highlightEnabled = true,
    hpFontSize = 14,
    hpSpacerSelectedUnitKey = "player",
    hpTextMode = "FULL_PLUS_PERCENT",
    hpTextSeparator = "-",
    hpTextSpacerEnabled = false,
    hpTextSpacerX = 140,
    incomingResIndicatorPos = "TOPRIGHT",
    leaderIconOffsetX = 0,
    leaderIconOffsetY = 3,
    levelIndicatorAnchor = "NAMERIGHT",
    levelIndicatorOffsetX = 0,
    levelIndicatorOffsetY = 0,
    linkEditModes = true,
    minimapIconDB = {
      hide = false,
      minimapPos = 220,
      radius = 80,
    },
    nameClassColor = true,
    nameFontSize = 14,
    noOutline = false,
    npcNameRed = false,
    playerCastbarOverrideB = 1,
    playerCastbarOverrideEnabled = true,
    playerCastbarOverrideG = 1,
    playerCastbarOverrideMode = "CLASS",
    playerCastbarOverrideR = 1,
    powerFontSize = 14,
    powerTextMode = "FULL_PLUS_PERCENT",
    powerTextSeparator = "-",
    raidMarkerSize = 14,
    roundedUnitframes = true,
    shortenNameClipSide = "LEFT",
    shortenNameFrontMaskPx = 14,
    shortenNameMaxChars = 6,
    showBossCastIcon = true,
    showBossCastName = true,
    showBossCastTime = true,
    showCombatStateIndicator = true,
    showFocusCastTime = true,
    showIncomingResIndicator = true,
    showLeaderIcon = true,
    showLevel = true,
    showMinimapIcon = true,
    showPlayerCastTime = true,
    showRaidMarker = true,
    showTargetCastTime = true,
    showTotalAbsorbAmount = false,
    statusIndicators = {
      showAFK = true,
      showDND = true,
      showDead = true,
      showGhost = true,
    },
    textBackdrop = false,
    tipCycleIndex = 4,
    unitInfoTooltipStyle = "classic",
    useBarBorder = true,
    useClassColors = false,
    useCustomFontColor = false,
  },
  npcColors = {
  },
  pet = {
    enabled = false,
    height = 30,
    hpOffsetX = -4,
    hpOffsetY = -4,
    hpTextSpacerEnabled = false,
    hpTextSpacerX = 140,
    nameOffsetX = 4,
    nameOffsetY = -4,
    offsetX = -260,
    offsetY = 135,
    portraitMode = "OFF",
    powerOffsetX = -4,
    powerOffsetY = 4,
    raidMarkerAnchor = "TOPLEFT",
    raidMarkerOffsetX = 21,
    raidMarkerOffsetY = 3,
    raidMarkerSize = 14,
    showHP = true,
    showInterrupt = true,
    showLevelIndicator = false,
    showName = true,
    showPower = true,
    showRaidMarker = true,
    width = 220,
  },
  player = {
    castbar = {
      channelTickCount = 5,
      channelTickPosPct = {
      },
      channelTickPreviewDuration = 2.5,
      channelTickPreviewLoop = true,
      channelTickUseCustom = false,
    },
    enabled = true,
    height = 27,
    hpOffsetX = -19,
    hpOffsetY = -5,
    hpTextSpacerEnabled = true,
    hpTextSpacerX = 165,
    nameOffsetX = 23,
    nameOffsetY = -4,
    offsetX = 14,
    offsetY = 0,
    portraitMode = "OFF",
    powerOffsetX = -4,
    powerOffsetY = 4,
    raidMarkerAnchor = "TOPLEFT",
    raidMarkerOffsetX = -19,
    raidMarkerOffsetY = -1,
    raidMarkerSize = 20,
    showHP = true,
    showInterrupt = true,
    showLevelIndicator = false,
    showName = false,
    showPower = false,
    showRaidMarker = true,
    width = 260,
  },
  shortenNames = false,
  target = {
    enabled = true,
    height = 27,
    hpFontSize = 13,
    hpOffsetX = -13,
    hpOffsetY = -4,
    hpTextSpacerEnabled = false,
    hpTextSpacerX = 140,
    leaderIconAnchor = "TOPRIGHT",
    nameFontSize = 13,
    nameOffsetX = 17,
    nameOffsetY = -5,
    offsetX = -16,
    offsetY = 0,
    portraitMode = "OFF",
    powerOffsetX = -4,
    powerOffsetY = 4,
    raidMarkerAnchor = "TOPRIGHT",
    raidMarkerOffsetX = 20,
    raidMarkerOffsetY = -2,
    raidMarkerSize = 20,
    showHP = true,
    showInterrupt = true,
    showLevelIndicator = false,
    showName = true,
    showPower = false,
    showRaidMarker = true,
    width = 260,
  },
  targettarget = {
    enabled = true,
    height = 27,
    hpOffsetX = -4,
    hpOffsetY = -4,
    hpTextSpacerEnabled = false,
    hpTextSpacerX = 140,
    nameOffsetX = 24,
    nameOffsetY = -4,
    offsetX = 122,
    offsetY = -40,
    portraitMode = "OFF",
    powerOffsetX = -4,
    powerOffsetY = 4,
    raidMarkerAnchor = "TOPLEFT",
    raidMarkerOffsetX = 21,
    raidMarkerOffsetY = 3,
    raidMarkerSize = 14,
    showHP = false,
    showInterrupt = true,
    showLevelIndicator = false,
    showName = true,
    showPower = false,
    showRaidMarker = true,
    showToTInTargetName = false,
    totInlineSeparator = ">>>",
    width = 183,
  },
  },
}

-- Optional global export for debugging/compat
_G.MSUF_PRESETS = ns.MSUF_PRESETS
