local SM = LibStub("LibSharedMedia-3.0")

SM:Register("statusbar", "BantoBar",	"Interface\\AddOns\\InvenUnitFrames\\Texture\\BantoBar")
SM:Register("statusbar", "Flat Smooth",	"Interface\\AddOns\\InvenUnitFrames\\Texture\\FlatSmooth")
SM:Register("statusbar", "Melli Dark",	"Interface\\AddOns\\InvenUnitFrames\\Texture\\MelliDark")
SM:Register("statusbar", "Minimalist",	"Interface\\AddOns\\InvenUnitFrames\\Texture\\Minimalist")
SM:Register("statusbar", "Smooth v2",	"Interface\\AddOns\\InvenUnitFrames\\Texture\\Smoothv2")
SM:Register("statusbar", "Smooth",		"Interface\\AddOns\\InvenUnitFrames\\Texture\\Smooth")
SM:Register("statusbar", "Rocks",		"Interface\\AddOns\\InvenUnitFrames\\Texture\\Rocks")
SM:Register("statusbar", "Runes",		"Interface\\AddOns\\InvenUnitFrames\\Texture\\Runes")