--[[
	Language Localization: deDE
	Translated by: Chiaki EU-Frostwolf <chiakiaccess@hotmail.com>
]]

WIM.AddLocale("deDE", {
    ["WIM (WoW Instant Messenger)"] = true,
    ["_Description"] = "WIM ist ein AddOn, welches einem das vertraute Gefühl über ein Chatsystem zu kommunizieren zurückbringt. In diesem Fenster kannst du WIM individualisieren, um es deinen Bedürfnissen anzupassen.",

    ["_DemoText"] = "Dies ist ein Demonstrationsfenster und ist nicht voll funktionsfähig. Platziere dieses Fenster an die Stelle, an der du alle anderen Fenster erzeugen möchtest. Sobald du fertig bist kannst du das Fenster schließen, um die Einstellungen zu speichern.",

    ["_DateFormat"] = "%d/%m/%Y",

    ["Yes"] = "Ja",
    ["No"] = "Nein",
    ["None"] = "Kein(e)",
    ["<Right-Click>"] = "<Rechts-Klick>",
    ["<Left-Click>"] = "<Links-Klick>",
    ["OK"] = true,
    ["Cancel"] = "Abbrechen",
    ["Unknown"] = "Unbekannt",
    ["Click to update..."] = "Klicke um ein Update zu starten...",
    ["Usage"] = "Gebrauch",

    ["state_resting"] = "Ruhend",
    ["state_combat"] = "Kampf",
    ["state_pvp"] = "PVP",
    ["state_arena"] = "Arena",
    ["state_party"] = "Gruppeninstanz",
    ["state_raid"] = "Schlachtzuginstanz",
    ["state_other"] = "Normal (Sonstiges)",

    ["A new version of WIM is available!\nYou can download the latest version from curse"] = "Eine neue Version von WIM ist verfügbar!\nDu kannst die neueste Version von Curse herunterladen.",

    ["Options"] = "Einstellungen",

    ["Icon Position"] = "Symbolposition",
    ["Font Size"] = "Schriftgröße",
    ["Window Scale (Percent)"] = "Fensterskalierung (Prozent)",
    ["Transparency (Percent)"] = "Transparenz (Prozent)",
    ["Window Width"] = "Fensterbreite",
    ["Window Height"] = "Fensterhöhe",
    ["(Limited by shortcut bar)"] = "(Begrenzt durch die Funktionsleiste rechts)",
    ["ERROR"] = "FEHLER",
    ["Invalid Name!"] = "Ungültiger Name!",
    ["Name is already used!"] = "Name wird bereits verwendet!",
    ["Invalid Alias!"] = "Ungültiges Alias!",
    ["Invalid Keyword/Phrase!"] = "Ungültige Schlüsselwort-/Phrasen!",
    ["Keyword/Phrase is already used!"] = "Schlüsselwort/Phrase wird bereits verwendet!",

    ["Day"] = "Tag",
    ["Week"] = "Woche",
    ["Month"] = "Monat",
    ["Drag to set default spawn/position for message windows."] = "Ziehe um die Ausgangsposition für die Erzeugung von Nachrichtenfenstern festzulegen.",
    ["Up"] = "Oben",
    ["Down"] = "Unten",
    ["Left"] = "Links",
    ["Right"] = "Rechts",
    ["Ignore"] = "Ignorieren",
    ["Block"] = "Blockieren",
    ["Enable WIM"] = "WIM aktivieren",

    ["Auto Close Friends after:"] = "Schließe Freundesnachrichten automatisch nachdem:",
    ["Auto Close Non-Friends after:"] = "Schließe Nicht-Freundesnachrichten automatisch nachdem:",

    ["Display"] = "Anzeige",
    ["Incoming Messages"] = "Eingehende Nachrichten",
    ["Outgoing Messages"] = "Ausgehende Nachrichten",
    ["System Messages"] = "Systemnachrichten",
    ["Error Messages"] = "Fehlernachrichten",
    ["Web URLs"] = "Internet-Adressen",
    ["Enable"] = "Aktivieren",
    ["Disable"] = "Deaktivieren",
    ["Enabled"] = "Aktiviert",
    ["Disabled"] = "Deaktiviert",
    ["Display character information."] = "Zeige Charakterinformationen an.",
    ["Display time stamps"] = "Zeige Zeitstempel an",
    ["This setting limits the\nwindow's minimum height."] = "Diese Einstellung begrenzt die\n Minimalhöhe des Fensters.",
    ["Requires /who querying."] = "Benötigt /who Abfragen.",
    ["Enable window fading effects."] = "Fenster-Verblassungseffekte aktivieren.",
    ["Enable window animations."] = "Fenster-Animationen aktivieren.",

    ["Display minimap icon."] = "Minimap-Symbol anzeigen.",

    ["General"] = "Allgemein",
    ["History"] = "Verlauf",
    ["Filters"] = "Filter",
    ["Plugins"] = true,

    ["Auto focus when window is shown."] = "Automatischer Textcursor-Fokus wenn sich ein Fenster öffnet.",
    ["Preserve focus after sending messages."] = "Textcursor-Fokus nach der Nachrichtenversendung beibehalten.",
    ["Display tooltips."] = "Tooltips anzeigen.",
    ["Show window when sending a message."] = "Fenster anzeigen, wenn eine Nachricht gesendet wird.",
    ["Show window when message has been received."] = "Fenster anzeigen, wenn eine Nachricht erhalten wurde.",
    ["Suppress messages from default chat frame."] = "Nachrichten vom Standard-Chatfenster unterdrücken.",
    ["Play sound when message is received."] = "Geräusch abspielen, wenn eine Nachricht erhalten wurde.",
    ["Play sound when message is sent."] = "Geräusch abspielen, wenn eine Nachricht versendet wurde.",
    ["Sort alphabetically."] = "Alphabetisch sortieren.",
    ["Use <Escape> to close windows."] = "<Escape> benutzen können, um Fenster zu schließen.",
    ["Windows will close when opening the world map."] = "Fenster sollen sich schließen, sobald Weltkarte geöffnet wird.",
    ["Intercept slash commands."] = "Slash-Befehle abfangen.",
    ["Include sent messages in /REPLY."] = "Gesendete Nachrichten in /REPLY einschließen.",
    ["Ignore arrow keys while typing."] = "Pfeiltasten ignorieren, während getippt wird.",
    ["Requires using <Alt> to navigate text."] = "Benötigt gedrückte <Alt>-Taste um durch den Text zu navigieren.",
    ["Display emoticons."] = "Zeige Emoticons/Smileys an.",
    ["Display URLs as item links."] = "Zeige Internet-Adressen als Itemlinks an.",
    ["Display floating item links."] = "Zeige schwebende Itemlinks.",

    ["Cascade windows."] = "Fenster hintereinanderschalten.",
    ["Direction:"] = "Richtung:",
    ["Tabs"] = true,
    ["Sort tabs by:"] = "Sortiere Tabs:",
    ["Window Created"] = "Fenster erstellt",
    ["Last Activity"] = "Letzte Aktivität",
    ["Alphabetical"] = "Alphabetisch",
    ["Recent Activity"] = "Letzte Aktion",
    ["Keep windows on top of your UI."] = "Fenster im Vordergrund des Interface halten.",

    ["Enable/Disable addon messages."] = "Addon-Nachrichten aktivieren/deaktivieren.",

    -- Class Names --
    ["Druid"] = LOCALIZED_CLASS_NAMES_MALE.DRUID,
    ["Hunter"] = LOCALIZED_CLASS_NAMES_MALE.HUNTER,
    ["Mage"] = LOCALIZED_CLASS_NAMES_MALE.MAGE,
    ["Paladin"] = LOCALIZED_CLASS_NAMES_MALE.PALADIN,
    ["Priest"] = LOCALIZED_CLASS_NAMES_MALE.PRIEST,
    ["Rogue"] = LOCALIZED_CLASS_NAMES_MALE.ROGUE,
    ["Shaman"] = LOCALIZED_CLASS_NAMES_MALE.SHAMAN,
    ["Warlock"] = LOCALIZED_CLASS_NAMES_MALE.WARLOCK,
    ["Warrior"] = LOCALIZED_CLASS_NAMES_MALE.WARRIOR,
    ["Death Knight"] = LOCALIZED_CLASS_NAMES_MALE.DEATHKNIGHT,
    ["Monk"] = LOCALIZED_CLASS_NAMES_MALE.MONK,
    ["Demon Hunter"] = LOCALIZED_CLASS_NAMES_MALE.DEMONHUNTER,
	["Evoker"] = LOCALIZED_CLASS_NAMES_MALE.EVOKER,

    -- Female Class Names --
    ["DruidF"] = LOCALIZED_CLASS_NAMES_FEMALE.DRUID,
    ["HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.HUNTER,
    ["MageF"] = LOCALIZED_CLASS_NAMES_FEMALE.MAGE,
    ["PaladinF"] = LOCALIZED_CLASS_NAMES_FEMALE.PALADIN,
    ["PriestF"] = LOCALIZED_CLASS_NAMES_FEMALE.PRIEST,
    ["RogueF"] = LOCALIZED_CLASS_NAMES_FEMALE.ROGUE,
    ["ShamanF"] = LOCALIZED_CLASS_NAMES_FEMALE.SHAMAN,
    ["WarlockF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARLOCK,
    ["WarriorF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARRIOR,
    ["Death KnightF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEATHKNIGHT,
    ["MonkF"] = LOCALIZED_CLASS_NAMES_FEMALE.MONK,
    ["Demon HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEMONHUNTER,
	["EvokerF"] = LOCALIZED_CLASS_NAMES_FEMALE.EVOKER,

    ["Game Master"] = "Spielmeister",

    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "Schalte WIM 'Ein' oder 'Aus'.",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "Schalte Debugging Modus 'Ein' oder 'Aus'",
    ["WIM is currently running. To access WIM's wide array of options type:"] = "WIM ist zur Zeit aktiv. Um die breite Auswahl an Einstellungen vornehmen zu können, gebe ein:",

    -- Filters.lua --
    ["Whispers Sent by Addons"] = "Flüsternachrichten gesendet durch AddOns",
    ["WhisperSelect Part 1"] = "FlüsterAuswahl Teil 1",
    ["Example Spam Blocker"] = "Beispiel Spamblocker",
    ["WhisperSelect Part 2"] = "FlüsterAuswahl Teil 2",
    ["Filter Name"] = "Filtername",
    ["Filter By"] = "Filtern nach",
    ["Pattern"] = "Muster",
    ["User Type"] = "Spielertyp",
    ["Level"] = "Level",
    ["Friends"] = "Freunde",
    ["Guild Members"] = "Gildenmitglieder",
    ["Party Members"] = "Gruppenmitglieder",
    ["Raid Members"] = "Schlachtzugsmitglieder",
    ["Cross-Realm"] = "Realm-Übergreifend",
    ["Everyone"] = "Alle",
    ["User must be at least level:"] = "Spieler muss mindestens diesen Level haben:",
    ["Apply to messages received."] = "Für eingehende Nachrichten übernehmen.",
    ["Apply to messages sent."] = "Für ausgehende Nachrichten übernehmen.",
    ["Action to Perform:"] = "Durchzuführende Aktion:",
    ["Allow"] = "Erlauben",
    ["Ignore"] = "Ignorieren",
    ["Blocked"] = "Blockieren",
    ["Save"] = "Speichern",
    ["Cancel"] = "Abbrechen",
    ["Edit Filter"] = "Filter bearbeiten",
    ["Add Filter"] = "Filter hinzufügen",

    -- History.lua --
    ["WIM History Button"] = "WIM Verlaufsbutton",
    ["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = "Das Klicken auf den %s Button auf dem Nachrichtenfenster zeigt den Nachrichtenverlauf mit dem Spieler in der WIM Verlaufsanzeige.",
    ["Click to view message history."] = "Klicken um den Nachrichtenverlauf anzuzeigen.",
    ["WIM pruned %d |4message:messages; from your history."] = "WIM hat %d |4message:messages; von deinem Nachrichtenverlauf gelöscht.",
    ["History Viewer"] = "Verlaufsanzeige",
    ["Filters"] = "Filter",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "Bist du sicher, dass du sämtliche Nachrichtenverläufe gespeichert für %s auf %s löschen möchtest?",
    ["Search resulted in %d |4message:messages;."] = "Ergebnis der Suche resultiert in %d |4message:messages;.",
    ["No results found!"] = "Keine Ergebnisse gefunden!",
    ["Search"] = "Suche",
    ["Show All"] = "Alle anzeigen",
    ["Loading History"] = "Verlauf wird geladen",
    ["Chat View"] = "Chatansicht",
    ["Text View"] = "Textansicht",
    ["WIM History Viewer can be accessed any time by typing:"] = "WIM Verlaufsanzeige kann jederzeit aufgerufen werden durch drücken von:",
    ["WIM History Viewer"] = "WIM Verlaufsanzeige",
    ["Display history viewer."] = "Verlaufsanzeige anzeigen",

    -- ldb.lua --
    ["No New Messages"] = "Keine neuen Nachrichten",

    -- Menu.lua --
    ["Whispers"] = "Flüsternachrichten",
    ["Chat"] = true,

    -- Negotiate.lua --
    ["WIM Update Available!"] = "WIM Update verfügbar!",
    ["There is a newer version of WIM available for download. You can download it at %s."] = "Es ist eine neuere Version von WIM zum Download verfügbar. Du kannst sie herunterladen auf %s.",

    -- ShortcutBar.lua --
    ["Player Location"] = "Spieler Standort",
    ["Unknown"] = "Unbekannt",
    ["Click to update..."] = "Klicke um ein Update zu starten...",
    ["Coordinates"] = "Koordinaten",
    ["Invite to Party"] = "In die Gruppe einladen",
    ["Add Friend"] = "Freund hinzufügen",
    ["Ignore User"] = "Spieler ignorieren",
    ["Are you sure you want to\nignore %s?"] = "Bist du sicher, dass du \n %s ignorieren willst?",
	["Copy Name"] = "Namen kopieren",

    -- Tutorials.lua --
    ["Display WIM tips"] = "WIM Tipps anzeigen",

    -- W2W.lua --
    ["%s is typing..."] = "%s tippt...",
    ["W2W Profile"] = "W2W Profil",

    -- WhisperEngine.lua --
    ["Whisper Received!"] = "Flüsternachricht erhalten!",
    ["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = "Du hast eine Flüsternachricht erhalten, welche aufgrund deines Charakterzustandes zu dem Zeitpunkt nicht angezeigt wurde. Du kannst das Verhalten der Anzeige von Flüsternachrichten in bestimmten Situationen in den WIM Optionen ändern durch Drücken von",

    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "Du bist dabei den gesamten WIM Nachrichtenverlauf zu löschen!",
    ["This action will reload your user interface."] = "Dieser Vorgang wird dein Interface neu laden.",
    ["Do you want to continue?"] = "Willst du fortfahren?",
    ["You are about to restore WIM's filters to it's default settings!"] = "Du bist dabei die WIM Filtereinstellungen auf die Standardeinstellungen zurückzusetzen!",
    ["Usage"] = "Gebrauch",
    ["Clear various WIM data."] = "Lösche diverse WIM Daten.",

    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "WIM Slash-Befehle",
    ["To see a list of available WIM slash commands type:"] = "Um eine Liste von verfügbaren WIM-Befehlen zu erhalten gebe ein:",
    ["Display available slash commands."] = "Zeige verfügbare Slash-Befehle an.",
    ["Reload User Interface."] = "Lade Spieler-Interface neu.",

    -- TabHandler.lua --
    ["Manipulating Tabs"] = "Manipulation von Tabs",
    ["You can <Shift-Click> a tab and drag it out into it's own window."] = "<Shift-Klick> auf einen Tab erlaubt dir ihn aus dem eigenen Fenster zu ziehen.",

    -- WindowHandler.lua --
    ["Window Resized!"] = "Fenstergröße angepasst!",
    ["If you want all windows to be this size, you can set the default window size within WIM's options."] = "Wenn du möchtest, dass alle Fenster diese Größe haben, dann kannst du die Standardgröße von Fenstern in den WIM Optionen einstellen.",
    ["Creating Tab Groups"] = "Erstellung von Tab-Gruppen",
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "Du kannst zwei oder mehrere Fenster zusammengruppieren indem du ein Fenster <Shift-Klickst> und es auf ein anderes ziehst.",
    ["Resizing Windows"] = "Größenanpassung von Fenstern",
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "Du kannst die Größe eines Fensters anpassen, indem du <Shift> gedrückt hältst und die obere rechte Ecke des Fensters ziehst.",
    ["Demo Window"] = "Demonstrationsfenster",
    ["<Shift-Click> to close window."] = "<Shift-Klick> zum Schließen des Fensters.",
    ["Message Window Hidden"] = "Nachrichtenfenster versteckt",
    ["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = "WIMs Nachrichtenfenster wurde im WIM Minimap-Symbol versteckt. Wenn du eine Konversation beenden möchtest, kannst du das durch einen <Shift-Klick> auf den Schließen-Button tun.",
    ["Default"] = "Standard",
    ["%s is Away From Keyboard: %s"] = "%s ist AFK (Away From Keyboard/Abwesend): %s",
    ["%s does not wish to be disturbed: %s"] = "%s möchte nicht gestört werden: %s",
    ["Right-Mouse Click!"] = "Rechtsklick!",
    ["There might be useful tools hidden under the message box. Right-Click to see them!"] = "Unter dem Nachrichtenfeld könnten nützliche Werkzeuge verborgen sein. Rechtsklick zum Anzeigen!",

    -- Options.lua --
    ["Display WIM's options."] = "WIM Optionen anzeigen.",
    ["Resetting WIM will clear all of your settings!"] = "Das Zurücksetzen von WIM wird sämtliche deiner Einstellungen löschen!",
    ["Reset all options to default."] = "Alle Einstellungen zurücksetzen.",

    -- CoreOptions --
    ["Created By:"] = "Kreiert von:",
    ["Special Thanks:"] = "Besonderer Dank:",
    ["Welcome!"] = "Willkommen!",
    ["Enable WIM"] = "WIM aktivieren",
    ["Display Minimap Icon"] = "Minimap-Symbol anzeigen",
    ["<Right-Click> to show unread messages."] = "<Rechts-Klick> um ungelesene Nachrichten anzuzeigen.",
	["Display Addon Compartment Icon"] = "Icon des Addon-Fachs anzeigen",
    ["Display Tutorials"] = "Tutorials anzeigen",
    ["Reset Tutorials"] = "Tutorials zurücksetzen",
    ["Credits"] = "Danksagungen",
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "Dies ist eine lange Nachricht, die sowohl Emoticons/Smileys, als auch Internetadressen enthält 8). WIMs Homepage ist www.WIMAddon.com.",
    ["Message Formatting"] = "Nachrichtenformatierung",
    ["Manipulate how WIM displays messages."] = "Stelle ein, wie WIM Nachrichten darstellen soll.",
    ["Preview"] = "Vorschau",
    ["Display Time Stamps"] = "Zeitstempel anzeigen",
    ["Display Emoticons"] = "Emoticons/Smileys anzeigen",
    ["Display URLs as Links"] = "Internetadressen als Links anzeigen",
    ["Indent long messages."] = "Lange Nachrichten einrücken.",
    ["Window Behavior"] = "Fensterverhalten",
    ["Bracket names."] = "Namen einklammern.",
    ["You can control how windows behave while you are in different situations."] = "Du kannst das Verhalten von Fenstern in verschiedenen Situationen einstellen.",
    ["Intercept Slash Commands"] = "Slash-Befehle abfangen",
	["Obey autofocus rules when opening frames via the menu. (autofocus if unchecked)"] = "Respektiere beim Öffnen via des Menüs die autofocus-Einstellung.",
    ["Use the same rules for all states."] = "Dieselben Regeln für alle Situationen anwenden.",
    ["Behaviors for state:"] = "Verhalten für Situation:",
    ["Pop-Up window when message is sent."] = "Fenster als Pop-Up sobald Nachricht versendet wurde.",
    ["Pop-Up window when message is received."] = "Fenster als Pop-Up sobald Nachricht erhalten wurde.",
    ["Auto focus a window when it is shown."] = "Automatischer Textcursor-Fokus wenn sich ein Fenster öffnet.",
    ["Keep focus on window after sending a message."] = "Textcursor-Fokus nach der Nachrichtenversendung beibehalten.",
    ["Suppress messages from the default chat frame."] = "Nachrichten vom Standard-Chatfenster unterdrücken.",
    ["Window Settings"] = "Fenstereinstellungen",
    ["Some settings may be limited by certain skins."] = "Manche Einstellungen können auf bestimmte Skins begrenzt sein.",
    ["Default Width"] = "Standardbreite",
    ["Default Height"] = "Standardhöhe",
    ["Window Scale"] = "Fensterskalierung",
    ["Window Alpha"] = "Fenstertransparenz",
    ["Set Window Spawn Location"] = "Stelle Erzeugungspunkt für Fenster ein",
    ["Up"] = "Oben",
    ["Down"] = "Unten",
    ["Left"] = "Links",
    ["Right"] = "Rechts",
    ["Cascade overlapping windows."] = "Überlappende Fenster hintereinanderschalten.",
    ["Ignore arrow keys in message box."] = "Pfeiltasten im Nachrichtenfenster ignorieren.",
    ["Allow <ESC> to hide windows."] = "<ESC> zum verstecken von Fenstern erlauben.",
    ["Display Settings"] = "Anzeige-Einstellungen",
    ["Configure general window display settings."] = "Allgemeine Einstellungen zur Fensteranzeige konfigurieren.",
    ["Window Skin:"] = "Fenster-Skin:",
    ["Version"] = true,
    ["Color: System Messages"] = "Farbe: Systemnachrichten",
    ["Color: Error Messages"] = "Farbe: Fehlernachrichten",
    ["Color: URL - Web Addresses"] = "Farbe: Internetadressen",
    ["Color: History Messages Sent"] = "Farbe: Versendete Nachrichten im Nachrichtenverlauf",
    ["Color: History Messages Received"] = "Farbe: Empfangene Nachrichten im Nachrichtenverlauf",
    ["Use colors suggested by skin."] = "Verwende für den Skin empfohlene Farben.",
    ["Enable window fading effects."] = "Fenster-Verblassungseffekte aktivieren.",
    ["Enable window animation effects."] = "Fenster-Animationseffekte aktivieren.",
    ["Display item links when hovering over them."] = "Itemlinks bei Mouseover anzeigen.",
    ["Fonts"] = "Schriftarten",
    ["Configure the fonts used in WIM's message windows."] = "Schriftarten in den WIM Nachrichtenfenstern konfigurieren.",
    ["Font Outline"] = "Schriftart-Außenlinie",
    ["Thin"] = "Dünn",
    ["Thick"] = "Dick",
    ["Use font suggested by skin."] = "Verwende für den Skin empfohlene Schriftart.",
    ["Chat Font Size"] = "Chat Schriftgröße",
    ["Configure general display settings when dealing with whispers."] = "Konfiguriere allgemeine Darstellungsoptionen bei Flüsternachrichten.",
    ["Color: Messages Sent"] = "Farbe: Gesendete Nachrichten",
    ["Color: Messages Received"] = "Farbe: Empfangene Nachrichten",
    ["Use colors suggested by skin."] = "Verwende für den Skin empfohlene Farben.",
    ["Display user class icons and details."] = "Zeige Spieler Klassensymbole und Details an.",
    ["Requires who lookups."] = "Benötigt /wer Abfragen.",
    ["Display Shortcut Bar"] = "Zeige Funktionsleiste (rechts) an.",
    ["Allow"] = "Erlauben",
    ["Ignore"] = "Ignorieren",
    ["Block"] = "Blockieren",
    ["Filtering"] = "Filterung",
    ["Filtering allows you to control which messages are handled as well as how they are handled by WIM."] = "Filtern erlaubt dir die Kontrolle darüber zu haben welche Nachrichten wie von WIM gehandhabt werden.",
    ["Enable Filtering"] = "Filterung aktivieren.",
    ["Protected"] = "Gesichert",
    ["Action:"] = "Aktion:",
    ["Occurrences:"] = "Vorfälle:",
    ["Delete Filter"] = "Filter löschen",
    ["History"] = "Nachrichtenverlauf",
    ["WIM can store conversations to be viewed at a later time."] = "WIM kann Konversationen speichern, um sie zu einem späteren Zeitpunkt wieder anzuzeigen.",
    ["Enable History"] = "Nachrichtenverlauf aktivieren.",
    ["Messages"] = "Nachrichten",
    ["Preview history inside message windows."] = "Vorschau des Nachrichtenverlaufs innerhalb \n der Nachrichtenfenster anzeigen.",
    ["Record Whispers"] = "Flüsternachrichten \n aufzeichnen von",
    ["Record Friends"] = "Freunde aufzeichnen",
    ["Record Guild"] = "Gildenmitglieder aufzeichnen",
    ["Record Everyone"] = "Alle aufzeichen",
    ["Record Chat"] = "Chat aufzeichnen",
    ["Maintenance"] = "Wartung",
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "Wenn du deinen Nachrichtenverläufen ermöglichst \n zu lang/groß zu werden, könnte dies die Performance des Spiels beeinträchtigen, deswegen ist es empfehlenswert, dass du folgende Einstellungen nutzt.",
    ["Save a maximum number of messages per person."] = "Speichere eine Maximalzahl an Nachrichten pro Spieler.",
    ["%d |4Week:Weeks;"] = "%d |4Woche:Wochen;",
    ["Automatically delete old messages."] = "Automatisch alte Nachrichten löschen.",
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM ist eine Funktion, die WIM erlaubt mit Spielern, die ebenfalls WIM nutzen, auf bestimmte Arten zu interagieren, die über normales Flüstern nicht möglich sind.",
    ["Enable WIM-2-WIM"] = "WIM-2-WIM aktivieren",
    ["Privacy"] = "Privatsphäre",
    ["Restrict the data that is shared."] = "Austauschbare Daten eingrenzen.",
    ["Allow others to see me typing."] = "Erlaube Anderen zu sehen, wann ich tippe.",
    ["Allow others to see my location."] = "Erlaube Anderen meinen Standort zu sehen.",
    ["Main"] = "Haupteinstellungen",
    ["General"] = "Allgemein",
    ["User Level"] = "Spielerlevel",
    ["Windows will also be hidden when frames such as the world map are shown."] = "Fenster werden ebenfalls versteckt, sobald andere Fenster, wie etwa die Weltkarte, angezeigt werden.",
	["Background"] = BACKGROUND,
	["Low"] = LOW,
	["Medium"] = "Mittel",
	["High"] = "Hoch",
	["Dialog"] = ENABLE_DIALOG,
	["Tooltip"] = true,
    ["Unlock from Minimap"] = "Von der Minikarte lösen",
    ["Press <Tab> to advance to next tell target."] = "<Tab> drücken, um zum nächsten Whisper-Ziel zu wechseln.",
    ["Force sounds when game sound is disabled."] = "Sound erzwingen, auch wenn der Spielsound deaktiviert ist.",
    ["Colorize names."] = "Namen einfärben.",
    ["Clamp window to screen."] = "Fenster am Bildschirmrand begrenzen.",
    ["Group with whisper windows."] = "Mit Whisper-Fenstern gruppieren.",
    ["Color: BNet Messages Sent"] = "Farbe: Gesendete BNet-Nachrichten",
    ["Color: BNet Messages Received"] = "Farbe: Empfangene BNet-Nachrichten",

    -- TabManagement.lua --
    ["Tab Management"] = true,
    ["Automatically manage your open windows and place them into appropriate tab groups."] = "Manage automatisch deine offenen Fenster und platziere sie in angemessene Tabgruppen.",
    ["Automatically group whispers."] = "Automatische Gruppen-Flüsternachrichten.",
    ["Place friends in their own group."] = "Platziere Freunde in ihre eigene Gruppe.",
    ["Place guild members in their own group."] = "Platziere Gildenmitglieder in ihre eigene Gruppe.",
    ["Does not apply to windows already opened."] = "Wird nicht für Fenster übernommen, die bereits geöffnet sind.",

    -- Talent Specs --
    ["Affliction"] = "Gebrechen",
    ["Arcane"] = "Arkan",
    ["Arms"] = "Waffen",
    ["Assassination"] = "Meucheln",
    ["Balance"] = "Gleichgewicht",
    ["Beast Mastery"] = "Tierherrschaft",
    ["Blood"] = "Blut",
    ["Combat"] = "Kampf",
    ["Demonology"] = "Dämonologie",
    ["Destruction"] = "Zerstörung",
    ["Discipline"] = "Disziplin",
    ["Elemental"] = "Elementar",
    ["Enhancement"] = "Verstärkung",
    ["Feral Combat"] = "Wilder Kampf",
    ["Fire"] = "Feuer",
    ["Frost"] = "Frost",
    ["Fury"] = "Furor",
    ["Holy"] = "Heilig",
    ["Hybrid"] = "Hybride",
    ["Marksmanship"] = "Treffsicherheit",
    ["Protection"] = "Schutz",
    ["Restoration"] = "Wiederherstellung",
    ["Retribution"] = "Vergeltung",
    ["Shadow"] = "Schatten",
    ["Subtlety"] = "Täuschung",
    ["Survival"] = "Überleben",
    ["Unholy"] = "Unheilig",
    ["Windwalker"] = "Windläufer",
    ["Havok"] = "Verwüstung",
    ["Vengeance"] = "Rachsucht",

    -- ChangeLog.lua --
    ["Change Log"] = "Änderungsprotokoll",
    ["View WIM's change log."] = "WIM-Änderungsprotokoll anzeigen.",
    ["Available For Download!"] = "Zum Download verfügbar!",

    -- Filters.lua --
    ["Show Alert"] = "Warnung anzeigen",
    ["WIM has blocked a message from %s."] = "WIM hat eine Nachricht von %s blockiert.",
    ["View Blocked Message"] = "Blockierte Nachricht anzeigen",
    ["Blocked Message"] = "Blockierte Nachricht",

    -- MinimapIcon.lua
    ["Show Unread Messages"] = "Zeige ungelesene Nachrichten",
    ["Show All Windows"] = "Zeige alle Fenster",
    ["Hide All Windows"] = "Verberge alle Fenster",

    -- Emoticons.lua --
    ["Also"] = "Auch",
    ["More"] = "Mehr",
    ["Emoticons"] = "Emoticons",

    -- Expose.lua --
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = "Deine Gespräche wurden ausgeblendet, um den Bildschirm im Kampf zu bereinigen. Zum Deaktivieren gib ein:",
    ["Expose"] = "Expose",
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = "Expose ist eine von macOS inspirierte Funktion, mit der du schnell alle Fenster vom Bildschirm entfernen und anschließend wieder in ihre ursprüngliche Position zurückbringen kannst.",
    ["Auto hide/restore windows during combat."] = "Fenster im Kampf automatisch aus-/einblenden.",
    ["Delay if I am typing a message."] = "Verzögern, wenn ich gerade eine Nachricht tippe.",
    ["Border Size"] = "Rahmengröße",
    ["Only while in an instance."] = "Nur in Instanzen.",
    ["Show Border"] = "Rahmen anzeigen",
    ["Animation Direction:"] = "Animationsrichtung:",

    -- ChatEngine.lua --
    ["WIM will manage this chat type within its own message windows."] = "WIM verwaltet diesen Chattyp in eigenen Nachrichtenfenstern.",
    ["Show Minimap Alerts"] = "Minikartenwarnungen anzeigen",
    ["Never pop-up on my screen."] = "Nie als Popup auf meinem Bildschirm anzeigen.",
    ["Never suppress messages."] = "Keine Nachrichtenunterdrückung.",
    ["Include emotes."] = "Emotes einschließen.",
    ["Have WIM monitor this channel."] = "WIM soll diesen Kanal überwachen.",
    ["Never Pop"] = "Nie Popup",
    ["Never have this window pop-up on my screen."] = "Dieses Fenster niemals als Popup anzeigen.",
    ["Never Suppress"] = "Nie unterdrücken",
    ["Never suppress messages from the default chat frame."] = "Keine Nachrichten im Standard-Chatfenster unterdrücken.",
    ["Show unread message alert on minimap."] = "Warnung für ungelesene Nachrichten auf der Minikarte anzeigen.",
    ["No History"] = "Kein Verlauf",
    ["Do not record history for this channel."] = "Keinen Verlauf für diesen Kanal speichern.",
    ["World Chat"] = "Weltchat",
    ["Custom Chat"] = "Benutzerdefinierter Chat",
    ["Chat"] = "Chat",
    ["Play special sound for %s."] = "Speziellen Sound für %s abspielen.",
    ["Play sound when a message is received."] = "Sound bei eingehender Nachricht abspielen.",
    ["Play sound when a message is sent."] = "Sound bei gesendeter Nachricht abspielen.",
    ["Do not play sounds for this channel."] = "Keine Sounds für diesen Kanal abspielen.",
    ["No Sound"] = "Kein Sound",
    ["Sensitivity"] = "Empfindlichkeit",
    ["Enable WorldFrame Click Detection."] = "WorldFrame-Klickerkennung aktivieren.",
    ["The UI must be reloaded in order to disable this module fully. Reload UI now?"] = "Die Benutzeroberfläche muss neu geladen werden, um dieses Modul vollständig zu deaktivieren. Jetzt neu laden?",

    -- OffScreenTracker.lua --
    ["WIM Window Off Screen"] = "WIM-Fenster außerhalb des Bildschirms",
    ["Click to reposition."] = "Klicken zum Neupositionieren.",

    -- Misc --
    ["WIM has detected that you are playing on a private server. Some servers can not process ChatAddonMessages. Would you like to enable them anyway?"] = "WIM hat erkannt, dass du auf einem privaten Server spielst. Einige Server können ChatAddonMessages nicht verarbeiten. Möchtest du sie trotzdem aktivieren?",

    -- Whisper Mode Warnings --
    ["Whisper Mode: In-line"] = "Flüstermodus: Inline",
    ["Set whispers to In-line"] = "Flüstern auf Inline setzen",
    ["Message suppression requires whispers to be set to 'In-line'."] = "Nachrichtenunterdrückung erfordert, dass Flüstern auf 'Inline' gesetzt ist.",
    ["It is recommended for whispers to be set to in-line in order to handle their behavior properly."] = "Es wird empfohlen, Flüstern auf Inline zu setzen, um das Verhalten korrekt zu verarbeiten.",
});
