--[[
    Language Localization: esES & esMX
    Translated by: Woopy#1685 (NA)
]]

local translations = {
    ["WIM (WoW Instant Messenger)"] = "WIM (WoW Instant Messenger)",
    ["_Description"] = "WIM es un addon que aporta una sensación familiar a la comunicación a través del chat en The World of Warcraft. En esta pantalla podrá personalizar WIM para adaptarlo a tus necesidades.",

    ["_DemoText"] = "Esta es una ventana de demostración y no es completamente funcional. Coloca esta ventana en el lugar donde deseas que aparezcan todas las demás ventanas. Cuando termines, puedes cerrar esta ventana y su configuración se guardará.",

    ["_DateFormat"] = "%d/%m/%Y",

    ["Yes"] = "Sí",
    ["No"] = "No",
    ["None"] = "Ninguno",
    ["Cancel"] = "Cancelar",
    ["Unknown"] = "Desconocido",
    ["Click to update..."] = "Haz clic para actualizar...",
    ["Usage"] = "Uso",

    ["state_resting"] = "Ausente",
    ["state_combat"] = "Combate",
    ["state_pvp"] = "JcJ",
    ["state_arena"] = "Arena",
    ["state_party"] = "Grupo de mazmorra",
    ["state_raid"] = "Grupo de banda",
    ["state_other"] = "Normal (otro)",

    ["Options"] = "Opciones",

    ["Up"] = "Arriba",
    ["Down"] = "Abajo",
    ["Left"] = "Izquierda",
    ["Right"] = "Derecha",
    ["Ignore"] = "Ignorar",
    ["Block"] = "Bloquear",
    ["Enable WIM"] = "Activar WIM",

    ["Enable"] = "Activar",
    ["Disable"] = "Desactivar",
    ["Enable window fading effects."] = "Activar efectos de desvanecimiento de ventana",

    ["General"] = "General",
    ["History"] = "Historial",
    ["Filters"] = "Filtros",

    ["Include sent messages in /REPLY."] = "Incluir mensajes enviados en /r",

    ["Sort tabs by:"] = "Ordenar pestañas por:",
	["Window Created"] = "Ventana creada",
	["Last Activity"] = "Última actividad",
    ["Alphabetical"] = "Alfabético",

    -- Class Names --
    ["Druid"] = LOCALIZED_CLASS_NAMES_MALE.DRUID,
    ["Hunter"] = LOCALIZED_CLASS_NAMES_MALE.HUNTER,
    ["Mage"] = LOCALIZED_CLASS_NAMES_MALE.MAGE,
    ["Paladin"] = LOCALIZED_CLASS_NAMES_MALE.PALADIN,
    ["Priest"] = LOCALIZED_CLASS_NAMES_MALE.PRIEST,
    ["Rogue"] = LOCALIZED_CLASS_NAMES_MALE.ROGUE,
    ["Shaman"] = LOCALIZED_CLASS_NAMES_MALE.SHAMAN,
    ["Warlock"] = LOCALIZED_CLASS_NAMES_MALE.WARLOCK,
    ["Warrior"] = LOCALIZED_CLASS_NAMES_MALE.WARRIOR,
    ["Death Knight"] = LOCALIZED_CLASS_NAMES_MALE.DEATHKNIGHT,
    ["Monk"] = LOCALIZED_CLASS_NAMES_MALE.MONK,
    ["Demon Hunter"] = LOCALIZED_CLASS_NAMES_MALE.DEMONHUNTER,
	["Evoker"] = LOCALIZED_CLASS_NAMES_MALE.EVOKER,

    -- Female Class Names --
    ["DruidF"] = LOCALIZED_CLASS_NAMES_FEMALE.DRUID,
    ["HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.HUNTER,
    ["MageF"] = LOCALIZED_CLASS_NAMES_FEMALE.MAGE,
    ["PaladinF"] = LOCALIZED_CLASS_NAMES_FEMALE.PALADIN,
    ["PriestF"] = LOCALIZED_CLASS_NAMES_FEMALE.PRIEST,
    ["RogueF"] = LOCALIZED_CLASS_NAMES_FEMALE.ROGUE,
    ["ShamanF"] = LOCALIZED_CLASS_NAMES_FEMALE.SHAMAN,
    ["WarlockF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARLOCK,
    ["WarriorF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARRIOR,
    ["Death KnightF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEATHKNIGHT,
    ["MonkF"] = LOCALIZED_CLASS_NAMES_FEMALE.MONK,
    ["Demon HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEMONHUNTER,
	["EvokerF"] = LOCALIZED_CLASS_NAMES_FEMALE.EVOKER,

    ["Game Master"] = "Maestro de juego",

    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "Alternar WIM 'Activado' y 'Desactivado'.",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "Activar y desactivar el modo de depuración.",

    -- Filters.lua --
    ["Whispers Sent by Addons"] = "Susurros enviados por addons",
    ["WhisperSelect Part 1"] = "Selección de susurros parte 1",
    ["Example Spam Blocker"] = "Ejemplo del bloqueador de spam",
    ["WhisperSelect Part 2"] = "Selección de susurros parte 2",
    ["Filter Name"] = "Nombre de filtro",
    ["Filter By"] = "Filtrar por",
    ["Pattern"] = "Patrón",
    ["User Type"] = "Tipo de jugador",
    ["Level"] = "Nivel",
    ["Friends"] = "Amigos",
    ["Guild Members"] = "Miembros de hermandad",
    ["Party Members"] = "Miembros de grupo",
    ["Raid Members"] = "Miembros de banda",
    ["Cross-Realm"] = "Interreinos",
    ["Everyone"] = "Todos",
    ["User must be at least level:"] = "El jugador debe tener al menos un nivel:",
    ["Apply to messages received."] = "Aplicar a los mensajes recibidos.",
    ["Apply to messages sent."] = "Aplicar a los mensajes enviados.",
    ["Apply to:"] = "Aplicar a:",
    ["All Classes"] = "Todas las clases",
    ["Action to Perform:"] = "Acción a realizar:",
    ["Allow"] = "Permitir",
    ["Ignore"] = "Ignorar",
    ["Blocked"] = "Bloqueado",
    ["Save"] = "Guardar",
    ["Cancel"] = "Cancelar",
    ["Edit Filter"] = "Editar filtro",
    ["Add Filter"] = "Añadir filtro",

    -- History.lua --
    ["WIM History Button"] = "Botón de historial de WIM",
    ["Click to view message history."] = "Haz clic para ver el historial de mensajes.",
    ["WIM pruned %d |4message:messages; from your history."] = "WIM eliminó %d |4mensaje:mensajes; de tu historial.",
    ["History Viewer"] = "Visor de historial",
    ["Filters"] = "Filtros",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "¿Está seguro de que desea eliminar todo el historial guardado para %s en %s?",
    ["Search resulted in %d |4message:messages;."] = "La búsqueda resultó en %d |4mensaje:mensajes;.",
    ["No results found!"] = "¡No se han encontrado resultados!",
    ["Search"] = "Buscar",
    ["Show All"] = "Mostrar todos",
    ["Loading History"] = "Cargando historial",
    ["Chat View"] = "Vista de chat",
    ["Text View"] = "Vista de texto",
    ["BBCode"] = "BBCode",
    ["WIM History Viewer can be accessed any time by typing:"] = "Se puede acceder al visor de historial de WIM en cualquier momento escribiendo:",
    ["WIM History Viewer"] = "Visor de historial de WIM",
    ["Display history viewer."] = "Mostrar visor de historial",

    -- ldb.lua --
    ["No New Messages"] = "No hay mensajes nuevos",

    -- Menu.lua --
    ["Whispers"] = "Susurros",
    ["Chat"] = "Chat",

    -- Negotiate.lua --
    ["WIM Update Available!"] = "¡Actualización WIM disponible!",

    -- ShortcutBar.lua --
    ["Player Location"] = "Zona del jugador",
    ["Unknown"] = "Desconocido",
    ["Click to update..."] = "Haz clic para actualizar...",
    ["Invite to Party"] = "Invitar al grupo",
    ["Invite to Guild"] = "Invitar a la hermandad",
    ["Add Friend"] = "Añadir amigo",
    ["Ignore Player"] = "Ignorar jugador",
    ["Are you sure you want to\nignore %s?"] = "¿Estás seguro de que quieres\nignorar a %s?",
    ["Right-Click for profile links..."] = "Haz clic derecho para enlaces de perfil...",
    ["Profile Links"] = "Enlaces de perfil",
    ["Location"] = "Zona",
    ["Game"] = "Juego",
    ["Realm"] = "Reino",
    ["Character"] = "Personaje",
	["Copy Name"] = "Copiar nombre",

    -- Tutorials.lua --
    ["View Updates"] = "Ver actualizaciones",

    -- WhisperEngine.lua --
    ["Whisper Received!"] = "¡Susurro recibido!",
    ["Recently Sent Messages"] = "Mensajes enviados recientemente",
    ["Users in %s"] = "Usuarios en %s",

    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "¡Estás a punto de borrar toda la historia de WIM!",
    ["This action will reload your user interface."] = "Esta acción volverá a cargar tu interfaz de usuario.",
    ["Do you want to continue?"] = "¿Quieres continuar?",
    ["You are about to restore WIM's filters to it's default settings!"] = "¡Está a punto de restaurar los filtros de WIM a su configuración predeterminada!",
    ["Usage"] = "Uso",
    ["Clear various WIM data."] = "Borrar varios datos WIM.",

    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "Comandos de barra diagonal WIM",
    ["Hide or show {all, whisper, chat} windows."] = "Ocultar o mostrar ventanas {todas, de susurro, de chat}.",
    ["To see a list of available WIM slash commands type:"] = "Para ver una lista de comandos de barra diagonal WIM, escribe:",
    ["Display available slash commands."] = "Mostrar los comandos de barra diagonal disponibles.",
    ["Reload User Interface."] = "Recargar la interfaz del usuario",

    -- TabHandler.lua --
    ["Manipulating Tabs"] = "Manipular pestañas",

    -- WindowHandler.lua --
    ["Window Resized!"] = "¡Ventana redimensionada!",
    ["Creating Tab Groups"] = "Crear grupos de pestañas",
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "Puedes agrupar dos o muchas ventanas juntas por <Mayús-clic> en una ventana y arrastrándola encima de otra.",
    ["Resizing Windows"] = "Redimensionar Ventanas",
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "Puedes redimensionar una ventana manteniendo presionado <Mayús> y arrastrando la esquina inferior derecha de la ventana.",
    ["Demo Window"] = "Ventana de demonstración",
    ["<Shift-Click> to close window."] = "<Mayús-clic> para cerrar la ventana.",
    ["Message Window Hidden"] = "Ventana de mensaje oculta",
    ["Default"] = "Predeterminado",
    ["%s is Away From Keyboard: %s"] = "%s está ausente: %s",
    ["%s does not wish to be disturbed: %s"] = "%s no desea ser molestrado: %s",
    ["Right-Mouse Click!"] = "¡Haz clic derecho!",
    ["There might be useful tools hidden under the message box. Right-Click to see them!"] = "Se puede haber herramientas útiles ocultas debajo del cuadro de mensaje. ¡Haz clic derecho para verlas!",

    -- Options.lua --
    ["Display WIM's options."] = "Mostrar opciones de WIM",
    ["Resetting WIM will clear all of your settings!"] = "¡Al restablecer WIM se borrarán todas las configuraciones!",
    ["A reset will reload your user interface."] = "Un restablecimiento recargará tu interfaz de usuario.",
    ["Reset all options to default."] = "Restablecer todas las opciones a las predeterminadas.",

    -- CoreOptions --
    ["Created By:"] = "Creado por:",
    ["Special Thanks:"] = "Agradecimiento especial:",
    ["Welcome!"] = "¡Bienvenido!",
    ["Enable WIM"] = "Activar WIM",
    ["Display Minimap Icon"] = "Mostrar icono del minimapa",
    ["<Right-Click> to show unread messages."] = "<Haz clic derecho> para mostrar mensajes no leídos",
	["Display Addon Compartment Icon"] = "Mostrar icono del compartimento de addons",
    ["Display Tutorials"] = "Mostrar tutoriales",
    ["Reset Tutorials"] = "Restablecer tutoriales",
    ["Credits"] = "Créditos",
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "Este es un mensaje largo que contiene emoticonos y urls 8). La página de WIM es www.WIMAddon.com.",
    ["Message Formatting"] = "Formato de mensaje",
    ["Manipulate how WIM displays messages."] = "Manipula cómo WIM muestra los mensajes.",
    ["Preview"] = "Vista previa",
    ["Display Time Stamps"] = "Mostrar sellos de tiempo",
    ["Display Emoticons"] = "Mostrar emoticonos",
    ["Display URLs as Links"] = "Mostrar URLs como enlaces",
    ["Indent long messages."] = "Sangrar mensajes largos",
    ["Bracket names."] = "Nombres en paréntesis",
    ["Window Behavior"] = "Comportamiento",
    ["You can control how windows behave while you are in different situations."] = "Puedes controlar cómo se comportan las ventanas mientras estás en diferentes situaciones.",
    ["Intercept Slash Commands"] = "Interceptar comandos de barra diagonal",
    ["Obey autofocus rules when opening frames via the menu. (autofocus if unchecked)"] = "Obedecer las reglas de enfoque automático al abrir marcos",
    ["Use the same rules for all states."] = "Usar las mismas reglas para todos los estados",
    ["Behaviors for state:"] = "Comportamientos de estado:",
    ["Pop-Up window when message is sent."] = "Ventana emergente cuando se envía un mensaje",
    ["Pop-Up window when message is received."] = "Ventana emergente cuando se recibe el mensaje",
    ["Auto focus a window when it is shown."] = "Autoenfocar una ventana cuando se muestra",
    ["Keep focus on window after sending a message."] = "Mantener el foco en la ventana después de enviar un mensaje",
    ["Suppress messages from the default chat frame."] = "Suprimir los mensajes del marco de chat predeterminado",
    ["Window Settings"] = "Ventana",
    ["Some settings may be limited by certain skins."] = "Algunas configuraciones pueden estar limitadas por ciertos estilos.",
    ["Default Width"] = "Anchura predeterminada",
    ["Default Height"] = "Altura predeterminada",
    ["Window Scale"] = "Escala de la ventana",
    ["Window Alpha"] = "Transparencia de la ventana",
    ["Set Window Spawn Location"] = "Establecer ubicación de generación de ventana",
    ["Up"] = "Arriba",
    ["Down"] = "Abajo",
    ["Left"] = "Izquierdo",
    ["Right"] = "Derecho",
    ["Cascade overlapping windows."] = "Ventanas superpuestas en cascada",
    ["Ignore arrow keys in message box."] = "Ignorar las teclas de flecha en el cuadro de mensaje",
    ["Allow <ESC> to hide windows."] = "Permitir que <ESC> oculte ventanas",
    ["Display Settings"] = "Visualización",
    ["Configure general window display settings."] = "Configura ajustes generales de visualización de ventana.",
    ["Window Skin:"] = "Estilo de ventana:",
    ["Version"] = "Versión",
    ["Color: System Messages"] = "Color: Mensajes de sistema",
    ["Color: Error Messages"] = "Color: Mensajes de error",
    ["Color: URL - Web Addresses"] = "Color: URL - Dirección de web",
    ["Color: History Messages Sent"] = "Color: Mensajes de historial enviados",
    ["Color: History Messages Received"] = "Color: Mensajes de historial recibidos",
    ["Enable window fading effects."] = "Activar efectos de desvanecimiento de ventana",
    ["Enable window animation effects."] = "Activar efectos de animación de ventana",
    ["Display item links when hovering over them."] = "Mostrar enlaces de objetos al pasar el cursor sobre ellos",
    ["Fonts"] = "Fuentes",
    ["Configure the fonts used in WIM's message windows."] = "Configura las fuentes utilizadas en las ventanas de mensajes de WIM.",
    ["Font Outline"] = "Contorno de fuente",
    ["Thin"] = "Delgado",
    ["Thick"] = "Grueso",
    ["Use font suggested by skin."] = "Usar fuente sugerida por el estilo",
    ["Chat Font Size"] = "Tamaño de fuente del chat",
    ["Configure general display settings when dealing with whispers."] = "Configura ajustes generales de pantalla cuando se trata de susurros.",
    ["Color: Messages Sent"] = "Color: Mensajes enviados",
    ["Color: Messages Received"] = "Color: Mensajes recibidos",
    ["Color: BNet Messages Sent"] = "Color: Mensajes de BNet enviados",
    ["Color: BNet Messages Received"] = "Color: Mensajes de BNet recibidos",
    ["Use colors suggested by skin."] = "Usar colores sugeridos por el estilo",
    ["Display user class icons and details."] = "Mostrar iconos de clase de usuario y detalles",
    ["Requires who lookups."] = "Requiere búsqueda de quién",
    ["Display Shortcut Bar"] = "Mostrar barra de acceso directo",
    ["Allow"] = "Permitir",
    ["Ignore"] = "Ignorar",
    ["Block"] = "Bloquear",
    ["Filtering"] = "Filtro",
    ["Filtering allows you to control which messages are handled as well as how they are handled by WIM."] = "El filtro te permite controlar qué mensajes se manejan y cómo WIM los maneja.",
    ["Enable Filtering"] = "Activar filtro",
    ["Protected"] = "Protegido",
    ["Action:"] = "Acción:",
    ["Occurrences:"] = "Ocurrencias:",
    ["Delete Filter"] = "Eliminar filtro",
    ["History"] = "Historial",
    ["WIM can store conversations to be viewed at a later time."] = "WIM puede archivar conversaciones para verlas más adelante.",
    ["Enable History"] = "Activar historial",
    ["Messages"] = "Mensajes",
    ["Preview history inside message windows."] = "Previsualización del historial",
    ["Record Friends"] = "Grabar amigos",
    ["Record Guild"] = "Grabar hermandad",
    ["Record Everyone"] = "Grabar todos",
    ["Record Chat"] = "Grabar chat",
    ["Maintenance"] = "Mantenimiento",
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "Permite que tus registros de historial crezcan demasiado afectará el rendimiento del juego, por lo tanto, se recomienda que uses las siguientes opciones.",
    ["Save a maximum number of messages per person."] = "Guardar un número máximo de mensajes por persona",
    ["%d |4Week:Weeks;"] = "%d |4Semana:Semanas;",
    ["Automatically delete old messages."] = "Eliminar automáticamente los mensajes antiguos",
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM es una característica que permite a los usuarios con WIM interactuar de formas que los susurros normales no pueden.",
    ["Enable WIM-2-WIM"] = "Activar WIM-2-WIM",
    ["Privacy"] = "Privacidad",
    ["Restrict the data that is shared."] = "Restringir los datos que se comparten.",
    ["Allow others to see me typing."] = "Permitir que otros me vean escribiendo.",
    ["Allow others to see my location."] = "Permitir a otros ver mi ubicación.",
    ["Main"] = "Principal",
    ["General"] = "General",
    ["User Level"] = "Nivel del jugador",
    ["Windows will also be hidden when frames such as the world map are shown."] = "Ventanas también estará oculto cuando se muestren marcos como el mapa del mundo.",
    ["Sounds"] = "Sonidos",
    ["Configure various sound events and how they are triggered."] = "Configura varios eventos de sonido y cómo se activan.",
    ["Play sound when a whisper is received."] = "Reproducir sonido cuando se recibe un susurro",
    ["Play special sound for friends."] = "Reproducir un sonido especial para amigos",
    ["Play special sound for battle.net friends."] = "Reproducir un sonido especial para amigos de battle.net",
    ["Play special sound for guild members."] = "Reproducir un sonido especial para miembros de la hermandad",
    ["Play sound when a whisper is sent."] = "Reproducir sonido cuando se envía un susurro",
    ["Allow others to see my talent spec."] = "Permitir que otros vean mi especialización de talento",
    ["Window Strata:"] = "Estratos de ventana:",
	["Background"] = BACKGROUND,
	["Low"] = LOW,
	["Medium"] = "Medio",
	["High"] = "Alto",
	["Dialog"] = ENABLE_DIALOG,
	["Tooltip"] = true,
    ["Unlock from Minimap"] = "Desbloquear del minimapa",
    ["Press <Tab> to advance to next tell target."] = "Presionar <Tab> para avanzar al siguiente objetivo",
    ["Force sounds when game sound is disabled."] = "Forzar sonidos cuando el sonido del juego está desactivado",
    ["Colorize names."] = "Colorear nombres",
    ["Clamp window to screen."] = "Anclar la ventana a la pantalla",
    ["Group with whisper windows."] = "Agrupar con ventanas de susurros",

    -- TabManagement.lua --
    ["Tab Management"] = "Gestión de pestañas",
    ["Automatically manage your open windows and place them into appropriate tab groups."] = "Gestiona automáticamente tus ventanas abiertas y colóquelas en grupos de pestañas apropiados.",
    ["Automatically group whispers."] = "Agrupar automáticamente los susurros",
    ["Automatically group chat windows."] = "Agrupar automáticamente las ventanas de chat",
    ["Place friends in their own group."] = "Colocar amigos en su propio grupo",
    ["Place guild members in their own group."] = "Colocar a los miembros de la hermandad en su propio grupo",
    ["Does not apply to windows already opened."] = "No se aplica a las ventanas ya abiertas.",

    -- Talent Specs --
    ["Hybrid"] = "Híbrido",

    -- Filters.lua --
    ["Show Alert"] = "Mostrar alerta",
    ["WIM has blocked a message from %s."] = "WIM ha bloqueado un mensaje de %s.",
    ["View Blocked Message"] = "Ver mensaje bloqueado",
    ["Blocked Message"] = "Mensaje bloqueado",

    -- MinimapIcon.lua
    ["Show Unread Messages"] = "Mostrar mensajes no leídos",
    ["Show All Windows"] = "Mostrar todas las ventanas",
    ["Hide All Windows"] = "Ocultar todas las ventanas",

    --Emoticons.lua
    ["Also"] = "También",
    ["More"] = "Más",
    ["Emoticons"] = "Emoticones",

    --Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = "Tus conversaciones se han ocultado para limpiar tu pantalla mientras estás en combate. Para desactivar esto escribe",
    ["Expose"] = "Expose",
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = "Expose es una característica inspirada en Mac OS X que le permite borrar rápidamente la pantalla de ventanas y luego restaurarlas a su posición original.",
    ["Auto hide/restore windows during combat."] = "Ocultar/restaurar ventanas automáticamente durante el combate",
    ["Delay if I am typing a message."] = "Retrasar si estoy escribiendo un mensaje",
    ["Border Size"] = "Tamaño del borde",
    ["Only while in an instance."] = "Solo en una estancia",
    ["Show Border"] = "Mostrar borde",
    ["Animation Direction:"] = "Dirección de animación:",

    --ChatEngine.lua
    ["WIM will manage this chat type within its own message windows."] = "WIM gestionará este tipo de chat dentro de sus propias ventanas de mensajes.",
    ["Show Minimap Alerts"] = "Mostrar alertas de minimapa",
    ["Never pop-up on my screen."] = "Nunca aparecer en mi pantalla",
    ["Never suppress messages."] = "Nunca suprimir mensajes",
    ["Include emotes."] = "Incluir emociones",
    ["Have WIM monitor this channel."] = "Haz que WIM supervise este canal.",
    ["Never Pop"] = "Nunca aparecer",
    ["Never have this window pop-up on my screen."] = "Nunca mostrar esta ventana emergente en mi pantalla.",
    ["Never Suppress"] = "Nunca suprimir",
    ["Never suppress messages from the default chat frame."] = "Nunca suprimir mensajes del marco de chat predeterminado.",
    ["Show unread message alert on minimap."] = "Mostrar alerta de mensaje no leído en el minimapa.",
    ["No History"] = "Sin historial",
    ["Do not record history for this channel."] = "No grabar el historial de este canal.",
    ["World Chat"] = "Chat del mundo",
    ["Custom Chat"] = "Chat personalizado",
    ["Community Chat"] = "Chat de comunidad",
    ["Chat"] = "Chat",
    ["Play special sound for %s."] = "Reproducir sonido especial para %s",
    ["Play sound when a message is received."] = "Reproducir sonido cuando se recibe un mensaje",
    ["Play sound when a message is sent."] = "Reproducir sonido cuando se envía un mensaje",
    ["Do not play sounds for this channel."] = "No reproducir sonidos para este canal.",
    ["No Sound"] = "Sin sonido",
    ["Sensitivity"] = "Sensibilidad",
    ["Enable WorldFrame Click Detection."] = "Activar detección de clic WorldFrame",

    --OffScreenTracker.lua
    ["WIM Window Off Screen"] = "Ventana WIM fuera de pantalla",
    ["Click to reposition."] = "Haz clic para reposicionar.",

	-- Whisper Mode Warnings
    ["Whisper Mode: In-line"] = "Modo de susurro: en línea",
	["Set whispers to In-line"] = "Establecer susurros en línea",
	["Message suppression requires whispers to be set to 'In-line'."] = "La supresión de mensajes requiere que los susurros estén configurados en 'en línea'.",
	["It is recommended for whispers to be set to in-line in order to handle their behavior properly."] = "Se recomienda configurar los susurros en línea para manejar su comportamiento correctamente.",

	-- Skins --
	["Blue"] = "Azul",
	["Green"] = "Verde",
	["Red"] = "Rojo",
	["Yellow"] = "Amarillo",
};

if WIM.getLocale() == "esES" then
	WIM.AddLocale("esES", translations);
else
	WIM.AddLocale("esMX", translations);
end
