--[[
    Language Localization: frFR
    Translated by: name <email address>
]]

WIM.AddLocale("frFR", {

    ["WIM (WoW Instant Messenger)"] = "WIM (WoW Instant Messenger)",
    ["_Description"] = "WIM est un addon qui apporte un sens familier à la communication par la discussion dans World of Warcraft. Sur cet écran, vous serez en mesure de personnaliser WIM de l'adapter à vos besoins.",

    ["_DemoText"] = "C'est une fenêtre de démonstration elle n'est pas entièrement fonctionnel. Placez cette fenêtre à l'endroit où vous voulez que toutes les autres fenêtres s'ouvrent. Quand c'est bon, vous pouvez fermer cette fenêtre et vos vos réglages seront sauvegardés.",

    ["_DateFormat"] = "%d/%m/%Y",

    ["Yes"] = "Oui",
    ["No"] = "Non",
    ["None"] = "Aucun",
    ["Cancel"] = "Annuler",
    ["Unknown"] = "Inconnu",
    ["Click to update..."] = "Cliquez pour mettre à jour ...",
    ["Usage"] = "Usage",

    ["state_resting"] = "Repos",
    ["state_combat"] = "Combat",
    ["state_pvp"] = "JcJ",
    ["state_arena"] = "Arène",
    ["state_party"] = "Groupe de donjon",
    ["state_raid"] = "Groupe de raid",
    ["state_other"] = "Normal (Divers)",

    ["Options"] = true,

    ["Up"] = "Haut",
    ["Down"] = "Bas",
    ["Left"] = "Gauche",
    ["Right"] = "Droit",
    ["Ignore"] = "Ignorer",
    ["Block"] = "Bloquer",
    ["Enable WIM"] = "Activer WIM",

    ["Enable"] = "Activer",
    ["Disable"] = "Désactiver",
    ["Enable window fading effects."] = "Activer les effets.",

    ["General"] = "Général",
    ["History"] = "Historique",
    ["Filters"] = "Filtres",

    ["Sort tabs by:"] = "Trier les onglets par :",
	["Window Created"] = "Fenêtre créée",
	["Last Activity"] = "Dernière activité",
    ["Alphabetical"] = "Alphabétique",

  -- Class Names --
	["Druid"] = LOCALIZED_CLASS_NAMES_MALE.DRUID,
    ["Hunter"] = LOCALIZED_CLASS_NAMES_MALE.HUNTER,
    ["Mage"] = LOCALIZED_CLASS_NAMES_MALE.MAGE,
    ["Paladin"] = LOCALIZED_CLASS_NAMES_MALE.PALADIN,
    ["Priest"] = LOCALIZED_CLASS_NAMES_MALE.PRIEST,
    ["Rogue"] = LOCALIZED_CLASS_NAMES_MALE.ROGUE,
    ["Shaman"] = LOCALIZED_CLASS_NAMES_MALE.SHAMAN,
    ["Warlock"] = LOCALIZED_CLASS_NAMES_MALE.WARLOCK,
    ["Warrior"] = LOCALIZED_CLASS_NAMES_MALE.WARRIOR,
    ["Death Knight"] = LOCALIZED_CLASS_NAMES_MALE.DEATHKNIGHT,
    ["Monk"] = LOCALIZED_CLASS_NAMES_MALE.MONK,
    ["Demon Hunter"] = LOCALIZED_CLASS_NAMES_MALE.DEMONHUNTER,
	["Evoker"] = LOCALIZED_CLASS_NAMES_MALE.EVOKER,

    -- Female Class Names --
    ["DruidF"] = LOCALIZED_CLASS_NAMES_FEMALE.DRUID,
    ["HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.HUNTER,
    ["MageF"] = LOCALIZED_CLASS_NAMES_FEMALE.MAGE,
    ["PaladinF"] = LOCALIZED_CLASS_NAMES_FEMALE.PALADIN,
    ["PriestF"] = LOCALIZED_CLASS_NAMES_FEMALE.PRIEST,
    ["RogueF"] = LOCALIZED_CLASS_NAMES_FEMALE.ROGUE,
    ["ShamanF"] = LOCALIZED_CLASS_NAMES_FEMALE.SHAMAN,
    ["WarlockF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARLOCK,
    ["WarriorF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARRIOR,
    ["Death KnightF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEATHKNIGHT,
    ["MonkF"] = LOCALIZED_CLASS_NAMES_FEMALE.MONK,
    ["Demon HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEMONHUNTER,
	["EvokerF"] = LOCALIZED_CLASS_NAMES_FEMALE.EVOKER,

    ["Game Master"] = "Maître de jeu",

    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "Basculer WIM 'Activé' et 'Désactivé'.",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "Basculer en débogage 'Activé' et 'Désactivé'.",

    -- Filters.lua --
    ["Whispers Sent by Addons"] = "Chuchotements envoyés par l'addons",
    ["WhisperSelect Part 1"] = "Sélection de chuchotement partie 1",
    ["Example Spam Blocker"] = "Exemple de bloqueur de spam",
    ["WhisperSelect Part 2"] = "Sélection de chuchotement partie 2",
    ["Filter Name"] = "Nom du filtre",
    ["Filter By"] = "Filtre par",
    ["Pattern"] = "Style",
    ["User Type"] = "Type d'utilisateur",
    ["Level"] = "Niveau",
    ["Friends"] = "Amis",
    ["Guild Members"] = "Membres de guilde",
    ["Party Members"] = "Membres du groupe",
    ["Raid Members"] = "Membres du raid",
    ["Cross-Realm"] = "Inter-royaumes",
    ["Everyone"] = "Tout le monde",
    ["User must be at least level:"] = "L'utilisateur doit être au moins au niveau : ",
    ["Apply to messages received."] = "S'appliquent aux messages reçus.",
    ["Apply to messages sent."] = "S'appliquent aux messages envoyés.",
    ["Apply to:"] = "Appliquer à :",
    ["All Classes"] = "Toutes les classes",
    ["Action to Perform:"] = "Action à exécuter :",
    ["Allow"] = "Autoriser",
    ["Ignore"] = "Ignorer",
    ["Blocked"] = "Bloqué",
    ["Save"] = "Sauver",
    ["Cancel"] = "Annuler",
    ["Edit Filter"] = "Modifier le filtre",
    ["Add Filter"] = "Ajouter un filtre",

    -- History.lua --
    ["WIM History Button"] = "Bouton de l'historique",
    ["Click to view message history."] = "Cliquez pour voir l'historique des messages.",
    ["WIM pruned %d |4message:messages; from your history."] = "WIM taille %d |4message:messages, à partir de votre histoire.",
    ["History Viewer"] = "L'historique",
    ["Filters"] = "Filtres",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "Etes-vous sûr de vouloir supprimer toute l'historique enregistrée de %s sur %s ?",
    ["Search resulted in %d |4message:messages;."] = "Résultat des recherches dans %d |4message:messages;.",
    ["No results found!"] = "Aucun résultat trouvé !",
    ["Search"] = "Recherche",
    ["Show All"] = "Tout afficher",
    ["Loading History"] = "Chargement de l'historique",
    ["Chat View"] = "Vue de la discussion",
    ["Text View"] = "Vue du texte",
    ["BBCode"] = "BBCode",
    ["WIM History Viewer can be accessed any time by typing:"] = "L'historique peut être accessible à tout moment en tapant :",
    ["WIM History Viewer"] = "L'historique",
    ["Display history viewer."] = "Afficher l'historique",

    -- ldb.lua --
    ["No New Messages"] = "Pas de nouveaux messages",

    -- Menu.lua --
    ["Whispers"] = "Chuchotement",
    ["Chat"] = "Discussion",

    -- Negotiate.lua --
    ["WIM Update Available!"] = "Mise à jour disponible !",

    -- ShortcutBar.lua --
    ["Player Location"] = "Zone du joueur",
    ["Unknown"] = "Inconnu",
    ["Click to update..."] = "Cliquez pour mettre à jour...",
    ["Invite to Party"] = "Inv. groupe",
    ["Invite to Guild"] = "Inv. guilde",
    ["Add Friend"] = "Ajouter un ami",
    ["Ignore Player"] = "Ignorer le joueur",
    ["Are you sure you want to\nignore %s?"] = "Êtes-vous sûr de vouloir ignorer %s?",
    ["Right-Click for profile links..."] = "Clic droit pour les liens de profil...",
    ["Profile Links"] = "Liens de profil",
	["Location"] = "Zone",
	["Game"] = "Jeu",
	["Realm"] = "Royaume",
	["Character"] = "Personnage",
	["Copy Name"] = "Copier le nom",

    -- Tutorials.lua --
    ["View Updates"] = "Voir les mises à jour",

    -- WhisperEngine.lua --
    ["Whisper Received!"] = "Chuchoetment reçu !",
    ["Recently Sent Messages"] = "Messages récemment envoyés",
    ["Users in %s"] = "Utilisateurs dans %s",

    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "Vous êtes sur le point d'effacer toutes l'historiques !",
    ["This action will reload your user interface."] = "Cette action se rechargera dans votre interface utilisateur.",
    ["Do you want to continue?"] = "Voulez-vous continuer ?",
    ["You are about to restore WIM's filters to it's default settings!"] = "Vous êtes sur le point de rétablir les filtres WIM à ses paramètres par défaut !",
    ["Usage"] = "Traitement",
    ["Clear various WIM data."] = "Nettoyer les données diverses de WIM",

    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "WIM commandes slash",
    ["Hide or show {all, whisper, chat} windows."] = "Masquer ou afficher les fenêtres {toutes, de chuchotement, de discussion}.",
    ["To see a list of available WIM slash commands type:"] = "Pour voir une liste des commandes slash WIM disponibles, tapez :",
    ["Display available slash commands."] = "Afficher les commandes slash disponibles.",
    ["Reload User Interface."] = "Recharger l'interface utilisateur.",

    -- TabHandler.lua --
    ["Manipulating Tabs"] = "Manipulation des onglets",

    -- WindowHandler.lua --
    ["Window Resized!"] = "Fenêtre redimensionnée !",
	["Creating Tab Groups"] = "Création de groupes d'onglets",
	["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "Vous pouvez regrouper deux fenêtres ou plus en maintenant <Maj> enfoncé et en faisant glisser une fenêtre sur une autre.",
	["Resizing Windows"] = "Redimensionner les fenêtres",
	["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "Vous pouvez redimensionner une fenêtre en maintenant la touche <Maj> enfoncée et en faisant glisser le coin inférieur droit de la fenêtre.",
	["Demo Window"] = "Fenêtre de démonstration",
	["<Shift-Click> to close window."] = "<Maj-clic> pour fermer la fenêtre.",
	["Message Window Hidden"] = "Fenêtre de message masquée",
	["Default"] = "Par défaut",
	["%s is Away From Keyboard: %s"] = "%s est absent : %s",
	["%s does not wish to be disturbed: %s"] = "%s ne souhaite pas être dérangé : %s",
	["Right-Mouse Click!"] = "Clique droit de la souris !",
	["There might be useful tools hidden under the message box. Right-Click to see them!"] = "Il pourrait y avoir des outils utiles cachés sous la boîte de message. Faites un clic droit pour les voir !",

    -- Options.lua --
    ["Display WIM's options."] = "Afficher les options de WIM.",
    ["Resetting WIM will clear all of your settings!"] = "Réinitialisation de WIM et efface la totalité des paramètres !",
    ["A reset will reload your user interface."] = "Une réinitialisation rechargera votre interface.",
    ["Reset all options to default."] = "Réinitialiser toutes les options par défaut.",

    -- CoreOptions --
    ["Created By:"] = "Créé par :",
    ["Special Thanks:"] = "Merci spécial :",
    ["Welcome!"] = "Bienvenue !",
    ["Enable WIM"] = "Activer WIM",
    ["Display Minimap Icon"] = "Afficher l'icône sur la minicarte",
    ["<Right-Click> to show unread messages."] = "<Clic-droit> Pour afficher les messages non lus",
	["Display Addon Compartment Icon"] = "Afficher l’icône du compartiment des addons",
    ["Display Tutorials"] = "Afficher le tutorial",
    ["Reset Tutorials"] = "Réinitialiser le tutorial",
    ["Credits"] = "Crédits",
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "Il s'agit d'un long message qui contient à la fois des émoticônes et des URL 8). La page d’accueil de WIM est www.WIMAddon.com.",
    ["Message Formatting"] = "Format d'un message",
    ["Manipulate how WIM displays messages."] = "Manipulez la façon dont WIM affiche les messages.",
    ["Preview"] = "Aperçu",
    ["Display Time Stamps"] = "Afficher le temps",
    ["Display Emoticons"] = "Afficher les émoticônes",
    ["Display URLs as Links"] = "Afficher les URLs comme les liens",
    ["Indent long messages."] = "Indenter les longs messages",
	["Bracket names."] = "Noms de parenthèses",
    ["Window Behavior"] = "Comportement",
    ["You can control how windows behave while you are in different situations."] = "Vous pouvez contrôler la façon dont se comportent les fenêtres lorsque vous êtes dans des situations différentes.",
    ["Intercept Slash Commands"] = "Intercepter les commandes slash",
    ["Include sent messages in /REPLY."] = "Inclure les messages envoyés dans /r",
	["Obey autofocus rules when opening frames via the menu. (autofocus if unchecked)"] = "Respecter les règles d'autofocus lors de l'ouverture des fenêtres",
    ["Use the same rules for all states."] = "Utilisez les mêmes règles pour tous les etats",
    ["Behaviors for state:"] = "Comportements pour l'etat :",
    ["Pop-Up window when message is sent."] = "Fenêtre contextuelle lorsque le message est envoyé",
    ["Pop-Up window when message is received."] = "Fenêtre contextuelle lorsque le message est reçu",
    ["Auto focus a window when it is shown."] = "Mettre le focus sur une fenêtre lorsqu'elle est affichée",
    ["Keep focus on window after sending a message."] = "Garder le focus sur la fenêtre après l'envoi d'un message",
    ["Suppress messages from the default chat frame."] = "Supprimer les messages de la discussion par défaut",
    ["Window Settings"] = "Réglages de la fenêtre",
    ["Some settings may be limited by certain skins."] = "Quelques cadres peuvent être limités par certain skin.",
    ["Default Width"] = "Largeur par défaut",
    ["Default Height"] = "Hauteur par défaut",
    ["Window Scale"] = "Échelle de la fenêtre",
    ["Window Alpha"] = "Alpha de la fenêtre",
    ["Set Window Spawn Location"] = "Fenêtre du lieu de multiplication définit",
    ["Up"] = "Haut",
    ["Down"] = "Bas",
    ["Left"] = "Gauche",
    ["Right"] = "Droit",
    ["Cascade overlapping windows."] = "Cascade de fenêtres superposées",
    ["Ignore arrow keys in message box."] = "Ignorer les touches de direction dans un message",
    ["Allow <ESC> to hide windows."] = "Allouer <ESC> pour cacher les fenêtres",
    ["Display Settings"] = "Paramètres d'affichage",
    ["Configure general window display settings."] = "Configuration général des paramètres d'affichage des fenêtres.",
    ["Window Skin:"] = "Skin de la fenêtre :",
    ["Version"] = "Version",
    ["Color: System Messages"] = "Couleur : messages du système",
    ["Color: Error Messages"] = "Couleur : messages d'erreur",
    ["Color: URL - Web Addresses"] = "Couleur : URL - adresses web",
    ["Color: History Messages Sent"] = "Couleur : messages d'historique envoyés",
    ["Color: History Messages Received"] = "Couleur : messages d'historique reçus",
    ["Use colors suggested by skin."] = "Utilisez des couleurs proposé pour le skin",
    ["Enable window fading effects."] = "Activer la fenêtre des effets",
    ["Enable window animation effects."] = "Activer les effets d'animation de la fenêtre",
    ["Display item links when hovering over them."] = "Afficher le lien vers les objets lors du survol de la souris",
    ["Fonts"] = "Polices",
    ["Configure the fonts used in WIM's message windows."] = "Configurez les polices utilisées dans les fenêtres de message.",
    ["Font Outline"] = "Contour de la police",
    ["Thin"] = "Fin",
    ["Thick"] = "Épais",
    ["Use font suggested by skin."] = "Utiliser la police suggérée par le skin",
    ["Chat Font Size"] = "Taille du texte",
    ["Configure general display settings when dealing with whispers."] = "Configurez les paramètres d'affichage général lorsqu'il s'agit de chuchotements.",
    ["Color: Messages Sent"] = "Coleur : messages envoyés",
    ["Color: Messages Received"] = "Coleur : messages reçus",
	["Color: BNet Messages Sent"] = "Coleur : messages de BNet envoyés",
	["Color: BNet Messages Received"] = "Coleur : messages de BNet reçus",
    ["Use colors suggested by skin."] = "Utiliser des couleurs proposées par le skin",
    ["Display user class icons and details."] = "Afficher les icônes de classe et les détails",
    ["Requires who lookups."] = "Besoin de recherches qui",
    ["Display Shortcut Bar"] = "Afficher la barre rapide",
    ["Allow"] = "Autoriser",
    ["Ignore"] = "Ignore",
    ["Block"] = "Bloquer",
    ["Filtering"] = "Filtrage",
    ["Filtering allows you to control which messages are handled as well as how they are handled by WIM."] = "Le filtrage vous permet de contrôler quels messages sont transformés, ainsi que la façon dont ils seront traités WIM.",
    ["Enable Filtering"] = "Activer le filtrage",
    ["Protected"] = "Protégées",
    ["Action:"] = "Action :",
    ["Occurrences:"] = "Occurrences :",
    ["Delete Filter"] = "Supprimer le filtre",
    ["History"] = "L'historique",
    ["WIM can store conversations to be viewed at a later time."] = "WIM peut enregistrer les conversations pour être consultées ultérieurement.",
    ["Enable History"] = "Activer l'historique",
    ["Messages"] = "Messages",
    ["Preview history inside message windows."] = "Aperçu de l'historique à l'intérieur des fenêtres de message",
    ["Record Friends"] = "Enregistrer les amis",
    ["Record Guild"] = "Enregistrer la guilde",
    ["Record Everyone"] = "Enregistrer tout le monde",
    ["Record Chat"] = "Enregistrer la discussion",
    ["Maintenance"] = "Maintenance",
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "L'enregistrement de l'historique de tous les messages, va devenir trop volumineux et affectera la performance du jeu, il est donc recommandé d'utiliser les options suivantes.",
    ["Save a maximum number of messages per person."] = "Enregistrer un nombre maximal de messages par personne",
    ["%d |4Week:Weeks;"] = "%d |4semaine:semaines;",
    ["Automatically delete old messages."] = "Supprimer automatiquement les anciens messages",
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM est une fonctionnalité qui permet à des joueurs qui utilisent aussi WIM d'interagir de manière à chuchoter normalement s'ils ne peuvent pas.",
    ["Enable WIM-2-WIM"] = "Activer WIM-2-WIM",
    ["Privacy"] = "Confidentialité",
    ["Restrict the data that is shared."] = "Limiter les données qui sont partagées",
    ["Allow others to see me typing."] = "Permettre aux autres de me voir taper",
    ["Allow others to see my location."] = "Permettre aux autres de voir ma position.",
    ["Main"] = "Principal",
    ["General"] = "Général",
    ["User Level"] = "Niveau du joueur",
    ["Windows will also be hidden when frames such as the world map are shown."] = "La fenêtre va également se cacher lorsque les cadres telles que la carte mondiale sera montrés.",
    ["Sounds"] = "Son",
    ["Configure various sound events and how they are triggered."] = "Configurez le son de divers événements et la façon dont ils sont déclenchés.",
    ["Play sound when a whisper is received."] = "Jouer un son quand un chuchotement est reçu",
    ["Play special sound for friends."] = "Jouer un son spécial pour les amis",
	["Play special sound for battle.net friends."] = "Jouer un son spécial pour les amis de battle.net",
    ["Play special sound for guild members."] = "Jouer un son spécial pour les membres de la guilde",
    ["Play sound when a whisper is sent."] = "Jouer un son lorsqu'un chuchotement est envoyé",
    ["Allow others to see my talent spec."] = "Permettre aux autres de voir mes talents",
    ["Window Strata:"] = "Strate de la fenêtre :",
	["Background"] = BACKGROUND,
	["Low"] = LOW,
	["Medium"] = "Moyenne",
	["High"] = "Élevée",
	["Dialog"] = ENABLE_DIALOG,
	["Tooltip"] = "Infobulle",
    ["Unlock from Minimap"] = "Déverrouiller de la minicarte",
	["Press <Tab> to advance to next tell target."] = "Appuyer sur <Tab> pour passer à la prochaine cible",
    ["Force sounds when game sound is disabled."] = "Forcer les sons lorsque le son du jeu est désactivé",
    ["Colorize names."] = "Colorer les noms",
    ["Clamp window to screen."] = "Fixer la fenêtre à l'écran",
    ["Group with whisper windows."] = "Grouper avec les fenêtres de chuchotement",

-- TabManagement.lua --
    ["Tab Management"] = "Gestion d'onglet",
    ["Automatically manage your open windows and place them into appropriate tab groups."] = "Gérez automatiquement vos fenêtres ouvertes et placez-les dans des groupes d'onglets appropriés.",
    ["Automatically group whispers."] = "Grouper automatiquement les chuchotements",
	["Automatically group chat windows."] = "Grouper automatiquement les fenêtres de discussion",
    ["Place friends in their own group."] = "Placer les amis dans le groupe",
    ["Place guild members in their own group."] = "Placer les membres de la guilde dans leur propre groupe",
    ["Does not apply to windows already opened."] = "Ne s'applique pas à la fenêtre déjà ouverte",

    -- Talent Specs --
    ["Hybrid"] = "Hybride",

    -- Filters.lua --
    ["Show Alert"] = "Afficher une alerte",
    ["WIM has blocked a message from %s."] = "Afficher une alerte",
    ["View Blocked Message"] = "Voir message bloqué",
    ["Blocked Message"] = "Message bloqué",

    -- MinimapIcon.lua
    ["Show Unread Messages"] = "Afficher les messages non lus",
    ["Show All Windows"] = "Afficher tous les fenêtres",
    ["Hide All Windows"] = "Masquer toutes les fenêtres",

    --Emoticons.lua
    ["Also"] = "Également",
    ["More"] = "Plus",
    ["Emoticons"] = "Émoticônes",

    --Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = "Vos conversations ont été cachés afin de vider votre écran tout en combat. Pour désactiver cette fonction, tapez :",
    ["Expose"] = "Exposé",
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = "Exposé est inspiré d'une application Mac OS X, fonction qui permet de masquer temporairement toutes les fenêtres, puis les remets à leurs position initiale.",
    ["Auto hide/restore windows during combat."] = "Auto masquer / restaurer les fenêtres pendant le combat",
	["Delay if I am typing a message."] = "Retarder si je tape un message",
    ["Border Size"] = "Taille de la bordure",
    ["Only while in an instance."] = "Seulement dans une instance",
    ["Show Border"] = "Afficher la bordure",
    ["Animation Direction:"] = "Direction de l'animation :",

    --ChatEngine.lua
    ["WIM will manage this chat type within its own message windows."] = "WIM gére ce type de discussion au sein de ses propre fenêtres de message.",
    ["Show Minimap Alerts"] = "Afficher une alerte sur la minicarte",
    ["Never pop-up on my screen."] = "Ne jamais faire apparaître sur mon écran",
    ["Never suppress messages."] = "Ne jamais supprimer des messages",
	["Include emotes."] = "Inclure des émoticônes",
    ["Have WIM monitor this channel."] = "WIM surveille ce canal",
	["Never Pop"] = "Ne jamais apparaître",
	["Never have this window pop-up on my screen."] = "Ne jamais faire apparaître cette fenêtre sur mon écran",
    ["Never Suppress"] = "Ne jamais supprimer",
    ["Never suppress messages from the default chat frame."] = "Ne jamais supprimer les messages de la fenêtre de discussion par défaut",
    ["Show unread message alert on minimap."] = "Afficher l'alerte de message non lu sur la minicarte",
    ["No History"] = "Aucun historique",
    ["Do not record history for this channel."] = "Ne pas enregistrer l'historique de ce canal",
    ["World Chat"] = "Discussion du monde",
    ["Custom Chat"] = "Discussion personnalisée",
    ["Community Chat"] = "Discussion de communauté",
    ["Chat"] = "Discussion",
    ["Play special sound for %s."] = "Jouer le son spécial pour %s",
    ["Play sound when a message is received."] = "Jouer un son quand un message est reçu",
    ["Play sound when a message is sent."] = "Jouer un son quand un message est envoyé",
	["Do not play sounds for this channel."] = "Ne pas jouer de sons pour ce canal",
	["No Sound"] = "Pas de son",
	["Sensitivity"] = "Sensibilité",
	["Enable WorldFrame Click Detection."] = "Activer la détection des clics WorldFrame",

	--OffScreenTracker.lua
	["WIM Window Off Screen"] = "Fenêtre WIM hors écran",
	["Click to reposition."] = "Cliquez pour repositionner.",

	-- Whisper Mode Warnings
    ["Whisper Mode: In-line"] = "Mode de chuchotement : en ligne",
	["Set whispers to In-line"] = "Régler les chuchotements sur en ligne",
	["Message suppression requires whispers to be set to 'In-line'."] = "La suppression des messages nécessite que les chuchotements soient réglés sur 'En ligne'.",
	["It is recommended for whispers to be set to in-line in order to handle their behavior properly."] = "Il est recommandé de régler les chuchotements sur En ligne afin de gérer correctement leur comportement.",

	-- Skins --
	["Blue"] = "Bleu",
	["Green"] = "Vert",
	["Red"] = "Rouge",
	["Yellow"] = "Jaune",
});
