--[[
    Language Localization: itIT
]]

WIM.AddLocale("itIT", {
    ["WIM (WoW Instant Messenger)"] = "WIM (WoW Instant Messenger)",
    ["_Description"] = "WIM è un addon che rende familiare la comunicazione tramite chat in World of Warcraft. In questa schermata potrai personalizzare WIM per adattarlo alle tue esigenze.",

    ["_DemoText"] = "Questa è una finestra dimostrativa e non è completamente funzionante. Posiziona questa finestra nel punto in cui vuoi che tutte le altre finestre vengano aperte. Quando hai finito, puoi chiudere questa finestra e le tue impostazioni verranno salvate.",

    ["_DateFormat"] = "%d/%m/%Y",

    ["Yes"] = "Sì",
    ["No"] = "No",
    ["None"] = "Nessuno",
    ["Cancel"] = "Annulla",
    ["Unknown"] = "Sconosciuto",
    ["Click to update..."] = "Clicca per aggiornare...",
    ["Usage"] = "Utilizzo",

    ["state_resting"] = "Riposo",
    ["state_combat"] = "Combattimento",
    ["state_pvp"] = "PvP",
    ["state_arena"] = "Arena",
    ["state_party"] = "Gruppo di istanza",
    ["state_raid"] = "Gruppo raid",
    ["state_other"] = "Normale (altro)",

    ["Options"] = "Opzioni",

    ["Up"] = "Su",
    ["Down"] = "Giù",
    ["Left"] = "Sinistra",
    ["Right"] = "Destra",
    ["Ignore"] = "Ignora",
    ["Block"] = "Blocca",
    ["Enable WIM"] = "Abilita WIM",

    ["Enable"] = "Abilita",
    ["Disable"] = "Disabilita",
    ["Enable window fading effects."] = "Abilita gli effetti di dissolvenza delle finestre.",

    ["General"] = "Generale",
    ["History"] = "Cronologia",
    ["Filters"] = "Filtri",

    ["Sort tabs by:"] = "Ordina le schede per:",
	["Window Created"] = "Finestra creata",
	["Last Activity"] = "Ultima attività",
    ["Alphabetical"] = "Alfabetico",

    -- Class Names --
    ["Druid"] = LOCALIZED_CLASS_NAMES_MALE.DRUID,
    ["Hunter"] = LOCALIZED_CLASS_NAMES_MALE.HUNTER,
    ["Mage"] = LOCALIZED_CLASS_NAMES_MALE.MAGE,
    ["Paladin"] = LOCALIZED_CLASS_NAMES_MALE.PALADIN,
    ["Priest"] = LOCALIZED_CLASS_NAMES_MALE.PRIEST,
    ["Rogue"] = LOCALIZED_CLASS_NAMES_MALE.ROGUE,
    ["Shaman"] = LOCALIZED_CLASS_NAMES_MALE.SHAMAN,
    ["Warlock"] = LOCALIZED_CLASS_NAMES_MALE.WARLOCK,
    ["Warrior"] = LOCALIZED_CLASS_NAMES_MALE.WARRIOR,
    ["Death Knight"] = LOCALIZED_CLASS_NAMES_MALE.DEATHKNIGHT,
    ["Monk"] = LOCALIZED_CLASS_NAMES_MALE.MONK,
    ["Demon Hunter"] = LOCALIZED_CLASS_NAMES_MALE.DEMONHUNTER,
	["Evoker"] = LOCALIZED_CLASS_NAMES_MALE.EVOKER,

    -- Female Class Names --
    ["DruidF"] = LOCALIZED_CLASS_NAMES_FEMALE.DRUID,
    ["HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.HUNTER,
    ["MageF"] = LOCALIZED_CLASS_NAMES_FEMALE.MAGE,
    ["PaladinF"] = LOCALIZED_CLASS_NAMES_FEMALE.PALADIN,
    ["PriestF"] = LOCALIZED_CLASS_NAMES_FEMALE.PRIEST,
    ["RogueF"] = LOCALIZED_CLASS_NAMES_FEMALE.ROGUE,
    ["ShamanF"] = LOCALIZED_CLASS_NAMES_FEMALE.SHAMAN,
    ["WarlockF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARLOCK,
    ["WarriorF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARRIOR,
    ["Death KnightF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEATHKNIGHT,
    ["MonkF"] = LOCALIZED_CLASS_NAMES_FEMALE.MONK,
    ["Demon HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEMONHUNTER,
	["EvokerF"] = LOCALIZED_CLASS_NAMES_FEMALE.EVOKER,

    ["Game Master"] = "Master di gioco",

    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "Attiva/disattiva WIM",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "Attiva/disattiva la modalità di debug",

    -- Filters.lua --
    ["Whispers Sent by Addons"] = "Sussurri inviati dagli addon",
    ["WhisperSelect Part 1"] = "WhisperSelect parte 1",
    ["Example Spam Blocker"] = "Blocco spam di esempio",
    ["WhisperSelect Part 2"] = "WhisperSelect parte 2",
    ["Filter Name"] = "Nome filtro",
    ["Filter By"] = "Filtra per",
    ["Pattern"] = "Modello",
    ["User Type"] = "Tipo di utente",
    ["Level"] = "Livello",
    ["Friends"] = "Amici",
    ["Guild Members"] = "Membri della gilda",
    ["Party Members"] = "Membri del gruppo",
    ["Raid Members"] = "Membri del raid",
    ["Cross-Realm"] = "Cross-realm",
    ["Everyone"] = "Tutti",
    ["User must be at least level:"] = "L'utente deve essere almeno di livello:",
    ["Apply to messages received."] = "Applica ai messaggi ricevuti.",
    ["Apply to messages sent."] = "Applica ai messaggi inviati.",
    ["Apply to:"] = "Applica a:",
    ["All Classes"] = "Tutte le classi",
    ["Action to Perform:"] = "Azione da eseguire:",
    ["Allow"] = "Consenti",
    ["Ignore"] = "Ignora",
    ["Blocked"] = "Bloccato",
    ["Save"] = "Salva",
    ["Cancel"] = "Annulla",
    ["Edit Filter"] = "Modifica filtro",
    ["Add Filter"] = "Aggiungi filtro",

    -- History.lua --
    ["WIM History Button"] = "Pulsante cronologia WIM",
    ["Click to view message history."] = "Clicca per visualizzare la cronologia dei messaggi.",
    ["WIM pruned %d |4message:messages; from your history."] = "WIM ha eliminato %d |4messaggio:messaggi; dalla tua cronologia.",
    ["History Viewer"] = "Visualizzatore cronologia",
    ["Filters"] = "Filtri",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "Vuoi davvero eliminare tutta la cronologia salvata per %s su %s?",
    ["Search resulted in %d |4message:messages;."] = "La ricerca ha trovato %d |4messaggio:messaggi;.",
    ["No results found!"] = "Nessun risultato trovato!",
    ["Search"] = "Cerca",
    ["Show All"] = "Mostra tutto",
    ["Loading History"] = "Caricamento cronologia",
    ["Chat View"] = "Vista chat",
    ["Text View"] = "Vista testo",
    ["BBCode"] = "BBCode",
    ["WIM History Viewer can be accessed any time by typing:"] = "Il visualizzatore cronologia WIM è accessibile in qualsiasi momento digitando:",
    ["WIM History Viewer"] = "Visualizzatore cronologia WIM",
    ["Display history viewer."] = "Mostra il visualizzatore cronologia.",

    -- ldb.lua --
    ["No New Messages"] = "Nessun nuovo messaggio",

    -- Menu.lua --
    ["Whispers"] = "Sussurri",
    ["Chat"] = "Chat",

    -- Negotiate.lua --
    ["WIM Update Available!"] = "Aggiornamento WIM disponibile!",

    -- ShortcutBar.lua --
    ["Player Location"] = "Posizione del giocatore",
    ["Unknown"] = "Sconosciuto",
    ["Click to update..."] = "Clicca per aggiornare...",
    ["Invite to Party"] = "Invita nel gruppo",
    ["Invite to Guild"] = "Invita nella gilda",
    ["Add Friend"] = "Aggiungi amico",
    ["Ignore Player"] = "Ignora utente",
    ["Are you sure you want to\nignore %s?"] = "Vuoi davvero\nignorare %s?",
    ["Right-Click for profile links..."] = "Tasto destro per i collegamenti al profilo...",
    ["Profile Links"] = "Collegamenti profilo",
	["Location"] = "Posizione",
	["Game"] = "Gioco",
	["Realm"] = "Reame",
	["Character"] = "Personaggio",
	["Copy Name"] = "Copia nome",

    -- Tutorials.lua --
    ["View Updates"] = "Visualizza aggiornamenti",

    -- WhisperEngine.lua --
    ["Whisper Received!"] = "Sussurro ricevuto!",
    ["Recently Sent Messages"] = "Messaggi inviati di recente",
    ["Users in %s"] = "Utenti in %s",

    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "Stai per cancellare tutta la cronologia di WIM!",
    ["This action will reload your user interface."] = "Questa azione ricaricherà la tua interfaccia utente.",
    ["Do you want to continue?"] = "Vuoi continuare?",
    ["You are about to restore WIM's filters to it's default settings!"] = "Stai per ripristinare i filtri di WIM alle impostazioni predefinite!",
    ["Usage"] = "Utilizzo",
    ["Clear various WIM data."] = "Cancella vari dati di WIM.",

    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "Comandi slash di WIM",
    ["Hide or show {all, whisper, chat} windows."] = "Nascondi o mostra le finestre {tutte, sussurri, chat}.",
    ["To see a list of available WIM slash commands type:"] = "Per vedere un elenco dei comandi slash WIM disponibili, digita:",
    ["Display available slash commands."] = "Mostra i comandi slash disponibili.",
    ["Reload User Interface."] = "Ricarica l'interfaccia utente.",

    -- TabHandler.lua --
    ["Manipulating Tabs"] = "Gestione delle schede",

    -- WindowHandler.lua --
    ["Window Resized!"] = "Finestra ridimensionata!",
	["Creating Tab Groups"] = "Creazione di gruppi di schede",
	["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "Puoi raggruppare due o più finestre <Maiusc-cliccando> su una finestra e trascinandola sopra un'altra.",
	["Resizing Windows"] = "Ridimensionamento delle finestre",
	["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "Puoi ridimensionare una finestra tenendo premuto <Maiusc> e trascinando l'angolo in basso a destra della finestra.",
	["Demo Window"] = "Finestra dimostrativa",
	["<Shift-Click> to close window."] = "<Maiusc-clic> per chiudere la finestra.",
	["Message Window Hidden"] = "Finestra messaggi nascosta",
	["Default"] = "Predefinito",
	["%s is Away From Keyboard: %s"] = "%s è assente (AFK): %s",
	["%s does not wish to be disturbed: %s"] = "%s non vuole essere disturbato: %s",
	["Right-Mouse Click!"] = "Clic con il tasto destro!",
	["There might be useful tools hidden under the message box. Right-Click to see them!"] = "Potrebbero esserci strumenti utili nascosti sotto la casella dei messaggi. Fai clic con il tasto destro per vederli!",

    -- Options.lua --
    ["Display WIM's options."] = "Mostra le opzioni di WIM.",
    ["Resetting WIM will clear all of your settings!"] = "Il ripristino di WIM cancellerà tutte le tue impostazioni!",
    ["A reset will reload your user interface."] = "Un ripristino ricaricherà la tua interfaccia utente.",
    ["Reset all options to default."] = "Ripristina tutte le opzioni ai valori predefiniti.",

    -- CoreOptions --
    ["Created By:"] = "Creato da:",
    ["Special Thanks:"] = "Ringraziamenti speciali:",
    ["Welcome!"] = "Benvenuto!",
    ["Enable WIM"] = "Abilita WIM",
    ["Display Minimap Icon"] = "Mostra l'icona sulla minimappa",
    ["<Right-Click> to show unread messages."] = "<Tasto destro> per mostrare i messaggi non letti.",
	["Display Addon Compartment Icon"] = "Mostra l'icona nel compartimento addon",
    ["Display Tutorials"] = "Mostra i tutorial",
    ["Reset Tutorials"] = "Ripristina i tutorial",
    ["Credits"] = "Crediti",
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "Questo è un messaggio lungo che contiene sia emoticon che URL 8). La home di WIM è www.WIMAddon.com.",
    ["Message Formatting"] = "Formattazione dei messaggi",
    ["Manipulate how WIM displays messages."] = "Gestisci come WIM visualizza i messaggi.",
    ["Preview"] = "Anteprima",
    ["Display Time Stamps"] = "Mostra i timestamp",
    ["Display Emoticons"] = "Mostra le emoticon",
    ["Display URLs as Links"] = "Mostra gli URL come collegamenti",
    ["Indent long messages."] = "Rientra i messaggi lunghi.",
	["Bracket names."] = "Racchiudi i nomi tra parentesi.",
    ["Window Behavior"] = "Comportamento delle finestre",
    ["You can control how windows behave while you are in different situations."] = "Puoi controllare come si comportano le finestre in diverse situazioni.",
    ["Intercept Slash Commands"] = "Intercetta i comandi slash",
    ["Include sent messages in /REPLY."] = "Includi i messaggi inviati in /REPLY.",
	["Obey autofocus rules when opening frames via the menu. (autofocus if unchecked)"] = "Rispetta le regole di messa a fuoco automatica quando si aprono le finestre tramite il menu. (autofocus se non selezionato)",
    ["Use the same rules for all states."] = "Usa le stesse regole per tutti gli stati.",
    ["Behaviors for state:"] = "Comportamenti per lo stato:",
    ["Pop-Up window when message is sent."] = "Finestra popup quando il messaggio viene inviato.",
    ["Pop-Up window when message is received."] = "Finestra popup quando il messaggio viene ricevuto.",
    ["Auto focus a window when it is shown."] = "Messa a fuoco automatica sulla finestra quando viene mostrata.",
    ["Keep focus on window after sending a message."] = "Mantieni la messa a fuoco sulla finestra dopo l'invio di un messaggio.",
    ["Suppress messages from the default chat frame."] = "Sopprimi i messaggi dalla finestra chat predefinita.",
    ["Window Settings"] = "Impostazioni finestra",
    ["Some settings may be limited by certain skins."] = "Alcune impostazioni possono essere limitate da certi skin.",
    ["Default Width"] = "Larghezza predefinita",
    ["Default Height"] = "Altezza predefinita",
    ["Window Scale"] = "Scala finestra",
    ["Window Alpha"] = "Alpha finestra",
    ["Set Window Spawn Location"] = "Imposta la posizione di comparsa delle finestre",
    ["Up"] = "Su",
    ["Down"] = "Giù",
    ["Left"] = "Sinistra",
    ["Right"] = "Destra",
    ["Cascade overlapping windows."] = "Finestre sovrapposte a cascata.",
    ["Ignore arrow keys in message box."] = "Ignora i tasti freccia nella casella messaggi.",
    ["Allow <ESC> to hide windows."] = "Consenti a <ESC> di nascondere le finestre.",
    ["Display Settings"] = "Impostazioni di visualizzazione",
    ["Configure general window display settings."] = "Configura le impostazioni generali di visualizzazione delle finestre.",
    ["Window Skin:"] = "Skin finestra:",
    ["Version"] = "Versione",
    ["Color: System Messages"] = "Colore: messaggi di sistema",
    ["Color: Error Messages"] = "Colore: messaggi di errore",
    ["Color: URL - Web Addresses"] = "Colore: URL - indirizzi web",
    ["Color: History Messages Sent"] = "Colore: messaggi cronologia inviati",
    ["Color: History Messages Received"] = "Colore: messaggi cronologia ricevuti",
    ["Use colors suggested by skin."] = "Usa i colori suggeriti dallo skin.",
    ["Enable window fading effects."] = "Abilita gli effetti di dissolvenza delle finestre.",
    ["Enable window animation effects."] = "Abilita gli effetti di animazione delle finestre.",
    ["Display item links when hovering over them."] = "Mostra i collegamenti agli oggetti quando ci passi sopra con il mouse.",
    ["Fonts"] = "Caratteri",
    ["Configure the fonts used in WIM's message windows."] = "Configura i caratteri usati nelle finestre dei messaggi di WIM.",
    ["Font Outline"] = "Contorno del carattere",
    ["Thin"] = "Sottile",
    ["Thick"] = "Spesso",
    ["Use font suggested by skin."] = "Usa il carattere suggerito dallo skin.",
    ["Chat Font Size"] = "Dimensione carattere chat",
    ["Configure general display settings when dealing with whispers."] = "Configura le impostazioni di visualizzazione generali per i sussurri.",
    ["Color: Messages Sent"] = "Colore: messaggi inviati",
    ["Color: Messages Received"] = "Colore: messaggi ricevuti",
	["Color: BNet Messages Sent"] = "Colore: messaggi BNet inviati",
	["Color: BNet Messages Received"] = "Colore: messaggi BNet ricevuti",
    ["Use colors suggested by skin."] = "Usa i colori suggeriti dallo skin.",
    ["Display user class icons and details."] = "Mostra le icone e i dettagli della classe dell'utente.",
    ["Requires who lookups."] = "Richiede le ricerche who.",
    ["Display Shortcut Bar"] = "Mostra la barra dei comandi rapidi",
    ["Allow"] = "Consenti",
    ["Ignore"] = "Ignora",
    ["Block"] = "Blocca",
    ["Filtering"] = "Filtraggio",
    ["Filtering allows you to control which messages are handled as well as how they are handled by WIM."] = "Il filtraggio ti permette di controllare quali messaggi vengono gestiti e come vengono gestiti da WIM.",
    ["Enable Filtering"] = "Abilita il filtraggio",
    ["Protected"] = "Protetto",
    ["Action:"] = "Azione:",
    ["Occurrences:"] = "Occorrenze:",
    ["Delete Filter"] = "Elimina filtro",
    ["History"] = "Cronologia",
    ["WIM can store conversations to be viewed at a later time."] = "WIM può salvare le conversazioni per poterle rivedere in seguito.",
    ["Enable History"] = "Abilita cronologia",
    ["Messages"] = "Messaggi",
    ["Preview history inside message windows."] = "Anteprima della cronologia nelle finestre dei messaggi.",
    ["Record Friends"] = "Registra gli amici",
    ["Record Guild"] = "Registra la gilda",
    ["Record Everyone"] = "Registra tutti",
    ["Record Chat"] = "Registra la chat",
    ["Maintenance"] = "Manutenzione",
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "Lasciare che i registri della cronologia diventino troppo grandi influirà sulle prestazioni del gioco, quindi si consiglia di utilizzare le seguenti opzioni.",
    ["Save a maximum number of messages per person."] = "Salva un numero massimo di messaggi per persona.",
    ["%d |4Week:Weeks;"] = "%d |4settimana:settimane;",
    ["Automatically delete old messages."] = "Elimina automaticamente i vecchi messaggi.",
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM è una funzionalità che consente agli utenti con WIM di interagire in modi che il normale sussurrare non può.",
    ["Enable WIM-2-WIM"] = "Abilita WIM-2-WIM",
    ["Privacy"] = "Privacy",
    ["Restrict the data that is shared."] = "Limita i dati condivisi.",
    ["Allow others to see me typing."] = "Consenti agli altri di vedermi mentre scrivo.",
    ["Allow others to see my location."] = "Consenti agli altri di vedere la mia posizione.",
    ["Main"] = "Principale",
    ["General"] = "Generale",
    ["User Level"] = "Livello utente",
    ["Windows will also be hidden when frames such as the world map are shown."] = "Le finestre verranno nascoste anche quando vengono mostrate cornici come la mappa del mondo.",
    ["Sounds"] = "Suoni",
    ["Configure various sound events and how they are triggered."] = "Configura i vari eventi sonori e come vengono attivati.",
    ["Play sound when a whisper is received."] = "Riproduci un suono quando viene ricevuto un sussurro.",
    ["Play special sound for friends."] = "Riproduci un suono speciale per gli amici.",
	["Play special sound for battle.net friends."] = "Riproduci un suono speciale per gli amici battle.net.",
    ["Play special sound for guild members."] = "Riproduci un suono speciale per i membri della gilda.",
    ["Play sound when a whisper is sent."] = "Riproduci un suono quando viene inviato un sussurro.",
    ["Allow others to see my talent spec."] = "Consenti agli altri di vedere la mia specializzazione.",
    ["Window Strata:"] = "Strato finestra:",
	["Background"] = BACKGROUND,
	["Low"] = LOW,
	["Medium"] = "Medio",
	["High"] = "Alto",
	["Dialog"] = ENABLE_DIALOG,
	["Tooltip"] = "Tooltip",
    ["Unlock from Minimap"] = "Sblocca dalla minimappa",
	["Press <Tab> to advance to next tell target."] = "Premi <Tab> per passare al prossimo destinatario del messaggio.",
    ["Force sounds when game sound is disabled."] = "Forza i suoni quando il suono del gioco è disabilitato.",
    ["Colorize names."] = "Colora i nomi.",
    ["Clamp window to screen."] = "Fissa la finestra allo schermo.",
    ["Group with whisper windows."] = "Raggruppa con le finestre dei sussurri.",

    -- TabManagement.lua --
    ["Tab Management"] = "Gestione schede",
    ["Automatically manage your open windows and place them into appropriate tab groups."] = "Gestisci automaticamente le finestre aperte e inseriscile in gruppi di schede appropriati.",
    ["Automatically group whispers."] = "Raggruppa automaticamente i sussurri.",
	["Automatically group chat windows."] = "Raggruppa automaticamente le finestre della chat.",
    ["Place friends in their own group."] = "Metti gli amici in un gruppo separato.",
    ["Place guild members in their own group."] = "Metti i membri della gilda in un gruppo separato.",
    ["Does not apply to windows already opened."] = "Non si applica alle finestre già aperte.",

    -- Talent Specs --
    ["Hybrid"] = "Ibrido",

    -- Filters.lua --
    ["Show Alert"] = "Mostra avviso",
    ["WIM has blocked a message from %s."] = "WIM ha bloccato un messaggio da %s.",
    ["View Blocked Message"] = "Visualizza messaggio bloccato",
    ["Blocked Message"] = "Messaggio bloccato",

    -- MinimapIcon.lua
    ["Show Unread Messages"] = "Mostra messaggi non letti",
    ["Show All Windows"] = "Mostra tutte le finestre",
    ["Hide All Windows"] = "Nascondi tutte le finestre",

    --Emoticons.lua
    ["Also"] = "Anche",
    ["More"] = "Altro",
    ["Emoticons"] = "Emoticon",

    --Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = "Le tue conversazioni sono state nascoste per liberare lo schermo durante il combattimento. Per disabilitare questa funzione digita",
    ["Expose"] = "Expose",
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = "Expose è una funzionalità ispirata a Mac OS X che ti consente di liberare rapidamente lo schermo dalle finestre e poi ripristinarle nella loro posizione originale.",
    ["Auto hide/restore windows during combat."] = "Nascondi/ripristina automaticamente le finestre durante il combattimento.",
	["Delay if I am typing a message."] = "Ritarda se sto scrivendo un messaggio.",
    ["Border Size"] = "Dimensione bordo",
    ["Only while in an instance."] = "Solo in un'istanza.",
    ["Show Border"] = "Mostra bordo",
    ["Animation Direction:"] = "Direzione animazione:",

    --ChatEngine.lua
    ["WIM will manage this chat type within its own message windows."] = "WIM gestirà questo tipo di chat nelle proprie finestre dei messaggi.",
    ["Show Minimap Alerts"] = "Mostra avvisi sulla minimappa",
    ["Never pop-up on my screen."] = "Non far mai comparire popup sul mio schermo.",
    ["Never suppress messages."] = "Non sopprimere mai i messaggi.",
	["Include emotes."] = "Includi le emote.",
    ["Have WIM monitor this channel."] = "Fai monitorare a WIM questo canale.",
    ["Never Pop"] = "Mai popup",
    ["Never have this window pop-up on my screen."] = "Non far mai comparire questa finestra sul mio schermo.",
    ["Never Suppress"] = "Non sopprimere mai",
    ["Never suppress messages from the default chat frame."] = "Non sopprimere mai i messaggi dalla finestra chat predefinita.",
    ["Show unread message alert on minimap."] = "Mostra un avviso di messaggi non letti sulla minimappa.",
    ["No History"] = "Nessuna cronologia",
    ["Do not record history for this channel."] = "Non registrare la cronologia per questo canale.",
    ["World Chat"] = "Chat mondiale",
    ["Custom Chat"] = "Chat personalizzata",
    ["Community Chat"] = "Chat della comunità",
    ["Chat"] = "Chat",
    ["Play special sound for %s."] = "Riproduci un suono speciale per %s.",
    ["Play sound when a message is received."] = "Riproduci un suono quando viene ricevuto un messaggio.",
    ["Play sound when a message is sent."] = "Riproduci un suono quando viene inviato un messaggio.",
	["Do not play sounds for this channel."] = "Non riprodurre suoni per questo canale.",
	["No Sound"] = "Nessun suono",
	["Sensitivity"] = "Sensibilità",
	["Enable WorldFrame Click Detection."] = "Abilita il rilevamento dei clic nel WorldFrame.",

	--OffScreenTracker.lua
	["WIM Window Off Screen"] = "Finestra WIM fuori schermo",
	["Click to reposition."] = "Clicca per riposizionare.",

	-- Whisper Mode Warnings
    ["Whisper Mode: In-line"] = "Modalità sussurri: in linea",
	["Set whispers to In-line"] = "Imposta i sussurri su In linea",
	["Message suppression requires whispers to be set to 'In-line'."] = "La soppressione dei messaggi richiede che i sussurri siano impostati su 'In linea'.",
	["It is recommended for whispers to be set to in-line in order to handle their behavior properly."] = "Si consiglia di impostare i sussurri su In linea per gestirne correttamente il comportamento.",

	-- Skins --
	["Blue"] = "Blu",
	["Green"] = "Verde",
	["Red"] = "Rosso",
	["Yellow"] = "Giallo",
});
