--[[
    Language Localization: koKR
    Translated by: BlueNyx <bluenyx@gmail.com>
]]

WIM.AddLocale("koKR", {
    ["WIM (WoW Instant Messenger)"] = "WIM (와우 메신저)",
    ["_Description"] = "WIM은 월드 오브 워크래프트에서 채팅을 통한 대화를 보다 익숙한 방식으로 사용할 수 있도록 도와주는 애드온입니다. 이 화면에서는 WIM을 필요에 맞게 설정할 수 있습니다.",

    ["_DemoText"] = "이 창은 데모 창이며 완전한 기능을 제공하지 않습니다. 다른 모든 창이 생성될 위치에 이 창을 배치하세요. 완료되면 이 창을 닫으면 설정이 저장됩니다.",

    ["_DateFormat"] = "%Y/%m/%d",

    ["Yes"] = "예",
    ["No"] = "아니오",
    ["None"] = "없음",
    ["Cancel"] = "취소",
    ["Unknown"] = "알 수 없음",
    ["Click to update..."] = "클릭 - 위치 정보 갱신",
    ["Usage"] = "사용",

    ["state_resting"] = "대도시",
    ["state_combat"] = "전투중",
    ["state_pvp"] = "전장",
    ["state_arena"] = "투기장",
    ["state_party"] = "파티",
    ["state_raid"] = "레이드",
    ["state_other"] = "일반 (기타)",

    ["Options"] = "옵션",

    ["Up"] = "위",
    ["Down"] = "아래",
    ["Left"] = "왼쪽",
    ["Right"] = "오른쪽",
    ["Ignore"] = "무시",
    ["Block"] = "차단",
    ["Enable WIM"] = "WIM 사용",

    ["Enable"] = "켜기",
    ["Disable"] = "끄기",
    ["Enable window fading effects."] = "창 투명화 효과 기능",

    ["General"] = "일반",
    ["History"] = "대화기록",
    ["Filters"] = "필터",

    ["Sort tabs by:"] = "탭 정렬 방식 :",
	["Window Created"] = "창 생성됨",
	["Last Activity"] = "마지막 활동",
    ["Alphabetical"] = "가나다순",

    -- Class Names --
    ["Druid"] = LOCALIZED_CLASS_NAMES_MALE.DRUID,
    ["Hunter"] = LOCALIZED_CLASS_NAMES_MALE.HUNTER,
    ["Mage"] = LOCALIZED_CLASS_NAMES_MALE.MAGE,
    ["Paladin"] = LOCALIZED_CLASS_NAMES_MALE.PALADIN,
    ["Priest"] = LOCALIZED_CLASS_NAMES_MALE.PRIEST,
    ["Rogue"] = LOCALIZED_CLASS_NAMES_MALE.ROGUE,
    ["Shaman"] = LOCALIZED_CLASS_NAMES_MALE.SHAMAN,
    ["Warlock"] = LOCALIZED_CLASS_NAMES_MALE.WARLOCK,
    ["Warrior"] = LOCALIZED_CLASS_NAMES_MALE.WARRIOR,
    ["Death Knight"] = LOCALIZED_CLASS_NAMES_MALE.DEATHKNIGHT,
    ["Monk"] = LOCALIZED_CLASS_NAMES_MALE.MONK,
    ["Demon Hunter"] = LOCALIZED_CLASS_NAMES_MALE.DEMONHUNTER,
	["Evoker"] = LOCALIZED_CLASS_NAMES_MALE.EVOKER,

    -- Female Class Names --
    ["DruidF"] = LOCALIZED_CLASS_NAMES_FEMALE.DRUID,
    ["HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.HUNTER,
    ["MageF"] = LOCALIZED_CLASS_NAMES_FEMALE.MAGE,
    ["PaladinF"] = LOCALIZED_CLASS_NAMES_FEMALE.PALADIN,
    ["PriestF"] = LOCALIZED_CLASS_NAMES_FEMALE.PRIEST,
    ["RogueF"] = LOCALIZED_CLASS_NAMES_FEMALE.ROGUE,
    ["ShamanF"] = LOCALIZED_CLASS_NAMES_FEMALE.SHAMAN,
    ["WarlockF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARLOCK,
    ["WarriorF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARRIOR,
    ["Death KnightF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEATHKNIGHT,
    ["MonkF"] = LOCALIZED_CLASS_NAMES_FEMALE.MONK,
    ["Demon HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEMONHUNTER,
	["EvokerF"] = LOCALIZED_CLASS_NAMES_FEMALE.EVOKER,

    ["Game Master"] = "GM",

    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "WIM을 켜고 끕니다",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "WIM 디버그모드를 켜고 끕니다",

    -- Filters.lua --
    ["Whispers Sent by Addons"] = "애드온을 통해 귓속말",
    ["WhisperSelect Part 1"] = "귓속말 대상자 선택 파트 1",
    ["Example Spam Blocker"] = "스팸 차단 예제",
    ["WhisperSelect Part 2"] = "귓속말 대상자 선택 파트 2",
    ["Filter Name"] = "조건 이름",
    ["Filter By"] = "조건 만든이",
    ["Pattern"] = "패턴(반복적 형식)",
    ["User Type"] = "유저 타입",
    ["Level"] = "레벨",
    ["Friends"] = "친구",
    ["Guild Members"] = "길드 멤버",
    ["Party Members"] = "파티 멤버",
    ["Raid Members"] = "공대 멤버",
    ["Cross-Realm"] = "다른 서버",
    ["Everyone"] = "모두",
    ["User must be at least level:"] = "유저의 최소 레벨",
    ["Apply to messages received."] = "메세지 받기 허용",
    ["Apply to messages sent."] = "메세지 보내기 허용",
    ["Apply to:"] = "적용 대상:",
    ["All Classes"] = "전체 클래스",
    ["Action to Perform:"] = "실행할 동작:",
    ["Allow"] = "허용",
    ["Ignore"] = "무시",
    ["Blocked"] = "차단",
    ["Save"] = "저장",
    ["Cancel"] = "취소",
    ["Edit Filter"] = "조건 수정",
    ["Add Filter"] = "조건 추가",

    -- History.lua --
    ["WIM History Button"] = "WIM 대화기록 버튼",
    ["Click to view message history."] = "클릭하면 대화기록을 볼 수 있습니다.",
    ["WIM pruned %d |4message:messages; from your history."] = "WIM이 대화 기록에서 메시지 %d개를 정리했습니다.",
    ["History Viewer"] = "기록 보기",
    ["Filters"] = "필터",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "%s의 %s에 저장된 모든 기록을 삭제하시겠습니까?",
    ["Search resulted in %d |4message:messages;."] = "검색 결과 메시지 %d개가 발견되었습니다.",
    ["No results found!"] = "검색 결과가 없습니다.",
    ["Search"] = "검색",
    ["Show All"] = "전체 보기",
    ["Loading History"] = "기록 불러오는 중",
    ["Chat View"] = "대화 보기",
    ["Text View"] = "텍스트 보기",
    ["BBCode"] = "BBCode",
    ["WIM History Viewer can be accessed any time by typing:"] = "다음 명령어를 입력하면 언제든지 WIM 기록 보기를 열 수 있습니다:",
    ["WIM History Viewer"] = "WIM 기록 보기",
    ["Display history viewer."] = "기록 보기를 표시합니다",

    -- ldb.lua --
    ["No New Messages"] = "새로운 메세지가 없습니다",

    -- Menu.lua --
    ["Whispers"] = "귓속말",
    ["Chat"] = "대화",

    -- Negotiate.lua --
    ["WIM Update Available!"] = "WIM 업데이트가 있습니다",

    -- ShortcutBar.lua --
    ["Player Location"] = "현재 위치",
    ["Unknown"] = "알 수 없음",
    ["Click to update..."] = "클릭 - 위치 정보 갱신",
    ["Invite to Party"] = "파티 초대",
    ["Invite to Guild"] = "길드 초대",
    ["Add Friend"] = "친구 추가",
    ["Ignore Player"] = "플레이어 차단",
    ["Are you sure you want to\nignore %s?"] = "%s을(를) 차단하시겠습니까?",
    ["Right-Click for profile links..."] = "우클릭하여 프로필 링크 보기...",
    ["Profile Links"] = "프로필 링크",
    ["Location"] = "위치",
    ["Game"] = "게임",
    ["Realm"] = "서버",
    ["Character"] = "캐릭터",
	["Copy Name"] = "이름 복사",

    -- Tutorials.lua --
    ["View Updates"] = "업데이트 보기",

    -- WhisperEngine.lua --
    ["Whisper Received!"] = "귓속말 받기",
    ["Recently Sent Messages"] = "최근 보낸 메시지",
    ["Users in %s"] = "%s 내 사용자",

    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "WIM의 모든 대화 기록을 삭제합니다!",
    ["This action will reload your user interface."] = "이 작업은 사용자 인터페이스(UI)를 재시작합니다.",
    ["Do you want to continue?"] = "계속 하시겠습니까?",
    ["You are about to restore WIM's filters to it's default settings!"] = "WIM의 필터 설정을 기본값으로 복원하려고 합니다!",
    ["Usage"] = "사용법",
    ["Clear various WIM data."] = "WIM 데이터를 삭제합니다",

    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "WIM /명령어",
    ["Hide or show {all, whisper, chat} windows."] = "{전체, 귓속말, 채팅} 창 숨기기 또는 보이기.",
    ["To see a list of available WIM slash commands type:"] = "사용 가능한 WIM 슬래시 명령어 목록을 보려면 다음을 입력하세요:",
    ["Display available slash commands."] = "사용 가능한 명령어를 표시합니다",
    ["Reload User Interface."] = "유저 인터페이스 재시작",

    -- TabHandler.lua --
    ["Manipulating Tabs"] = "탭 조작",

    -- WindowHandler.lua --
    ["Window Resized!"] = "창 크기가 변경되었습니다!",
    ["Creating Tab Groups"] = "탭 그룹 만들기",
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "Shift 클릭으로 창을 선택한 뒤 다른 창 위로 끌어다 놓으면 여러 창을 하나의 탭 그룹으로 묶을 수 있습니다.",
    ["Resizing Windows"] = "창 크기 조절",
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "<Shift> 키를 누른 상태에서 창의 오른쪽 아래 모서리를 끌어 크기를 조절할 수 있습니다.",
    ["Demo Window"] = "데모 창",
	["<Shift-Click> to close window."] = "Shift 클릭으로 창 닫기",
    ["Message Window Hidden"] = "메시지 창 숨김",
    ["Default"] = "기본값",
    ["%s is Away From Keyboard: %s"] = "%s님이 자리 비움 상태입니다: %s",
    ["%s does not wish to be disturbed: %s"] = "%s님은 현재 방해받고 싶지 않습니다: %s",
    ["Right-Mouse Click!"] = "오른쪽 버튼 클릭!",
    ["There might be useful tools hidden under the message box. Right-Click to see them!"] = "메시지 창 아래에 유용한 도구가 숨겨져 있을 수 있습니다. 오른쪽 클릭으로 확인하세요!",

    -- Options.lua --
    ["Display WIM's options."] = "WIM 옵션을 표시합니다.",
    ["Resetting WIM will clear all of your settings!"] = "WIM을 초기화하면 모든 설정이 삭제됩니다!",
    ["A reset will reload your user interface."] = "초기화하면 사용자 인터페이스가 다시 로드됩니다.",
    ["Reset all options to default."] = "모든 옵션을 기본값으로 초기화합니다.",

    -- CoreOptions --
    ["Created By:"] = "제작자:",
    ["Special Thanks:"] = "특별 감사:",
    ["Welcome!"] = "환영합니다!",
    ["Enable WIM"] = "WIM 사용",
    ["Display Minimap Icon"] = "미니맵 아이콘 표시",
    ["<Right-Click> to show unread messages."] = "오른쪽 클릭으로 읽지 않은 메시지를 표시합니다",
	["Display Addon Compartment Icon"] = "애드온 구획 아이콘 표시",
    ["Display Tutorials"] = "튜토리얼 표시",
    ["Reset Tutorials"] = "튜토리얼 초기화",
    ["Credits"] = "제작자 명단",
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "이것은 이모티콘과 URL이 모두 포함된 긴 메시지입니다 8). WIM의 홈페이지는 www.WIMAddon.com입니다.",
    ["Message Formatting"] = "메시지 형식",
    ["Manipulate how WIM displays messages."] = "WIM의 메시지 표시 방식을 설정합니다.",
    ["Preview"] = "미리보기",
    ["Display Time Stamps"] = "메시지 시간 표시",
    ["Display Emoticons"] = "이모티콘 표시",
    ["Display URLs as Links"] = "URL을 링크로 표시",
    ["Indent long messages."] = "긴 메시지를 자동으로 들여쓰기합니다",
    ["Bracket names."] = "이름을 대괄호로 표시합니다",
    ["Window Behavior"] = "창 동작",
    ["You can control how windows behave while you are in different situations."] = "상황에 따라 창이 어떻게 동작할지 설정할 수 있습니다.",
    ["Intercept Slash Commands"] = "/명령어 가로채기",
    ["Include sent messages in /REPLY."] = "보낸 메시지를 /r에 포함합니다",
    ["Obey autofocus rules when opening frames via the menu. (autofocus if unchecked)"] = "메뉴를 통해 창을 열 때 자동 포커스 규칙을 따릅니다",
    ["Use the same rules for all states."] = "모든 상황에서 동일한 규칙을 사용합니다",
    ["Behaviors for state:"] = "상태에 따른 동작:",
    ["Pop-Up window when message is sent."] = "메시지 전송 시 창을 팝업합니다",
    ["Pop-Up window when message is received."] = "메시지 수신 시 창을 팝업합니다",
    ["Auto focus a window when it is shown."] = "창이 표시되면 자동으로 포커스를 이동합니다",
    ["Keep focus on window after sending a message."] = "메시지를 보낸 후에도 창에 포커스를 유지합니다",
    ["Suppress messages from the default chat frame."] = "기본 채팅 창에서 메시지를 숨깁니다",
    ["Window Settings"] = "창 설정",
    ["Some settings may be limited by certain skins."] = "일부 설정은 특정 스킨에 의해 제한될 수 있습니다.",
    ["Default Width"] = "기본 너비",
    ["Default Height"] = "기본 높이",
    ["Window Scale"] = "창 크기 비율",
    ["Window Alpha"] = "창 투명도",
    ["Set Window Spawn Location"] = "창 생성 위치 설정",
    ["Up"] = "위",
    ["Down"] = "아래",
    ["Left"] = "왼쪽",
    ["Right"] = "오른쪽",
    ["Cascade overlapping windows."] = "겹쳐진 창을 계단식으로 배열합니다",
    ["Ignore arrow keys in message box."] = "메시지 입력창에서 방향키를 무시합니다",
    ["Allow <ESC> to hide windows."] = "<ESC> 키로 창을 숨길 수 있게 합니다",
    ["Display Settings"] = "표시 설정",
    ["Configure general window display settings."] = "일반적인 창 표시 설정을 구성합니다.",
    ["Window Skin:"] = "창 스킨:",
    ["Version"] = "버전",
    ["Color: System Messages"] = "색상: 시스템 메시지",
    ["Color: Error Messages"] = "색상: 오류 메시지",
    ["Color: URL - Web Addresses"] = "색상: URL - 웹 주소",
    ["Color: History Messages Sent"] = "색상: 이전에 보낸 메시지",
    ["Color: History Messages Received"] = "색상: 이전에 받은 메시지",
    ["Use colors suggested by skin."] = "스킨에서 제공하는 색상을 사용합니다",
    ["Enable window fading effects."] = "창 페이드 효과를 활성화합니다",
    ["Enable window animation effects."] = "창 애니메이션 효과를 활성화합니다",
    ["Display item links when hovering over them."] = "아이템 링크 위에 마우스를 올리면 링크 정보를 표시합니다",
    ["Fonts"] = "글꼴",
    ["Configure the fonts used in WIM's message windows."] = "WIM 메시지 창에서 사용할 글꼴을 설정합니다.",
    ["Font Outline"] = "글꼴 외곽선",
    ["Thin"] = "얇게",
    ["Thick"] = "굵게",
    ["Use font suggested by skin."] = "스킨에서 제안한 글꼴을 사용합니다",
    ["Chat Font Size"] = "채팅 글꼴 크기",
    ["Configure general display settings when dealing with whispers."] = "귓속말 표시와 관련된 일반 설정을 구성합니다.",
    ["Color: Messages Sent"] = "색상: 보낸 메시지",
    ["Color: Messages Received"] = "색상: 받은 메시지",
    ["Use colors suggested by skin."] = "스킨에서 제안한 색상을 사용합니다",
    ["Display user class icons and details."] = "플레이어 직업 아이콘 및 정보를 표시합니다",
    ["Requires who lookups."] = "who 조회가 필요합니다.",
    ["Display Shortcut Bar"] = "단축 바 표시",
    ["Allow"] = "허용",
    ["Ignore"] = "무시",
    ["Block"] = "차단",
    ["Filtering"] = "필터링",
    ["Filtering allows you to control which messages are handled as well as how they are handled by WIM."] = "필터링을 통해 어떤 메시지를 어떻게 처리할지 WIM에서 제어할 수 있습니다.",
    ["Enable Filtering"] = "필터링 사용",
    ["Protected"] = "보호됨",
    ["Action:"] = "동작:",
    ["Occurrences:"] = "발생 조건:",
    ["Delete Filter"] = "필터 삭제",
    ["History"] = "대화 기록",
    ["WIM can store conversations to be viewed at a later time."] = "WIM은 나중에 다시 볼 수 있도록 대화 내용을 저장할 수 있습니다.",
    ["Enable History"] = "대화 기록 사용",
    ["Messages"] = "메시지",
    ["Preview history inside message windows."] = "메시지 창에서 대화 기록을 미리 봅니다.",
    ["Record Friends"] = "친구 대화 기록",
    ["Record Guild"] = "길드 대화 기록",
    ["Record Everyone"] = "모든 대화 기록",
    ["Record Chat"] = "채팅 기록",
    ["Maintenance"] = "관리하기",
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "대화 기록이 너무 많아지면 게임 성능에 영향을 줄 수 있으므로, 아래 옵션을 사용하는 것을 권장합니다.",
    ["Save a maximum number of messages per person."] = "유저당 최대 저장 메세지 갯수",
    ["%d |4Week:Weeks;"] = "%d 주",
    ["Automatically delete old messages."] = "오래된 메세지를 자동으로 지웁니다",
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM은 기본 귓속말로는 사용할 수 없는 확장 기능을 WIM 사용자끼리 이용할 수 있게 해주는 시스템입니다.",
    ["Enable WIM-2-WIM"] = "WIM 사용자간 대화 켜기",
    ["Privacy"] = "개인 정보 보호",
    ["Restrict the data that is shared."] = "공유되는 데이터를 제한합니다",
    ["Allow others to see me typing."] = "다른 사용자가 내가 입력 중인지 확인할 수 있도록 허용합니다",
    ["Allow others to see my location."] = "다른 사용자가 내 위치를 볼 수 있도록 허용합니다",
    ["Main"] = "메인",
    ["General"] = "일반",
    ["User Level"] = "플레이어 레벨",
    ["Windows will also be hidden when frames such as the world map are shown."] = "세계 지도와 같은 화면 전체 프레임이 열리면 WIM 창도 함께 숨겨집니다.",
    ["Sounds"] = "사운드",
    ["Configure various sound events and how they are triggered."] = "다양한 사운드 이벤트와 동작 방식을 설정합니다.",
    ["Play sound when a whisper is received."] = "귓속말을 받으면 효과음 재생",
    ["Play special sound for friends."] = "친구가 귓속말을 보낼 때 효과음 재생",
    ["Play special sound for battle.net friends."] = "Battle.net 친구에게서 메시지가 올 경우 효과음 재생",
    ["Play special sound for guild members."] = "길드원이 귓속말을 보낼 때 효과음 재생",
    ["Play sound when a whisper is sent."] = "귓속말을 보낼 때 효과음 재생",
    ["Allow others to see my talent spec."] = "다른 사용자가 내 특성을 확인할 수 있도록 허용",
    ["Window Strata:"] = "창 레이어:",
	["Background"] = BACKGROUND,
	["Low"] = LOW,
	["Medium"] = "보통",
	["High"] = "혼잡",
	["Dialog"] = ENABLE_DIALOG,
	["Tooltip"] = "툴팁",
    ["Unlock from Minimap"] = "미니맵에서 위치 잠금 해제",
    ["Press <Tab> to advance to next tell target."] = "<Tab> 키를 눌러 다음 귓속말 대상자로 이동",
    ["Force sounds when game sound is disabled."] = "게임 사운드가 꺼져 있어도 강제 효과음 재생",
    ["Colorize names."] = "이름에 색상 적용",
    ["Clamp window to screen."] = "창이 화면 밖으로 벗어나지 않도록 제한",
    ["Group with whisper windows."] = "귓속말 창과 함께 그룹화",
    ["Color: BNet Messages Sent"] = "Battle.net 메시지를 보냈을 때 표시되는 색상",
    ["Color: BNet Messages Received"] = "Battle.net 메시지를 받았을 때 표시되는 색상",

    -- TabManagement.lua --
    ["Tab Management"] = "탭 관리",
    ["Automatically manage your open windows and place them into appropriate tab groups."] = "열려 있는 창을 자동으로 관리하여 적절한 탭 그룹에 배치합니다.",
    ["Automatically group whispers."] = "귓속말 창을 자동으로 그룹화합니다",
    ["Place friends in their own group."] = "친구는 별도의 그룹에 배치합니다",
    ["Place guild members in their own group."] = "길드원은 별도의 그룹에 배치합니다",
    ["Automatically group chat windows."] = "채팅 창을 자동으로 그룹화합니다",
    ["Does not apply to windows already opened."] = "이미 열린 창에는 적용되지 않습니다",

	-- Talent Specs --
    ["Hybrid"] = "하이브리드",

    -- Filters.lua --
    ["Show Alert"] = "알림 표시",
    ["WIM has blocked a message from %s."] = "%s 로부터 온 메시지가 차단되었습니다.",
    ["View Blocked Message"] = "차단된 메시지 보기",
    ["Blocked Message"] = "차단된 메시지",

    -- MinimapIcon.lua
    ["Show Unread Messages"] = "읽지 않은 메시지 표시",
    ["Show All Windows"] = "모든 창 표시",
    ["Hide All Windows"] = "모든 창 숨기기",

    --Emoticons.lua
    ["Also"] = "기타",
    ["More"] = "더 보기",
    ["Emoticons"] = "이모티콘",

    --Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = "전투 중 화면을 깨끗하게 유지하기 위해 대화창이 숨겨졌습니다. 기능을 끄려면 다음을 입력하세요:",
    ["Expose"] = "Expose",
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = "Expose는 Mac OS X에서 영감을 받은 기능으로, 화면의 창을 빠르게 숨겼다가 원래 위치로 복원할 수 있습니다.",
    ["Auto hide/restore windows during combat."] = "전투 중 자동으로 창 숨김/복원",
    ["Delay if I am typing a message."] = "입력 중일 때는 지연",
    ["Border Size"] = "테두리 크기",
    ["Only while in an instance."] = "인스턴스 내부에서만 적용",
    ["Show Border"] = "테두리 표시",
    ["Animation Direction:"] = "애니메이션 방향:",

    --ChatEngine.lua
    ["WIM will manage this chat type within its own message windows."] = "WIM이 이 채팅 유형을 별도의 대화창에서 처리합니다.",
    ["Show Minimap Alerts"] = "미니맵 알림 표시",
    ["Never pop-up on my screen."] = "화면에 자동으로 창을 띄우지 않기",
    ["Never suppress messages."] = "메시지 숨김 사용 안 함",
    ["Include emotes."] = "감정표현 포함",
    ["Have WIM monitor this channel."] = "이 채널을 WIM이 관리하도록 설정",
    ["Never Pop"] = "팝업 안 함",
    ["Never have this window pop-up on my screen."] = "이 창이 자동으로 뜨지 않기",
    ["Never Suppress"] = "기본 채팅창에서 메시지를 숨기지 않기",
    ["Never suppress messages from the default chat frame."] = "기본 채팅창의 메시지를 숨기지 않기",
    ["Show unread message alert on minimap."] = "읽지 않은 메시지 미니맵 알림",
    ["No History"] = "기록 안 함",
    ["Do not record history for this channel."] = "이 채널의 기록을 저장하지 않기",
    ["World Chat"] = "월드 채팅",
    ["Custom Chat"] = "사용자 채팅",
    ["Community Chat"] = "커뮤니티 채팅",
    ["Chat"] = "채팅",
    ["Play special sound for %s."] = "%s에 대해 소리 재생",
    ["Play sound when a message is received."] = "메시지 수신 시 효과음 재생",
    ["Play sound when a message is sent."] = "메시지 발송 시 효과음 재생",
    ["Do not play sounds for this channel."] = "이 채널에서는 효과음을 재생하지 않음",
    ["No Sound"] = "소리 없음",
    ["Sensitivity"] = "민감도",
    ["Enable WorldFrame Click Detection."] = "WorldFrame 클릭 감지 사용",

    --OffScreenTracker.lua
    ["WIM Window Off Screen"] = "WIM 창이 화면 밖에 있습니다",
    ["Click to reposition."] = "클릭하여 위치 재조정",

    -- Whisper Mode Warnings
    ["Whisper Mode: In-line"] = "귓속말 모드: 인라인",
    ["Set whispers to In-line"] = "귓속말을 인라인으로 설정",
    ["Message suppression requires whispers to be set to 'In-line'."] = "메시지 숨김 기능을 사용하려면 귓속말이 '인라인'으로 설정되어 있어야 합니다.",
    ["It is recommended for whispers to be set to in-line in order to handle their behavior properly."] = "귓속말의 동작을 올바르게 처리하려면 인라인 설정을 권장합니다.",

    -- Skins --
    ["Blue"] = "파란색",
    ["Green"] = "초록색",
    ["Red"] = "빨간색",
    ["Yellow"] = "노란색",
});
