--[[
    Language Localization: zhCN
    Translated by: MouJiaoZi  moujiaozi@outlook.com
]]

WIM.AddLocale("zhCN", {
    ["WIM (WoW Instant Messenger)"] = "WIM 魔兽即时通讯",
    ["_Description"] = "WIM是一款在魔兽世界中提供熟悉的即时聊天风格的悄悄话插件，在本界面中你可以进行自定义以适应你的需求。",

    ["_DemoText"] = "这是一个仅用于预览的窗口示例，调整此窗口的位置将调整真正的对话窗口打开的位置，将其移动到合适的位置后通过右上角关闭窗口，窗口的位置设置将自动保存。",

    ["_DateFormat"] = "%Y/%m/%d",

    ["Yes"] = "是",
    ["No"] = "否",
    ["None"] = "无",
    ["Cancel"] = "取消",
    ["Unknown"] = "未知",
    ["Click to update..."] = "点击更新……",
    ["Usage"] = "使用方法",

    ["state_resting"] = "休息",
    ["state_combat"] = "战斗中",
    ["state_pvp"] = "PVP",
    ["state_arena"] = "竞技场",
    ["state_party"] = "在小队中",
    ["state_raid"] = "在团队中",
    ["state_other"] = "其他情况",

    ["Options"] = "选项",

    ["Up"] = "上",
    ["Down"] = "下",
    ["Left"] = "左",
    ["Right"] = "右",
    ["Ignore"] = "忽略",
    ["Block"] = "屏蔽",
    ["Enable WIM"] = "开启WIM",

    ["Enable"] = "启用",
    ["Disable"] = "禁用",
    ["Enable window fading effects."] = "开启窗口渐隐效果。",

    ["General"] = "一般",
    ["History"] = "历史记录",
    ["Filters"] = "过滤",

    ["Include sent messages in /REPLY."] = "在/REPLY中包含已发送的消息。",

    ["Sort tabs by:"] = "选项卡排序方法：",
    ["Window Created"] = "窗口创建时间",
    ["Last Activity"] = "最后活动",
    ["Alphabetical"] = "ID首字母",

    -- Class Names --
    ["Druid"] = LOCALIZED_CLASS_NAMES_MALE.DRUID,
    ["Hunter"] = LOCALIZED_CLASS_NAMES_MALE.HUNTER,
    ["Mage"] = LOCALIZED_CLASS_NAMES_MALE.MAGE,
    ["Paladin"] = LOCALIZED_CLASS_NAMES_MALE.PALADIN,
    ["Priest"] = LOCALIZED_CLASS_NAMES_MALE.PRIEST,
    ["Rogue"] = LOCALIZED_CLASS_NAMES_MALE.ROGUE,
    ["Shaman"] = LOCALIZED_CLASS_NAMES_MALE.SHAMAN,
    ["Warlock"] = LOCALIZED_CLASS_NAMES_MALE.WARLOCK,
    ["Warrior"] = LOCALIZED_CLASS_NAMES_MALE.WARRIOR,
    ["Death Knight"] = LOCALIZED_CLASS_NAMES_MALE.DEATHKNIGHT,
    ["Monk"] = LOCALIZED_CLASS_NAMES_MALE.MONK,
    ["Demon Hunter"] = LOCALIZED_CLASS_NAMES_MALE.DEMONHUNTER,
	["Evoker"] = LOCALIZED_CLASS_NAMES_MALE.EVOKER,

    -- Female Class Names --
    ["DruidF"] = LOCALIZED_CLASS_NAMES_FEMALE.DRUID,
    ["HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.HUNTER,
    ["MageF"] = LOCALIZED_CLASS_NAMES_FEMALE.MAGE,
    ["PaladinF"] = LOCALIZED_CLASS_NAMES_FEMALE.PALADIN,
    ["PriestF"] = LOCALIZED_CLASS_NAMES_FEMALE.PRIEST,
    ["RogueF"] = LOCALIZED_CLASS_NAMES_FEMALE.ROGUE,
    ["ShamanF"] = LOCALIZED_CLASS_NAMES_FEMALE.SHAMAN,
    ["WarlockF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARLOCK,
    ["WarriorF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARRIOR,
    ["Death KnightF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEATHKNIGHT,
    ["MonkF"] = LOCALIZED_CLASS_NAMES_FEMALE.MONK,
    ["Demon HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEMONHUNTER,
	["EvokerF"] = LOCALIZED_CLASS_NAMES_FEMALE.EVOKER,

    ["Game Master"] = "GM",

    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "切换WIM开/关。",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "切换Debug模式开/关。",

    -- Filters.lua --
    ["Whispers Sent by Addons"] = "由插件发送的悄悄话",
    ["WhisperSelect Part 1"] = "悄悄话选择区1",
    ["Example Spam Blocker"] = "骚扰屏蔽示例",
    ["WhisperSelect Part 2"] = "悄悄话选择区2",
    ["Filter Name"] = "过滤器名称",
    ["Filter By"] = "过滤",
    ["Pattern"] = "关键词",
    ["User Type"] = "角色类型",
    ["Level"] = "等级",
    ["Friends"] = "好友",
    ["Guild Members"] = "公会成员",
    ["Party Members"] = "小队成员",
    ["Raid Members"] = "团队成员",
    ["Cross-Realm"] = "其他服务器",
    ["Everyone"] = "所有人",
    ["User must be at least level:"] = "玩家最低等级：",
    ["Apply to messages received."] = "应用至收到的信息。",
    ["Apply to messages sent."] = "应用到发送的信息。",
    ["Apply to:"] = "应用于：",
    ["All Classes"] = "所有职业",
    ["Action to Perform:"] = "操作：",
    ["Allow"] = "允许",
    ["Ignore"] = "忽略",
    ["Blocked"] = "屏蔽",
    ["Save"] = "保存",
    ["Cancel"] = "取消",
    ["Edit Filter"] = "修改过滤器",
    ["Add Filter"] = "添加过滤器",

    -- History.lua --
    ["WIM History Button"] = "WIM历史按钮",
    ["Click to view message history."] = "点击查看历史消息。",
    ["WIM pruned %d |4message:messages; from your history."] = "WIM从历史记录中显示了 %d 条消息。",
    ["History Viewer"] = "聊天记录浏览器",
    ["Filters"] = "过滤器",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "你确定要删除 %s 的 %s 所有历史记录吗？",
    ["Search resulted in %d |4message:messages;."] = "找到 %d 消息。",
    ["No results found!"] = "没有任何结果！",
    ["Search"] = "搜索",
    ["Show All"] = "显示全部",
    ["Loading History"] = "正在载入历史记录",
    ["Chat View"] = "查看聊天",
    ["Text View"] = "查看文本",
    ["BBCode"] = "BBCode",
    ["WIM History Viewer can be accessed any time by typing:"] = "WIM聊天记录浏览器可以通过输入以下命令打开：",
    ["WIM History Viewer"] = "WIM聊天记录浏览器",
    ["Display history viewer."] = "打开聊天记录浏览器。",

    -- ldb.lua --
    ["No New Messages"] = "没有新消息",

    -- Menu.lua --
    ["Whispers"] = "悄悄话",
    ["Chat"] = "聊天",

    -- Negotiate.lua --
    ["WIM Update Available!"] = "WIM的新版本已经可用！",

    -- ShortcutBar.lua --
    ["Player Location"] = "玩家地区",
    ["Unknown"] = "未知",
    ["Click to update..."] = "点击更新……",
    ["Invite to Party"] = "组队邀请",
    ["Invite to Guild"] = "公会邀请",
    ["Add Friend"] = "添加好友",
    ["Ignore Player"] = "屏蔽玩家",
    ["Are you sure you want to\nignore %s?"] = "确定要屏蔽 %s 吗？",
    ["Right-Click for profile links..."] = "右键查看英雄榜链接……",
	["Profile Links"] = "英雄榜链接",
	["Location"] = "地区",
	["Game"] = "游戏",
	["Realm"] = "服务器",
	["Character"] = "角色",
	["Copy Name"] = "复制名称",

    -- Tutorials.lua --
    ["View Updates"] = "查看更新",

    -- WhisperEngine.lua --
    ["Whisper Received!"] = "新悄悄话！",
    ["Recently Sent Messages"] = "最近发出的消息",
    ["Users in %s"] = "%s中的用户",

    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "你正在删除所有WIM的聊天记录！",
    ["This action will reload your user interface."] = "这个操作将重载你的用户界面（/reload /rl）",
    ["Do you want to continue?"] = "你确定要继续吗？",
    ["You are about to restore WIM's filters to it's default settings!"] = "你正在重置WIM的过滤器设置！",
    ["Usage"] = "使用方法：",
    ["Clear various WIM data."] = "清除大量WIM数据。",

    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "WIM斜杠（/）命令",
    ["Hide or show {all, whisper, chat} windows."] = "隐藏或显示{所有、密语、聊天}窗口。",
    ["To see a list of available WIM slash commands type:"] = "要查看所有可用的斜杠（/）命令，请输入：",
    ["Display available slash commands."] = "显示可用的斜杠（/）命令。",
    ["Reload User Interface."] = "重新加载用户界面（/reload /rl）",

    -- TabHandler.lua --
    ["Manipulating Tabs"] = "操纵选项卡",

    -- WindowHandler.lua --
    ["Window Resized!"] = "已改变窗口大小！",
    ["Creating Tab Groups"] = "创建选项卡组",
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "你可以通过Shift+点击一个选项卡并将其拖动到其他选项卡上来组合它们。",
    ["Resizing Windows"] = "改变窗口大小",
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "你可以按住Shift并拖动窗口右下角来调整窗口的大小。",
    ["Demo Window"] = "示例窗口",
    ["<Shift-Click> to close window."] = "Shift+点击以关闭窗口。",
    ["Message Window Hidden"] = "已隐藏聊天窗口",
    ["Default"] = "默认",
    ["%s is Away From Keyboard: %s"] = "%s 正处于离开状态: %s",
    ["%s does not wish to be disturbed: %s"] = "%s 不愿被打扰: %s",
    ["Right-Mouse Click!"] = "右键点击！",
    ["There might be useful tools hidden under the message box. Right-Click to see them!"] = "在消息窗口下隐藏了有用的工具，右键点击来查看它们！",

    -- Options.lua --
    ["Display WIM's options."] = "显示WIM选项。",
    ["Resetting WIM will clear all of your settings!"] = "重置WIM将清除你所有的设置！",
    ["A reset will reload your user interface."] = "重置将重新加载您的用户界面。",
    ["Reset all options to default."] = "将所有选项恢复至默认状态。",

    -- CoreOptions --
    ["Created By:"] = "作者：",
    ["Special Thanks:"] = "鸣谢：",
    ["Welcome!"] = "欢迎！",
    ["Enable WIM"] = "开启WIM",
    ["Display Minimap Icon"] = "显示小地图图标",
    ["<Right-Click> to show unread messages."] = "右键点击显示未读消息。",
	["Display Addon Compartment Icon"] = "显示插件隔间图标",
    ["Display Tutorials"] = "显示教程",
    ["Reset Tutorials"] = "重置教程",
    ["Credits"] = "感谢",
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "这是一个同时包含表情与网页链接的超长信息8)。WIM的主页是 www.WIMAddon.com。",
    ["Message Formatting"] = "消息格式",
    ["Manipulate how WIM displays messages."] = "控制WIM如何显示消息。",
    ["Preview"] = "预览",
    ["Display Time Stamps"] = "显示时间",
    ["Display Emoticons"] = "显示表情",
    ["Display URLs as Links"] = "显示网址链接",
	["Indent long messages."] = "折叠长信息。",
	["Bracket names."] = "角色名称括号样式",
    ["Window Behavior"] = "窗口行为",
    ["You can control how windows behave while you are in different situations."] = "你可以控制在不同状态下的窗口的行为。",
    ["Intercept Slash Commands"] = "拦截斜杠（/）命令",
	["Obey autofocus rules when opening frames via the menu. (autofocus if unchecked)"] = "通过菜单打开窗口时遵从自动激活输入框规则（取消选择将自动激活输入框）。",
    ["Use the same rules for all states."] = "所有状态使用相同规则。",
    ["Behaviors for state:"] = "此状态的行为：",
    ["Pop-Up window when message is sent."] = "发送消息时弹出窗口。",
    ["Pop-Up window when message is received."] = "收到消息时弹出窗口。",
    ["Auto focus a window when it is shown."] = "窗口打开时自动激活输入框。",
    ["Keep focus on window after sending a message."] = "发送消息后保持输入框激活状态。",
    ["Suppress messages from the default chat frame."] = "隐藏暴雪聊天框中的消息。",
    ["Window Settings"] = "窗口设置",
    ["Some settings may be limited by certain skins."] = "部分设置可能受皮肤限制。",
    ["Default Width"] = "默认宽度",
    ["Default Height"] = "默认高度",
    ["Window Scale"] = "窗口缩放",
    ["Window Alpha"] = "窗口透明度",
    ["Set Window Spawn Location"] = "设置窗口默认位置",
    ["Up"] = "上",
    ["Down"] = "下",
    ["Left"] = "左",
    ["Right"] = "右",
    ["Cascade overlapping windows."] = "层叠重叠窗口。",
    ["Ignore arrow keys in message box."] = "激活输入框时屏蔽方向键。",
    ["Allow <ESC> to hide windows."] = "允许使用ESC隐藏窗口。",
    ["Display Settings"] = "显示设置",
    ["Configure general window display settings."] = "设置窗口的显示样式。",
    ["Window Skin:"] = "聊天窗口皮肤：",
    ["Version"] = "版本",
    ["Color: System Messages"] = "系统消息颜色",
    ["Color: Error Messages"] = "错误信息颜色",
    ["Color: URL - Web Addresses"] = "网址链接颜色",
    ["Color: History Messages Sent"] = "发送的消息颜色",
    ["Color: History Messages Received"] = "收到的消息颜色",
    ["Use colors suggested by skin."] = "使用皮肤推荐的颜色设置。",
    ["Enable window fading effects."] = "开启窗口渐隐效果。",
    ["Enable window animation effects."] = "开启窗口动画效果。",
    ["Display item links when hovering over them."] = "鼠标悬停时显示物品链接。",
    ["Fonts"] = "字体",
    ["Configure the fonts used in WIM's message windows."] = "设置聊天窗口中的字体。",
    ["Font Outline"] = "字体描边",
    ["Thin"] = "细",
    ["Thick"] = "粗",
    ["Use font suggested by skin."] = "使用皮肤推荐的字体。",
    ["Chat Font Size"] = "聊天字体大小",
    ["Configure general display settings when dealing with whispers."] = "设置悄悄话时的显示选项。",
    ["Color: Messages Sent"] = "发送的消息颜色",
    ["Color: Messages Received"] = "收到的消息颜色",
    ["Use colors suggested by skin."] = "使用皮肤推荐的颜色设置。",
    ["Display user class icons and details."] = "显示角色职业图标和详情。",
    ["Requires who lookups."] = "需要/who查找",
    ["Display Shortcut Bar"] = "显示快捷栏",
    ["Allow"] = "允许",
    ["Ignore"] = "忽略",
    ["Block"] = "屏蔽",
    ["Filtering"] = "过滤器",
    ["Filtering allows you to control which messages are handled as well as how they are handled by WIM."] = "设置消息过滤规则。",
    ["Enable Filtering"] = "开启过滤器",
    ["Protected"] = "已保护",
    ["Action:"] = "动作：",
    ["Occurrences:"] = "生效次数：",
    ["Delete Filter"] = "删除过滤器",
    ["History"] = "聊天记录",
    ["WIM can store conversations to be viewed at a later time."] = "WIM可以保存历史消息以供后日查看。",
    ["Enable History"] = "开启聊天记录",
    ["Messages"] = "消息",
    ["Preview history inside message windows."] = "在聊天窗口中展示历史消息。",
    ["Record Friends"] = "保存好友的消息",
    ["Record Guild"] = "保存公会的消息",
    ["Record Everyone"] = "保存所有人的消息",
    ["Record Chat"] = "保存聊天的消息",
    ["Maintenance"] = "维护",
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "保存过多聊天消息将对游戏性能产生影响，强烈推荐设置以下选项。",
    ["Save a maximum number of messages per person."] = "每人最大保存的聊天消息数。",
    ["%d |4Week:Weeks;"] = "%d 周",
    ["Automatically delete old messages."] = "自动删除过旧的消息。",
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM允许两名使用WIM的用户进行普通悄悄话无法实现的悄悄话对话。",
    ["Enable WIM-2-WIM"] = "开启WIM-2-WIM",
    ["Privacy"] = "隐私",
    ["Restrict the data that is shared."] = "限制共享的数据。",
    ["Allow others to see me typing."] = "显示自己的输入状态。",
    ["Allow others to see my location."] = "显示自己的位置。",
    ["Main"] = "主要",
    ["General"] = "一般",
    ["User Level"] = "等级",
    ["Windows will also be hidden when frames such as the world map are shown."] = "打开大地图时窗口将隐藏。",
    ["Sounds"] = "声音",
    ["Configure various sound events and how they are triggered."] = "控制音效以及触发方式。",
    ["Play sound when a whisper is received."] = "收到悄悄话时播放声音",
	["Play special sound for friends."] = "好友消息声音。",
	["Play special sound for battle.net friends."] = "战网好友消息声音。",
    ["Play special sound for guild members."] = "公会成员消息声音",
    ["Play sound when a whisper is sent."] = "发送悄悄话时播放声音",
    ["Allow others to see my talent spec."] = "允许他人查看我的专精。",
    ["Window Strata:"] = "窗口层级：",
	["Background"] = BACKGROUND,
	["Low"] = LOW,
	["Medium"] = "中",
	["High"] = "高",
	["Dialog"] = ENABLE_DIALOG,
	["Tooltip"] = "提示",
    ["Unlock from Minimap"] = "小地图按钮自由移动",
	["Press <Tab> to advance to next tell target."] = "按TAB切换至下一个聊天对象。",
	["Force sounds when game sound is disabled."] = "忽视游戏静音强制播放声音。",
    ["Colorize names."] = "名字上色。",
    ["Clamp window to screen."] = "窗口吸附。",
	["Group with whisper windows."] = "合并悄悄话窗口",
	["Color: BNet Messages Sent"] = "战网消息发送颜色",
	["Color: BNet Messages Received"] = "战网消息收到颜色",

    -- TabManagement.lua --
    ["Tab Management"] = "选项卡管理",
    ["Automatically manage your open windows and place them into appropriate tab groups."] = "自动管理打开的窗口并将它们放置在相似的选项卡组中。",
    ["Automatically group whispers."] = "自动合并悄悄话聊天。",
    ["Place friends in their own group."] = "好友聊天单独分组。",
	["Place guild members in their own group."] = "公会成员聊天单独分组。",
	["Automatically group chat windows."] = "自动分组聊天窗口。",
    ["Does not apply to windows already opened."] = "不要对已经打开的聊天窗口生效。",

    -- Talent Specs --
    ["Hybrid"] = "混合",

    -- Filters.lua --
    ["Show Alert"] = "显示警告",
    ["WIM has blocked a message from %s."] = "WIM阻止了%s的一条消息。",
    ["View Blocked Message"] = "查看被拦截的消息",
    ["Blocked Message"] = "被拦截的消息",

    -- MinimapIcon.lua
    ["Show Unread Messages"] = "显示未读消息",
    ["Show All Windows"] = "显示所有窗口",
    ["Hide All Windows"] = "隐藏所有窗口",

    --Emoticons.lua
    ["Also"] = "也",
    ["More"] = "更多",
    ["Emoticons"] = "表情",

    --Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = "由于你的当前状态，收到的悄悄话已经被隐藏，要改变设置，请在聊天框中输入",
    ["Expose"] = "清除",
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = "清除允许你清除你的窗口并将它们重置到原始位置。",
	["Auto hide/restore windows during combat."] = "战斗自动隐藏/脱战自动恢复窗口。",
	["Delay if I am typing a message."] = "打字时延迟恢复窗口。",
    ["Border Size"] = "边框宽度",
    ["Only while in an instance."] = "仅单一实例时",
    ["Show Border"] = "显示边框",
    ["Animation Direction:"] = "动画方向",

    --ChatEngine.lua
    ["WIM will manage this chat type within its own message windows."] = "WIM将在它的聊天窗口中管理聊天类型。",
    ["Show Minimap Alerts"] = "显示小地图警告",
    ["Never pop-up on my screen."] = "从不弹出",
	["Never suppress messages."] = "不要隐藏信息。",
	["Include emotes."] = "包含表情。",
    ["Have WIM monitor this channel."] = "WIM监控这个频道",
    ["Never Pop"] = "从不弹出",
    ["Never have this window pop-up on my screen."] = "从不弹出",
    ["Never Suppress"] = "正常聊天框",
    ["Never suppress messages from the default chat frame."] = "不要隐藏暴雪聊天框中的消息。",
    ["Show unread message alert on minimap."] = "在小地图上显示未读消息警告。",
    ["No History"] = "不保存聊天记录",
    ["Do not record history for this channel."] = "不要保存此频道的聊天记录",
    ["World Chat"] = "世界聊天",
    ["Custom Chat"] = "自定义聊天",
    ["Community Chat"] = "社区聊天",
    ["Chat"] = "聊天",
    ["Play special sound for %s."] = "为%s播放特殊音效。",
    ["Play sound when a message is received."] = "收到信息时播放音效。",
    ["Play sound when a message is sent."] = "发出消息时播放音效。",
    ["Do not play sounds for this channel."] = "不要为这个频道播放音效。",
    ["No Sound"] = "无声",
    ["Sensitivity"] = "灵敏度",
    ["Enable WorldFrame Click Detection."] = "开启世界框架点击侦测。",

    --OffScreenTracker.lua
    ["WIM Window Off Screen"] = "越界窗口侦测",
    ["Click to reposition."] = "点击重置位置。",

	-- Whisper Mode Warnings
	["Whisper Mode: In-line"] = "密语模式：内联",
	["Set whispers to In-line"] = "将密语设置为内联",
	["Message suppression requires whispers to be set to 'In-line'."] = "消息抑制需要将密语设置为“内联”。",
	["It is recommended for whispers to be set to in-line in order to handle their behavior properly."] = "建议将密语设置为内联，以便正确处理其行为。",

	-- Skins --
	["Blue"] = "蓝色",
	["Green"] = "绿色",
	["Red"] = "红色",
	["Yellow"] = "黄色",
});
