local _, T = ...

function T.WhatsNewData(vh, uv, li)
	vh("v8.6.3")
	uv("In Classic Mists, <b>Anglers Fishing Raft</b> is now considered usable by characters with a fishing skill of 525 or more.")
	uv("Fixed an issue causing profession extended conditionals such as <tt>[fish]</tt> to be unreliable in Classic WoW.")
	li("Quest Items ring now includes quest-starting items in Classic Anniversary.")
	vh("v8.6")
	uv("<b>Teleport Home</b> and <b>Return from Home</b> slices can now be added to OPie rings.")
	uv("The Mounts action category now also includes mounts you have acquired but your current character cannot use.")
	uv("<b>Nether-Swept Drake</b>, nee <b>Nether Drake</b>, can now be summoned by OPie.")
	li("The Quest Items ring now includes <b>Return from Home</b> when applicable.")
	li("The Quest Items ring now includes toys, mounts, and pets you have in your inventory.")
	li("<tt>[in:val/naigtal]</tt> is satisfied when you are on Val or Naigtal respectively.")
	li("<tt>[game:classic]</tt> is satisfied on non-Era/Season of Discovery Classic realms.")
	vh("v8.3")
	li("Added <tt>[in:midnight]</tt> extended conditional token.")
	li("Added <tt>[prey]</tt> extended conditional, satisfied while hunting Prey.")
	li("<b>Path of the Seasoned Hero</b> now teleports to Midnight Season 1 Mythic+ dungeons.")
	uv("Updated default rings for Midnight content.")
end