local _, T = ...

function T.WhatsNewData(vh, uv, li)
	vh("v8.8")
	uv("You can now add slices to rings by dragging actions from the spell book, bags, toy box, mount journal, etc, onto the slice list in the <tt>/opie rings</tt> editor.")
	li("<b>Path of the Seasoned Hero</b> updated for Midnight Season 2.")
	uv("Added <tt>[warbank]</tt> conditional, satisfied when you can access the warband bank.")
	uv("<b>Warband Bank Distance Inhibitor</b> feedback is now adjusted when you cannot access the warband bank.")
	li("OPie's Options window (opened via <tt>/opie</tt>) is no longer closed by the Spellbook/Talents UI.")
	vh("v8.6")
	uv("<b>Teleport Home</b> and <b>Return from Home</b> slices can now be added to OPie rings.")
	uv("The Mounts action category now also includes mounts you have acquired but your current character cannot use.")
	uv("<b>Nether-Swept Drake</b>, nee <b>Nether Drake</b>, can now be summoned by OPie.")
	li("The Quest Items ring now includes <b>Return from Home</b> when applicable.")
	li("The Quest Items ring now includes toys, mounts, and pets you have in your inventory.")
	li("The Quest Items ring now includes quest-starting items in Classic Anniversary.")
	li("<tt>[in:val/naigtal]</tt> is satisfied when you are on Val or Naigtal respectively.")
	li("<tt>[game:classic]</tt> is satisfied on non-Era/Season of Discovery Classic realms.")
	vh("v8.3")
	li("Added <tt>[in:midnight]</tt> extended conditional token.")
	li("Added <tt>[prey]</tt> extended conditional, satisfied while hunting Prey.")
	li("<b>Path of the Seasoned Hero</b> now teleports to Midnight Season 1 Mythic+ dungeons.")
	uv("Updated default rings for Midnight content.")
end