local L = LibStub("AceLocale-3.0"):NewLocale("EasyFrames", "zhCN")
if not L then return end

L["loaded. Options:"] = "已载入，选项命令："

L["Opacity"] = "不透明度"
L["Opacity of combat texture"] = "战斗材质的不透明度。"

L["Main options"] = "主选项"
L["In main options you can set the global options like colored frames, buffs settings, etc"] = "在主选项中你可以设置全局选项，如彩色框架，增益效果设置...等"

L["Percent"] = "百分比"
L["Current + Max"] = "当前 + 最大"
L["Current + Max + Percent"] = "当前 + 最大 + 百分比"
L["Current + Percent"] = "当前 + 百分比"
L["Custom format"] = "自定义格式"
L["Smart"] = "智能"

L["None"] = "无"
L["Outline"] = "轮廓"
L["Thickoutline"] = "粗轮廓"
L["Monochrome"] = "单色"

L["Portrait"] = "头像"
L["Default"] = "默认"
L["Hide"] = "隐藏"

L["HP and MP bars"] = "血量和能量条"

L["Font size"] = "字体大小"
L["Healthbar font size"] = "血量条字体大小"
L["Manabar font size"] = "能量条字体大小"
L["Font family"] = "字体"
L["Healthbar font style"] = "血量条字体样式"
L["Healthbar font family"] = "血量条字体"
L["Manabar font style"] = "能量条字体样式"
L["Manabar font family"] = "能量条字体"
L["Font style"] = "字体样式"

L["Reverse the direction of losing health/mana"] = "反向显示损失的血量/能量"
L["By default direction starting from right to left. If checked direction of losing health/mana will be from left to right"] = "默认的方向是从右到左，勾选时损失血量/能量的方向会从左到右。"

L["Custom format of HP"] = "自定义血量格式"
L["You can set custom HP format. More information about custom HP format you can read on project site.\n\n" ..
    "Formulas:"] = "可以自定义血量格式，关于血量格式的更多相关信息请浏览插件的官方网站。\n\n公式语法:"
L["Use full values of health"] = "使用完整的血量数值"
L["Formula converts the original value to the specified value.\n\n" ..
    "Description: for example formula is '%.fM'.\n" ..
    "The first part '%.f' is the formula itself, the second part 'M' is the abbreviation\n\n" ..
    "Example, value is 150550. '%.f' will be converted to '151' and '%.1f' to '150.6'"] = "公式语法会將原始的数值转换成指定的数值。\n\n说明: 例如公式语法为 '%.fM'。\n第一个部分的 '%.f' 是公式本身，第二个部分的 'M' 是百万的单位缩写\n\n举例來说，当数值是 150550 时，'%.f' 会將其转换成 '151'，而 '%.1f' 会转换成 '150.6'"
L["Value greater than 1000"] = "数值大于 1000"
L["Value greater than 10 000"] = "数值大于 10000"
L["Value greater than 100 000"] = "数值大于 100000"
L["Value greater than 1 000 000"] = "数值大于 1000000"
L["Value greater than 10 000 000"] = "数值大于 10000000"
L["Value greater than 100 000 000"] = "数值大于 100000000"
L["Value greater than 1 000 000 000"] = "数值大于 1000000000"
L["By default all formulas use divider (for value eq 1000 and more it's 1000, for 1 000 000 and more it's 1 000 000, etc).\n\n" ..
    "If checked formulas will use full values of HP (without divider)"] = "所有公式默认都会使用千位分隔符号 (大于或等于 1000 的数值会是 1000，大于或等于 1 000 000 会是 1 000 000，以此类推)。\n\n勾选时，公式会使用完整的血量数值 (沒有分隔符号)。"
L["Displayed HP by pattern"] = "使用格式显示血量"
L["You can use patterns:\n\n" ..
    "%CURRENT% - return current health\n" ..
    "%MAX% - return maximum of health\n" ..
    "%PERCENT% - return percent of current/max health\n\n" ..
    "All values are returned from formulas. For set abbreviation use formulas' fields"] = "可以使用的格式有:\n\n%CURRENT% - 返回当前的血量\n%MAX% - 返回最大血量\n%PERCENT% - 返回当前血量除以最大血量的百分比\n\n所有数值都会通过公式返回，请使用公式的文字格式设置好单位缩写。"

L["Custom format of mana"] = "自定义能量格式"
L["You can set custom mana format. More information about custom mana format you can read on project site.\n\n" ..
        "Formulas:"] = "可以自定义能量格式，关于能量格式的更多相关信息请浏览官方网站。\n\n公式语法:"
L["Use full values of mana"] = "使用完整的能量数值"
L["By default all formulas use divider (for value eq 1000 and more it's 1000, for 1 000 000 and more it's 1 000 000, etc).\n\n" ..
        "If checked formulas will use full values of mana (without divider)"] = "所有公式默认都会使用千位分隔符号 (大于或等于 1000 的数值会是 1000，大于或等于 1 000 000 会是 1 000 000，以此类推)。\n\n勾选时，公式会使用完整的能量数值 (沒有分隔符号)。"
L["Displayed mana by pattern"] = "使用格式显示能量"
L["You can use patterns:\n\n" ..
        "%CURRENT% - return current mana\n" ..
        "%MAX% - return maximum of mana\n" ..
        "%PERCENT% - return percent of current/max mana\n\n" ..
        "All values are returned from formulas. For set abbreviation use formulas' fields"] = "可以使用的格式有:\n\n%CURRENT% - 返回当前的能量\n%MAX% - 返回最大能量\n%PERCENT% - 返回当前能量除以最大能量的百分比\n\n所有数值都会通过公式返回，请使用公式的文字格式设置好单位缩写。"


L["Frames"] = "框架"
L["Setting for unit frames"] = "单位框架的设置。"

L["Class colored healthbars"] = "血量条使用职业颜色"
L["If checked frames becomes class colored.\n\n" ..
    "This option excludes the option 'Healthbar color is based on the current health value'"] = "勾选时，框架会变成职业颜色。\n\n这个选项会停用 '根据当前血量变化血量条颜色' 选项。"
L["Healthbar color is based on the current health value"] = "根据当前血量变化血量条颜色"
L["Healthbar color is based on the current health value.\n\n"..
    "This option excludes the option 'Class colored healthbars'"] = "根据当前血量变化血量条颜色。\n\n这个选项会停用 '血量条使用职业颜色' 选项。"
L["Custom buffsize"] = "自定义增益效果大小"
L["Buffs settings (like custom buffsize, highlight dispelled buffs, etc)"] = "增益效果设置 (包括自定义图标大小、高亮标示可驱散的效果...等等)。"
L["Turn on custom buffsize"] = "启用自定义大小"
L["Turn on custom target and focus frames buffsize"] = "启用目标和焦点目标框架的自定义增益效果大小。"
L["Buffs"] = "增益效果"
L["Buffsize"] = "增益效果大小"
L["Self buffsize"] = "自己的增益效果大小"
L["Buffsize that you create"] = "自己施放的增益效果大小。"
L["Highlight dispelled buffs"] = "高亮标示可驱散"
L["Highlight buffs that can be dispelled from target frame"] = "高亮标示目标框架可驱散的效果。"
L["Dispelled buff scale"] = "可驱散的效果缩放大小"
L["Dispelled buff scale that can be dispelled from target frame"] = "目标框架可驱散的效果缩放大小。"
L["Only if player can dispel them"] = "只有玩家可驱散时"
L["Highlight dispelled buffs only if player can dispel them"] = "只有玩家可驱散时才要高亮标示可驱散的效果。"
L["Show only my debuffs"] = "只显示我施放的减益魔法"
L["Show only my debuffs (which the player creates)"] = "只显示我施放的减益魔法（由玩家施放的）"
L["Max buffs count"] = "增益魔法最大数量"
L["How many buffs you can see on target/focus frames"] = "你可以在目标/焦点框架上看到多少个增益效果"
L["Max debuffs count"] = "减益魔法最大数量"
L["How many debuffs you can see on target/focus frames"] = "你可以在目标/焦点框架上看到多少个减益效果"

L["Class portraits"] = "职业头像"
L["Replaces the unit-frame portrait with their class icon"] = "使用职业图标替换单位框架的头像。"
L["Hide frames out of combat"] = "非战斗中隐藏框架"
L["Hide frames out of combat (for example in resting)"] = "非战斗中隐藏框架 (例如休息时)。"
L["Only if HP equal to 100%"] = "只有血量等于 100% 时"
L["Hide frames out of combat only if HP equal to 100%"] = "只有血量等于 100% 时才要在非战斗中隐藏框架。"
L["Opacity of frames"] = "框架不透明度"
L["Opacity of frames when frames is hidden (in out of combat)"] = "框架隐藏时的不透明度 (非战斗中)。"

L["Texture"] = "材质"
L["Set the frames bar Texture"] = "设置框架条的材质。"
L["Bright frames border"] = "框架外框亮度"
L["You can set frames border bright/dark color. From bright to dark. 0 - dark, 100 - bright"] = "设置框架外框显示较亮/或较暗的颜色， 0 - 暗，100 - 亮。"
L["Use a light texture"] = "使用亮色的材质"
L["Use a brighter texture (like Blizzard's default texture)"] = "使用较明亮的材质 (像是暴雪默认的材质)。"
L["Set the manabar texture by force"] = "强行设置能量条材质"
L["Use a force manabar texture setter. The Blizzard UI resets to default manabar texture each time an addon tries to modify it. " ..
        "With this option, the texture setter will set texture by force.\n\n" ..
        "IMPORTANT. When this option is enabled the addon will use a more CPU. More information in the issue #28"] = "使用强行能量条置器，每次插件尝试修改时，暴雪UI都会重置为默认的能量条材质。使用此选项，设置器将强行设置材质。\n\n重要。 启用此选项后，插件将使用更多内存， 更多信息请在问题#28查阅。"

L["Frames colors"] = "框架颜色"
L["In this section you can set the default colors for friendly, enemy and neutral frames"] = "设置友方、敌方和中立框架的默认颜色。"
L["Set default friendly healthbar color"] = "设置友方血条颜色"
L["You can set the default friendly healthbar color for frames"] = "设置友方框架默认的血条颜色。"
L["Set default enemy healthbar color"] = "设置敌方血条颜色"
L["You can set the default enemy healthbar color for frames"] = "设置敌方框架默认的血条颜色。"
L["Set default neutral healthbar color"] = "设置中立血条颜色"
L["You can set the default neutral healthbar color for frames"] = "设置中立框架默认的血条颜色。"
L["Reset color to default"] = "恢复成默认颜色"

L["Other"] = "其他"
L["In this section you can set the settings like 'show welcome message' etc"] = "在这里你可以设置 '显示欢迎信息' 等设置"
L["Show welcome message"] = "显示欢迎信息"
L["Show welcome message when addon is loaded"] = "插件载入时显示欢迎信息。"

L["Save positions of frames to current profile"] = "将框架的位置保存到当前配置文件"
L["Restore positions of frames from current profile"] = "从当前配置文件恢复框架的位置"
L["Saved"] = "保存"
L["Restored"] = "恢复"


L["Player"] = "玩家"
L["In player options you can set scale player frame, healthbar text format, etc"] = "在玩家选项中可以设置玩家框架的缩放大小、血量条文字格式...等。"
L["Set the player's portrait"] = "设置玩家的头像"
L["Player name"] = "玩家名字"
L["Player name font family"] = "玩家名字字体"
L["Player name font size"] = "玩家名字字体大小"
L["Player name font style"] = "玩家名字字体样式"
L["Show or hide some elements of frame"] = "显示或隐藏框架的某些部分"
L["Show player name"] = "显示玩家名字"
L["Show player name inside the frame"] = "名字在框架內侧"
L["Player frame scale"] = "玩家框架缩放大小"
L["Scale of player unit frame"] = "玩家框架的缩放大小。"
L["Enable hit indicators"] = "启用战斗文字"
L["Show or hide the damage/heal which you take on your unit frame"] = "在你的框架中显示或隐藏你受到的伤害/治疗。"
L["Player healthbar text format"] = "玩家血量条文字格式"
L["Set the player healthbar text format"] = "设置玩家血量条的文字格式。"
L["Player manabar text format"] = "玩家能量条文字格式"
L["Set the player manabar text format"] = "设置玩家能量条的文字格式。"
L["Show player specialbar"] = "显示职业特殊能量条"
L["Show or hide the player specialbar, like Paladin's holy power, Priest's orbs, Monk's harmony or Warlock's soul shards"] = "显示或隐藏玩家的职业特殊能量条，如圣骑士的圣能、牧师的狂乱值、武僧的气或术士的灵魂碎片。"
L["Show player resting icon"] = "显示玩家休息图标"
L["Show or hide player resting icon when player is resting (e.g. in the tavern or in the capital)"] = "显示或隐藏玩家休息时的图标 (例如在旅店或主城中时)。"
L["Show player status texture (inside the frame)"] = "显示玩家状态材质 (框架內)"
L["Show or hide player status texture (blinking glow inside the frame when player is resting or in combat)"] = "显示或隐藏玩家的状态材质 (当玩家正在休息或战斗中框架会闪烁发光)。"
L["Show player combat texture (outside the frame)"] = "显示玩家战斗材质 (框架外)"
L["Show or hide player red background texture (blinking red glow outside the frame in combat)"] = "显示或隐藏玩家的红色背景材质 (战斗中框架外侧会闪红光)。"
L["Show player group number"] = "显示玩家队伍编号"
L["Show or hide player group number when player is in a raid group (over portrait)"] = "当玩家在团队中时，显示或隐藏玩家的小队编号 (在头像上)。"
L["Show player role icon"] = "显示玩家角色图标"
L["Show or hide player role icon when player is in a group"] = "当玩家在队伍中时，显示或隐藏玩家担任的角色图标。"


L["Target"] = "目标"
L["In target options you can set scale target frame, healthbar text format, etc"] = "在目标选项中可以设置目标框架的缩放大小、血量条文字格式...等。"
L["Set the target's portrait"] = "设置目标的头像"
L["Target name"] = "目标名字"
L["Target name font family"] = "目标名字字体"
L["Target name font size"] = "目标名字字体大小"
L["Target name font style"] = "目标名字字体样式"
L["Target frame scale"] = "目标框架缩放大小"
L["Scale of target unit frame"] = "目标框架的缩放大小。"
L["Target healthbar text format"] = "目标血量条文字格式"
L["Set the target healthbar text format"] = "设置目标血量条的文字格式。"
L["Target manabar text format"] = "目标能量条文字格式"
L["Set the target manabar text format"] = "设置目标能量条的文字格式。"
L["Show target name"] = "显示目标名字"
L["Show target name inside the frame"] = "名字在框架內侧"
L["Show target of target frame"] = "显示目标的目标框架"
L["Show target combat texture (outside the frame)"] = "显示目标战斗材质 (框架外)"
L["Show or hide target red background texture (blinking red glow outside the frame in combat)"] = "显示或隐藏目标的红色背景材质 (战斗中框架外侧会闪红光)。"
L["Show blizzard's target castbar"] = "显示暴雪的目标施法条"
L["When you change this option you need to reload your UI (because it's Blizzard config variable). \n\nCommand /reload"] = "更改这个选项需要重新载入界面 (因为这是暴雪的游戏参数)。\n\n输入命令 /reload"


L["Focus"] = "焦点目标"
L["In focus options you can set scale focus frame, healthbar text format, etc"] = "在焦点目标选项中可以设置焦点目标框架的缩放大小、血量条文字格式...等。"
L["Set the focus's portrait"] = "设置焦点目标的头像"
L["Focus name"] = "焦点目标名字"
L["Focus name font family"] = "焦点目标名字字体"
L["Focus name font size"] = "焦点目标名字字体大小"
L["Focus name font style"] = "焦点目标名字字体样式"
L["Focus frame scale"] = "焦点目标框架缩放大小"
L["Scale of focus unit frame"] = "焦点目标框架的缩放大小。"
L["Focus healthbar text format"] = "焦点目标血量条文字格式"
L["Set the focus healthbar text format"] = "设置焦点目标血量条的文字格式。"
L["Focus manabar text format"] = "焦点目标能量条文字格式"
L["Set the focus manabar text format"] = "设置焦点目标能量条的文字格式。"
L["Show target of focus frame"] = "显示焦点目标的目标框架"
L["Show name of focus frame"] = "显示焦点目标名字"
L["Show name of focus frame inside the frame"] = "名字在框架內侧"
L["Show focus combat texture (outside the frame)"] = "显示焦点目标战斗材质 (框架外)"
L["Show or hide focus red background texture (blinking red glow outside the frame in combat)"] = "显示或隐藏焦点目标的红色背景材质 (战斗中框架外侧会闪红光)。"


L["Pet"] = "宠物"
L["In pet options you can set scale pet frame, show/hide pet name, enable/disable pet hit indicators, etc"] = "在宠物选项中可以设置宠物框架的缩放大小、显示/隐藏宠物名字、启用/禁用宠物命中指示器等。"
L["Pet name"] = "宠物名字"
L["Pet name font family"] = "宠物名字字体"
L["Pet name font size"] = "宠物名字字体大小"
L["Pet name font style"] = "宠物名字字体样式"
L["Pet frame scale"] = "宠物框架缩放大小"
L["Scale of pet unit frame"] = "宠物框架的缩放大小。"
L["Lock pet frame"] = "锁定宠物框架"
L["Lock or unlock pet frame. When unlocked you can move frame using your mouse (draggable)"] = "锁定或解锁宠物框架，解锁时可以使用鼠标來移动框架 (可以拖动)。"
L["Reset position to default"] = "恢复成默认位置"
L["Pet healthbar text format"] = "宠物血量条文字格式"
L["Set the pet healthbar text format"] = "设置宠物血量条的文字格式。"
L["Pet manabar text format"] = "宠物能量条文字格式"
L["Set the pet manabar text format"] = "设置宠物能量条的文字格式。"
L["Show pet name"] = "显示宠物名字"
L["Show or hide the damage/heal which your pet take on pet unit frame"] = "在宠物框架中显示或隐藏宠物受到的伤害/治疗。"
L["Show pet combat texture (inside the frame)"] = "显示宠物战斗材质 (框架內)"
L["Show or hide pet red background texture (blinking red glow inside the frame in combat)"] = "显示或隐藏宠物的红色背景材质 (战斗中框架內侧会闪红光)。"
L["Show pet combat texture (outside the frame)"] = "显示宠物战斗材质 (框架外)"
L["Show or hide pet red background texture (blinking red glow outside the frame in combat)"] = "显示或隐藏宠物的红色背景材质 (战斗中框架外侧会闪红光)。"


L["Party"] = "队伍"
L["In party options you can set scale party frames, healthbar text format, etc"] = "在队伍选项中你可以设置队伍框架的缩放大小、血量条文字格式...等。"
L["Party frames scale"] = "队伍框架缩放大小"
L["Scale of party unit frames"] = "队伍框架的缩放大小。"
L["Party healthbar text format"] = "队伍血量条文字格式"
L["Set the party healthbar text format"] = "设置队伍血量条的文字格式。"
L["Party manabar text format"] = "队伍能量条文字格式"
L["Set the party manabar text format"] = "设置队伍能量条的文字格式。"
L["Party frames names"] = "队伍框架名字"
L["Show names of party frames"] = "显示队伍框架名字"
L["Party names font family"] = "队伍名字字体"
L["Party names font size"] = "队伍名字字体大小"
L["Party names font style"] = "队伍名字字体样式"
L["Show party pet frames"] = "显示队伍宠物框架"

L["Profiles"] = "设定档"
L["EasyFrames"] = "暴雪风格头像 EasyFrames"
L["Easy Frames"] = "头像"