local Runtime = _G["Ayije_CDM"]
if not Runtime then return end
local ns = Runtime._OptionsNS
local CDM = Runtime

ns.ConfigKeys = {
    order = {
        "cooldowngroups",
        "styling",
        "text",
        "bars",
        "resources",
        "racials",
        "defensives",
        "trinkets",
        "externals",
        "castbar",
        "glow",
        "fading",
        "assist",
        "positions",
        "buffgroups",
    },
    categories = {
        cooldowngroups = {
            label = "Cooldown Groups",
            keys = {
                "cooldownGroups",
                "ungroupedCooldownOverrides",
                "sizeEssRow1",
                "sizeEssRow2",
                "sizeUtility",
                "sizeBuff",
                "spacing",
                "maxRowEss",
                "utilityWrap",
                "maxRowUtil",
                "utilityUnlock",
                "utilityXOffset",
                "utilityVertical",
            },
        },
        styling = {
            label = "Border & Visual Styling",
            keys = {
                "borderFile",
                "borderSize",
                "borderOffsetX",
                "borderOffsetY",
                "borderColor",
                "zoomIcons",
                "zoomAmount",
                "hideIconOverlay",
                "hideIconOverlayTexture",
                "hideDebuffBorder",
                "hidePandemicIndicator",
                "hideCooldownBling",
                "swipeColor",
                "hideGCDSwipe",
            },
        },
        text = {
            label = "Text & Font Settings",
            keys = {
                "textFont",
                "textFontOutline",
                "cooldownFontSize",
                "cooldownColor",
                "cooldownDecimalThreshold",
                "cooldownColorThresholdEnabled",
                "cooldownColorThreshold",
                "cooldownColorThresholdColor",
                "essRow2CooldownFontSize",
                "utilityCooldownFontSize",
                "chargeFontSize",
                "utilityChargeFontSize",
                "chargeColor",
                "chargePosition",
                "chargeOffsetX",
                "chargeOffsetY",
                "essRow2ChargeFontSize",
                "essRow2ChargeColor",
                "essRow2ChargePosition",
                "essRow2ChargeOffsetX",
                "essRow2ChargeOffsetY",
                "utilityChargeColor",
                "utilityChargePosition",
                "utilityChargeOffsetX",
                "utilityChargeOffsetY",
                "countFontSize",
                "countColor",
                "buffCooldownFontSize",
                "buffCooldownColor",
                "countPositionMain",
                "countOffsetXMain",
                "countOffsetYMain",
                "buffBarNameFontSize",
                "buffBarNameColor",
                "buffBarNameOffsetX",
                "buffBarNameOffsetY",
                "buffBarDurationFontSize",
                "buffBarDurationColor",
                "buffBarDurationOffsetX",
                "buffBarDurationOffsetY",
            },
        },
        bars = {
            label = "Buff Bar Settings",
            keys = {
                "buffBarWidth",
                "buffBarHeight",
                "buffBarSpacing",
                "buffBarGrowDirection",
                "buffBarIconPosition",
                "buffBarIconGap",
                "buffBarShowName",
                "buffBarNameMaxChars",
                "buffBarShowDuration",
                "buffBarShowApplications",
                "buffBarApplicationsFontSize",
                "buffBarApplicationsColor",
                "buffBarApplicationsPosition",
                "buffBarApplicationsOffsetX",
                "buffBarApplicationsOffsetY",
                "buffBarTexture",
                "buffBarColor",
                "buffBarBackgroundColor",
                "buffBarDualMode",
            },
        },
        resources = {
            label = "Resource Bar Settings",
            keys = {
                "resourcesEnabled",
                "resourceBarSettings",
                "resourceGroupSettings",
                "unifiedBorder",
                "moveBuffsDown",
                "moveBuffsDownOffset",
                "moveBuffsDownFallback",
            },
        },
        racials = {
            label = "Racials Tracker Settings",
            keys = {
                "racialsEnabled",
                "racialsIconWidth",
                "racialsIconHeight",
                "racialsAnchorPoint",
                "racialsOffsetX",
                "racialsOffsetY",
                "racialsChargeFontSize",
                "racialsCooldownFontSize",
                "racialsChargePosition",
                "racialsChargeOffsetX",
                "racialsChargeOffsetY",
                "racialsUsePartyFrame",
                "racialsPartyFrameSide",
                "racialsPartyFrameOffsetX",
                "racialsPartyFrameOffsetY",
                "racialsChargeColor",
                "racialsShowItemsAtZeroStacks",
                "racialsCustomEntries",
                "racialsOrderPerSpec",
                "racialsDisabled",
            },
        },
        defensives = {
            label = "Defensives Tracker Settings",
            keys = {
                "defensivesEnabled",
                "defensivesIconWidth",
                "defensivesIconHeight",
                "defensivesAnchorPoint",
                "defensivesOffsetX",
                "defensivesOffsetY",
                "defensivesChargeFontSize",
                "defensivesCooldownFontSize",
                "defensivesChargePosition",
                "defensivesChargeOffsetX",
                "defensivesChargeOffsetY",
                "defensivesDisabledSpells",
                "defensivesCustomSpells",
                "defensivesOrder",
            },
        },
        trinkets = {
            label = "Trinkets Tracker Settings",
            keys = {
                "trinketsEnabled",
                "trinketsIconWidth",
                "trinketsIconHeight",
                "trinketsAnchorPoint",
                "trinketsOffsetX",
                "trinketsOffsetY",
                "trinketsCooldownFontSize",
                "trinketsShowPassive",
                "trinketsMode",
                "trinketsEssentialRow",
                "trinketsEssentialPosition",
            },
        },
        externals = {
            label = "Externals Tracker Settings",
            keys = {
                "externalsEnabled",
                "externalsIconWidth",
                "externalsIconHeight",
                "externalsCooldownFontSize",
                "externalsDisableBlink",
            },
        },
        castbar = {
            label = "Cast Bar Settings",
            keys = {
                "castBarEnabled",
                "hideBlizzardCastBar",
                "castBarWidth",
                "castBarHeight",
                "castBarFontSize",
                "castBarShowSpellName",
                "castBarNameMaxChars",
                "castBarShowTimer",
                "castBarShowSpark",
                "castBarNameOffsetX",
                "castBarNameOffsetY",
                "castBarTimerOffsetX",
                "castBarTimerOffsetY",
                "castBarOffsetX",
                "castBarOffsetY",
                "castBarAnchor",
                "castBarAnchorPoint",
                "castBarTargetPoint",
                "castBarPreviewEnabled",
                "castBarUseAtlasTextures",
                "castBarTexture",
                "castBarBackgroundTexture",
                "castBarBackgroundColor",
                "castBarUseClassColor",
                "castBarCastColor",
                "castBarChannelColor",
                "castBarUninterruptibleColor",
                "castBarEmpowerWindUpColor",
                "castBarEmpowerStage1Color",
                "castBarEmpowerStage2Color",
                "castBarEmpowerStage3Color",
                "castBarEmpowerStage4Color",
                "castBarShowIcon",
                "castBarIconPosition",
                "castBarIconGap",
                "castBarAutoWidthSource",
            },
        },
        glow = {
            label = "Glow Settings",
            keys = {
                "glowType",
                "glowUseCustomColor",
                "glowColor",
                "glowPixelLines",
                "glowPixelFrequency",
                "glowPixelLength",
                "glowPixelThickness",
                "glowPixelXOffset",
                "glowPixelYOffset",
                "glowPixelBorder",
                "glowAutocastParticles",
                "glowAutocastFrequency",
                "glowAutocastScale",
                "glowAutocastXOffset",
                "glowAutocastYOffset",
                "glowButtonFrequency",
                "glowProcDuration",
                "glowProcXOffset",
                "glowProcYOffset",
            },
        },
        assist = {
            label = "Assist Settings",
            keys = {
                "rotationAssistEnabled",
                "rotationAssistGlowRatio",
                "assistEnabled",
                "assistFontSize",
                "assistColor",
                "assistPosition",
                "assistOffsetX",
                "assistOffsetY",
                "pressOverlayEnabled",
                "pressOverlayTint",
                "pressOverlayTintColor",
                "pressOverlayHighlight",
                "pressOverlayBorder",
                "pressOverlayBorderColor",
            },
        },
        fading = {
            label = "Fading Settings",
            keys = {
                "fadingEnabled",
                "fadingTriggerNoTarget",
                "fadingTriggerOOC",
                "fadingTriggerMounted",
                "fadingOpacity",
                "fadingEssential",
                "fadingUtility",
                "fadingBuffs",
                "fadingBuffBars",
                "fadingRacials",
                "fadingDefensives",
                "fadingTrinkets",
                "fadingResources",
            },
        },
        positions = {
            label = "Positions & Locking",
            keys = {
                "containerLocked",
                "buffContainerLocked",
                "buffBarContainerLocked",
                "editModePositions",
                "utilityYOffset",
            },
        },
        buffgroups = {
            label = "Buff Groups",
            keys = {
                "buffGroups",
                "ungroupedBuffOverrides",
                "spellRegistry",
                "customBuffRegistry",
                "ungroupedCustomBuffOrder",
            },
        },
    },
}

do
    local defaults = CDM.defaults
    if not defaults then return end

    local keysInCategories = {}
    for catName, catDef in pairs(ns.ConfigKeys.categories) do
        for _, key in ipairs(catDef.keys) do
            if keysInCategories[key] then
                print("|cffff6600[CDM] ConfigKeys: '" .. key .. "' in both '" .. keysInCategories[key] .. "' and '" .. catName .. "'|r")
            end
            keysInCategories[key] = catName
        end
    end

    for key in pairs(defaults) do
        if not keysInCategories[key] then
            print("|cffff6600[CDM] ConfigKeys: default key '" .. key .. "' not in any export category|r")
        end
    end

    for key, catName in pairs(keysInCategories) do
        if defaults[key] == nil then
            print("|cffff6600[CDM] ConfigKeys: export key '" .. key .. "' (in '" .. catName .. "') has no default|r")
        end
    end
end
