-- Config/ConfigKeys.lua - Centralized config key registry for import/export
-- Defines category labels and key lists to prevent drift across the UI and profile I/O

local Runtime = _G["Ayije_CDM"]
if not Runtime then return end
local API = Runtime.API
local ns = Runtime._OptionsNS
local CDM = Runtime

ns.ConfigKeys = {
    order = {
        "icons",
        "sizes",
        "styling",
        "text",
        "bars",
        "resources",
        "racials",
        "defensives",
        "trinkets",
        "castbar",
        "glow",
        "fading",
        "assist",
        "positions",
        "custombuffs",
    },
    categories = {
        icons = {
            label = "Spell Registry & Icon Order",
            keys = {
                "spellRegistry",
            },
        },
        sizes = {
            label = "Icon Sizes & Layout",
            keys = {
                "sizeEssRow1",
                "sizeEssRow2",
                "sizeUtility",
                "sizeBuff",
                "sizeBuffSecondary",
                "sizeBuffTertiary",
                "spacing",
                "maxRowEss",
                "utilityYOffset",
                "utilityWrap",
                "maxRowUtil",
                "utilityUnlock",
                "utilityXOffset",
                "utilityVertical",
                "buffSecondaryHorizontal",
                "buffTertiaryHorizontal",
            },
        },
        styling = {
            label = "Border & Visual Styling",
            keys = {
                "borderFile",
                "borderSize",
                "borderOffsetX",
                "borderOffsetY",
                "borderColor",
                "zoomIcons",
                "hideDebuffBorder",
                "hidePandemicIndicator",
                "hideCooldownBling",
            },
        },
        text = {
            label = "Text & Font Settings",
            keys = {
                "textFont",
                "textFontOutline",
                "cooldownFontSize",
                "cooldownColor",
                "chargeFontSize",
                "chargeColor",
                "chargePosition",
                "chargeOffsetX",
                "chargeOffsetY",
                "countFontSize",
                "countColor",
                "buffCooldownFontSize",
                "countPositionMain",
                "countOffsetXMain",
                "countOffsetYMain",
                "countPositionSec",
                "countOffsetXSec",
                "countOffsetYSec",
                "countPositionTert",
                "countOffsetXTert",
                "countOffsetYTert",
                "buffBarNameFontSize",
                "buffBarNameColor",
                "buffBarNameOffsetX",
                "buffBarNameOffsetY",
                "buffBarDurationFontSize",
                "buffBarDurationColor",
                "buffBarDurationOffsetX",
                "buffBarDurationOffsetY",
            },
        },
        bars = {
            label = "Buff Bar Settings",
            keys = {
                "buffBarWidth",
                "buffBarHeight",
                "buffBarSpacing",
                "buffBarGrowDirection",
                "buffBarIconPosition",
                "buffBarIconGap",
                "buffBarShowName",
                "buffBarShowDuration",
                "buffBarShowApplications",
                "buffBarApplicationsFontSize",
                "buffBarApplicationsColor",
                "buffBarApplicationsPosition",
                "buffBarApplicationsOffsetX",
                "buffBarApplicationsOffsetY",
                "buffBarTexture",
                "buffBarColor",
                "buffBarBackgroundColor",
                "buffBarDualMode",
            },
        },
        resources = {
            label = "Resource Bar Settings",
            keys = {
                "resourcesEnabled",
                "resourcesTagSettings",
                "resourcesBar1TagFontSize",
                "resourcesBar1TagAnchor",
                "resourcesBar1TagOffsetX",
                "resourcesBar1TagOffsetY",
                "resourcesBar1TagColor",
                "resourcesBar2TagFontSize",
                "resourcesBar2TagAnchor",
                "resourcesBar2TagOffsetX",
                "resourcesBar2TagOffsetY",
                "resourcesBar2TagColor",
                "resourcesBarHeight",
                "resourcesBar2Height",
                "resourcesBarWidth",
                "resourcesBarSpacing",
                "resourcesOffsetX",
                "resourcesOffsetY",
                "resourcesUnifiedBorder",
                "resourcesMoveBuffsDown",
                "resourcesBarTexture",
                "resourcesBarBackgroundTexture",
                "resourcesRageColor",
                "resourcesEnergyColor",
                "resourcesFocusColor",
                "resourcesRunicPowerColor",
                "resourcesLunarPowerColor",
                "resourcesMaelstromColor",
                "resourcesInsanityColor",
                "resourcesFuryColor",
                "resourcesEssenceColor",
                "resourcesEssenceRechargingColor",
                "resourcesSoulShardsColor",
                "resourcesSoulShardsRechargingColor",
                "resourcesHolyPowerColor",
                "resourcesComboPointsColor",
                "resourcesArcaneChargesColor",
                "resourcesRunesReadyColor",
                "resourcesRunesRechargingColor",
                "resourcesChiColor",
                "resourcesSoulFragmentsColor",
                "resourcesBackgroundColor",
                "resourcesStaggerLightColor",
                "resourcesStaggerModerateColor",
                "resourcesStaggerHeavyColor",
                "resourcesManaColor",
                "resourcesManaSettings",
                "resourcesManaPercentage",
            },
        },
        racials = {
            label = "Racials Tracker Settings",
            keys = {
                "racialsEnabled",
                "racialsIconWidth",
                "racialsIconHeight",
                "racialsAnchorPoint",
                "racialsOffsetX",
                "racialsOffsetY",
                "racialsChargeFontSize",
                "racialsCooldownFontSize",
                "racialsChargePosition",
                "racialsChargeOffsetX",
                "racialsChargeOffsetY",
                "racialsUsePartyFrame",
                "racialsPartyFrameSide",
                "racialsPartyFrameOffsetX",
                "racialsPartyFrameOffsetY",
                "racialsChargeColor",
                "racialsCustomEntries",
                "racialsOrderPerSpec",
                "racialsDisabled",
            },
        },
        defensives = {
            label = "Defensives Tracker Settings",
            keys = {
                "defensivesEnabled",
                "defensivesIconWidth",
                "defensivesIconHeight",
                "defensivesAnchorPoint",
                "defensivesOffsetX",
                "defensivesOffsetY",
                "defensivesChargeFontSize",
                "defensivesCooldownFontSize",
                "defensivesChargePosition",
                "defensivesChargeOffsetX",
                "defensivesChargeOffsetY",
                "defensivesDisabledSpells",
                "defensivesCustomSpells",
                "defensivesHideFromViewers",
                "defensivesOrder",
            },
        },
        trinkets = {
            label = "Trinkets Tracker Settings",
            keys = {
                "trinketsEnabled",
                "trinketsIconWidth",
                "trinketsIconHeight",
                "trinketsAnchorPoint",
                "trinketsOffsetX",
                "trinketsOffsetY",
                "trinketsCooldownFontSize",
                "trinketsShowPassive",
                "trinketsMode",
                "trinketsEssentialRow",
                "trinketsEssentialPosition",
            },
        },
        castbar = {
            label = "Cast Bar Settings",
            keys = {
                "castBarEnabled",
                "hideBlizzardCastBar",
                "castBarWidth",
                "castBarHeight",
                "castBarFontSize",
                "castBarShowSpellName",
                "castBarShowTimer",
                "castBarShowSpark",
                "castBarNameOffsetX",
                "castBarNameOffsetY",
                "castBarTimerOffsetX",
                "castBarTimerOffsetY",
                "castBarOffsetX",
                "castBarOffsetY",
                "castBarContainerLocked",
                "castBarAnchorToResources",
                "castBarResourcesSpacing",
                "castBarUseAtlasTextures",
                "castBarTexture",
                "castBarBackgroundTexture",
                "castBarBackgroundColor",
                "castBarCastColor",
                "castBarChannelColor",
                "castBarUninterruptibleColor",
                "castBarEmpowerWindUpColor",
                "castBarEmpowerStage1Color",
                "castBarEmpowerStage2Color",
                "castBarEmpowerStage3Color",
                "castBarEmpowerStage4Color",
                "castBarShowIcon",
                "castBarIconPosition",
                "castBarIconGap",
            },
        },
        glow = {
            label = "Glow Settings",
            keys = {
                "glowType",
                "glowUseCustomColor",
                "glowColor",
                "glowPixelLines",
                "glowPixelFrequency",
                "glowPixelLength",
                "glowPixelThickness",
                "glowPixelXOffset",
                "glowPixelYOffset",
                "glowAutocastParticles",
                "glowAutocastFrequency",
                "glowAutocastScale",
                "glowAutocastXOffset",
                "glowAutocastYOffset",
                "glowButtonFrequency",
                "glowProcDuration",
                "glowProcXOffset",
                "glowProcYOffset",
            },
        },
        assist = {
            label = "Assist Settings",
            keys = {
                "rotationAssistEnabled",
                "rotationAssistGlowRatio",
                "assistEnabled",
                "assistFontSize",
                "assistColor",
                "assistPosition",
                "assistOffsetX",
                "assistOffsetY",
            },
        },
        fading = {
            label = "Fading Settings",
            keys = {
                "fadingEnabled",
                "fadingTrigger",
                "fadingOpacity",
                "fadingEssential",
                "fadingUtility",
                "fadingBuffs",
                "fadingBuffBars",
                "fadingRacials",
                "fadingDefensives",
                "fadingTrinkets",
                "fadingResources",
            },
        },
        positions = {
            label = "Positions & Locking",
            keys = {
                "containerLocked",
                "buffContainerLocked",
                "buffBarContainerLocked",
                "editModePositions",
                "buffSecondaryOffsetX",
                "buffSecondaryOffsetY",
                "buffTertiaryOffsetX",
                "buffTertiaryOffsetY",
            },
        },
        custombuffs = {
            label = "Custom Timers",
            keys = {
                "customBuffRegistry",
            },
        },
    },
}
