local Loc = LibStub("AceLocale-3.0"):NewLocale("Details_EncounterDetails", "zhTW") 

if (not Loc) then
	return 
end 

Loc ["STRING_PLUGIN_NAME"] = "首領戰分析"
Loc ["STRING_WINDOW_TITLE"] = "Details! 首領戰分析"
Loc ["STRING_TOTAL_DAMAGE"] = "總輸出"
Loc ["STRING_TOTAL_HEAL"] = "總治療"
Loc ["STRING_SHOW_ALL_DATA"] = "顯示整體資料"
Loc ["STRING_SHOW_PHASE_DATA"] = "顯示此階段的詳細內容"
Loc ["STRING_NOT IMPLEMENTED"] = "尚未實裝"
Loc ["STRING_DIED"] = "死亡"
Loc ["STRING_MELEE_DAMAGE"] = "近戰傷害"
Loc ["STRING_DAMAGE_TAKEN_REPORT"] = "承受傷害 - "
Loc ["STRING_ABILITY_DAMAGE"] = "技能傷害"
Loc ["STRING_DAMAGE_TAKEN"] = "承受傷害"
Loc ["STRING_TOOK_DAMAGE_FROM"] = "承受傷害來自"
Loc ["STRING_INTERRUPT_BY"] = "斷法 - "
Loc ["STRING_DISPELLED_BY"] = "驅散 - "
Loc ["STRING_DEAD_LOG"] = "最後幾秒 - "
Loc ["STRING_CURRENT"] = "目前"
Loc ["STRING_TRY"] = "戰鬥"
Loc ["STRING_DAMAGE_AT"] = "承受傷害"
Loc ["STRING_INFLICTED_BY"] = "造成傷害 - "
Loc ["STRING_INFLICTED"] = "造成傷害"
Loc ["STRING_ADDS"] = "加入"
Loc ["STRING_INTERRUPTS"] = "斷法"
Loc ["STRING_INTERRUPTS_OF"] = "斷法 - "
Loc ["STRING_DISPELLS_OF"] = "驅散 - "
Loc ["STRING_DISPELLS"] = "驅散"
Loc ["STRING_DEATH_LOG"] = "死亡記錄"
Loc ["STRING_FIGHT_SUMMARY"] = "首領戰總結"
Loc ["STRING_FIGHT_GRAPHIC"] = "首領戰圖表和階段"
Loc ["STRING_FIGHT_EMOTES"] = "首領戰台詞"
Loc ["STRING_FIGHT_SPELLS"] = "首領戰法術和光環"
Loc ["STRING_TOOLTIP"] = "顯示首領戰詳細內容視窗"
Loc ["STRING_LAST_COOLDOWN"] = "最後使用的冷卻"
Loc ["STRING_NOLAST_COOLDOWN"] = "沒有使用的冷卻"

Loc ["STRING_BOSS_NOT_REGISTRED"] = "Details! 沒有登錄這場首領戰。\n請確認在選擇角色畫面的插件控制視窗中有載入這場首領戰。"

Loc ["STRING_HOLDSHIFT"] = "按住 SHIFT 顯示法術說明"

Loc ["STRING_ADDS_HELP"] = "滑鼠指向|cFF00FF00向上箭頭|r\n顯示接收的傷害，|cFFFF0000箭頭\n|cFFFF0000向下|r為處理的傷害。|cFFFFFF00點一下\n|cFFFFFF00箭頭|r: 報告顯示在滑鼠提示中的資料。"
Loc ["STRING_INTERRIPT_HELP"] = " |cFFFFFF00點一下|r計量條:\n打開報告視窗。\n右側會顯示打斷次數與總共唱法了幾次。"
Loc ["STRING_DISPELL_HELP"] = " \n|cFFFFFF00點一下|r計量條:\n打開報告視窗。"
Loc ["STRING_DEATHS_HELP"] = " \n|cFFFFFF00點一下|r計量條:\n打開報告視窗。"

--> mechanic types
Loc ["STRING_HEAL"] = "heal"
Loc ["STRING_LOWDPS"] = "lowdps"
Loc ["STRING_LOWHEAL"] = "lowheal"
Loc ["STRING_VOIDZONE"] = "voidzone"
Loc ["STRING_DISPELL"] = "dispell"
Loc ["STRING_INTERRUPT"] = "interrupt"
Loc ["STRING_POSITIONING"] = "positioning"
Loc ["STRING_RUNAWAY"] = "runaway"
Loc ["STRING_TANKSWITCH"] = "tankswitch"
Loc ["STRING_MECHANIC"] = "mechanic"
Loc ["STRING_CROWDCONTROL"] = "cc"
Loc ["STRING_TANKCOOLDOWN"] = "tankcooldown"
Loc ["STRING_KILLADD"] = "killadd"
Loc ["STRING_SPREADOUT"] = "spreadout"
Loc ["STRING_STOPCAST"] = "stopcast"
Loc ["STRING_FACING"] = "facing"
Loc ["STRING_STACK"] = "stack"

-- 自行加入
-- frames.lua
Loc ["Encounter Breakdown Options"] = "首領戰分析設定選項"
Loc ["Inside Raid"] = "在團隊中"
Loc ["Only show the icon while inside a raid."] = "只有在團隊中時才顯示圖示。"
Loc ["In Group"] = "在隊伍中"
Loc ["Only show the icon while in group."] = "只有在隊伍中時才顯示圖示。"
Loc ["After Encounter"] = "首領戰結束"
Loc ["Show the icon after a raid boss encounter."] = "團隊首領戰結束後顯示圖示。"
Loc ["Always"] = "總是"
Loc ["Always show the icon."] = "永遠顯示圖示。"
Loc ["Auto"] = "自動"
Loc ["The plugin decides when the icon needs to be shown."] = "讓外掛套件自行決定何時要顯示圖示。"
Loc ["Show Icon"] = "顯示圖示"
Loc ["When the icon is shown in the Details! tooltip."] = "何時要在 Details! 滑鼠提示中顯示圖示。"
Loc ["Hide on Combat"] = "戰鬥中隱藏"
Loc ["Encounter Breakdown window automatically close when you enter in combat."] = "進入戰鬥時自動關閉首領戰分析視窗。"
Loc ["Emote Segments Amount"] = "台詞記錄數量"
Loc ["Keep how many segments emotes."] = "要保留多少個台詞記錄。"
Loc ["Window Scale"] = "視窗縮放大小"
Loc ["Set the window size"] = "設定視窗大小。"
Loc ["Unknown Raid"] = "未知的團隊"
Loc ["Unknown Encounter"] = "未知的首領戰"
Loc ["Summary"] = "總結"
Loc ["Phases"] = "階段"
Loc ["Damage Graphic"] = "傷害圖表"
Loc ["Emotes"] = "台詞"
Loc ["Options"] = "設定選項"
Loc ["macro"] = "巨集"

-- Details_EncounterDetails.lua
Loc ["Raid encounters summary, show basic stuff like dispels, interrupts and also graphic charts, boss emotes and the Weakaura Creation Tool."] = "團隊首領戰的總結，顯示像是驅散、斷法...等的基本內容，還包含了圖表、首領台詞、和 WA 技能提醒的建立工具。"
Loc ["Encounter Breakdown"] = "首領戰分析"
Loc ["Raid Damage Done"] = "團隊輸出傷害"
Loc ["Encounter Details"] = "首領戰詳細內容"
Loc ["Encounter Summary"] = "首領戰總結"
-- Loc ["Damage Graphic"] = "傷害圖表" -- 前面已有
Loc ["Boss Emotes"] = "首領台詞"
Loc ["Damage by Boss Phase"] = "首領各階段傷害"
Loc ["Click to Report"] = "點一下發送報告"
Loc [" |cFFFF8800overkill|r)"] = " |cFFFF8800溢傷|r)"

-- frames_auras.lua -- 更改字體大小
Loc ["event:"] = "事件:"
Loc ["source:"] = "來源:"
Loc ["school:"] = "屬性:"
Loc ["aura type:"] = "光環類型:"
Loc ["Boss Mods Time Bars:"] = "首領模組計時條:"
Loc ["Boss Spells and Auras:"] = "省領技能和光環:"
Loc ["info"] = "資訊"
Loc ["Make Aura"] = "製作提醒效果"
Loc ["Next "] = "下一個是 "
Loc [" In"] = " 於"


-- frames_chart.lua -- 更改字體大小
Loc ["phases:"] = "階段:"
Loc ["This segment doesn't have chart data."] = "此戰鬥記錄沒有圖表資料。"
Loc ["Damage Done:"] = "輸出傷害:"
Loc ["Healing Done:"] = "造成治療:"
Loc ["|cFFffb400Left Click|r: Report Damage |cFFffb400Right Click|r: Report Heal"] = "|cFFffb400左鍵|r: 報告輸出傷害 |cFFffb400右鍵|r: 報告治療"
Loc ["Details!: Damage for Phase "] = "Details!: 輸出傷害 來自 階段 "
Loc [" of "] = " - "
Loc ["Unknown"] = "未知"
Loc ["Details!: Healing for Phase "] = "Details!: 治療 來自 階段 "
Loc ["|cFFffb400Phase|r: "] = "|cFFffb400階段|r: "
Loc ["|cFFffb400Elapsed|r: "] = "|cFFffb400時間|r: "
Loc ["m "] = " 分 "
Loc ["s"] = " 秒"
Loc ["Phase out of range:"] = "超出範圍階段:"

-- frames_emote.lua -- 更改字體大小
Loc ["Found "] = "找到 "
Loc [" matches"] = " 個符合結果"
Loc ["m"] = " 分 "
Loc ["s:"] = " 秒:"
Loc ["Details! Encounter Emote at "] = "Details! 首領戰台詞於 "
Loc ["Segment:"] = "戰鬥記錄:"
Loc ["unknown"] = "未知"
Loc ["Search:"] = "搜尋:"
Loc ["Details!: Emotes for "] = "Details!: 台詞 來自 "
Loc ["There is nothing to report."] = "沒有東西可供報告。"
Loc ["Report Results"] = "報告結果"
Loc ["|cFFffb400Left Click|r: Report Line"] = "|cFFffb400點一下|r: 報告這行"

-- frames_phases.lua -- 更改字體大小
Loc ["Select Phase:"] = "選擇階段:"
Loc ["Damage Done"] = "輸出傷害"
Loc ["Healing Done"] = "造成治療"
Loc ["Time Spent on Each Phase"] = "每個階段花費的時間"
-- Loc ["Details!: Damage for Phase "] = "Details!: 輸出傷害 來自 階段 " -- 前面已有
-- Loc [" of "] = " - "
-- Loc ["Unknown"] = "未知"
-- Loc ["Details!: Healing for Phase "] = "Details!: 治療 來自 階段 "
Loc ["report"] = "報告"
Loc ["|cFFC0C0C0Phase:|r |cFFFFFFFF"] = "|cFFC0C0C0階段:|r |cFFFFFFFF"
Loc ["Segment "] = "戰鬥記錄 "

-- frames_summary.lua
Loc ["Damage Taken by Spell"] = "承受傷害的技能"
Loc ["Enemy Damage Taken"] = "敵方承受傷害"
Loc["Player Damage Taken"] = "玩家承受傷害"
Loc ["Interrupts"] = "斷法"
Loc ["Dispels"] = "驅散"
Loc ["Deaths"] = "死亡"
-- Loc [" |cFFFF8800overkill|r)"] = " |cFFFF8800溢傷|r)" -- 前面已有