local addonName, addon = ...
addon.language = addon.language or {}
local lang = addon.language

local locale = GetLocale()
--if locale ~= "enUS" and locale ~= "enGB" then return end

lang["difficulty.normal"] = "Normal"
lang["difficulty.heroic"] = "Heroic"
lang["difficulty.mythic"] = "Mythic"
lang["difficulty.mythicplus"] = "Mythic+"

lang["expl.simple"] = "Check the box, and input the maximum value and (or) the minimum value."
lang["expl.state"] = "The team must have:" 
lang["expl.min"] = "Min"
lang["expl.max"] = "Max"
lang["expl.advanced"] = "Extras"
lang["dialog.difficulty"] = "Difficulty ..........................."
lang["dialog.dungeon"] = "Dungeon/Area ..........................."
lang["dialog.createtime"] = "CreateTime(sec) ..........................."
lang["dialog.negate"] = "Class Exclude"
lang["dialog.class"] = "Class Included(at least one)................"
lang["dialog.class_off"] = "Class Excluded(at least one)................"
lang["dialog.showinfo"] = "ShowInfo....................."
lang["dialog.ilvl"] = "Item Level ....................."
lang["dialog.mythicscore"] = "Mythic+ Score ....................."
lang["dialog.defeated"] = "Bosses Defeated ......................"
lang["dialog.pvprating"] = "PVP Score ......................"
lang["dialog.members"] = "Members ....................."
lang["dialog.tanks"] = "Tanks ..........................."
lang["dialog.heals"] = "Healer ..........................."
lang["dialog.dps"] = "DPS ..........................."
lang["dialog.to"] = "to"
lang["dialog.unselect"] = "Unselected"
lang["dialog.resetmenu"] = "|cFF00FF00Reset Menu|r"
lang["dialog.showclassinfo"] = "Show the class icon"
lang["dialog.showclassbar"] = "Show the class color"
lang["dialog.showservername"] = "Show the servername"
lang["dialog.showleaderscore"] = "Show the leaderscores"
lang["dialog.showleaderraidprocess"] = "Show the RaidProcess"
lang["dialog.shortcutoption"] = "Shortcut Options....................."
lang["dialog.quicksingnup"] = "Double click for quick signup " 
lang["dialog.autorolecheck"] = "Automatic role confirm"
lang["dialog.autoacceptinvite"] = "Automatically accept invitation"
lang["dialog.autoinviteapplicate"] = "Automatically invite applicants"
lang["dialog.resetbutton"] = "Reset"
lang["dialog.searchbutton"] = "Research"
lang["dialog.ignore.title"] = "Black List"
lang["dialog.ignore.total"] = "Total number on the black list: "
lang["dialog.ignore.clearbutton"] = "Clear the list"
lang["dialog.ignore.clearall"] = "Are you sure you want to clear out the black list?"

lang["dialog.order.score"] = "Highest score first"
lang["dialog.order.time"] = "Creation time come first"
lang["dialog.order.lessprocess"] = "Less kills come first"
lang["dialog.order.moreprocess"] = "Most kills come first"
lang["dialog.order.default"] = "Default Order"
lang["dialog.order"] = "Order Setting................................"

lang["Tank"] = "Tank"
lang["Healer"] = "Healer"
lang["DPS"] = "DPS"