local addonName, addon = ...
addon.language = addon.language or {}
local lang = addon.language

local locale = GetLocale()
if locale ~= "zhCN" then return end

lang["difficulty.normal"] = "普通"
lang["difficulty.heroic"] = "英雄"
lang["difficulty.mythic"] = "史诗"
lang["difficulty.mythicplus"] = "史诗钥石"

lang["expl.simple"] = "勾选选项，输入最大值和(或)最小值。"
lang["expl.state"] = "队伍中必须包含"
lang["expl.min"] = "最小值"
lang["expl.max"] = "最大值"
lang["expl.advanced"] = "额外设置"
lang["dialog.difficulty"] = "难度 ..........................."
lang["dialog.dungeon"] = "副本/区域 ..........................."
lang["dialog.createtime"] = "创建时间(秒) ..........................."
lang["dialog.negate"] = "不包含职业"
lang["dialog.class"] = "包含职业(其一)................"
lang["dialog.class_off"] = "不包含职业(其一)................"
lang["dialog.showinfo"] = "显示信息....................."
lang["dialog.ilvl"] = "装备等级 ....................."
lang["dialog.mythicscore"] = "钥石评分 ....................."
lang["dialog.defeated"] = "已击败首领 ......................"
lang["dialog.pvprating"] = "PVP等级 ......................"
lang["dialog.hlvl"] = "荣誉等级 ...................."
lang["dialog.members"] = "队伍人数 ....................."
lang["dialog.tanks"] = "坦克 ..........................."
lang["dialog.heals"] = "治疗 ..........................."
lang["dialog.dps"] = "输出 ..........................."
lang["dialog.to"] = "～"
lang["dialog.unselect"] = "未选择"
lang["dialog.resetmenu"] = "|cFF00FF00重置选项|r"
lang["dialog.showclassinfo"] = "显示队伍职业图标"
lang["dialog.showclassbar"] = "显示队伍职业颜色"
lang["dialog.showservername"] = "显示队长服务器"
lang["dialog.showleaderscore"] = "显示队长分数"
lang["dialog.showleaderraidprocess"] = "显示队长进度"
lang["dialog.shortcutoption"] = "快捷选项....................."
lang["dialog.quicksingnup"] = "双击快速申请"
lang["dialog.autorolecheck"] = "自动职责确认"
lang["dialog.autoacceptinvite"] = "自动接受邀请"
lang["dialog.autoinviteapplicate"] = "自动邀请申请者"
lang["dialog.resetbutton"] = "重置选项"
lang["dialog.searchbutton"] = "重新搜索"
lang["dialog.ignore.title"] = "屏蔽列表"
lang["dialog.ignore.total"] = "屏蔽数量："
lang["dialog.ignore.clearbutton"] = "清空列表"
lang["dialog.ignore.clearall"] = "确认要删除所有的屏蔽项吗？"

lang["dialog.order.score"] = "评分高的在前"
lang["dialog.order.time"] = "创建时间短的在前"
lang["dialog.order.lessprocess"] = "击杀数量少的在前"
lang["dialog.order.moreprocess"] = "击杀数量多的在前"
lang["dialog.order.default"] = "默认排序规则"
lang["dialog.order"] = "排序规则..................................."

lang["Tank"] = "坦克"
lang["Healer"] = "治疗"
lang["DPS"] = "伤害输出"
--[[
lang["dialog.tooltip.difficulty"] = "选择想要筛选的副本难度"
lang["dialog.tooltip.dungeon"] = "选择想要筛选的地区或副本"
lang["dialog.tooltip.class"] = "队伍中必须包含某个职业（多选）"
lang["dialog.tooltip.ilvl"] = "筛选队伍的装备等级限制"
lang["dialog.tooltip.mythicscore"] = "钥匙评分 ....................."
lang["dialog.tooltip.defeated"] = "已击败首领 ......................"
lang["dialog.tooltip.hlvl"] = "荣誉等级 ...................."
lang["dialog.tooltip.members"] = "队伍人数 ....................."
lang["dialog.tooltip.tanks"] = "坦克 ..........................."
lang["dialog.tooltip.heals"] = "治疗 ..........................."
lang["dialog.tooltip.dps"] = "输出 ..........................."
lang["dialog.tooltip.showinfo"] = "显示信息....................."
lang["dialog.tooltip.shortcutoption"] = "快捷选项....................."
]]