local LSM = LibStub("LibSharedMedia-3.0") 

-- ----- 
-- BACKGROUND 
-- ----- 

-- ----- 
--  BORDER 
-- ---- 

-- -----
--   FONT
-- -----

-- -----
--   SOUND
-- -----

LSM:Register("sound", "|cFFFF00CD01|r", [[Interface\Addons\SharedMedia_Saha\sound\1.ogg]])
LSM:Register("sound", "|cFFFF00CD02|r", [[Interface\Addons\SharedMedia_Saha\sound\2.ogg]])
LSM:Register("sound", "|cFFFF00CD03|r", [[Interface\Addons\SharedMedia_Saha\sound\3.ogg]])
LSM:Register("sound", "|cFFFF00CD04|r", [[Interface\Addons\SharedMedia_Saha\sound\4.ogg]])
LSM:Register("sound", "|cFFFF00CD05|r", [[Interface\Addons\SharedMedia_Saha\sound\5.ogg]])
LSM:Register("sound", "|cFFFF00CD06|r", [[Interface\Addons\SharedMedia_Saha\sound\6.ogg]])
LSM:Register("sound", "|cFFFF00CD07|r", [[Interface\Addons\SharedMedia_Saha\sound\7.ogg]])
LSM:Register("sound", "|cFFFF00CD08|r", [[Interface\Addons\SharedMedia_Saha\sound\8.ogg]])
LSM:Register("sound", "|cFFFF00CD09|r", [[Interface\Addons\SharedMedia_Saha\sound\9.ogg]])
LSM:Register("sound", "|cFFFF00CD10|r", [[Interface\Addons\SharedMedia_Saha\sound\10.ogg]])
LSM:Register("sound", "|cFFFF00CD11|r", [[Interface\Addons\SharedMedia_Saha\sound\11.ogg]])

--小怪
LSM:Register("sound", "|cFFFF00CD小怪_5層吞食|r", [[Interface\Addons\SharedMedia_Saha\sound\小怪_5層吞食.mp3]])
LSM:Register("sound", "|cFFFF00CD小怪_小怪增傷|r", [[Interface\Addons\SharedMedia_Saha\sound\小怪_小怪增傷.mp3]])
LSM:Register("sound", "|cFFFF00CD小怪_怪群增傷|r", [[Interface\Addons\SharedMedia_Saha\sound\小怪_怪群增傷.mp3]])
LSM:Register("sound", "|cFFFF00CD小怪_準備小怪氣噗噗|r", [[Interface\Addons\SharedMedia_Saha\sound\小怪_準備小怪氣噗噗.mp3]])

--分散
LSM:Register("sound", "|cFFFF00CD分散_5碼分散|r", [[Interface\Addons\SharedMedia_Saha\sound\分散_5碼分散.mp3]])
LSM:Register("sound", "|cFFFF00CD分散_8碼分散|r", [[Interface\Addons\SharedMedia_Saha\sound\分散_8碼分散.mp3]])
LSM:Register("sound", "|cFFFF00CD分散_快分散|r", [[Interface\Addons\SharedMedia_Saha\sound\分散_快分散.ogg]])
LSM:Register("sound", "|cFFFF00CD分散_震地分散|r", [[Interface\Addons\SharedMedia_Saha\sound\分散_震地分散.mp3]])
LSM:Register("sound", "|cFFFF00CD分散_準備分散|r", [[Interface\Addons\SharedMedia_Saha\sound\分散_準備分散.mp3]])

--分攤
LSM:Register("sound", "|cFFFF00CD分攤_火焰分傷|r", [[Interface\Addons\SharedMedia_Saha\sound\分攤_火焰分傷.ogg]])
LSM:Register("sound", "|cFFFF00CD分攤_找人分攤|r", [[Interface\Addons\SharedMedia_Saha\sound\分攤_找人分攤.ogg]])
LSM:Register("sound", "|cFFFF00CD分攤_物理分傷|r", [[Interface\Addons\SharedMedia_Saha\sound\分攤_物理分傷.ogg]])
LSM:Register("sound", "|cFFFF00CD分攤_衝鋒擋線分傷|r", [[Interface\Addons\SharedMedia_Saha\sound\分攤_衝鋒擋線分傷.mp3]])
LSM:Register("sound", "|cFFFF00CD分攤_擋線分傷|r", [[Interface\Addons\SharedMedia_Saha\sound\分攤_擋線分傷.mp3]])
LSM:Register("sound", "|cFFFF00CD分攤_幫忙分攤|r", [[Interface\Addons\SharedMedia_Saha\sound\分攤_幫忙分攤.mp3]])
LSM:Register("sound", "|cFFFF00CD分攤_魔法分傷|r", [[Interface\Addons\SharedMedia_Saha\sound\分攤_魔法分傷.ogg]])

--方向
LSM:Register("sound", "|cFFFF00CD方向_中間|r", [[Interface\Addons\SharedMedia_Saha\sound\方向_中間.ogg]])
LSM:Register("sound", "|cFFFF00CD方向_右邊|r", [[Interface\Addons\SharedMedia_Saha\sound\方向_右邊.ogg]])
LSM:Register("sound", "|cFFFF00CD方向_左邊|r", [[Interface\Addons\SharedMedia_Saha\sound\方向_左邊.ogg]])
LSM:Register("sound", "|cFFFF00CD方向_快轉身|r", [[Interface\Addons\SharedMedia_Saha\sound\方向_快轉身.mp3]])

--打斷
LSM:Register("sound", "|cFFFF00CD打斷_反抗鐵拳必須打斷|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_反抗鐵拳 必須打斷.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_必須打斷|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_必須打斷.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_打斷心控|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_打斷心控.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_打斷吞食|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_打斷吞食.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_打斷沉睡|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_打斷沉睡.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_打斷定身|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_打斷定身.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_打斷恐懼|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_打斷恐懼.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_打斷減傷|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_打斷減傷.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_打斷增傷|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_打斷增傷.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_打斷增傷詛咒|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_打斷增傷詛咒.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_打斷護盾|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_打斷護盾.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_尖刺鐐銬必須打斷|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_尖刺鐐銬必須打斷.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_死靈箭雨必須打斷|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_死靈箭雨必須打斷.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快打斷|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快打斷.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快打斷妖術|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快打斷妖術.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快打斷抽取法力|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快打斷抽取法力.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快打斷凋萎釋放|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快打斷凋萎釋放.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快打斷強力群補|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快打斷強力群補.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快打斷強力補血|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快打斷強力補血.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快打斷強迫自白|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快打斷強迫自白.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快打斷強效療癒|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快打斷強效療癒.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快打斷禁制詛咒|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快打斷禁制詛咒.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快打斷群補|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快打斷群補.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快打斷補血|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快打斷補血.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快打斷穢邪狂熱|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快打斷穢邪狂熱.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快恐懼打斷|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快恐懼打斷.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快控場|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快控場.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快控場打斷|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快控場打斷.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快擊退打斷|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快擊退打斷.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_快擊暈打斷|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_快擊暈打斷.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_骨矛必須打斷|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_骨矛必須打斷.mp3]])
LSM:Register("sound", "|cFFFF00CD打斷_停止施法|r", [[Interface\Addons\SharedMedia_Saha\sound\打斷_停止施法.ogg]])

--生成
LSM:Register("sound", "|cFFFF00CD生成_6秒後AOE出小怪|r", [[Interface\Addons\SharedMedia_Saha\sound\生成_6秒後AOE出小怪.mp3]])
LSM:Register("sound", "|cFFFF00CD生成_出去放水出小怪|r", [[Interface\Addons\SharedMedia_Saha\sound\生成_出去放水出小怪.mp3]])
LSM:Register("sound", "|cFFFF00CD生成_召喚小怪|r", [[Interface\Addons\SharedMedia_Saha\sound\生成_召喚小怪.mp3]])
LSM:Register("sound", "|cFFFF00CD生成_注意寶珠|r", [[Interface\Addons\SharedMedia_Saha\sound\生成_注意寶珠.ogg]])
LSM:Register("sound", "|cFFFF00CD生成_復生大怪|r", [[Interface\Addons\SharedMedia_Saha\sound\生成_復生大怪.mp3]])
LSM:Register("sound", "|cFFFF00CD生成_復生小怪|r", [[Interface\Addons\SharedMedia_Saha\sound\生成_復生小怪.mp3]])
LSM:Register("sound", "|cFFFF00CD生成_準備小怪|r", [[Interface\Addons\SharedMedia_Saha\sound\生成_準備小怪.ogg]])
LSM:Register("sound", "|cFFFF00CD生成_準備恐懼小怪|r", [[Interface\Addons\SharedMedia_Saha\sound\生成_準備恐懼小怪.ogg]])
LSM:Register("sound", "|cFFFF00CD生成_準備蟲群|r", [[Interface\Addons\SharedMedia_Saha\sound\生成_準備蟲群.mp3]])
LSM:Register("sound", "|cFFFF00CD生成_靈魂看你快跑|r", [[Interface\Addons\SharedMedia_Saha\sound\生成_靈魂看你快跑.mp3]])

--光束
LSM:Register("sound", "|cFFFF00CD光束_注意光束|r", [[Interface\Addons\SharedMedia_Saha\sound\光束_注意光束.ogg]])
LSM:Register("sound", "|cFFFF00CD光束_注意連線|r", [[Interface\Addons\SharedMedia_Saha\sound\光束_注意連線.ogg]])

--快躲
LSM:Register("sound", "|cFFFF00CD快躲_小心躲好|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_小心躲好.ogg]])
LSM:Register("sound", "|cFFFF00CD快躲_火炮彈幕|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_火炮彈幕.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_火砲彈幕找掩體|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_火砲彈幕找掩體.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_王前半場衝擊波|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_王前半場衝擊波.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_王前直線衝擊波|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_王前直線衝擊波.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_王前範圍斬擊|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_王前範圍斬擊.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_正面順劈|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_正面順劈.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_安全安全|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_安全安全.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_別靠近坦克|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_別靠近坦克.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_快進安全區|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_快進安全區.ogg]])
LSM:Register("sound", "|cFFFF00CD快躲_快進罩子|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_快進罩子.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_快躲好|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_快躲好.ogg]])
LSM:Register("sound", "|cFFFF00CD快躲_快躲開|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_快躲開.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_注意正面|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_注意正面.ogg]])
LSM:Register("sound", "|cFFFF00CD快躲_注意地板黑圈|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_注意地板黑圈.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_注意殘影|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_注意殘影.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_注意順劈|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_注意順劈.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_注意腳下|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_注意腳下.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_注意躲圈|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_注意躲圈.ogg]])
LSM:Register("sound", "|cFFFF00CD快躲_注意躲開|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_注意躲開.ogg]])
LSM:Register("sound", "|cFFFF00CD快躲_注意衝鋒路徑|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_注意衝鋒路徑.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_注意衝擊波|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_注意衝擊波.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_注意龍捲風|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_注意龍捲風.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_注意爆炸|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_注意爆炸.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_風箏|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_風箏.ogg]])
LSM:Register("sound", "|cFFFF00CD快躲_旋風斬快躲|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_旋風斬快躲.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_黑球爆發|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_黑球爆發.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_準備躲長矛|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_準備躲長矛.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_躲光圈|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_躲光圈.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_躲後面|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_躲後面.ogg]])
LSM:Register("sound", "|cFFFF00CD快躲_躲紅圈|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_躲紅圈.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_躲紫圈|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_躲紫圈.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_躲開正面|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_躲開正面.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_躲開正面扇形|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_躲開正面扇形.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_躲開光彈|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_躲開光彈.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_躲開黃圈|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_躲開黃圈.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_躲開黑球|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_躲開黑球.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_躲開衝鋒|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_躲開衝鋒.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_躲綠圈|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_躲綠圈.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_躲藍圈|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_躲藍圈.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_遠離旋風|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_遠離旋風.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_遠離連線|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_遠離連線.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_衝鋒快躲|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_衝鋒快躲.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_衝鋒帶去撞王|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_衝鋒帶去撞王.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_衝鋒帶去撞牆|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_衝鋒帶去撞牆.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_衝鋒點你快躲開|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_衝鋒點你 快躲開.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_骸骨尖刺注意閃地板|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_骸骨尖刺注意閃地板.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_骸骨風暴快逃|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_骸骨風暴快逃.mp3]])
LSM:Register("sound", "|cFFFF00CD快躲_龍捲風|r", [[Interface\Addons\SharedMedia_Saha\sound\快躲_龍捲風.mp3]])

--坦克
LSM:Register("sound", "|cFFFF00CD坦克_王增傷|r", [[Interface\Addons\SharedMedia_Saha\sound\坦克_王增傷.mp3]])
LSM:Register("sound", "|cFFFF00CD坦克_快貼王不要離開|r", [[Interface\Addons\SharedMedia_Saha\sound\坦克_快貼王不要離開.mp3]])
LSM:Register("sound", "|cFFFF00CD坦克_快貼近怪|r", [[Interface\Addons\SharedMedia_Saha\sound\坦克_快貼近怪.mp3]])
LSM:Register("sound", "|cFFFF00CD坦克_快開減傷防回血|r", [[Interface\Addons\SharedMedia_Saha\sound\坦克_快開減傷防回血.mp3]])
LSM:Register("sound", "|cFFFF00CD坦克_快嘲諷|r", [[Interface\Addons\SharedMedia_Saha\sound\坦克_快嘲諷.ogg]])
LSM:Register("sound", "|cFFFF00CD坦克_把王拉開|r", [[Interface\Addons\SharedMedia_Saha\sound\坦克_把王拉開.mp3]])
LSM:Register("sound", "|cFFFF00CD坦克_拉開王|r", [[Interface\Addons\SharedMedia_Saha\sound\坦克_拉開王.mp3]])
LSM:Register("sound", "|cFFFF00CD坦克_注意減傷|r", [[Interface\Addons\SharedMedia_Saha\sound\坦克_注意減傷.mp3]])
LSM:Register("sound", "|cFFFF00CD坦克_抹滅|r", [[Interface\Addons\SharedMedia_Saha\sound\坦克_首創者的守護者_抹滅.mp3]])
LSM:Register("sound", "|cFFFF00CD坦克_碎裂|r", [[Interface\Addons\SharedMedia_Saha\sound\坦克_首創者的守護者_碎裂.mp3]])
LSM:Register("sound", "|cFFFF00CD坦克_閃躲招架格擋失效|r", [[Interface\Addons\SharedMedia_Saha\sound\坦克_閃躲招架格擋失效.mp3]])
LSM:Register("sound", "|cFFFF00CD坦克_連續攻擊準備|r", [[Interface\Addons\SharedMedia_Saha\sound\坦克_連續攻擊準備.mp3]])
LSM:Register("sound", "|cFFFF00CD坦克_敗壞之刃|r", [[Interface\Addons\SharedMedia_Saha\sound\坦克_靈魂撕裂者多瑪讚_敗壞之刃.mp3]])

--放水
LSM:Register("sound", "|cFFFF00CD放水_出去放水|r", [[Interface\Addons\SharedMedia_Saha\sound\放水_出去放水.ogg]])
LSM:Register("sound", "|cFFFF00CD放水_出去放刺|r", [[Interface\Addons\SharedMedia_Saha\sound\放水_出去放刺.mp3]])
LSM:Register("sound", "|cFFFF00CD放水_出去靠近放球|r", [[Interface\Addons\SharedMedia_Saha\sound\放水_出去靠近放球.mp3]])
LSM:Register("sound", "|cFFFF00CD放水_快出去放陷阱|r", [[Interface\Addons\SharedMedia_Saha\sound\放水_快出去放陷阱.mp3]])
LSM:Register("sound", "|cFFFF00CD放水_注意陷阱|r", [[Interface\Addons\SharedMedia_Saha\sound\放水_注意陷阱.ogg]])
LSM:Register("sound", "|cFFFF00CD放水_集合放球|r", [[Interface\Addons\SharedMedia_Saha\sound\放水_集合放球.mp3]])
LSM:Register("sound", "|cFFFF00CD放水_準備黑水|r", [[Interface\Addons\SharedMedia_Saha\sound\放水_準備黑水.mp3]])
LSM:Register("sound", "|cFFFF00CD放水_遠離王放球|r", [[Interface\Addons\SharedMedia_Saha\sound\放水_遠離王放球.mp3]])
LSM:Register("sound", "|cFFFF00CD放水_靠近放球|r", [[Interface\Addons\SharedMedia_Saha\sound\放水_靠近放球.mp3]])
LSM:Register("sound", "|cFFFF00CD放水_邊邊放火|r", [[Interface\Addons\SharedMedia_Saha\sound\放水_邊邊放火.mp3]])

--狀態
LSM:Register("sound", "|cFFFF00CD狀態_DOT注意血量|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_DOT注意血量.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_上鉤DOT開減傷|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_上鉤DOT開減傷.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_大怪增傷|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_大怪增傷.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_小心層數|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_小心層數.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_不可再分攤|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_不可再分攤.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_不可再吃線|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_不可再吃線.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_不可再吃環|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_不可再吃環.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_加速buff|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_加速buff.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_加速下降|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_加速下降.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_加速光環|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_加速光環.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_回血回魔|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_回血回魔.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_你被沉默|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_你被沉默.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_你被定身|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_你被定身.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_你被易傷|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_你被易傷.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_你被流血|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_你被流血.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_你被強化|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_你被強化.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_你被傳送|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_你被傳送.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_你被緩速|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_你被緩速.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_免疫|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_免疫.ogg]])
LSM:Register("sound", "|cFFFF00CD狀態_免疫結束|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_免疫結束.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_快驅散|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_快驅散.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_沒斷到隊長降傷50%|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_沒斷到隊長降傷50%.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_受到治療下降|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_受到治療下降.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_受傷共享|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_受傷共享.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_易傷結束|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_易傷結束.ogg]])
LSM:Register("sound", "|cFFFF00CD狀態_注意心控|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_注意心控.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_降主屬debuff|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_降主屬debuff.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_降血量debuff|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_降血量debuff.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_降傷debuff|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_降傷debuff.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_凋萎荒疫傷害治療下降|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_凋萎荒疫傷害治療下降.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_荒寂詛咒|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_荒寂詛咒.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_偷取法術|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_偷取法術.ogg]])
LSM:Register("sound", "|cFFFF00CD狀態_被鎖定|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_被鎖定.ogg]])
LSM:Register("sound", "|cFFFF00CD狀態_連線DOT開減傷|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_連線DOT開減傷.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_最大血量下降|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_最大血量下降.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_減益|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_減益.ogg]])
LSM:Register("sound", "|cFFFF00CD狀態_減傷65%|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_減傷65%.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_詛咒|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_詛咒.ogg]])
LSM:Register("sound", "|cFFFF00CD狀態_超痛DOT|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_超痛DOT.ogg]])
LSM:Register("sound", "|cFFFF00CD狀態_超痛DOT開減傷|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_超痛DOT開減傷.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_進圈消層|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_進圈消層.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_傷害治療上升|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_傷害治療上升.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_準備恐懼|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_準備恐懼.ogg]])
LSM:Register("sound", "|cFFFF00CD狀態_準備隨機增益|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_準備隨機增益.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_漸強AOE|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_漸強AOE.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_增益|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_增益.ogg]])
LSM:Register("sound", "|cFFFF00CD狀態_增傷buff|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_增傷buff.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_層數過高|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_層數過高.ogg]])
LSM:Register("sound", "|cFFFF00CD狀態_緩速光環|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_緩速光環.mp3]])
LSM:Register("sound", "|cFFFF00CD狀態_護甲下降|r", [[Interface\Addons\SharedMedia_Saha\sound\狀態_護甲下降.mp3]])

--特殊
LSM:Register("sound", "|cFFFF00CD特殊_黑暗闊步注意黑球|r", [[Interface\Addons\SharedMedia_Saha\sound\特殊_黑暗闊步注意黑球.mp3]])

--移動
LSM:Register("sound", "|cFFFF00CD移動_出去|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_出去.ogg]])
LSM:Register("sound", "|cFFFF00CD移動_快跑|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_快跑.ogg]])
LSM:Register("sound", "|cFFFF00CD移動_快跑遠|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_快跑遠.mp3]])
LSM:Register("sound", "|cFFFF00CD移動_快進人群|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_快進人群.mp3]])
LSM:Register("sound", "|cFFFF00CD移動_快進去|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_快進去.ogg]])
LSM:Register("sound", "|cFFFF00CD移動_快跳快跳|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_快跳快跳.mp3]])
LSM:Register("sound", "|cFFFF00CD移動_快離開|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_快離開.ogg]])
LSM:Register("sound", "|cFFFF00CD移動_快離開釘刺|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_快離開釘刺.mp3]])
LSM:Register("sound", "|cFFFF00CD移動_保持移動|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_保持移動.mp3]])
LSM:Register("sound", "|cFFFF00CD移動_停止移動|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_停止移動.ogg]])
LSM:Register("sound", "|cFFFF00CD移動_停止跳躍|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_停止跳躍.mp3]])
LSM:Register("sound", "|cFFFF00CD移動_進入力場|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_進入力場.mp3]])
LSM:Register("sound", "|cFFFF00CD移動_進去|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_進去.ogg]])
LSM:Register("sound", "|cFFFF00CD移動_準備拉扯|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_準備拉扯.mp3]])
LSM:Register("sound", "|cFFFF00CD移動_準備跳下去|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_準備跳下去.mp3]])
LSM:Register("sound", "|cFFFF00CD移動_準備跳坑|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_準備跳坑.mp3]])
LSM:Register("sound", "|cFFFF00CD移動_準備躲罩子|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_準備躲罩子.mp3]])
LSM:Register("sound", "|cFFFF00CD移動_碎片集合|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_碎片集合.mp3]])
LSM:Register("sound", "|cFFFF00CD移動_遠離人群|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_遠離人群.mp3]])
LSM:Register("sound", "|cFFFF00CD移動_遠離人群爆炸|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_遠離人群爆炸.mp3]])
LSM:Register("sound", "|cFFFF00CD移動_遠離王|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_遠離王.mp3]])
LSM:Register("sound", "|cFFFF00CD移動_調整站位|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_調整站位.mp3]])
LSM:Register("sound", "|cFFFF00CD移動_靠近|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_靠近.ogg]])
LSM:Register("sound", "|cFFFF00CD移動_離開人群|r", [[Interface\Addons\SharedMedia_Saha\sound\移動_離開人群.ogg]])

--減傷
LSM:Register("sound", "|cFFFF00CD減傷_這個圈超痛快開減傷|r", [[Interface\Addons\SharedMedia_Saha\sound\減傷_這個圈超痛快開減傷.mp3]])

--階段
LSM:Register("sound", "|cFFFF00CD階段_快點快點|r", [[Interface\Addons\SharedMedia_Saha\sound\階段_快點快點.ogg]])
LSM:Register("sound", "|cFFFF00CD階段_第二階段|r", [[Interface\Addons\SharedMedia_Saha\sound\階段_第二階段.ogg]])
LSM:Register("sound", "|cFFFF00CD階段_第三階段|r", [[Interface\Addons\SharedMedia_Saha\sound\階段_第三階段.ogg]])
LSM:Register("sound", "|cFFFF00CD階段_階段轉換 注意殘影|r", [[Interface\Addons\SharedMedia_Saha\sound\階段_階段轉換 注意殘影.mp3]])
LSM:Register("sound", "|cFFFF00CD階段_轉階段準備|r", [[Interface\Addons\SharedMedia_Saha\sound\階段_轉階段準備.ogg]])

--準備
LSM:Register("sound", "|cFFFF00CD準備_4秒後AOE|r", [[Interface\Addons\SharedMedia_Saha\sound\準備_4秒後AOE.mp3]])
LSM:Register("sound", "|cFFFF00CD準備_AOE|r", [[Interface\Addons\SharedMedia_Saha\sound\準備_AOE.ogg]])
LSM:Register("sound", "|cFFFF00CD準備_一秒後AOE|r", [[Interface\Addons\SharedMedia_Saha\sound\準備_一秒後AOE.mp3]])
LSM:Register("sound", "|cFFFF00CD準備_光圈|r", [[Interface\Addons\SharedMedia_Saha\sound\準備_光圈.mp3]])
LSM:Register("sound", "|cFFFF00CD準備_迅捷打擊準備|r", [[Interface\Addons\SharedMedia_Saha\sound\準備_迅捷打擊準備.mp3]])
LSM:Register("sound", "|cFFFF00CD準備_無雙亂舞|r", [[Interface\Addons\SharedMedia_Saha\sound\準備_無雙亂舞.mp3]])
LSM:Register("sound", "|cFFFF00CD準備_準備躲鉤子|r", [[Interface\Addons\SharedMedia_Saha\sound\準備_準備躲鉤子.mp3]])
LSM:Register("sound", "|cFFFF00CD準備_碎片|r", [[Interface\Addons\SharedMedia_Saha\sound\準備_碎片.mp3]])

--補師
LSM:Register("sound", "|cFFFF00CD補師_受到治療被吸收|r", [[Interface\Addons\SharedMedia_Saha\sound\補師_受到治療被吸收.mp3]])
LSM:Register("sound", "|cFFFF00CD補師_治療|r", [[Interface\Addons\SharedMedia_Saha\sound\補師_治療.ogg]])
LSM:Register("sound", "|cFFFF00CD補師_治療效果上升|r", [[Interface\Addons\SharedMedia_Saha\sound\補師_治療效果上升.mp3]])
LSM:Register("sound", "|cFFFF00CD補師_治療效果上升結束|r", [[Interface\Addons\SharedMedia_Saha\sound\補師_治療效果上升結束.mp3]])
LSM:Register("sound", "|cFFFF00CD補師_治療被吸收|r", [[Interface\Addons\SharedMedia_Saha\sound\補師_治療被吸收.mp3]])
LSM:Register("sound", "|cFFFF00CD補師_注意坦克血量|r", [[Interface\Addons\SharedMedia_Saha\sound\補師_注意坦克血量.mp3]])
LSM:Register("sound", "|cFFFF00CD補師_注意群補|r", [[Interface\Addons\SharedMedia_Saha\sound\補師_注意群補.mp3]])
LSM:Register("sound", "|cFFFF00CD補師_注意補血|r", [[Interface\Addons\SharedMedia_Saha\sound\補師_注意補血.mp3]])
LSM:Register("sound", "|cFFFF00CD補師_注意補坦|r", [[Interface\Addons\SharedMedia_Saha\sound\補師_注意補坦.mp3]])
LSM:Register("sound", "|cFFFF00CD補師_停止補血|r", [[Interface\Addons\SharedMedia_Saha\sound\補師_停止補血.mp3]])
LSM:Register("sound", "|cFFFF00CD補師_準備驅散|r", [[Interface\Addons\SharedMedia_Saha\sound\補師_準備驅散.mp3]])
LSM:Register("sound", "|cFFFF00CD補師_靈魂風暴注意血量|r", [[Interface\Addons\SharedMedia_Saha\sound\補師_靈魂風暴注意血量.mp3]])

--蒐集
LSM:Register("sound", "|cFFFF00CD蒐集_吃球減傷|r", [[Interface\Addons\SharedMedia_Saha\sound\蒐集_吃球減傷.mp3]])
LSM:Register("sound", "|cFFFF00CD蒐集_快去送貨|r", [[Interface\Addons\SharedMedia_Saha\sound\蒐集_快去送貨.mp3]])
LSM:Register("sound", "|cFFFF00CD蒐集_快吃球|r", [[Interface\Addons\SharedMedia_Saha\sound\蒐集_快吃球.mp3]])
LSM:Register("sound", "|cFFFF00CD蒐集_快追靈魂|r", [[Interface\Addons\SharedMedia_Saha\sound\蒐集_快追靈魂.mp3]])
LSM:Register("sound", "|cFFFF00CD蒐集_快撿|r", [[Interface\Addons\SharedMedia_Saha\sound\蒐集_快撿.ogg]])
LSM:Register("sound", "|cFFFF00CD蒐集_快撿球|r", [[Interface\Addons\SharedMedia_Saha\sound\蒐集_快撿球.mp3]])
LSM:Register("sound", "|cFFFF00CD蒐集_快撿符文|r", [[Interface\Addons\SharedMedia_Saha\sound\蒐集_快撿符文.mp3]])
LSM:Register("sound", "|cFFFF00CD蒐集_快撿靈魂|r", [[Interface\Addons\SharedMedia_Saha\sound\蒐集_快撿靈魂.mp3]])
LSM:Register("sound", "|cFFFF00CD蒐集_拿球丟王|r", [[Interface\Addons\SharedMedia_Saha\sound\蒐集_拿球丟王.mp3]])
LSM:Register("sound", "|cFFFF00CD蒐集_拿球回祭壇|r", [[Interface\Addons\SharedMedia_Saha\sound\蒐集_拿球回祭壇.mp3]])
LSM:Register("sound", "|cFFFF00CD蒐集_拿球給王|r", [[Interface\Addons\SharedMedia_Saha\sound\蒐集_拿球給王.mp3]])
LSM:Register("sound", "|cFFFF00CD蒐集_準備投遞|r", [[Interface\Addons\SharedMedia_Saha\sound\蒐集_準備投遞.mp3]])
LSM:Register("sound", "|cFFFF00CD蒐集_準備接球|r", [[Interface\Addons\SharedMedia_Saha\sound\蒐集_準備接球.mp3]])

--踩圈
LSM:Register("sound", "|cFFFF00CD踩圈_快去吸水|r", [[Interface\Addons\SharedMedia_Saha\sound\踩圈_快去吸水.mp3]])
LSM:Register("sound", "|cFFFF00CD踩圈_快踩小怪|r", [[Interface\Addons\SharedMedia_Saha\sound\踩圈_快踩小怪.mp3]])
LSM:Register("sound", "|cFFFF00CD踩圈_快踩水|r", [[Interface\Addons\SharedMedia_Saha\sound\踩圈_快踩水.ogg]])
LSM:Register("sound", "|cFFFF00CD踩圈_快踩圈|r", [[Interface\Addons\SharedMedia_Saha\sound\踩圈_快踩圈.mp3]])
LSM:Register("sound", "|cFFFF00CD踩圈_快踩符文|r", [[Interface\Addons\SharedMedia_Saha\sound\踩圈_快踩符文.mp3]])
LSM:Register("sound", "|cFFFF00CD踩圈_準備踩圈|r", [[Interface\Addons\SharedMedia_Saha\sound\踩圈_準備踩圈.mp3]])

--機制
LSM:Register("sound", "|cFFFF00CD機制_十字|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_十字.ogg]])
LSM:Register("sound", "|cFFFF00CD機制_十字擴散|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_十字擴散.ogg]])
LSM:Register("sound", "|cFFFF00CD機制_下一個|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_下一個.ogg]])
LSM:Register("sound", "|cFFFF00CD機制_中場休息|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_中場休息.ogg]])
LSM:Register("sound", "|cFFFF00CD機制_分裂|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_分裂.ogg]])
LSM:Register("sound", "|cFFFF00CD機制_平手降傷10%|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_平手降傷10%.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_用圈消柱子|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_用圈消柱子.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_用圈消球|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_用圈消球.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_用線消球|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_用線消球.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_用線破盾|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_用線破盾.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_取回武器|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_取回武器.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_姊妹呼喚|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_姊妹呼喚.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_注意消圈|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_注意消圈.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_注意蟲洞|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_注意蟲洞.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_要吸了要吸了哦要吸了|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_要吸了要吸了哦要吸了.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_首領強化|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_首領強化.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_高能警告|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_高能警告.ogg]])
LSM:Register("sound", "|cFFFF00CD機制_御主之眼_輕蔑|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_御主之眼_輕蔑.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_御主之眼_憤怒|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_御主之眼_憤怒.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_進蟲洞|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_進蟲洞.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_傳送門|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_傳送門.ogg]])
LSM:Register("sound", "|cFFFF00CD機制_準備演奏|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_準備演奏.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_輪盤點你快跑|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_輪盤點你快跑.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_輸了降傷10%|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_輸了降傷10%.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_擴散|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_擴散.ogg]])
LSM:Register("sound", "|cFFFF00CD機制_贏了增傷10%|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_贏了增傷10%.mp3]])
LSM:Register("sound", "|cFFFF00CD機制_罐子|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_罐子.ogg]])
LSM:Register("sound", "|cFFFF00CD機制_罐子打開快打小怪|r", [[Interface\Addons\SharedMedia_Saha\sound\機制_罐子打開快打小怪.mp3]])

--擊退
LSM:Register("sound", "|cFFFF00CD擊退_注意擊退|r", [[Interface\Addons\SharedMedia_Saha\sound\擊退_注意擊退.mp3]])

--轉火
LSM:Register("sound", "|cFFFF00CD轉火_小怪被定暈 快打|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_小怪被定暈 快打.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_弓箭手快打|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_弓箭手快打.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_打小怪|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_打小怪.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_打後面|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_打後面.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_打破詛咒者護盾|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_打破詛咒者護盾.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_打破護盾|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_打破護盾.ogg]])
LSM:Register("sound", "|cFFFF00CD轉火_免疫控場快打|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_免疫控場快打.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_免疫控場快打大怪|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_免疫控場快打大怪.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_免疫控場快打小怪|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_免疫控場快打小怪.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_快打大監督者|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_快打大監督者.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_快打易傷100趴|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_快打易傷100趴.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_快打傷害增加|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_快打傷害增加.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_快打旗子|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_快打旗子.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_快打護盾|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_快打護盾.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_快救人|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_快救人.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_快噴球|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_快噴球.ogg]])
LSM:Register("sound", "|cFFFF00CD轉火_快轉火|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_快轉火.ogg]])
LSM:Register("sound", "|cFFFF00CD轉火_刺客暈人 快救隊友|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_刺客暈人 快救隊友.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_活力鮮魚棒快打|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_活力鮮魚棒快打.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_停止攻擊|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_停止攻擊.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_準備撞球|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_準備撞球.mp3]])
LSM:Register("sound", "|cFFFF00CD轉火_噴小怪|r", [[Interface\Addons\SharedMedia_Saha\sound\轉火_噴小怪.mp3]])

--鎖鏈
LSM:Register("sound", "|cFFFF00CD鎖鏈_拉斷鎖鏈|r", [[Interface\Addons\SharedMedia_Saha\sound\鎖鏈_拉斷鎖鏈.ogg]])
LSM:Register("sound", "|cFFFF00CD鎖鏈_準備鎖鏈|r", [[Interface\Addons\SharedMedia_Saha\sound\鎖鏈_準備鎖鏈.ogg]])

--顏色
LSM:Register("sound", "|cFFFF00CD顏色_白色|r", [[Interface\Addons\SharedMedia_Saha\sound\顏色_白色.ogg]])
LSM:Register("sound", "|cFFFF00CD顏色_紅色|r", [[Interface\Addons\SharedMedia_Saha\sound\顏色_紅色.ogg]])
LSM:Register("sound", "|cFFFF00CD顏色_紫色|r", [[Interface\Addons\SharedMedia_Saha\sound\顏色_紫色.ogg]])
LSM:Register("sound", "|cFFFF00CD顏色_黃色|r", [[Interface\Addons\SharedMedia_Saha\sound\顏色_黃色.ogg]])
LSM:Register("sound", "|cFFFF00CD顏色_綠色|r", [[Interface\Addons\SharedMedia_Saha\sound\顏色_綠色.ogg]])
LSM:Register("sound", "|cFFFF00CD顏色_橘色|r", [[Interface\Addons\SharedMedia_Saha\sound\顏色_橘色.ogg]])
LSM:Register("sound", "|cFFFF00CD顏色_藍色|r", [[Interface\Addons\SharedMedia_Saha\sound\顏色_藍色.ogg]])


-- -----
--   STATUSBAR
-- -----
