local inserted = false

function DBMCPOverwatch()
	if inserted then return end
	DBM:AddCountSound("Overwatch: Ana", "Ana", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Ana\\", 5, true)
	DBM:AddCountSound("Overwatch: Ana (German)", "Anade", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Ana\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Announcer", "Overwatch", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Announcer\\", 5, true)
	DBM:AddCountSound("Overwatch: Announcer (German)", "Overwatchde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Announcer\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Ashe", "Ashe", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Ashe\\", 5, true)
	DBM:AddCountSound("Overwatch: Ashe (German)", "Ashede", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Ashe\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Baptiste", "Baptiste", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Baptiste\\", 5, true)
	DBM:AddCountSound("Overwatch: Baptiste (German)", "Baptistede", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Baptiste\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Bastion (Old)", "Bastion", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Bastion\\", 5, true)
	DBM:AddCountSound("Overwatch: Bastion", "Bastionnew", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Bastion_New\\", 5, true)
	DBM:AddCountSound("Overwatch: Brigitte", "Brigitte", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Brigitte\\", 5, true)
	DBM:AddCountSound("Overwatch: Brigitte (German)", "Brigittede", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Brigitte\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Cassidy", "Cassidy", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Cassidy\\", 5, true)
	DBM:AddCountSound("Overwatch: Cassidy (German)", "Cassidyde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Cassidy\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: D.Va", "DVa", "Interface\\AddOns\\DBM-CountPack-Overwatch\\DVa\\", 5, true)
	DBM:AddCountSound("Overwatch: D.Va (German)", "DVade", "Interface\\AddOns\\DBM-CountPack-Overwatch\\DVa\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: D.Va (Korean)", "DVakr", "Interface\\AddOns\\DBM-CountPack-Overwatch\\DVa\\kr\\", 5, true)
	DBM:AddCountSound("Overwatch: Doomfist", "Doomfist", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Doomfist\\", 5, true)
	DBM:AddCountSound("Overwatch: Doomfist (German)", "Doomfistde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Doomfist\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Echo", "Echo", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Echo\\", 3, true)
	DBM:AddCountSound("Overwatch: Echo (German)", "Echode", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Echo\\de\\", 3, true)
	DBM:AddCountSound("Overwatch: Freja", "Freja", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Freja\\", 3, true)
	DBM:AddCountSound("Overwatch: Freja (German)", "Frejade", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Freja\\de\\", 3, true)
	DBM:AddCountSound("Overwatch: Genji", "Genji", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Genji\\", 5, true)
	DBM:AddCountSound("Overwatch: Genji (German)", "Genjide", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Genji\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Genji (Japanese)", "Genjijp", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Genji\\jp\\", 5, true)
	DBM:AddCountSound("Overwatch: Hanzo", "Hanzo", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Hanzo\\", 5, true)
	DBM:AddCountSound("Overwatch: Hanzo (German)", "Hanzode", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Hanzo\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Hanzo (Japanese)", "Hanzojp", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Hanzo\\jp\\", 3, true)
	DBM:AddCountSound("Overwatch: Hazard", "Hazard", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Hazard\\", 3, true)
	DBM:AddCountSound("Overwatch: Hazard (German)", "Hazardde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Hazard\\de\\", 3, true)
	DBM:AddCountSound("Overwatch: Illari", "Illari", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Illari\\", 3, true)
	DBM:AddCountSound("Overwatch: Illari (German)", "Illaride", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Illari\\de\\", 3, true)
	DBM:AddCountSound("Overwatch: JunkerQueen", "JunkerQueen", "Interface\\AddOns\\DBM-CountPack-Overwatch\\JunkerQueen\\", 3, true)
	DBM:AddCountSound("Overwatch: JunkerQueen (German)", "JunkerQueende", "Interface\\AddOns\\DBM-CountPack-Overwatch\\JunkerQueen\\de\\", 3, true)
	DBM:AddCountSound("Overwatch: Junkrat", "Junkrat", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Junkrat\\", 5, true)
	DBM:AddCountSound("Overwatch: Junkrat (German)", "Junkratde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Junkrat\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Juno", "Juno", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Juno\\", 3, true)
	DBM:AddCountSound("Overwatch: Juno (German)", "Junode", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Juno\\de\\", 3, true)
	DBM:AddCountSound("Overwatch: Kiriko", "Kiriko", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Kiriko\\", 3, true)
	DBM:AddCountSound("Overwatch: Kiriko (German)", "Kirikode", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Kiriko\\de\\", 3, true)
	DBM:AddCountSound("Overwatch: Lifeweaver", "Lifeweaver", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Lifeweaver\\", 3, true)
	DBM:AddCountSound("Overwatch: Lifeweaver (German)", "Lifeweaverde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Lifeweaver\\de\\", 3, true)
	DBM:AddCountSound("Overwatch: Lucio", "Lucio", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Lucio\\", 5, true)
	DBM:AddCountSound("Overwatch: Lucio (German)", "Luciode", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Lucio\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Mauga", "Mauga", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Mauga\\", 3, true)
	DBM:AddCountSound("Overwatch: Mauga (German)", "Maugade", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Mauga\\de\\", 3, true)
	DBM:AddCountSound("Overwatch: Mei", "Mei", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Mei\\", 5, true)
	DBM:AddCountSound("Overwatch: Mei (German)", "Meide", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Mei\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Mei (Chinese)", "Meicn", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Mei\\cn\\", 5, true)
	DBM:AddCountSound("Overwatch: Moira", "Moira", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Moira\\", 5, true)
	DBM:AddCountSound("Overwatch: Moira (German)", "Moirade", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Moira\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Orisa", "Orisa", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Orisa\\", 5, true)
	DBM:AddCountSound("Overwatch: Orisa (German)", "Orisade", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Orisa\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Mercy", "Mercy", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Mercy\\", 5, true)
	DBM:AddCountSound("Overwatch: Mercy (German)", "Mercyde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Mercy\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Pharah", "Pharah", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Pharah\\", 5, true)
	DBM:AddCountSound("Overwatch: Pharah (German)", "Pharahde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Pharah\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Ramattra", "Ramattra", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Ramattra\\", 3, true)
	DBM:AddCountSound("Overwatch: Ramattra (German)", "Ramattrade", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Ramattra\\de\\", 3, true)
	DBM:AddCountSound("Overwatch: Reaper", "Reaper", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Reaper\\", 5, true)
	DBM:AddCountSound("Overwatch: Reaper (German)", "Reaperde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Reaper\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Reinhardt", "Reinhardt", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Reinhardt\\", 5, true)
	DBM:AddCountSound("Overwatch: Reinhardt (German)", "Reinhardtde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Reinhardt\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Roadhog", "Roadhog", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Roadhog\\", 5, true)
	DBM:AddCountSound("Overwatch: Roadhog (German)", "Roadhogde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Roadhog\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Sigma", "Sigma", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Sigma\\", 5, true)
	DBM:AddCountSound("Overwatch: Soldier", "Soldier", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Soldier\\", 5, true)
	DBM:AddCountSound("Overwatch: Soldier (German)", "Soldierde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Soldier\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Symmetra", "Symmetra", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Symmetra\\", 5, true)
	DBM:AddCountSound("Overwatch: Symmetra (German)", "Symmetrade", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Symmetra\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Sojourn", "Sojourn", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Sojourn\\", 3, true)
	DBM:AddCountSound("Overwatch: Sojourn (German)", "Sojournde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Sojourn\\de\\", 3, true)
	DBM:AddCountSound("Overwatch: Sombra", "Sombra", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Sombra\\", 5, true)
	DBM:AddCountSound("Overwatch: Sombra (German)", "Sombrade", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Sombra\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Torbjorn", "Torbjorn", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Torbjorn\\", 5, true)
	DBM:AddCountSound("Overwatch: Torbjorn (German)", "Torbjornde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Torbjorn\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Tracer", "Tracer", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Tracer\\", 5, true)
	DBM:AddCountSound("Overwatch: Tracer (German)", "Tracerde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Tracer\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Venture", "Venture", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Venture\\", 3, true)
	DBM:AddCountSound("Overwatch: Venture (German)", "Venturede", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Venture\\de\\", 3, true)
	DBM:AddCountSound("Overwatch: Widowmaker", "Widowmaker", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Widowmaker\\", 5, true)
	DBM:AddCountSound("Overwatch: Widowmaker (German)", "Widowmakerde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Widowmaker\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Winston", "Winston", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Winston\\", 5, true)
	DBM:AddCountSound("Overwatch: Winston (German)", "Winstonde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Winston\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Wrecking Ball", "Wrecking Ball", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Wrecking Ball\\", 5, true)
	DBM:AddCountSound("Overwatch: Wrecking Ball (German)", "Wrecking Ballde", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Wrecking Ball\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Zarya", "Zarya", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Zarya\\", 5, true)
	DBM:AddCountSound("Overwatch: Zarya (German)", "Zaryade", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Zarya\\de\\", 5, true)
	DBM:AddCountSound("Overwatch: Zenyatta", "Zenyatta", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Zenyatta\\", 5, true)
	DBM:AddCountSound("Overwatch: Zenyatta (German)", "Zenyattade", "Interface\\AddOns\\DBM-CountPack-Overwatch\\Zenyatta\\de\\", 5, true)
	inserted = true
end
