local LSM = LibStub("LibSharedMedia-3.0")
local zhCN, zhTW, western = LSM.LOCALE_BIT_zhCN, LSM.LOCALE_BIT_zhTW, LSM.LOCALE_BIT_western

local MediaType_BACKGROUND = LSM.MediaType.BACKGROUND
local MediaType_BORDER = LSM.MediaType.BORDER
local MediaType_FONT = LSM.MediaType.FONT
local MediaType_STATUSBAR = LSM.MediaType.STATUSBAR

-- -----
-- borders
-- -----

LSM:Register(MediaType_BORDER, "fer01", [[Interface\AddOns\SharedMedia_BNS\Borders\fer1.tga]])
LSM:Register(MediaType_BORDER, "fer02", [[Interface\AddOns\SharedMedia_BNS\Borders\fer2.tga]])
LSM:Register(MediaType_BORDER, "fer03", [[Interface\AddOns\SharedMedia_BNS\Borders\fer3.tga]])
LSM:Register(MediaType_BORDER, "fer04", [[Interface\AddOns\SharedMedia_BNS\Borders\fer4.tga]])
LSM:Register(MediaType_BORDER, "fer05", [[Interface\AddOns\SharedMedia_BNS\Borders\fer5.tga]])
LSM:Register(MediaType_BORDER, "fer06", [[Interface\AddOns\SharedMedia_BNS\Borders\fer6.tga]])
LSM:Register(MediaType_BORDER, "fer07", [[Interface\AddOns\SharedMedia_BNS\Borders\fer7.tga]])
LSM:Register(MediaType_BORDER, "fer08", [[Interface\AddOns\SharedMedia_BNS\Borders\fer8.tga]])
LSM:Register(MediaType_BORDER, "fer09", [[Interface\AddOns\SharedMedia_BNS\Borders\fer9.tga]])
LSM:Register(MediaType_BORDER, "fer10", [[Interface\AddOns\SharedMedia_BNS\Borders\fer10.tga]])
LSM:Register(MediaType_BORDER, "fer11", [[Interface\AddOns\SharedMedia_BNS\Borders\fer11.tga]])
LSM:Register(MediaType_BORDER, "fer12", [[Interface\AddOns\SharedMedia_BNS\Borders\fer12.tga]])
LSM:Register(MediaType_BORDER, "fer13", [[Interface\AddOns\SharedMedia_BNS\Borders\fer13.tga]])

-- -----
--   FONT
-- -----
LSM:Register(MediaType_FONT, " 昭源黑體改",						[[Interface\Addons\SharedMedia_BNS\font\ChironHeiHKText-SemiBold.ttf]], zhCN + zhTW + western)
LSM:Register(MediaType_FONT, " 芫荽+霞鹜文楷",					[[Interface\Addons\SharedMedia_BNS\font\bLEI00D.ttf]], zhCN + zhTW + western)
LSM:Register(MediaType_FONT, " 更莎黑體等寬",					[[Interface\Addons\SharedMedia_BNS\font\SarasaMonoTC-Regular.ttf]], zhCN + zhTW + western)
LSM:Register(MediaType_FONT, "Alata",							[[Interface\Addons\SharedMedia_BNS\font\Alata.ttf]], zhCN + zhTW + western)
LSM:Register(MediaType_FONT, "MaJi Bold",						[[Interface\Addons\SharedMedia_BNS\font\MaJi-Bold.ttf]], zhCN + zhTW + western)
LSM:Register(MediaType_FONT, "US Damage text",					[[Interface\Addons\SharedMedia_BNS\font\US_damage_Font_Bold.TTF]], zhCN + zhTW + western)
LSM:Register(MediaType_FONT, "CANAVAR Bold",					[[Interface\Addons\SharedMedia_BNS\font\CANAVAR-Bold.ttf]], zhCN + zhTW + western)
LSM:Register(MediaType_FONT, "PEPSI",							[[Interface\Addons\SharedMedia_BNS\font\PEPSI_pl.ttf]], zhCN + zhTW + western)
LSM:Register(MediaType_FONT, "Coalition",						[[Interface\Addons\SharedMedia_BNS\font\Coalition.ttf]], zhCN + zhTW + western)
LSM:Register(MediaType_FONT, "ReggaeOne",						[[Interface\Addons\SharedMedia_BNS\font\ReggaeOneLatin.ttf]], zhCN + zhTW + western)
LSM:Register(MediaType_FONT, "Neusharp Bold",					[[Interface\Addons\SharedMedia_BNS\font\Neusharp-Bold.ttf]], zhCN + zhTW + western)
LSM:Register(MediaType_FONT, "sf-fourche Bold",					[[Interface\Addons\SharedMedia_BNS\font\sf-fourche bold.ttf]], zhCN + zhTW + western)
LSM:Register(MediaType_FONT, "Spartan Bold",					[[Interface\Addons\SharedMedia_BNS\font\Spartan Bold.ttf]], zhCN + zhTW + western)
LSM:Register(MediaType_FONT, "Hackman",							[[Interface\Addons\SharedMedia_BNS\font\Hackman.ttf]], zhCN + zhTW + western)
LSM:Register(MediaType_FONT, "Kdam Thmor Pro",					[[Interface\Addons\SharedMedia_BNS\font\Kdam Thmor Pro.ttf]], zhCN + zhTW + western)
LSM:Register(MediaType_FONT, "Balisong",						[[Interface\Addons\SharedMedia_BNS\font\Balisong.ttf]], zhCN + zhTW + western)
LSM:Register(MediaType_FONT, "Refunk",							[[Interface\Addons\SharedMedia_BNS\font\Refunk.ttf]], zhCN + zhTW + western)

-- -----
--   SOUND
-- -----
LSM:Register("sound", "+|cff00c0ff數字：01|r", [[Interface\Addons\SharedMedia_BNS\sound\1.ogg]]) 
LSM:Register("sound", "+|cff00c0ff數字：02|r", [[Interface\Addons\SharedMedia_BNS\sound\2.ogg]]) 
LSM:Register("sound", "+|cff00c0ff數字：03|r", [[Interface\Addons\SharedMedia_BNS\sound\3.ogg]]) 
LSM:Register("sound", "+|cff00c0ff數字：04|r", [[Interface\Addons\SharedMedia_BNS\sound\4.ogg]]) 
LSM:Register("sound", "+|cff00c0ff數字：05|r", [[Interface\Addons\SharedMedia_BNS\sound\5.ogg]]) 
LSM:Register("sound", "+|cff00c0ff數字：06|r", [[Interface\Addons\SharedMedia_BNS\sound\6.ogg]]) 
LSM:Register("sound", "+|cff00c0ff數字：07|r", [[Interface\Addons\SharedMedia_BNS\sound\7.ogg]]) 
LSM:Register("sound", "+|cff00c0ff數字：08|r", [[Interface\Addons\SharedMedia_BNS\sound\8.ogg]]) 
LSM:Register("sound", "+|cff00c0ff數字：09|r", [[Interface\Addons\SharedMedia_BNS\sound\9.ogg]]) 
LSM:Register("sound", "+|cff00c0ff數字：10|r", [[Interface\Addons\SharedMedia_BNS\sound\10.ogg]]) 
LSM:Register("sound", "#|cff00c0ff標記：靠近骷髏|r", [[Interface\Addons\SharedMedia_BNS\sound\Skull.ogg]]) 
LSM:Register("sound", "#|cff00c0ff標記：靠近方塊|r", [[Interface\Addons\SharedMedia_BNS\sound\Square.ogg]])
LSM:Register("sound", "#|cff00c0ff標記：靠近星星|r", [[Interface\Addons\SharedMedia_BNS\sound\Star.ogg]])
LSM:Register("sound", "#|cff00c0ff標記：靠近大餅|r", [[Interface\Addons\SharedMedia_BNS\sound\Circle.ogg]])
LSM:Register("sound", "#|cff00c0ff標記：靠近叉叉|r", [[Interface\Addons\SharedMedia_BNS\sound\Cross.ogg]]) 
LSM:Register("sound", "#|cff00c0ff標記：靠近菱形|r", [[Interface\Addons\SharedMedia_BNS\sound\Diamond.ogg]]) 
LSM:Register("sound", "#|cff00c0ff標記：靠近月亮|r", [[Interface\Addons\SharedMedia_BNS\sound\Moon.ogg]]) 
LSM:Register("sound", "#|cff00c0ff標記：靠近三角|r", [[Interface\Addons\SharedMedia_BNS\sound\Triangle.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：Aoe準備|r", [[Interface\Addons\SharedMedia_BNS\sound\aesoon.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：中間|r", [[Interface\Addons\SharedMedia_BNS\sound\center.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：注意轉火|r", [[Interface\Addons\SharedMedia_BNS\sound\changetarget.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：控場準備|r", [[Interface\Addons\SharedMedia_BNS\sound\crowdcontrol.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：結束|r", [[Interface\Addons\SharedMedia_BNS\sound\end.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：快集合|r", [[Interface\Addons\SharedMedia_BNS\sound\gather.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：集合分攤|r", [[Interface\Addons\SharedMedia_BNS\sound\gathershare.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：快驅散|r", [[Interface\Addons\SharedMedia_BNS\sound\dispelnow.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：驅散中毒|r", [[Interface\Addons\SharedMedia_BNS\sound\dispelnow.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：驅散詛咒|r", [[Interface\Addons\SharedMedia_BNS\sound\dispelnow.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：驅散疾病|r", [[Interface\Addons\SharedMedia_BNS\sound\dispelnow.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：驅散魔法|r", [[Interface\Addons\SharedMedia_BNS\sound\dispelnow.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：進攻驅散|r", [[Interface\Addons\SharedMedia_BNS\sound\進攻驅散.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：幫忙吸收|r", [[Interface\Addons\SharedMedia_BNS\sound\helpsoad.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：快打斷|r", [[Interface\Addons\SharedMedia_BNS\sound\kickcast.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：控斷鋼條|r", [[Interface\Addons\SharedMedia_BNS\控斷鋼條.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：快跑|r", [[Interface\Addons\SharedMedia_BNS\sound\justrun.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：小怪準備|r", [[Interface\Addons\SharedMedia_BNS\sound\mobsoon.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：快跑位|r", [[Interface\Addons\SharedMedia_BNS\sound\movesoon.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：左|r", [[Interface\Addons\SharedMedia_BNS\sound\left.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：右|r", [[Interface\Addons\SharedMedia_BNS\sound\right.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：快躲開|r", [[Interface\Addons\SharedMedia_BNS\sound\runaway.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：跑開人群|r", [[Interface\Addons\SharedMedia_BNS\sound\runout.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：安全安全|r", [[Interface\Addons\SharedMedia_BNS\sound\safenow.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：快分散|r", [[Interface\Addons\SharedMedia_BNS\sound\scatter.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：注意踩圈|r", [[Interface\Addons\SharedMedia_BNS\sound\stepring.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：危險危險|r", [[Interface\Addons\SharedMedia_BNS\sound\stilldanger.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：注意停手|r", [[Interface\Addons\SharedMedia_BNS\sound\stopatk.ogg]]) 
LSM:Register("sound", "#|cff00c0ff語音：停止移動|r", [[Interface\Addons\SharedMedia_BNS\sound\stopmove.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：目標是你|r", [[Interface\Addons\SharedMedia_BNS\sound\targetyou.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：注意腳下|r", [[Interface\Addons\SharedMedia_BNS\sound\watchstep.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：找人靠近|r", [[Interface\Addons\SharedMedia_BNS\sound\findgather.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：快找掩體|r", [[Interface\Addons\SharedMedia_BNS\sound\findshelter.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：你被點名|r", [[Interface\Addons\SharedMedia_BNS\sound\你被點名.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：躲開正面|r", [[Interface\Addons\SharedMedia_BNS\sound\躲開正面.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：注意血量|r", [[Interface\Addons\SharedMedia_BNS\sound\checkhp.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：注意減傷|r", [[Interface\Addons\SharedMedia_BNS\sound\defensive.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：注意群療|r", [[Interface\Addons\SharedMedia_BNS\sound\healall.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：下一棒|r", [[Interface\Addons\SharedMedia_BNS\sound\下一棒.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：快卡視野|r", [[Interface\Addons\SharedMedia_BNS\sound\快卡視野.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：注意寶珠|r", [[Interface\Addons\SharedMedia_BNS\sound\watchorb.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：小怪快打|r", [[Interface\Addons\SharedMedia_BNS\sound\killmob.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：你被強化|r", [[Interface\Addons\SharedMedia_BNS\sound\你被強化.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：層數過高|r", [[Interface\Addons\SharedMedia_BNS\sound\stackhigh.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：準備交換|r", [[Interface\Addons\SharedMedia_BNS\sound\swapsoon.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：承受傷害|r", [[Interface\Addons\SharedMedia_BNS\sound\takedamage.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：快撿道具|r", [[Interface\Addons\SharedMedia_BNS\sound\快撿道具.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：使用道具|r", [[Interface\Addons\SharedMedia_BNS\sound\useitem.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：使用額外技能|r", [[Interface\Addons\SharedMedia_BNS\sound\使用額外技能.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：小心擊飛|r", [[Interface\Addons\SharedMedia_BNS\sound\carefly.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：注意衝擊波|r", [[Interface\Addons\SharedMedia_BNS\sound\watchwave.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：注意衝鋒|r", [[Interface\Addons\SharedMedia_BNS\sound\注意衝鋒.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：注意射線|r", [[Interface\Addons\SharedMedia_BNS\sound\注意射線.ogg]])
LSM:Register("sound", "#|cff00c0ff語音：保持移動|r", [[Interface\Addons\SharedMedia_BNS\sound\保持移動.ogg]])
LSM:Register("sound", "!|cff00c0ffJoJo冒險野郎1|r", [[Interface\Addons\SharedMedia_BNS\sound\Fists of Fury_1.ogg]]) 
LSM:Register("sound", "!|cff00c0ffJoJo冒險野郎2|r", [[Interface\Addons\SharedMedia_BNS\sound\Fists of Fury_2.ogg]]) 
LSM:Register("sound", "!|cff00c0ffJoJo冒險野郎3|r", [[Interface\Addons\SharedMedia_BNS\sound\Fists of Fury_3.ogg]]) 
LSM:Register("sound", "!|cff00c0ffJoJo冒險野郎4|r", [[Interface\Addons\SharedMedia_BNS\sound\Fists of Fury_4.ogg]]) 
LSM:Register("sound", "!|cff00c0ffJoJo冒險野郎5|r", [[Interface\Addons\SharedMedia_BNS\sound\Fists of Fury_8.ogg]]) 
LSM:Register("sound", "!|cff00c0ffJoJo冒險野郎6|r", [[Interface\Addons\SharedMedia_BNS\sound\Touch of Death_1.ogg]]) 
LSM:Register("sound", "!|cff00c0ffJoJo死亡音效1|r", [[Interface\Addons\SharedMedia_BNS\sound\hurt_5.ogg]]) 
LSM:Register("sound", "!|cff00c0ffJoJo死亡音效2|r", [[Interface\Addons\SharedMedia_BNS\sound\hurt_6.ogg]]) 
LSM:Register("sound", "!|cff00c0ffJoJo死亡音效3|r", [[Interface\Addons\SharedMedia_BNS\sound\hurt_7.ogg]]) 
LSM:Register("sound", "!|cff00c0ffJoJo死亡音效4|r", [[Interface\Addons\SharedMedia_BNS\sound\hurt_8.ogg]]) 
LSM:Register("sound", "!|cff00c0ffJoJo死亡音效5|r", [[Interface\Addons\SharedMedia_BNS\sound\hurt_11.ogg]]) 
LSM:Register("sound", "!|cff00c0ffBleach月牙天沖|r", [[Interface\Addons\SharedMedia_BNS\sound\月牙天沖.ogg]]) 
LSM:Register("sound", "!|cff00c0ffBleach卍解1|r", [[Interface\Addons\SharedMedia_BNS\sound\死神卍解1.ogg]]) 
LSM:Register("sound", "!|cff00c0ffBleach卍解2|r", [[Interface\Addons\SharedMedia_BNS\sound\死神卍解2.ogg]]) 
LSM:Register("sound", "!|cff00c0ffBleach卍解3|r", [[Interface\Addons\SharedMedia_BNS\sound\死神卍解3.ogg]]) 
LSM:Register("sound", "!|cff00c0ffBleach卍解4|r", [[Interface\Addons\SharedMedia_BNS\sound\死神卍解4.ogg]]) 
LSM:Register("sound", "!|cff00c0ffBleach卍解5|r", [[Interface\Addons\SharedMedia_BNS\sound\死神卍解5.ogg]]) 
LSM:Register("sound", "!|cff00c0ffOW源氏大招|r", [[Interface\Addons\SharedMedia_BNS\sound\源氏大招.ogg]]) 
LSM:Register("sound", "!|cff00c0ffOW半藏大招|r", [[Interface\Addons\SharedMedia_BNS\sound\半藏大招.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：地爆天星|r", [[Interface\Addons\SharedMedia_BNS\sound\地爆天星.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：水晶|r", [[Interface\Addons\SharedMedia_BNS\sound\水晶.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：交響|r", [[Interface\Addons\SharedMedia_BNS\sound\交響.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：咕嚕靈波|r", [[Interface\Addons\SharedMedia_BNS\sound\princess-connect.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：庫洛魔法使|r", [[Interface\Addons\SharedMedia_BNS\sound\secure.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：神羅天征|r", [[Interface\Addons\SharedMedia_BNS\sound\Shinra Tensei.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：快打旋風|r", [[Interface\Addons\SharedMedia_BNS\sound\Hadouken.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：WindowsXP開機|r", [[Interface\Addons\SharedMedia_BNS\sound\Windows XP.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：WindowsXP關機|r", [[Interface\Addons\SharedMedia_BNS\sound\WindowsXPShutdown.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：ayaya|r", [[Interface\Addons\SharedMedia_BNS\sound\ayaya.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：Bonk|r", [[Interface\Addons\SharedMedia_BNS\sound\Bonk.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：低血量|r", [[Interface\Addons\SharedMedia_BNS\sound\LowHealth.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：低法力|r", [[Interface\Addons\SharedMedia_BNS\sound\LowMana.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：mgsdrop|r", [[Interface\Addons\SharedMedia_BNS\sound\mgsdrop.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：mgsmail|r", [[Interface\Addons\SharedMedia_BNS\sound\mgsmail.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：mgsopen|r", [[Interface\Addons\SharedMedia_BNS\sound\mgsopen.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：mgspickup|r", [[Interface\Addons\SharedMedia_BNS\sound\mgspickup.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：MGS Alert|r", [[Interface\Addons\SharedMedia_BNS\sound\MGS Alert.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：Quack|r", [[Interface\Addons\SharedMedia_BNS\sound\Quack.ogg]]) 
LSM:Register("sound", "!|cff00c0ff音效：CSC_attention|r", [[Interface\Addons\SharedMedia_BNS\sound\CSC_attention.ogg]])
LSM:Register("sound", "!|cff00c0ff音效：CSC_determined|r", [[Interface\Addons\SharedMedia_BNS\sound\CSC_determined.ogg]])
LSM:Register("sound", "!|cff00c0ff音效：CSC_powerdown|r", [[Interface\Addons\SharedMedia_BNS\sound\CSC_power-down.ogg]])
LSM:Register("sound", "!|cff00c0ff音效：CSC_teleporter|r", [[Interface\Addons\SharedMedia_BNS\sound\CSC_teleporter.ogg]])
LSM:Register("sound", "!|cff00c0ff音效：TacoBellBong|r", [[Interface\Addons\SharedMedia_BNS\sound\TacoBellBong.ogg]])
LSM:Register("sound", "!|cff00c0ff音效：Tuturu|r", [[Interface\Addons\SharedMedia_BNS\sound\Tuturu.ogg]])
LSM:Register("sound", "!|cff00c0ff音效：WowAnime|r", [[Interface\Addons\SharedMedia_BNS\sound\WowAnime.ogg]])
LSM:Register("sound", "!|cff00c0ff音效：警報_01|r", [[Interface\Addons\SharedMedia_BNS\sound\SP_Alarm_01.ogg]])
LSM:Register("sound", "!|cff00c0ff音效：警報_02|r", [[Interface\Addons\SharedMedia_BNS\sound\SP_Alarm_02.ogg]])
LSM:Register("sound", "!|cff00c0ff音效：警報_03|r", [[Interface\Addons\SharedMedia_BNS\sound\SP_Alarm_03.ogg]])
LSM:Register("sound", "!|cff00c0ff音效：瑪利歐金幣|r", [[Interface\Addons\SharedMedia_BNS\sound\super_mario_bros_coin.ogg]])
LSM:Register("sound", "!|cff00c0ff音效：瑪利歐GG|r", [[Interface\Addons\SharedMedia_BNS\sound\super_mario_bros_game_over.ogg]])
LSM:Register("sound", "!|cff00c0ff音效：瑪利歐變大|r", [[Interface\Addons\SharedMedia_BNS\sound\super_mario_bros_powerup.ogg]])
LSM:Register("sound", "!|cff00c0ff音效：特效_01|r", [[Interface\Addons\SharedMedia_BNS\sound\SP_SciFi_01.ogg]])
LSM:Register("sound", "!|cff00c0ff音效：特效_02|r", [[Interface\Addons\SharedMedia_BNS\sound\SP_SciFi_02.ogg]])
LSM:Register("sound", "!|cff00c0ff音效：特效_03|r", [[Interface\Addons\SharedMedia_BNS\sound\SP_SciFi_03.ogg]])
LSM:Register("sound", "!|cff00c0ff音效：喵(女)|r", [[Interface\Addons\SharedMedia_BNS\sound\meow_girl.ogg]])
LSM:Register("sound", "$|cff00c0ff爐石：登場音效|r", [[Interface\Addons\SharedMedia_BNS\sound\爐石登場音效.ogg]]) 
LSM:Register("sound", "$|cff00c0ff爐石：殺殺殺|r", [[Interface\Addons\SharedMedia_BNS\sound\爐石憎惡體.ogg]]) 
LSM:Register("sound", "$|cff00c0ff爐石：北郡教士|r", [[Interface\Addons\SharedMedia_BNS\sound\北郡教士攻擊.ogg]]) 
LSM:Register("sound", "$|cff00c0ff爐石：去死啦垃圾|r", [[Interface\Addons\SharedMedia_BNS\sound\去死啦垃圾.ogg]]) 
LSM:Register("sound", "$|cff00c0ff爐石：打中了|r", [[Interface\Addons\SharedMedia_BNS\sound\打中了.ogg]]) 
LSM:Register("sound", "$|cff00c0ff爐石：皮鞭|r", [[Interface\Addons\SharedMedia_BNS\sound\皮鞭.ogg]]) 
LSM:Register("sound", "$|cff00c0ff爐石：好膽麥走|r", [[Interface\Addons\SharedMedia_BNS\sound\好膽麥走.ogg]]) 
LSM:Register("sound", "$|cff00c0ff爐石：你還沒準備好|r", [[Interface\Addons\SharedMedia_BNS\sound\你還沒準備好.ogg]]) 
LSM:Register("sound", "$|cff00c0ff爐石：為了部落|r", [[Interface\Addons\SharedMedia_BNS\sound\為了部落.ogg]]) 
LSM:Register("sound", "$|cff00c0ff爐石：為了聯盟|r", [[Interface\Addons\SharedMedia_BNS\sound\為了聯盟.ogg]]) 
LSM:Register("sound", "$|cff00c0ff爐石：開火|r", [[Interface\Addons\SharedMedia_BNS\sound\開火.ogg]]) 
LSM:Register("sound", "$|cff00c0ff爐石：嚐嚐我的刀劍|r", [[Interface\Addons\SharedMedia_BNS\sound\嚐嚐我的刀劍.ogg]]) 
LSM:Register("sound", "$|cff00c0ff爐石：關門放狗|r", [[Interface\Addons\SharedMedia_BNS\sound\關門放狗.ogg]]) 
LSM:Register("sound", "$|cff00c0ff爐石：殺戮時刻|r", [[Interface\Addons\SharedMedia_BNS\sound\爐石殺戮時刻.ogg]]) 
LSM:Register("sound", "$|cff00c0ff爐石：搖滾|r", [[Interface\Addons\SharedMedia_BNS\sound\爐石搖滾.ogg]]) 
LSM:Register("sound", "$|cff00c0ff爐石：準備行動|r", [[Interface\Addons\SharedMedia_BNS\sound\爐石準備行動.ogg]]) 
LSM:Register("sound", "&|cff00c0ff配樂：黑人抬棺舞|r", [[Interface\Addons\SharedMedia_BNS\sound\coffindance.ogg]]) 
LSM:Register("sound", "&|cff00c0ff配樂：Hello My Love|r", [[Interface\Addons\SharedMedia_BNS\sound\hello-my-love.ogg]]) 
LSM:Register("sound", "&|cff00c0ff配樂：M_eeee_ep|r", [[Interface\Addons\SharedMedia_BNS\sound\M_eeee_ep.ogg]]) 
LSM:Register("sound", "&|cff00c0ff配樂：M_Nemesis|r", [[Interface\Addons\SharedMedia_BNS\sound\M_Nemesis.ogg]]) 
LSM:Register("sound", "&|cff00c0ff配樂：M_Vestige_elephant|r", [[Interface\Addons\SharedMedia_BNS\sound\M_Vestige_elephant.ogg]]) 
LSM:Register("sound", "&|cff00c0ff配樂：M_Yes_roundabout|r", [[Interface\Addons\SharedMedia_BNS\sound\M_Yes_roundabout.ogg]]) 
LSM:Register("sound", "&|cff00c0ff配樂：GTA任務完成|r", [[Interface\Addons\SharedMedia_BNS\sound\M_gta_mission_complete.ogg]]) 
LSM:Register("sound", "&|cff00c0ff配樂：火影忍者|r", [[Interface\Addons\SharedMedia_BNS\sound\Naruto Battle.ogg]]) 
LSM:Register("sound", "&|cff00c0ff配樂：哈利路亞|r", [[Interface\Addons\SharedMedia_BNS\sound\hallelujah.ogg]]) 
LSM:Register("sound", "&|cff00c0ff配樂：sombrero|r", [[Interface\Addons\SharedMedia_BNS\sound\sombrero.ogg]]) 
LSM:Register("sound", "&|cff00c0ff配樂：權力的遊戲|r", [[Interface\Addons\SharedMedia_BNS\sound\GameOfThrones.ogg]]) 
LSM:Register("sound", "&|cff00c0ff配樂：X檔案|r", [[Interface\Addons\SharedMedia_BNS\sound\X檔案.ogg]]) 

-- -----
--   STATUSBAR
-- -----
LSM:Register(MediaType_STATUSBAR, "Cloud",				[[Interface\Addons\SharedMedia_BNS\statusbar\Cloud]])
LSM:Register(MediaType_STATUSBAR, "Comet",				[[Interface\Addons\SharedMedia_BNS\statusbar\Comet]])
LSM:Register(MediaType_STATUSBAR, "Dabs",				[[Interface\Addons\SharedMedia_BNS\statusbar\Dabs]])
LSM:Register(MediaType_STATUSBAR, "DarkBottom",			[[Interface\Addons\SharedMedia_BNS\statusbar\DarkBottom]])
LSM:Register(MediaType_STATUSBAR, "Glamour",			[[Interface\Addons\SharedMedia_BNS\statusbar\Glamour]])
LSM:Register(MediaType_STATUSBAR, "Glamour2",			[[Interface\Addons\SharedMedia_BNS\statusbar\Glamour2]])
LSM:Register(MediaType_STATUSBAR, "Glamour3",			[[Interface\Addons\SharedMedia_BNS\statusbar\Glamour3]])
LSM:Register(MediaType_STATUSBAR, "Glamour4",			[[Interface\Addons\SharedMedia_BNS\statusbar\Glamour4]])
LSM:Register(MediaType_STATUSBAR, "Glamour5",			[[Interface\Addons\SharedMedia_BNS\statusbar\Glamour5]])
LSM:Register(MediaType_STATUSBAR, "Glamour6",			[[Interface\Addons\SharedMedia_BNS\statusbar\Glamour6]])
LSM:Register(MediaType_STATUSBAR, "Glamour7",			[[Interface\Addons\SharedMedia_BNS\statusbar\Glamour7]])
LSM:Register(MediaType_STATUSBAR, "Perl v2",			[[Interface\Addons\SharedMedia_BNS\statusbar\Perl2]])
LSM:Register(MediaType_STATUSBAR, "Rainbow",			[[Interface\Addons\SharedMedia_BNS\statusbar\Rainbow]])
LSM:Register(MediaType_STATUSBAR, "Rocks",				[[Interface\Addons\SharedMedia_BNS\statusbar\Rocks]])
LSM:Register(MediaType_STATUSBAR, "Runes",				[[Interface\Addons\SharedMedia_BNS\statusbar\Runes]])
LSM:Register(MediaType_STATUSBAR, "Smooth v2",			[[Interface\Addons\SharedMedia_BNS\statusbar\Smoothv2]])
LSM:Register(MediaType_STATUSBAR, "Water",				[[Interface\Addons\SharedMedia_BNS\statusbar\Water]])
LSM:Register(MediaType_STATUSBAR, "Wisps",				[[Interface\Addons\SharedMedia_BNS\statusbar\Wisps]])
LSM:Register(MediaType_STATUSBAR, "fer2",				[[Interface\Addons\SharedMedia_BNS\statusbar\fer2]])
LSM:Register(MediaType_STATUSBAR, "fer3",				[[Interface\Addons\SharedMedia_BNS\statusbar\fer3]])
LSM:Register(MediaType_STATUSBAR, "fer5",				[[Interface\Addons\SharedMedia_BNS\statusbar\fer5]])
LSM:Register(MediaType_STATUSBAR, "fer6",				[[Interface\Addons\SharedMedia_BNS\statusbar\fer6]])
LSM:Register(MediaType_STATUSBAR, "fer8",				[[Interface\Addons\SharedMedia_BNS\statusbar\fer8]])
LSM:Register(MediaType_STATUSBAR, "fer9",				[[Interface\Addons\SharedMedia_BNS\statusbar\fer9]])
LSM:Register(MediaType_STATUSBAR, "fer14",				[[Interface\Addons\SharedMedia_BNS\statusbar\fer14]])
LSM:Register(MediaType_STATUSBAR, "fer20",				[[Interface\Addons\SharedMedia_BNS\statusbar\fer20]])
LSM:Register(MediaType_STATUSBAR, "fer21",				[[Interface\Addons\SharedMedia_BNS\statusbar\fer21]])
LSM:Register(MediaType_STATUSBAR, "fer25",				[[Interface\Addons\SharedMedia_BNS\statusbar\fer25]])
LSM:Register(MediaType_STATUSBAR, "fer27",				[[Interface\Addons\SharedMedia_BNS\statusbar\fer27]])
LSM:Register(MediaType_STATUSBAR, "fer34",				[[Interface\Addons\SharedMedia_BNS\statusbar\fer34]])
LSM:Register(MediaType_STATUSBAR, "fer35",				[[Interface\Addons\SharedMedia_BNS\statusbar\fer35]])
LSM:Register(MediaType_STATUSBAR, "FF_Antonia",			[[Interface\Addons\SharedMedia_BNS\statusbar\FF_Antonia]])
LSM:Register(MediaType_STATUSBAR, "FF_Bettina",			[[Interface\Addons\SharedMedia_BNS\statusbar\FF_Bettina]])
