-- some variables --
VDW.VCB.Local = VDW.VCB.Local or (function()
	local base = {
		TIP_CLOSE_PANEL = "Close this panel!",
-- tab --
		T_PLAYER = "Player Cast Bar",
		T_TARGET = "Target Cast Bar",
		T_FOCUS = "Focus Cast Bar",
		T_BOSS = "Boss Cast Bars",
		T_ARENA = "Arena Cast Bars",
		T_TIP = "Options for %s",
-- panel --
		P_PLAYER = "Player Cast Bar Options",
		P_TARGET = "Target Cast Bar Options",
		P_FOCUS = "Focus Cast Bar Options",
		P_BOSS = "Boss Cast Bars Options",
		P_ARENA = "Arena Cast Bars Options",
-- box --
		B_CCT = "Current Cast Time",
		B_BCT = "Cast Time (Current/Total)",
		B_TCT = "Total Cast Time",
		B_SN = "Spell Name",
		B_SB = "Status Bar",
		B_BB = "Bar Border",
		B_SI = "Spell Icon",
		B_UCB = "Unlock the Cast Bar",
		B_ST = "Spell Ticks",
		B_LB = "Latency Bar",
		B_QB = "Spell Queue Window Bar",
		B_GC = "Global Cooldown",
-- widget --
		W_TARGET = "Target Casting Bar",
		W_FOCUS = "Focus Casting Bar",
		W_BOSS = "Bosses Casting Bars",
		W_ARENA = "Arena Casting Bars",
		W_POSITION = "Position",
		W_DECIMALS = "Decimals",
		W_DIRECTION = "Direction",
		W_STYLE = "Style",
		W_VISIBILITY = "Visibility",
		W_COLOR = "Color",
		W_LOCK = "Locking",
		W_SHIELD = "Shield Icon",
		W_P_TIP = "Where do you want the %s to be shown?",
		W_V_TIP = "Do you want the %s to be shown?",
		W_S_TIP = "What kind of style do you want the %s to be?",
		W_C_TIP = "What color do you want the %s to be?",
		W_SLIDER_TIP = "You can also use the mouse wheel or the edge buttons to change the value.",
		W_CHECKBOX_TIP = "Check me! if you want the %s to be shown",
		W_DECIMALS_TIP = "How many decimals do you want to be shown?",
		W_ST_TIP = "What kind of style do you want the %s to be?|n|nAfter your choice, the game will be reloaded!",
		W_DIRECTION_TIP = "How do you want the direction of timer to be?|n|n'Both' means that the timer, would be ascending while casting, and would be descending while channeling!",
		W_LOCK_TIP_T = "1. Locked: Attach the cast bar to the target frame.|n|n2. Unlocked: Unlocks the cast bar and you can move it anywhere.|n|n3. S.U.F: Makes VCB to work with Shadowed Unit Frame.|n|nAfter your choice, the game will be reloaded!",
		W_LOCK_TIP_F = "1. Locked: Attach the cast bar to the focus frame.|n|n2. Unlocked: Unlocks the cast bar and you can move it anywhere.|n|n3. S.U.F: Makes VCB to work with Shadowed Unit Frame.|n|nAfter your choice, the game will be reloaded!",
		W_LOCK_TIP_B = "1. Locked: Attach the cast bars to the bosses frames.|n|n2. Unlocked: Unlocks the cast bars and you can move them anywhere.|n|n3. S.U.F: Makes VCB to work with Shadowed Unit Frame.|n|nAfter your choice, the game will be reloaded!",
		W_LOCK_TIP_A = "1. Locked: Attach the cast bars to the arena frames.|n|n2. Unlocked: Unlocks the cast bars and you can move them anywhere.|n|n3. S.U.F: Makes VCB to work with Shadowed Unit Frame.|n|nAfter your choice, the game will be reloaded!",
-- profiles --
		P_TAB = "Profiles",
		P_TITLE = "Create, Load, Delete Profiles!",
		P_SUB_CREATE = "Create Profiles",
		P_SUB_LOAD = "Load Profiles",
		P_SUB_DELETE = "Delete Profiles",
		P_TIP_CREATE = "Enter a profile name in the edit box and press Enter to save your settings/options.",
		P_TIP_LOAD = "Select a profile to load.",
		P_TIP_DELETE = "Select a profile to delete.",
		P_WRN_NEED = "Please enter a profile name.",
		P_WRN_EXIST = "This profile already exists. Please try another name.",
		P_WRN_LOAD = "There are no profiles to load.",
		P_WRN_DELETE = "There are no profiles to delete.",
-- warning --
		WRN_NO_SUF = " You don't use the Shadow Unit Frame add on, you don't need to choose that option!",
	}
	local o = {
		frFR = {
			TIP_CLOSE_PANEL = "Fermer ce panneau !",
-- tab --
			T_PLAYER = "Barre d’incantation (Joueur)",
			T_TARGET = "Barre d’incantation (Cible)",
			T_FOCUS = "Barre d’incantation (Focus)",
			T_BOSS = "Barres d’incantation (Boss)",
			T_ARENA = "Barres d’incantation (Arène)",
			T_TIP = "Options pour %s",
-- panel --
			P_PLAYER = "Options de la barre d’incantation du joueur",
			P_TARGET = "Options de la barre d’incantation de la cible",
			P_FOCUS = "Options de la barre d’incantation du focus",
			P_BOSS = "Options des barres d’incantation des boss",
			P_ARENA = "Options des barres d’incantation d’arène",
-- box --
			B_CCT = "Temps d’incantation actuel",
			B_BCT = "Temps d’incantation (actuel/total)",
			B_TCT = "Temps d’incantation total",
			B_SN = "Nom du sort",
			B_SB = "Barre d’état",
			B_BB = "Bordure de la barre",
			B_SI = "Icône du sort",
			B_UCB = "Déverrouiller la barre d’incantation",
			B_ST = "Pulsations du sort",
			B_LB = "Barre de latence",
			B_QB = "Barre de fenêtre de file d’attente",
			B_GC = "Temps de recharge global",
-- widget --
			W_TARGET = "Barre d’incantation de la cible",
			W_FOCUS = "Barre d’incantation du focus",
			W_BOSS = "Barres d’incantation des boss",
			W_ARENA = "Barres d’incantation de l’arène",
			W_POSITION = "Position",
			W_DECIMALS = "Décimales",
			W_DIRECTION = "Direction",
			W_STYLE = "Style",
			W_VISIBILITY = "Visibilité",
			W_COLOR = "Couleur",
			W_LOCK = "Verrouillage",
			W_SHIELD = "Icône de bouclier",
			W_P_TIP = "Où voulez-vous afficher %s ?",
			W_V_TIP = "Voulez-vous afficher %s ?",
			W_S_TIP = "Quel style voulez-vous pour %s ?",
			W_C_TIP = "Quelle couleur voulez-vous pour %s ?",
			W_SLIDER_TIP = "Vous pouvez aussi utiliser la molette de la souris ou les boutons sur les bords pour changer la valeur.",
			W_CHECKBOX_TIP = "Cochez-moi si vous voulez afficher %s",
			W_DECIMALS_TIP = "Combien de décimales voulez-vous afficher ?",
			W_ST_TIP = "Quel style voulez-vous pour %s ?|n|nAprès votre choix, le jeu sera rechargé !",
			W_DIRECTION_TIP = "Comment voulez-vous que la direction du minuteur soit ?|n|n« Les deux » signifie que le minuteur comptera vers le haut pendant l’incantation et vers le bas pendant la canalisation !",
			W_LOCK_TIP_T = "1. Verrouillé : Attache la barre d’incantation au cadre de la cible.|n|n2. Déverrouillé : Déverrouille la barre d’incantation et vous pouvez la déplacer n’importe où.|n|n3. S.U.F : Permet à VCB de fonctionner avec Shadowed Unit Frame.|n|nAprès votre choix, le jeu sera rechargé !",
			W_LOCK_TIP_F = "1. Verrouillé : Attache la barre d’incantation au cadre du focus.|n|n2. Déverrouillé : Déverrouille la barre d’incantation et vous pouvez la déplacer n’importe où.|n|n3. S.U.F : Permet à VCB de fonctionner avec Shadowed Unit Frame.|nAprès votre choix, le jeu sera rechargé !",
			W_LOCK_TIP_B = ". Verrouillé : Attache les barres d’incantation aux cadres des boss.|n|n2. Déverrouillé : Déverrouille les barres d’incantation et vous pouvez les déplacer n’importe où.|n|n3. S.U.F : Permet à VCB de fonctionner avec Shadowed Unit Frame.|n|nAprès votre choix, le jeu sera rechargé !",
			W_LOCK_TIP_A = "1. Verrouillé : Attache les barres d’incantation aux cadres de l’arène.|n|n2. Déverrouillé : Déverrouille les barres d’incantation et vous pouvez les déplacer n’importe où.|n|n3. S.U.F : Permet à VCB de fonctionner avec Shadowed Unit Frame.|n|nAprès votre choix, le jeu sera rechargé !",
-- profiles --
			P_TAB = "Profils",
			P_TITLE = "Créer, charger, supprimer des profils !",
			P_SUB_CREATE = "Créer un profil",
			P_SUB_LOAD = "Charger des profils",
			P_SUB_DELETE = "Supprimer des profils",
			P_TIP_CREATE = "Saisissez un nom de profil dans le champ de texte et appuyez sur Entrée pour sauvegarder vos réglages/options.",
			P_TIP_LOAD = "Sélectionnez un profil à charger.",
			P_TIP_DELETE = "Sélectionnez un profil à supprimer.",
			P_WRN_EXIST = "Ce profil existe déjà. Essayez un autre nom.",
			P_WRN_NEED = "Entrez un nom de profil.",
			P_WRN_LOAD = "Aucun profil à charger.",
			P_WRN_DELETE = "Aucun profil à supprimer.",
-- warning --
			WRN_NO_SUF = " Vous n’utilisez pas l’addon Shadowed Unit Frames, vous n’avez pas besoin de choisir cette option !",
		},
		deDE = {
			TIP_CLOSE_PANEL = "Dieses Panel schließen!",
-- tab --
			T_PLAYER = "Zauberleiste (Spieler)",
			T_TARGET = "Zauberleiste (Ziel)",
			T_FOCUS = "Zauberleiste (Fokus)",
			T_BOSS = "Zauberleisten (Bosse)",
			T_ARENA = "Zauberleisten (Arena)",
			T_TIP = "Optionen für %s",
-- panel --
			P_PLAYER = "Optionen für die Zauberleiste des Spielers",
			P_TARGET = "Optionen für die Zauberleiste des Ziels",
			P_FOCUS = "Optionen für die Zauberleiste des Fokus",
			P_BOSS = "Optionen für die Zauberleisten der Bosse",
			P_ARENA = "Optionen für die Zauberleisten der Arena",
-- box --
			B_CCT = "Aktuelle Zauberzeit",
			B_BCT = "Zauberzeit (aktuell/gesamt)",
			B_TCT = "Gesamte Zauberzeit",
			B_SN = "Zaubername",
			B_SB = "Statusleiste",
			B_BB = "Leistenrahmen",
			B_SI = "Zauber-Symbol",
			B_UCB = "Zauberleiste entsperren",
			B_ST = "Zauber-Ticks",
			B_LB = "Latenzleiste",
			B_QB = "Zauberwarteschlangenfenster-Leiste",
			B_GC = "Globale Abklingzeit",
-- widget --
			W_TARGET = "Zauberleiste des Ziels",
			W_FOCUS = "Zauberleiste des Fokus",
			W_BOSS = "Zauberleisten der Bosse",
			W_ARENA = "Zauberleisten der Arena",
			W_POSITION = "Position",
			W_DECIMALS = "Dezimalstellen",
			W_DIRECTION = "Richtung",
			W_STYLE = "Stil",
			W_VISIBILITY = "Sichtbarkeit",
			W_COLOR = "Farbe",
			W_LOCK = "Sperre",
			W_SHIELD = "Schildsymbol",
			W_P_TIP = "Wo soll %s angezeigt werden?",
			W_V_TIP = "Möchtest du %s anzeigen?",
			W_S_TIP = "Welchen Stil möchtest du für %s?",
			W_C_TIP = "Welche Farbe möchtest du für %s?",
			W_SLIDER_TIP = "Du kannst auch das Mausrad oder die Randtasten verwenden, um den Wert zu ändern.",
			W_CHECKBOX_TIP = "Hake mich an, wenn du möchtest, dass %s angezeigt wird",
			W_DECIMALS_TIP = "Wie viele Dezimalstellen sollen angezeigt werden?",
			W_ST_TIP = "Welchen Stil möchtest du für %s?|n|nNach deiner Wahl wird das Spiel neu geladen!",
			W_DIRECTION_TIP = "Wie soll die Richtung des Timers sein?|n|n„Beides“ bedeutet, dass der Timer beim Wirken hochzählt und beim Kanalisieren runterzählt!",
			W_LOCK_TIP_T = "1. Gesperrt: Hängt die Zauberleiste an den Zielrahmen.|n|n2. Entsperrt: Entsperrt die Zauberleiste und du kannst sie überall hin verschieben.|n|n3. S.U.F: Lässt VCB mit Shadowed Unit Frame funktionieren.|n|nNach deiner Wahl wird das Spiel neu geladen!",
			W_LOCK_TIP_F = "1. Gesperrt: Hängt die Zauberleiste an den Fokusrahmen.|n|n2. Entsperrt: Entsperrt die Zauberleiste und du kannst sie überall hin verschieben.|n|n3. S.U.F: Lässt VCB mit Shadowed Unit Frame funktionieren.|n|nNach deiner Wahl wird das Spiel neu geladen!",
			W_LOCK_TIP_B = "1. Gesperrt: Hängt die Zauberleisten an die Bossrahmen.|n|n2. Entsperrt: Entsperrt die Zauberleisten und du kannst sie überall hin verschieben.|n|n3. S.U.F: Lässt VCB mit Shadowed Unit Frame funktionieren.|n|nNach deiner Wahl wird das Spiel neu geladen!",
			W_LOCK_TIP_A = "1. Gesperrt: Hängt die Zauberleisten an die Arenarahmen.|n|n2. Entsperrt: Entsperrt die Zauberleisten und du kannst sie überall hin verschieben.|n|n3. S.U.F: Lässt VCB mit Shadowed Unit Frame funktionieren.|n|nNach deiner Wahl wird das Spiel neu geladen!",
-- profiles --
			P_TAB = "Profile",
			P_TITLE = "Profile erstellen, laden, löschen!",
			P_SUB_CREATE = "Profil erstellen",
			P_SUB_LOAD = "Profile laden",
			P_SUB_DELETE = "Profile löschen",
			P_TIP_CREATE = "Gib einen Profilnamen in das Eingabefeld ein und drücke Enter, um deine Einstellungen/Optionen zu speichern.",
			P_TIP_LOAD = "Profil zum Laden auswählen.",
			P_TIP_DELETE = "Profil zum Löschen auswählen.",
			P_WRN_EXIST = "Dieses Profil existiert bereits. Bitte einen anderen Namen wählen.",
			P_WRN_NEED = "Bitte einen Profilnamen eingeben.",
			P_WRN_LOAD = "Keine Profile zum Laden.",
			P_WRN_DELETE = "Keine Profile zum Löschen.",
-- warning --
			WRN_NO_SUF = " Du benutzt das Addon Shadowed Unit Frames nicht, du musst diese Option nicht auswählen!",
		},
		esES = {
			TIP_CLOSE_PANEL = "Cerrar este panel!",
-- tab --
			T_PLAYER = "Barra de lanzamiento (Jugador)",
			T_TARGET = "Barra de lanzamiento (Objetivo)",
			T_FOCUS = "Barra de lanzamiento (Foco)",
			T_BOSS = "Barras de lanzamiento (Jefes)",
			T_ARENA = "Barras de lanzamiento (Arena)",
			T_TIP = "Opciones para %s",
-- panels --
			P_PLAYER = "Opciones de la barra de lanzamiento del jugador",
			P_TARGET = "Opciones de la barra de lanzamiento del objetivo",
			P_FOCUS = "Opciones de la barra de lanzamiento del foco",
			P_BOSS = "Opciones de las barras de lanzamiento de los jefes",
			P_ARENA = "Opciones de las barras de lanzamiento de la arena",
-- box --
			B_CCT = "Tiempo de lanzamiento actual",
			B_BCT = "Tiempo de lanzamiento (actual/total)",
			B_TCT = "Tiempo de lanzamiento total",
			B_SN = "Nombre del hechizo",
			B_SB = "Barra de estado",
			B_BB = "Borde de la barra",
			B_SI = "Icono del hechizo",
			B_UCB = "Desbloquear la barra de lanzamiento",
			B_ST = "Ticks del hechizo",
			B_LB = "Barra de latencia",
			B_QB = "Barra de ventana de cola",
			B_GC = "Tiempo de reutilización global",
-- widget --
			W_TARGET = "Barra de lanzamiento del objetivo",
			W_FOCUS = "Barra de lanzamiento del foco",
			W_BOSS = "Barras de lanzamiento de jefes",
			W_ARENA = "Barras de lanzamiento de arena",
			W_POSITION = "Posición",
			W_DECIMALS = "Decimales",
			W_DIRECTION = "Dirección",
			W_STYLE = "Estilo",
			W_VISIBILITY = "Visibilidad",
			W_COLOR = "Color",
			W_LOCK = "Bloqueo",
			W_SHIELD = "Icono de escudo",
			W_P_TIP = "¿Dónde quieres que se muestre %s?",
			W_V_TIP = "¿Quieres que se muestre %s?",
			W_S_TIP = "¿Qué estilo quieres para %s?",
			W_C_TIP = "¿Qué color quieres para %s?",
			W_SLIDER_TIP = "También puedes usar la rueda del ratón o los botones del borde para cambiar el valor.",
			W_CHECKBOX_TIP = "Márcame si quieres que se muestre %s",
			W_DECIMALS_TIP = "¿Cuántos decimales quieres que se muestren?",
			W_ST_TIP = "¿Qué estilo quieres para %s?|n|n¡Después de tu elección, el juego se recargará!",
			W_DIRECTION_TIP = "¿Cómo quieres que sea la dirección del temporizador?|n|n«Ambos» significa que el temporizador contará hacia arriba al lanzar y hacia abajo al canalizar.",
			W_LOCK_TIP_T = "1. Bloqueado: Ancla la barra de lanzamiento al marco del objetivo.|n|n2. Desbloqueado: Desbloquea la barra de lanzamiento y puedes moverla a cualquier lugar.|n|n3. S.U.F: Hace que VCB funcione con Shadowed Unit Frame.|n|n¡Después de tu elección, el juego se recargará!",
			W_LOCK_TIP_F = "1. Bloqueado: Ancla la barra de lanzamiento al marco del foco.|n|n2. Desbloqueado: Desbloquea la barra de lanzamiento y puedes moverla a cualquier lugar.|n|n3. S.U.F: Hace que VCB funcione con Shadowed Unit Frame.|n|n¡Después de tu elección, el juego se recargará!",
			W_LOCK_TIP_B = "1. Bloqueado: Ancla las barras de lanzamiento a los marcos de los jefes.|n|n2. Desbloqueado: Desbloquea las barras de lanzamiento y puedes moverlas a cualquier lugar.|n|n3. S.U.F: Hace que VCB funcione con Shadowed Unit Frame.|n|n¡Después de tu elección, el juego se recargará!",
			W_LOCK_TIP_A = "1. Bloqueado: Ancla las barras de lanzamiento a los marcos de la arena.|n|n2. Desbloqueado: Desbloquea las barras de lanzamiento y puedes moverlas a cualquier lugar.|n|n3. S.U.F: Hace que VCB funcione con Shadowed Unit Frame.|n|n¡Después de tu elección, el juego se recargará!",
-- profiles --
			P_TAB = "Perfiles",
			P_TITLE = "¡Crear, cargar y eliminar perfiles!",
			P_SUB_CREATE = "Crear perfil",
			P_SUB_LOAD = "Cargar perfiles",
			P_SUB_DELETE = "Eliminar perfiles",
			P_TIP_CREATE = "Escribe un nombre de perfil en el cuadro de texto y pulsa Intro para guardar tu configuración/opciones.",
			P_TIP_LOAD = "Selecciona un perfil para cargar.",
			P_TIP_DELETE = "Selecciona un perfil para eliminar.",
			P_WRN_EXIST = "Este perfil ya existe. Prueba con otro nombre.",
			P_WRN_NEED = "Introduce un nombre de perfil.",
			P_WRN_LOAD = "No hay perfiles para cargar.",
			P_WRN_DELETE = "No hay perfiles para eliminar.",
-- warning --
			WRN_NO_SUF = " No usas el addon Shadowed Unit Frames, no necesitas elegir esa opción.",
		},
		esMX = {
			TIP_CLOSE_PANEL = "Cerrar este panel!",
-- tab --
			T_PLAYER = "Barra de lanzamiento (Jugador)",
			T_TARGET = "Barra de lanzamiento (Objetivo)",
			T_FOCUS = "Barra de lanzamiento (Foco)",
			T_BOSS = "Barras de lanzamiento (Jefes)",
			T_ARENA = "Barras de lanzamiento (Arena)",
			T_TIP = "Opciones para %s",
-- panel --
			P_PLAYER = "Opciones de la barra de lanzamiento del jugador",
			P_TARGET = "Opciones de la barra de lanzamiento del objetivo",
			P_FOCUS = "Opciones de la barra de lanzamiento del foco",
			P_BOSS = "Opciones de las barras de lanzamiento de los jefes",
			P_ARENA = "Opciones de las barras de lanzamiento de la arena",
-- box --
			B_CCT = "Tiempo de lanzamiento actual",
			B_BCT = "Tiempo de lanzamiento (actual/total)",
			B_TCT = "Tiempo de lanzamiento total",
			B_SN = "Nombre del hechizo",
			B_SB = "Barra de estado",
			B_BB = "Borde de la barra",
			B_SI = "Icono del hechizo",
			B_UCB = "Desbloquear la barra de lanzamiento",
			B_ST = "Ticks del hechizo",
			B_LB = "Barra de latencia",
			B_QB = "Barra de ventana de cola",
			B_GC = "Tiempo de reutilización global",
-- widget --
			W_TARGET = "Barra de lanzamiento del objetivo",
			W_FOCUS = "Barra de lanzamiento del foco",
			W_BOSS = "Barras de lanzamiento de jefes",
			W_ARENA = "Barras de lanzamiento de arena",
			W_POSITION = "Posición",
			W_DECIMALS = "Decimales",
			W_DIRECTION = "Dirección",
			W_STYLE = "Estilo",
			W_VISIBILITY = "Visibilidad",
			W_COLOR = "Color",
			W_LOCK = "Bloqueo",
			W_SHIELD = "Ícono de escudo",
			W_P_TIP = "¿Dónde quieres que se muestre %s?",
			W_V_TIP = "¿Quieres que se muestre %s?",
			W_S_TIP = "¿Qué estilo quieres para %s?",
			W_C_TIP = "¿Qué color quieres para %s?",
			W_SLIDER_TIP = "También puedes usar la rueda del ratón o los botones del borde para cambiar el valor.",
			W_CHECKBOX_TIP = "Márcame si quieres que se muestre %s",
			W_DECIMALS_TIP = "¿Cuántos decimales quieres que se muestren?",
			W_ST_TIP = "¿Qué estilo quieres para %s?|n|n¡Después de tu elección, el juego se recargará!",
			W_DIRECTION_TIP = "¿Cómo quieres que sea la dirección del temporizador?|n|n«Ambos» significa que el temporizador contará hacia arriba al lanzar y hacia abajo al canalizar.",
			W_LOCK_TIP_T = "1. Bloqueado: Ancla la barra de lanzamiento al marco del objetivo.|n|n2. Desbloqueado: Desbloquea la barra de lanzamiento y puedes moverla a cualquier lugar.|n|n3. S.U.F: Hace que VCB funcione con Shadowed Unit Frame.|n|n¡Después de tu elección, el juego se recargará!",
			W_LOCK_TIP_F = "1. Bloqueado: Ancla la barra de lanzamiento al marco del foco.|n|n2. Desbloqueado: Desbloquea la barra de lanzamiento y puedes moverla a cualquier lugar.|n|n3. S.U.F: Hace que VCB funcione con Shadowed Unit Frame.|n|n¡Después de tu elección, el juego se recargará!",
			W_LOCK_TIP_B = "1. Bloqueado: Ancla las barras de lanzamiento a los marcos de los jefes.|n|n2. Desbloqueado: Desbloquea las barras de lanzamiento y puedes moverlas a cualquier lugar.|n|n3. S.U.F: Hace que VCB funcione con Shadowed Unit Frame.|n|n¡Después de tu elección, el juego se recargará!",
			W_LOCK_TIP_A = "1. Bloqueado: Ancla las barras de lanzamiento a los marcos de la arena.|n|n2. Desbloqueado: Desbloquea las barras de lanzamiento y puedes moverlas a cualquier lugar.|n|n3. S.U.F: Hace que VCB funcione con Shadowed Unit Frame.|n|n¡Después de tu elección, el juego se recargará!",
-- profiles --
			P_TAB = "Perfiles",
			P_TITLE = "¡Crear, cargar y eliminar perfiles!",
			P_SUB_CREATE = "Crear perfil",
			P_SUB_LOAD = "Cargar perfiles",
			P_SUB_DELETE = "Eliminar perfiles",
			P_TIP_CREATE = "Escribe un nombre de perfil en el cuadro de texto y pulsa Intro para guardar tu configuración/opciones.",
			P_TIP_LOAD = "Selecciona un perfil para cargar.",
			P_TIP_DELETE = "Selecciona un perfil para eliminar.",
			P_WRN_EXIST = "Este perfil ya existe. Prueba con otro nombre.",
			P_WRN_NEED = "Introduce un nombre de perfil.",
			P_WRN_LOAD = "No hay perfiles para cargar.",
			P_WRN_DELETE = "No hay perfiles para eliminar.",
-- warning --
			WRN_NO_SUF = " No usas el addon Shadowed Unit Frames, no necesitas elegir esa opción.",
		},
		ptBR = {
			TIP_CLOSE_PANEL = "Fechar este painel!",
-- tab --
			T_PLAYER = "Barra de conjuração (Jogador)",
			T_TARGET = "Barra de conjuração (Alvo)",
			T_FOCUS = "Barra de conjuração (Foco)",
			T_BOSS = "Barras de conjuração (Chefes)",
			T_ARENA = "Barras de conjuração (Arena)",
			T_TIP = "Opções para %s",
-- panel --
			P_PLAYER = "Opções da barra de conjuração do jogador",
			P_TARGET = "Opções da barra de conjuração do alvo",
			P_FOCUS = "Opções da barra de conjuração do foco",
			P_BOSS = "Opções das barras de conjuração dos chefes",
			P_ARENA = "Opções das barras de conjuração da arena",
-- box --
			B_CCT = "Tempo de conjuração atual",
			B_BCT = "Tempo de conjuração (atual/total)",
			B_TCT = "Tempo de conjuração total",
			B_SN = "Nome do feitiço",
			B_SB = "Barra de status",
			B_BB = "Borda da barra",
			B_SI = "Ícone do feitiço",
			B_UCB = "Desbloquear a barra de conjuração",
			B_ST = "Ticks do feitiço",
			B_LB = "Barra de latência",
			B_QB = "Barra da janela de fila",
			B_GC = "Recarga global",
-- widget --
			W_TARGET = "Barra de conjuração do alvo",
			W_FOCUS = "Barra de conjuração do foco",
			W_BOSS = "Barras de conjuração dos chefes",
			W_ARENA = "Barras de conjuração da arena",
			W_POSITION = "Posição",
			W_DECIMALS = "Decimais",
			W_DIRECTION = "Direção",
			W_STYLE = "Estilo",
			W_VISIBILITY = "Visibilidade",
			W_COLOR = "Cor",
			W_LOCK = "Trava",
			W_SHIELD = "Ícone de escudo",
			W_P_TIP = "Onde você quer que %s seja exibido?",
			W_V_TIP = "Você quer que %s seja exibido?",
			W_S_TIP = "Que estilo você quer para %s?",
			W_C_TIP = "Que cor você quer para %s?",
			W_SLIDER_TIP = "Você também pode usar a roda do mouse ou os botões da borda para alterar o valor.",
			W_CHECKBOX_TIP = "Marque-me se você quiser que %s seja exibido",
			W_DECIMALS_TIP = "Quantas casas decimais você quer que sejam exibidas?",
			W_ST_TIP = "Que estilo você quer para %s?|n|nApós sua escolha, o jogo será recarregado!",
			W_DIRECTION_TIP = "Como você quer que seja a direção do temporizador?|n|n«Ambos» significa que o temporizador contará para cima ao conjurar e para baixo ao canalizar!",
			W_LOCK_TIP_T = "1. Travado: Anexa a barra de conjuração ao quadro do alvo.|n|n2. Destravado: Destrava a barra de conjuração e você pode movê-la para qualquer lugar.|n|n3. S.U.F: Faz o VCB funcionar com Shadowed Unit Frame.|n|nApós sua escolha, o jogo será recarregado!",
			W_LOCK_TIP_F = "1. Travado: Anexa a barra de conjuração ao quadro do foco.|n|n2. Destravado: Destrava a barra de conjuração e você pode movê-la para qualquer lugar.|n|n3. S.U.F: Faz o VCB funcionar com Shadowed Unit Frame.|n|nApós sua escolha, o jogo será recarregado!",
			W_LOCK_TIP_B = "1. Travado: Anexa as barras de conjuração aos quadros dos chefes.|n|n2. Destravado: Destrava as barras de conjuração e você pode movê-las para qualquer lugar.|n|n3. S.U.F: Faz o VCB funcionar com Shadowed Unit Frame.|n|nApós sua escolha, o jogo será recarregado!",
			W_LOCK_TIP_A = "1. Travado: Anexa as barras de conjuração aos quadros da arena.|n|n2. Destravado: Destrava as barras de conjuração e você pode movê-las para qualquer lugar.|n|n3. S.U.F: Faz o VCB funcionar com Shadowed Unit Frame.|n|nApós sua escolha, o jogo será recarregado!",
-- profiles --
			P_TAB = "Perfis",
			P_TITLE = "Criar, carregar e excluir perfis!",
			P_SUB_CREATE = "Criar perfil",
			P_SUB_LOAD = "Carregar perfis",
			P_SUB_DELETE = "Excluir perfis",
			P_TIP_CREATE = "Digite um nome de perfil na caixa de texto e pressione Enter para salvar suas configurações/opções.",
			P_TIP_LOAD = "Selecione um perfil para carregar.",
			P_TIP_DELETE = "Selecione um perfil para excluir.",
			P_WRN_EXIST = "Este perfil já existe. Tente outro nome.",
			P_WRN_NEED = "Digite um nome de perfil.",
			P_WRN_LOAD = "Não há perfis para carregar.",
			P_WRN_DELETE = "Não há perfis para excluir.",
-- warning --
			WRN_NO_SUF = " Você não usa o addon Shadowed Unit Frames, então não precisa escolher essa opção!",
		},
		itIT = {
			TIP_CLOSE_PANEL = "Chiudi questo pannello!",
-- tab --
			T_PLAYER = "Barra di lancio (Giocatore)",
			T_TARGET = "Barra di lancio (Bersaglio)",
			T_FOCUS = "Barra di lancio (Focus)",
			T_BOSS = "Barre di lancio (Boss)",
			T_ARENA = "Barre di lancio (Arena)",
			T_TIP = "Opzioni per %s",
-- panel --
			P_PLAYER = "Opzioni della barra di lancio del giocatore",
			P_TARGET = "Opzioni della barra di lancio del bersaglio",
			P_FOCUS = "Opzioni della barra di lancio del focus",
			P_BOSS = "Opzioni delle barre di lancio dei boss",
			P_ARENA = "Opzioni delle barre di lancio da arena",
-- box --
			B_CCT = "Tempo di lancio attuale",
			B_BCT = "Tempo di lancio (attuale/totale)",
			B_TCT = "Tempo di lancio totale",
			B_SN = "Nome dell’incantesimo",
			B_SB = "Barra di stato",
			B_BB = "Bordo della barra",
			B_SI = "Icona dell’incantesimo",
			B_UCB = "Sblocca la barra di lancio",
			B_ST = "Tick dell’incantesimo",
			B_LB = "Barra della latenza",
			B_QB = "Barra della finestra di coda",
			B_GC = "Tempo di recupero globale",
-- widget --
			W_TARGET = "Barra di lancio del bersaglio",
			W_FOCUS = "Barra di lancio del focus",
			W_BOSS = "Barre di lancio dei boss",
			W_ARENA = "Barre di lancio dell’arena",
			W_POSITION = "Posizione",
			W_DECIMALS = "Decimali",
			W_DIRECTION = "Direzione",
			W_STYLE = "Stile",
			W_VISIBILITY = "Visibilità",
			W_COLOR = "Colore",
			W_LOCK = "Blocco",
			W_SHIELD = "Icona dello scudo",
			W_P_TIP = "Dove vuoi che %s venga mostrato?",
			W_V_TIP = "Vuoi mostrare %s?",
			W_S_TIP = "Che stile vuoi per %s?",
			W_C_TIP = "Che colore vuoi per %s?",
			W_SLIDER_TIP = "Puoi anche usare la rotellina del mouse o i pulsanti sul bordo per cambiare il valore.",
			W_CHECKBOX_TIP = "Spuntami se vuoi che %s venga mostrato",
			W_DECIMALS_TIP = "Quanti decimali vuoi visualizzare?",
			W_ST_TIP = "Che stile vuoi per %s?|n|nDopo la tua scelta, il gioco verrà ricaricato!",
			W_DIRECTION_TIP = "Come vuoi che sia la direzione del timer?|n|n«Entrambi» significa che il timer conterà in aumento durante il lancio e in diminuzione durante la canalizzazione!",
			W_LOCK_TIP_T = "1. Bloccato: Aggancia la barra di lancio al riquadro del bersaglio.|n|n2. Sbloccato: Sblocca la barra di lancio e puoi spostarla ovunque.|n|n3. S.U.F: Fa funzionare VCB con Shadowed Unit Frame.|n|nDopo la tua scelta, il gioco verrà ricaricato!",
			W_LOCK_TIP_F = "1. Bloccato: Aggancia la barra di lancio al riquadro del focus.|n|n2. Sbloccato: Sblocca la barra di lancio e puoi spostarla ovunque.|n|n3. S.U.F: Fa funzionare VCB con Shadowed Unit Frame.|n|nDopo la tua scelta, il gioco verrà ricaricato!",
			W_LOCK_TIP_B = "1. Bloccato: Aggancia le barre di lancio ai riquadri dei boss.|n|n2. Sbloccato: Sblocca le barre di lancio e puoi spostarle ovunque.|n|n3. S.U.F: Fa funzionare VCB con Shadowed Unit Frame.|n|nDopo la tua scelta, il gioco verrà ricaricato!",
			W_LOCK_TIP_A = "1. Bloccato: Aggancia le barre di lancio ai riquadri dell’arena.|n|n2. Sbloccato: Sblocca le barre di lancio e puoi spostarle ovunque.|n|n3. S.U.F: Fa funzionare VCB con Shadowed Unit Frame.|n|nDopo la tua scelta, il gioco verrà ricaricato!",
-- profiles --
			P_TAB = "Profili",
			P_TITLE = "Crea, carica ed elimina profili!",
			P_SUB_CREATE = "Crea profilo",
			P_SUB_LOAD = "Caricare profili",
			P_SUB_DELETE = "Eliminare profili",
			P_TIP_CREATE = "Inserisci un nome profilo nella casella di testo e premi Invio per salvare impostazioni/opzioni.",
			P_TIP_LOAD     = "Seleziona un profilo da caricare.",
			P_TIP_DELETE   = "Seleziona un profilo da eliminare.",
			P_WRN_EXIST = "Questo profilo esiste già. Prova un altro nome.",
			P_WRN_NEED = "Inserisci un nome per il profilo.",
			P_WRN_LOAD = "Nessun profilo da caricare.",
			P_WRN_DELETE = "Nessun profilo da eliminare.",
-- warning --
			WRN_NO_SUF = " Non usi l’addon Shadowed Unit Frames, non devi scegliere questa opzione!",
		},
		ruRU = base,
		zhCN = base,
		zhTW = base,
		koKR = base,
	}
	local loc = GetLocale()
	local ov = o[loc]
	if type(ov) == "string" then ov = o[ov] end
	if ov then
		for k, v in pairs(ov) do base[k] = v end
	end
	return base
end)()
