-- Menu2 search query aliases: maps natural search wording to known pages and controls.
-- Data should stay deterministic and side-effect free so Search and Assistant can share it.
local addonName, MSUF = ...
MSUF = MSUF or {}

local M = MSUF.MSUF2 or {}
MSUF.MSUF2 = M

local Data = M.SearchData or {}
M.SearchData = Data
local Lines = M.Lines or function(rows) return tostring(rows or ""):gmatch("[^\r\n]+") end
local KeySetFromWords = M.KeySetFromWords or function(text)
    local out = {}
    for word in tostring(text or ""):gmatch("%S+") do out[word] = true end
    return out
end

-- Search query alias catalogue.
-- Expands human terms and common misspellings into the canonical search keywords used by the
-- index/query layer. This is declarative data; routing/rendering live in other search shards.
local ZERO_INDEX_ALIASES = KeySetFromWords [[
    debuff debuffs dispel dispels dispell dispellable dispelable cleansing cleanse decurse cure magic curse poison disease bleed
    stealable purge spellsteal aggro threat highlight highlights border borders glow overlay stripe priority
]]

local function TermList(text, zeroIndex)
    local list = {}
    if zeroIndex then list[0] = false end
    for term in tostring(text or ""):gmatch("[^|]+") do
        list[#list + 1] = term
    end
    return list
end

local function AliasMap(rows)
    local aliases = {}
    local function Add(keys, terms)
        for key in tostring(keys or ""):gmatch("[^|]+") do
            aliases[key] = TermList(terms, ZERO_INDEX_ALIASES[key])
        end
    end
    if type(rows) == "string" then
        for line in Lines(rows) do
            local keys, terms = line:match("^([^=]+)=(.*)$")
            Add(keys, terms)
        end
    else
        for i = 1, #rows, 2 do Add(rows[i], rows[i + 1]) end
    end
    return aliases
end

Data.QUERY_ALIASES = AliasMap [[
evoker=empowered|empower|empowered casts|stage|stages|hold cast|release cast|quell|essence|augmentation|devastation|preservation
devastation|preservation=evoker|empowered|empower|empowered casts|essence
augmentation=evoker|empowered|empower|empowered casts|essence|ebon might
empower=empowered|empowered casts|stage|stages|hold cast|release cast
empowered=empower|empowered casts|stage|stages|hold cast|release cast
stage|stages=empowered|empowered casts|blink|castbar
demonhunter=demon hunter|dh|havoc|vengeance|disrupt|consume magic|devour|interrupt|kick|interrupt ready
dh=demon hunter|demonhunter|havoc|vengeance|disrupt|consume magic|devour|interrupt|kick|interrupt ready
havoc|vengeance=demon hunter|demonhunter|dh|disrupt|consume magic|interrupt|kick
devour=consume|consume magic|purge|dispel|disrupt|interrupt|kick|interrupt ready
consume=consume magic|devour|purge|dispel|interrupt|kick
disrupt=demon hunter|demonhunter|dh|interrupt|kick|focus kick|interrupt ready
kick|kicks=interrupt|interrupt ready|focus kick|counterspell|disrupt|pummel|rebuke|wind shear|mind freeze|muzzle|skull bash|spear hand strike|counter shot|quell|silence
interrupt=kick|interrupt ready|focus kick|counterspell|disrupt|pummel|rebuke|wind shear|mind freeze|muzzle|skull bash|spear hand strike|counter shot|quell|silence
interrupts=kick|interrupt|interrupt ready|focus kick
counterspell=interrupt|kick|interrupt ready|focus kick
pummel|rebuke|silence=interrupt|kick|interrupt ready
windshear=wind shear|interrupt|kick|interrupt ready
quell=evoker|interrupt|kick|interrupt ready
cast|casting=castbar|cast bar|spell name|channel
castbar=cast bar|casts|casting|spell name|channel
castbars=castbar|cast bar|casts|casting|spell name|channel
zauberleiste=castbar|cast bar|casts|casting
level=level indicator|level text|show level|unit level|player level|target level|status icons|status indicator|indicator|anchor level|level anchor|position level|level position|x offset|y offset
levels=level|level indicator|level text|show level|status icons|status indicator
lvl=level|level indicator|level text|show level
leveltext=level text|level indicator|show level|status icons|status indicator|anchor|position|x offset|y offset
levelindicator=level indicator|level text|show level|status icons|status indicator|anchor|position|x offset|y offset
statusindicator=status indicator|status icons|indicator|level indicator|level text|enabled|anchor|size|layer|x offset|y offset
statusindicators=status indicators|status icons|indicator|level indicator|level text|enabled|anchor|size|layer|x offset|y offset
indicator=indicators|status icons|status indicator|selected indicator|level indicator|group status and indicators|group indicators
indicators=indicator|status icons|status indicators|selected indicator|level indicator|group status and indicators|group indicators
turn=enable|disable|show|hide|enabled|disabled|visible|hidden
off=disable|hide|disabled|hidden
onoff=enable|disable|show|hide|enabled|disabled
greyed|grayed=disabled|locked|shared setting|unit auras|custom caps|max buffs|max debuffs
showbuffs=show buffs|unit auras|display|shared setting|custom caps|max buffs
maxbuffs=max buffs|buff cap|caps & icons|hide buffs|custom caps
customcaps=custom caps|caps & icons|max buffs|max debuffs|unit override
positioning=position|positions|move|edit mode|x offset|y offset|anchor|anchoring
background=bar background tint|background tint|background opacity|background alpha|backdrop|bg|bar colors|transparency|alpha|unitframe colors
backgrond|backgroud|backround|bakground|hintergrund|backdrop=background|bar background tint|background tint|bg
bg=background|bar background tint|background tint|background opacity|background alpha
alpha=opacity|transparency|fade|background alpha|in combat|out of combat
opacity=alpha|transparency|fade|background opacity|in combat|out of combat
transparent=transparency|alpha|opacity|fade
transparency=alpha|opacity|fade|background
fade=alpha|opacity|transparency|range fade|out of range
fades|faded=fade|alpha|opacity|range fade|out of range
range=range fade|out of range|range alpha|range check|distance|distance check
rangecheck=range check|range fade|out of range|distance check|unit frame range check|out of range alpha|range fade affects
rangechecker|distancecheck=range check|range fade|out of range|distance check|unit frame range check
distance=range|range fade|out of range|range check|distance check|alpha
outofrange=out of range|range fade|range alpha|range check|distance
check=range check|range fade|out of range|distance check|ready check|version check
checker|checking=check|range check|range fade|out of range
reichweite|reichweiten=range|range fade|out of range|range check|distance
reichweitencheck=range check|range fade|out of range|distance check
entfernung=distance|range|range fade|out of range|range check
ausserhalb=out of range|range fade|range check
misc=miscellaneous|global style|tooltips|blizzard frames|language|startup
miscellaneous=misc|global style|tooltips|blizzard frames|language|startup
verschiedenes=misc|miscellaneous|global style|tooltips|blizzard frames|language|startup
move|moving=edit mode|position|positions|drag|x offset|y offset|anchor|anchoring
drag=edit mode|move|position|x offset|y offset
position=positions|move|edit mode|x offset|y offset|anchor|anchoring
positions=position|move|edit mode|x offset|y offset|anchor|anchoring|reset positions
anchor=anchoring|position|move|attach|global anchor|custom anchor
anchoring=anchor|position|move|attach|global anchor|custom anchor
unitframe|unitframes=unit frame|unit frames|player frame|target frame|focus frame|focus target frame|boss frame|frame basics|anchoring|edit mode
unitfram|unitfrme=unitframe|unit frame|unit frames|frame basics|anchoring|edit mode
player=player frame|playerframe
target=target frame|targetframe
focus=focus frame|focusframe
focustarget=focus target frame|focus target|ft frame
pet=pet frame|petframe
fram=frame|unit frame|frames|frame basics
frame=unit frame|frames|unitframe|frame basics
frames=unit frames|unitframe|frame basics|edit mode
playerframe=player frame|move player frame|drag player frame|player position|unit frame|frame basics|anchoring|edit mode
targetframe=target frame|move target frame|drag target frame|target position|unit frame|frame basics|anchoring|edit mode
focusframe=focus frame|move focus frame|drag focus frame|focus position|unit frame|frame basics|anchoring|edit mode|focus kick
focustargetframe=focus target frame|move focus target frame|drag focus target frame|focus target position|unit frame|frame basics|anchoring|edit mode
petframe=pet frame|move pet frame|drag pet frame|pet position|unit frame|frame basics|anchoring|edit mode
bossframe=boss frame|boss frames|unit frame|boss layout
bossframes=boss frame|boss frames|unit frame|boss layout|boss preview
size=width|height|scale|frame basics|frame scaling
resize=size|width|height|scale|frame basics|frame scaling
bigger|smaller=size|scale|width|height|font size
big=bigger|size|scale|width|height|font size
small=smaller|size|scale|width|height|font size|text size|icon size
scale=size|frame scaling|menu scale|ui scale
smooth|smoothfill=smooth fill|smooth health fill|smooth power bar|bar animation|soft fill|fluid fill|weiche fuellung
softfill|fluidfill|fuellung|fuellen=smooth fill|smooth health fill|smooth power bar|bar animation|weiche fuellung
rounded=rounded texture|rounded frame texture|rounded frames|round corners|unit frames|group frames|power bars|mouseover highlights|bars
round=rounded|rounded texture|rounded frames|round corners|corners|bars
corners=rounded|rounded texture|rounded frames|round corners|frame corners|bars
corner=corners|rounded|round corners|frame corners
roundedframes=rounded frames|rounded frame texture|rounded texture|unit frames|group frames|bars
roundedtexture=rounded texture|rounded frame texture|rounded frames|bars
rund|runde|abrunden|abrundung|abgerundet|abgerundete|abgerundeten=rounded|rounded frames|round corners|rounded texture|bars
kanten|ecken=corners|rounded|round corners|rounded frames|bars
einschalten|anschalten|aktivieren=enable|turn on|on|show
ausschalten|abschalten|deaktivieren=disable|turn off|off|hide
weich|weiche|weichen|sanft|sanfte=smooth fill|smooth health fill|smooth power bar|soft fill|weiche fuellung
fluessig|fluessige=smooth fill|smooth health fill|smooth power bar|fluid fill|weiche fuellung
relleno|llenado|suave|remplissage|riempimento|preenchimento=smooth fill|soft fill|fluid fill|bar animation
fluido|fluida|fluide=smooth fill|fluid fill|bar animation
animacion|animacao=bar animation|smooth fill
doux|douce|morbido|morbida=smooth fill|soft fill|bar animation
hp=health|health text|health bar|leben
health=hp|health text|health bar|life|leben
leben=health|hp|health bar|health text
name|names=name text|text|font|name shortening
shorten|shortened|shortens|shortening|truncated|kuerzen|gekuerzt|namenskuerzung|namenskurzung|kuerzung=name shortening|short names|truncate names|max name length
override|overrides=custom settings|font override|scope override|group frame override|shared changes
fontoverride=font override|custom font settings|name shortening|shared changes
scopeoverride=scope override|font override|custom settings|shared changes
groupoverride=group frame override|font override|group frames|name shortening
text=font|fonts|name text|health text|power text|spell name
font=fonts|text|font size|outline|shadow
fonts=font|text|font size|outline|shadow
mana=power|power bar|alternative mana|alt mana
power=mana|power bar|class resources|resource
resource|resources=class resources|classpower|power|combo points|essence
profile=profiles|import|export|copy profile|spec profiles|wago
profiles=profile|import|export|copy profile|spec profiles|wago
import=profiles|profile|import string|wago|legacy import
export=profiles|profile|export string|copy profile|wago
wago=profiles|import|export|profile string
reload=refresh|apply|not updating|profile|reset
reset=reset positions|factory reset|profile reset|profiles
broken=not updating|reset positions|profile reset|reload|factory reset
broke=broken|not updating|reset positions|profile reset|reload
bugged=broken|not updating|reload|reset positions
wrong=not updating|colors|profile|reset
missing=not visible|hidden|invisible|gone|load conditions
gone=missing|not visible|hidden|invisible
invisible=not visible|hidden|alpha|transparency|range fade
hidden=hide|show|enable|disable|not visible
show=enable|visible|not hidden
hide=disable|hidden|not visible
disabled|enabled=enable|show|frame basics
offscreen=reset positions|move|edit mode|position
overlap=text layer|position|anchor|offset|frame level
overlapping=overlap|text layer|position|anchor|offset
lag|fps=performance|auras|cooldown|filters
bad=wrong|broken|performance|lag|fps
performance=auras|cooldown|filters|range fade
combat=combat lockdown|in combat|out of combat|alpha|settings
lockdown=combat lockdown|combat|protected frames|reload
raidframes=group frames|groupframes|raid frames|raid frame|raid|party|layout|group layout|anchoring|move raid frames|disable raid frames|hide raid frames|turn off raid frames|raid frames off
partyframes=group frames|groupframes|party frames|party frame|party|raid|layout|group layout|anchoring|move party frames|disable party frames|hide party frames|turn off party frames|party frames off
gruppenframes|group|groupframes=group frames|party|raid|layout|disable group frames|hide group frames|turn off group frames
raid=group frames|groupframes|raid frames|raid frame|layout|party|anchoring|move raid frames|disable raid frames|hide raid frames|turn off raid frames|raid frames off
party=group frames|groupframes|party frames|party frame|layout|raid|anchoring|move party frames|disable party frames|hide party frames|turn off party frames|party frames off
tank|tanks=tank role|show tank power|tank power|tank power bar|role power|group frames
healer|healers=healer role|show healer power|healer power|healer power bar|healer mana|role power|group frames
dps|damager|damage=damage role|damager role|show dps power|show damager power|dps power|damager power|dps power bar|role power|group frames
debuff=debuffs|auras|aura|buffs|dispellable debuffs|dispel border|dispel overlay|debuff stripe|magic|curse|poison|disease|any debuff
debuffs=debuff|auras|aura|buffs|dispellable debuffs|dispel border|dispel overlay|debuff stripe|magic|curse|poison|disease|any debuff
buff=buffs|auras|aura|debuffs
buffs=buff|auras|aura|debuffs
aura=auras|buffs|debuffs|cooldown|aura filters
auras=aura|buffs|debuffs|cooldown|aura filters
hot=hots|healer buffs|own buffs|aura indicators|group buffs
hots=hot|healer buffs|own buffs|aura indicators|group buffs
own|personal=only mine|own buffs|own debuffs|player only|aura filters
spellid|spellids=spell id|aura blacklist|aura filters
bossdebuff|bossdebuffs=boss debuffs|raid debuffs|aura filters
dispel=dispel border|dispel overlay|dispellable debuffs|dispel border detects|any dispel-type debuff|any debuff|magic|curse|poison|disease|cleanse|decurse|group status and indicators|group indicators|highlight borders
dispels=dispel|dispel border|dispel overlay|dispellable debuffs|magic|curse|poison|disease
dispell=dispel|dispel border|dispel overlay|dispellable debuffs|cleanse|decurse
dispellable=dispellable debuffs|dispel border detects|dispellable by me|any dispel-type debuff|magic|curse|poison|disease
dispelable=dispellable|dispellable debuffs|dispel border detects
cleansing=cleanse|dispel|dispellable debuffs|magic|curse|poison|disease
cleanse=dispel|dispellable debuffs|magic|curse|poison|disease
decurse=curse|dispel|dispellable debuffs
cure=cleanse|dispel|poison|disease|dispellable debuffs
magic=dispel|dispellable debuffs|dispel border detects|dispel test type
curse=dispel|decurse|dispellable debuffs|dispel border detects|dispel test type
poison|disease=dispel|cleanse|dispellable debuffs|dispel border detects|dispel test type
bleed=debuff|any debuff|dispel test type
stealable=auras|buffs|purge|dispel|spellsteal|purge border|offensive dispel
purge=dispel|stealable|auras|buffs|purge border|spellsteal|offensive dispel
spellsteal=stealable|purge|purge border|offensive dispel|buffs
pandemic=colors|auras|cooldown text|debuffs|timer
timer=cooldown text|aura timers|cast time|combat timer
cooldown=cooldown text|cooldown swipe|aura timers|interrupt ready
cooldowns=cooldown|cooldown text|cooldown swipe|aura timers|interrupt ready
blacklist=ignore list|global ignore list|hide aura|hide buff|hide debuff|unit auras|aura filters
ignore=ignore list|global ignore list|blacklist|hide aura|hide buff|hide debuff|unit auras
absorb=absorbs|absorb display|heal prediction|health
absorbs=absorb|absorb display|heal prediction|health
heal=heal prediction|incoming heals|health|healer
aggro=threat|aggro|aggro border|highlight borders|indicators|highlight priority
threat=aggro|threat border|highlight borders|indicators|highlight priority
blizzard|default|blizzardframes=blizzard frames|default frames|hide blizzard|disable blizzard
unlock=edit mode|move|drag|frames unlocked|lock frames
locked=edit mode|move|drag|frames locked|lock frames|disabled|shared setting|custom caps
solo=show solo|show player solo|party frames solo|group frames
self=player|show player|hide player|party frames
tooltip=tooltips|unitframe tooltips|group frame tooltips|mouseover tooltip
tooltips=tooltip|unitframe tooltips|mouseover tooltip
language=locale|localization|translation|sprache
sprache=language|locale|localization|translation
click=click cast|clickthrough|click-through|mouse|mouseover|target modifier
clickcast=click cast|click casting|mouse|targeting
clickthrough=click-through|click through|mouse|unitframe tooltips
mouseover=mouse|mouseover highlight|tooltip|click cast|targeting
menu=dashboard|menu scale|ui scale|search|support
window=menu|dashboard|reset positions|ui scale
ui=ui scale|menu scale|dashboard
unit|units=unit frame|unit frames|unitframe|frame basics
einheit=unit|unit frame|unitframe
einheiten=unit|unit frames|unitframe
einheitenfenster=unit frame|unitframe|frames
spieler=player|player frame|playerframe
spielerframe=player frame|playerframe|unit frame
ziel=target|target frame|targetframe
zielframe=target frame|targetframe|unit frame
zielziel=target of target|targettarget|tot
tot=target of target|targettarget|target target
targettarget=target of target|tot|target target
fokusziel|focusziel|ft=focus target|focustarget|focus target frame
fokus=focus|focus frame|focusframe|focus kick
fokusframe=focus frame|focusframe|focus kick
begleiter|haustier=pet|pet frame|petframe
enable=show|visible|frame basics|aktivieren
disable=hide|hidden|frame basics|deaktivieren
visible=show|enable|sichtbar
aktivieren=enable|show|visible
deaktivieren|abschalten=disable|hide|hidden
anzeigen=show|visible|enable
ausblenden=hide|hidden|disable
ausgegraut=disabled|locked|shared setting|custom caps|unit auras
grau=disabled|locked|shared setting
sichtbar=visible|show|enable
unsichtbar=invisible|hidden|alpha|transparency
versteckt=hidden|hide|disable
verschieben=move|drag|position|edit mode|anchor
bewegen=move|drag|position|edit mode
ziehen=drag|move|edit mode
verankern|anker=anchor|anchoring|position
koordinaten=x offset|y offset|position|anchor
editmode=edit mode|move|drag|position
loadconditions=load conditions|visibility|show|hide
breite=width|size|resize|frame basics
hoehe=height|size|resize|frame basics
groesse=size|resize|scale|width|height
skalierung=scale|size|frame scaling|ui scale
layout=group frames|frame basics|growth|sorting|anchoring
sorting=sort|role order|group frames|layout
sortierung=sorting|role order|group frames|layout
growth=growth direction|layout|group frames
spalten=columns|layout|group frames
reihen=rows|layout|auras|group frames
rolle=role|role icon|sorting|tank|healer|dps
role=role icon|sorting|tank|healer|dps
groupnumber=group number|indicators|group frames
tank|dps=role icon|group status and indicators|group indicators|sorting
healer=role icon|healer buffs|group status and indicators|group indicators
healthbar=health bar|health|hp|bar colors
powerbar=power bar|power|mana|class resources
lebensbalken=health bar|health|hp
energieleiste=power bar|power|mana
manabar=mana|power bar|power
color=colors|bar colors|unitframe colors|class colors
colours=colors|color|bar colors
farbe|farben=colors|color|bar colors|class colors
klassfarbe|classcolor=class color|class colors|health color
reaction=reaction color|npc type colors|colors
npc=npc type colors|reaction color|colors
highlight=highlights|mouseover highlight|highlight borders|dispel highlight|aggro border|target border|focus highlight|highlight priority|colors|bars
highlights=highlight|highlight borders|dispel highlight|aggro border|target border|focus highlight|highlight priority|mouseover highlight
border=borders|highlight borders|frame outline|dispel border|aggro border|purge border|target border|focus highlight|group border
borders=border|highlight borders|frame outline|dispel border|aggro border|purge border|target border|focus highlight|group border
glow=focus glow|highlight borders
overlay=dispel overlay|unitframe dispel overlay|overlay style|overlay opacity|health bar tint
stripe=debuff stripe|stripe edge|stripe height|stripe opacity|debuff filter
priority=highlight priority|dispel priority|aggro priority|target priority|focus priority
fontsize=font size|text size|fonts|text
textsize=text size|font size|fonts|text
schrift=font|fonts|text|font size
schriftart=font|fonts|font family
schriftgroesse=font size|text size|fonts
namen=names|name text|name shortening
ueberschreiben|ueberschreibung=override|font override|custom settings
realm|server=realm names|name shortening|short names
truncate=name shortening|short names|max name length
nameshortening=name shortening|short names|truncate names|realm names
healthtext=health text|hp text|text|fonts
powertext=power text|mana text|text|fonts
nametext=name text|text|fonts|name shortening
stufe|stufen=level|level indicator|level text|show level|status icons
stufentext=level text|level indicator|show level|status icons|anchor|position
levelanzeige=level indicator|level text|show level|status icons|anchor|position
statusanzeige=status indicator|status icons|indicator|level indicator
portrait=portraits|portrait mode|class icon|2d portrait|3d portrait
portraits=portrait|portrait mode|class icon
avatar|portraet=portrait|portraits|class icon
portraitdeko=portrait decoration|modules|style
castbalken|zauberbalken=castbar|cast bar|casting
spell=spell name|castbar|auras|spell id
spellname=spell name|castbar|name shortening
interruptready=interrupt ready|focus kick|kick|castbar
kanal|kanalisieren=channel|channel ticks|castbar
unterbrechen=interrupt|kick|focus kick|interrupt ready
fokuskick=focus kick|interrupt|kick|castbar
stack=stacks|aura stack count|auras
stacks=stack|aura stack count|auras
stapel=stacks|stack|auras
cooldowntext=cooldown text|timer|auras
swipe=cooldown swipe|auras|cooldown
staerkungszauber=buffs|buff|auras
zauber=spell|auras|castbar|spell id
gruppe|gruppen|gruppenrahmen|gruppenfenster=group frames|groupframes|party|raid|layout|disable group frames|hide group frames|turn off group frames
raidframe=raid frames|raidframes|group frames|layout|disable raid frames|hide raid frames|turn off raid frames|raid frames off
partyframe=party frames|partyframes|group frames|layout|disable party frames|hide party frames|turn off party frames|party frames off
schlachtzug=raid|raid frames|group frames|disable raid frames|hide raid frames|turn off raid frames
mythic=mythic raid|raid|group frames
readycheck|bereitschaft=ready check|status icons|group status and indicators|group indicators
statusicon|statusicons=status icons|indicators|dead|offline|ready check
marker=raid marker|markers|indicators
raidmarker=raid marker|marker|indicators
leader=leader icon|status icons|indicators
assist=assist icon|status icons|indicators
offline=offline icon|status icons|indicators
afk=afk icon|status icons|indicators
dead=dead icon|ghost|status icons|indicators
profil=profile|profiles|import|export
importieren=import|profiles|wago|profile string
exportieren=export|profiles|profile string
kopieren=copy profile|profiles|import|export
teilen=share profile|export|wago
backup=profiles|export|copy profile
restore=profiles|import|reset
minimap|minimapicon|minimapbutton=minimap icon|minimap button|miscellaneous
minikarte=minimap|minimap icon|miscellaneous
sound=sounds|target sound|target lost|miscellaneous
sounds=sound|target sound|target lost|miscellaneous
targetsound=target sound|target lost|sounds|miscellaneous
versioncheck=version check|miscellaneous|startup
menuscale=menu scale|dashboard|ui scale
uiscale=ui scale|dashboard|menu scale
unitauras=unit auras|auras|buffs|debuffs
globalstyle=global style|bars|fonts|colors|castbar|miscellaneous
standardframes=default frames|blizzard frames|hide blizzard
crosshair=combat crosshair|gameplay|melee range spell|range check
fadenkreuz=crosshair|combat crosshair|gameplay|melee range spell
melee=melee range spell|crosshair|range check
maus=mouse|mouseover|click cast|targeting
maustaste=mouse buttons|click cast|targeting
klick|klicken=click|click cast|clickthrough|targeting
heilung=heal|healer|click cast|mouseover
mouseoverheal=mouseover heal|click cast|healing
ruckelt|haengt=lag|fps|performance
langsam=slow|performance|lag|fps
cpu=performance|auras|cooldown
speicher=performance|auras|profiles
optimieren=performance|auras|fps
classpower=class resources|power|resource
classresourceshape|classpowershape|resourceshape=class resources|shape|class resource shape|combo point shape
combopointshape|combopointsshape=combo points|class resources|shape|class resource shape
playerpowershape|detachedpowershape|powerbarshape=player power shape|detached power bar|shape|class resources
orb|orbs|manaorb|powerorb|manaorbs|powerorbs|manaball|powerball|powersphere=player power shape|detached power bar|orb|orb size|power orb
connectedpowerbar|managedpowerbar|managedpowertext|classresourcepowerbar=class resources|detached power bar|power text|anchor to class resource|sync width
playerhpbar|duplicatehp|secondhp|secondhealth|classresourcehealth|classresourcehp=class resources|player hp bar|health text|foreground texture|background texture|anchor|width mode|hp shape|follow player power|orb size|hp color|class color|dark mode|hp gradient|smooth fill|use player hp text|shared text
playerhpshape|secondhpshape|duplicatehpshape|healthorb|hporb=class resources|player hp bar|hp shape|follow player power|round|crystal|orb|orb size
playerhpcolor|secondhpcolor|duplicatehpcolor|classresourcehpcolor=class resources|player hp bar|hp color|class color|dark mode|hp gradient|global color
healthduplicate|doppelhp|zweitehp|zweitehealth|lebenzweimal=class resources|player hp bar|second player hp bar|health text
shapepreset|shapepresets|stylepreset|stylepresets=class resources|shape|class resource shape|preset|clean dots|gems|hex pips|compact
cleandots|dots|dotpips=class resources|shape|class resource shape|circle|shape preset
gems|gemshape=class resources|shape|class resource shape|diamond|shape preset
hexpips|hexshape=class resources|shape|class resource shape|hex|shape preset
autofit|autofitpips|fitpips=class resources|width mode|auto fit pips|shape alignment
pipalignment|shapealignment|alignpips=class resources|shape alignment|class resource alignment
klassenressourcen|klassenressource=class resources|classpower|resource
combopoints=combo points|class resources|rogue
soulshards=soul shards|class resources|warlock
runen=runes|runic power|class resources
eclipse=eclipse|class resources|druid
stagger=stagger|class resources|brewmaster
]]
