CustomMageArcaneOrbOptions = {
    name = "|cFF40C7EB自訂法師秘法寶珠條|r",
    type = "group",
    args = {
        enableCustomArcaneOrb = {
            name = "啟用自訂秘法寶珠條",
            desc = "顯示自訂秘法寶珠條。停用則使用預設的個人資源條秘法寶珠。",
            type = "toggle",
            get = function() return CustomMageArcaneOrbDB.enabled ~= false end,
            set = function(_, val) CustomMageArcaneOrbDB.enabled = val if UpdateMageArcaneOrbEnabled then UpdateMageArcaneOrbEnabled() end end,
            order = 0.5,
        },
        arcaneOrbWidth = {
            name = "秘法寶珠寬度 (每顆)",
            desc = "設定每顆秘法寶珠的寬度。若已設定「總條寬度」，此選項將被忽略。",
            type = "range",
            min = 10,
            max = 100,
            step = 0.001,
            get = function() return CustomMageArcaneOrbDB.arcaneOrbWidth end,
            set = function(_, val) CustomMageArcaneOrbDB.arcaneOrbWidth = val if UpdateArcaneOrbs then UpdateArcaneOrbs() end end,
            order = 1,
        },
        totalWidth = {
            name = "整條寬度",
            desc = "設定所有秘法寶珠合併的總寬度。若設定，寶珠將自動適配此寬度。",
            type = "range",
            min = 60,
            max = 600,
            step = 0.1,
            get = function() return CustomMageArcaneOrbDB.totalWidth or 0 end,
            set = function(_, val) if val > 0 then CustomMageArcaneOrbDB.totalWidth = val else CustomMageArcaneOrbDB.totalWidth = nil end if UpdateArcaneOrbs then UpdateArcaneOrbs() end end,
            order = 1.5,
        },
        arcaneOrbHeight = {
            name = "秘法寶珠高度",
            desc = "設定每顆秘法寶珠的高度。",
            type = "range",
            min = 10,
            max = 100,
            step = 0.001,
            get = function() return CustomMageArcaneOrbDB.arcaneOrbHeight end,
            set = function(_, val) CustomMageArcaneOrbDB.arcaneOrbHeight = val if UpdateArcaneOrbs then UpdateArcaneOrbs() end end,
            order = 2,
        },
        arcaneOrbBgColor = {
            name = "秘法寶珠背景顏色",
            desc = "設定秘法寶珠的背景顏色。",
            type = "color",
            hasAlpha = true,
            get = function() local c = CustomMageArcaneOrbDB.arcaneOrbBgColor or {0, 0, 0, 0.5} return c[1], c[2], c[3], c[4] end,
            set = function(_, r, g, b, a) CustomMageArcaneOrbDB.arcaneOrbBgColor = {r, g, b, a} if UpdateArcaneOrbs then UpdateArcaneOrbs() end end,
            order = 3,
        },
        arcaneOrbFillColor1 = {
            name = "秘法寶珠填充顏色 1",
            desc = "設定第一顆秘法寶珠的填充顏色。",
            type = "color",
            hasAlpha = true,
            get = function() local c = CustomMageArcaneOrbDB.arcaneOrbFillColors[1] or {0.2, 0.4, 1, 1} return c[1], c[2], c[3], c[4] end,
            set = function(_, r, g, b, a) CustomMageArcaneOrbDB.arcaneOrbFillColors[1] = {r, g, b, a} if UpdateArcaneOrbs then UpdateArcaneOrbs() end end,
            order = 4,
        },
        arcaneOrbFillColor2 = {
            name = "秘法寶珠填充顏色 2",
            desc = "設定第二顆秘法寶珠的填充顏色。",
            type = "color",
            hasAlpha = true,
            get = function() local c = CustomMageArcaneOrbDB.arcaneOrbFillColors[2] or {0.2, 0.4, 1, 1} return c[1], c[2], c[3], c[4] end,
            set = function(_, r, g, b, a) CustomMageArcaneOrbDB.arcaneOrbFillColors[2] = {r, g, b, a} if UpdateArcaneOrbs then UpdateArcaneOrbs() end end,
            order = 5,
        },
        arcaneOrbFillColor3 = {
            name = "秘法寶珠填充顏色 3",
            desc = "設定第三顆秘法寶珠的填充顏色。",
            type = "color",
            hasAlpha = true,
            get = function() local c = CustomMageArcaneOrbDB.arcaneOrbFillColors[3] or {0.2, 0.4, 1, 1} return c[1], c[2], c[3], c[4] end,
            set = function(_, r, g, b, a) CustomMageArcaneOrbDB.arcaneOrbFillColors[3] = {r, g, b, a} if UpdateArcaneOrbs then UpdateArcaneOrbs() end end,
            order = 6,
        },
        arcaneOrbFillColor4 = {
            name = "秘法寶珠填充顏色 4",
            desc = "設定第四顆秘法寶珠的填充顏色。",
            type = "color",
            hasAlpha = true,
            get = function() local c = CustomMageArcaneOrbDB.arcaneOrbFillColors[4] or {0.2, 0.4, 1, 1} return c[1], c[2], c[3], c[4] end,
            set = function(_, r, g, b, a) CustomMageArcaneOrbDB.arcaneOrbFillColors[4] = {r, g, b, a} if UpdateArcaneOrbs then UpdateArcaneOrbs() end end,
            order = 7,
        },
        gradientColoringEnabled = {
            name = "啟用漸層色",
            desc = "根據位置啟用秘法寶珠的漸層著色。",
            type = "toggle",
            get = function() return CustomMageArcaneOrbDB.gradientColoringEnabled end,
            set = function(_, val) CustomMageArcaneOrbDB.gradientColoringEnabled = val if UpdateArcaneOrbs then UpdateArcaneOrbs() end end,
            order = 8,
        },
        gradientColorStart = {
            name = "漸層起始色",
            desc = "設定漸層著色的起始顏色。",
            type = "color",
            hasAlpha = true,
            get = function() local c = CustomMageArcaneOrbDB.gradientColorStart or {0, 0, 1, 1} return c[1], c[2], c[3], c[4] end,
            set = function(_, r, g, b, a) CustomMageArcaneOrbDB.gradientColorStart = {r, g, b, a} if UpdateArcaneOrbs then UpdateArcaneOrbs() end end,
            order = 9,
        },
        gradientColorEnd = {
            name = "漸層結束色",
            desc = "設定漸層著色的結束顏色。",
            type = "color",
            hasAlpha = true,
            get = function() local c = CustomMageArcaneOrbDB.gradientColorEnd or {1, 1, 0, 1} return c[1], c[2], c[3], c[4] end,
            set = function(_, r, g, b, a) CustomMageArcaneOrbDB.gradientColorEnd = {r, g, b, a} if UpdateArcaneOrbs then UpdateArcaneOrbs() end end,
            order = 10,
        },
        anchorToPRD = {
            name = "對齊到個人資源條",
            desc = "將秘法寶珠條對齊到個人資源條。",
            type = "toggle",
            get = function() return CustomMageArcaneOrbDB.anchorToPRD end,
            set = function(_, val) CustomMageArcaneOrbDB.anchorToPRD = val if UpdateMageArcaneOrbSettings then UpdateMageArcaneOrbSettings() end end,
            order = 11,
        },
        anchorPosition = {
            name = "對齊位置",
            desc = "將寶珠條置於個人資源條的上方或下方。",
            type = "select",
            values = {
                ABOVE = "上方",
                BELOW = "下方",
            },
            get = function() return CustomMageArcaneOrbDB.anchorPosition end,
            set = function(_, val)
                CustomMageArcaneOrbDB.            anchorPosition = val if UpdateMageArcaneOrbSettings then UpdateMageArcaneOrbSettings() end end,
            order = 12,
        },
        anchorOffset = {
            name = "對齊偏移量",
            desc = "從個人資源條對齊點的偏移量。",
            type = "range",
            min = -50,
            max = 50,
            step = 1,
            get = function() return CustomMageArcaneOrbDB.anchorOffset or 10 end,
            set = function(_, val) CustomMageArcaneOrbDB.anchorOffset = val if UpdateMageArcaneOrbSettings then UpdateMageArcaneOrbSettings() end end,
            order = 13,
        },
        anchorTarget = {
            name = "對齊目標",
            desc = "要對齊到哪個個人資源條。",
            type = "select",
            values = {
                HEALTH = "血量條",
                POWER = "能量條",
            },
            get = function() return CustomMageArcaneOrbDB.anchorTarget end,
            set = function(_, val) CustomMageArcaneOrbDB.anchorTarget = val if UpdateMageArcaneOrbSettings then UpdateMageArcaneOrbSettings() end end,
            order = 14,
        },
        locked = {
            name = "鎖定位置",
            desc = "鎖定寶珠條位置以避免意外移動。",
            type = "toggle",
            get = function() return CustomMageArcaneOrbDB.locked end,
            set = function(_, val) CustomMageArcaneOrbDB.locked = val end,
            order = 15,
        },
        debug = {
            name = "除錯模式",
            desc = "啟用除錯訊息輸出。",
            type = "toggle",
            get = function() return CustomMageArcaneOrbDB.debug end,
            set = function(_, val) CustomMageArcaneOrbDB.debug = val end,
            order = 16,
        },
    },
}

_G.CustomMageArcaneOrbOptions = CustomMageArcaneOrbOptions