local addonName, ham = ...

-- Retail - Mage-conjured (restores both health and mana)
ham.conjuredManaBun = ham.Item.new(113509, "Conjured Mana Bun", { conjured = true })

-- Retail - Mage-conjured food (health only; the mana-restoring counterpart, Conjured Tea,
-- is declared in Core/Drink.lua). Reskins of the same conjured mechanic.
ham.conjuredSouffle = ham.Item.new(265096, "Conjured Souffle", { conjured = true })
ham.conjuredCinnamonRoll2 = ham.Item.new(265097, "Conjured Cinnamon Roll", { conjured = true })
ham.conjuredCroissant2 = ham.Item.new(265098, "Conjured Croissant", { conjured = true })

-- Retail - communal feast: Well Fed with a secondary stat, restores both health and mana.
-- "Hearty" is the same recipe at a higher crafting quality (Hearty Well Fed also persists through death).
ham.heartyFeastOfKnowledge = ham.Item.new(275269, "Hearty Feast of Knowledge", { buffFood = true })
ham.feastOfKnowledge = ham.Item.new(275266, "Feast of Knowledge", { buffFood = true })

-- Retail - personal Well Fed food: flat primary stat, restores health only.
ham.heartyRoyalRoast = ham.Item.new(242747, "Hearty Royal Roast", { buffFood = true })
ham.royalRoast = ham.Item.new(242275, "Royal Roast", { buffFood = true })

-- Retail - other current-tier "Well Fed" food (communal feast or personal, either primary or
-- secondary stat). Wowhead's Food & Drinks category lists dozens of cosmetic name/icon reskins
-- of the same few mechanics at the current level cap; these are the confirmed Well Fed ones,
-- included individually since a given player only ever owns one specific reskin.
-- (Spirit Sprouts (280422) was checked and excluded: it restores spirit while dead, not
-- health/mana, so it's a different mechanic entirely and out of scope for this macro.)
ham.beledarsBounty = ham.Item.new(222728, "Beledar's Bounty", { buffFood = true })
ham.heartyAuthenticUndermineClamChowder = ham.Item.new(235853, "Hearty Authentic Undermine Clam Chowder", { buffFood = true })
ham.pocketPizza = ham.Item.new(233062, "Pocket Pizza", { buffFood = true })
ham.incontinentalTakeout = ham.Item.new(233118, "Incontinental Takeout", { buffFood = true })
ham.amaniCornucopia = ham.Item.new(275264, "Amani Cornucopia", { buffFood = true })
ham.arcanoCutlets = ham.Item.new(242287, "Arcano Cutlets", { buffFood = true })
ham.bakedLuckyLoa = ham.Item.new(242279, "Baked Lucky Loa", { buffFood = true })
ham.bloodthistleWrappedCutlets = ham.Item.new(242296, "Bloodthistle-Wrapped Cutlets", { buffFood = true })
ham.bloomSkewers = ham.Item.new(242302, "Bloom Skewers", { buffFood = true })
ham.bloomingFeast = ham.Item.new(242273, "Blooming Feast", { buffFood = true })
ham.braisedBloodHunter = ham.Item.new(242276, "Braised Blood Hunter", { buffFood = true })
ham.butteredRootCrab = ham.Item.new(242280, "Buttered Root Crab", { buffFood = true })
ham.championsBento = ham.Item.new(242274, "Champion's Bento", { buffFood = true })
ham.crimsonCalamari = ham.Item.new(242277, "Crimson Calamari", { buffFood = true })
ham.eversongPudding = ham.Item.new(242292, "Eversong Pudding", { buffFood = true })
ham.farstriderRations = ham.Item.new(242309, "Farstrider Rations", { buffFood = true })
ham.felKissedFilet = ham.Item.new(242286, "Fel-Kissed Filet", { buffFood = true })
ham.felberryFigs = ham.Item.new(242294, "Felberry Figs", { buffFood = true })
ham.floraFrenzy = ham.Item.new(255848, "Flora Frenzy", { buffFood = true })
ham.foragersMedley = ham.Item.new(242306, "Forager's Medley", { buffFood = true })
ham.friedBloomtail = ham.Item.new(242291, "Fried Bloomtail", { buffFood = true })
ham.glitterSkewers = ham.Item.new(242281, "Glitter Skewers", { buffFood = true })
ham.harandarCelebration = ham.Item.new(255846, "Harandar Celebration", { buffFood = true })
ham.hearthflameSupper = ham.Item.new(242295, "Hearthflame Supper", { buffFood = true })
ham.heartyAmaniCornucopia = ham.Item.new(275267, "Hearty Amani Cornucopia", { buffFood = true })
ham.heartyArcanoCutlets = ham.Item.new(242759, "Hearty Arcano Cutlets", { buffFood = true })
ham.heartyBloodthistleWrappedCutlets = ham.Item.new(242768, "Hearty Bloodthistle-Wrapped Cutlets", { buffFood = true })
ham.heartyBloomSkewers = ham.Item.new(242769, "Hearty Bloom Skewers", { buffFood = true })
ham.heartyBloomingFeast = ham.Item.new(242745, "Hearty Blooming Feast", { buffFood = true })
ham.heartyBraisedBloodHunter = ham.Item.new(242748, "Hearty Braised Blood Hunter", { buffFood = true })
ham.heartyButteredRootCrab = ham.Item.new(242752, "Hearty Buttered Root Crab", { buffFood = true })
ham.heartyChampionsBento = ham.Item.new(242746, "Hearty Champion's Bento", { buffFood = true })
ham.heartyCrimsonCalamari = ham.Item.new(242749, "Hearty Crimson Calamari", { buffFood = true })
ham.heartyEversongPudding = ham.Item.new(242764, "Hearty Eversong Pudding", { buffFood = true })
ham.heartyFarstriderRations = ham.Item.new(242776, "Hearty Farstrider Rations", { buffFood = true })
ham.heartyFelKissedFilet = ham.Item.new(242758, "Hearty Fel-Kissed Filet", { buffFood = true })
ham.heartyFelberryFigs = ham.Item.new(242766, "Hearty Felberry Figs", { buffFood = true })
ham.heartyFloraFrenzy = ham.Item.new(267000, "Hearty Flora Frenzy", { buffFood = true })
ham.heartyFloraFrenzy2 = ham.Item.new(268680, "Hearty Flora Frenzy", { buffFood = true })
ham.heartyForagersMedley = ham.Item.new(242773, "Hearty Forager's Medley", { buffFood = true })
ham.heartyFriedBloomtail = ham.Item.new(242763, "Hearty Fried Bloomtail", { buffFood = true })
ham.heartyGlitterSkewers = ham.Item.new(242753, "Hearty Glitter Skewers", { buffFood = true })
ham.heartyHarandarCelebration = ham.Item.new(266996, "Hearty Harandar Celebration", { buffFood = true })
ham.heartyHearthflameSupper = ham.Item.new(242767, "Hearty Hearthflame Supper", { buffFood = true })
ham.heartyImpossiblyRoyalRoast = ham.Item.new(268679, "Hearty Impossibly Royal Roast", { buffFood = true })
ham.heartyLoasGathering = ham.Item.new(275268, "Hearty Loa's Gathering", { buffFood = true })
ham.heartyManaInfusedStew = ham.Item.new(242770, "Hearty Mana-Infused Stew", { buffFood = true })
ham.heartyNullAndVoidPlate = ham.Item.new(242754, "Hearty Null and Void Plate", { buffFood = true })
ham.heartyPortableSnack = ham.Item.new(242775, "Hearty Portable Snack", { buffFood = true })
ham.heartyPufferPlate = ham.Item.new(275262, "Hearty Puffer Plate", { buffFood = true })
ham.heartyQueldoreiMedley = ham.Item.new(242744, "Hearty Quel'dorei Medley", { buffFood = true })
ham.heartyQueldoreiMedley2 = ham.Item.new(266986, "Hearty Quel'dorei Medley", { buffFood = true })
ham.heartyQuickSandwich = ham.Item.new(242774, "Hearty Quick Sandwich", { buffFood = true })
ham.heartyRootlandSurprise = ham.Item.new(242751, "Hearty Rootland Surprise", { buffFood = true })
ham.heartySilvermoonParade = ham.Item.new(266985, "Hearty Silvermoon Parade", { buffFood = true })
ham.heartySilvermoonStandard = ham.Item.new(242772, "Hearty Silvermoon Standard", { buffFood = true })
ham.heartySpellfireFilet = ham.Item.new(242761, "Hearty Spellfire Filet", { buffFood = true })
ham.heartySpicedBiscuits = ham.Item.new(242771, "Hearty Spiced Biscuits", { buffFood = true })
ham.heartySunSearedLumifin = ham.Item.new(242755, "Hearty Sun-Seared Lumifin", { buffFood = true })
ham.heartySunwellDelight = ham.Item.new(242765, "Hearty Sunwell Delight", { buffFood = true })
ham.heartySweetAndSourSkewers = ham.Item.new(275263, "Hearty Sweet-And-Sour Skewers", { buffFood = true })
ham.heartyTastySmokedTetra = ham.Item.new(242750, "Hearty Tasty Smoked Tetra", { buffFood = true })
ham.heartyTwilightAnglersMedley = ham.Item.new(242760, "Hearty Twilight Angler's Medley", { buffFood = true })
ham.heartyVenomSpicedCutlets = ham.Item.new(275259, "Hearty Venom-Spiced Cutlets", { buffFood = true })
ham.heartyVoidKissedFishRolls = ham.Item.new(242756, "Hearty Void-Kissed Fish Rolls", { buffFood = true })
ham.heartyWarpedWiseWings = ham.Item.new(242757, "Hearty Warped Wise Wings", { buffFood = true })
ham.heartyWiseTails = ham.Item.new(242762, "Hearty Wise Tails", { buffFood = true })
ham.impossiblyRoyalRoast = ham.Item.new(255847, "Impossibly Royal Roast", { buffFood = true })
ham.loasGathering = ham.Item.new(275265, "Loa's Gathering", { buffFood = true })
ham.manaInfusedStew = ham.Item.new(242303, "Mana-Infused Stew", { buffFood = true })
ham.nullAndVoidPlate = ham.Item.new(242282, "Null and Void Plate", { buffFood = true })
ham.portableSnack = ham.Item.new(242308, "Portable Snack", { buffFood = true })
ham.pufferPlate = ham.Item.new(275260, "Puffer Plate", { buffFood = true })
ham.queldoreiMedley = ham.Item.new(242272, "Quel'dorei Medley", { buffFood = true })
ham.quickSandwich = ham.Item.new(242307, "Quick Sandwich", { buffFood = true })
ham.silvermoonParade = ham.Item.new(255845, "Silvermoon Parade", { buffFood = true })
ham.silvermoonStandard = ham.Item.new(242305, "Silvermoon Standard", { buffFood = true })
ham.spellfireFilet = ham.Item.new(242289, "Spellfire Filet", { buffFood = true })
ham.spicedBiscuits = ham.Item.new(242304, "Spiced Biscuits", { buffFood = true })
ham.sunSearedLumifin = ham.Item.new(242283, "Sun-Seared Lumifin", { buffFood = true })
ham.sunwellDelight = ham.Item.new(242293, "Sunwell Delight", { buffFood = true })
ham.sweetAndSourSkewers = ham.Item.new(275261, "Sweet-And-Sour Skewers", { buffFood = true })
ham.tastySmokedTetra = ham.Item.new(242278, "Tasty Smoked Tetra", { buffFood = true })
ham.twilightAnglersMedley = ham.Item.new(242288, "Twilight Angler's Medley", { buffFood = true })
ham.venomSpicedCutlets = ham.Item.new(275258, "Venom-Spiced Cutlets", { buffFood = true })
ham.voidKissedFishRolls = ham.Item.new(242284, "Void-Kissed Fish Rolls", { buffFood = true })
ham.warpedWiseWings = ham.Item.new(242285, "Warped Wise Wings", { buffFood = true })
ham.wiseTails = ham.Item.new(242290, "Wise Tails", { buffFood = true })

-- Retail - plain vendor food (no stats). Same reskin situation as above: dozens of cosmetic
-- flavor/zone variants of the same restore-only mechanic, included individually for coverage.
ham.bloodKnightBurger = ham.Item.new(264992, "Blood Knight Burger")
ham.akilstew = ham.Item.new(260276, "Akil'stew")
ham.alndustInfusedFeast = ham.Item.new(260288, "Alndust-Infused Feast")
ham.asteroidSoup = ham.Item.new(260292, "Asteroid Soup")
ham.astralApplePie = ham.Item.new(260298, "Astral Apple Pie")
ham.bogLegs = ham.Item.new(260270, "Bog Legs")
ham.coiledCurry = ham.Item.new(280182, "Coiled Curry")
ham.delicateDartLegs = ham.Item.new(264993, "Delicate Dart Legs")
ham.fairbreezeFeast = ham.Item.new(260262, "Fairbreeze Feast")
ham.ghostlandsPepper = ham.Item.new(260257, "Ghostlands Pepper")
ham.goldenboughPreserves = ham.Item.new(264995, "Goldenbough Preserves")
ham.goldenmistGouda = ham.Item.new(264973, "Goldenmist Gouda")
ham.harrierHotcakes = ham.Item.new(280183, "Harrier Hotcakes")
ham.jerkBoarJerky = ham.Item.new(260269, "Jerk Boar Jerky")
ham.kalethasSunsalad = ham.Item.new(260254, "Kale'thas Sunsalad")
ham.lightbloominOnion = ham.Item.new(260279, "Lightbloomin' Onion")
ham.luxuriousOmelette = ham.Item.new(260256, "Luxurious Omelette")
ham.machosMagnificentFishTacos = ham.Item.new(238896, "Macho's Magnificent \"Fish\" Tacos")
ham.managiRoll = ham.Item.new(260255, "Managi Roll")
ham.mukleechCurry = ham.Item.new(260275, "Mukleech Curry")
ham.murderRoe = ham.Item.new(264991, "Murder Roe")
ham.pangoAndMash = ham.Item.new(260268, "Pango and Mash")
ham.pickledBloomShoots = ham.Item.new(264994, "Pickled Bloom Shoots")
ham.potatoadSalad = ham.Item.new(260278, "Potatoad Salad")
ham.queldanasRations = ham.Item.new(260264, "Quel'Danas Rations")
ham.quelthalasCheese = ham.Item.new(260290, "Quel'Thalas Cheese")
ham.rendoreiRations = ham.Item.new(260289, "Ren'dorei Rations")
ham.roastedAbyssalEel = ham.Item.new(260299, "Roasted Abyssal Eel")
ham.sauteedFungalTubers = ham.Item.new(260280, "Sauteed Fungal Tubers")
ham.sedgeCrawlerGumbo = ham.Item.new(260277, "Sedge Crawler Gumbo")
ham.shroomsAndNectar = ham.Item.new(260286, "Shrooms and Nectar")
ham.silvermoonSoireeSpread = ham.Item.new(260263, "Silvermoon Soiree Spread")
ham.stargazerPudding = ham.Item.new(260291, "Stargazer Pudding")
ham.steamedHexxalorLobster = ham.Item.new(260267, "Steamed Hexx'alor Lobster")
ham.stirFriedSaptorSirloin = ham.Item.new(260281, "Stir-Fried Saptor Sirloin")
ham.sunBastedCeviche = ham.Item.new(246383, "Sun-Basted Ceviche")
ham.sweetsawSurprise = ham.Item.new(280184, "Sweetsaw Surprise")
ham.tastyMeat = ham.Item.new(265674, "Tasty Meat")
ham.voidfarersRespite = ham.Item.new(260297, "Voidfarer's Respite")
ham.worldRootsBanquet = ham.Item.new(260287, "World Roots Banquet")

-- Classic - vendor/cooked food (no stats)
ham.toughJerky = ham.Item.new(117, "Tough Jerky")
ham.haunchOfMeat = ham.Item.new(2287, "Haunch of Meat")
ham.muttonChop = ham.Item.new(3770, "Mutton Chop")
ham.wildHogShank = ham.Item.new(3771, "Wild Hog Shank")
ham.curedHamSteak = ham.Item.new(4599, "Cured Ham Steak")
ham.roastedQuail = ham.Item.new(8952, "Roasted Quail")

-- Classic - stat ("Well Fed") food, highly situational, opt-in via HAMDB.includeBuffFood
ham.grilledSquid = ham.Item.new(13928, "Grilled Squid", { buffFood = true }) -- Agility
ham.nightfinSoup = ham.Item.new(13931, "Nightfin Soup", { buffFood = true }) -- Mana regen
ham.runnTumTuberSurprise = ham.Item.new(18254, "Runn Tum Tuber Surprise", { buffFood = true }) -- Intellect
ham.smokedDesertDumplings = ham.Item.new(20452, "Smoked Desert Dumplings", { buffFood = true }) -- Strength
ham.dirgesKickinChimaerokChops = ham.Item.new(21023, "Dirge's Kickin' Chimaerok Chops", { buffFood = true }) -- Stamina

-- Classic - conjured (Mage), prioritized first: free and doesn't consume bag/gold
ham.conjuredMuffin = ham.Item.new(5349, "Conjured Muffin", { conjured = true })
ham.conjuredBread = ham.Item.new(1113, "Conjured Bread", { conjured = true })
ham.conjuredRye = ham.Item.new(1114, "Conjured Rye", { conjured = true })
ham.conjuredPumpernickel = ham.Item.new(1487, "Conjured Pumpernickel", { conjured = true })
ham.conjuredSourdough = ham.Item.new(8075, "Conjured Sourdough", { conjured = true })
ham.conjuredSweetRoll = ham.Item.new(8076, "Conjured Sweet Roll", { conjured = true })
ham.conjuredCinnamonRoll = ham.Item.new(22895, "Conjured Cinnamon Roll", { conjured = true })

-- Classic - more stat ("Well Fed") food, classified from Wowhead's actual tooltip effect text
-- (well fed / stat-granting wording) rather than guesswork, opt-in via HAMDB.includeBuffFood
ham.badEggNog = ham.Item.new(17199, "Bad Egg Nog", { buffFood = true })
ham.barbecuedBuzzardWing = ham.Item.new(4457, "Barbecued Buzzard Wing", { buffFood = true })
ham.beerBastedBoarRibs = ham.Item.new(2888, "Beer Basted Boar Ribs", { buffFood = true })
ham.bigBearSteak = ham.Item.new(3726, "Big Bear Steak", { buffFood = true })
ham.blessedSunfruit = ham.Item.new(13810, "Blessed Sunfruit", { buffFood = true })
ham.bloodSausage = ham.Item.new(3220, "Blood Sausage", { buffFood = true })
ham.boiledClams = ham.Item.new(5525, "Boiled Clams", { buffFood = true })
ham.cactusAppleSurprise = ham.Item.new(11584, "Cactus Apple Surprise", { buffFood = true })
ham.candyBar = ham.Item.new(7807, "Candy Bar", { buffFood = true })
ham.carrionSurprise = ham.Item.new(12213, "Carrion Surprise", { buffFood = true })
ham.chocolateSquare = ham.Item.new(7808, "Chocolate Square", { buffFood = true })
ham.clamletteSurprise = ham.Item.new(16971, "Clamlette Surprise", { buffFood = true })
ham.cookedGlossyMightfish = ham.Item.new(13927, "Cooked Glossy Mightfish", { buffFood = true })
ham.coyoteSteak = ham.Item.new(2684, "Coyote Steak", { buffFood = true })
ham.crabCake = ham.Item.new(2683, "Crab Cake", { buffFood = true })
ham.crispyBatWing = ham.Item.new(12224, "Crispy Bat Wing", { buffFood = true })
ham.crispyLizardTail = ham.Item.new(5479, "Crispy Lizard Tail", { buffFood = true })
ham.crocoliskGumbo = ham.Item.new(3664, "Crocolisk Gumbo", { buffFood = true })
ham.crocoliskSteak = ham.Item.new(3662, "Crocolisk Steak", { buffFood = true })
ham.curiouslyTastyOmelet = ham.Item.new(3665, "Curiously Tasty Omelet", { buffFood = true })
ham.dryPorkRibs = ham.Item.new(2687, "Dry Pork Ribs", { buffFood = true })
ham.eggNog = ham.Item.new(17198, "Egg Nog", { buffFood = true })
ham.filletOfFrenzy = ham.Item.new(5476, "Fillet of Frenzy", { buffFood = true })
ham.giantClamScorcho = ham.Item.new(6038, "Giant Clam Scorcho", { buffFood = true })
ham.gingerbreadCookie = ham.Item.new(17197, "Gingerbread Cookie", { buffFood = true })
ham.goblinDeviledClams = ham.Item.new(5527, "Goblin Deviled Clams", { buffFood = true })
ham.gooeySpiderCake = ham.Item.new(3666, "Gooey Spider Cake", { buffFood = true })
ham.goretuskLiverPie = ham.Item.new(724, "Goretusk Liver Pie", { buffFood = true })
ham.heavyCrocoliskStew = ham.Item.new(20074, "Heavy Crocolisk Stew", { buffFood = true })
ham.heavyKodoStew = ham.Item.new(12215, "Heavy Kodo Stew", { buffFood = true })
ham.herbBakedEgg = ham.Item.new(6888, "Herb Baked Egg", { buffFood = true })
ham.hotLionChops = ham.Item.new(3727, "Hot Lion Chops", { buffFood = true })
ham.hotSmokedBass = ham.Item.new(13929, "Hot Smoked Bass", { buffFood = true })
ham.hotWolfRibs = ham.Item.new(13851, "Hot Wolf Ribs", { buffFood = true })
ham.jungleStew = ham.Item.new(12212, "Jungle Stew", { buffFood = true })
ham.kaldoreiSpiderKabob = ham.Item.new(5472, "Kaldorei Spider Kabob", { buffFood = true })
ham.leanVenison = ham.Item.new(5480, "Lean Venison", { buffFood = true })
ham.leanWolfSteak = ham.Item.new(12209, "Lean Wolf Steak", { buffFood = true })
ham.lollipop = ham.Item.new(7806, "Lollipop", { buffFood = true })
ham.mightfishSteak = ham.Item.new(13934, "Mightfish Steak", { buffFood = true })
ham.monsterOmelet = ham.Item.new(12218, "Monster Omelet", { buffFood = true })
ham.murlocFinSoup = ham.Item.new(3663, "Murloc Fin Soup", { buffFood = true })
ham.mysteryStew = ham.Item.new(12214, "Mystery Stew", { buffFood = true })
ham.redridgeGoulash = ham.Item.new(1082, "Redridge Goulash", { buffFood = true })
ham.roastRaptor = ham.Item.new(12210, "Roast Raptor", { buffFood = true })
ham.roastedKodoMeat = ham.Item.new(5474, "Roasted Kodo Meat", { buffFood = true })
ham.sagefishDelight = ham.Item.new(21217, "Sagefish Delight", { buffFood = true })
ham.seasonedWolfKabob = ham.Item.new(1017, "Seasoned Wolf Kabob", { buffFood = true })
ham.smokedSagefish = ham.Item.new(21072, "Smoked Sagefish", { buffFood = true })
ham.soothingTurtleBisque = ham.Item.new(3729, "Soothing Turtle Bisque", { buffFood = true })
ham.spicedChiliCrab = ham.Item.new(12216, "Spiced Chili Crab", { buffFood = true })
ham.spicedWolfMeat = ham.Item.new(2680, "Spiced Wolf Meat", { buffFood = true })
ham.spicedWolfRibs = ham.Item.new(12211, "Spiced Wolf Ribs", { buffFood = true })
ham.spiderSausage = ham.Item.new(17222, "Spider Sausage", { buffFood = true })
ham.striderStew = ham.Item.new(5477, "Strider Stew", { buffFood = true })
ham.tastyLionSteak = ham.Item.new(3728, "Tasty Lion Steak", { buffFood = true })
ham.tenderWolfSteak = ham.Item.new(18045, "Tender Wolf Steak", { buffFood = true })
ham.winterVeilCookie = ham.Item.new(21254, "Winter Veil Cookie", { buffFood = true })

-- Classic - dual restore (health AND mana, no stats). Shared with Core/Drink.lua's priority
-- list since these satisfy either need; referencing the same ham.Item object from both lists
-- is safe (same underlying item, whichever macro runs first uses it).
ham.alteracMannaBiscuit = ham.Item.new(19301, "Alterac Manna Biscuit")
ham.bobbingApple = ham.Item.new(20516, "Bobbing Apple")
ham.cookedCrabClaw = ham.Item.new(2682, "Cooked Crab Claw")
ham.enrichedMannaBiscuit = ham.Item.new(13724, "Enriched Manna Biscuit")
ham.essenceMango = ham.Item.new(20031, "Essence Mango")
ham.graccusMinceMeatFruitcake = ham.Item.new(21215, "Graccu's Mince Meat Fruitcake")
ham.greenTeaLeaf = ham.Item.new(1401, "Green Tea Leaf")
ham.refreshingRedApple = ham.Item.new(23172, "Refreshing Red Apple")
ham.sengginRoot = ham.Item.new(3448, "Senggin Root")

-- Classic - more plain vendor/cooked food (no stats). Wowhead's Classic Era food & drinks
-- category lists dozens of race/zone/fishing reskins of the same restore-only mechanic;
-- included individually for coverage since a given player only ever owns one specific reskin.
ham.alteracSwiss = ham.Item.new(8932, "Alterac Swiss")
ham.bakedSalmon = ham.Item.new(13935, "Baked Salmon")
ham.beanSoup = ham.Item.new(16166, "Bean Soup")
ham.bellarasNutterbar = ham.Item.new(18635, "Bellara's Nutterbar")
ham.bloodbellyFish = ham.Item.new(13546, "Bloodbelly Fish")
ham.brilliantSmallfish = ham.Item.new(6290, "Brilliant Smallfish")
ham.bristleWhiskerCatfish = ham.Item.new(4593, "Bristle Whisker Catfish")
ham.cabbageKimchi = ham.Item.new(21031, "Cabbage Kimchi")
ham.candyCane = ham.Item.new(17344, "Candy Cane")
ham.charredWolfMeat = ham.Item.new(2679, "Charred Wolf Meat")
ham.clamChowder = ham.Item.new(5526, "Clam Chowder")
ham.crunchyFrog = ham.Item.new(19306, "Crunchy Frog")
ham.dalaranSharp = ham.Item.new(414, "Dalaran Sharp")
ham.darkmoonDog = ham.Item.new(19223, "Darkmoon Dog")
ham.darkshoreGrouper = ham.Item.new(12238, "Darkshore Grouper")
ham.darnassianBleu = ham.Item.new(2070, "Darnassian Bleu")
ham.darnassusKimchiPie = ham.Item.new(21030, "Darnassus Kimchi Pie")
ham.deepFriedCandybar = ham.Item.new(19225, "Deep Fried Candybar")
ham.deepFriedPlantains = ham.Item.new(8953, "Deep Fried Plantains")
ham.deeprunRatKabob = ham.Item.new(17119, "Deeprun Rat Kabob")
ham.deliciousCaveMold = ham.Item.new(4607, "Delicious Cave Mold")
ham.digRatStew = ham.Item.new(5478, "Dig Rat Stew")
ham.driedKingBolete = ham.Item.new(8948, "Dried King Bolete")
ham.dwarvenMild = ham.Item.new(422, "Dwarven Mild")
ham.filetOfRedgill = ham.Item.new(13930, "Filet of Redgill")
ham.fineAgedCheddar = ham.Item.new(3927, "Fine Aged Cheddar")
ham.fissurePlant = ham.Item.new(5066, "Fissure Plant")
ham.forestMushroomCap = ham.Item.new(4604, "Forest Mushroom Cap")
ham.freshlyBakedBread = ham.Item.new(4541, "Freshly Baked Bread")
ham.friendshipBread = ham.Item.new(23160, "Friendship Bread")
ham.frogLegStew = ham.Item.new(6807, "Frog Leg Stew")
ham.goldenbarkApple = ham.Item.new(4539, "Goldenbark Apple")
ham.graccusHomemadeMeatPie = ham.Item.new(17407, "Graccu's Homemade Meat Pie")
ham.grilledKingCrawlerLegs = ham.Item.new(9681, "Grilled King Crawler Legs")
ham.grimGuzzlerBoar = ham.Item.new(11444, "Grim Guzzler Boar")
ham.harvestBoar = ham.Item.new(19995, "Harvest Boar")
ham.harvestBread = ham.Item.new(19696, "Harvest Bread")
ham.harvestFish = ham.Item.new(19996, "Harvest Fish")
ham.harvestFruit = ham.Item.new(19994, "Harvest Fruit")
ham.healingHerb = ham.Item.new(961, "Healing Herb")
ham.heavenPeach = ham.Item.new(16168, "Heaven Peach")
ham.holidayCheesewheel = ham.Item.new(17406, "Holiday Cheesewheel")
ham.homemadeCherryPie = ham.Item.new(8950, "Homemade Cherry Pie")
ham.largeRawMightfish = ham.Item.new(13893, "Large Raw Mightfish")
ham.legMeat = ham.Item.new(7097, "Leg Meat")
ham.lobsterStew = ham.Item.new(13933, "Lobster Stew")
ham.lochFrenzyDelight = ham.Item.new(6316, "Loch Frenzy Delight")
ham.longjawMudSnapper = ham.Item.new(4592, "Longjaw Mud Snapper")
ham.mithrilHeadTrout = ham.Item.new(8364, "Mithril Head Trout")
ham.mixedBerries = ham.Item.new(11415, "Mixed Berries")
ham.moistCornbread = ham.Item.new(4542, "Moist Cornbread")
ham.moonHarvestPumpkin = ham.Item.new(4602, "Moon Harvest Pumpkin")
ham.moonbrookRiotTaffy = ham.Item.new(18632, "Moonbrook Riot Taffy")
ham.mulgoreSpiceBread = ham.Item.new(4544, "Mulgore Spice Bread")
ham.pickledKodoFoot = ham.Item.new(19305, "Pickled Kodo Foot")
ham.poachedSunscaleSalmon = ham.Item.new(13932, "Poached Sunscale Salmon")
ham.radishKimchi = ham.Item.new(21033, "Radish Kimchi")
ham.rainbowFinAlbacore = ham.Item.new(5095, "Rainbow Fin Albacore")
ham.rawBlackTruffle = ham.Item.new(4608, "Raw Black Truffle")
ham.redHotWings = ham.Item.new(19224, "Red Hot Wings")
ham.redSpeckledMushroom = ham.Item.new(4605, "Red-speckled Mushroom")
ham.ripeWatermelon = ham.Item.new(5057, "Ripe Watermelon")
ham.roastedBoarMeat = ham.Item.new(2681, "Roasted Boar Meat")
ham.rockscaleCod = ham.Item.new(4594, "Rockscale Cod")
ham.runnTumTuber = ham.Item.new(18255, "Runn Tum Tuber")
ham.sauteedSunfish = ham.Item.new(1326, "Sauteed Sunfish")
ham.scorpidSurprise = ham.Item.new(5473, "Scorpid Surprise") -- rarely inflicts a minor, brief poison
ham.shinsollo = ham.Item.new(16171, "Shinsollo")
ham.shinyRedApple = ham.Item.new(4536, "Shiny Red Apple")
ham.sicklyLookingFish = ham.Item.new(6299, "Sickly Looking Fish")
ham.slitherskinMackerel = ham.Item.new(787, "Slitherskin Mackerel")
ham.smallPumpkin = ham.Item.new(4656, "Small Pumpkin")
ham.smokedBearMeat = ham.Item.new(6890, "Smoked Bear Meat")
ham.snapvineWatermelon = ham.Item.new(4538, "Snapvine Watermelon")
ham.softBananaBread = ham.Item.new(4601, "Soft Banana Bread")
ham.specialChickenFeed = ham.Item.new(11109, "Special Chicken Feed")
ham.spicedBeefJerky = ham.Item.new(19304, "Spiced Beef Jerky")
ham.spicyBeefstick = ham.Item.new(17408, "Spicy Beefstick")
ham.spinefinHalibut = ham.Item.new(8957, "Spinefin Halibut")
ham.spongyMorel = ham.Item.new(4606, "Spongy Morel")
ham.spottedYellowtail = ham.Item.new(6887, "Spotted Yellowtail")
ham.steamedMandu = ham.Item.new(16170, "Steamed Mandu")
ham.stormwindBrie = ham.Item.new(1707, "Stormwind Brie")
ham.stripedYellowtail = ham.Item.new(21552, "Striped Yellowtail")
ham.styleensSourSuckerpop = ham.Item.new(18633, "Styleen's Sour Suckerpop")
ham.succulentPorkRibs = ham.Item.new(2685, "Succulent Pork Ribs")
ham.telabimBanana = ham.Item.new(4537, "Tel'Abim Banana")
ham.tigulesStrawberryIceCream = ham.Item.new(7228, "Tigule's Strawberry Ice Cream")
ham.toughHunkOfBread = ham.Item.new(4540, "Tough Hunk of Bread")
ham.ungoroEtherfruit = ham.Item.new(12763, "Un'Goro Etherfruit")
ham.undermineClamChowder = ham.Item.new(16766, "Undermine Clam Chowder")
ham.versicolorTreat = ham.Item.new(16167, "Versicolor Treat")
ham.westfallStew = ham.Item.new(733, "Westfall Stew")
ham.whipperRootTuber = ham.Item.new(11951, "Whipper Root Tuber")
ham.wildRicecake = ham.Item.new(16169, "Wild Ricecake")
ham.winterKimchi = ham.Item.new(22324, "Winter Kimchi")
ham.winterSquid = ham.Item.new(13755, "Winter Squid")
ham.winterVeilCandy = ham.Item.new(21240, "Winter Veil Candy")
ham.winterVeilLoaf = ham.Item.new(21236, "Winter Veil Loaf")
ham.winterVeilRoast = ham.Item.new(21235, "Winter Veil Roast")

-- TBC - stat ("Well Fed") food, classified from Wowhead's actual tooltip effect text,
-- opt-in via HAMDB.includeBuffFood
ham.batBites = ham.Item.new(27636, "Bat Bites", { buffFood = true })
ham.blackenedBasilisk = ham.Item.new(27657, "Blackened Basilisk", { buffFood = true })
ham.blackenedSporefish = ham.Item.new(27663, "Blackened Sporefish", { buffFood = true })
ham.bonestripperBuzzardHotwings = ham.Item.new(29293, "Bonestripper Buzzard Hotwings", { buffFood = true })
ham.broiledBloodfin = ham.Item.new(33867, "Broiled Bloodfin", { buffFood = true })
ham.buzzardBites = ham.Item.new(27651, "Buzzard Bites", { buffFood = true })
ham.charredBearKabobs = ham.Item.new(35563, "Charred Bear Kabobs", { buffFood = true })
ham.clamBar = ham.Item.new(30155, "Clam Bar", { buffFood = true })
ham.clamletteSurprise2 = ham.Item.new(33004, "Clamlette Surprise", { buffFood = true })
ham.cookiesJumboGumbo = ham.Item.new(23756, "Cookie's Jumbo Gumbo", { buffFood = true })
ham.crunchySerpent = ham.Item.new(31673, "Crunchy Serpent", { buffFood = true })
ham.crunchySpiderSurprise = ham.Item.new(22645, "Crunchy Spider Surprise", { buffFood = true })
ham.driedFruitRations = ham.Item.new(24009, "Dried Fruit Rations", { buffFood = true })
ham.driedMushroomRations = ham.Item.new(24008, "Dried Mushroom Rations", { buffFood = true })
ham.feltailDelight = ham.Item.new(27662, "Feltail Delight", { buffFood = true })
ham.fishermansFeast = ham.Item.new(33052, "Fisherman's Feast", { buffFood = true })
ham.goldenFishSticks = ham.Item.new(27666, "Golden Fish Sticks", { buffFood = true })
ham.grilledMudfish = ham.Item.new(27664, "Grilled Mudfish", { buffFood = true })
ham.helboarBacon = ham.Item.new(29292, "Helboar Bacon", { buffFood = true })
ham.hotAppleCider = ham.Item.new(34411, "Hot Apple Cider", { buffFood = true })
ham.juicyBearBurger = ham.Item.new(35565, "Juicy Bear Burger", { buffFood = true })
ham.lynxSteak = ham.Item.new(27635, "Lynx Steak", { buffFood = true })
ham.marshLichen = ham.Item.new(24539, "Marsh Lichen", { buffFood = true })
ham.moknathalShortribs = ham.Item.new(31672, "Mok'Nathal Shortribs", { buffFood = true })
ham.oronoksTuberOfAgility = ham.Item.new(30358, "Oronok's Tuber of Agility", { buffFood = true })
ham.oronoksTuberOfHealing = ham.Item.new(30357, "Oronok's Tuber of Healing", { buffFood = true })
ham.oronoksTuberOfSpellPower = ham.Item.new(30361, "Oronok's Tuber of Spell Power", { buffFood = true })
ham.oronoksTuberOfStrength = ham.Item.new(30359, "Oronok's Tuber of Strength", { buffFood = true })
ham.poachedBluefish = ham.Item.new(27665, "Poached Bluefish", { buffFood = true })
ham.ravagerDog = ham.Item.new(27655, "Ravager Dog", { buffFood = true })
ham.ravagerEggOmelet = ham.Item.new(28501, "Ravager Egg Omelet", { buffFood = true })
ham.roastedClefthoof = ham.Item.new(27658, "Roasted Clefthoof", { buffFood = true })
ham.roastedMoongrazeTenderloin = ham.Item.new(24105, "Roasted Moongraze Tenderloin", { buffFood = true })
ham.skullfishSoup = ham.Item.new(33825, "Skullfish Soup", { buffFood = true })
ham.skyguardRations = ham.Item.new(32721, "Skyguard Rations", { buffFood = true })
ham.spicyCrawdad = ham.Item.new(27667, "Spicy Crawdad", { buffFood = true })
ham.spicyHotTalbuk = ham.Item.new(33872, "Spicy Hot Talbuk", { buffFood = true })
ham.talbukSteak = ham.Item.new(27660, "Talbuk Steak", { buffFood = true })
ham.warpBurger = ham.Item.new(27659, "Warp Burger", { buffFood = true })

-- TBC - dual restore (health AND mana, no stats)
ham.conjuredMannaBiscuit = ham.Item.new(34062, "Conjured Manna Biscuit", { conjured = true })
ham.enrichedTeroconeJuice = ham.Item.new(32722, "Enriched Terocone Juice")
ham.hotButteredTrout = ham.Item.new(33053, "Hot Buttered Trout")
ham.naaruRation = ham.Item.new(34780, "Naaru Ration")
ham.undersporePod = ham.Item.new(28112, "Underspore Pod")

-- TBC - plain food (no stats), reskins of the same restore-only mechanic
ham.blackenedTrout = ham.Item.new(27661, "Blackened Trout")
ham.bladespireBagel = ham.Item.new(29449, "Bladespire Bagel")
ham.clefthoofRibs = ham.Item.new(29451, "Clefthoof Ribs")
ham.conjuredCroissant = ham.Item.new(22019, "Conjured Croissant", { conjured = true })
ham.deliciousBakedHam = ham.Item.new(35710, "Delicious Baked Ham")
ham.diamondBerries = ham.Item.new(29393, "Diamond Berries")
ham.garadarSharp = ham.Item.new(27857, "Garadar Sharp")
ham.grilledShadowmoonTuber = ham.Item.new(30355, "Grilled Shadowmoon Tuber")
ham.hellfireSpineleaf = ham.Item.new(24338, "Hellfire Spineleaf")
ham.honeyBread = ham.Item.new(20857, "Honey Bread")
ham.jessensSpecialSlop = ham.Item.new(29412, "Jessen's Special Slop")
ham.jessensSpecialSlopOld = ham.Item.new(29402, "Jessen's Special Slop OLD")
ham.lyribread = ham.Item.new(29394, "Lyribread")
ham.magharGrainbread = ham.Item.new(27855, "Mag'har Grainbread")
ham.magharMildCheese = ham.Item.new(29448, "Mag'har Mild Cheese")
ham.mingosFortuneGiblets = ham.Item.new(32686, "Mingo's Fortune Giblets")
ham.mosersMagnificentMuffin = ham.Item.new(28486, "Moser's Magnificent Muffin")
ham.ogrilaChickenFingers = ham.Item.new(32685, "Ogri'la Chicken Fingers")
ham.pickledEgg = ham.Item.new(38427, "Pickled Egg")
ham.rockSaltedPretzel = ham.Item.new(38428, "Rock-Salted Pretzel")
ham.sandPearPie = ham.Item.new(24072, "Sand Pear Pie")
ham.skethylBerries = ham.Item.new(27856, "Skethyl Berries")
ham.smokedBlackBearMeat = ham.Item.new(30610, "Smoked Black Bear Meat")
ham.smokedTalbukVenison = ham.Item.new(27854, "Smoked Talbuk Venison")
ham.spiceBread = ham.Item.new(30816, "Spice Bread")
ham.sporeggarMushroom = ham.Item.new(29453, "Sporeggar Mushroom")
ham.springpawAppetizer = ham.Item.new(23495, "Springpaw Appetizer")
ham.stewedTrout = ham.Item.new(33048, "Stewed Trout")
ham.stromgardeMuenster = ham.Item.new(30458, "Stromgarde Muenster")
ham.sunspringCarp = ham.Item.new(27858, "Sunspring Carp")
ham.telaariGrapes = ham.Item.new(29450, "Telaari Grapes")
ham.zangarCaps = ham.Item.new(27859, "Zangar Caps")
ham.zangarTrout = ham.Item.new(29452, "Zangar Trout")

-- Wrath - stat ("Well Fed") food, classified from Wowhead's actual tooltip effect text,
-- opt-in via HAMDB.includeBuffFood
ham.bakedMantaRay = ham.Item.new(42942, "Baked Manta Ray", { buffFood = true })
ham.blackenedDragonfin = ham.Item.new(42999, "Blackened Dragonfin", { buffFood = true })
ham.blackenedWorgSteak = ham.Item.new(42997, "Blackened Worg Steak", { buffFood = true })
ham.bountifulFeast = ham.Item.new(46887, "Bountiful Feast", { buffFood = true })
ham.candiedSweetPotato = ham.Item.new(44839, "Candied Sweet Potato", { buffFood = true })
ham.cranberryChutney = ham.Item.new(44840, "Cranberry Chutney", { buffFood = true })
ham.cuttlesteak = ham.Item.new(42998, "Cuttlesteak", { buffFood = true })
ham.dalaranClamChowder = ham.Item.new(43268, "Dalaran Clam Chowder", { buffFood = true })
ham.dragonfinFilet = ham.Item.new(43000, "Dragonfin Filet", { buffFood = true })
ham.firecrackerSalmon = ham.Item.new(34767, "Firecracker Salmon", { buffFood = true })
ham.fishFeast = ham.Item.new(43015, "Fish Feast", { buffFood = true })
ham.greatFeast = ham.Item.new(34753, "Great Feast", { buffFood = true })
ham.grilledSculpin = ham.Item.new(34762, "Grilled Sculpin", { buffFood = true })
ham.heartyRhino = ham.Item.new(42995, "Hearty Rhino", { buffFood = true })
ham.imperialMantaSteak = ham.Item.new(34769, "Imperial Manta Steak", { buffFood = true })
ham.jilliansGourmetFishFeast = ham.Item.new(45279, "Jillian's Gourmet Fish Feast", { buffFood = true })
ham.mammothMeal = ham.Item.new(34748, "Mammoth Meal", { buffFood = true })
ham.megaMammothMeal = ham.Item.new(34754, "Mega Mammoth Meal", { buffFood = true })
ham.mightyRhinoDogs = ham.Item.new(34758, "Mighty Rhino Dogs", { buffFood = true })
ham.noblegardenChocolate = ham.Item.new(44791, "Noblegarden Chocolate", { buffFood = true })
ham.pickledFangtooth = ham.Item.new(34765, "Pickled Fangtooth", { buffFood = true })
ham.poachedNettlefish = ham.Item.new(34764, "Poached Nettlefish", { buffFood = true })
ham.poachedNorthernSculpin = ham.Item.new(34766, "Poached Northern Sculpin", { buffFood = true })
ham.pumpkinPie = ham.Item.new(44836, "Pumpkin Pie", { buffFood = true })
ham.rhinoDogs = ham.Item.new(34752, "Rhino Dogs", { buffFood = true })
ham.rhinoliciousWormsteak = ham.Item.new(42994, "Rhinolicious Wormsteak", { buffFood = true })
ham.roastedWorg = ham.Item.new(34751, "Roasted Worg", { buffFood = true })
ham.shoveltuskSoup = ham.Item.new(34125, "Shoveltusk Soup", { buffFood = true })
ham.shoveltuskSteak = ham.Item.new(34749, "Shoveltusk Steak", { buffFood = true })
ham.slowRoastedTurkey = ham.Item.new(44838, "Slow-Roasted Turkey", { buffFood = true })
ham.smokedSalmon = ham.Item.new(34763, "Smoked Salmon", { buffFood = true })
ham.snapperExtreme = ham.Item.new(42996, "Snapper Extreme", { buffFood = true })
ham.spiceBreadStuffing = ham.Item.new(44837, "Spice Bread Stuffing", { buffFood = true })
ham.spicedWormBurger = ham.Item.new(34756, "Spiced Worm Burger", { buffFood = true })
ham.spicyBlueNettlefish = ham.Item.new(34768, "Spicy Blue Nettlefish", { buffFood = true })
ham.spicyFriedHerring = ham.Item.new(42993, "Spicy Fried Herring", { buffFood = true })
ham.steamingChickenSoup = ham.Item.new(42779, "Steaming Chicken Soup", { buffFood = true })
ham.succulentOrcaStew = ham.Item.new(39691, "Succulent Orca Stew", { buffFood = true })
ham.tenderShoveltuskSteak = ham.Item.new(34755, "Tender Shoveltusk Steak", { buffFood = true })
ham.trackerSnacks = ham.Item.new(43001, "Tracker Snacks", { buffFood = true })
ham.veryBurntWorg = ham.Item.new(34757, "Very Burnt Worg", { buffFood = true })
ham.worgTartare = ham.Item.new(44953, "Worg Tartare", { buffFood = true })
ham.wormDelight = ham.Item.new(34750, "Worm Delight", { buffFood = true })

-- Wrath - dual restore (health AND mana, no stats)
ham.blackJelly = ham.Item.new(45932, "Black Jelly")
ham.conjuredManaPie = ham.Item.new(43518, "Conjured Mana Pie", { conjured = true })
ham.conjuredManaStrudel = ham.Item.new(43523, "Conjured Mana Strudel", { conjured = true })
ham.giganticFeast = ham.Item.new(43478, "Gigantic Feast")
ham.grilledBonescale = ham.Item.new(34760, "Grilled Bonescale")
ham.sauteedGoby = ham.Item.new(34761, "Sauteed Goby")
ham.smallFeast = ham.Item.new(43480, "Small Feast")
ham.smokedRockfin = ham.Item.new(34759, "Smoked Rockfin")

-- Wrath - plain food (no stats), reskins of the same restore-only mechanic
ham.agedDalaranSharp = ham.Item.new(44607, "Aged Dalaran Sharp")
ham.agedYolk = ham.Item.new(44722, "Aged Yolk")
ham.berryPieSlice = ham.Item.new(42432, "Berry Pie Slice")
ham.blackMushroom = ham.Item.new(41751, "Black Mushroom")
ham.bowelsNBrains = ham.Item.new(38706, "Bowels 'n' Brains")
ham.breadOfTheDead = ham.Item.new(46691, "Bread of the Dead")
ham.brinyHardcheese = ham.Item.new(35952, "Briny Hardcheese")
ham.candySkull = ham.Item.new(46690, "Candy Skull")
ham.carrotCupcake = ham.Item.new(42428, "Carrot Cupcake")
ham.chocolateCakeSlice = ham.Item.new(42433, "Chocolate Cake Slice")
ham.cornBreadedSausage = ham.Item.new(44940, "Corn-Breaded Sausage")
ham.crispDalaranApple = ham.Item.new(43087, "Crisp Dalaran Apple")
ham.crusadersRations = ham.Item.new(42778, "Crusader's Rations")
ham.crustyFlatbread = ham.Item.new(33449, "Crusty Flatbread")
ham.dalaranBrownie = ham.Item.new(42431, "Dalaran Brownie")
ham.dalaranDoughnut = ham.Item.new(42430, "Dalaran Doughnut")
ham.dalaranSwiss = ham.Item.new(44608, "Dalaran Swiss")
ham.fattyBluefin = ham.Item.new(37452, "Fatty Bluefin")
ham.filletOfIcefin = ham.Item.new(33451, "Fillet of Icefin")
ham.freshDalaranBreadSlice = ham.Item.new(44609, "Fresh Dalaran Bread Slice")
ham.freshEagleMeat = ham.Item.new(40359, "Fresh Eagle Meat")
ham.freshlySpearedEmperorSalmon = ham.Item.new(44049, "Freshly-Speared Emperor Salmon")
ham.frostberries = ham.Item.new(37252, "Frostberries")
ham.grizzleberries = ham.Item.new(40356, "Grizzleberries")
ham.homemadeFishFry = ham.Item.new(45901, "Homemade Fish Fry")
ham.honeySpicedLichen = ham.Item.new(33452, "Honey-Spiced Lichen")
ham.lovelyCakeSlice = ham.Item.new(42434, "Lovely Cake Slice")
ham.meadBastedCaribou = ham.Item.new(35953, "Mead Basted Caribou")
ham.mingosFortuneGiblets = ham.Item.new(32686, "Mingo's Fortune Giblets")
ham.mulgoreSweetPotato = ham.Item.new(46797, "Mulgore Sweet Potato")
ham.northernStew = ham.Item.new(34747, "Northern Stew")
ham.poachedEmperorSalmon = ham.Item.new(35951, "Poached Emperor Salmon")
ham.rawTallhornChunk = ham.Item.new(40358, "Raw Tallhorn Chunk")
ham.redVelvetCupcake = ham.Item.new(42429, "Red Velvet Cupcake")
ham.ripeElwynnPumpkin = ham.Item.new(46784, "Ripe Elwynn Pumpkin")
ham.ripeTirisfalPumpkin = ham.Item.new(46796, "Ripe Tirisfal Pumpkin")
ham.roastedMysteryBeast = ham.Item.new(44072, "Roasted Mystery Beast")
ham.saltedVenison = ham.Item.new(33454, "Salted Venison")
ham.saltedYetiCheese = ham.Item.new(44749, "Salted Yeti Cheese")
ham.savorySnowplum = ham.Item.new(35948, "Savory Snowplum")
ham.sizzlingGrizzlyFlank = ham.Item.new(40202, "Sizzling Grizzly Flank")
ham.slowRoastedEel = ham.Item.new(44071, "Slow-Roasted Eel")
ham.sourGoatCheese = ham.Item.new(33443, "Sour Goat Cheese")
ham.sparklingFrostcap = ham.Item.new(35947, "Sparkling Frostcap")
ham.stewedDrakeflesh = ham.Item.new(41729, "Stewed Drakeflesh")
ham.stolenRibs = ham.Item.new(36831, "Stolen Ribs")
ham.sweetPotatoBread = ham.Item.new(35950, "Sweet Potato Bread")
ham.tangySouthfuryCranberries = ham.Item.new(46793, "Tangy Southfury Cranberries")
ham.tangyWetlandCranberries = ham.Item.new(44854, "Tangy Wetland Cranberries")
ham.teldrassilSweetPotato = ham.Item.new(44855, "Teldrassil Sweet Potato")
ham.tundraBerries = ham.Item.new(35949, "Tundra Berries")

-- Cata - stat ("Well Fed") food, classified from Wowhead's actual tooltip effect text,
-- opt-in via HAMDB.includeBuffFood
ham.bakedRockfish = ham.Item.new(62661, "Baked Rockfish", { buffFood = true })
ham.basiliskLiverdog = ham.Item.new(62665, "Basilisk Liverdog", { buffFood = true })
ham.beerBastedCrocolisk = ham.Item.new(62670, "Beer-Basted Crocolisk", { buffFood = true })
ham.blackbellySushi = ham.Item.new(62668, "Blackbelly Sushi", { buffFood = true })
ham.broiledDragonFeast = ham.Item.new(62289, "Broiled Dragon Feast", { buffFood = true })
ham.broiledMountainTrout = ham.Item.new(62655, "Broiled Mountain Trout", { buffFood = true })
ham.cookiesSpecialRamlette = ham.Item.new(57519, "Cookie's Special Ramlette", { buffFood = true })
ham.crocoliskAuGratin = ham.Item.new(62664, "Crocolisk Au Gratin", { buffFood = true })
ham.deliciousSagefishTail = ham.Item.new(62666, "Delicious Sagefish Tail", { buffFood = true })
ham.eternalEyeOfElune = ham.Item.new(70924, "Eternal Eye of Elune", { buffFood = true })
ham.eternalLunarPear = ham.Item.new(70925, "Eternal Lunar Pear", { buffFood = true })
ham.eternalMoonberry = ham.Item.new(70926, "Eternal Moonberry", { buffFood = true })
ham.eternalSunfruit = ham.Item.new(70927, "Eternal Sunfruit", { buffFood = true })
ham.fortuneCookie = ham.Item.new(62649, "Fortune Cookie", { buffFood = true })
ham.goblinBarbecue = ham.Item.new(60858, "Goblin Barbecue", { buffFood = true })
ham.grilledDragon = ham.Item.new(62662, "Grilled Dragon", { buffFood = true })
ham.heartySeafoodSoup = ham.Item.new(62659, "Hearty Seafood Soup", { buffFood = true })
ham.lavascaleFillet = ham.Item.new(62654, "Lavascale Fillet", { buffFood = true })
ham.lavascaleMinestrone = ham.Item.new(62663, "Lavascale Minestrone", { buffFood = true })
ham.lightlyFriedLurker = ham.Item.new(62651, "Lightly Fried Lurker", { buffFood = true })
ham.lurkerLunch = ham.Item.new(62657, "Lurker Lunch", { buffFood = true })
ham.mushroomSauceMudfish = ham.Item.new(62667, "Mushroom Sauce Mudfish", { buffFood = true })
ham.pickledGuppy = ham.Item.new(62660, "Pickled Guppy", { buffFood = true })
ham.saltedEye = ham.Item.new(62653, "Salted Eye", { buffFood = true })
ham.seafoodMagnifiqueFeast = ham.Item.new(62290, "Seafood Magnifique Feast", { buffFood = true })
ham.seasonedCrab = ham.Item.new(62652, "Seasoned Crab", { buffFood = true })
ham.severedSagefishHead = ham.Item.new(62671, "Severed Sagefish Head", { buffFood = true })
ham.skeweredEel = ham.Item.new(62669, "Skewered Eel", { buffFood = true })
ham.tenderBakedTurtle = ham.Item.new(62658, "Tender Baked Turtle", { buffFood = true })
ham.venisonSteak = ham.Item.new(46392, "Venison Steak", { buffFood = true })
ham.whitecrestGumbo = ham.Item.new(62656, "Whitecrest Gumbo", { buffFood = true })

-- Cata - dual restore (health AND mana, no stats)
ham.conjuredManaBrownie = ham.Item.new(65515, "Conjured Mana Brownie", { conjured = true })
ham.conjuredManaCake = ham.Item.new(65499, "Conjured Mana Cake", { conjured = true })
ham.conjuredManaCookie = ham.Item.new(65500, "Conjured Mana Cookie", { conjured = true })
ham.conjuredManaCupcake = ham.Item.new(65516, "Conjured Mana Cupcake", { conjured = true })
ham.conjuredManaLollipop = ham.Item.new(65517, "Conjured Mana Lollipop", { conjured = true })
ham.scaldingMurglesnout = ham.Item.new(68687, "Scalding Murglesnout")

-- Cata - plain food (no stats), reskins of the same restore-only mechanic
ham.bearSteaks = ham.Item.new(62909, "\"Bear\" Steaks")
ham.deliciousWormSteak = ham.Item.new(64641, "\"Delicious\" Worm Steak")
ham.acidicDrink = ham.Item.new(67378, "Acidic Drink")
ham.acidicFood = ham.Item.new(67384, "Acidic Food")
ham.beerBastedShortRibs = ham.Item.new(75029, "Beer-Basted Short Ribs")
ham.bitterDrink = ham.Item.new(67374, "Bitter Drink")
ham.bitterFood = ham.Item.new(67380, "Bitter Food")
ham.blackenedSurprise = ham.Item.new(62676, "Blackened Surprise")
ham.brivelthwerpsCrunchyIceCreamBar = ham.Item.new(63691, "Brivelthwerp's Crunchy Ice Cream Bar")
ham.bubblingDrink = ham.Item.new(67373, "Bubbling Drink")
ham.bubblingFood = ham.Item.new(67379, "Bubbling Food")
ham.butteryWheatRoll = ham.Item.new(58261, "Buttery Wheat Roll")
ham.cheeryCherryPie = ham.Item.new(60375, "Cheery Cherry Pie")
ham.chillwindOmelet = ham.Item.new(67273, "Chillwind Omelet")
ham.countryPumpkin = ham.Item.new(60267, "Country Pumpkin")
ham.darkmoonDoughnut = ham.Item.new(74921, "Darkmoon Doughnut")
ham.draenicDumplings = ham.Item.new(75031, "Draenic Dumplings")
ham.exoticDrink = ham.Item.new(67371, "Exotic Drink")
ham.exoticFood = ham.Item.new(67365, "Exotic Food")
ham.fishFry = ham.Item.new(62677, "Fish Fry")
ham.forsakenFoieGras = ham.Item.new(75034, "Forsaken Foie Gras")
ham.foulDrink = ham.Item.new(67376, "Foul Drink")
ham.foulFood = ham.Item.new(67382, "Foul Food")
ham.frozenCreamCustard = ham.Item.new(63692, "Frozen \"Cream\" Custard")
ham.garrsKeyLimePie = ham.Item.new(61383, "Garr's Key Lime Pie")
ham.gilneanWhite = ham.Item.new(58276, "Gilnean White")
ham.gnomereganGnuggets = ham.Item.new(75030, "Gnomeregan Gnuggets")
ham.goblinShortbread = ham.Item.new(49600, "Goblin Shortbread")
ham.greenHamEggs = ham.Item.new(75033, "Green Ham & Eggs")
ham.grilledShark = ham.Item.new(58263, "Grilled Shark")
ham.halfEatenRat = ham.Item.new(49397, "Half-Eaten Rat")
ham.hardtack = ham.Item.new(58275, "Hardtack")
ham.hellHootBarbecue = ham.Item.new(67271, "Hell-Hoot Barbecue")
ham.highlandPomegranate = ham.Item.new(58265, "Highland Pomegranate")
ham.highlandSheepCheese = ham.Item.new(58259, "Highland Sheep Cheese")
ham.hoboSurprise = ham.Item.new(60268, "Hobo Surprise")
ham.hotCrossBuns = ham.Item.new(49603, "Hot Cross Buns")
ham.iceCreamBar = ham.Item.new(69244, "Ice Cream Bar")
ham.iceCreamCakeSlice = ham.Item.new(69243, "Ice Cream Cake Slice")
ham.lambShank = ham.Item.new(49361, "Lamb Shank")
ham.leftoverBoarMeat = ham.Item.new(57544, "Leftover Boar Meat")
ham.lotsOMeatPie = ham.Item.new(60377, "Lots 'o Meat Pie")
ham.massiveTurkeyLeg = ham.Item.new(58269, "Massive Turkey Leg")
ham.mrBubblesShockinglyDeliciousIceCream = ham.Item.new(57518, "Mr. Bubble's Shockingly Delicious Ice Cream")
ham.mudPie = ham.Item.new(60379, "Mud Pie")
ham.mulgoreMeatPie = ham.Item.new(75032, "Mulgore Meat Pie")
ham.oilyGiblets = ham.Item.new(59231, "Oily Giblets")
ham.ooeyGooeyGelato = ham.Item.new(63693, "Ooey Gooey Gelato")
ham.pineNutBread = ham.Item.new(58260, "Pine Nut Bread")
ham.plumpkinPie = ham.Item.new(60378, "Plumpkin Pie")
ham.puzzlingDrink = ham.Item.new(67369, "Puzzling Drink")
ham.puzzlingFood = ham.Item.new(67363, "Puzzling Food")
ham.roastedBeef = ham.Item.new(58268, "Roasted Beef")
ham.rockHardBiscuit = ham.Item.new(59227, "Rock-Hard Biscuit")
ham.saltySeaDog = ham.Item.new(73260, "Salty Sea Dog")
ham.scarletPolypore = ham.Item.new(58267, "Scarlet Polypore")
ham.shyRotamSteak = ham.Item.new(67272, "Shy-Rotam Steak")
ham.silithidFreeSorbet = ham.Item.new(63694, "Silithid-Free Sorbet")
ham.silvermoonSteak = ham.Item.new(75036, "Silvermoon Steak")
ham.simmeredSquid = ham.Item.new(58277, "Simmered Squid")
ham.slicedRawBillfish = ham.Item.new(58262, "Sliced Raw Billfish")
ham.slightlyWormEatenHardtack = ham.Item.new(49253, "Slightly Worm-Eaten Hardtack")
ham.smokedStringCheese = ham.Item.new(58258, "Smoked String Cheese")
ham.steamingDrink = ham.Item.new(67377, "Steaming Drink")
ham.steamingFood = ham.Item.new(67383, "Steaming Food")
ham.stewedRabbit = ham.Item.new(58280, "Stewed Rabbit")
ham.strangeDrink = ham.Item.new(67367, "Strange Drink")
ham.strangeFood = ham.Item.new(67361, "Strange Food")
ham.stuffedBushChicken = ham.Item.new(62910, "Stuffed Bush Chicken")
ham.sweetDrink = ham.Item.new(67375, "Sweet Drink")
ham.sweetFood = ham.Item.new(67381, "Sweet Food")
ham.tastyPuffball = ham.Item.new(58279, "Tasty Puffball")
ham.teldrassilTenderloin = ham.Item.new(75027, "Teldrassil Tenderloin")
ham.thriceSpicedCrunchyStew = ham.Item.new(69920, "Thrice-Spiced Crunchy Stew")
ham.trollTartare = ham.Item.new(75035, "Troll Tartare")
ham.tropicalSunfruit = ham.Item.new(58278, "Tropical Sunfruit")
ham.unidentifiableMeatDish = ham.Item.new(59232, "Unidentifiable Meat Dish")
ham.ursiusFlank = ham.Item.new(67270, "Ursius Flank")
ham.vegetarianDrink = ham.Item.new(67370, "Vegetarian Drink")
ham.vegetarianFood = ham.Item.new(67364, "Vegetarian Food")
ham.venisonJerky = ham.Item.new(67230, "Venison Jerky")
ham.vilePurpleFungus = ham.Item.new(59228, "Vile Purple Fungus")
ham.violetMorel = ham.Item.new(58266, "Violet Morel")
ham.weirdDrink = ham.Item.new(67368, "Weird Drink")
ham.weirdFood = ham.Item.new(67362, "Weird Food")
ham.wrigglingDrink = ham.Item.new(67372, "Wriggling Drink")
ham.wrigglingFood = ham.Item.new(67366, "Wriggling Food")
ham.yetichokeHearts = ham.Item.new(65731, "Yetichoke Hearts")

-- Mists - stat ("Well Fed") food, classified from Wowhead's actual tooltip effect text,
-- opt-in via HAMDB.includeBuffFood
ham.banquetOfTheBrew = ham.Item.new(87246, "Banquet of the Brew", { buffFood = true })
ham.banquetOfTheGrill = ham.Item.new(87226, "Banquet of the Grill", { buffFood = true })
ham.banquetOfTheOven = ham.Item.new(87242, "Banquet of the Oven", { buffFood = true })
ham.banquetOfThePot = ham.Item.new(87234, "Banquet of the Pot", { buffFood = true })
ham.banquetOfTheSteamer = ham.Item.new(87238, "Banquet of the Steamer", { buffFood = true })
ham.banquetOfTheWok = ham.Item.new(87230, "Banquet of the Wok", { buffFood = true })
ham.blackPepperRibsAndShrimp = ham.Item.new(74646, "Black Pepper Ribs and Shrimp", { buffFood = true })
ham.blanchedNeedleMushrooms = ham.Item.new(81412, "Blanched Needle Mushrooms", { buffFood = true })
ham.bloodberryTart = ham.Item.new(98124, "Bloodberry Tart", { buffFood = true })
ham.boiledSilkwormPupa = ham.Item.new(81405, "Boiled Silkworm Pupa", { buffFood = true })
ham.braisedTurtle = ham.Item.new(74649, "Braised Turtle", { buffFood = true })
ham.brewCurriedWhitefish = ham.Item.new(105719, "Brew-Curried Whitefish", { buffFood = true })
ham.camembertDuClefthoof = ham.Item.new(98122, "Camembert du Clefthoof", { buffFood = true })
ham.candiedApple = ham.Item.new(105720, "Candied Apple", { buffFood = true })
ham.chaoCookies = ham.Item.new(88586, "Chao Cookies", { buffFood = true })
ham.charbroiledTigerSteak = ham.Item.new(74642, "Charbroiled Tiger Steak", { buffFood = true })
ham.chunTianSpringRolls = ham.Item.new(74656, "Chun Tian Spring Rolls", { buffFood = true })
ham.crazySnakeNoodles = ham.Item.new(104340, "Crazy Snake Noodles", { buffFood = true })
ham.deluxeNoodleCartKit = ham.Item.new(101661, "Deluxe Noodle Cart Kit", { buffFood = true })
ham.deluxeNoodleSoup = ham.Item.new(101617, "Deluxe Noodle Soup", { buffFood = true })
ham.dentedCanOfKajacola = ham.Item.new(98127, "Dented Can of Kaja'Cola", { buffFood = true })
ham.driedNeedleMushrooms = ham.Item.new(81404, "Dried Needle Mushrooms", { buffFood = true })
ham.driedPeaches = ham.Item.new(81403, "Dried Peaches", { buffFood = true })
ham.eternalBlossomFish = ham.Item.new(74645, "Eternal Blossom Fish", { buffFood = true })
ham.farmersDelight = ham.Item.new(101747, "Farmer's Delight", { buffFood = true })
ham.fireSpiritSalmon = ham.Item.new(74652, "Fire Spirit Salmon", { buffFood = true })
ham.fluffySilkfeatherOmelet = ham.Item.new(101750, "Fluffy Silkfeather Omelet", { buffFood = true })
ham.friedCheeseDumplings = ham.Item.new(105724, "Fried Cheese Dumplings", { buffFood = true })
ham.goldenDragonNoodles = ham.Item.new(104343, "Golden Dragon Noodles", { buffFood = true })
ham.grandDeluxeNoodleCartKit = ham.Item.new(101729, "Grand Deluxe Noodle Cart Kit", { buffFood = true })
ham.grandNoodleCartKit = ham.Item.new(101727, "Grand Noodle Cart Kit", { buffFood = true })
ham.grandPandarenTreasureNoodleCartKit = ham.Item.new(101740, "Grand Pandaren Treasure Noodle Cart Kit", { buffFood = true })
ham.greatBanquetOfTheBrew = ham.Item.new(87248, "Great Banquet of the Brew", { buffFood = true })
ham.greatBanquetOfTheGrill = ham.Item.new(87228, "Great Banquet of the Grill", { buffFood = true })
ham.greatBanquetOfTheOven = ham.Item.new(87244, "Great Banquet of the Oven", { buffFood = true })
ham.greatBanquetOfThePot = ham.Item.new(87236, "Great Banquet of the Pot", { buffFood = true })
ham.greatBanquetOfTheSteamer = ham.Item.new(87240, "Great Banquet of the Steamer", { buffFood = true })
ham.greatBanquetOfTheWok = ham.Item.new(87232, "Great Banquet of the Wok", { buffFood = true })
ham.greatPandarenBanquet = ham.Item.new(75016, "Great Pandaren Banquet", { buffFood = true })
ham.greenCurryFish = ham.Item.new(81410, "Green Curry Fish", { buffFood = true })
ham.grilledDinosaurHaunch = ham.Item.new(94535, "Grilled Dinosaur Haunch", { buffFood = true })
ham.grummlecake = ham.Item.new(88379, "Grummlecake", { buffFood = true })
ham.halfALovelyApple = ham.Item.new(79320, "Half a Lovely Apple", { buffFood = true })
ham.harmoniousRiverNoodles = ham.Item.new(104339, "Harmonious River Noodles", { buffFood = true })
ham.hotPapayaMilk = ham.Item.new(105721, "Hot Papaya Milk", { buffFood = true })
ham.initiatesSerpentBrew = ham.Item.new(89589, "Initiate's Serpent Brew", { buffFood = true })
ham.initiatesTigerBrew = ham.Item.new(89596, "Initiate's Tiger Brew", { buffFood = true })
ham.luckyMushroomNoodles = ham.Item.new(104344, "Lucky Mushroom Noodles", { buffFood = true })
ham.mahsWarmYakTailStew = ham.Item.new(90457, "Mah's Warm Yak-Tail Stew", { buffFood = true })
ham.mangoIce = ham.Item.new(101745, "Mango Ice", { buffFood = true })
ham.mechanopeepFoieGras = ham.Item.new(98126, "Mechanopeep Foie Gras", { buffFood = true })
ham.moguFishStew = ham.Item.new(74650, "Mogu Fish Stew", { buffFood = true })
ham.noodleCartKit = ham.Item.new(101630, "Noodle Cart Kit", { buffFood = true })
ham.noodleSoup = ham.Item.new(101616, "Noodle Soup", { buffFood = true })
ham.novicesSerpentBrew = ham.Item.new(89588, "Novice's Serpent Brew", { buffFood = true })
ham.novicesTigerBrew = ham.Item.new(89595, "Novice's Tiger Brew", { buffFood = true })
ham.nuttyBrewBun = ham.Item.new(105722, "Nutty Brew-Bun", { buffFood = true })
ham.pandarenBanquet = ham.Item.new(74919, "Pandaren Banquet", { buffFood = true })
ham.pandarenTreasureNoodleCartKit = ham.Item.new(101662, "Pandaren Treasure Noodle Cart Kit", { buffFood = true })
ham.pandarenTreasureNoodleSoup = ham.Item.new(101618, "Pandaren Treasure Noodle Soup", { buffFood = true })
ham.peachPie = ham.Item.new(81411, "Peach Pie", { buffFood = true })
ham.peanutPorkChops = ham.Item.new(105723, "Peanut Pork Chops", { buffFood = true })
ham.pearlMilkTea = ham.Item.new(81414, "Pearl Milk Tea", { buffFood = true })
ham.poundedRiceCake = ham.Item.new(81400, "Pounded Rice Cake", { buffFood = true })
ham.redBeanBun = ham.Item.new(81408, "Red Bean Bun", { buffFood = true })
ham.ricePudding = ham.Item.new(86069, "Rice Pudding", { buffFood = true })
ham.riceWineMushrooms = ham.Item.new(105717, "Rice-Wine Mushrooms", { buffFood = true })
ham.roastedBarleyTea = ham.Item.new(81406, "Roasted Barley Tea", { buffFood = true })
ham.sauteedCarrots = ham.Item.new(74643, "Sauteed Carrots", { buffFood = true })
ham.seaMistRiceNoodles = ham.Item.new(74648, "Sea Mist Rice Noodles", { buffFood = true })
ham.seasonedPomfruitSlices = ham.Item.new(101746, "Seasoned Pomfruit Slices", { buffFood = true })
ham.serpentBrewOfAdversity = ham.Item.new(89590, "Serpent Brew of Adversity", { buffFood = true })
ham.serpentBrewOfFallenBlossoms = ham.Item.new(89593, "Serpent Brew of Fallen Blossoms", { buffFood = true })
ham.serpentBrewOfMeditation = ham.Item.new(89592, "Serpent Brew of Meditation", { buffFood = true })
ham.serpentBrewOfPilgrimage = ham.Item.new(89591, "Serpent Brew of Pilgrimage", { buffFood = true })
ham.serpentBrewOfSerenity = ham.Item.new(89594, "Serpent Brew of Serenity", { buffFood = true })
ham.shavedZangarTruffles = ham.Item.new(98125, "Shaved Zangar Truffles", { buffFood = true })
ham.shrimpDumplings = ham.Item.new(74651, "Shrimp Dumplings", { buffFood = true })
ham.skeweredPeanutChicken = ham.Item.new(81413, "Skewered Peanut Chicken", { buffFood = true })
ham.smallBambooShoot = ham.Item.new(77264, "Small Bamboo Shoot", { buffFood = true })
ham.smallRiceCake = ham.Item.new(77273, "Small Rice Cake", { buffFood = true })
ham.smallSugarcaneStalk = ham.Item.new(77272, "Small Sugarcane Stalk", { buffFood = true })
ham.spicedBlossomSoup = ham.Item.new(101748, "Spiced Blossom Soup", { buffFood = true })
ham.spicyMushanNoodles = ham.Item.new(104342, "Spicy Mushan Noodles", { buffFood = true })
ham.spicySalmon = ham.Item.new(86073, "Spicy Salmon", { buffFood = true })
ham.spicyVegetableChips = ham.Item.new(86074, "Spicy Vegetable Chips", { buffFood = true })
ham.squirmyDelight = ham.Item.new(88388, "Squirmy Delight", { buffFood = true })
ham.steamedCrabSurprise = ham.Item.new(74653, "Steamed Crab Surprise", { buffFood = true })
ham.steamingGoatNoodles = ham.Item.new(104341, "Steaming Goat Noodles", { buffFood = true })
ham.stuffedLushrooms = ham.Item.new(101749, "Stuffed Lushrooms", { buffFood = true })
ham.swirlingMistSoup = ham.Item.new(74644, "Swirling Mist Soup", { buffFood = true })
ham.tangyYogurt = ham.Item.new(81409, "Tangy Yogurt", { buffFood = true })
ham.tigerBrewOfAdversity = ham.Item.new(89597, "Tiger Brew of Adversity", { buffFood = true })
ham.tigerBrewOfFallenBlossoms = ham.Item.new(89600, "Tiger Brew of Fallen Blossoms", { buffFood = true })
ham.tigerBrewOfMeditation = ham.Item.new(89599, "Tiger Brew of Meditation", { buffFood = true })
ham.tigerBrewOfPilgrimage = ham.Item.new(89598, "Tiger Brew of Pilgrimage", { buffFood = true })
ham.tigerBrewOfSerenity = ham.Item.new(89601, "Tiger Brew of Serenity", { buffFood = true })
ham.toastedFishJerky = ham.Item.new(81402, "Toasted Fish Jerky", { buffFood = true })
ham.twinFishPlatter = ham.Item.new(74655, "Twin Fish Platter", { buffFood = true })
ham.valleyStirFry = ham.Item.new(74647, "Valley Stir Fry", { buffFood = true })
ham.whaleSharkCaviar = ham.Item.new(98123, "Whale Shark Caviar", { buffFood = true })
ham.wildfowlGinsengSoup = ham.Item.new(86070, "Wildfowl Ginseng Soup", { buffFood = true })
ham.wildfowlRoast = ham.Item.new(74654, "Wildfowl Roast", { buffFood = true })
ham.yakCheeseCurds = ham.Item.new(81401, "Yak Cheese Curds", { buffFood = true })

-- Mists - dual restore (health AND mana, no stats)
ham.conjuredManaBuns = ham.Item.new(80618, "Conjured Mana Buns", { conjured = true })
ham.conjuredManaPudding = ham.Item.new(80610, "Conjured Mana Pudding", { conjured = true })
ham.freezeDriedHyenaJerky = ham.Item.new(98116, "Freeze-Dried Hyena Jerky")
ham.ginsengTea = ham.Item.new(75026, "Ginseng Tea")
ham.kRE = ham.Item.new(98111, "K.R.E.")
ham.lemonFlowerPudding = ham.Item.new(108920, "Lemon Flower Pudding")
ham.madBrewersBreakfast = ham.Item.new(75038, "Mad Brewer's Breakfast")
ham.megaFood4000 = ham.Item.new(80239, "Mega Food 4000")
ham.perfectlyCookedInstantNoodles = ham.Item.new(86026, "Perfectly Cooked Instant Noodles")
ham.perpetualLeftovers = ham.Item.new(87253, "Perpetual Leftovers")
ham.scorpionCrunchies = ham.Item.new(98118, "Scorpion Crunchies")

-- Mists - plain food (no stats), reskins of the same restore-only mechanic
ham.ancientShawl = ham.Item.new(103644, "Ancient Shawl")
ham.barnacleBouillabaisse = ham.Item.new(82449, "Barnacle Bouillabaisse")
ham.batteredCarp = ham.Item.new(74609, "Battered Carp")
ham.chiltonStilton = ham.Item.new(81921, "Chilton Stilton")
ham.cornmealBiscuit = ham.Item.new(82450, "Cornmeal Biscuit")
ham.crispyDojaniEel = ham.Item.new(81175, "Crispy Dojani Eel")
ham.fishCake = ham.Item.new(74641, "Fish Cake")
ham.freshBread = ham.Item.new(86508, "Fresh Bread")
ham.frybread = ham.Item.new(82451, "Frybread")
ham.humongousFungus = ham.Item.new(81916, "Humongous Fungus")
ham.krasarangFritters = ham.Item.new(85504, "Krasarang Fritters")
ham.muttonStew = ham.Item.new(81917, "Mutton Stew")
ham.pepperedPuffball = ham.Item.new(81889, "Peppered Puffball")
ham.pickledPigsSnout = ham.Item.new(81918, "Pickled Pig's Snout")
ham.plumpFig = ham.Item.new(81920, "Plump Fig")
ham.redRaspberry = ham.Item.new(81919, "Red Raspberry")
ham.redridgeRoquefort = ham.Item.new(81922, "Redridge Roquefort")
ham.rootVeggieStew = ham.Item.new(88398, "Root Veggie Stew")
ham.slicedPeaches = ham.Item.new(86057, "Sliced Peaches")
ham.smokedSquidBelly = ham.Item.new(82448, "Smoked Squid Belly")
ham.sourGreenApple = ham.Item.new(58264, "Sour Green Apple")
ham.thickCutBacon = ham.Item.new(90135, "Thick-Cut Bacon")
ham.tortoiseJerky = ham.Item.new(83097, "Tortoise Jerky")

local function getRawFood()
  if ham.isRetail and ham.getFoodForRetail then return ham.getFoodForRetail() end
  if ham.isClassic and ham.getFoodForClassic then return ham.getFoodForClassic() end
  if ham.isTBC and ham.getFoodForTBC then return ham.getFoodForTBC() end
  if ham.isWrath and ham.getFoodForWrath then return ham.getFoodForWrath() end
  if ham.isCata and ham.getFoodForCata then return ham.getFoodForCata() end
  if ham.isMop and ham.getFoodForMists then return ham.getFoodForMists() end
  if ham.isForever and ham.getFoodForForever then return ham.getFoodForForever() end
  return {}
end

-- Return a prioritized list of food items for the current client, excluding
-- "buff food" (situational Well Fed stat food) unless the user opted in.
function ham.getFood()
  local list = getRawFood()
  if HAMDB and HAMDB.includeBuffFood then
    return list
  end
  local filtered = {}
  for _, item in ipairs(list) do
    if not item.hasTag("buffFood") then
      table.insert(filtered, item)
    end
  end
  return filtered
end
