----- AUTO GENERATED - DO NOT EDIT

local L = BtWQuests.L
L["ANCIENT_WAYGATES"] = "Ancient Waygates"
L["BORN_TO_BE_WILDER"] = "Born to Be Wilder"
L["BRONZE_ECONCILIATION"] = "Bronze Reconciliation"
L["CATALOGING_THE_EXPEIDITION"] = "Cataloging the Expedition"
L["DRAGON_ISLES_EMISSARY"] = "Dragon Isles Emissary"
L["DRAGON_SHARD_OF_KNOWLEDGE"] = "Dragon Shard of Knowledge"
L["MISFIT_DRAGONS"] = "Misfit Dragons"
L["OLD_HATREDS"] = "Old Hatreds"
L["REBEL_RESURGENCE"] = "Rebel Resurgence"
L["RECONCILIATION"] = "Reconciliation"
L["REFORGING_THE_TYRS_GUARD"] = "Reforging the Tyr's Guard"
L["RETURN_TO_LORDAERON"] = "Return to Lordaeron"
L["SPARK_OF_INGENUITY"] = "Spark of Ingenuity"
L["THE_COALITION_OF_FLAMES"] = "The Coalition of Flames"
L["THE_DRAGONS_AND_THE_SCALE_EXPEDITION"] = "The Dragons and the Scale Expedition"
L["THE_EARTHEN_RING"] = "The Earthen Ring"
L["THE_MOTHER_OATHSTONE"] = "The Mother Oathstone"
L["THE_VEILED_OSSUARY"] = "The Veiled Ossuary"
L["UNITED_AGAIN"] = "United Again"
L["ZSKERA_VAULTS"] = "Zskera Vaults"
