-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('deDE') -- luacheck: ignore
L["Cannot be disenchanted"] = "Kann nicht entzaubert werden"
L["Modifier to activate %s"] = "Modifikator, um %s zu aktivieren"
L["Press |A:NPE_LeftClick:18:18|a to cast |cff0090ff%s|r"] = "Drückt |A:NPE_LeftClick:18:18|a, um |cff0090ff%s|r zu wirken"
L["Press |A:NPE_LeftClick:18:18|a to use |cff0090ff%s|r"] = "Drückt |A:NPE_LeftClick:18:18|a, um |cff0090ff%s|r zu einzusetzen"
L["Requires %d %s."] = "Benötigt %d %s."
L["Requires %s"] = "Benötigt %1$s"

