-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('deDE') -- luacheck: ignore
L["Modifier to activate %s"] = "Modifikator, um %s zu aktivieren"

