-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('esMX') -- luacheck: ignore
L["Cannot be disenchanted"] = "No se puede desencantar"
L["Modifier to activate %s"] = "Modificador para activar %s"
L["Press |A:NPE_LeftClick:18:18|a to cast |cff0090ff%s|r"] = "Presiona |A:NPE_LeftClick:18:18|a para lanzar |cff0090ff%s|r"
L["Press |A:NPE_LeftClick:18:18|a to use |cff0090ff%s|r"] = "Presiona |A:NPE_LeftClick:18:18|a para usar |cff0090ff%s|r"
L["Requires %d %s."] = "Necesita %d %s."
L["Requires %s"] = "Requiere %s"

