-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('frFR') -- luacheck: ignore
L["Cannot be disenchanted"] = "Ne peut pas être désenchanté"
L["Modifier to activate %s"] = "Modificateur pour activer %s"
L["Press |A:NPE_LeftClick:18:18|a to cast |cff0090ff%s|r"] = "Appuyez sur |A:NPE_LeftClick:18:18|a pour lancer |cff0090ff%1$s|r"
L["Press |A:NPE_LeftClick:18:18|a to use |cff0090ff%s|r"] = "Appuyez sur |A:NPE_LeftClick:18:18|a pour utiliser |cff0090ff%1$s|r"
L["Requires %d %s."] = "%d exemplaires |2 %s requis."
L["Requires %s"] = "Requiert %s"

