-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('itIT') -- luacheck: ignore
L["Cannot be disenchanted"] = "Impossibile disincantare"
L["Modifier to activate %s"] = "Modificatore per attivare %s"
L["Press |A:NPE_LeftClick:18:18|a to cast |cff0090ff%s|r"] = "Premi |A:NPE_LeftClick:18:18|a per lanciare |cff0090ff%s|r"
L["Press |A:NPE_LeftClick:18:18|a to use |cff0090ff%s|r"] = "Premi |A:NPE_LeftClick:18:18|a per usare |cff0090ff%s|r"
L["Requires %d %s."] = "Richiede %d %s."
L["Requires %s"] = "Richiede %s"

