-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('koKR') -- luacheck: ignore
L["Cannot be disenchanted"] = "마력 추출 불가"
L["Modifier to activate %s"] = "‘%s’를 활성화할 수정키"
L["Press |A:NPE_LeftClick:18:18|a to cast |cff0090ff%s|r"] = "|A:NPE_LeftClick:18:18|a 키를 눌러 |cff0090ff%s|1|r을;를; 시전하십시오"
L["Press |A:NPE_LeftClick:18:18|a to use |cff0090ff%s|r"] = "|A:NPE_LeftClick:18:18|a 키를 눌러 |cff0090ff%s|1|r을;를; 사용하십시오"
L["Requires %d %s."] = "%2$s %1$d개가 필요합니다."
L["Requires %s"] = "%s|1이;가; 필요합니다"

