-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('ptBR') -- luacheck: ignore
L["Cannot be disenchanted"] = "Não é possível desencantar este item"
L["Modifier to activate %s"] = "Modificador para ativar %s"
L["Press |A:NPE_LeftClick:18:18|a to cast |cff0090ff%s|r"] = "Pressione |A:NPE_LeftClick:18:18|a para lançar |cff0090ff%s|r"
L["Press |A:NPE_LeftClick:18:18|a to use |cff0090ff%s|r"] = "Pressione |A:NPE_LeftClick:18:18|a para usar |cff0090ff%s|r"
L["Requires %d %s."] = "Requer %d %s."
L["Requires %s"] = "Requer %s"

