-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('ruRU') -- luacheck: ignore
L["Cannot be disenchanted"] = "Нельзя распылить"
L["Modifier to activate %s"] = "Модификатор для активации %s"
L["Press |A:NPE_LeftClick:18:18|a to cast |cff0090ff%s|r"] = "Нажмите |A:NPE_LeftClick:18:18|a, чтобы применить |cff0090ff%s|r"
L["Press |A:NPE_LeftClick:18:18|a to use |cff0090ff%s|r"] = "Нажмите |A:NPE_LeftClick:18:18|a, чтобы применить |cff0090ff%s|r"
L["Requires %d %s."] = "Требуется: %2$s %1$d."
L["Requires %s"] = "Требуется: %s"

