-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('zhTW') -- luacheck: ignore

L['Modifier to activate %s'] = '分解時要按住的輔助鍵'

-- 自行加入
L['Molinari'] = '專業-分解'
