-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('zhTW') -- luacheck: ignore
L["Cannot be disenchanted"] = "無法分解"
L["Modifier to activate %s"] = "啟動 %s 的修飾鍵"
L["Press |A:NPE_LeftClick:18:18|a to cast |cff0090ff%s|r"] = "按下|A:NPE_LeftClick:18:18|a施放|cff0090ff%s|r"
L["Press |A:NPE_LeftClick:18:18|a to use |cff0090ff%s|r"] = "按下|A:NPE_LeftClick:18:18|a就可以使用|cff0090ff%s|r"
L["Requires %d %s."] = "需要%d%s。"
L["Requires %s"] = "需要%s"

