-- Assistant geometry parser data.
-- Generated phrase lists for MSUF_AssistantParser_Geometry.lua.
local addonName, MSUF = ...
MSUF = MSUF or _G.MSUF_NS or {}

local M = MSUF.MSUF2 or _G.MSUF2 or {}
MSUF.MSUF2 = M

local A = MSUF.Assistant or {}
MSUF.Assistant = A
M.Assistant = A

local Data = A.ParserData or {}
A.ParserData = Data

Data.GEOMETRY_PARSER = {
    PHRASES = {
        [1] = {
        "as big as", "same size as", "the same size as", "same width and height as",
        "so gross wie", "gleich gross wie", "gleiche groesse wie", "dieselbe groesse wie",
        -- Single-dimension matching ("the same width as the target frame").
        -- Without these the lane returned before its patterns ran, and the most
        -- precise form of the request -- which names both the value to copy and
        -- the frame to copy it from -- reached no lane at all.
        "same width as", "same height as", "as wide as", "as tall as", "as high as",
        "gleiche breite wie", "gleiche hoehe wie", "so breit wie", "so hoch wie",
    },
        [2] = { "castbar", "cast bar", "class power", "class resource", "aura", "auras" },
        [3] = { "combat timer alpha", "combat timer opacity", "combat timer transparency" },
        [4] = {
        "all", "all of", "for all", "every", "each",
        "alle", "alles", "fuer alle", "jede", "jeder", "jedes", "jeweils",
    },
        [5] = { "portrait", "portraits" },
        [6] = { "color", "colour", "farbe", "reset" },
        [7] = {
        "keep text portrait visible", "keep text and portrait visible", "keep text & portrait visible", "keep text visible", "keep portrait visible",
        "exclude text from opacity", "exclude portrait from opacity", "text portrait opacity", "text and portrait opacity", "text & portrait opacity",
    },
        [8] = { "move", "nudge", "shift", "verschiebe", "offset" },
        [9] = { "x offset", "offset x", "portrait x", "horizontal offset" },
        [10] = { "y offset", "offset y", "portrait y", "vertical offset" },
        [11] = { "class portrait style", "portrait class style" },
        [12] = { "default" },
        [13] = { "render", "type", "2d", "2d portrait", "class portrait", "to class" },
        [14] = { "class portrait style", "portrait class style", "border" },
        [15] = { "2d", "2d portrait", "normal portrait", "normal render" },
        [16] = { "class portrait", "class render", "class icon", "class icons", "to class" },
        [17] = { "shape", "square", "circle", "rounded", "round", "diamond", "blizzard ring", "gold ring", "goldring" },
        [18] = { "square" },
        [19] = { "rounded" },
        [20] = { "circle", "round" },
        [21] = { "diamond" },
        [22] = { "fill border", "border gap", "frame gap", "fill portrait border", "fill border into frame gap" },
        [23] = { "fill", "into gap", "frame gap" },
        [24] = { "portrait background", "portrait bg" },
        [25] = { "border thickness", "border size", "border thicker", "border thinner", "thicker", "thinner", "dicker", "duenner" },
        [26] = { "zoom", "portrait zoom", "2d portrait zoom", "reinzoomen", "rauszoomen", "crop" },
        [27] = { "size", "size override", "bigger", "smaller", "larger", "groesser", "kleiner" },
        [28] = { "border" },
        [29] = { "off", "disable", "disabled", "hide", "none", "no border", "aus", "deaktivieren" },
        [30] = { "on", "enable", "enabled", "show", "solid", "an", "aktivieren" },
        [31] = { "class color", "class" },
        [32] = { "reaction" },
        [33] = { "custom" },
        [34] = { "off", "disable", "disabled", "hide", "aus", "deaktivieren" },
        [35] = { "right" },
        [36] = { "on", "enable", "enabled", "show", "left", "an", "aktivieren" },
        [37] = { term },
        [38] = { "unitframe", "unitframes", "unit frame", "unit frames", "frame", "frames" },
        [39] = { "group", "group frame", "group frames", "party", "raid", "mythic raid", "mythicraid" },
        [40] = { "move", "nudge", "shift", "verschiebe", "offset", "position", "pos", "x", "y" },
        [41] = { "castbar", "cast bar", "zauberleiste" },
        [42] = { "detached power", "detached power bar", "detached mana", "detached mana bar" },
        [43] = { "move", "nudge", "shift", "verschiebe", "offset" },
        [44] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar" },
        [45] = {
        "power text", "mana text", "power value", "mana value", "power number", "mana number",
        "power label", "mana label", "energie text", "resource text", "resource label",
    },
        [46] = {
        "powerbar", "power bar", "mana bar", "manabar", "power balken", "mana balken",
    },
        [47] = {
            "closer to", "nearer to", "toward", "towards", "move to", "move closer", "move nearer",
            "near", "near to", "next to", "put near", "put next to", "place near", "place next to",
            "follow", "dock to", "attach to", "anchor to", "snap to", "bring closer",
            "under", "below", "above", "over",
        },
        [48] = { "cooldown manager", "cooldownmanager", "cdm" },
        [49] = { "detached", "undocked", "separate", "separated", "abgekoppelt" },
        [50] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar" },
        [51] = {
        "closer together", "closer to each other", "closer", "nearer together", "nearer to each other",
        "bring closer", "bring together", "naeher zusammen", "zusammen naeher",
    },
        [52] = {
        "farther apart", "further apart", "move apart", "spread apart", "more space", "more spacing",
        "more distance", "space between", "away from each other", "weiter auseinander", "mehr abstand",
    },
        [53] = { "horizontal", "horizontally", "x axis", "x-axis", "left right", "left/right" },
        [54] = { "vertical", "vertically", "y axis", "y-axis", "up down", "up/down" },
        [55] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar" },
        [56] = { "boss", "boss frame", "boss frames", "bossframe", "bossframes" },
        [57] = {
        "closer together", "closer to each other", "nearer together", "bring together",
        "less space", "less spacing", "reduce spacing", "decrease spacing", "tighten spacing",
        "smaller spacing", "smaller gap", "less gap", "compact spacing",
        "tighter", "tighter spacing", "more compact", "too far apart",
    },
        [58] = {
        "farther apart", "further apart", "spread apart", "spread out", "space out",
        "more space", "more spacing", "more distance", "increase spacing", "add spacing",
        "add space between", "bigger spacing", "larger spacing", "bigger gap", "larger gap",
        "looser", "looser spacing", "too close",
    },
        [59] = { "spread", "space" },
        [60] = { "apart", "out" },
        [61] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar" },
        [62] = {
        "portrait", "name", "hp text", "health text", "power text", "mana text", "status icon",
        "indicator", "border padding", "group border", "power bar", "health bar",
    },
        [63] = {
        "closer together", "closer to each other", "nearer together", "bring together",
        "less space", "less spacing", "reduce spacing", "decrease spacing", "tighten spacing",
        "smaller spacing", "smaller gap", "less gap", "compact spacing",
        "tighter", "tighter spacing", "more compact", "closer vertically", "closer horizontally",
    },
        [64] = {
        "farther apart", "further apart", "spread apart", "spread out", "space out",
        "more space", "more spacing", "more distance", "increase spacing", "add spacing",
        "add space between", "bigger spacing", "larger spacing", "bigger gap", "larger gap",
        "looser", "looser spacing", "farther vertically", "farther horizontally",
    },
        [65] = { "spread", "space" },
        [66] = { "apart", "out" },
        [67] = {
        "utility cooldown", "utility cooldowns", "utility cooldown manager", "utility cooldownmanager",
        "utility cooldown viewer", "ucv",
    },
        [68] = {
        "tracked buff", "tracked buffs", "tracked buffs viewer", "buff icon cooldown viewer",
        "buff cooldown viewer", "buff tracker",
    },
        [69] = {
        "essential cooldown", "essential cooldowns", "essential cooldown manager", "essential cooldownmanager",
        "essential cooldown viewer", "cooldown manager", "cooldownmanager", "cooldowns manager", "cdm",
    },
        [70] = { "open", "where", "where is", "where are", "how", "help", "settings", "setting", "page" },
        [71] = { "anchor", "anchors", "custom anchor", "anchor settings", "anchor page" },
        [72] = {
        "close to", "closer to", "nearer to", "toward", "towards", "move to", "move closer", "move nearer",
        "near", "near to", "next to", "put near", "put next to", "place near", "place next to",
        "follow", "dock to", "attach to", "anchor to", "snap to", "bring closer",
    },
        [73] = { "unitframe", "unitframes", "unit frame", "unit frames", "group frame", "group frames", "party frames", "raid frames" },
        [74] = { "frame", "frames", "all frames", "everything", "all msuf", "all ui" },
        [75] = { "custom anchor", "custom anchor frame", "anchor frame name", "anchor point", "anchor position" },
        [76] = {
        "portrait", "castbar", "cast bar", "name text", "hp text", "health text", "power text",
        "powerbar", "power bar", "mana bar", "manabar", "power balken", "mana balken",
        "text", "icon", "indicator", "raid marker", "status", "level", "level indicator",
        "raid group name", "group number", "leader", "assist", "elite", "rare",
        "combat indicator", "rested", "resting", "incoming rez", "incoming resurrection",
        "ready check", "ready icon", "role icon", "leader icon", "assist icon", "summon icon",
        "resurrect icon", "resurrection icon", "rez icon", "pvp icon", "phase icon",
        "dead text", "ghost text", "afk text", "dnd text",
    },
        [77] = {
        "close to", "closer to", "nearer to", "toward", "towards", "move to", "move closer", "move nearer",
        "near", "near to", "next to", "put near", "put next to", "place near", "place next to",
        "follow", "dock to", "attach to", "anchor to", "snap to", "bring closer",
    },
        [78] = { "put", "place", "move", "anchor", "attach" },
        [79] = { "under", "below", "above", "over" },
        [80] = {
        "away from", "farther from", "further from", "move away", "move away from",
        "detach from", "undock from", "disconnect from", "detach", "undock", "free anchor",
        "free from anchor", "clear anchor",
    },
        [81] = { "unitframe", "unitframes", "unit frame", "unit frames" },
        [82] = { "frame", "frames", "all frames", "everything", "all msuf", "all ui" },
        [83] = {
        "over 25", "above 25", "more than 25", "over twenty five", "above twenty five",
        "25 plus", "25+", "25 or more", "26 plus", "26+", "26 or more", "large raid", "full raid",
        "raid is full", "full group", "full party", "full size raid", "max raid", "maximum raid",
        "when full", "at full", "is full", "full roster",
    },
        [84] = {
            "1-10", "1 to 10", "one to ten", "small group", "small raid", "small party",
            "dungeon group", "dungeon party", "five man", "five-man", "5 man", "5-man", "5m",
        },
        [85] = { "11-20", "11 to 20", "eleven to twenty" },
        [86] = { "21-25", "21 to 25", "twenty one to twenty five" },
        [87] = {
        "normal size", "normal scale", "normal scaling", "default scale", "default scaling",
        "full size", "regular size", "regular scale", "back to 100", "back to normal",
    },
        [88] = {
        "decrease", "lower", "reduce", "smaller", "shrink", "scale down",
        "less scale", "less scaling", "kleiner", "senke", "reduziere", "weniger",
    },
        [89] = {
        "increase", "raise", "higher", "bigger", "larger", "grow", "scale up",
        "more scale", "more scaling", "groesser", "erhoehe", "mehr",
    },
        [90] = { "a little", "a bit", "slightly", "small amount", "klein wenig" },
        [91] = { "a lot", "much", "massive", "huge", "large amount", "stark" },
        [92] = { "aura", "auras", "buff", "debuff" },
        [93] = {
        "scale", "scaling", "frame scale", "raid scale", "party scale", "mythic raid scale",
        "players", "raider", "raiders", "people", "persons", "members",
        "raid member", "raid members", "player count", "raid size",
        "when we are", "when we have", "when our group is", "when our raid is",
        "if we are", "if we have", "if our group is", "if our raid is",
        "with us at", "with the group at", "with the raid at",
        "full raid", "large raid", "big raid", "max raid", "maximum raid",
        "raid is full", "full group", "full size raid", "when full", "at full", "full roster",
        "small raid", "small group", "small party", "dungeon group", "dungeon party",
        "five man", "5 man", "5m",
    },
        [94] = { "right then down", "right and down", "right first", "grow right", "to the right", "horizontal", "horizontally", "rechts" },
        [95] = { "left then down", "left and down", "left first", "grow left", "to the left", "links" },
        [96] = { "down then right", "down and right", "down first", "grow down", "downwards", "vertical", "vertically", "runter", "unten" },
        [97] = { "up then right", "up and right", "up first", "grow up", "upwards", "hoch", "oben" },
        [98] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar" },
        [99] = { "grow", "growth", "growth direction", "fill direction", "layout direction" },
        [100] = { "a lot", "much", "massive", "huge", "large amount", "stark" },
        [101] = { "power bar", "mana bar", "power balken", "mana balken" },
        [102] = {
        "power text", "mana text", "power value", "mana value", "power number", "mana number",
        "power label", "mana label", "border", "outline", "aura", "auras", "buff", "debuff",
        "class power", "class resource", "castbar", "cast bar",
    },
        [103] = { "wider", "wide", "increase width", "more width", "breiter" },
        [104] = { "narrower", "decrease width", "less width", "schmaler" },
        [105] = {
        "taller", "higher", "thicker", "increase height", "more height", "bigger", "larger",
        "increase size", "make bigger", "make larger", "hoeher", "dicker",
    },
        [106] = {
        "shorter", "lower", "thinner", "decrease height", "less height", "smaller", "shrink",
        "reduce size", "make smaller", "niedriger", "duenner",
    },
        [107] = { "height", "hoehe" },
        [108] = { "move", "nudge", "shift", "verschiebe", "offset", "position", "pos", "x", "y" },
        [109] = { "increase", "raise" },
        [110] = { "size", "frame size", "unitframe size", "unit frame size" },
        [111] = { "decrease", "reduce", "lower" },
        [112] = { "size", "frame size", "unitframe size", "unit frame size" },
        [113] = { "a bit", "bit", "little", "slightly", "small amount" },
        [114] = { "a lot", "lot", "much", "massive", "huge", "big amount" },
        [115] = { "detached", "detached power", "detached power bar", "detached mana", "detached mana bar" },
        [116] = { "power", "mana", "role power", "healer power", "tank power" },
        [117] = { "width", "frame width", "unit frame width", "unitframe width", "breite", "frame breite" },
        [118] = { "height", "frame height", "unit frame height", "unitframe height", "hoehe", "frame hoehe" },
        [119] = {
        "wider", "narrower", "taller", "shorter", "bigger", "larger", "smaller",
        "increase", "decrease", "reduce", "raise", "lower", "grow", "shrink", "by",
        "breiter", "schmaler", "hoeher", "duenner", "groesser", "kleiner",
    },
        [120] = {
        "both", "width and height", "height and width", "whole frame", "entire frame",
        "overall", "all around", "in both directions",
    },
        [121] = { "height", "power height", "mana height", "hoehe" },
        [122] = { "width", "power width", "mana width", "breite" },
        [123] = { "a bit", "bit", "little", "slightly", "small amount" },
        [124] = { "a lot", "lot", "much", "massive", "huge", "big amount" },
        [125] = { "all", "all unitframes", "all unit frames", "every", "each", "alle" },
        [126] = { "height", "power height", "mana height", "hoehe" },
        [127] = { "width", "power width", "mana width", "breite" },
        [128] = { "increase", "raise", "more", "grow", "hoeher", "groesser" },
        [129] = { "decrease", "reduce", "lower", "less", "shrink", "niedriger", "kleiner" },
        [130] = { "all", "all unitframes", "all unit frames", "every", "each", "alle" },
        [131] = { "detached", "undocked", "separate", "separated", "abgekoppelt" },
        [132] = {
        "show me", "tell me", "what is", "whats", "which", "where", "why",
        "explain", "help", "option", "options", "setting", "settings", "page", "tab",
    },
        [133] = { "castbar", "cast bar", "aura", "auras", "buff", "debuff", "class power", "class resource", "class resources" },
        [134] = { "power bar", "powerbar", "mana bar", "mana balken", "power balken" },
        [135] = {
        "reverse hp text", "hp text reverse", "reverse health text", "health text reverse",
        "hide name on dead", "hide name when dead", "hide name on offline", "hide name when offline", "dead or offline",
    },
        [136] = {
        "power text", "mana text", "energy text", "resource text", "energie text", "ressource text",
        "power number", "power numbers", "mana number", "mana numbers", "energy number", "energy numbers",
    },
        [137] = {
        "hp text", "health text", "life text", "leben text", "gesundheit text",
        "hp number", "hp numbers", "health number", "health numbers", "life number", "life numbers",
    },
        [138] = { "name text", "unit name", "unit names", "names", "name" },
        [139] = {
        "all", "all of", "for all", "every", "each",
        "alle", "alles", "fuer alle", "jede", "jeder", "jedes", "jeweils",
    },
        [140] = { "custom anchor", "custom anchor frame", "anchor frame name", "anchor point", "anchor position" },
        [141] = {
        "portrait", "castbar", "cast bar", "name text", "hp text", "health text", "power text",
        "text", "icon", "indicator", "raid marker", "status", "level", "level indicator",
        "raid group name", "group number", "leader", "assist", "elite", "rare",
        "combat indicator", "rested", "resting", "incoming rez", "incoming resurrection",
    },
        [142] = { "anchor to", "attach to", "anchored to", "anchor target", "anchor frame" },
        [143] = { "unitframe", "unitframes", "unit frame", "unit frames" },
        [144] = { "castbar", "cast bar", "zauberleiste", "portrait" },
        [145] = { "move", "nudge", "shift", "verschiebe", "offset" },
        [146] = { "x offset", "x position", "x pos", "horizontal", "left right" },
        [147] = { "y offset", "y position", "y pos", "vertical", "up down" },
        [148] = { "castbar", "cast bar", "zauberleiste", "portrait" },
        [149] = { "offset", "position", "pos", "x", "y" },
        [150] = { "border", "outline" },
        [151] = { "portrait", "castbar", "cast bar", "class power", "class resource", "class resources", "power bar", "mana bar", "power border", "mana border", "detached power", "group border", "group frame border" },
        [152] = { "color", "colour", "farbe", "opacity", "alpha", "transparent", "transparency", "reset" },
        [153] = { "aggro", "threat", "dispel", "dispellable", "purge", "purgeable", "boss target", "highlight" },
        [154] = {
        "frame outline", "frame border", "bar outline", "bar border", "border outline", "outline border",
        "outline thickness", "border thickness", "outline size", "border size", "outline width", "border width",
        "outline thicker", "outline thinner", "border thicker", "border thinner",
        "thicker", "thinner", "bigger", "larger", "smaller", "dicker", "duenner",
    },
        [155] = { "thicker", "thinner", "bigger", "larger", "smaller", "increase", "decrease", "dicker", "duenner" },
        [156] = { "global", "shared", "all scopes" },
        [157] = {
        "custom highlight priority", "highlight priority", "border priority", "highlight border priority",
        "highlight prio", "border prio", "custom highlight prio", "highlight prioritaet", "border prioritaet",
    },
        [158] = {
        "highlight border thickness", "highlight border size", "highlight border width",
        "aggro border size", "aggro border thickness", "aggro border width",
        "dispel border size", "dispel border thickness", "dispel border width",
    },
        [159] = {
        "bar outline opacity", "bar outline alpha", "frame outline opacity", "frame outline alpha",
        "bar border opacity", "bar border alpha", "frame border opacity", "frame border alpha",
        "outline opacity", "outline alpha", "border opacity", "border alpha",
    },
        [160] = {
        "bar outline thickness", "bar outline size", "bar outline width", "bar outline",
        "frame outline thickness", "frame outline size", "frame outline width", "frame outline",
        "bar border thickness", "bar border size", "bar border width",
        "frame border thickness", "frame border size", "frame border width",
        "outline thickness", "outline size", "outline width",
        "border thickness", "border size", "border width",
        "outline thicker", "outline thinner", "border thicker", "border thinner",
        "outline bigger", "outline smaller", "border bigger", "border smaller",
    },
        [161] = { "outline", "border", "highlight", "prio", "priority" },
        [162] = { "global", "shared", "all scopes" },
        [163] = { "heal prediction anchor", "heal prediction anchoring", "incoming heal anchor" },
        [164] = { "heal prediction", "heal prediction overlay", "incoming heal prediction" },
        [165] = { "heal absorb texture", "heal-absorb texture", "heal absorb bar texture" },
        [166] = { "heal absorb opacity", "heal-absorb opacity", "heal absorb bar opacity", "heal absorb alpha" },
        [167] = { "absorb display mode", "absorb mode", "absorb bars" },
        [168] = { "absorb bar anchor", "absorb anchor", "absorb anchoring" },
        [169] = { "over absorb overlay", "over-absorb overlay", "over absorb glow", "overshield overlay", "full hp absorb overlay", "full health absorb overlay" },
        [170] = { "absorb bar texture", "absorb texture" },
        [171] = { "absorb bar opacity", "absorb opacity", "absorb alpha" },
        [172] = { "absorb", "heal prediction", "incoming heal" },
        [173] = {
        "color", "colors", "colour", "colours", "farbe", "farben", "tint",
        "test", "preview", "show preview", "hide preview",
        "aura", "auras", "buff", "debuff", "castbar", "cast bar", "power bar", "class resource", "class power",
    },
        [174] = { "boss target border", "boss target outline" },
        [175] = {
        "aggro shows for", "aggro role filter", "aggro non tanks", "aggro not tank",
        "threat shows for", "threat role filter", "threat non tanks",
    },
        [176] = { "dispel border detects", "dispel border trigger", "dispel detection" },
        [177] = { "aggro border", "threat border", "aggro outline", "threat outline" },
        [178] = { "dispel border", "dispellable border", "dispel outline" },
        [179] = { "purge border", "purge outline", "purgeable border" },
        [180] = { "aggro", "threat", "dispel", "dispellable", "purge", "purgeable", "boss target" },
        [181] = {
        "fallback", "fallback aggro", "fallback threat",
        "aura", "auras", "buff", "debuff", "native group aura",
        "overlay", "unitframe dispel overlay", "unit frame dispel overlay", "debuff overlay",
        "color", "colors", "colour", "colours", "opacity", "alpha",
        "thickness", "size", "width",
        "test", "preview", "castbar", "cast bar", "class resource", "class power",
    },
        [182] = { "castbar", "cast bar", "zauberleiste" },
        [183] = { "offset" },
        [184] = { "wider", "wider bar", "make wider", "increase width", "raise width", "larger width", "more width", "breiter" },
        [185] = { "narrower", "make narrower", "decrease width", "reduce width", "smaller width", "less width", "schmaler" },
        [186] = { "taller", "higher", "make taller", "increase height", "raise height", "larger height", "more height", "hoeher" },
        [187] = { "shorter", "lower", "make shorter", "decrease height", "reduce height", "smaller height", "less height", "niedriger" },
        [188] = { "bigger", "larger", "increase size", "make bigger", "make larger" },
        [189] = { "smaller", "decrease size", "reduce size", "make smaller", "shrink" },
        [190] = { "castbar", "cast bar", "zauberleiste" },
        [191] = { "aura", "auras", "buff", "debuff" },
        [192] = {
        "icon", "spell name", "spell text", "castbar text", "castbar name", "timer", "time text",
        "border", "outline", "spark", "latency", "focus kick", "interrupt ready",
    },
        [193] = { "castbar", "cast bar", "zauberleiste" },
        [194] = { "aura", "auras", "buff", "debuff" },
        [195] = { "icon", "spell name", "spell text", "timer", "time text", "interrupt ready", "focus kick" },
        [196] = { "move", "put", "place", "position" },
        [197] = { "under", "below", "beneath", "underneath" },
        [198] = { "above", "over", "on top of" },
        [199] = { "castbar", "cast bar", "zauberleiste" },
        [200] = { "aura", "auras", "buff", "debuff" },
        [201] = { "move", "nudge", "shift", "offset", "position" },
        [202] = { "font size", "text size", "size", "bigger", "larger", "smaller", "increase", "decrease", "raise", "reduce" },
        [203] = { "spell name", "spell text", "castbar text", "castbar name", "timer", "time text", "cast time" },
        [204] = { "timer", "time text", "cast time" },
        [205] = { "spell name", "spell text", "castbar text", "castbar name", "text" },
        [206] = { "bigger", "larger", "increase", "raise", "more", "groesser" },
        [207] = { "smaller", "decrease", "reduce", "lower", "less", "kleiner" },
        [208] = { "castbar", "cast bar", "zauberleiste" },
        [209] = { "move", "nudge", "shift", "verschiebe", "offset" },
        [210] = { "time text", "castbar time", "cast time", "timer", "time" },
        [211] = { "spell name", "spell text", "castbar text", "castbar name", "text" },
        [212] = { "alpha", "opacity", "transparency", "transparent", "opaque" },
        [213] = { "edit mode", "editmode", "editor mode" },
        [214] = { "class power", "class resource", "class resources", "resource bar", "alt mana", "alternative mana", "secondary mana", "dual resource mana" },
        [215] = { "player hp bar opacity", "player health bar opacity" },
        [216] = {
            "second", "duplicate", "class resource", "class power", "background", "backdrop", "bg",
            "text", "font", "outline", "border", "color", "colour", "texture",
        },
        [217] = { "more transparent", "more transparency", "more see through", "transparenter" },
        [218] = { "less transparent", "less transparency", "more opaque", "opaquer" },
        -- Words that name an opacity belonging to some OTHER control, so the
        -- unit-frame alpha lane must not claim them. Each one owns a
        -- "background"/"opacity" wording of its own; without the guard the lane
        -- reads "temp max health background opacity" as unit alpha and asks
        -- "which unit frame alpha?" for a setting that is not per-unit at all.
        [219] = {
        "second hp", "duplicate hp", "second health", "duplicate health", "player hp bar",
        "bar outline", "outline opacity", "outline alpha", "border opacity", "border alpha",
        "highlight border", "group border", "dead background", "dead bg", "health fade",
        "temp max health", "temporary max health", "temp maximum health",
        "maximum health loss", "max health loss", "max hp loss", "maximum health reduction",
        "max health reduction", "maximum health loss overlay", "max health loss overlay",
        "heal prediction", "healing prediction", "incoming heal",
        -- Opacity words belong to these Bars controls, not to the unit frame's
        -- own alpha: "make the shield bar 50% transparent" was answered with
        -- "which unit frame alpha do you want me to change?".
        "frame border", "frame outline", "shield bar", "absorb bar", "absorbs",
        "heal absorb", "healing absorb",
    },
        [220] = { "power bar", "powerbar", "power opacity", "power alpha", "mana bar", "mana opacity", "mana alpha", "resource bar", "resource opacity", "resource alpha" },
        [221] = { "background", "backdrop", "track", "hp track", "health track", "bg", "bar background" },
        [222] = {
        "range fade", "in combat", "out of combat", "outside combat", "sync", "affects", "fade target",
        "preserve hp",
        "text opacity", "text alpha", "font opacity", "font alpha", "absorb", "heal absorb",
        "dispel overlay", "debuff overlay", "unitframe dispel overlay", "unit frame dispel overlay",
        "dispel symbol", "unitframe dispel symbol", "unit frame dispel symbol",
    },
        [223] = { "more transparent", "more transparency", "more see through", "transparenter" },
        [224] = { "less transparent", "less transparency", "more opaque", "opaquer" },
        [225] = { "alpha", "opacity", "transparency", "transparent", "opaque" },
        [226] = { "edit mode", "editmode", "editor mode" },
        [227] = {
        "bar outline", "outline opacity", "outline alpha", "border opacity", "border alpha",
        "highlight border", "group border", "dead background", "dead bg", "dead member",
        "dead offline", "offline opacity", "health fade",
        -- The portrait owns its own opacity pair (portraitAlpha and
        -- portraitBgColorA). Without these the health-bar shortcut claimed
        -- "party portrait opacity" and wrote hpBarAlpha instead.
        "portrait", "portraits", "portraet",
    },
        [228] = { "background", "backdrop", "track", "hp track", "health track", "bg", "bar background" },
        [229] = { "range fade", "dispel overlay", "debuff overlay" },
        [230] = {
        "debuff stripe opacity", "debuff stripe alpha", "offline opacity", "offline alpha", "offline member opacity",
        "corner indicator opacity", "corner indicator alpha", "corner dot opacity", "corner dot alpha",
        "text opacity", "text alpha", "absorb bar opacity", "absorb bar alpha", "heal absorb opacity", "heal absorb alpha",
        "heal absorb bar opacity", "heal absorb bar alpha",
    },
        [231] = { "more transparent", "more transparency", "more see through", "transparenter" },
        [232] = { "less transparent", "less transparency", "more opaque", "opaquer" },
        [233] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar" },
        [234] = { "keep text visible", "keep names visible", "text visible", "names visible" },
        [235] = {
        "range fade", "range fading", "out of range", "outside range",
        "when out of range", "while out of range",
    },
        [236] = {
        "alpha", "opacity", "transparency", "transparent", "out of range alpha",
        "out of range opacity", "range fade alpha", "range fade opacity",
        "more visible", "less visible", "more faded", "less faded",
    },
        [237] = {
        "affects", "layer", "mode", "health only", "current health only", "hp only",
        "frame only", "whole frame", "to frame", "to health",
    },
        [238] = { "more transparent", "more transparency", "less visible", "fade more", "more faded", "stronger fade" },
        [239] = { "less transparent", "less transparency", "more visible", "more opaque", "fade less", "less faded", "weaker fade" },
        [240] = {
            "transparent when out of range", "transparent out of range",
            "fade when out of range", "fade out of range", "fade outside range",
            "range fade", "range fading",
        },
        [241] = { "health only", "current health only", "hp only", "to health" },
        [242] = { "frame only", "whole frame", "to frame" },
        [243] = {
        "health color scheme", "health color mode",
        "health bar color scheme", "health bar color mode",
        "unitframe color scheme", "unit frame color scheme",
    },
        [244] = { "party", "raid", "mythic raid", "mythicraid", "group frame", "group frames" },
        [245] = { "anchor to", "anchor target", "anchor frame" },
        [246] = {
        "anchor point", "frame anchor point", "anchor position", "custom anchor",
        "custom anchor frame", "anchor frame name", "clear custom anchor",
        "remove custom anchor", "reset custom anchor", "picker",
    },
        [247] = {
        "class power", "class resource", "detached power", "detached mana", "castbar", "cast bar",
        "name text", "health text", "hp text", "power text", "mana text", "status", "indicator", "icon",
        "aura", "auras", "buff", "debuff", "group frame", "group frames", "party", "raid", "mythic raid",
    },
        [248] = { "anchor point", "frame anchor point", "anchor position" },
        [249] = {
        "custom anchor", "custom anchor frame", "anchor frame name", "anchor to", "anchor target",
        "class power", "class resource", "detached power", "detached mana", "castbar", "cast bar",
        "name text", "health text", "hp text", "power text", "mana text", "status", "indicator", "icon",
        "level", "pvp", "pvp flag", "aura", "auras", "buff", "debuff", "group frame", "group frames",
        "party", "raid", "mythic raid",
    },
        [250] = {
        "power bar border thickness", "power bar border size",
        "power border thickness", "power border size",
        "mana bar border thickness", "mana bar border size",
    },
        [251] = {
        "detached", "detached power", "detached power bar", "class power", "class resource",
        "aura", "auras", "buff", "debuff", "text", "font", "castbar", "cast bar",
        "health bar", "hp bar", "portrait", "group frame", "group frames", "party", "raid", "mythic raid",
    },
        [252] = { "power bar", "mana bar", "powerbar", "mana bar", "power balken", "mana balken" },
        [253] = {
        "class power", "class resource", "class resources", "power text", "mana text", "resource text",
        "text on", "sync", "anchor", "width", "height", "x offset", "y offset", "offset x", "offset y",
        "frame level", "layer", "shape", "orb", "border thickness", "border size", "smooth",
        "aura", "auras", "buff", "debuff", "castbar", "cast bar", "group frame", "group frames",
        "party", "raid", "mythic raid",
    },
        [254] = { "border", "outline", "rand" },
        [255] = { "embed", "embedded", "into health", "into hp", "inside health", "inside hp", "within health", "within hp" },
        [256] = { "detach", "detached", "undock", "undocked", "separate", "separated", "abkoppeln" },
        [257] = { "left", "right", "up", "down", "links", "rechts", "oben", "unten", "x", "y", "position", "pos", "move", "nudge", "shift" },
        [258] = { "attach", "attached", "reattach", "dock", "docked", "back to frame", "into frame", "ankoppeln" },
        [259] = {
        "player power shape", "player power bar shape",
        "detached power shape", "detached power bar shape",
        "class resources player power shape", "class resources player power bar shape",
        "class resource player power shape", "class power player power shape",
    },
        [260] = {
        "texture", "foreground", "background", "outline", "border", "color", "colour",
        "text", "font", "width", "height", "x", "y", "offset", "layer",
    },
        [261] = {
        "health", "hp", "player hp", "second hp", "duplicate hp", "health orb",
        "hp orb", "player health", "class resource health", "class resources hp",
    },
        [262] = {
        "mana orb size", "power orb size", "detached power orb size", "detached power bar orb size",
        "player power orb size", "player power bar orb size", "mana ball size", "power ball size",
        "class resources player power orb size", "class resources player power bar orb size",
        "class resource player power orb size", "class power player power orb size",
    },
        [263] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar" },
        [264] = { "affects", "layer", "mode", "health only", "current health only" },
        [265] = { "keep text visible", "keep names visible", "text visible", "names visible" },
        [266] = {
        "range fade", "range fading", "out of range", "outside range",
        "when out of range", "while out of range",
    },
        [267] = {
        "alpha", "opacity", "transparency", "transparent", "out of range alpha",
        "out of range opacity", "range fade alpha", "range fade opacity",
        "more visible", "less visible", "more faded", "less faded",
    },
        [268] = { "more transparent", "more transparency", "less visible", "fade more", "more faded", "stronger fade" },
        [269] = { "less transparent", "less transparency", "more visible", "more opaque", "fade less", "less faded", "weaker fade" },
        [270] = {
            "transparent when out of range", "transparent out of range",
            "fade when out of range", "fade out of range", "fade outside range",
            "range fade", "range fading",
        },
        [271] = { "group frames", "group frame", "gruppenframes", "groups" },
        [272] = { "party", "party frame", "party frames", "partyframe" },
        [273] = { "mythic raid", "mythicraid", "mythic raid frame", "mythic raid frames", "mythicraidframe" },
        [274] = { "raid", "raid frame", "raid frames", "raidframe" },
        [275] = { "mythic raid", "mythicraid", "mythicraidframe" },
        [276] = {
        "class color", "class colors", "class colored", "class mode", "use class color",
        "use class colors", "use class colour", "use class colours", "colored by class",
        "coloured by class", "by class", "class colored bars", "class color bars",
    },
        [277] = { "gradient", "health gradient" },
        [278] = { "custom", "manual" },
        [279] = { "dark mode", "dark bars", "dark" },
        [280] = { "unified", "unified color", "unified bars" },
        [281] = {
        "global", "global style", "global color", "global colors", "global colour", "global colours",
        "inherit", "inherit color", "inherit colors", "default", "default color", "default colors",
    },
        [282] = {
        "group frames", "group frame", "gruppenframes", "party", "party frame", "party frames", "partyframe",
        "raid", "raid frame", "raid frames", "raidframe", "mythic raid", "mythicraid",
    },
        [283] = {
        "bar color mode", "health bar color mode", "class color mode", "health color mode",
        "group bar style", "bar mode", "class colored health", "class color health",
        "use class color", "use class colors", "use class colour", "use class colours",
        "class colored", "class colors", "colored by class", "coloured by class",
        "use global color", "use global colors", "use default color", "use default colors",
        "global colors", "default colors", "inherit colors",
    },
        [284] = {
        "full-health absorb stripe", "full health absorb stripe", "full hp absorb stripe",
        "absorb stripe at full health", "absorb stripe on full health",
    },
        -- Outline layer. Must be probed before the thickness phrases in
        -- [160]: every phrase here also contains a bare "bar outline"/"outline"
        -- substring, so a thickness-first probe would swallow all of them.
        [285] = {
        "bar outline strata", "bar outline layer", "bar outline draw layer",
        "frame outline strata", "frame outline layer", "frame outline draw layer",
        "bar border strata", "bar border layer", "frame border strata", "frame border layer",
        "outline strata", "outline layer", "outline draw layer",
        "border strata", "border layer", "border draw layer",
    },
        -- Portrait shape value: the stock Blizzard ring dressing. Bare
        -- "blizzard" is safe here because it is only probed inside the shape
        -- branch opened by [17].
        [286] = { "blizzard", "blizzard ring", "gold ring", "goldring", "blizzard-ring" },
        -- "highlight border(s)" as a whole: on the Bars page that name covers
        -- the Aggro, Dispel and Purge borders together (plus Boss Target on the
        -- shared control). Each one already answers to its own name; the
        -- umbrella phrase had no owner at all, so "turn off highlight borders
        -- for party frame" dead-ended -- and before that it disabled the party
        -- frames outright.
        [287] = {
        "highlight border", "highlight borders", "highlight outline", "highlight outlines",
        "hervorhebungsrahmen", "highlight rahmen",
    },
    },
}
