-- Assistant auras parser data.
-- Generated phrase lists for MSUF_AssistantParser_Auras.lua.
local addonName, MSUF = ...
MSUF = MSUF or _G.MSUF_NS or {}

local M = MSUF.MSUF2 or _G.MSUF2 or {}
MSUF.MSUF2 = M

local A = MSUF.Assistant or {}
MSUF.Assistant = A
M.Assistant = A

local Data = A.ParserData or {}
A.ParserData = Data

Data.AURAS_PARSER = {
    PHRASES = {
        [1] = { "shared", "global", "all auras", "all aura" },
        [2] = {
        "group aura", "group auras", "group aura icon", "group aura icons",
        "group buff", "group buffs", "group buff icon", "group buff icons",
        "group debuff", "group debuffs", "group debuff icon", "group debuff icons",
        "group frame aura", "group frame auras", "group frame buff", "group frame buffs",
        "group frame debuff", "group frame debuffs",
        "gruppen aura", "gruppen auren", "gruppen buff", "gruppen buffs",
        "gruppen debuff", "gruppen debuffs", "gruppenframe aura", "gruppenframe auren",
    },
        [3] = {
        "party", "party frame", "party frames", "party aura", "party auras",
        "party buff", "party buffs", "party debuff", "party debuffs",
        "raid", "raid frame", "raid frames", "raid aura", "raid auras",
        "raid buff", "raid buffs", "raid debuff", "raid debuffs",
        "mythic", "mythic raid", "mythicraid", "mythic raid aura", "mythic raid auras",
        "all group", "all group aura", "all group auras", "all group buffs", "all group debuffs",
        "alle gruppen aura", "alle gruppen auren", "alle gruppen buffs", "alle gruppen debuffs",
        "every group aura", "every group buff", "every group debuff",
    },
        [4] = { "buff", "buffs" },
        [5] = { "debuff", "debuffs" },
        [6] = { "aura", "auras", "auren", "aura icon", "aura icons", "aura symbole", "auren symbole" },
        [7] = { "x offset", "offset x", "horizontal offset", "left", "right", "links", "rechts" },
        [8] = { "y offset", "offset y", "vertical offset", "up", "down", "oben", "unten", "hoch", "runter" },
        [9] = { "cooldown anchor", "timer anchor", "cooldown text anchor", "timer text anchor" },
        [10] = { "filter token", "filter type", "inclusive filter" },
        [11] = { "filter" },
        [12] = { "exclusive", "category", "blacklist" },
        [13] = { "growth direction", "growth", "grow direction" },
        [14] = { "grow", "grows" },
        [15] = { "anchor", "anchor point", "position anchor", "bottom left", "bottom right", "top left", "top right", "bottomleft", "bottomright", "topleft", "topright" },
        [16] = { "icon size", "icons size", "size", "bigger", "larger", "smaller", "shrink", "groesse", "grosse" },
        [17] = {
        "max", "maximum", "max icons", "maximum icons", "max count", "maximum count",
        "icon count", "aura count", "buff count", "debuff count", "count",
        "cap", "caps", "capped", "aura cap", "buff cap", "debuff cap",
        "limit", "limits", "limited", "icon limit", "aura limit", "buff limit", "debuff limit",
    },
        [18] = { "per row", "icons per row", "wrap count", "row count" },
        [19] = { "spacing", "gap", "icon gap" },
        [20] = { "layer", "z", "z layer", "z level", "z-level", "z order", "z-order", "z index", "z-index", "draw layer", "frame level", "strata", "frame strata" },
        [21] = { "move", "nudge", "shift", "offset", "left", "right", "up", "down", "verschiebe", "links", "rechts", "oben", "unten" },
        [22] = { "bigger", "larger", "grow", "increase", "raise", "more", "groesser", "mehr" },
        [23] = { "smaller", "shrink", "decrease", "lower", "less", "kleiner", "weniger" },
        [24] = { "aura", "auras", "auren", "buff", "buffs", "debuff", "debuffs" },
        [25] = { "copy", "preset", "blacklist", "category" },
        [26] = {
        "shared", "shared aura", "shared auras", "global", "all aura", "all auras",
        "player aura", "player auras", "player buff", "player buffs", "player debuff", "player debuffs",
        "target aura", "target auras", "target buff", "target buffs", "target debuff", "target debuffs",
        "focus aura", "focus auras", "focus buff", "focus buffs", "focus debuff", "focus debuffs",
        "pet aura", "pet auras", "pet buff", "pet buffs", "pet debuff", "pet debuffs",
        "boss aura", "boss auras", "boss buff", "boss buffs", "boss debuff", "boss debuffs",
    },
        [27] = { "party", "party frame", "party frames", "raid", "raid frame", "raid frames", "mythic raid", "group frame", "group frames" },
        [28] = { "cooldown anchor", "timer anchor", "filter token", "filter type", "inclusive filter" },
        [29] = { "filter" },
        [30] = { "exclusive", "category", "blacklist" },
        [31] = { "filter" },
        [32] = { "stack size", "stack text size", "stack font", "cooldown size", "cooldown text size", "cooldown font", "timer size", "timer text size", "timer font" },
        [33] = { "icon size", "icons size" },
        [34] = { "stack", "stacks", "stack count", "cooldown text", "timer text", "cooldown", "timer" },
        [35] = { "text", "font", "anchor", "x offset", "offset x", "y offset", "offset y", "text x", "text y" },
        [36] = { "shared", "global", "all auras", "shared auras" },
        [37] = { "player aura", "player auras", "spieler aura", "spieler auren" },
        [38] = { "target aura", "target auras", "ziel aura", "ziel auren" },
        [39] = { "focus aura", "focus auras", "fokus aura", "fokus auren" },
        [40] = { "boss aura", "boss auras", "boss1 aura", "boss1 auras", "boss 1 aura", "boss 1 auras" },
        [41] = { "party aura", "party auras", "party frame aura", "party frame auras", "group aura", "group auras", "gruppen aura", "gruppen auren" },
        [42] = { "raid aura", "raid auras", "raid frame aura", "raid frame auras", "mythic raid aura", "mythic raid auras", "schlachtzug aura", "schlachtzug auren" },
        [43] = { "shared", "global", "shared aura", "shared auras" },
        [44] = { "symbol", "with symbol", "with icon", "border symbol", "border and symbol", "border plus symbol" },
        [45] = { "off", "none", "disabled", "hide", "hidden", "turn off" },
        [46] = { "border only", "just border", "outline", "outline only" },
        [47] = { "debuff", "debuffs" },
        [48] = { "buff", "buffs" },
        [49] = { "filter", "filters" },
        [50] = { "good filter", "best filter", "which filter should", "what filter should", "recommend", "recommendation", "for raid", "for raids", "raid setup", "raiding", "new player", "beginner" },
        [51] = { "active", "current", "enabled", "what", "which", "explain", "check", "status", "do i have", "is on", "are on" },
        [52] = { "off", "disable", "disabled", "hide", "hidden", "without", "no ", "aus", "deaktivieren" },
        [53] = { "up", "oben", "hoch" },
        [54] = { "down", "unten", "runter" },
        [55] = { "left", "links" },
        [56] = { "right", "rechts" },
        [57] = { "shared", "global", "all unit auras", "unit auras", "unitframe auras" },
        [58] = { "stack", "stacks", "cooldown text", "timer text", "cooldown swipe", "timer swipe", "duration bar", "timer bar" },
        [59] = {
        "anchor", "x offset", "offset x", " y offset", "offset y", "text x", "text y",
        "size", "font", "height", "position", "edge", "fill mode", "direction", "reverse",
        "display", "display mode", "mode", "bar only", "separate bar", "icon bar",
        "icon and bar", "icon plus bar", "icon + bar", "overlay",
        "decimals", "decimal", "seconds", "threshold", "filter", "exclusive", "color", "colors", "colour", "colours",
    },
        [60] = { "debuff", "debuffs" },
        [61] = { "buff", "buffs" },
        [62] = {
        "stack size", "stack text size", "stack x", "stack y",
        "stack groesse", "stack grosse", "stack text groesse", "stack text grosse",
        "cooldown size", "cooldown text size", "timer size", "timer text size",
        "cooldown x", "cooldown y", "timer text x", "timer text y",
        "cooldown decimals", "cooldown decimal", "timer decimals", "timer decimal", "decimal seconds",
        "duration bar height", "timer bar height",
    },
        [63] = { "icon size", "icons size", "anchor", "position", "fill mode", "direction", "color", "colors", "colour", "colours", "filter", "exclusive" },
        [64] = { "debuff", "debuffs" },
        [65] = { "buff", "buffs" },
        [66] = { "stack anchor", "stack count anchor", "stack text anchor" },
        [67] = { "cooldown anchor", "cooldown text anchor", "timer anchor", "timer text anchor" },
        [68] = { "x offset", "offset x", " y offset", "offset y", "text x", "text y", "size", "font", "color", "colors", "colour", "colours" },
        [69] = { "debuff", "debuffs" },
        [70] = { "buff", "buffs" },
        [71] = { "show tooltip", "show tooltips", "tooltip", "tooltips", "aura tooltip", "aura tooltips" },
        [72] = { "group", "group aura", "party", "raid", "mythic", "native", "blizzard", "anchor", "position", "x offset", "offset x", "y offset", "offset y" },
        [73] = { "exclusive filter", "exclusive aura filter" },
        [74] = { "debuff", "debuffs" },
        [75] = { "buff", "buffs" },
        [76] = { "shared", "global", "shared aura", "shared auras" },
        [88] = { "party buff", "party buffs", "party debuff", "party debuffs", "raid buff", "raid buffs", "raid debuff", "raid debuffs", "mythic raid buff", "mythic raid buffs", "mythicraid buff", "mythicraid buffs", "mythic raid debuff", "mythic raid debuffs", "mythicraid debuff", "mythicraid debuffs" },
        [89] = {
        "filter", "filters", "only", "show only", "private", "native", "blizzard", "blacklist", "whitelist",
        "stack", "cooldown", "timer", "duration", "x offset", "offset x", " y offset", "offset y",
        " x ", "x ", " y ", "y ", "per row", "layer", "swipe", "direction", "dispel", "border", "mode",
        "size", "max", "count", "spacing", "growth", "anchor", "position", "color", "colors", "colour", "colours", "stripe",
    },
        [90] = { "debuff", "debuffs" },
        [91] = { "buff", "buffs" },
        [92] = {
        "aura", "auras", "buff", "buffs", "debuff", "debuffs", "sated", "exhaustion",
        "swipe darkens", "cooldown swipe darkens", "dispel type border", "dispel type borders", "debuff type border", "debuff type borders",
        "stack count", "show stack", "stack anchor", "stack size", "stack x", "stack y",
        "cooldown anchor", "timer anchor", "cooldown text", "timer text", "cooldown size", "timer size",
        "cooldown x", "cooldown y", "cooldown decimal", "cooldown decimals", "timer decimal", "timer decimals",
        "cooldown swipe", "timer swipe",
        "duration bar", "timer bar", "show tooltip", "tooltip",
        "exclusive filter",
        "shared filters", "global filters", "player filters", "target filters", "focus filters", "boss filters", "unit filters",
        "sort order",
    },
        [93] = { "aura blacklist spell", "hidden aura spell", "blacklist spell" },
        [94] = { "blacklist", "whitelist", "spell id", "spellid", "spell:" },
        [95] = { "aura blacklist preset", "blacklist preset", "hidden aura preset" },
        [96] = { "unit auras", "aura system", "auras system", "all unit auras", "unitframe auras" },
        [97] = { "aura editing scope", "editing aura scope", "aura scope", "edit aura scope" },
        [98] = { "aura style lane", "aura style tab", "aura buffs tab", "aura debuffs tab" },
        [99] = { "aura filter lane", "aura filter tab", "aura buff filters tab", "aura debuff filters tab" },
        [100] = { "aura settings view", "aura view", "aura settings mode", "basic aura settings", "advanced aura settings", "all aura settings" },
        [101] = { "aura blacklist preset", "blacklist preset", "hidden aura preset" },
        [102] = {},
        [103] = { "custom aura caps", "custom caps", "aura caps override", "aura limits override", "custom aura layout", "custom layout", "aura layout override", "custom aura ignore", "custom ignore", "aura ignore list override" },
        [104] = { "custom aura caps", "custom caps", "aura caps override", "aura limits override" },
        [105] = { "custom aura layout", "custom layout", "aura layout override" },
        [106] = { "custom aura ignore", "custom ignore", "aura ignore list override" },
        [107] = { "filters", "aura filters" },
        [108] = { "custom", "buff", "buffs", "debuff", "debuffs", "raid", "dispellable", "exclusive", "only", "player only", "nameplate", "crowd control" },
        [109] = { "filter", "filters" },
        [110] = {
            "buff", "buffs", "debuff", "debuffs", "raid", "dispellable", "purgeable",
            "crowd control", "cc debuff", "nameplate", "cancelable", "cancellable",
            "external defensive", "big defensive",
        },
        [111] = { "buff", "buffs", "debuff", "debuffs" },
        [112] = { " x", "x ", "x offset", "offset x", " y", "y ", "y offset", "offset y", "left", "right", "up", "down", "links", "rechts", "oben", "unten" },
        [113] = {
            "cooldown", "timer", "stack", "duration", "filter", "exclusive", "custom",
            "size", "max", "per row", "growth", "anchor", "spacing", "layer", "color", "colour",
        },
        [114] = { "debuff", "debuffs" },
        [115] = { "buff", "buffs" },
        [116] = { "x offset", "offset x", " x", "x ", "left", "right", "links", "rechts" },
        [117] = { "y offset", "offset y", " y", "y ", "up", "down", "oben", "unten" },
        [118] = { "move", "nudge", "shift", "verschiebe" },
        [119] = { "buff", "buffs", "debuff", "debuffs" },
        [120] = {
            "filter", "filters", "raid", "dispellable", "exclusive", "only", "custom",
            "cooldown", "stack", "duration", "timer", "x ", " y ", "offset", "size", "max",
            "per row", "growth", "anchor", "spacing", "layer", "swipe", "direction", "color", "colour",
            -- Naming a lane ATTRIBUTE is not a request to show or hide the lane.
            -- "turn on target debuff type borders" was answered by switching the
            -- whole Target debuff lane on, leaving Target Debuff Type Border
            -- untouched -- the player's actual subject.
            "border", "borders", "tooltip", "tooltips", "sort", "reverse",
            "opacity", "alpha", "transparency", "font", "zoom", "shape", "mask",
            "padding", "highlight", "glow",
        },
        [121] = { "debuff", "debuffs" },
        [122] = { "buff", "buffs" },
        [123] = { "aura filters", "auras filters", "aura filtering", "filter auras", "filter buffs", "filter debuffs" },
        [124] = { "custom", "player", "target", "focus", "boss", "party", "raid", "mythic" },
        [125] = { "shared filters", "global filters", "shared aura filters", "global aura filters" },
        [130] = { "color", "colors", "colour", "colours", "farbe", "farben" },
        [133] = { "show aura buffs", "show buffs", "aura buffs", "buff auras" },
        [134] = { "show aura debuffs", "show debuffs", "aura debuffs", "debuff auras" },
        [136] = { "aura edit preview", "edit mode auras", "preview auras in edit mode", "show auras in edit mode", "edit preview auras" },
        [137] = { "aura timer bucket colors", "aura timer color buckets", "aura cooldown bucket colors", "aura cooldown color buckets", "aura cooldown buckets", "aura timer buckets", "color aura timers by remaining time" },
        [140] = { "buff growth", "buff grow direction", "buff direction", "buff aura growth" },
        [141] = { "debuff growth", "debuff grow direction", "debuff direction", "debuff aura growth" },
        [142] = { "buff wrap rows", "buff row wrap", "buff wrap direction", "buff wrap" },
        [143] = { "debuff wrap rows", "debuff row wrap", "debuff wrap direction", "debuff wrap" },
        [144] = { "sort order", "aura sort order", "buff sort order", "debuff sort order" },
        [146] = { "aura cooldown safe seconds", "aura timer safe seconds", "aura safe seconds", "safe aura seconds", "safe aura timer threshold", "aura safe timer threshold" },
        [147] = { "aura cooldown warning seconds", "aura timer warning seconds", "aura warning seconds", "warning aura seconds", "warning aura timer threshold", "aura warning timer threshold" },
        [148] = { "aura cooldown urgent seconds", "aura timer urgent seconds", "aura urgent seconds", "urgent aura seconds", "urgent aura timer threshold", "aura urgent timer threshold" },
        [149] = { "aura cooldown safe color", "aura cooldown safe text color", "cooldown text safe color", "aura timer safe color", "aura safe timer color", "safe aura timer color" },
        [150] = { "aura cooldown warning color", "aura cooldown warning text color", "cooldown text warning color", "aura timer warning color", "aura warning timer color", "warning aura timer color" },
        [151] = { "aura cooldown urgent color", "aura cooldown urgent text color", "cooldown text urgent color", "aura timer urgent color", "aura urgent timer color", "urgent aura timer color" },
        [152] = { "shared", "global", "shared aura", "shared auras", "all unit auras" },
        [153] = {
        "player filter", "only my", "my buffs", "my debuffs", "player buffs only", "player debuffs only",
        "own buffs", "own debuffs",
    },
        [154] = { "buff", "buffs" },
        [155] = { "debuff", "debuffs" },
        [156] = { "corner", "corner indicator", "corner indicators", "corner custom", "custom corner" },
        [157] = { "dispel overlay", "unitframe dispel overlay", "unit frame dispel overlay", "debuff overlay", "dispellable overlay", "dispellable debuff overlay" },
        [158] = { "aura custom settings", "custom aura settings", "aura override", "aura overrides", "aura scope" },
        [159] = { "reset", "clear", "remove", "restore" },
        [160] = { "blacklist", "whitelist", "category", "spell id", "spellid", "spell:" },
        [161] = { "filter", "filters", "only", "show only", "just show", "display only" },
        [162] = {
        "show all", "show everything", "all buffs", "all debuffs", "all auras",
        "no filter", "clear filter", "clear filters", "remove filter", "remove filters",
        "filter off", "filters off", "normal filter", "default filter",
    },
        [163] = {
        "dispellable", "dispelable", "purgeable",
        "crowd control", "cc debuff", "cc debuffs",
        "raid buff", "raid buffs", "raid debuff", "raid debuffs",
        "raid in combat", "combat raid",
        "nameplate only", "nameplate-only", "include nameplate", "include nameplate-only",
        "external defensive", "external defensives", "big defensive", "big defensives", "major defensive", "major defensives",
        "cancelable buff", "cancelable buffs", "cancellable buff", "cancellable buffs",
        "not cancelable buff", "not cancelable buffs", "not cancellable buff", "not cancellable buffs",
        "non cancelable buff", "non cancelable buffs", "uncancelable buff", "uncancelable buffs",
    },
        [164] = { "native", "blizzard" },
        [165] = {
        "party", "raid", "mythic raid", "mythicraid",
        "group aura", "group auras", "group frame", "group frames",
    },
        [166] = {
        "aura", "auras", "buff", "buffs", "debuff", "debuffs",
        "dispel", "dispels", "dispellable", "external", "externals",
    },
        [167] = {
        "all group auras", "all group aura", "all group buffs", "all group debuffs",
        "all group frames", "all groups", "every group aura", "every group buff", "every group debuff",
    },
        [168] = { "party", "party frame", "party frames", "party aura", "party auras", "party buff", "party buffs", "party debuff", "party debuffs" },
        [169] = { "mythic raid", "mythicraid", "mythic raid frame", "mythic raid frames", "mythic raid aura", "mythic raid auras", "mythic raid buff", "mythic raid buffs", "mythic raid debuff", "mythic raid debuffs" },
        [170] = { "raid frame", "raid frames", "raid aura", "raid auras" },
        [171] = { "raid buff", "raid buffs", "raid debuff", "raid debuffs" },
        [172] = { "raid", "raid frame", "raid frames", "raid aura", "raid auras", "raid buff", "raid buffs", "raid debuff", "raid debuffs" },
        [173] = { "group frame", "group frames", "group debuff", "group debuffs", "group buff", "group buffs" },
        [174] = { "buff", "buffs" },
        [175] = { "debuff", "debuffs" },
        [176] = { "debuff", "debuffs" },
        [177] = {
        "show all", "show everything", "all buffs", "all debuffs", "all auras",
        "no filter", "clear filter", "clear filters", "remove filter", "remove filters",
        "filter off", "filters off", "normal filter", "default filter",
    },
        [178] = { "clear", "remove", "reset", "default", "normal" },
        [179] = { "filter", "filters" },
        [180] = { "filter", "filters" },
        [181] = { "shared", "global", "shared aura", "shared auras", "all unit auras" },
        [182] = {
        "filter", "filters", "only", "show only", "just show", "display only",
        "no filter", "clear filter", "clear filters", "remove filter", "remove filters",
    },
        [183] = {
        "max", "maximum", "size", "bigger", "larger", "smaller", "icon", "icons",
        "per row", "spacing", "layer", "x", "y", "anchor", "growth",
        "cooldown", "timer", "stack", "duration", "swipe", "dispel type border", "debuff type border",
        "stripe", "debuff stripe",
        "turn on", "turn off", "enable", "disable",
    },
        [184] = { "aura filter lane", "aura filter tab", "aura filter type", "aura buff filters tab", "aura debuff filters tab" },
        [185] = { "aura filters", "auras filters", "aura filtering", "filter auras", "filter buffs", "filter debuffs" },
        [186] = {
            "player filter", "raid filter", "raid in combat", "nameplate", "cancelable", "not cancelable",
            "dispellable", "crowd control", "external defensive", "big defensive", "only", "show only",
        },
        [187] = { "shared", "global", "shared aura", "shared auras", "all unit auras" },
        [188] = { "party", "raid frame", "raid frames", "group frame", "group frames", "mythic raid" },
        [189] = {
        "show all", "show everything", "all buffs", "all debuffs", "all auras",
        "no filter", "clear filter", "clear filters", "remove filter", "remove filters",
        "filter off", "filters off", "normal filter", "default filter",
    },
        [190] = { "off", "disable", "disabled", "turn off", "remove", "clear", "without", "no ", "aus", "deaktivieren" },
        [191] = { "only", "show only", "just", "just show", "display only" },
        [192] = { "blacklist", "whitelist", "category", "spell id", "spellid", "spell:" },
        [193] = { "only", "show only", "just show", "display only", "clear filter", "clear filters", "remove filter", "remove filters", "show all", "show everything" },
        [194] = { "shared", "global", "shared aura", "shared auras", "all unit auras" },
        [195] = { "party", "raid frame", "raid frames", "group frame", "group frames", "mythic raid" },
        [196] = { "party", "raid frame", "raid frames", "group frame", "group frames", "mythic raid" },
        [197] = { "buff", "buffs" },
        [198] = { "debuff", "debuffs" },
        [199] = { "debuff", "debuffs" },
        [200] = { "raid in combat", "combat raid" },
        [201] = { "raid filter", "raid buff", "raid buffs", "raid debuff", "raid debuffs" },
        [202] = { "nameplate only", "nameplate-only", "include nameplate", "include nameplate-only" },
        [203] = { "dispellable", "dispelable", "purgeable" },
        [204] = { "crowd control", "cc debuff", "cc debuffs" },
        [205] = { "not cancelable", "not cancellable", "non cancelable", "uncancelable" },
        [206] = { "cancelable", "cancellable" },
        [207] = { "external defensive", "external defensives", "external buffs" },
        [208] = { "big defensive", "big defensives", "major defensive", "major defensives" },
        [209] = { "player filter", "only my", "my buffs", "my debuffs", "player buffs only", "player debuffs only", "own buffs", "own debuffs" },
        [210] = { "off", "disable", "disabled", "turn off", "remove", "without", "no ", "aus", "deaktivieren" },
        [211] = { "blacklist", "blocklist", "filter token", "live filter", "spell id", "spellid" },
        [212] = {
        "group aura", "group auras", "party aura", "party auras", "raid aura", "raid auras",
        "mythicraid aura", "mythic raid aura", "mythicraid auras", "mythic raid auras",
        "aura tooltip", "aura tooltips", "prefer player auras", "prefer my auras",
        "sort auras by duration", "aura duration sort",
        "dynamic aura scale", "dynamic icon scale", "native aura", "native auras",
        "native group aura", "native group auras", "blizzard aura", "blizzard auras",
    },
        [213] = { "prefer player auras", "prefer my auras" },
        [214] = { "dynamic aura scale", "dynamic icon scale" },
        [215] = { "aura tooltip", "aura tooltips" },
        [216] = { "sort auras by duration", "aura duration sort" },
        [217] = { "native group aura dispel border", "blizzard group aura dispel border", "native dispel border", "native dispellable border", "native aura debuff border" },
        [218] = { "native group aura buffs", "blizzard group aura buffs", "native buffs", "native aura buffs" },
        [219] = { "native group aura debuffs", "blizzard group aura debuffs", "native debuffs", "native aura debuffs" },
        [220] = { "native group aura dispels", "blizzard group aura dispels", "native dispel auras", "native dispels", "dispellable auras" },
        [221] = { "native group aura externals", "blizzard group aura externals", "native external auras", "native externals", "external auras" },
        [223] = { "all group auras", "all group aura", "group aura system", "group auras enabled", "native group auras", "native group aura" },
        [224] = { "all group", "all group auras", "every group", "group aura system", "group auras" },
        [225] = { "buff", "buffs" },
        [226] = { "debuff", "debuffs" },
        [227] = { "aura", "auras", "auren" },
        [228] = {
        "show", "enable", "enabled", "turn on", "on",
        "hide", "disable", "disabled", "turn off", "off",
        "anzeigen", "einblenden", "aktivieren", "an",
        "ausblenden", "verstecken", "deaktivieren", "aus",
    },
        [229] = { "size", "count", "max", "maximum", "cap", "limit", "spacing", "gap", "growth", "anchor", "position", "offset", "filter", "blacklist", "cooldown", "timer", "duration", "stack", "copy", "preset" },
        [230] = {
        "all group auras", "all group aura", "group aura system", "group auras enabled",
        "aura tooltip", "aura tooltips", "prefer player auras", "prefer my auras",
        "dynamic aura scale", "dynamic icon scale", "native group",
    },
        [231] = {
        "aura system", "group aura system", "native aura", "native auras", "native group aura", "native group auras",
        "blizzard aura", "blizzard auras", "blizzard group aura", "blizzard group auras",
    },
        [232] = { "group", "group frame", "group frames" },
        [233] = { "show", "enable", "enabled", "turn on", "on", "anzeigen", "einblenden", "aktivieren", "an" },
        [234] = { "hide", "disable", "disabled", "turn off", "off", "ausblenden", "verstecken", "deaktivieren", "aus" },
        [235] = { "both", "both lanes", "buffs and debuffs", "buff and debuff", "buffs debuffs" },
        [236] = { "all auras", "all aura", "all party auras", "all raid auras", "all mythic raid auras", "all group auras" },
        [237] = { "cooldown swipe direction", "timer swipe direction", "reverse cooldown swipe", "swipe direction" },
        [238] = { "swipe" },
        [239] = { "duration bar", "timer bar" },
        [240] = {
        "duration bar position", "timer bar position", "duration bar edge",
        "top", "upper", "on top", "at top", "top edge", "above",
        "bottom", "lower", "on bottom", "at bottom", "bottom edge", "below",
    },
        [241] = {
        "duration bar display", "timer bar display", "duration bar mode", "timer bar mode",
        "bar only", "separate bar", "icon bar", "icon and bar", "icon plus bar", "icon + bar", "overlay",
    },
        [242] = {
        "duration bar fill mode", "duration bar direction", "timer bar fill mode", "timer bar direction",
        "fill mode", "remaining", "elapsed", "count up", "count down", "countdown", "deplete", "depletion", "drain", "progress",
    },
        [243] = { "debuff type border", "dispel type border", "debuff border mode", "dispel border mode", "aura debuff border" },
        [244] = { "mode", "symbol", "with symbol", "with icon", "border symbol", "border only", "just border", "outline only", "to border", "as border", "use border", "to off", "as off", "use off" },
        [245] = { "what", "where", "why", "help", "explain", "how" },
        [246] = {
        "custom aura style", "use custom aura style", "aura style override", "custom aura visuals",
        "use shared style", "shared aura style", "inherit style", "follow shared style",
        "custom aura filters", "custom filters", "use custom aura filters", "use custom filters", "aura filter override", "aura filters override", "custom filter override",
        "use shared filters", "shared filters", "shared aura filters", "inherit filters", "follow shared filters",
        "use shared rules", "shared aura rules", "inherit rules", "follow shared rules",
    },
        [247] = { "custom aura style", "use custom aura style", "aura style override", "custom aura visuals" },
        [248] = { "use shared style", "shared aura style", "inherit style", "follow shared style" },
        [249] = { "custom aura filters", "custom filters", "use custom aura filters", "use custom filters", "aura filter override", "aura filters override", "custom filter override" },
        [250] = { "use shared filters", "shared filters", "shared aura filters", "inherit filters", "follow shared filters" },
        [251] = { "use shared rules", "shared aura rules", "inherit rules", "follow shared rules" },
        [252] = { "party", "party frames", "gruppe" },
        [253] = { "raid", "raid frames", "mythic raid", "mythicraid", "schlachtzug" },
        [254] = { "group frames", "gruppenframes", "all groups" },
        [255] = { "debuff", "debuffs" },
    },
}
