-- Assistant registry parser data.
-- Generated phrase lists for MSUF_AssistantParser_Registry.lua.
local addonName, MSUF = ...
MSUF = MSUF or _G.MSUF_NS or {}

local M = MSUF.MSUF2 or _G.MSUF2 or {}
MSUF.MSUF2 = M

local A = MSUF.Assistant or {}
MSUF.Assistant = A
M.Assistant = A

local Data = A.ParserData or {}
A.ParserData = Data

Data.REGISTRY_PARSER = {
    PHRASES = {
        [1] = { "boss target", "boss targets" },
        [2] = {
        "all", "all of", "for all", "every", "everyone", "everything", "each",
        "alle", "alles", "fuer alle", "jede", "jeder", "jedes", "jeweils",
    },
        [3] = { "filter", "filters" },
        [4] = { "aura", "auras", "buff", "buffs", "debuff", "debuffs" },
        [5] = { " icon", " icons" },
        [6] = { "buff icons", "debuff icons", "aura icons", "buff icon", "debuff icon", "aura icon" },
        [7] = {
        "not class resource", "not class resources", "not class power", "not class bar", "not resource bar",
        "no class resource", "no class resources", "no class power", "no class bar", "no resource bar",
        "dont class resource", "do not class resource",
        "nicht class resource", "nicht class power", "nicht klassenressource", "keine class resource",
        "kein class resource", "keine klassenressource", "nicht ressourcenleiste",
    },
        [8] = { "aura", "auras", "buff", "buffs", "debuff", "debuffs" },
        [9] = { "aura", "auras", "aura icon", "aura icons" },
        [10] = { "shared", "global", "all aura", "all auras", "all buffs", "all debuffs", "every aura", "every auras", "every buff", "every buffs", "every debuff", "every debuffs" },
        [11] = { "growth", "grow", "growth direction", "grow direction" },
        [12] = { "all buffs", "all debuffs", "all aura", "all auras" },
        [13] = { "filter", "filters" },
        [14] = { "shared", "global", "all auras", "all aura" },
        [15] = { "boss target", "boss targets" },
        [16] = { "castbar", "cast bar", "zauberleiste" },
        [17] = { "portrait", "portrait border" },
        [18] = { "shift", "umschalt", "umschalttaste", "shift taste" },
        [19] = { "ctrl", "control", "strg", "steuerung", "strg taste" },
        [20] = { "alt", "option", "alt taste" },
        [21] = { "castbar", "cast bar", "zauberleiste" },
        [22] = { "not show", "dont show", "do not show", "never show", "nicht anzeigen", "nicht zeigen", "nicht einblenden" },
        [23] = { "not show", "dont show", "do not show", "never show", "nicht anzeigen", "nicht zeigen", "nicht einblenden" },
        [24] = { "group frame", "group frames", "group when solo", "player in group when solo", "when solo", "while solo" },
        [25] = { "hide in group", "hide while in group", "hide when in group", "group load condition" },
        [26] = { "tint offline", "tint offline members", "also tint offline members", "dead background offline", "dead background offline members", "dead offline tint" },
        [27] = { "offline", "offline member", "offline members", "offline player", "offline players" },
        [28] = { "combat", "in combat" },
        [29] = { "hide", "hidden", "not show", "dont show", "do not show", "never show" },
        [30] = {
        "offline in combat", "offline members in combat", "offline players in combat",
        "hide offline in combat", "hide offline members in combat", "hide offline players in combat",
        "only hide offline in combat", "only hide offline members in combat", "only hide offline players in combat",
        "combat offline hide", "offline im kampf",
    },
        [31] = { "offline members", "offline member", "offline players", "hide offline members", "offline spieler" },
        [32] = { "client scene", "client scenes", "hide during client scene", "hide in client scene", "client szene" },
        [33] = { "housing", "house", "in housing", "while in housing", "when in housing", "player housing", "haus", "spielerhaus" },
        [34] = {
        "player in group", "player in group frames", "show player in group",
        "show player in group frames", "show player when solo", "show player in group when solo",
        "hide player in group", "hide player in group frames", "player when solo",
        "spieler in gruppe", "spieler anzeigen",
    },
        [35] = {
        "show while solo", "show solo", "solo mode", "show group while solo",
        "show party frames while solo", "show raid frames while solo", "show mythic raid frames while solo",
        "show party frame while solo", "show raid frame while solo", "show mythic raid frame while solo",
        "show party frame when solo", "show raid frame when solo", "show mythic raid frame when solo",
        "show group frame while solo", "show group frame when solo",
        "show group frames while solo", "group while solo", "group frames while solo",
        "group frame while solo", "group frame when solo",
        "hide while solo", "hide solo", "not show while solo", "dont show while solo", "do not show while solo",
        "hide party frames while solo", "hide raid frames while solo", "hide mythic raid frames while solo",
        "hide party frame while solo", "hide raid frame while solo", "hide mythic raid frame while solo",
        "hide party frame when solo", "hide raid frame when solo", "hide mythic raid frame when solo",
        "hide group frame while solo", "hide group frame when solo",
        "solo anzeigen", "solo modus",
    },
        [36] = {
        "use msuf group frames", "msuf group frames", "group frames enabled",
        "party frames enabled", "raid frames enabled", "enable group frames",
        "disable group frames", "turn on group frames", "turn off group frames",
        "enable party frames", "disable party frames", "turn on party frames", "turn off party frames",
        "enable party frame", "disable party frame", "turn on party frame", "turn off party frame",
        "enable raid frames", "disable raid frames", "turn on raid frames", "turn off raid frames",
        "enable raid frame", "disable raid frame", "turn on raid frame", "turn off raid frame",
        "enable mythic raid frames", "disable mythic raid frames", "turn on mythic raid frames", "turn off mythic raid frames",
        "enable mythicraid frames", "disable mythicraid frames", "turn on mythicraid frames", "turn off mythicraid frames",
        "party frames from off to on", "party frames from on to off", "party frames off to on", "party frames on to off",
        "party frame from off to on", "party frame from on to off", "party frame off to on", "party frame on to off",
        "raid frames from off to on", "raid frames from on to off", "raid frames off to on", "raid frames on to off",
        "raid frame from off to on", "raid frame from on to off", "raid frame off to on", "raid frame on to off",
        "mythic raid frames from off to on", "mythic raid frames from on to off",
        "mythicraid frames from off to on", "mythicraid frames from on to off",
    },
        [37] = {
        "preview", "power bar", "name", "text", "status icon", "indicator",
        "scaling", "scale", "raid marker", "marker", "role icon", "ready check",
        "summon", "resurrection", "phase", "pvp", "war mode", "icon",
    },
        [38] = { "bigger", "larger", "smaller", "shrink", "groesser", "kleiner" },
        [39] = {
        "size", "icon size", "text size", "font size", "spacing", "gap", "offset", "x offset", "y offset",
        "x ", " y ", "layer", "per row", "icons per row", "max", "count", "stack", "cooldown", "timer",
    },
        [40] = { "on", "off", "enable", "disable", "show", "hide", "remove", "without", "no ", "with ", "an", "aus", "aktivieren", "deaktivieren" },
        [41] = { "what", "where", "why", "help", "explain", "how" },
        [42] = {
        "use custom", "custom aura", "custom style", "custom filters", "custom rules",
        "custom layout", "custom caps", "override", "own aura", "own filters",
    },
        [43] = {
        "use shared", "shared aura", "shared style", "shared filters", "shared rules",
        "inherit", "inherited", "follow shared", "use defaults", "default aura",
    },
        [44] = { "toggle", "switch", "flip", "invert", "umschalten", "wechseln" },
        [45] = { "attach", "attached", "reattach", "dock", "docked", "anchor to frame", "back to frame", "into frame", "ankoppeln" },
        [46] = { "detach", "detached", "undock", "undocked", "separate", "separated", "abkoppeln" },
        [47] = { "turn off", "disable", "disabled", "off", "false", "no" },
        [48] = { "fully hide", "hard hide", "hard kill", "enable", "enabled", "turn on", "on", "true", "yes" },
        [49] = { "hide", "hidden", "disable", "disabled", "turn off", "off", "false", "no" },
        [50] = { "show", "visible", "enable", "enabled", "turn on", "on", "true", "yes" },
        -- Polarity for settings whose own NAME contains "hide" (Hide Out of
        -- Combat, Hide Mounted...). [52] deliberately treats "hide" as ON, but
        -- the setting's own label puts that word in the request, so any verb
        -- missing from [51] loses to it: "deactivate Boss Hide Out of Combat"
        -- matched nothing here, fell through to "hide", and switched the
        -- setting ON. [51] is tested first, so it must carry every negation
        -- verb the parser accepts elsewhere.
        [51] = { "turn off", "turned off", "disable", "disabled", "deactivate", "deactivated",
            "switch off", "switched off", "shut off", "toggle off",
            "off", "false", "no", "dont hide", "do not hide", "never hide", "always show", "show" },
        [52] = { "hide", "enable", "enabled", "activate", "activated", "turn on", "turned on",
            "switch on", "switched on", "toggle on", "on", "true", "yes" },
        [53] = { "font", "fonts", "schrift", "schriftart" },
        [54] = { "what", "which", "where", "why", "help", "explain", "how", "current", "active", "show me" },
        [55] = {
        "font color", "font colour", "font palette", "text color", "text colour", "custom font color",
        "font size", "text size", "font scale", "outline", "shadow", "shorten", "shortening", "truncate",
        "rendering", "font rendering", "monochrome", "anti alias", "anti-alias", "antialias",
        "font smoothing", "text smoothing", "smooth font", "smooth text",
        "name font", "name text", "health font", "health text", "hp font", "hp text",
        "power font", "power text", "castbar", "cast bar", "spell name", "timer font", "time font",
        "aura", "auras", "buff", "buffs", "debuff", "debuffs", "cooldown", "stack",
        "combat timer", "combat text", "anchor", "offset",
        "x position", "y position", "line 1", "line 2", "slot 1", "slot 2", "override",
    },
        [56] = {
        "set font", "change font", "make font", "use font", "choose font", "switch font",
        "set global font", "change global font", "set main font", "change main font",
        "set default font", "change default font", "set shared font", "change shared font",
        "set all fonts", "change all fonts", "make all fonts", "use all fonts",
        "set every font", "change every font", "all fonts to", "all font to", "every font to",
        "schriftart", "schrift setzen", "schrift aendern", "schrift andern",
    },
        [57] = { "monochrome", "mono", "sharp", "crisp", "pixel", "pixel sharp", "pixelscharf" },
        [58] = { "smooth", "smoothing", "soft", "normal" },
        [59] = { "font", "fonts", "text", "schrift" },
        [60] = { "what", "which", "where", "why", "help", "explain", "how", "current", "active", "show me" },
        [61] = {
        "font rendering", "text rendering", "font smoothing", "text smoothing",
        "sharp text", "sharp font", "pixel font", "monochrome font", "font monochrome",
        "slug rendering", "slug font", "font slug",
        "global font rendering", "shared font rendering", "default font rendering",
    },
        [62] = { "text opacity", "text alpha", "font opacity", "font alpha" },
        [63] = { "what", "which", "where", "why", "help", "explain", "how", "current", "active", "show me" },
        [64] = {
        "aura", "auras", "buff", "buffs", "debuff", "debuffs", "castbar", "cast bar",
        "combat", "edit mode", "editmode", "background", "bar opacity", "bar alpha",
        "outline", "border", "shadow opacity", "shadow alpha",
    },
        [65] = { "white", "weiss" },
        [66] = {
        "everything", "all text", "all texts", "all font", "all fonts", "all names",
        "all unitframe text", "all unit frame text", "all msuf text", "make everything",
        "color everything", "colour everything", "text white", "font white",
    },
        [67] = {
        "bar", "bars", "castbar", "cast bar", "border", "outline", "background",
        "aura", "auras", "buff", "debuff", "class resource", "class resources",
        "class power", "resource bar",
    },
        [68] = { "default", "font color", "palette", "standard" },
        [69] = {
            "class", "class color", "class colour", "by class", "class colored", "class coloured",
        },
        [70] = {
            "health", "hp", "by health", "health color", "health colour", "health gradient",
        },
        [71] = {
            "resource", "power", "power type", "by power", "by power type",
            "energy", "mana", "rage", "focus", "runic power", "insanity", "fury", "pain",
            "essence", "astral power", "lunar power", "maelstrom",
        },
        [72] = {
            "npc", "red", "class", "class color", "class colour", "by class", "npc red",
        },
        [73] = { "default", "font color", "palette", "standard" },
        [74] = {
            "not by class", "not class color", "not class colored", "not colored by class",
            "without class color", "without class", "no class color", "no class colours",
            "dont color name by class", "do not color name by class",
            "dont use class color", "do not use class color", "disable class color names",
            "turn off class color names", "turn off name class color",
        },
        [75] = {
            "not by health", "not health color", "without health color", "no health color",
            "dont color by health", "do not color by health", "disable health color",
        },
        [76] = {
            "not by power", "not by resource", "not power color", "not resource color",
            "without power color", "without resource color", "no power color", "no resource color",
            "dont color by power", "do not color by power", "disable power color",
        },
        [77] = {
            "not red", "not npc red", "without npc red", "without red", "no npc red",
            "dont make npc red", "do not make npc red",
            "no npc color", "no npc name color", "without npc color", "disable npc color",
            "turn off npc color", "no npc class color", "disable npc class color",
        },
        [78] = { "castbar", "cast bar", "zauberleiste" },
        [79] = {
        "class resource color", "class resource colors", "class resource colour", "class resource colours",
        "class power color", "class power colors", "class power colour", "class power colours",
        "resource text class resource color", "resource text class resource colour",
    },
        [80] = {
        "color text by power", "text color by power", "color text by resource", "text color by resource",
        "color text by mana", "text color by mana", "color power text", "power color text",
        "mana color text", "resource color text", "power text color", "mana text color",
        "resource text color", "power text by type", "power text by power",
        "powertext color", "powertext colour", "color of power text", "colour of power text",
        "color of powertext", "colour of powertext",
    },
        [81] = {
            "power text", "powertext", "mana text", "resource text", "power value", "mana value", "resource value",
        },
        [82] = {
            "power color", "power colour", "power colors", "power colours",
            "resource color", "resource colour", "mana color", "mana colour",
            "font color",
        },
        [83] = {
            "power text", "powertext", "mana text", "resource text", "power value", "mana value", "resource value",
        },
        [84] = {
            "default", "standard",
        },
        [85] = {
            "show", "hide", "enable", "disable", "turn on", "turn off",
            "size", "font size", "text size", "x offset", "y offset", "offset",
            " x", "x ", " y", "y ", "delimiter", "separator", "format",
            "anchor", "position", "format", "template", "custom text", "layer",
        },
        [86] = {
        "color text by health", "text color by health", "color health text", "health color text",
        "hp color text", "health text color", "hp text color", "health text by health",
    },
        [87] = {
        "npc name color", "npc text color", "npc name red", "npc red name",
        "npc name class color", "npc class color name", "color npc name by class",
        "npc name by class", "npc class colored name",
    },
        [88] = {
            "class color", "class colour", "by class", "class colored", "class coloured",
        },
        [89] = {
        "name text color", "name color", "color name by class", "color name text by class",
        "color name not by class", "name text by class", "name text not by class",
        "name not by class", "names not by class", "unit name not by class",
        "class color name text", "class colored name text", "not class color name",
    },
        [90] = { "only", "nur", "just" },
        [91] = {
        "text color", "text colour", "text colors", "text colours",
        "color text", "colour text", "font text color", "font text colour",
    },
        [92] = {
        "name text color", "name text colour", "name color", "name colour",
        "health text color", "health text colour", "hp text color", "hp text colour",
        "power text color", "power text colour", "powertext color", "powertext colour",
        "mana text color", "mana text colour", "resource text color", "resource text colour",
        "dead text", "status text", "offline text", "afk text", "dnd text",
    },
        [93] = {
        "castbar", "cast bar", "aura", "auras", "buff", "buffs", "debuff", "debuffs",
        "border", "outline", "background", "bar color", "bar colour",
        "combat", "timer", "enter text", "leave text", "stack count", "cooldown text",
        "pandemic", "crosshair", "kick", "interrupt", "cast color", "cast colour",
    },
        [94] = { "color", "colors", "colour", "colours", "tint", "farbe", "farben" },
        [95] = { "set", "change", "make", "turn", "use", "to " },
        [96] = {
        "player", "target", "focus", "pet", "boss", "party", "raid", "mythic raid", "mythicraid",
        "health", "hp", "power", "mana", "energy", "rage", "focus power", "class resource", "class power",
        "class color", "class colour", "warrior", "paladin", "hunter", "rogue", "priest", "death knight",
        "shaman", "mage", "warlock", "monk", "druid", "demon hunter", "evoker",
        "npc", "npc type", "friendly npc", "neutral npc", "enemy npc", "dead npc",
        "combo", "name", "text", "font", "bar", "bars", "castbar", "cast bar", "cast color", "cast colour",
        "interrupt", "kick", "mouseover", "combat", "timer", "enter text", "leave text",
        "crosshair", "pandemic", "stack count", "border", "outline",
        "background", "aura", "auras", "buff", "buffs", "debuff", "debuffs", "dispel", "aggro",
        "gradient", "raid marker", "role icon", "status icon",
    },
        [97] = {
        "interrupt ready", "kick ready", "ready interrupt", "ready kick",
        "interrupt bereit", "kick bereit", "unterbrechung bereit", "unterbrechen bereit",
    },
        [98] = { "interrupt", "kick", "unterbrechen", "unterbrechung" },
        [99] = {
            "ready indicator", "ready icon", "ready border", "ready box",
            "bereit anzeige", "bereit symbol", "bereit rand", "bereit box",
        },
        [100] = { "aura", "auras", "buff", "debuff" },
        [101] = { "color", "colors", "colour", "colours", "farbe", "farben", "tint" },
        [102] = { "auto size", "autosize", "automatic size", "automatic sizing", "auto-size", "automatische groesse", "automatisch groesse" },
        [103] = { "style", "border", "box", "fill", "outline", "square", "unavailable fill", "castbar fill", "stil", "rand", "kasten", "quadrat" },
        [104] = { "anchor", "anchor point", "anchor position", "position dropdown", "put", "place", "position", "anker", "ankerpunkt", "platzieren" },
        [105] = { "move", "nudge", "shift", "offset", "x offset", "y offset", "verschiebe", "verschieben", "versatz" },
        [106] = { "x offset", "horizontal offset", "offset x", "move left", "move right", "nudge left", "nudge right", "left by", "right by", "x versatz", "horizontaler versatz", "nach links", "nach rechts", "links um", "rechts um" },
        [107] = { "y offset", "vertical offset", "offset y", "move up", "move down", "nudge up", "nudge down", "up by", "down by", "y versatz", "vertikaler versatz", "nach oben", "nach unten", "hoch um", "runter um" },
        [108] = { "move", "nudge", "shift", "verschiebe", "verschieben" },
        [109] = { "move", "nudge", "shift", "verschiebe", "verschieben" },
        [110] = { "size", "scale", "groesse", "grosse", "bigger", "larger", "smaller", "grow", "shrink", "icon bigger", "icon smaller", "groesser", "kleiner", "symbol groesser", "symbol kleiner" },
        [111] = { "target", "target castbar", "target cast bar", "ziel", "ziel castbar", "ziel zauberleiste" },
        [112] = { "focus", "focus castbar", "focus cast bar", "fokus", "fokus castbar", "fokus zauberleiste" },
        [113] = { "boss", "bosses", "boss castbar", "boss castbars", "boss cast bar", "boss cast bars", "boss zauberleiste", "boss zauberleisten" },
        [114] = { "show", "enable", "enabled", "turn on", "on", "true", "yes", "anzeigen", "einblenden", "aktivieren", "an" },
        [115] = { "hide", "disable", "disabled", "turn off", "off", "false", "no", "ausblenden", "deaktivieren", "aus" },
        [116] = { "aura", "auras", "buff", "debuff" },
        [117] = {
        "focus kick", "focus interrupt tracker", "focus interrupt icon", "focus kick tracker", "focus kick icon",
        "fokus kick", "fokus interrupt tracker", "fokus interrupt symbol", "fokus kick tracker", "fokus kick symbol",
        "fokus kick anzeige", "fokus interrupt anzeige",
    },
        [118] = { "reset", "restore", "default", "defaults", "zuruecksetzen", "zurucksetzen", "standard" },
        [119] = { "move", "nudge", "shift", "offset", "position", "x", "y", "horizontal", "vertical", "verschiebe", "verschieben", "versatz", "platzierung" },
        [120] = { "x offset", "offset x", "horizontal", "x versatz", "horizontaler versatz" },
        [121] = { "y offset", "offset y", "vertical", "y versatz", "vertikaler versatz" },
        [122] = { "text size", "font size", "text bigger", "text smaller", "textgroesse", "schriftgroesse", "text groesser", "text kleiner", "schrift groesser", "schrift kleiner" },
        [123] = { "size", "scale", "bigger", "larger", "smaller", "grow", "shrink", "width", "height", "groesse", "grosse", "groesser", "kleiner", "breite", "hoehe" },
        [124] = { "width", "wide", "wider", "narrower", "breite", "breiter", "schmaler" },
        [125] = { "height", "tall", "taller", "shorter", "hoehe", "hoeher", "niedriger" },
        [126] = { "height", "tall", "taller", "shorter", "hoehe", "hoeher", "niedriger" },
        [127] = { "width", "wide", "wider", "narrower", "breite", "breiter", "schmaler" },
        [128] = { "show", "enable", "turn on", "on", "anzeigen", "einblenden", "aktivieren", "an" },
        [129] = { "hide", "disable", "turn off", "off", "ausblenden", "deaktivieren", "aus" },
        [130] = { "symbol", "icon" },
        [131] = { "role icon style", "indicator style", "icon design", "icon pack", "icon style", "midnight style", "classic style" },
        [132] = { "aura", "auras", "buff", "debuff" },
        [133] = { "default", "reset", "restore", "standard" },
        [134] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar" },
        [135] = { "health text decimals", "hp text decimals", "health decimals", "hp decimals", "decimal percent" },
        [136] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar" },
        [137] = { "power smooth fill", "power bar smooth fill", "smooth power bar", "smooth mana bar", "smooth resource bar" },
        [138] = { "reverse fill direction", "reverse health fill", "reverse bar fill" },
        [139] = { "smooth fill", "smooth health fill", "smooth frame fill" },
        [140] = {
        "layer down", "down layer", "move layer down", "drop layer",
        "behind", "backward", "backwards", "send back", "to back", "lower layer", "lower draw",
        "below", "back", "down", "hinter", "nach hinten", "runter",
    },
        [141] = {
        "layer up", "up layer", "move layer up", "raise layer",
        "forward", "front", "to front", "bring forward", "higher layer", "higher draw",
        "above", "up", "nach vorne", "hoch",
    },
        [142] = { "aura", "auras", "buff", "debuff" },
        [143] = {
        "level", "level indicator", "level text", "pvp flag", "pvp indicator", "pvp icon",
        "raid marker", "raid marker icon", "raid group", "raid group name", "raid group style",
        "raid group name style", "group number style",
        "combat indicator", "combat icon", "rested indicator", "rested icon", "resting indicator",
        "resting icon", "rested symbol", "resting symbol",
        "incoming rez", "incoming rez icon", "incoming resurrection", "incoming resurrection icon",
        "resurrection icon", "rez icon", "dead text", "dead indicator", "ghost indicator", "status text",
        "elite icon", "elite indicator", "rare icon", "rare indicator",
    },
        [144] = { "anchor", "position" },
        [145] = { "x offset", "offset x", "horizontal offset", "horizontal position" },
        [146] = { "y offset", "offset y", "vertical offset", "vertical position" },
        [147] = { "size", "icon size", "text size", "font size" },
        [148] = {
        "layer", "frame level", "framelevel", "draw layer",
        "layer up", "layer down", "bring forward", "send back",
        "front", "behind", "backward", "backwards", "above", "below",
    },
        [149] = { "raid group style", "raid group name style", "group number style" },
        [150] = { "show", "hide", "enable", "disable", "turn on", "turn off", "on", "off" },
        [151] = { "color", "colour", "test", "preview", "group", "party", "raid", "mythic raid" },
        [152] = { "boss target highlight", "boss target outline", "highlight boss target" },
        [153] = { "mythic raid", "mythicraid", "mythic raid frame", "mythicraid frame" },
        [154] = { "party", "party frame", "party frames" },
        [155] = { "raid", "raid frame", "raid frames" },
        [156] = { "group border color", "group border colour", "frame group border color", "frame group border colour" },
        [157] = { "aura", "auras", "buff", "debuff", "stripe", "dispel", "corner" },
        [158] = { "texture", "foreground texture", "background texture", "bar texture", "bar background texture", "bar bg texture" },
        [159] = { "castbar", "cast bar", "class resource", "class resources", "detached power", "player hp", "absorb", "heal absorb" },
        [160] = { "bar background texture", "background bar texture", "bar bg texture" },
        [161] = { "bar texture", "bars texture", "health bar texture", "power bar texture", "foreground bar texture" },
        [162] = { "background texture", "health background texture" },
        [163] = { "foreground texture" },
        [164] = { "dispel overlay", "unitframe dispel overlay", "unit frame dispel overlay", "debuff overlay", "dispellable overlay" },
        [165] = { "current health only", "current health", "on health only", "on current health", "on current health only" },
        [166] = { "opacity", "alpha", "style", "trigger", "detects", "color", "colour" },
        [167] = {
        "class resource", "class resources", "class power", "class powers",
        "combo point", "combo points", "holy power", "soul shard", "soul shards",
    },
        [168] = { "color", "colour", "font size", "text size", "move", "offset", "position", "anchor", "placement" },
        [169] = { "player hp smooth fill", "player health smooth fill", "hp bar smooth fill", "health bar smooth fill" },
        [170] = { "player hp bar", "player health bar", "hp bar", "health bar", "second hp", "duplicate hp" },
        [171] = { "class resource text", "class resources text", "class power text", "class powers text", "resource text", "resource numbers", "resource number" },
        [172] = { "class resource fill", "class resources fill", "class power fill", "class powers fill" },
        [173] = { "class power", "class resource", "class resources", "combo point", "combo points", "holy power", "soul shard", "soul shards" },
        [174] = { "power color", "power colour", "power colors", "power colours", "power bar color", "power bar colour" },
        [175] = { "aura filters", "auras filters", "aura filtering", "filter auras", "filter buffs", "filter debuffs" },
        [176] = {
        "player", "target", "focus", "boss", "party", "raid", "mythic raid",
        "buff player filter", "debuff player filter", "raid filter", "raid in combat",
        "nameplate", "cancelable", "not cancelable", "dispellable", "crowd control",
        "external defensive", "big defensive", "only", "show only",
    },
        [177] = { "aura", "auras", "buff", "debuff" },
        [178] = {
        "keep text portrait visible", "keep text and portrait visible", "keep text & portrait visible",
        "keep text visible", "keep portrait visible", "exclude text from opacity", "exclude portrait from opacity",
        "text portrait opacity", "text and portrait opacity", "text & portrait opacity",
        "keep names visible when transparent", "keep name visible when transparent",
        "names visible when transparent", "name visible when transparent",
        "keep text visible when transparent", "text visible when transparent",
        "keep names visible when faded", "keep name visible when faded",
        "names visible when faded", "name visible when faded",
        "keep text visible when faded", "text visible when faded",
    },
        [179] = { "group frame", "group frames", "all groups", "all group" },
        [180] = { "unitframe", "unit frame", "unitframes", "unit frames", "all units" },
        [181] = { "group", "groups", "group frame", "group frames" },
        [182] = { "castbar", "cast bar", "zauberleiste", "zauberleisten" },
        [183] = { "aura", "auras", "buff", "debuff" },
        [184] = { "blizzard", "msuf", "hide castbar", "hide cast bar", "hide zauberleiste", "verstecke zauberleiste", "zauberleiste ausblenden", "deaktiviere zauberleiste" },
        [185] = {
        "hide", "disable", "disabled", "turn off", "off",
        "ausblenden", "verstecken", "verstecke", "deaktivieren", "deaktiviere", "ausschalten", "aus",
    },
        [186] = {
        "hide", "hidden", "disable", "disabled", "turn off", "off",
        "ausblenden", "verstecken", "verstecke", "deaktivieren", "deaktiviere", "ausschalten", "aus",
    },
        [187] = { "blizzard", "msuf" },
        [188] = {
        "blizzard", "blizzard castbar", "blizzard cast bar", "blizzard zauberleiste",
        "wow castbar", "wow zauberleiste", "standard castbar", "standard zauberleiste",
    },
        [189] = {
        "msuf", "msuf castbar", "msuf cast bar", "msuf zauberleiste",
        "own castbar", "custom castbar", "eigene castbar", "eigene zauberleiste",
    },
        [190] = { "all castbars", "all cast bars", "alle castbar", "alle castbars", "alle zauberleisten" },
        [191] = { "castbar", "cast bar", "zauberleiste" },
        [192] = { "aura", "auras", "buff", "debuff" },
        [193] = {
        "alignment", "align", "text alignment", "text align",
        "spell name alignment", "spell text alignment", "castbar text alignment", "cast bar text alignment",
    },
        [194] = { "middle", "center", "centre", "mitte" },
        [195] = { "put", "place", "set", "position", "on the", "to the", "in the", "middle", "center", "centre", "mitte" },
        [196] = { "position", "position preset", "placement" },
        [197] = { "move", "nudge", "shift", "offset", "x offset", "y offset" },
        [198] = { "icon position", "spell icon position", "castbar icon position", "cast bar icon position" },
        [199] = { "icon", "spell icon" },
        [200] = { "spell name position", "spell text position", "castbar text position", "cast bar text position", "castbar name position" },
        [201] = { "spell name", "spell text", "castbar text", "cast bar text", "text", "name" },
        [202] = { "time position", "time text position", "timer position", "cast time position", "castbar time position", "cast bar time position" },
        [203] = { "time", "timer", "cast time" },
        [204] = { "middle", "center", "centre", "mitte" },
        [205] = { "aura", "auras", "buff", "debuff" },
        [206] = { "power bar gradient", "power gradient", "mana gradient" },
        [207] = { "group frame", "group frames", "all groups", "all group" },
        [208] = { "unitframe", "unit frame", "unitframes", "unit frames", "all units" },
        [209] = { "only", "just", "nur" },
        [210] = { "from right", "to right", "right side", "rightward", "right", "rechts", "von rechts", "nach rechts" },
        [211] = { "from left", "to left", "left side", "leftward", "left", "links", "von links", "nach links" },
        [212] = { "from top", "to top", "from up", "to up", "top", "up", "above", "oben", "hoch", "von oben", "nach oben" },
        [213] = { "from bottom", "to bottom", "from down", "to down", "bottom", "down", "below", "unten", "runter", "von unten", "nach unten" },
        [214] = { "aura", "auras", "buff", "buffs", "debuff", "debuffs" },
        [215] = {
        "gradient", "gradients", "bar gradient", "bar gradients", "bars gradient",
        "hp gradient", "health gradient", "power gradient", "mana gradient",
        "gradient direction", "gradient strength",
    },
        [216] = { "gradient strength", "strength", "intensity", "staerke", "starke" },
        [217] = { "power", "power bar", "power bars", "mana", "mana bar", "mana bars", "resource", "resource bar", "resource bars", "energie", "ressource" },
        [218] = { "hp", "health", "health bar", "health bars", "hp bar", "hp bars", "leben", "gesundheit" },
        [219] = {
        "both", "both bars", "all bars", "all bar gradients", "bar gradients", "gradients",
        "health and power", "hp and power", "power and health", "power and hp",
        "health plus power", "hp plus power", "health power",
    },
        [220] = {
        "unitframe", "unit frame", "unitframes", "unit frames", "all units", "all unitframes", "all unit frames",
        "player", "target", "focus", "pet", "boss", "targettarget", "target of target", "focustarget", "focus target",
    },
        [221] = {
        "group frame", "group frames", "all groups", "all group frames", "party", "raid", "mythic raid", "mythicraid",
    },
        [222] = { "all frames", "all bar scopes", "every frame" },
        [223] = { "only", "just", "nur" },
        [224] = {
        "all group frames", "all groups", "group frames", "party raid", "party and raid",
    },
        [225] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar" },
        [226] = { "role icon", "role indicator", "status icon", "status indicator", "symbol" },
        [227] = { "power", "mana", "resource", "resources", "power bar", "power bars", "mana bar", "mana bars", "resource bar", "resource bars" },
        [228] = { "tank", "tanks", "tank role", "tank players" },
        [229] = { "healer", "healers", "heal role", "healer role", "healer mana", "healer power" },
        [230] = { "dps", "damage dealer", "damage dealers", "damager", "damagers", "damage role" },
        [231] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar" },
        [232] = { "role icon", "role icons", "role indicator", "role indicators", "role symbol", "role symbols" },
        [233] = { "tank", "tanks", "tank role", "tank players" },
        [234] = { "healer", "healers", "heal role", "healer role" },
        [235] = { "dps", "damage dealer", "damage dealers", "damager", "damagers", "damage role" },
        [236] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar" },
        [237] = { "offline", "offline member", "offline members", "offline player", "offline players" },
        [238] = { "delay", "after", "seconds", "in combat", "hide offline in combat", "offline members in combat", "offline players in combat" },
        [239] = {
        "alpha", "opacity", "transparency", "transparent", "fade", "faded",
        "more visible", "less visible", "more transparent", "less transparent",
    },
        [240] = { "more transparent", "less visible", "fade more", "more faded", "stronger fade" },
        [241] = { "less transparent", "more visible", "fade less", "less faded", "weaker fade" },
        [242] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar" },
        [243] = {
        "health fade", "healthy fade", "healer health fade",
        "fade healthy", "fade healthy members", "fade healthy frames",
        "dim healthy", "dim healthy members", "dim healthy frames",
        "fade full health", "dim full health",
    },
        [244] = {
        "opacity", "alpha", "transparent", "transparency", "visibility",
        "dimmed opacity", "dimmed health opacity", "healthy opacity",
    },
        [245] = {
        "dim healthy", "dim healthy members", "dim healthy frames",
        "fade healthy", "fade healthy members", "fade healthy frames",
        "dim full health", "fade full health",
    },
        [246] = {
        "threshold", "percent", "health percent", "hp percent",
        "above health", "above health percent", "above hp", "above hp percent",
        "fade above", "dim above", "when above", "at health",
    },
        [247] = { "more transparent", "less visible", "fade more", "more faded", "stronger fade", "dim more" },
        [248] = { "less transparent", "more visible", "fade less", "less faded", "weaker fade", "dim less" },
        [249] = { "stop", "stop fading", "stop dimming", "do not dim", "dont dim", "don't dim", "never dim", "do not fade", "dont fade", "don't fade", "never fade" },
        [250] = { "dim", "fade", "health fade", "healthy fade" },
        [251] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar" },
        [252] = { "column", "columns", "per column", "spalte", "spalten" },
        [253] = { "party", "raid", "mythic raid", "mythicraid", "group frame", "group frames", "frames", "member", "members", "players" },
        [254] = {
        "per column", "members per column", "players per column", "frames per column", "units per column",
        "new column after", "column after", "columns after", "start new column after", "break column after",
        "break columns after", "after players", "after members",
    },
        [255] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar" },
        [256] = {
        "preserve raid groups", "keep raid groups", "keep raid groups together",
        "keep groups together", "preserve groups", "preserve group order",
    },
        [257] = { "do not", "dont", "don't", "disable", "turn off", "off", "false", "no", "stop" },
        [258] = { "aura", "auras", "buff", "debuff" },
        [259] = { "role", "role sorting", "sort by role", "sorting" },
        [260] = {
        "player first", "me first", "myself first", "put me first", "put myself first",
        "keep me first", "keep myself first", "me at top", "me at the top",
        "myself at top", "myself at the top", "put me at top", "put me at the top",
        "put myself at top", "put myself at the top", "keep me at top", "keep me at the top",
        "keep myself at top", "keep myself at the top",
    },
        [261] = { "do not", "dont", "don't", "disable", "turn off", "off", "false", "no" },
        [262] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar", "unitframe", "unit frame", "unitframes", "unit frames" },
        [263] = {
        "show", "hide", "force", "auto", "automatic", "fallback", "when disabled", "if off",
        "anzeigen", "einblenden", "ausblenden", "verstecken", "erzwingen", "automatisch",
        "wenn aus", "wenn deaktiviert", "wenn ausgeschaltet",
    },
        [264] = {
        "auto", "automatic", "automatically", "blizzard default", "blizzard decides",
        "normal behavior", "default behavior", "automatisch", "blizzard entscheidet",
        "standard verhalten", "normales verhalten",
    },
        [265] = {
        "hide all", "hide both", "hide blizzard", "hide default", "hide standard",
        "none", "no blizzard", "no default frames", "no standard frames",
        "alles ausblenden", "alle verstecken", "beide ausblenden", "blizzard ausblenden",
        "blizzard verstecken", "standardrahmen ausblenden", "standard rahmen ausblenden",
        "keine blizzard frames", "keine standardrahmen", "nichts anzeigen",
    },
        [266] = {
        "show blizzard", "show default", "show standard", "force blizzard",
        "restore blizzard", "use blizzard", "blizzard visible", "blizzard frames visible",
        "blizzard anzeigen", "blizzard einblenden", "standardrahmen anzeigen",
        "standard rahmen anzeigen", "standardframes anzeigen", "blizzard erzwingen",
        "blizzard sichtbar", "blizzard frames sichtbar",
    },
        [267] = { "show", "visible", "anzeigen", "einblenden", "sichtbar" },
        [268] = { "hide", "hidden", "off", "ausblenden", "verstecken", "aus" },
        [269] = { "non tank", "non tanks", "nontank", "nontanks", "not tank", "not tanks", "non-tank", "non-tanks" },
        [270] = { "healer", "healers", "heal role", "healer role", "healing role" },
        [271] = { "tank", "tanks", "tank role" },
        [272] = {
        "shows for all", "show for all", "role filter to all", "filter to all",
        "for everyone", "for anyone", "all roles", "all players",
    },
        [273] = {
        "mythic raid", "mythic raid frame", "mythic raid frames", "mythicraid",
        "mythicraidframe", "mythicraidframes",
    },
        [274] = { "party", "party frame", "party frames", "partyframe", "partyframes" },
        [275] = { "raid", "raid frame", "raid frames", "raidframe", "raidframes" },
        [276] = { "all group frames", "all groups", "every group frame", "each group frame", "party and raid", "party raid" },
        [277] = { "group", "groups", "group frame", "group frames" },
        [278] = { "aura", "auras", "buff", "debuff", "castbar", "cast bar", "boss target", "corner indicator", "spell indicator" },
        [279] = { "fallback aggro", "fallback threat", "group fallback aggro", "group fallback threat" },
        [280] = { "aggro", "threat" },
        [281] = { "color", "colour", "opacity", "alpha", "thickness", "size" },
        [282] = { "aura", "auras", "buff", "debuff" },
        [283] = { "sort", "sorting", "order", "first" },
        [284] = { "sort by role", "role sorting", "sort roles" },
        [285] = {
        "party", "raid", "mythic raid", "mythicraid", "group frame", "group frames", "frames",
        "role", "roles", "tank", "tanks", "healer", "healers", "heal", "dps", "damager", "name", "alphabetical", "group",
    },
        [286] = {
        "sort by group and role", "sort by group role", "group and role", "group plus role",
        "group role", "group then role", "group then roles", "groups then role", "groups then roles",
        "by group then role", "by group then roles", "by groups then role", "by groups then roles",
        "raid groups then roles", "raid groups then role", "groups first then roles", "groups first then role",
    },
        [287] = { "sort by group", "raid group order", "by raid group", "by group" },
        [288] = { "sort by name", "by name", "alphabetical", "alphabetically", "name order" },
        [289] = { "sort by role", "by role", "role sorting", "sort roles", "roles" },
        [290] = {
        "tank first", "tanks first", "tank on top", "tanks on top", "tank at top", "tanks at top",
        "tank at the top", "tanks at the top", "with tanks at top", "with tanks at the top",
        "tank role first", "tanks role first",
    },
        [291] = { "healer first", "healers first", "heal first", "heals first", "healer on top", "healers on top" },
        [292] = { "dps first", "damage first", "damager first", "damagers first", "dps on top" },
        [293] = { "aura", "auras", "buff", "debuff" },
        [294] = { "scale", "scaling", "frame scale", "frame scaling", "group scale", "group scaling" },
        [295] = {
        "scale mode", "scaling mode", "frame scale mode", "frame scaling mode",
        "group scale mode", "group scaling mode",
    },
        [296] = {
        "auto", "automatic", "automatically", "breakpoint", "breakpoints", "dynamic",
        "by player count", "by players", "by group size", "by raid size",
        "based on player count", "based on players", "based on group size", "based on raid size",
        "depending on player count", "depending on players", "depending on group size", "depending on raid size",
        "scale by player count", "scale by raid size", "scale by group size",
    },
        [297] = { "manual", "custom" },
        [298] = { "off", "disable", "disabled", "turn off", "none", "no scaling" },
        [299] = { "on", "enable", "enabled", "turn on" },
        [300] = { "aura", "auras", "buff", "debuff" },
        [301] = { "offline", "offline members", "offline players" },
        [302] = { "delay", "after", "seconds", "sec", "hide offline" },
        [303] = { "hide", "hide offline", "offline members", "offline players" },
        [304] = { "aura", "auras", "buff" },
        [305] = { "debuff" },
        [306] = { "debuff stripe" },
        [307] = { "midnight status icons", "status icons midnight style", "status icon midnight style", "midnight status icon style", "use midnight status icons" },
        [308] = { "global ui scale", "global ui scale override", "wow ui scale", "wow ui scale override", "ui scale override" },
        [309] = { "realtime power text", "real time power text", "live power text", "instant power text" },
        [310] = { "sync combat state colors", "sync combat enter leave colors", "same combat state colors", "combat state color sync" },
        [311] = { "sync", "same" },
        [312] = { "castbar fill left to right", "cast bar fill left to right", "castbar fills left to right", "cast bar fills left to right", "castbar direction left to right", "cast bar direction left to right" },
        [313] = { "castbar fill right to left", "cast bar fill right to left", "castbar fills right to left", "cast bar fills right to left", "castbar direction right to left", "cast bar direction right to left" },
        [314] = {
        "castbar fill backwards", "cast bar fill backwards", "castbar fills backwards", "cast bar fills backwards",
        "castbar fill backward", "cast bar fill backward", "castbar reverse fill", "cast bar reverse fill",
        "reverse castbar fill", "reverse cast bar fill", "castbar reverse direction", "cast bar reverse direction",
    },
        [315] = {
        "castbar fill normal", "cast bar fill normal", "castbar normal fill", "cast bar normal fill",
        "castbar normal direction", "cast bar normal direction", "castbar fill forward", "cast bar fill forward",
        "castbar forward fill", "cast bar forward fill",
    },
        [316] = { "nameplate melee spell id", "melee nameplate spell id", "melee range spell id", "crosshair melee spell id", "crosshair spell id" },
        [317] = { "snap", "snapping", "edge snap", "window snap", "menu snap", "snapping feature", "snap feature", "menue snap", "menue einrasten", "menue andocken", "fenster einrasten", "fenster andocken", "kante andocken" },
        [318] = { "edit mode", "grid snap", "snap to grid", "snap frames", "mover snap", "raster snap" },
        [319] = { "advanced menu", "advanced menu section", "advanced section", "erweitertes menu", "erweitertes menue", "advanced menue" },
        [320] = { "reduce motion", "menu motion", "reduce animations", "menu animations", "bewegung reduzieren", "menue bewegung reduzieren", "animationen reduzieren", "weniger bewegung", "weniger animationen", "reduzierte bewegung" },
        [321] = { "navigation icons", "nav icons", "menu icons", "sidebar icons", "rail icons", "navigation symbols", "nav symbols", "menu symbols", "sidebar symbols", "rail symbols", "navi symbole", "navigationssymbole", "navigation symbole", "menue symbole", "menu symbole", "navi icons" },
        [322] = { "welcome message", "startup welcome", "startup message", "start message", "willkommensnachricht", "willkommens nachricht", "willkommens meldung", "willkommen nachricht", "login nachricht", "start meldung" },
        [323] = { "version check", "peer version check", "peer-to-peer version check", "update check", "versionscheck", "versions pruefung", "version pruefung", "versionspruefung", "peer versionspruefung", "update pruefung" },
        [324] = { "minimap icon", "minimap button", "msuf minimap icon", "msuf minimap button", "minikarten symbol", "minimap symbol", "minimap knopf", "minikarten icon", "minikarten button", "minikarten knopf" },
        [325] = { "target sounds", "target sound", "target lost sound", "target lost sounds", "target select sound", "target select sounds", "target select lost sounds", "play sound on target", "play sound on target lost", "play sound on target select", "ziel sound", "ziel sounds", "zielauswahl sound", "ziel verloren sound", "ziel verloren sounds", "sound bei ziel", "sound bei zielwechsel", "spiele sound bei ziel" },
        [328] = { "menu language", "msuf language", "menu locale", "locale", "language", "sprache", "menue sprache", "menuesprache", "msuf sprache", "optionen sprache" },
        [329] = { "dropdown style", "dropdown style mode", "dropdown module style", "menu dropdown style", "dropdown skin", "dropdown design", "dropdown stil", "menue dropdown stil", "dropdown modus", "dropdown aussehen", "auswahlmenue stil", "menue auswahl stil" },
        [330] = { "msuf style", "msuf style module", "midnight style", "midnight design", "style module", "module style", "msuf skin", "msuf stil", "midnight stil", "stil modul", "style modul", "design modul", "msuf design", "skin modul" },
        [331] = {
            "status icon", "status icons", "status indicator", "status indicators", "indicator", "indicators",
            "ready check", "readycheck", "combat icon", "combat indicator", "rested icon", "resting icon",
            "leader icon", "assist icon", "role icon", "raid marker", "pvp flag", "phase icon", "summon icon",
            "party", "party frame", "raid", "raid frame", "group frame", "group frames",
        },
        [332] = { "tooltip modifier", "tooltip modifier key", "unit tooltip modifier", "unitframe tooltip modifier", "modifier key", "tooltip taste", "tooltip modifier taste", "tooltip hotkey", "tooltip aktivierungstaste" },
        [333] = { "tooltip", "tooltips" },
        [334] = { "use msuf tooltip", "use msuf tooltips", "use msuf unitframe tooltip", "nutze msuf tooltip", "nutze msuf tooltips", "verwende msuf tooltip", "verwende msuf tooltips" },
        [335] = { "use gametooltip", "use game tooltip", "use game tooltips", "use blizzard tooltip", "nutze gametooltip", "nutze game tooltip", "verwende gametooltip", "verwende blizzard tooltip" },
        [336] = { "tooltip source", "unitframe tooltip source", "unit tooltip source", "group frame tooltip source", "game tooltip source", "gametooltip source", "tooltip quelle", "tooltip anbieter", "unitframe tooltip quelle", "einheiten tooltip quelle", "gruppen tooltip quelle", "game tooltip quelle", "msuf tooltip quelle" },
        [337] = { "tooltip anchor", "unitframe tooltip anchor", "unit tooltip anchor", "tooltip position", "tooltip location", "tooltip anker", "unitframe tooltip anker", "tooltip ort", "tooltip platzierung" },
        [338] = { "tooltip", "tooltips" },
        [339] = { "cursor", "mouse", "maus", "mauszeiger", "fixed", "fest", "fixiert", "external", "extern", "addon kontrolliert", "am cursor", "an der maus" },
        [340] = { "unitframe tooltips", "unit frame tooltips", "unit tooltips", "group frame tooltips", "show tooltips", "tooltips", "tooltip mode", "tooltip visibility", "tooltip anzeigen", "tooltips anzeigen", "tooltip modus", "tooltip sichtbarkeit", "unitframe tooltip anzeigen", "einheiten tooltips", "gruppen tooltips" },
        [341] = { "tooltip", "tooltips" },
        [342] = { "always", "immer", "ooc", "out of combat", "ausserhalb kampf", "modifier", "alt", "ctrl", "strg", "shift", "umschalt", "never", "nie", "niemals", "aus", "an" },
        [343] = {
        "remove border", "remove outline", "without border", "without outline",
        "no border", "no outline", "turn off border", "turn off outline",
        "disable border", "disable outline", "hide border", "hide outline",
        "border off", "outline off", "border aus", "outline aus", "rand aus",
        "ohne rand", "rand entfernen", "rand ausschalten",
    },
        [344] = {
        "add border", "add outline", "with border", "with outline",
        "turn on border", "turn on outline", "enable border", "enable outline",
        "show border", "show outline", "border on", "outline on",
        "border enabled", "outline enabled", "border an", "outline an",
        "rand an", "rand aktivieren", "rand einschalten", "mit rand",
    },
        [345] = { "add", "give", "with", "enable", "show", "an", "aktivieren", "einschalten", "mit" },
        [346] = {
        "thickness", "size", "width", "border thickness", "border size", "border width",
        "outline thickness", "outline size", "outline width",
        "thicker", "thinner", "increase", "decrease", "raise", "lower", "more", "less",
        "bigger", "smaller", "dicker", "duenner", "groesser", "kleiner",
    },
        [347] = { "detached power", "detached power bar", "detached mana", "detached mana bar" },
        [348] = { "text on bar", "text on detached", "text on detached power", "text on detached power bar", "detached power text on bar" },
        [349] = { "frame level", "framelevel", "layer", "strata offset" },
        [350] = { "width", "wide", "wider", "narrower" },
        [351] = { "width mode", "width source" },
        [352] = { "height", "tall", "higher", "lower" },
        [353] = { "power bar", "mana bar", "power border", "mana border", "power outline", "mana outline", "power balken", "mana balken" },
        [354] = { "detach", "detached", "undock", "attach", "reattach", "dock", "abkoppeln", "ankoppeln" },
        [355] = { "embed", "embedded", "unembed", "unembedded", "into health", "into hp", "inside health", "inside hp", "within health", "within hp", "outside health", "outside hp", "out of health", "out of hp" },
        [356] = { "border", "outline", "rand" },
        [357] = { "height", "hoehe", "higher", "lower", "increase", "decrease", "raise", "reduce", "hoeher", "erhoehe", "erhoehen", "senke", "reduziere" },
        [358] = { "smooth", "embed", "embedded", "text", "sync", "anchor", "width", "x", "y", "layer" },
        [359] = { "interrupt", "interruptible", "kick", "kickable", "unterbrechen" },
        [360] = { "ready", "tracker", "focus kick", "indicator" },
        [361] = { "castbar", "cast bar", "zauberleiste" },
        [366] = { "aura", "auras", "buff", "debuff" },
        [367] = {
        "castbar", "cast bar", "cast color", "cast colour", "zauberleiste",
        "interrupt color", "interrupt colour", "interrupt feedback", "interrupted cast", "after interrupt",
        "interruptible", "kickable", "unkickable",
        "non interruptible", "noninterruptible", "uninterruptible", "kick ready", "kick not ready",
    },
        [368] = { "not ready", "notready", "cooldown", "on cooldown", "kick cooldown", "interrupt cooldown" },
        [369] = { "kick", "interrupt" },
        [370] = { "ready", "available", "kick ready", "interrupt ready" },
        [371] = { "kick", "interrupt" },
        [372] = { "text color", "font color", "spell name color", "spell text color", "castbar text", "cast bar text" },
        [373] = { "border color", "outline color", "castbar border", "cast bar border" },
        [374] = { "background color", "bg color", "castbar background", "cast bar background" },
        [375] = { "player castbar override color", "player castbar custom color", "player cast custom color", "custom player castbar color" },
        [376] = { "non interruptible", "noninterruptible", "not interruptible", "uninterruptible", "unkickable", "not kickable", "cannot interrupt", "cant interrupt" },
        [377] = { "interrupt feedback", "interrupted cast", "interrupted castbar", "after interrupt", "interrupt color all castbars", "interrupt color for all castbars" },
        [378] = { "interruptible", "kickable", "interrupt castbar", "castbar interrupt", "interrupt cast color" },
        [379] = { "interrupt color", "interrupt colour" },
        [380] = { "castbar", "cast bar", "zauberleiste" },
        [381] = {
        "group border", "full group border", "whole group border", "outer group border", "group block border",
    },
        [382] = {
        "border color", "border colour", "outline color", "outline colour",
        "frame border color", "frame outline color", "bar border color", "bar outline color",
    },
        [383] = {
        "aura", "auras", "buff", "debuff",
        "castbar", "cast bar", "portrait", "power bar", "mana bar",
        "aggro", "threat", "focus", "target", "dispel", "dispellable", "purge", "purgeable", "highlight",
    },
        [384] = {
        "group", "group frame", "group frames",
        "party", "party frame", "party frames",
        "raid", "raid frame", "raid frames", "mythic raid", "mythicraid",
    },
        [385] = { "opacity", "alpha", "transparent", "transparency", "color", "colour" },
        [386] = {
        "bar outline", "frame outline", "outline thickness", "outline size", "outline width",
        "bar border thickness", "bar border size", "bar border width",
        "party frame border", "raid frame border", "mythic raid frame border",
    },
        [387] = {
        "thickness", "size", "width", "thicker", "thinner", "bigger", "smaller",
        "increase", "decrease", "reduce", "dicker", "duenner",
    },
        [388] = {
        "group frame border", "group frame outline", "frame border", "frame outline",
        "border thickness", "outline thickness", "border size", "outline size",
        "border width", "outline width",
    },
        [389] = {
        "aura", "auras", "buff", "debuff",
        "castbar", "cast bar", "portrait", "power bar", "mana bar",
        "aggro", "threat", "focus", "target", "dispel", "dispellable", "purge", "purgeable", "highlight",
    },
        [390] = {
        "group", "group frame", "group frames",
        "party", "party frame", "party frames",
        "raid", "raid frame", "raid frames", "mythic raid", "mythicraid",
    },
        [391] = { "aura", "auras", "buff", "buffs" },
        [392] = { "debuff", "debuffs" },
        [393] = { "debuff stripe", "debuff stripes" },
        [394] = { "color", "colors", "colour", "colours", "farbe", "farben", "tint" },
        [395] = {
        "group", "group frame", "group frames", "groupframe", "groupframes", "gruppenframe", "gruppenframes",
        "party", "party frame", "party frames", "raid", "raid frame", "raid frames", "mythic raid", "mythicraid",
    },
        [396] = { "off", "disable", "disabled", "hide", "stop", "clear", "aus", "deaktivieren", "ausschalten", "ausblenden" },
        [397] = { "on", "enable", "enabled", "show", "test", "preview", "an", "aktivieren", "einschalten", "anzeigen" },
        [398] = {
        "status icon", "status icons", "status indicator", "status indicators",
        "status preview", "test status", "test mode",
    },
        [399] = { "test", "preview", "test mode", "status preview" },
        [400] = { "show all", "all indicators", "all status icons", "preview all", "current indicator", "preview current" },
        [401] = { "aura", "auras", "buff", "debuff" },
        [402] = {
        "hide name on dead", "hide name when dead", "hide name on offline", "hide name when offline",
        "hide name on dead or offline", "hide name when dead or offline", "dead or offline",
    },
        [403] = { "turn off", "disable", "disabled", "deactivate", "deactivated", "ausschalten", "deaktivieren" },
        [404] = { "reverse hp text", "hp text reverse", "reverse health text", "health text reverse" },
        [405] = { "group number", "group index", "group number label" },
        [406] = { "size", "font size", "anchor", "x offset", "y offset", "offset", "color", "colour", "style" },
        [407] = {
            "move", "nudge", "shift", "position", "right", "left", "up", "down", "oben", "unten", "links", "rechts",
            "bigger", "larger", "smaller", "increase", "decrease", "reduce", "grow", "shrink", "groesser", "kleiner",
        },
        [408] = { "aura", "auras", "buff", "debuff" },
        [409] = {
        "reverse hp text", "hp text reverse", "reverse health text", "health text reverse",
        "reverse hp text order", "hp text reverse order", "reverse health text order", "health text reverse order",
    },
        [410] = { "unitframe", "unit frame", "unitframes", "unit frames" },
        [411] = { "group frame", "group frames", "groupframe", "groupframes" },
        [412] = { "aura", "auras", "buff" },
        [413] = { "group number", "group index", "group number label" },
        [414] = { "size", "font size", "scale", "bigger", "larger", "smaller", "increase", "decrease", "reduce", "grow", "shrink", "groesser", "kleiner" },
        [415] = { "group border padding", "border padding", "padding around", "padding around frames", "padding around group", "frame padding" },
        [416] = { "thickness", "size", "border size", "border thickness", "thicker", "thinner", "increase", "decrease", "reduce", "bigger", "smaller", "dicker", "duenner" },
        [417] = { "power height", "power bar height", "mana height", "mana bar height" },
        [418] = { "debuff stripe height", "debuff stripe size" },
        [419] = { "group frame", "group frames", "all group", "all groups" },
        [420] = { "inline" },
        [421] = { "inline text", "target target inline text", "target of target inline text", "separator", "seperator", "delimiter" },
        [422] = { "target of target", "targettarget", "target inline", "target target", "tot" },
        [423] = { "only", "nur", "just" },
        [424] = { "current health only", "on current health only", "on health only" },
        [425] = { "castbar", "cast bar", "zauberleiste" },
        [426] = {
        "font", "fonts", "schrift", "text outline", "font outline", "text shadow",
        "name color", "name text color", "name shortening", "text size",
        "text color", "color text", "health text color", "hp text color",
        "power text color", "mana text color", "resource text color",
        "color text by power", "color text by health",
    },
        [427] = { "bars", "bar", "bar texture", "health bar", "hp bar", "power bar", "gradient", "absorb", "outline", "border", "dispel", "aggro", "purge" },
        -- Colour MODES that Name Text Color Mode cannot express. It offers only
        -- Default and Class, but its lane derives the value from a hardcoded
        -- spec rather than from the sentence, so any of these was silently
        -- written as Class. They each belong to a sibling control (Health Text
        -- Color Mode, Power Text Color Mode, NPC Name Text Color).
        [428] = {
        "health", "hp", "by health", "health color", "health colour",
        "reaction", "reaction color", "reaction colour",
        "power", "mana", "resource", "power type", "by type",
        "threat", "aggro",
    },
    },
}
