-- Assistant features parser data.
-- Generated phrase lists for MSUF_AssistantParser_Features.lua.
local addonName, MSUF = ...
MSUF = MSUF or _G.MSUF_NS or {}

local M = MSUF.MSUF2 or _G.MSUF2 or {}
MSUF.MSUF2 = M

local A = MSUF.Assistant or {}
MSUF.Assistant = A
M.Assistant = A

local Data = A.ParserData or {}
A.ParserData = Data

Data.FEATURES_PARSER = {
    PHRASES = {
        [1] = {
        "not class resource", "not class resources", "not class power", "not class bar", "not resource bar",
        "no class resource", "no class resources", "no class power", "no class bar", "no resource bar",
        "dont class resource", "do not class resource",
        "nicht class resource", "nicht class power", "nicht klassenressource", "keine class resource",
        "kein class resource", "keine klassenressource", "nicht ressourcenleiste",
    },
        [2] = { "resource numbers", "resource number", "resource text", "resource texts" },
        [3] = { "setting", "settings", "option", "options", "page", "menu" },
        [4] = { "show me", "show", "open", "where", "find", "help" },
        [5] = { "auto fit", "autofit", "auto-fit", "auto fit pips", "fit pips", "compact pips", "pip width" },
        [6] = { "utility cooldown", "utility cooldowns", "utility cooldown manager", "utility cooldownmanager" },
        [7] = { "tracked buff", "tracked buffs", "buff tracker", "tracked-buffs" },
        [8] = { "custom width", "manual width", "custom mode", "manual mode" },
        [9] = { "detached power", "alt mana", "alternative mana" },
        [10] = {
        "width", "wide", "match", "same width", "width mode", "width source", "match width",
        "player width", "player frame width", "auto fit", "fit pips", "pip width",
    },
        [11] = { "width mode", "width source", "match", "same width", "player width", "cooldown", "cooldowns", "tracked buff", "utility", "auto fit", "fit pips", "pip width" },
        [12] = { "hide", "hide when", "hide while", "hide out of combat", "hide ooc" },
        [13] = { "show", "visible" },
        [14] = { "turn on" },
        [15] = {
        "when full", "if full", "full resource", "full resources",
        "when empty", "if empty", "empty resource", "empty resources",
        "out of combat", "ooc",
    },
        [16] = {
        "turn off hide", "disable hide", "dont hide", "do not hide", "never hide",
        "always show", "show when", "show while", "show out of combat", "show class resource",
    },
        [17] = { "turn on hide", "enable hide", "hide when", "hide while", "hide out of combat", "hide ooc" },
        [18] = { "hide class resource", "hide class resources", "hide class power", "hide class bar", "hide resource bar", "hide" },
        [19] = { "out of combat", "ooc" },
        [20] = { "when full", "if full", "full resource", "full resources", "full" },
        [21] = { "when empty", "if empty", "empty resource", "empty resources", "empty" },
        [22] = {
        "detached power", "alt mana", "alternative mana", "text anchor",
        "player hp", "player hp bar", "hp bar", "class resource hp", "class resources hp",
        "class resource health", "class resources health", "second hp", "duplicate hp",
    },
        [23] = {
        "anchor", "anchored", "follow", "attach", "attached", "dock", "to cooldown", "to cooldowns",
        "to player", "player frame", "cooldownmanager", "cooldown manager",
    },
        [24] = {
        "detach", "detach from", "undock", "undock from", "disconnect", "disconnect from",
        "stop following", "dont follow", "do not follow", "remove from",
    },
        [25] = { "anchor", "follow", "attach", "dock" },
        [26] = { "width", "match width", "same width" },
        [27] = { "under", "below", "beneath", "bottom of", "underneath", "unter", "darunter" },
        [28] = { "above", "over", "top of", "ueber", "darueber" },
        [29] = { "on player", "on the player", "inside player", "inside the player" },
        [30] = { "detached power", "alt mana", "alternative mana", "text" },
        [31] = {
        "player hp", "player hp bar", "player health", "player health bar",
        "class resource hp", "class resources hp", "class resource health", "class resources health",
        "second hp", "second player hp", "duplicate hp", "duplicate health",
    },
        [32] = { "color", "colour", "background", "font size", "text size", "move", "offset" },
        [33] = { "as text", "show text", "show numbers", "show number", "numbers only", "text only" },
        [34] = { "show", "turn on", "enable" },
        [35] = { "number", "numbers", "text" },
        [36] = {
        "as pips", "as dots", "as bars", "show pips", "show dots", "show bars",
        "pips only", "dots only", "hide numbers", "hide number", "hide text",
        "turn off numbers", "turn off number", "turn off text", "disable numbers",
        "disable number", "disable text", "without numbers", "no numbers",
    },
        [37] = { "hide", "turn off", "disable", "without", "no" },
        [38] = { "number", "numbers", "text" },
        [39] = { "show", "turn on", "enable" },
        [40] = {
        "player hp", "player hp bar", "player health", "second hp", "duplicate hp",
        "hp", "hp bar", "health", "health bar",
        "detached power", "detached power bar", "player power", "player power bar",
        "alt mana", "alternative mana",
    },
        [41] = { "color", "colors", "colour", "colours", "reset", "default", "defaults", "restore" },
        [42] = {
        "shape", "form", "as bar", "as bars", "as circle", "as circles", "as dots",
        "as diamond", "as diamonds", "as hex", "as hexagons",
        "bar shape", "circle shape", "dot shape", "orb shape", "diamond shape",
        "gem shape", "crystal shape", "hex shape", "hexagon shape",
        "alignment", "align pips", "pip alignment",
    },
        [43] = { "alignment", "align pips", "pip alignment", "shape align", "left", "center", "centre", "middle", "right" },
        [44] = { "alignment", "align", "left", "center", "centre", "middle", "right" },
        [45] = { "left to right", "right to left", "fill left", "fill right" },
        [46] = { "shape", "form", "bar", "circle", "round", "dot", "orb", "diamond", "gem", "crystal", "hex", "hexagon" },
        [47] = { "detached power", "alternative mana", "alt mana" },
        [48] = {
        "fill", "direction", "reverse", "reversed", "backwards", "backward",
        "right to left", "left to right", "normal", "forward",
    },
        [49] = { "reverse", "reversed", "backwards", "backward", "right to left" },
        [50] = {
        "right to left", "fill right", "fill backwards", "fill backward",
        "fills backwards", "fills backward", "reverse fill", "reverse direction",
        "fill reverse", "fill reversed", "other way",
    },
        [51] = {
        "left to right", "fill left", "normal direction", "normal fill",
        "fill normal", "forward fill", "fill forward", "same direction",
    },
        [52] = { "reverse", "reversed" },
        [53] = {
        "fill", "direction", "reverse", "reversed", "backwards", "backward",
        "right to left", "left to right", "normal", "forward",
    },
        [54] = { "reverse", "reversed", "backwards", "backward", "right to left" },
        [55] = {
        "right to left", "fill right", "fill backwards", "fill backward",
        "fills backwards", "fills backward", "reverse fill", "reverse direction",
        "fill reverse", "fill reversed", "other way",
    },
        [56] = {
        "left to right", "fill left", "normal direction", "normal fill",
        "fill normal", "forward fill", "fill forward", "same direction",
    },
        [57] = { "reverse", "reversed" },
        [58] = { "move", "nudge", "shift", "offset", "position" },
        [59] = { "text x", "text y", "text left", "text right", "text up", "text down", "x to", "y to" },
        [60] = { "text", "number", "numbers", "font", "font size", "text size", "number size" },
        [61] = { "size", "bigger", "larger", "smaller", "increase", "decrease", "raise", "reduce", "set", "make" },
        [62] = { "player hp", "player hp bar", "second hp", "duplicate hp" },
        [63] = {
        "text", "number", "numbers", "font", "outline", "border", "gap", "gaps", "spacing",
        "space", "spaces", "distance", "separator", "separators", "divider", "dividers", "tick",
        "ticks", "background", "opacity", "alpha", "texture",
    },
        [64] = { "width", "wide", "wider", "narrower", "height", "tall", "taller", "shorter", "size", "bigger", "larger", "smaller" },
        [65] = { "width", "wide", "wider", "narrower" },
        [66] = { "player hp", "player hp bar", "second hp", "duplicate hp", "detached power", "alt mana" },
        [67] = { "frame level", "framelevel", "layer", "z layer", "z level", "strata" },
        [68] = { "text", "number", "numbers", "font", "aura", "buff", "debuff", "status icon", "raid marker" },
        [69] = {
        "player hp", "player hp bar", "player health", "player health bar",
        "class resource hp", "class resources hp", "class resource health", "class resources health",
        "second hp", "second player hp", "duplicate hp", "duplicate health",
    },
        [70] = { "player hp", "player hp bar", "player health", "player health bar" },
        [71] = {
            "class power", "class powers", "class resource", "class resources",
            "second hp", "second player hp", "duplicate hp", "duplicate health",
        },
        [72] = { "use player text", "player text" },
        [73] = { "reverse text", "reversed text" },
        [74] = { "left text", "left slot" },
        [75] = { "center text", "centre text", "middle text", "center slot", "centre slot", "middle slot" },
        [76] = { "right text", "right slot" },
        [77] = { "text delimiter", "text separator", "delimiter", "separator" },
        [78] = { "text size", "font size", "text font" },
        [79] = { "text x", "text offset x" },
        [80] = { "text y", "text offset y" },
        [81] = { " text", " hp text", "health text" },
        [82] = { "background texture", "bg texture" },
        [83] = { "foreground texture", "texture" },
        [84] = { "background opacity", "background alpha", "bg opacity", "bg alpha" },
        [85] = { "width mode", "follows class resource", "follow class resource", "follows class", "follow class" },
        [86] = { "anchor", "anchoring", "above", "below", "top", "bottom" },
        [87] = { "smooth fill", "smooth hp", "smooth health" },
        [88] = { "color mode", "colour mode", " hp color", " hp colour", "health color", "health colour" },
        [89] = { "orb size", "sphere size" },
        [90] = { "shape", "orb", "bar shape" },
        [91] = { "frame level", "framelevel", "layer", "z layer", "z level", "strata" },
        [92] = { "gap", "gaps", "spacing", "space", "distance" },
        [93] = { "outline", "border", "outline width", "border width", "outline thickness", "border thickness" },
        [94] = { " x", "x offset", "offset x", "left", "right" },
        [95] = { " y", "y offset", "offset y", "up", "down" },
        [96] = { "width", "wide", "wider", "narrower" },
        [97] = { "height", "tall", "taller", "shorter" },
        [98] = { "hp bar", "health bar", "player hp", "player health", "second hp", "duplicate hp" },
        [99] = {
        "empowered combo point", "empowered combo points",
        "charged combo point", "charged combo points",
        "combo point charges",
    },
        [100] = {
        "color", "colour", "background", "bg", "text", "number", "font",
        "size", "width", "height", "gap", "spacing", "anchor", "move",
    },
        [101] = { "rune time", "rune timer", "rune timers", "rune cooldown", "rune cooldowns" },
        [102] = {
        "color", "colour", "background", "bg", "font", "size",
        "width", "height", "gap", "spacing", "anchor", "move",
    },
        [103] = {
        "color", "colour", "background", "bg", "font", "size",
        "width", "height", "gap", "spacing", "anchor", "move",
    },
        [104] = { "background", "bg", "font", "size", "width", "height", "anchor", "move" },
        [105] = { "color by type", "colour by type", "resource type colors", "resource type colours", "class resource class colors", "class resource class colours" },
        [106] = { "combo point color mode", "combo point colour mode", "combo point slot mode", "combo slot mode", "combo point colors", "combo point colours", "combo colors", "combo colours" },
        [107] = { "separator", "separators", "divider", "dividers", "tick", "ticks" },
        [108] = { "gap", "gaps", "spacing", "space", "spaces", "distance", "text", "font" },
        [109] = {
        "player hp", "player hp bar", "player health", "player health bar",
        "class resource hp", "class resources hp", "class resource health", "class resources health",
        "second hp", "second player hp", "duplicate hp", "duplicate health",
    },
        [110] = { "gap", "gaps", "spacing", "space", "spaces", "distance", "pip gap", "point gap" },
        [111] = { "text", "font", "outline", "border" },
        [112] = { "resource bar", "resource bars", "power bar", "power bars" },
        [113] = {
            "class power", "class powers", "class resource", "class resources",
            "combo point", "combo points", "holy power", "soul shard", "soul shards",
            "rune", "runes", "chi", "arcane charge", "arcane charges", "essence",
            "maelstrom", "ebon might", "insanity", "stagger", "eclipse",
        },
        [114] = { "background", "bg", "empty background" },
        [115] = { "color", "colour", "texture" },
        [116] = { "hide", "remove", "without", "no background" },
        [117] = { "show", "enable", "turn on", "with background" },
        [118] = {
        "player hp", "player hp bar", "player health", "player health bar",
        "class resource hp", "class resources hp", "class resource health", "class resources health",
        "second hp", "second player hp", "duplicate hp", "duplicate health",
    },
        [119] = { "outline", "border", "outline width", "border width", "outline thickness", "border thickness" },
        [120] = { "filled opacity", "filled alpha", "active opacity" },
        [121] = { "empty opacity", "empty alpha", "inactive opacity" },
        [122] = {
        "player hp", "player hp bar", "player health", "player health bar",
        "class resource hp", "class resources hp", "class resource health", "class resources health",
        "second hp", "second player hp", "duplicate hp", "duplicate health",
        "detached power", "alt mana", "alternative mana",
    },
        [123] = { "texture", "foreground texture", "background texture", "bg texture" },
        [124] = { "background texture", "bg texture" },
        [125] = {
        "detached power", "detached power bar", "detached mana", "detached mana bar",
        "class resources player power", "class resources player power bar",
        "class resource player power", "class resource player power bar",
        "player power in class resources", "player power bar in class resources",
    },
        [126] = { "player hp", "player health", "second hp", "duplicate hp", "alt mana", "alternative mana" },
        [127] = { "width mode", "width source", "follows cooldown", "follows tracked buff" },
        [128] = { "texture", "foreground texture", "background texture", "bg texture" },
        [129] = { "background texture", "bg texture" },
        [130] = { "outline", "border", "outline width", "border width", "outline thickness", "border thickness" },
        [131] = { "alt mana", "alternative mana", "secondary mana", "dual resource mana" },
        [132] = { "detached power", "player hp", "second hp", "duplicate hp" },
        [133] = { "height", "tall", "taller", "shorter" },
        [134] = { "y offset", "offset y", " y", "up", "down" },
        [135] = { "text", "number", "font", "detached power", "alt mana", "alternative mana" },
        [136] = { "move", "nudge", "shift", "verschiebe" },
        [137] = { "player hp", "player health", "second hp", "second player hp", "duplicate hp", "alt mana", "alternative mana" },
        [138] = {
        "class resources player power", "class resource player power", "class power player power",
        "class resources player power bar", "class resource player power bar", "class power player power bar",
        "attached player power", "attached player power bar", "detached player power", "detached player power bar",
        "klassenressourcen spieler energie", "klassenressourcen spieler energieleiste",
    },
        [139] = {
        "detached power", "detached power bar", "detached mana", "detached mana bar",
        "player power", "player power bar", "player mana", "player mana bar",
        "spieler energie", "spieler energieleiste", "abgekoppelte energie", "abgekoppelte energieleiste",
    },
        [140] = {
        "detached power", "detached power bar", "player power", "player power bar",
        "power area", "power section", "spieler energie", "energieleiste",
    },
        [141] = {
        "anchor to class", "anchor to class resource", "anchor to class resources",
        "anchor detached power to class", "anchor detached power to class resource", "anchor detached power to class resources",
        "anchor detached power bar to class", "anchor detached power bar to class resource", "anchor detached power bar to class resources",
        "anchor player power to class", "anchor player power bar to class",
        "anchor class resources player power", "anchor class resource player power", "anchor class power player power",
        "anchor class resources player power bar", "anchor class resource player power bar", "anchor class power player power bar",
        "player power to class resource", "player power to class resources", "player power bar to class resource",
        "power bar to class resource", "attached to class resource", "follow class resource",
        "an klassenressource ankern", "an klassenressourcen ankern",
    },
        [142] = { "off", "disable", "disabled", "no", "not", "detach", "disconnect", "aus", "deaktivieren", "nicht" },
        [143] = {
        "detached power sync class resource", "detached power sync class resources",
        "detached power bar sync class resource", "detached power bar sync class resources",
        "sync width", "sync to class", "sync with class", "match class resource width", "same width as class resource",
        "class resources player power sync", "class resources player power sync width",
        "class resources player power bar sync", "class resources player power bar sync width",
        "player power sync class resource", "player power bar sync class resource",
        "sync class resources player power", "sync class resources player power width",
        "sync class resources player power bar", "sync class resources player power bar width",
        "breite synchron", "gleiche breite",
    },
        [144] = { "manual", "off", "disable", "disabled", "no", "not", "aus", "deaktivieren", "nicht" },
        [145] = { "detach", "detached", "undock", "separate", "separated", "enable", "show", "attach", "reattach", "dock", "hide", "disable", "abkoppeln", "abgekoppelt", "ankoppeln", "anzeigen", "ausblenden" },
        [146] = { "attach", "reattach", "dock", "ankoppeln" },
        [147] = { "detach", "detached", "undock", "separate", "separated", "abkoppeln", "abgekoppelt" },
        [148] = { "text on bar", "power text on bar", "text inside", "text auf leiste", "text in leiste" },
        [149] = { "width", "wide", "wider", "narrower", "breite", "breiter", "schmaler" },
        [150] = { "shape", "form", "orb", "round", "crystal", "bar", "follow class", "sphere", "kugel", "rund", "kristall" },
        [151] = { "texture", "foreground", "background", "outline", "border", "color", "colour", "textur", "vordergrund", "hintergrund", "rahmen", "farbe" },
        [152] = { "orb size", "sphere size", "kugel groesse", "orb groesse" },
        [153] = { "text size", "font size", "power text size", "schriftgroesse", "textgroesse" },
        [154] = { "frame level", "framelevel", "layer", "strata", "ebene", "schicht" },
        [155] = { "height", "tall", "higher", "lower", "hoehe", "hoeher", "niedriger" },
        [156] = { "x", "y", "offset", "move", "nudge", "shift", "verschiebe", "versatz", "position" },
        [157] = { "x", "x offset", "offset x", "horizontal", "x versatz" },
        [158] = { "y", "y offset", "offset y", "vertical", "y versatz" },
        [159] = { "timer" },
        [160] = { "enter", "leave", "state" },
        [161] = { "color", "colour", "farbe" },
        [162] = { "combat enter text", "enter combat text", "combat state enter text" },
        [163] = { "combat leave text", "leave combat text", "combat state leave text" },
        [164] = { "unlock", "unlocked" },
        [165] = { "clickable", "mouse input on", "enable mouse input", "accept clicks" },
        [166] = { "lock", "locked", "click through", "click-through", "sync", "same", "ready", "icon", "cooldown swipe" },
        [167] = { "anchor", "attach", "size", "groesse", "grosse", "font", "duration", "dauer", "offset", "position", "move", "verschiebe", "x", "y", "thickness", "thick", "thin", "dicke", "staerke", "spell", "zauber" },
        [168] = { "anchor", "attach", "attached", "from point", "to point", "anker", "ankerpunkt", "anhaengen", "anhaengen an", "von punkt", "zu punkt" },
        [169] = { "from anchor", "anchor from", "from point", "von anker", "anker von", "von punkt" },
        [170] = { "to anchor", "anchor to", "to point", "attach to", "zu anker", "anker zu", "zu punkt", "anhaengen an" },
        [171] = { "melee range spell", "crosshair melee spell", "crosshair spell id", "combat crosshair spell id", "range check spell" },
        [172] = { "crosshair", "combat crosshair", "fadenkreuz" },
        [173] = { "clear", "reset", "none", "no spell" },
        [174] = { "spell", "spell id", "range check spell" },
        [175] = { "duration", "time visible", "visible time", "dauer", "anzeigedauer", "sichtbar dauer" },
        [176] = { "thickness", "thick", "thicker", "thin", "thinner", "dicke", "staerke", "strichstaerke", "duenner", "dunner" },
        [177] = { "size", "font size", "text size", "icon size", "bigger", "larger", "smaller", "grow", "shrink", "groesse", "grosse", "groesser", "kleiner" },
        [178] = { "under", "below", "beneath", "bottom of", "unter", "darunter" },
        [179] = { "above", "over", "top of", "ueber", "darueber", "oben" },
        [180] = { "left of", "to the left of", "links von" },
        [181] = { "right of", "to the right of", "rechts von" },
        [182] = { "center on", "centered on", "middle of", "zentriert", "mitte" },
        [183] = { "move", "place", "put", "position", "set", "verschiebe", "stelle", "setze" },
        [184] = { "move", "nudge", "shift", "verschiebe", "offset", "position", "x", "y", "horizontal", "vertical" },
        [185] = { "x", "x offset", "offset x", "horizontal" },
        [186] = { "y", "y offset", "offset y", "vertical" },
        [187] = { "font color", "text color", "global font color", "schriftfarbe", "textfarbe" },
        [188] = {
            "castbar", "combat", "aura", "stack", "cooldown", "power", "hp", "health",
            "name", "boss target", "mouseover", "dispel", "bar", "npc", "portrait",
        },
        [189] = { "global", "main", "default" },
        [190] = { "reset", "default", "palette", "zuruecksetzen" },
        [191] = { "reset", "default", "defaults", "restore", "zuruecksetzen" },
        [192] = { "background", "bg", "backdrop" },
        [193] = {
        "power text", "powertext", "mana text", "resource text", "font color", "text color",
    },
        [194] = {
        "class power", "class resource", "combo point", "combo points", "holy power",
        "soul shard", "soul shards", "chi", "arcane charge", "arcane charges", "runes",
    },
        [195] = {
        "color", "colors", "colour", "colours", "tint", "power bar", "powerbar",
        "resource bar", "mana bar", "energy bar", "rage bar",
    },
        [196] = { "reset", "default", "defaults", "restore", "zuruecksetzen" },
        [197] = { "reset", "default", "defaults", "restore", "zuruecksetzen" },
        [198] = { "color", "colors", "colour", "colours", "farbe", "farben", "tint", "gradient" },
        [199] = {
        "combo point slot", "combo point slots", "combo slot", "combo slots",
        "combo point colors", "combo colors", "all combo point colors",
    },
        [200] = { "power color", "power bar", "powerbar", "resource color", "resource bar", "mana color", "rage color", "energy color", "runic power", "astral power", "maelstrom color" },
        [201] = { "class power", "class resource", "combo point", "combo points", "holy power", "soul shard", "soul shards", "chi", "arcane charge", "arcane charges", "runes" },
        [202] = {
        "class power", "class resource", "resource", "combo", "holy power", "soul", "soul shard",
        "maelstrom", "astral", "arcane charge", "arcane charges", "eclipse", "stagger",
        "icicles", "ebon", "whirlwind", "tip of the spear", "insanity", "runes", "chi", "essence",
    },
        [203] = { "background", "bg" },
        [204] = { "castbar", "cast bar" },
        [205] = { "npc type", "npc role" },
        [206] = { "health gradient", "hp gradient", "gradient stop", "gradient stops", "reset gradient" },
        [207] = { "unitframe", "unit frame", "npc reaction", "reaction color" },
        [208] = { "class color", "class colors", "class bar" },
        [209] = { "bar background", "background tint", "bar tint" },
        [210] = { "bar color", "bar colors", "absorb", "aggro", "purge", "outline", "border" },
        [211] = { "dispel", "debuff type" },
        [212] = { "gameplay", "combat timer", "combat state", "crosshair" },
        [213] = { "aura", "auras", "buff", "debuff", "pandemic" },
        [214] = { "portrait" },
        [215] = { "resource", "power color", "class power", "class resource", "combo point" },
        [216] = {
        "turn on", "turn off", "enable", "disable", "show", "hide", "set", "make",
        "move", "put", "send", "bring", "increase", "decrease", "raise", "lower",
        "an", "aus", "einschalten", "ausschalten", "aktivieren", "deaktivieren",
        "einblenden", "ausblenden", "zeige", "anzeigen", "verstecke", "setze",
        "stelle", "mach", "mache", "verschiebe", "erhoehe", "reduziere", "senke",
    },
        [217] = {
        "diagnose", "diagnostic", "troubleshoot", "why", "wieso", "warum",
        "diagnostik", "diagnosebericht", "fehlersuche", "fehleranalyse",
        "not showing", "not visible", "not appearing", "not displayed", "not there",
        "doesnt show", "does not show", "doesnt appear", "does not appear",
        "cant see", "can't see", "cannot see", "can not see", "missing", "hidden", "invisible",
        "filtered out", "filtered", "blacklisted", "blocked",
        "disappeared", "disappear", "gone", "vanished", "broken", "not working", "doesnt work",
        "does not work", "won't work", "wont work", "fails", "failed", "failing", "failure", "error", "errors", "stuck",
        "nicht sichtbar", "zeigt nicht", "verschwunden", "kaputt", "haengt",
        "weg", "fehlt", "fehlen", "fehlende", "fehlender", "fehlendes", "fehlenden", "fehlgeschlagen",
        "versteckt", "unsichtbar", "funktioniert nicht", "geht nicht", "fehler",
    },
        [218] = {
        "diagnose", "diagnostic", "troubleshoot", "why", "wieso", "warum",
        "diagnostik", "diagnosebericht", "fehlersuche", "fehleranalyse",
        "pruefe", "pruefen", "ueberpruefe", "ueberpruefen", "checke", "check",
        "fix", "repair", "repariere", "reparieren", "beheben",
        "not showing", "not visible", "not appearing", "not displayed", "not there",
        "doesnt show", "does not show", "doesnt appear", "does not appear",
        "cant see", "can't see", "cannot see", "can not see", "missing", "hidden", "invisible",
        "filtered out", "filtered", "blacklisted", "blocked",
        "disappeared", "disappear", "gone", "vanished", "broken", "not working", "doesnt work",
        "does not work", "won't work", "wont work", "fails", "failed", "failing", "failure", "error", "errors", "stuck",
        "nicht sichtbar", "zeigt nicht", "verschwunden", "kaputt", "haengt",
        "weg", "fehlt", "fehlen", "fehlende", "fehlender", "fehlendes", "fehlenden", "fehlgeschlagen",
        "versteckt", "unsichtbar", "funktioniert nicht", "geht nicht", "fehler",
    },
        [219] = {
        "profile mapping", "profile mappings", "spec profile mapping", "spec profile mappings",
        "broken profile mapping", "broken profile mappings", "broken spec mapping", "broken spec mappings",
    },
        [220] = { "fix", "repair", "clear", "remove", "delete", "loeschen", "reparieren", "beheben" },
        [221] = { "combat timer", "kampf timer", "kampftimer" },
        [222] = { "combat enter", "combat leave", "combat state", "combat text", "enter leave", "kampf text", "kampfanzeige" },
        [223] = { "totem", "totem frame", "statue", "statue frame" },
        [224] = { "crosshair", "combat crosshair", "fadenkreuz" },
        [225] = { "gameplay", "gameplay helper", "gameplay helpers", "spielhilfe", "spielhilfen" },
        [226] = { "timer", "helper", "helpers", "not visible", "missing", "hidden", "nicht sichtbar" },
        [227] = { "profile", "profiles", "profil", "profile import", "profile export", "spec profile", "profil import", "profil export", "spec profil" },
        [228] = { "class resource", "class resources", "class power", "class bar", "resource bar", "combo point", "combo points", "holy power", "soul shard", "soul shards", "rune", "runes" },
        [229] = { "aura", "auras", "buff", "buffs", "debuff", "debuffs" },
        [230] = { "debuff", "debuffs" },
        [231] = { "buff", "buffs" },
        [232] = { "castbar", "cast bar", "cast bars", "casting bar", "zauberleiste" },
        [233] = { "detached power", "detached power bar", "power bar", "powerbar", "resource bar" },
        [234] = { "how", "where", "where can", "where do", "help", "explain", "what", "which" },
        [235] = {
            "ready check", "readycheck", "status icon", "status icons", "indicator", "indicators",
            "role icon", "leader icon", "assist icon", "summon icon", "phase icon", "pvp icon",
            "war mode", "spell indicator", "corner indicator", "raid marker",
        },
        [236] = { "group frames", "party frames", "raid frames", "mythic raid frames" },
        [237] = { "group frames", "gruppenframes", "party frames", "raid frames", "mythic raid frames" },
        [238] = { "dashboard", "assistant", "menu", "menu2", "setup", "assistant setup", "menu setup", "navigation", "page stack", "workflow", "setup checklist", "guided setup", "assistent", "menue", "einrichtung", "setup checkliste" },
        [239] = {
        "help me setup", "help me set up", "help me configure", "help me build",
        "guide me", "setup guide", "guided setup", "start guide", "start tour",
    },
        [240] = {
        "what can i change", "what can change", "what settings can i change",
        "what can i do here", "what can i change here", "commands for",
        "show commands for", "help for", "help with", "help me with",
        "what can i do on this page", "what can i do on current page",
        "what can i change on this page", "what can i change on current page",
        "explain this page", "explain current page", "page help",
        "help on this page", "help for this page", "commands on this page",
        "how can i configure this page", "how do i configure this page",
        "how can i use this page",
    },
        [241] = { "edit mode", "editmode" },
        [242] = {
        "help", "hilfe", "explain", "erklaere", "what is", "what are", "what can",
        "commands", "command examples",
    },
        [243] = { "how", "how do", "how can", "how to", "where", "where do", "where can", "where is" },
        [244] = {
            "change", "set", "make", "move", "hide", "show", "turn on", "turn off", "enable", "disable",
            "configure", "adjust", "bigger", "larger", "smaller", "wider", "taller", "lock", "unlock",
        },
        [245] = { "how", "how do", "how to", "why" },
        [246] = { "edit mode", "editmode" },
        [247] = { "help", "hilfe", "explain", "erklaere", "what is", "what can", "how", "how do", "how to", "commands" },
        [248] = { "here", "current page", "this page" },
        [249] = { "aura", "auras", "buff", "debuff" },
        [250] = { "castbar", "cast bar" },
        [251] = { "discord", "discord link", "support discord" },
        [252] = { "patreon", "patreon link" },
        [253] = { "paypal", "pay pal", "paypal link" },
        [254] = { "ko fi", "kofi", "ko-fi" },
        [255] = { "github", "repository", "repo link" },
        [256] = {
        "boss preview", "boss previews", "boss frame preview", "boss frame previews",
        "boss frames preview", "boss frames previews", "boss unit preview",
        "boss unit previews", "boss unitframe preview", "boss unitframe previews",
        "boss unit frame preview", "boss unit frame previews", "boss vorschau",
        "boss frames vorschau", "boss frame vorschau",
    },
        [257] = {
        "castbar", "cast bar", "castbars", "cast bars", "zauberleiste",
        "boss target", "target border", "target highlight",
    },
        [258] = { "mythic raid", "mythicraid", "mythic raid frame", "mythic raid frames", "mythicraid frame", "mythicraid frames" },
        [259] = { "raid", "raid frame", "raid frames", "raidframe", "raidframes", "schlachtzug" },
        [260] = { "party", "party frame", "party frames", "partyframe", "partyframes", "gruppe" },
        [261] = {
        "preview", "previews", "aura", "auras", "group preview", "group previews",
        "party preview", "party previews", "raid preview", "raid previews",
        "mythic raid preview", "mythic raid previews", "snap", "snapping",
        "grid", "grid lines", "grid spacing", "grid size", "raster", "raster groesse", "raster abstand",
        "rasterlinien", "hilfsraster", "background opacity",
        "background alpha", "bg opacity", "bg alpha", "background overlay",
        "hintergrund transparenz", "hintergrund deckkraft", "hintergrund overlay",
        "cdm", "cooldown manager", "anchor picker", "pick anchor", "select anchor",
        "ankerwahl", "anker auswahl", "reset", "undo", "redo",
    },
        [262] = { "preview", "previews", "preview mode", "preview modes", "vorschau", "platzhalter", "testdaten" },
        [263] = {
        "preview auras", "preview aura", "preview aura icons", "preview auras icons",
        "aura preview", "aura previews", "aura icon preview", "aura icon previews", "aura icons",
        "aura preview icons", "aura mover", "aura movers", "aura mover boxes",
        "auren vorschau", "vorschau auren", "auren symbole", "auren icons",
        "auren platzhalter", "aura platzhalter",
    },
        [264] = { "mover", "movers", "vorschau", "toggle", "umschalten" },
        [265] = { "auras", "aura", "auren" },
        [266] = { "toggle", "umschalten" },
        [267] = {
        "gf preview", "gf previews", "group frame preview", "group frame previews",
        "group frames preview", "group frames previews", "group preview", "group previews",
        "party frame preview", "party frame previews", "party frames preview",
        "party frames previews", "party preview", "party previews",
        "raid frame preview", "raid frame previews", "raid frames preview",
        "raid frames previews", "raid preview", "raid previews",
        "mythic raid frame preview", "mythic raid frame previews",
        "mythic raid frames preview", "mythic raid frames previews",
        "mythic raid preview", "mythic raid previews",
        "party raid preview", "party raid previews", "gruppenframes preview",
        "gruppenframes previews", "gruppen preview", "gruppen previews",
        "gruppenframes vorschau", "gruppen vorschau", "gruppe vorschau",
        "party vorschau", "raid vorschau", "schlachtzug vorschau",
    },
        [268] = {
        "gf", "group frame", "group frames", "party", "party frame", "party frames",
        "raid", "raid frame", "raid frames", "mythic raid", "mythicraid",
    },
        [269] = { "gf" },
        [270] = { "toggle", "umschalten" },
        [271] = {
        "edit mode preview", "edit mode previews", "unit preview", "unit previews",
        "unit frame preview", "unit frame previews", "unitframe preview", "unitframe previews",
        "preview frames", "preview frame", "frame preview", "frame previews",
        "mover preview", "mover previews", "placeholder data", "placeholder frame",
        "placeholder frames", "preview placeholders", "fake frame", "fake frames",
        "test frame", "test frames", "vorschau frames", "frame vorschau",
        "platzhalter", "platzhalter frames", "testdaten", "vorschau daten",
    },
        [272] = {
        "snap", "snapping", "grid snap", "snap frames", "snap to grid", "einrasten",
        "raster snap", "raster einrasten", "am raster ausrichten", "einrasten am raster", "rasterfang",
    },
        [273] = {
        "grid", "grid line", "grid lines", "grid overlay", "grid overlays",
        "edit mode grid", "raster", "raster lines", "rasterlinien", "hilfsraster",
    },
        [274] = { "edit mode grid", "msuf edit mode grid", "grid lines in edit mode", "raster groesse", "raster abstand", "rasterweite", "rasterlinien im bearbeitungsmodus" },
        [275] = {
        "grid", "grid spacing", "grid size", "grid step", "spacing", "space",
        "size", "groesse", "abstand", "rasterweite", "step", "pixel", "pixels", "px",
    },
        [276] = {
        "background opacity", "background alpha", "bg opacity", "bg alpha",
        "background overlay", "overlay opacity", "edit mode background", "edit mode bg",
        "hintergrund transparenz", "hintergrund deckkraft", "hintergrund alpha", "overlay transparenz",
    },
        [277] = { "edit mode background opacity", "edit mode bg opacity", "bearbeitungsmodus hintergrund transparenz", "bearbeitungsmodus hintergrund deckkraft" },
        [278] = {
        "cdm", "cooldown manager", "essential cooldown manager", "anchor to cooldown",
        "cooldown anchor", "cooldown manager anchor", "cooldownmanager", "cooldownmanager anker", "cdm anker",
    },
        [279] = {
        "anchor picker", "global anchor picker", "pick anchor", "select anchor",
        "choose anchor", "open anchor", "anker picker", "anker auswahl", "anker auswaehlen",
        "anker waehlen", "ankerwahl", "anker waehler",
    },
        [280] = {
        "custom anchor", "custom anchor picker", "custom anchor frame", "anchor frame picker",
        "status", "active", "is picker", "show picker",
    },
        [281] = { "global anchor picker", "anchor picker", "anker picker", "anker auswahl" },
        [282] = { "reset", "restore", "default", "zuruecksetzen", "zurucksetzen" },
        [283] = { "position", "selected frame", "current frame", "selected", "selection", "frame position", "mover", "auswahl", "ausgewaehlter frame", "aktueller frame", "rahmen position" },
        [284] = {
        "edit mode undo", "undo edit mode", "undo in edit mode", "undo last edit mode",
        "undo edit mode position", "undo last position", "undo position change",
        "undo last change", "undo edit mode change", "rueckgaengig", "rueckgaengig machen", "position rueckgaengig", "bearbeitungsmodus rueckgaengig",
    },
        [285] = {
        "edit mode redo", "redo edit mode", "redo in edit mode", "redo last edit mode",
        "redo edit mode position", "redo last position", "redo position change",
        "redo last change", "redo edit mode change", "wiederholen", "erneut anwenden", "bearbeitungsmodus wiederholen",
    },
        [286] = { "snap frames", "grid snap", "snap to grid", "raster snap", "raster einrasten" },
        [287] = {
        "clear no match telemetry", "clear nomatch telemetry", "clear assistant no match telemetry",
        "reset no match telemetry", "reset nomatch telemetry", "reset assistant misses",
        "clear unmatched commands", "clear missed commands",
        "loesche unbekannte befehle", "loesche nicht erkannte befehle",
        "leere nomatch telemetry", "leere no match telemetry", "assistant misses loeschen",
    },
        [288] = { "all no match", "all nomatch", "all missed", "all unmatched" },
        [289] = { "aura action", "aura actions", "aura workflow", "aura workflows" },
        [290] = { "aura", "auras", "buff", "buffs", "debuff", "debuffs" },
        [291] = { "anchor", "anchors", "anchoring", "cooldownmanager", "cooldown manager", "cdm" },
        [292] = { "registry", "registry alias", "aliases", "alias", "setting", "settings", "intent metadata" },
        [293] = { "media", "font", "texture", "sound", "sharedmedia" },
        [294] = { "knowledge", "help", "search", "faq", "where", "explain" },
        [295] = { "action", "actions", "workflow", "workflows", "copy", "profile", "preset" },
        [296] = { "parser", "triage", "generic" },
        [297] = { "all no match", "all nomatch", "all missed", "all unmatched" },
        [298] = { "unresolved", "open no match", "open nomatch", "open misses", "not resolved", "still failing" },
        [299] = { "needs clarification", "needs-clarification", "ambiguous no match", "ambiguous nomatch" },
        [300] = { "resolved", "fixed no match", "fixed nomatch", "solved no match", "covered no match" },
        [301] = { "all no match", "all nomatch", "all missed", "all unmatched" },
        [302] = { "high priority", "high-priority", "urgent no match", "urgent nomatch", "top priority", "top misses" },
        [303] = { "medium priority", "medium-priority", "normal priority" },
        [304] = { "low priority", "low-priority", "minor no match", "minor nomatch" },
        [305] = { "all no match", "all nomatch", "all missed", "all unmatched" },
        [306] = { "uncategorized", "untagged" },
        [307] = { "geometry tag", "geometry tagged", "geometry no match", "geometry misses", "movement no match", "movement misses", "layout no match", "layout misses" },
        [308] = { "media tag", "media tagged", "media no match", "media misses", "texture no match", "texture misses", "font no match", "font misses" },
        [309] = { "setting tag", "setting tagged", "setting no match", "setting misses", "control no match", "control misses" },
        [310] = { "scope tag", "scope tagged", "scope no match", "scope misses", "unit no match", "unit misses", "frame no match", "frame misses" },
        [311] = { "aura tag", "aura tagged", "aura no match", "aura misses", "buff no match", "debuff no match" },
        [312] = { "anchor tag", "anchor tagged", "anchor no match", "anchor misses" },
        [313] = { "action tag", "action tagged", "action no match", "action misses", "workflow no match", "workflow misses" },
        [314] = { "knowledge tag", "knowledge tagged", "knowledge no match", "knowledge misses", "help no match", "help misses" },
        [315] = {
        "no match worklist", "nomatch worklist", "assistant no match worklist",
        "assistant learning worklist", "learning worklist", "missed command worklist",
        "unmatched command worklist", "unmatched wording worklist",
        "alias review worklist", "alias worklist", "registry alias worklist",
        "registry alias candidates", "registry review candidates",
        "anchor review candidates", "anchor no match worklist", "anchor nomatch worklist",
        "aura review candidates", "aura no match worklist", "aura nomatch worklist",
        "knowledge review candidates", "knowledge no match worklist", "knowledge nomatch worklist",
        "media review candidates", "media no match worklist", "media nomatch worklist",
        "action review candidates", "action no match worklist", "action nomatch worklist",
        "geometry review candidates", "geometry no match worklist", "geometry nomatch worklist",
        "scope review candidates", "scope no match worklist", "scope nomatch worklist",
        "tagged no match worklist", "tagged nomatch worklist", "tagged misses",
        "show learning candidates", "show review candidates", "show alias candidates",
        "unbekannte befehle arbeitsliste", "nicht erkannte befehle arbeitsliste",
        "assistant arbeitsliste", "alias arbeitsliste", "fehlende aliases",
        "zeige unbekannte befehle", "zeige nicht erkannte befehle",
    },
        [316] = {
        "no match telemetry", "nomatch telemetry", "assistant no match telemetry",
        "assistant misses", "assistant missed commands", "missed commands",
        "unmatched commands", "unmatched wording", "show no match", "show nomatch",
        "assistant learning report", "learning report", "no match report",
        "unbekannte befehle", "nicht erkannte befehle", "nicht erkannte eingaben",
        "assistant lernbericht", "no match bericht", "nomatch bericht",
    },
        [317] = {
        "msuf status", "assistant status", "status report", "diagnostic report",
        "run checks", "run check", "run diagnostics", "health check", "run health check",
        "assistant support text", "support text", "support report", "support summary", "build support text", "make support text",
        "diagnostics", "diagnose", "diagnosen", "diagnose starten", "diagnosebericht", "debug summary", "debug report", "debug info", "debug bericht", "status bericht",
        "diagnostik", "fehlerbericht", "statusbericht", "diagnostik bericht",
        "assistant debug report", "version info", "locale info",
    },
        [318] = {
        "assistant help", "command help", "commands help", "help commands",
        "print help", "show help", "what can you do", "what settings can you change",
        "command examples",
    },
        [319] = {
        "edit mode", "editmode", "msuf edit mode", "bearbeitungsmodus", "bearbeitungs modus",
        "editmodus", "move frames", "drag frames", "position frames", "frames verschieben",
        "rahmen verschieben", "frames bewegen", "rahmen bewegen",
    },
        [320] = {
            "am i in edit mode", "is edit mode on", "is edit mode active", "edit mode status", "bearbeitungsmodus status", "ist bearbeitungsmodus an", "ist edit mode an",
            "why can't i exit edit mode", "why cant i exit edit mode", "why can not i exit edit mode",
            "why can't leave edit mode", "why cant leave edit mode",
            "bin ich im bearbeitungsmodus", "ist der bearbeitungsmodus aktiv", "ist editmodus aktiv",
            "warum kann ich bearbeitungsmodus nicht verlassen", "warum kann ich bearbeitungsmodus nicht beenden",
        },
        [321] = { "why can't", "why cant", "why can not", "warum kann" },
        [322] = { "cancel edit mode", "discard edit mode", "cancel msuf edit mode", "cancel all edit mode", "bearbeitungsmodus abbrechen", "edit mode abbrechen", "bearbeitungsmodus verwerfen", "editmodus abbrechen" },
        [323] = { "toggle edit mode", "toggle msuf edit mode", "bearbeitungsmodus umschalten", "edit mode umschalten", "editmodus umschalten", "bearbeitungsmodus toggeln" },
        [324] = {
            "stop edit mode", "exit edit mode", "exit msuf edit mode", "leave edit mode", "leave msuf edit mode",
            "close edit mode", "close msuf edit mode", "disable edit mode", "turn off edit mode", "edit mode off", "edit mode aus", "bearbeitungsmodus aus", "bearbeitungsmodus beenden", "bearbeitungsmodus verlassen", "bearbeitungsmodus deaktivieren",
            "editmodus aus", "editmodus beenden", "editmodus verlassen", "rahmen verschieben beenden",
        },
        [327] = { "recovery tools", "display recovery", "recover menu", "reset tools", "dashboard recovery" },
        [328] = { "scaling tools", "dashboard scaling", "scale tools", "ui scale tools", "open scaling" },
        [329] = { "changelog", "change log", "release notes", "latest changes", "build notes" },
        [330] = { "copy", "open", "link", "support", "join", "repo", "repository", "donate" },
        [331] = {
        "support links", "support msuf", "donate links", "development links",
        "hilfe links", "support link liste", "spenden links", "entwicklungs links",
    },
        [332] = { "1080p", "1080" },
        [333] = { "1440p", "1440" },
        [334] = { "4k", "2160p", "2160" },
        [335] = { "pixel perfect", "pixel" },
        [336] = { "auto" },
        [337] = { "turn off", "disable", "off" },
        [338] = { "preset", "scale preset" },
        [339] = { "preset", "global ui scale", "wow ui scale", "global scale", "scale preset", "ui preset", "ui scale preset" },
        [340] = { "global ui scale", "wow ui scale", "global scale", "scale preset", "ui preset", "ui scale preset" },
        [341] = { "preset", "panel", "section", "tools", "open", "close", "toggle" },
        [342] = {
        "msuf menu", "menu scale", "dashboard scale", "options menu", "config menu",
        "configuration menu", "assistant menu",
    },
        [343] = {
        "msuf frame scale", "msuf frames", "all msuf frames", "msuf ui scale",
        "unit frame scale", "unitframes scale", "frames globally", "all frames globally",
    },
        [344] = {
        "wow ui", "global ui", "global scale", "wow scale", "whole ui",
        "ui scale", "interface scale",
    },
        [345] = {
        "scale", "bigger", "larger", "smaller", "increase", "decrease", "raise", "lower",
        "grow", "shrink", "set", "make",
    },
        [346] = { "font", "fonts", "text style", "name color", "text color" },
        [347] = { "bars", "bar", "bar texture", "global bars", "gradient", "absorb", "highlight border", "dispel overlay", "aggro border", "purge border" },
        [348] = {
        "reset", "clear", "restore", "default", "defaults", "follow shared", "use shared",
        "remove override", "remove custom", "disable custom", "turn off custom",
    },
        [349] = {
        "all overrides", "every override", "all custom", "all scopes",
        "all bar overrides", "all bars overrides", "all global bar overrides", "all global bars overrides",
        "all font overrides", "all fonts overrides", "all global font overrides", "all global fonts overrides",
        "every bar override", "every bars override", "every font override", "every fonts override",
    },
        [350] = {
        "override", "overrides", "custom", "customized", "customised",
        "follow shared", "use shared", "remove override", "remove custom",
        "disable custom", "turn off custom",
    },
        [351] = {
        "preview resource", "resource preview", "preview class resource", "preview class resources",
        "preview class power", "preview class bar", "class resource preview", "class resources preview",
        "class power preview", "class bar preview", "class resource preview resource",
        "class power preview resource",
    },
        [352] = { "resource preview animation", "preview resource animation" },
        [353] = {
            "preview animation", "animate preview", "animate", "animation", "start preview", "stop preview",
            "play preview", "pause preview", "toggle preview animation", "start", "stop", "play", "pause",
        },
        [354] = { "preview", "animate", "animation" },
        [355] = { "stop", "pause", "off", "disable" },
        [356] = { "start", "play", "animate", "on", "enable" },
        [357] = { "toggle", "switch", "umschalten" },
        [358] = { "quick setup", "quicksetup", "setup" },
        [359] = { "crosshair", "fadenkreuz", "melee range spell", "range check spell", "nahkampf zauber", "reichweiten zauber" },
        [360] = { "spell", "zauber", "range check", "reichweite" },
        [361] = { "clear", "reset", "none", "no spell", "loeschen", "zuruecksetzen", "kein zauber", "ohne zauber" },
        [362] = { "preview", "test", "vorschau" },
        [363] = { "totem frame", "totemframe", "blizzard totem", "statue frame", "totem", "totems", "totem rahmen", "statuen rahmen", "statue rahmen" },
        [364] = { "reset", "restore", "default", "defaults", "zuruecksetzen", "zurucksetzen", "standard" },
        [365] = { "totem frame", "totemframe", "blizzard totem", "statue frame", "totem", "totems", "totem rahmen", "statuen rahmen", "statue rahmen" },
        [366] = { "dispel test type", "dispel border test type", "dispel border preview type", "dispel vorschau typ", "dispel border vorschau typ", "dispel rand vorschau typ" },
        [367] = { "curse" },
        [368] = { "disease" },
        [369] = { "poison" },
        [370] = { "bleed" },
        [371] = { "magic" },
        [372] = {
        "absorb bar", "absorb bars", "absorb test", "absorb test bar", "absorb test bars",
        "test absorb bar", "test absorb bars", "absorb prediction bar", "absorb prediction bars",
        "prediction bars", "heal absorb", "absorb vorschau", "absorb balken",
        "absorb balken test", "absorb balken vorschau", "heil absorb", "heal absorb vorschau",
    },
        [373] = { "absorb test", "prediction bar test", "absorb vorschau", "absorb balken", "absorb balken test", "absorb balken vorschau" },
        [374] = {
        "aggro border", "threat border", "aggro test border", "aggro border test",
        "threat test border", "threat border test", "border test aggro", "border test for aggro",
        "border test threat", "border test for threat", "aggro rand", "aggro rand test",
        "aggro rand vorschau", "bedrohung rand", "bedrohung rand test",
        "bedrohung rand vorschau", "bedrohungsrand",
    },
        [375] = {
        "dispel border", "dispellable border", "dispel test border", "dispel border test",
        "dispellable test border", "dispellable border test", "border test dispel",
        "border test for dispel", "border test dispellable", "border test for dispellable",
        "dispel rand", "dispel rand test", "dispel rand vorschau", "dispellable rand",
        "entzauber rand", "entzauber rand vorschau", "entzauberbar rand",
    },
        [376] = {
        "purge border", "purgeable border", "purge test border", "purge border test",
        "purgeable test border", "purgeable border test", "border test purge",
        "border test for purge", "border test purgeable", "border test for purgeable",
        "purge rand", "purge rand test", "purge rand vorschau", "purgeable rand",
        "offensiv dispel rand", "offensiv dispel rand vorschau",
    },
        [377] = {
        "boss target border", "boss target highlight", "boss target test border",
        "boss target border test", "boss target highlight test", "border test boss target",
        "border test for boss target", "boss ziel border", "boss ziel rand",
        "boss ziel rand test", "boss ziel rand vorschau", "bossziel rand",
    },
        [378] = { "dark mode", "dark bars", "dark bar", "dark mode bar color", "dark bar brightness" },
        [379] = {
        "lighter", "brighter", "brighten", "heller",
        "darker", "darken", "dunkler", "super dark", "very dark", "black", "almost black",
        "brightness", "bar color", "percent", "percentage", "slider", "value", "set", "make", "change", "adjust",
    },
        [380] = { "lighter", "brighter", "brighten", "heller", "darker", "darken", "dunkler" },
        [381] = {
        "to", "set", "value", "percent", "percentage", "slider", "brightness", "bar color", "make", "change", "adjust",
    },
        [382] = { "super dark", "very dark", "almost black", "black" },
        [383] = { "lighter", "brighter", "brighten", "heller" },
        [384] = { "bit", "a bit", "slightly", "little", "etwas" },
        [385] = { "darker", "darken", "dunkler" },
        [386] = { "bit", "a bit", "slightly", "little", "etwas" },
        [387] = { "shorten", "truncate", "truncation" },
        [388] = { "name", "names", "unit name", "unit names" },
        [389] = {
        "everything", "all names", "all unit names", "all unitframes", "all unitframe",
        "every unitframe", "every unitframes", "all frames", "every frame",
    },
        [390] = { "truncation style", "name truncation", "name clip side", "shortening side", "clip side" },
        [391] = { "left", "to left", "left side" },
        [392] = { "right", "to right", "right side" },
        [393] = { "castbar", "spell name", "spell names" },
        [394] = { "name", "names", "unit name", "unit names", "truncate", "truncation" },
        [395] = { "no dots", "without dots", "hide dots", "no ellipsis", "without ellipsis", "hide ellipsis" },
        -- Do not use "dots on" / "ellipsis on" here. In natural requests,
        -- "on" is commonly a location preposition ("dots on party frame"),
        -- not an enabled-state value. The owning parser resolves command
        -- polarity before scope wording.
        [396] = { "show dots", "with dots", "show ellipsis", "with ellipsis" },
        [397] = { "castbar", "spell name", "spell names" },
        [398] = { "test", "test mode", "testmode", "testmodus", "preview", "show preview", "vorschau", "zeige vorschau", "preview anzeigen" },
        [399] = { "castbar", "cast bar", "zauberleiste", "zauberleisten" },
        [400] = { "channel", "channeled", "channelled", "kanal", "kanalisiert" },
        [401] = { "empowered", "empower", "evoker", "verstaerkt", "verstaerken", "ermaechtigt", "ermaechtigen" },
        [402] = { "interrupt", "interrupted", "shake", "kick", "unterbrechen", "unterbrochen", "schuetteln", "schutteln" },
        [403] = { "castbar", "cast bar", "zauberleiste" },
        [404] = { "castbar", "cast bar", "zauberleiste", "zauberleisten" },
        [405] = { "target", "target castbar", "target cast bar", "ziel", "ziel castbar", "ziel zauberleiste" },
        [406] = {
        "other direction", "opposite direction", "opposite fill direction", "fill in the other direction",
        "fill the other direction", "other way", "opposite way", "reverse direction", "fill opposite", "opposite fill",
        "filling opposite", "fills opposite", "normal direction", "normal fill", "same direction", "same fill",
        "not opposite", "no opposite", "stop opposite", "stop filling opposite",
        "andere richtung", "entgegengesetzte richtung", "umgekehrte richtung", "andere fuellrichtung",
        "normal richtung", "normale richtung", "gleiche richtung", "gleiche fuellrichtung",
    },
        [407] = {
        "use opposite", "use opposite direction", "use opposite fill direction",
        "use target opposite", "use target opposite direction", "fill opposite", "opposite fill",
        "entgegengesetzte richtung", "umgekehrte richtung", "andere fuellrichtung",
    },
        [408] = {
        "normal direction", "normal fill", "same direction", "same fill",
        "not opposite", "no opposite", "stop opposite", "stop filling opposite",
        "normal richtung", "normale richtung", "gleiche richtung", "gleiche fuellrichtung",
    },
        [409] = { "stop", "clear", "remove", "aus", "deaktiviere", "beende" },
        [410] = { "opposite", "other way", "reverse", "entgegengesetzt", "umgekehrt" },
        [411] = {
        "help me build", "guided setup", "setup", "setup guide", "start guide", "start tour",
        "tour guide", "guide me", "show me around", "walk me through", "getting started",
        "start with msuf", "how do i start with msuf", "first time msuf", "new to msuf",
        "never used msuf", "never used this addon", "new user", "beginner guide",
        "beginner setup", "onboarding", "build a clean", "clean layout", "rogue layout",
        "layout bauen", "setup hilfe", "fuehre mich", "fuehr mich", "fuehrung",
        "einsteiger", "anfanger", "neu in msuf", "noch nie msuf", "zeig mir msuf",
        "hilf mir einrichten", "hilf mir beim einrichten", "einrichtungshilfe",
        "schritt fuer schritt", "fuehre mich durch msuf", "msuf einrichten",
        "assistant einrichtung", "assistent einrichtung",
    },
        [412] = {
        "cancel setup", "stop setup", "abort setup", "setup cancel",
        "finish setup", "done setup", "setup done", "complete setup", "setup complete",
        "skip setup", "skip setup step", "setup skip",
        "next setup", "next setup step", "setup next", "continue setup",
        "back setup", "back setup step", "setup back", "previous setup", "previous setup step", "setup previous",
        "show setup", "show setup step", "repeat setup", "current setup step", "setup status",
        "setup weiter", "weiter setup", "naechster setup schritt", "naechster schritt",
        "setup zurueck", "zurueck setup", "vorheriger setup schritt", "vorheriger schritt",
        "setup abbrechen", "einrichtung abbrechen", "setup fertig", "einrichtung fertig",
        "setup ueberspringen", "schritt ueberspringen", "setup anzeigen", "zeige setup",
        "setup wiederholen", "schritt wiederholen", "setup status",
    },
        [413] = { "cancel setup", "stop setup", "abort setup", "setup cancel", "setup abbrechen", "einrichtung abbrechen" },
        [414] = { "finish setup", "done setup", "setup done", "complete setup", "setup complete", "setup fertig", "einrichtung fertig" },
        [415] = { "skip setup", "skip setup step", "setup skip", "setup ueberspringen", "schritt ueberspringen" },
        [416] = { "next setup", "next setup step", "setup next", "continue setup", "setup weiter", "weiter setup", "naechster setup schritt", "naechster schritt" },
        [417] = { "back setup", "back setup step", "setup back", "previous setup", "previous setup step", "setup previous", "setup zurueck", "zurueck setup", "vorheriger setup schritt", "vorheriger schritt" },
        [418] = { "show setup", "show setup step", "repeat setup", "current setup step", "setup status", "setup anzeigen", "zeige setup", "setup wiederholen", "schritt wiederholen" },
        [419] = {
        "why this", "tell me more", "more details",
        "what is it for", "why this step", "what does this step do",
    },
        [420] = { "show examples", "show me examples", "example commands" },
        [421] = {
        "open it", "open this", "open that", "show me where", "take me there", "go there",
    },
        [422] = { "do it", "do that", "apply it", "use it", "run it" },
        [423] = {
        "backup before import", "backup before importing", "backup before profile import", "backup before importing profile",
        "make backup before import", "make a backup before import", "make backup before importing", "make a backup before importing",
    },
        [424] = { "custom anchor", "custom anchor picker", "anchor picker", "anchor settings" },
        [425] = { "aura", "auras", "buff", "debuff" },
        [426] = {
        "scale", "scaling", "frame scale", "raid scale", "party scale", "mythic raid scale",
        "players", "raider", "raiders", "people", "members", "player count", "raid size",
        "full raid", "when full", "large raid", "small raid", "five man", "5 man", "5m",
    },
        [427] = { "width", "wide", "wider", "narrow", "narrower" },
        [428] = { "x offset", "offset x", " x", "left", "right" },
        [429] = {
        "highlight tour", "highlights tour", "upgrade highlight tour", "upgrade highlights tour",
        "release highlight tour", "update highlight tour", "start upgrade highlights",
        "show upgrade highlights", "show update highlights again", "replay upgrade highlights",
        "highlight tour starten", "highlight tour neu starten", "highlights tour starten",
        "upgrade highlights starten", "upgrade tour neu starten", "tour der highlights",
    },
        [430] = {
        "restart the tour", "restart tour", "start the tour again", "start tour again",
        "replay the tour", "replay tour", "show the tour again",
        "tour neu starten", "tour nochmal starten", "tour wieder starten",
        "tour erneut starten", "tour wiederholen", "zeige die tour nochmal",
    },
    },
}
