-- Assistant actions parser data.
-- Generated phrase lists for MSUF_AssistantParser_Actions.lua.
local addonName, MSUF = ...
MSUF = MSUF or _G.MSUF_NS or {}

local M = MSUF.MSUF2 or _G.MSUF2 or {}
MSUF.MSUF2 = M

local A = MSUF.Assistant or {}
MSUF.Assistant = A
M.Assistant = A

local Data = A.ParserData or {}
A.ParserData = Data

Data.ACTIONS_PARSER = {
    PHRASES = {
        [1] = {
                "group setting", "group settings", "group frame setting", "group frame settings",
                "group frames", "group frame", "party setting", "party settings",
                "raid setting", "raid settings", "mythic raid setting", "mythic raid settings",
            },
        [2] = { "all", "alle" },
        [3] = { "all", "alle" },
        [4] = { "reset", "restore", "zuruecksetzen", "zurucksetzen", "default", "defaults", "werksreset", "werkseinstellungen", "vollreset" },
        [5] = {
        "group", "groups", "group frame", "group frames", "group status", "group icon", "group icons",
        "party", "party frame", "party frames", "raid", "raid frame", "raid frames", "mythic raid",
    },
        [6] = { "anchor", "anchor point", "anchor position", "position dropdown", "anker", "ankerpunkt", "anker position" },
        [7] = {
        "to top", "to the top", "to bottom", "to the bottom", "to left", "to the left", "to right", "to the right",
        "on top", "on the top", "on bottom", "on the bottom", "on left", "on the left", "on right", "on the right",
        "top left", "top right", "bottom left", "bottom right", "upper left", "upper right", "lower left", "lower right",
        "above frame", "above the frame", "over frame", "over the frame", "below frame", "below the frame", "under frame", "under the frame",
        "left side", "right side", "right of name", "left of name", "right to name", "left to name",
    },
        [8] = { "put", "place", "set", "move", "position", "stick", "keep" },
        [9] = { "above", "over", "below", "under" },
        [10] = { "frame", "frames", "unitframe", "unit frame", "group frame", "group frames" },
        [11] = { "put", "place", "set", "move", "position", "stick", "keep" },
        [12] = { "above frame", "above the frame", "over frame", "over the frame" },
        [13] = { "above", "over" },
        [14] = { "frame", "frames", "unitframe", "unit frame", "group frame", "group frames" },
        [15] = { "below frame", "below the frame", "under frame", "under the frame" },
        [16] = { "below", "under" },
        [17] = { "frame", "frames", "unitframe", "unit frame", "group frame", "group frames" },
        [18] = { "spell indicator", "spell indicators", "tracked spell", "tracked spells", "zauber indikator", "zauber indikatoren", "zauberindikator", "zauberindikatoren", "verfolgte zauber" },
        [19] = { "multi spec", "multispec", "track selected multi spec", "track spec", "mehrere specs", "spec verfolgen" },
        [20] = { "remove", "clear", "stop", "entfernen", "loeschen", "deaktivieren" },
        [21] = { "reset", "restore", "default", "defaults", "zuruecksetzen", "zurucksetzen" },
        [22] = { "move", "order", "reorder", "first", "last", "slot", "position", "verschiebe", "reihenfolge", "erste", "letzte" },
        [23] = { "first", "top", "front", "erste", "oben", "vorne" },
        [24] = { "last", "bottom", "end", "letzte", "unten", "ende" },
        [25] = { "only my cast", "only mine", "own cast", "cast by me", "nur meine", "nur eigener", "von mir" },
        [26] = { "cooldown text size", "cooldown font size" },
        [27] = { "cooldown swipe" },
        [28] = { "cooldown text", "show cooldown" },
        [29] = { "show when missing", "when missing", "missing indicator", "anzeigen wenn fehlt", "wenn fehlt", "fehlend anzeigen" },
        [30] = { "bar width", "balken breite" },
        [31] = { "growth", "grow", "wachstum", "richtung" },
        [32] = { "frame color", "effect color", "tint color", "glow color", "border color" },
        [33] = { "frame effect", "effect type", "frame type", "frame effekt", "effekt typ" },
        [34] = { "frame priority", "effect priority", "priority", "prioritaet" },
        [35] = { "tint alpha", "frame alpha", "effect alpha", "effekt alpha", "deckkraft" },
        [36] = { "thickness", "border thickness", "glow thickness", "dicke", "staerke", "rand dicke" },
        [37] = { "indicator type", "placed indicator", "placed type", "type", "indikator typ", "anzeige typ", "typ" },
        [38] = { "anchor", "anker", "position" },
        [39] = { "x offset", "x position", "x" },
        [40] = { "y offset", "y position", "y" },
        [41] = { "size", "icon size", "groesse", "symbol groesse" },
        [42] = {
        "corner indicator", "corner indicators", "corner dot", "corner dots",
        "ecken indikator", "ecken indikatoren", "eckenindikator", "eckenindikatoren", "ecken punkt", "ecken punkte",
    },
        [43] = {
        "corner", "ecke", "custom", "spell ids", "spell id", "zauber ids", "zauber id",
        "mode", "modus", "filter", "missing", "fehlend", "fehlt", "present", "vorhanden",
    },
        [44] = { "filter", "aura filter", "hilfreich", "schaedlich", "harmful", "helpful", "buff", "debuff" },
        [45] = { "mode", "modus", "when", "wenn", "missing", "fehlend", "fehlt", "present", "vorhanden" },
        [46] = { "spell ids", "spell id", "custom spells", "custom spell ids", "zauber ids", "zauber id" },
        [47] = { "color", "colour", "farbe" },
        [48] = { "alpha", "opacity", "deckkraft", "transparenz" },
        [49] = { "size", "groesse", "icon size", "punkt groesse" },
        [50] = { "reset", "restore", "default", "defaults", "zuruecksetzen" },
        [51] = { "corner indicator", "corner indicators", "corner dot", "corner dots", "custom spell", "ecken indikator", "ecken indikatoren", "eckenindikator", "eckenindikatoren", "ecken punkt", "custom zauber", "eigener zauber" },
        [52] = { "reset", "restore", "default", "defaults", "zuruecksetzen" },
        [53] = { "selected status indicator", "selected status icon", "current status indicator", "current status icon", "unit status indicator", "unit status icon" },
        [54] = { "preview", "show all", "current indicator", "all indicators", "all status icons", "test", "test mode", "preview mode" },
        [55] = { "selected status indicator", "selected status icon", "current status indicator", "current status icon", "unit status indicator", "unit status icon" },
        [56] = { "show all", "all indicators", "all status icons", "preview all" },
        [57] = {
        "layer down", "down layer", "move layer down", "drop layer",
        "behind", "backward", "backwards", "send back", "to back", "lower layer", "lower draw",
        "below", "back", "down", "lower", "hinter", "nach hinten", "runter",
    },
        [58] = {
        "layer up", "up layer", "move layer up", "raise layer",
        "forward", "front", "to front", "bring forward", "higher layer", "higher draw",
        "above", "up", "higher", "nach vorne", "hoch",
    },
        [59] = { "all group frames", "all groups", "every group frame", "each group frame", "for all group frames", "alle gruppen", "alle gruppenframes" },
        [60] = { "x offset", "offset x", "horizontal offset", "y offset", "offset y", "vertical offset" },
        [61] = {
        "dead text dead units", "status text dead units", "show dead text for dead",
        "dead text ghost units", "status text ghost units", "show ghost text",
        "dead text afk", "status text afk", "show afk text",
        "dead text dnd", "status text dnd", "show dnd text",
    },
        [62] = { "status icon", "status icons", "status indicator", "status indicators" },
        [63] = { "preview", "test", "test mode", "preview mode" },
        [64] = { "turn on", "turn off", "enable", "disable", "hide", "show midnight", "classic style", "midnight style" },
        [65] = { "role icon", "role icons", "role indicator", "role indicators", "role symbol", "role symbols" },
        [66] = { "tank", "tanks", "tank role", "tank players" },
        [67] = { "healer", "healers", "heal role", "healer role" },
        [68] = { "dps", "damage dealer", "damage dealers", "damager", "damagers", "damage role" },
        [69] = { "classic style", "classic icons", "classic status icons" },
        [70] = { "midnight style", "midnight icons", "midnight status icons" },
        [71] = { "hide", "disable", "disabled", "turn off", "off", "remove" },
        [72] = { "show", "enable", "enabled", "turn on", "on", "display" },
        [73] = { "role icon style", "indicator style", "icon design", "icon pack", "icon style" },
        [74] = { "move", "nudge", "shift", "verschiebe" },
        [75] = { "anchor", "anchor point", "anchor position", "position dropdown" },
        [76] = { "x offset", "offset x", "horizontal offset" },
        [77] = { "y offset", "offset y", "vertical offset" },
        [78] = { "move", "nudge", "shift", "position", "verschiebe" },
        [79] = { "layer", "draw layer", "frame level", "strata", "frame strata", "behind", "forward", "front", "backward", "backwards", "ebene", "zeichenebene" },
        [80] = { "size", "icon size", "indicator size", "symbol size", "scale", "bigger", "larger", "smaller", "increase", "decrease", "reduce", "grow", "shrink", "groesse", "grosse", "symbol groesse", "icon groesse", "groesser", "kleiner" },
        [81] = { "move", "nudge", "shift", "offset", "position", "verschiebe" },
        [82] = { "selected status indicator", "selected status icon", "current status indicator", "current status icon" },
        [83] = {
        "selected status indicator", "selected status icon", "current status indicator", "current status icon",
        "unit status indicator", "unit status icon", "status indicator", "status icon",
    },
        [84] = { "reset", "restore", "default", "defaults", "zuruecksetzen" },
        [85] = { "preview", "show all", "current indicator", "all indicators", "all status icons" },
        [86] = { "show all", "all indicators", "all status icons", "preview all" },
        [87] = { "status icon", "status icons", "status indicator", "status indicators" },
        [88] = { "classic style", "classic icon", "classic icons", "classic status icon", "classic status icons" },
        [89] = { "midnight style", "midnight icon", "midnight icons", "midnight status icon", "midnight status icons" },
        [90] = { "role icon style", "indicator style", "icon design", "icon pack", "icon style" },
        [91] = { "anchor", "anchor point", "anchor position", "position dropdown" },
        [92] = { "move", "nudge", "shift", "verschiebe" },
        [93] = { "anchor", "anchor point", "anchor position", "position dropdown" },
        [94] = { "layer", "draw layer", "frame level", "strata", "frame strata", "behind", "forward", "front", "backward", "backwards" },
        [95] = { "x offset", "offset x", "horizontal offset" },
        [96] = { "y offset", "offset y", "vertical offset" },
        [97] = { "move", "nudge", "shift", "offset", "position", "verschiebe" },
        [98] = { "size", "font size", "text size", "icon size", "indicator size", "symbol size", "scale", "groesse" },
        [99] = { "move", "nudge", "shift", "offset", "position", "verschiebe" },
        [100] = { "custom anchor", "custom anchor picker", "anchor picker", "anchor frame picker", "anker picker" },
        [101] = { "cancel", "close", "stop", "abort" },
        [102] = { "status", "active", "is picker", "show picker" },
        [103] = { "pick", "picker", "start", "open", "select", "choose" },
        [104] = { "where", "where is", "where are", "how", "help", "settings", "setting" },
        [105] = { "custom anchor", "custom anchor frame", "anchor frame name" },
        [106] = { "set", "change", "use", "assign", "write", "apply" },
        [107] = { "clear", "remove", "reset", "restore", "default", "defaults", "zuruecksetzen" },
        [108] = { "custom anchor", "custom anchor frame", "anchor frame name" },
        [109] = { "reset", "restore", "zuruecksetzen", "zurucksetzen", "default", "defaults", "werksreset", "werkseinstellungen", "vollreset" },
        [110] = { "factory reset", "full reset", "fullreset", "reset all settings", "reset all profiles", "werksreset", "werkseinstellungen", "vollreset", "alles zuruecksetzen", "alle einstellungen zuruecksetzen", "alle profile zuruecksetzen" },
        [111] = { "profile", "profil" },
        [112] = {
        "focus kick", "focus interrupt tracker", "focus interrupt", "kick tracker",
        "fokus kick", "fokus interrupt tracker", "fokus interrupt", "kick anzeige",
        "fokus kick anzeige", "fokus kick tracker", "fokus interrupt anzeige",
    },
        [113] = { "position", "pos", "placement", "x", "y", "platzierung", "stelle" },
        [114] = { "all positions", "frame positions", "reset positions", "reset movers", "offscreen", "off screen", "broken layout", "alle positionen" },
        [115] = { "position", "pos", "placement", "frame position", "x", "y" },
        [116] = { "open", "go to", "show settings", "show me", "find", "search", "where", "where is", "where are", "wo", "oeffne" },
        [117] = { "settings", "menu", "page", "options", "config", "configuration", "einstellungen", "menue", "seite" },
        [118] = { "recovery tools", "display recovery", "recover menu", "reset tools", "dashboard recovery", "recovery panel", "recovery section", "display panel", "wiederherstellung", "wiederherstellungs tools", "anzeige reparatur", "anzeigereparatur", "reparatur tools", "rettungswerkzeuge" },
        [119] = {
        "scaling tools", "dashboard scaling", "scale tools", "ui scale tools", "scaling panel", "scale panel",
        "scale section", "scaling section", "ui scaling panel", "ui scaling section", "menu scale", "menu scaling", "skalierung", "skalierungs tools", "skalierungswerkzeuge", "ui skalierung", "menue skalierung",
        "menu bigger", "menu smaller", "make menu bigger", "make menu smaller", "options scale", "options scaling",
        "ui scale", "ui scaling", "msuf frame scale", "msuf frames scale",
    },
        [120] = { "changelog", "change log", "release notes", "latest changes", "build notes", "changelog panel", "aenderungen", "aenderungslog", "versionshinweise", "neuerungen" },
        [121] = { "open", "show", "close", "hide", "collapse", "expand", "toggle", "oeffne", "oeffnen", "anzeigen", "schliessen", "verstecken", "ausblenden", "einklappen", "aufklappen", "umschalten" },
        [122] = { "dashboard panel", "dashboard panels" },
        [123] = { "close", "hide", "collapse", "schliessen", "verstecken", "ausblenden", "einklappen" },
        [124] = { "toggle", "umschalten" },
        [125] = { "close", "hide", "collapse", "schliessen", "verstecken", "ausblenden", "einklappen" },
        [126] = { "toggle", "umschalten" },
        [127] = { "search intro", "ask msuf intro", "assistant search intro", "search help intro", "such intro", "suche intro", "suchhilfe intro", "ask msuf einfuehrung" },
        [128] = { "hide", "close", "dismiss", "mark seen", "mark as seen", "mark search intro seen", "dont show", "ausblenden", "verstecken", "schliessen", "als gesehen markieren", "nicht anzeigen" },
        [129] = { "reset", "show again", "next time", "zuruecksetzen", "wieder anzeigen", "naechstes mal" },
        [130] = { "show", "open", "anzeigen", "oeffnen", "oeffne" },
        [131] = { "navigation section", "nav section", "sidebar section", "left nav section", "section", "navigation group", "nav group", "sidebar group", "navigations sektion", "nav sektion", "seitenleiste", "seitenleisten bereich", "sektion", "bereich", "navigation gruppe" },
        [132] = { "open", "show", "close", "hide", "collapse", "expand", "toggle", "oeffne", "oeffnen", "anzeigen", "schliessen", "verstecken", "ausblenden", "einklappen", "aufklappen", "umschalten" },
        [133] = { "close", "hide", "collapse", "schliessen", "verstecken", "ausblenden", "einklappen" },
        [134] = { "toggle", "umschalten" },
        [135] = { "panel", "tools", "changelog", "change log", "release notes", "werkzeuge", "aenderungen", "versionshinweise" },
        [136] = { "menu", "menue", "dashboard", "options", "optionen", "options window", "msuf menu", "msuf menue", "msuf window", "msuf fenster", "fenster" },
        [137] = { "restore", "unminimize", "unminimise", "show minimized", "wiederherstellen", "minimierung aufheben" },
        [138] = { "minimize", "minimise", "collapse", "minimieren", "einklappen" },
        [139] = { "maximize", "maximise", "fullscreen", "full screen", "maximieren", "vollbild" },
        [140] = { "close", "hide", "schliessen", "verstecken", "ausblenden" },
        [141] = {
        "menu history", "menu change", "menu changes", "menu session", "session changes",
        "msuf2 menu changes", "ui change", "ui changes", "navrail history",
        "assistant change", "assistant changes", "assistant session", "assistant edits", "menue verlauf", "menue aenderung", "menue aenderungen", "menue sitzung", "sitzungs aenderungen", "ui aenderung", "ui aenderungen", "assistant aenderung", "assistant aenderungen",
    },
        [142] = { "assistant change", "assistant changes", "assistant session", "assistant edits", "assistant aenderung", "assistant aenderungen" },
        [143] = { "redo", "reapply", "wiederholen", "erneut anwenden" },
        [144] = { "assistant change", "assistant changes", "assistant session", "assistant edits", "assistant aenderung", "assistant aenderungen" },
        [145] = { "undo", "revert", "rueckgaengig", "zuruecknehmen" },
        [146] = { "reset all", "reset", "restore all", "discard all", "revert all", "clear all", "zuruecksetzen", "zurucksetzen", "alles zuruecksetzen", "alle zuruecksetzen", "verwerfen", "alles verwerfen" },
        [147] = { "redo", "reapply", "wiederholen", "erneut anwenden" },
        [148] = { "undo", "revert", "rueckgaengig", "zuruecknehmen" },
        [149] = { "import", "export", "profile string", "copy", "backup", "reset", "open", "diagnose", "test" },
        [150] = {
        "width", "height", "size", "scale", "font size", "text size",
        "x offset", "y offset", "offset", "spacing", "alpha", "opacity",
        "breite", "hoehe", "groesse", "schriftgroesse", "text groesse",
    },
        [151] = {
        "player", "target", "focus", "pet", "boss", "party", "raid", "mythic",
        "frame", "unit", "castbar", "cast bar", "aura", "auras", "buff", "buffs", "debuff", "debuffs",
        "name", "health", "hp", "power", "mana", "text", "spieler", "ziel", "fokus",
    },
        [152] = { "aura editing scope", "editing aura scope", "aura scope", "edit aura scope" },
        [153] = { "set", "change" },
        [154] = { "to shared", "to player", "to target", "to focus", "to boss", "to party", "to raid" },
        [155] = { "aura blacklist spell", "blacklist spell", "selected aura blacklist spell", "aura spell preset" },
        [156] = { "set", "change" },
        [157] = { " to ", " as ", " = " },
        -- Navigation verbs that only mean navigation when the sentence states
        -- no value. "edit target auras" is a request to be taken to that page,
        -- but "edit target buff size to 30" is a change, so ParseOpen consults
        -- this list behind the same no-boolean/no-number guard the bare-noun
        -- shortcut uses.
        [158] = { "edit", "customize", "customise", "bearbeite", "bearbeiten", "anpassen" },
        -- Subjects narrower than a whole unit page. Their presence means the
        -- reset request is about one part of the frame, so the page-wide reset
        -- fallback must not claim it.
        [159] = {
            "aura", "auras", "buff", "buffs", "debuff", "debuffs", "override", "overrides",
            "castbar", "cast bar", "portrait", "text", "font", "color", "colour", "farbe",
            "name", "health", "power", "mana", "absorb", "shield",
            "size", "width", "height", "scale", "opacity", "alpha", "transparency",
            "border", "outline", "texture", "gradient", "icon", "icons",
            "indicator", "indicators", "filter", "filters", "highlight",
        },
    },
}
