---@type string, Addon
local _, addon = ...

-- GENERATED by scripts/GenerateArtTextures.py from the community listfile. Do not edit by
-- hand: re-run the script instead.
--
-- Every row is { file id, label, path }. The id is what draws, because ids outlive the paths
-- that name them. The path is what the client is asked about at load, so art a build never
-- shipped is dropped rather than offered as an empty square.

---@class ArtTextureData
local M = {}

addon.Core.ArtTextureData = M

-- The art the game flashes around the screen when a proc lands.
M.Alerts = {
	{ 460830, "Backlash", [[Textures/SpellActivationOverlays/Backlash.blp]] },
	{ 801266, "Backlash Green", [[Textures/SpellActivationOverlays/Backlash_Green.blp]] },
	{ 449487, "Blood Surge", [[Textures/SPELLACTIVATIONOVERLAYS/BLOOD_SURGE.BLP]] },
	{ 449488, "Brain Freeze", [[Textures/SpellActivationOverlays/BRAIN_FREEZE.BLP]] },
	{ 459313, "Daybreak", [[Textures/SpellActivationOverlays/DAYBREAK.BLP]] },
	{ 449489, "Frozen Fingers", [[Textures/SpellActivationOverlays/FROZEN_FINGERS.BLP]] },
	{ 467696, "Fulmination", [[Textures/SpellActivationOverlays/Fulmination.blp]] },
	{ 460831, "Fury Of Stormrage", [[Textures/SpellActivationOverlays/Fury_of_Stormrage.blp]] },
	{ 459314, "Hand Of Light", [[Textures/SpellActivationOverlays/Hand_of_Light.blp]] },
	{ 450927, "Maelstrom Weapon", [[Textures/SPELLACTIVATIONOVERLAYS/Maelstrom_Weapon.blp]] },
	{ 1028136, "Maelstrom Weapon 1", [[Textures/SPELLACTIVATIONOVERLAYS/Maelstrom_Weapon_1.blp]] },
	{ 1028137, "Maelstrom Weapon 2", [[Textures/SPELLACTIVATIONOVERLAYS/Maelstrom_Weapon_2.blp]] },
	{ 1028138, "Maelstrom Weapon 3", [[Textures/SPELLACTIVATIONOVERLAYS/Maelstrom_Weapon_3.blp]] },
	{ 1028139, "Maelstrom Weapon 4", [[Textures/SPELLACTIVATIONOVERLAYS/Maelstrom_Weapon_4.blp]] },
	{ 898423, "Predatory Swiftness", [[Textures/SpellActivationOverlays/Predatory_Swiftness.blp]] },
	{ 1518303, "Predatory Swiftness Green", [[Textures/SPELLACTIVATIONOVERLAYS/Predatory_Swiftness_Green.blp]] },
	{ 450930, "Rime", [[Textures/SpellActivationOverlays/Rime.blp]] },
	{ 469752, "Serendipity", [[Textures/SpellActivationOverlays/Serendipity.blp]] },
	{ 627609, "Shadow Of Death", [[Textures/SpellActivationOverlays/Shadow_of_Death.blp]] },
	{ 463452, "Shooting Stars", [[Textures/SpellActivationOverlays/Shooting_Stars.blp]] },
	{ 774420, "Tooth And Claw", [[Textures/SpellActivationOverlays/Tooth_and_Claw.blp]] },
}

---@class ArtTextureData
---@field Alerts table[]
