if (GetLocale() ~= "zhTW") then
	return;
end
-- New Options
-- @EXACT = false
VUHDO_I18N_SCANNERS = "掃描";
VUHDO_I18N_RESURRECT_SHORT = "復活";
VUHDO_I18N_GENERAL = "一般";
VUHDO_I18N_CONFIG = "設定";
VUHDO_I18N_REBUFF = "補上增益";
VUHDO_I18N_FORMAT = "格式";
VUHDO_I18N_BUFF_NAMES = "增益名稱";
VUHDO_I18N_STATES = "狀態";
VUHDO_I18N_CD_FLASHING = "冷卻閃爍";
VUHDO_I18N_TIMERS = "時間";
VUHDO_I18N_WHATEVER_FIRST = "... 或... (看哪個時間先到)";
VUHDO_I18N_MODES = "模式";
VUHDO_I18N_EMERGENCY_MODE = "緊急模式";
VUHDO_I18N_NORMAL_MODE = "普通模式";
VUHDO_I18N_RANGE = "範圍";
VUHDO_I18N_ADD_NEW_PANEL = "新增面板";
VUHDO_I18N_HOLD_TO_TEST = "按住來測試";
VUHDO_I18N_OWN_HOTS = "我的持續性治療";
VUHDO_I18N_LOSE = "損失";
VUHDO_I18N_ORDERING = "排列順序";
VUHDO_I18N_HIDE_EMPTY = "隱藏空的";
VUHDO_I18N_ANCHOR = "對齊";
VUHDO_I18N_UNIT_ID = "單位 ID";
VUHDO_I18N_HEADER_TEXT = "標題文字";
VUHDO_I18N_TOOLTIPS = "浮動提示";
VUHDO_I18N_SIZING = "大小";
VUHDO_I18N_BUTTON_SIZE = "按鈕大小";
VUHDO_I18N_PERCENT = "百分比";
VUHDO_I18N_MISSING = "缺少";
VUHDO_I18N_REMAINING = "剩餘";
VUHDO_I18N_HITPOINTS = "補血點";
VUHDO_I18N_BAR_TEXT = "條列文字";
VUHDO_I18N_MAX_BUFFS_PER_ROW = "每列最多增益數量";
VUHDO_I18N_REFRESH_RATE = "更新頻率";
VUHDO_I18N_INDICATE_REBUFF_BELOW = "低於時要補上增益";
VUHDO_I18N_SIZE = "大小";
VUHDO_I18N_TEXTURE_NUM = "材質 #";
VUHDO_I18N_TEXT_SIZE = "文字大小";
VUHDO_I18N_X_SPACING = "水平間距";
VUHDO_I18N_Y_SPACING = "垂直間距";
VUHDO_I18N_X_GAP = "水平空隙";
VUHDO_I18N_Y_GAP = "垂直空隙";
-- General Labels
-- @EXACT = false
VUHDO_I18N_CANCEL = "取消";
VUHDO_I18N_SHOW = "顯示";
VUHDO_I18N_BARS = "條列"
VUHDO_I18N_COLOR = "顏色";
VUHDO_I18N_COLORS = "顏色";
VUHDO_I18N_GENERAL_SHORT = "一般";
VUHDO_I18N_CUSTOM = "自訂";
VUHDO_I18N_MOUSE = "滑鼠";
VUHDO_I18N_STANDARD = "標準";
VUHDO_I18N_POSITION = "位置";
VUHDO_I18N_SCALE = "縮放";
VUHDO_I18N_ENABLE = "啟用";
VUHDO_I18N_BACKGROUND = "背景";
VUHDO_I18N_GROUPED = "分組";
VUHDO_I18N_SORT_BY = "排序方式...";
VUHDO_I18N_NAME = "名字";
VUHDO_I18N_MAX_HP = "最大血量";
VUHDO_I18N_MAX_COLUMNS = "最大直行數";
VUHDO_I18N_MAX_ROWS = "最大橫列數";
VUHDO_I18N_CLEAR_PANELS_CONFIRM = "是否要清空面板模組?!\n確定嗎?";
VUHDO_I18N_BUFF_NAME = "增益名稱";
VUHDO_I18N_BUFF_ON_PLAYER = "在玩家名稱:";
VUHDO_I18N_ALWAYS = "永遠";
VUHDO_I18N_BUFF_PANEL_BG = "面板";
-- VuhDoOptionsGeneral.lua
-- @EXACT = false
VUHDO_I18N_CLEANSE = "驅散";
VUHDO_I18N_RESURRECT = "復活";
VUHDO_I18N_SMART_CAST_OO_COMBAT = "智慧型施法";
VUHDO_I18N_IGNORE_IRRELEVANT = "忽略不要緊的 ...";
VUHDO_I18N_BY_CLASS = "職業";
VUHDO_I18N_MOVEMENT_IMPAIRING = "移動";
VUHDO_I18N_BY_DURATION = "持續時間";
VUHDO_I18N_BY_NON_HARMFUL = "無害";
VUHDO_I18N_REMOVABLE_ONLY = "可驅散";
--VUHDO_I18N_ESTIMATE = "Guess";
VUHOD_I18N_BY_SPELL = "法術";
VUHDO_I18N_SHOW_INC = "即將治療";
VUHDO_I18N_SHOW_OWN_HEAL = "我的";
VUHDO_I18N_SHOW_OVERHEAL = "過量治療";
VUHDO_I18N_OPERATION_MODE = "顯示模式";
VUHDO_I18N_MAX_EMERGENCIES = "最緊急";
VUHDO_I18N_RELVEVANCE = "超過則不要緊";
VUHDO_I18N_NEUTRAL_HEALBOT = "一般";
VUHDO_I18N_EMERGENCY_PERCENT = "緊急 - 血量 %";
VUHDO_I18N_EMERGENCY_MOST_MISSING = "最大缺少血量";
VUHDO_I18N_EMERGENCY_LEAST_LEFT = "至少剩餘血量";
-- VuhDoFormButtonColor.lua
-- @EXACT = false
-- Labels
VUHDO_I18N_TEXT = "文字";
VUHDO_I18N_ANOMALIES = "異常";
VUHDO_I18N_OPACITY = "不透明度";
-- VuhDoFormButtonSize.lua
-- @EXACT = false
VUHDO_I18N_PANEL = "面板";
VUHDO_I18N_SPACING = "間距";
VUHDO_I18N_BAR_HEIGHT = "條列高度";
VUHDO_I18N_TARGETS = "目標";
VUHDO_I18N_BAR_TEXTURE = "條列材質";
VUHDO_I18N_BAR_WIDTH = "條列寬度";
VUHDO_I18N_WIDTH = "寬度";
VUHDO_I18N_HEADERS = "標題";
VUHDO_I18N_CLASS_COL = "職業顏色";
--
-- VuhDoOptionsSpell.lua
-- @EXACT = false
VUHDO_I18N_KEY_MODIFIES = "組合按鍵";
VUHDO_I18N_KEY_NONE = "無";
VUHDO_I18N_ALT = "Alt";
VUHDO_I18N_CTRL = "Ctrl";
VUHDO_I18N_SHIFT = "Shift";
VUHDO_I18N_LEFT_BUTTON = "左鍵";
VUHDO_I18N_RIGHT_BUTTON = "右鍵";
VUHDO_I18N_MIDDLE_BUTTON = "中鍵";
VUHDO_I18N_BUTTON_4 = "按鍵 4";
VUHDO_I18N_BUTTON_5 = "按鍵 5";
VUHDO_I18N_MOUSE_KEY = "滑鼠按鍵";
VUHDO_I18N_IN_MACROS_USE = "(在巨集中使用 \"vuhdo\" 代替目標名字)";
VUHDO_I18N_SPELL_STATIC = "或 target/focus/assist/menu/tell/dropdown";
VUHDO_I18N_NAME_TIP = "輸入法術名稱、巨集或物品，";
VUHDO_I18N_PLUS_SHIFT = "+Shift";
VUHDO_I18N_PLUS_CTRL_SHIFT = "+Ctrl+Shift";
VUHDO_I18N_PLUS_CTRL = "+Ctrl";
-- VuhDoTooltipConfig.lua
-- @EXACT = false
VUHDO_I18N_AROUND_PANEL = "面板周圍";
VUHDO_I18N_SHOW_IN_FIGHT = "戰鬥中";
-- New Options - Tooltips
-- @EXACT = false
VUHDO_I18N_TT = { };
VUHDO_I18N_TT.K001 = "設定要 VuhDo 幫忙處理的增益。";
VUHDO_I18N_TT.K002 = "選擇增益監控面板的一般外觀。";
VUHDO_I18N_TT.K003 = "選擇增益色塊和不同時間狀態的顏色。";
VUHDO_I18N_TT.K004 = "調整計時器設定和選擇增益版本。";
VUHDO_I18N_TT.K005 = "調整 Vuhdo 增益監控的一般大小。";
VUHDO_I18N_TT.K007 = "設定每行顯示增益數量的最大值。";
VUHDO_I18N_TT.K008 = "選擇增益色塊的更新頻率。";
VUHDO_I18N_TT.K009 = "標題中顯示增益名稱。";
VUHDO_I18N_TT.K011 = "啟用增益監控。";
VUHDO_I18N_TT.K012 = "選擇增益持續時間充裕的顏色。";
VUHDO_I18N_TT.K013 = "選擇增益持續時間快結束的顏色。";
VUHDO_I18N_TT.K014 = "選擇缺少增益 (或部分缺少) 的顏色。";
VUHDO_I18N_TT.K015 = "選擇所有要施放增益的對象都超出範圍，無法套用增益的顏色。";
VUHDO_I18N_TT.K016 = "選擇增益正在冷卻中的顏色。";
VUHDO_I18N_TT.K017 = "選擇增益團補是空的顏色。";
VUHDO_I18N_TT.K018 = "選擇增益監控面板的背景顏色。";
VUHDO_I18N_TT.K019 = "選擇增益色塊的邊框顏色。";
VUHDO_I18N_TT.K020 = "選擇增益監控面板的邊框顏色。";
VUHDO_I18N_TT.K021 = "啟用增益的冷卻閃爍，當冷卻時間結束時會閃爍。";
VUHDO_I18N_TT.K022 = "選擇增益持續時間由充裕變為快結束的時間百分比。";
VUHDO_I18N_TT.K023 = "選擇增益色塊持續時間由充裕變為快結束的分鐘數。";
VUHDO_I18N_TT.K028 = "設定依據玩家狀態變化所顯示的顏色。";
VUHDO_I18N_TT.K029 = "設定依據選擇模式不同所顯示的顏色。";
VUHDO_I18N_TT.K031 = "更改表示緊急的顏色 (注意: 必須先啟用其中一種緊急模式)。";
VUHDO_I18N_TT.K032 = "更改表示玩家不緊急的顏色 (注意: 必須先啟用其中一種緊急模式)。";
VUHDO_I18N_TT.K033 = "更改表示玩家不要緊，也就是血量非常充裕的顏色 (請參考: 一般選項標籤頁中的 \"超過則不要緊\" 滑桿設定)。";
VUHDO_I18N_TT.K034 = "更改玩家身上已經有即將治療的顏色。";
VUHDO_I18N_TT.K035 = "更改玩家超出範圍的顏色 (注意: 必須先啟用範圍檢查)。";
VUHDO_I18N_TT.K036 = "更改表示玩家死亡的顏色。";
VUHDO_I18N_TT.K037 = "更改表示玩家離線的顏色。";
VUHDO_I18N_TT.K038 = "更改表示玩家被心控的顏色。";
VUHDO_I18N_TT.K040 = "更改表示玩家中毒的顏色。";
VUHDO_I18N_TT.K041 = "更改表示玩家中疾病的顏色。";
VUHDO_I18N_TT.K042 = "更改表示玩家中詛咒的顏色。";
VUHDO_I18N_TT.K043 = "更改表示玩家受到魔法減益效果影響的顏色。";
VUHDO_I18N_TT.K044 = "設定 VuhDo 的基本功能。";
VUHDO_I18N_TT.K045 = "選擇 VuhDo 要掃描的資訊。";
VUHDO_I18N_TT.K048 = "非戰鬥中要治療前先自動驅散。";
VUHDO_I18N_TT.K049 = "非戰鬥中自動復活死亡的玩家。";
VUHDO_I18N_TT.K053 = "選擇通用的治療外觀。通常偏好 \"一般\"，除非是治療大型團隊。";
VUHDO_I18N_TT.K054 = "設定最多同時顯示多少個血量最低的玩家，如果模式設定為 \"一般\" 則此選項沒有影響。";
VUHDO_I18N_TT.K055 = "設定補血點最大值的百分比，血量高於補血點的玩家會被認為是血量充裕的，也就是說，他們會被稍微淡出 (可自行設定)。";
VUHDO_I18N_TT.K056 = "忽略本質無害的減益。";
VUHDO_I18N_TT.K057 = "忽略只會緩速的減益。";
VUHDO_I18N_TT.K058 = "忽略持續時間非常短的減益。";
VUHDO_I18N_TT.K059 = "忽略和玩家自身職業無關的減益。 (例如: 盜賊身上的法力燃燒)。";
VUHDO_I18N_TT.K060 = "只顯示自己可以驅散的減益，不勾選則會顯示全部的減益。";
VUHDO_I18N_TT.K062 = "過量治療會讓血量條變亮。";
VUHDO_I18N_TT.K063 = "也要顯示自己造成的即將治療，但感覺會被其他玩家的誤導。";
VUHDO_I18N_TT.K065 = "選擇檢查玩家是否在範圍內的更新頻率。溫馨提示: 較低的數值更新較頻繁，可能會降低系統效能。";
VUHDO_I18N_TT.K066 = "使用 \"典型的\" 法術施法範圍。如果你沒有任何相關法術也請勾選此選項。";
VUHDO_I18N_TT.K067 = "輸入用來做範圍檢查的法術名稱。";
VUHDO_I18N_TT.K068 = "使用下方所指定的法術施法範圍來做範圍檢查。";
VUHDO_I18N_TT.K070 = "選擇持續性治療的圖示大小為條列高度的多少百分比。";
VUHDO_I18N_TT.K071 = "持續性治療圖示顯示在血量條內部的右側。";
VUHDO_I18N_TT.K072 = "持續性治療圖示顯示在血量條內部的左側。";
VUHDO_I18N_TT.K073 = "持續性治療圖示顯示在血量條外部的左側。";
VUHDO_I18N_TT.K074 = "持續性治療圖示顯示在血量條外部的右側。";
VUHDO_I18N_TT.K076 = "選擇條列背景的材質名稱。";
VUHDO_I18N_TT.K077 = "移動來更改條列背景材質。";
VUHDO_I18N_TT.K078 = "更改面板背景顏色。";
VUHDO_I18N_TT.K079 = "更改面板邊框顏色。";
VUHDO_I18N_TT.K081 = "拖曳來更改法力條的大小。";
VUHDO_I18N_TT.K083 = "選擇 \"分組\" 時，設定每個橫列最多顯示幾個隊伍，超過時會換到下一列。";
VUHDO_I18N_TT.K084 = "在選擇的治療面板中顯示所有玩家的按鈕，不分隊伍或職業隨意排列，會自動隱藏標題。";
VUHDO_I18N_TT.K085 = "在選擇的治療面板中顯示所有玩家的按鈕，依據隊伍/職業排列。";
VUHDO_I18N_TT.K086 = "在團隊中隱藏空的隊伍 (只有選擇 \"分組\" 時才有效果)。";
VUHDO_I18N_TT.K087 = "選擇每個橫列最多顯示幾個直行，超過時會換到下一列。";
VUHDO_I18N_TT.K088 = "面板的對齊點設為左上。";
VUHDO_I18N_TT.K089 = "面板的對齊點設為右上。";
VUHDO_I18N_TT.K090 = "面板的對齊點設為左下。";
VUHDO_I18N_TT.K091 = "面板的對齊點設為右下。";
VUHDO_I18N_TT.K092 = "面板中玩家的排序方式和遊戲內建的暴雪團隊框架相同。";
VUHDO_I18N_TT.K094 = "面板中玩家依據名字排序。";
VUHDO_I18N_TT.K095 = "拖曳來更改標題高度。";
VUHDO_I18N_TT.K096 = "拖曳來更改條列和標題之間的距離。";
VUHDO_I18N_TT.K097 = "顯示標題 (注意: 必須先選擇 \"一般\"=>\"分組\")";
VUHDO_I18N_TT.K098 = "移動來更改標題背景材質。";
VUHDO_I18N_TT.K099 = "選擇標題背景的材質名稱。";
VUHDO_I18N_TT.K100 = "移動來調整標題背景為條列寬度的多少百分比。";
VUHDO_I18N_TT.K101 = "移動來調整標題文字大小。";
VUHDO_I18N_TT.K102 = "標題文字使用職業顏色 (注意: 只有標題為職業時才有效果)。";
VUHDO_I18N_TT.K103 = "更改標題背景和文字顏色。";
VUHDO_I18N_TT.K104 = "設定面板標題的外觀。";
VUHDO_I18N_TT.K105 = "設定面板的基本外觀。";
VUHDO_I18N_TT.K106 = "設定浮動提示資訊的外觀。";
VUHDO_I18N_TT.K107 = "設定血量條上要顯示哪些文字，以及如何顯示。";
VUHDO_I18N_TT.K108 = "設定是否要在面板中顯示玩家的目標，以及如何顯示。";
VUHDO_I18N_TT.K109 = "設定血量條的寬度、高度、邊框距離和間距。";
VUHDO_I18N_TT.K110 = "設定血量條的外觀、面板背景和邊框顏色。";
VUHDO_I18N_TT.K111 = "將 '目前標籤頁面' 中的設定套用到所有面板。";
VUHDO_I18N_TT.K112 = "設定血量條之間的水平距離。";
VUHDO_I18N_TT.K113 = "設定血量條之間的垂直距離。";
VUHDO_I18N_TT.K114 = "設定血量條和邊框之間的垂直距離。";
VUHDO_I18N_TT.K115 = "設定血量條和邊框之間的水平距離。";
VUHDO_I18N_TT.K116 = "設定血量條在面板中的高度。";
VUHDO_I18N_TT.K117 = "設定血量條在面板中的寬度。";
VUHDO_I18N_TT.K118 = "移動來調整血量條和目標條之間的距離。";
VUHDO_I18N_TT.K119 = "在目前面板中顯示玩家目標。";
VUHDO_I18N_TT.K120 = "移動來調整目前面板中的目標條寬度。";
VUHDO_I18N_TT.K126 = "補血點文字顯示為百分比。";
VUHDO_I18N_TT.K127 = "補血點文字顯示為補血點已缺少的血量數字。";
VUHDO_I18N_TT.K128 = "補血點文字顯示為補血點還剩餘的血量數字。";
VUHDO_I18N_TT.K129 = "補血點文字顯示在玩家名字的右側。";
VUHDO_I18N_TT.K130 = "補血點文字顯示在玩家名字的左側。";
VUHDO_I18N_TT.K131 = "補血點文字顯示在玩家名字的下方。";
VUHDO_I18N_TT.K132 = "補血點文字顯示在玩家名字的上方。";
VUHDO_I18N_TT.K133 = "在血量條上顯示補血點文字。";
VUHDO_I18N_TT.K134 = "拖曳來調整血量條上的文字大小。";
VUHDO_I18N_TT.K135 = "使用職業顏色來顯示玩家名字。";
VUHDO_I18N_TT.K136 = "更改血量條文字顏色。";
VUHDO_I18N_TT.K138 = "允許自由移動浮動提示資訊面板，拖曳浮動提示資訊來調整位置。";
VUHDO_I18N_TT.K139 = "浮動提示資訊隨滑鼠游標，顯示在游標的位置 (注意: 可能會影響遊戲效能)";
VUHDO_I18N_TT.K140 = "浮動提示資訊顯示在遊戲預設的標準位置。";
VUHDO_I18N_TT.K141 = "大部分的時候都要顯示浮動提示資訊。";
VUHDO_I18N_TT.K142 = "戰鬥中也要顯示浮動提示資訊。";
VUHDO_I18N_TT.K143 = "調整浮動提示資訊的整體大小。";
VUHDO_I18N_TT.K144 = "選擇浮動提示資訊的背景顏色。";
VUHDO_I18N_TT.K145 = "浮動提示資訊的邊框顏色。";
VUHDO_I18N_TT.K146 = "設定組合按鍵 \"ALT+SHIFT\" 的法術。";
VUHDO_I18N_TT.K147 = "設定組合按鍵 \"CTRL\" 的法術。";
VUHDO_I18N_TT.K148 = "設定組合按鍵 \"CTRL+SHIFT\" 的法術。";
VUHDO_I18N_TT.K149 = "設定組合按鍵 \"ALT+CTRL+SHIFT\" 的法術。";
VUHDO_I18N_TT.K150 = "設定按下組合按鍵時要施放的法術。";
VUHDO_I18N_TT.K151 = "設定組合按鍵 \"ALT\" 的法術。";
VUHDO_I18N_TT.K152 = "設定組合按鍵 \"SHIFT\" 的法術。";
VUHDO_I18N_TT.K153 = "設定組合按鍵 \"ALT+CTRL\" 的法術。";
VUHDO_I18N_TT.K154 = "完成設定並確認所有更改。";
VUHDO_I18N_TT.K155 = "取消設定，放棄所有更改。";
VUHDO_I18N_TT.K156 = "隱藏增益次數 > 1 的剩餘次數數字。";
VUHDO_I18N_TT.K157 = "更改能量顏色，例如: 法力、能量或怒氣。"
VUHDO_I18N_TT.K158 = "選擇法力條的顏色。"
VUHDO_I18N_TT.K159 = "選擇怒氣條的顏色。"
VUHDO_I18N_TT.K160 = "選擇能量條的顏色。"
VUHDO_I18N_TT.K161 = "選擇符能條的顏色。"
VUHDO_I18N_TT.K162 = "設定當前仇恨/仇恨值的顯示方式。"
VUHDO_I18N_TT.K163 = "設定其他選項。"
VUHDO_I18N_TT.K164 = "載入或儲存外觀，方便變換外觀和調整設定。"
VUHDO_I18N_TT.K165 = "在隊伍/職業中不要重複顯示主坦克。"
VUHDO_I18N_TT.K166 = "在隊伍/職業中不要重複顯示玩家目標。"
VUHDO_I18N_TT.K167 = "自己的隊伍不要顯示在一般的隊伍裡面 (可能已經有另外的框架，或是在 VuhDo 中有一個面板是 \"我的隊伍\")。"
VUHDO_I18N_TT.K168 = "在玩家名字前面顯示標籤，例如: 暫離、離線或死亡。"
VUHDO_I18N_TT.K169 = "隱藏遊戲內建的暴雪隊伍框架。"
VUHDO_I18N_TT.K170 = "隱藏遊戲內建的暴雪玩家框架。"
VUHDO_I18N_TT.K173 = "選擇持續性治療的更新頻率。" -- 173
VUHDO_I18N_TT.K176 = "輸入已有的版面配置名稱來載入、取代或刪除，或是輸入新的名稱將目前的外觀另存新檔。"
VUHDO_I18N_TT.K177 = "選擇版面配置，包含大小、格式、位置的所有設定。"
VUHDO_I18N_TT.K179 = "設定仇恨值條的高度。"
VUHDO_I18N_TT.K183 = "選擇當前仇恨/仇恨值掃描的更新頻率 (毫秒)。"
VUHDO_I18N_TT.K184 = "選擇要顯示在當前仇恨對象名字左邊的文字。"
VUHDO_I18N_TT.K185 = "在名字旁加入一些文字來表示當前仇恨對象。"
VUHDO_I18N_TT.K188 = "選擇要顯示在當前仇恨對象名字右邊的文字。" -- 188
VUHDO_I18N_TT.K189 = "顯示目前的隊伍/團隊來做測試。"
VUHDO_I18N_TT.K190 = "顯示5人隊伍/團隊來做測試。"
VUHDO_I18N_TT.K191 = "顯示10人團隊來做測試。"
VUHDO_I18N_TT.K192 = "顯示25人團隊來做測試。"
VUHDO_I18N_TT.K193 = "顯示40人團隊來做測試。" -- 193
VUHDO_I18N_TT.K195 = "選擇標題文字的字體。"
VUHDO_I18N_TT.K196 = "標題背景也要使用職業顏色。"
VUHDO_I18N_TT.K197 = "選擇目標名字的文字顏色。" -- 197
VUHDO_I18N_TT.K198 = "選擇滑鼠點擊時要施放的法術。"
VUHDO_I18N_TT.K199 = "選擇按下鍵盤按鍵時要施放的法術。每個法術會使用一個空的巨集欄位來建立帳號共用巨集，並且永久綁定一個按鍵設定，其他自訂的單位框架也能夠使用。 "
VUHDO_I18N_TT.K200 = "選擇飾品/瞬發法術，只要能夠使用時就會立刻自動使用。"
VUHDO_I18N_TT.K201 = "輸入要在治療法術之前施放的瞬發法術名稱。注意: 這個法術必須沒有共用冷卻 (GCD)!"
VUHDO_I18N_TT.K202 = "輸入要在治療法術之前施放的瞬發法術名稱。注意: 這個法術必須沒有共用冷卻 (GCD)!"
VUHDO_I18N_TT.K203 = "在治療法術之前先施放法術。注意: 這個法術必須沒有共用冷卻 (GCD)!"
VUHDO_I18N_TT.K204 = "在治療法術之前先施放法術。注意: 這個法術必須沒有共用冷卻 (GCD)!" -- 204
VUHDO_I18N_TT.K205 = "在治療法術之前先使用飾品 2 (角色視窗中較下面的飾品)。注意: 這個法術必須沒有共用冷卻 (GCD)!"
VUHDO_I18N_TT.K206 = "在治療法術之前先使用飾品 1 (角色視窗中較上面的飾品)。注意: 這個法術必須沒有共用冷卻 (GCD)!"
VUHDO_I18N_TT.K207 = "非戰鬥中也要啟用自動使用飾品。"
VUHDO_I18N_TT.K208 = "法術是施放持續性治療也要啟用自動使用飾品。"
VUHDO_I18N_TT.K209 = "全部啟用/停用自動使用飾品/法術。"
VUHDO_I18N_TT.K210 = "輸入開始復活單一對象時要顯示的聊天文字，使用 \"vuhdo\" 代替復活對象的名字。";
VUHDO_I18N_TT.K211 = "開始復活單一對象時會顯示聊天文字，使用 \"vuhdo\" 代替復活對象的名字。";
VUHDO_I18N_TT.K212 = "完全隱藏空的面板。";
VUHDO_I18N_TT.K213 = "不要在 \"我負責的\" 面板中顯示專注目標。";
VUHDO_I18N_TT.K214 = "不要在一般的隊伍/團隊框架中顯示主助攻。";
VUHDO_I18N_TT.K215 = "戰鬥結束後重新補上缺少的增益。必須先在 VuhDo 增益監控中啟用增益效果，並且設定好顏色。";
VUHDO_I18N_TT.K216 = "顯示來自其他隊伍/團隊成員的即將治療。";
VUHDO_I18N_TT.K217 = "在血量條的血量文字中加入即將治療/過量治療。";
VUHDO_I18N_TT.K218 = "拖曳滑桿來調整過量治療文字的縮放大小。";
VUHDO_I18N_TT.K219 = "在血量條上使用額外的白色數字來顯示過量治療。";
VUHDO_I18N_TT.K221 = "戰鬥中也要顯示缺少增益條顏色。";
VUHDO_I18N_TT.K222 = "使用文字顏色表示缺少增益。";
VUHDO_I18N_TT.K223 = "使用條列顏色表示缺少增益。";
VUHDO_I18N_TT.K224 = "設定持續性治療方塊的基本顏色。";
VUHDO_I18N_TT.K225 = "設定持續性治療方塊的進階顏色。";
VUHDO_I18N_TT.K226 = "設定職業顏色。";
VUHDO_I18N_TT.K228 = "寵物顯示職業顏色而不是自訂顏色。";
VUHDO_I18N_TT.K229 = "選擇戰士的顏色。";
VUHDO_I18N_TT.K230 = "選擇盜賊的顏色。";
VUHDO_I18N_TT.K231 = "選擇獵人的顏色。";
VUHDO_I18N_TT.K232 = "選擇聖騎士的顏色。";
VUHDO_I18N_TT.K233 = "選擇術士的顏色。";
VUHDO_I18N_TT.K234 = "選擇薩滿的顏色。";
VUHDO_I18N_TT.K235 = "選擇德魯伊的顏色。";
VUHDO_I18N_TT.K236 = "選擇牧師的顏色。";
VUHDO_I18N_TT.K237 = "選擇法師的顏色。";
VUHDO_I18N_TT.K238 = "選擇死亡騎士的顏色。";
VUHDO_I18N_TT.K239 = "選擇寵物的顏色。";
VUHDO_I18N_TT.K241 = "使用左側的文字顏色來顯示持續性治療的次數。";
VUHDO_I18N_TT.K242 = "使用左側的背景顏色來顯示持續性治療的次數。";
VUHDO_I18N_TT.K243 = "選擇持續性治療還有2次的顏色。";
VUHDO_I18N_TT.K244 = "選擇持續性治療還有3次的顏色。";
VUHDO_I18N_TT.K245 = "選擇持續性治療還有4次的顏色。";
VUHDO_I18N_TT.K246 = "選擇持續性治療條1的顏色。";
VUHDO_I18N_TT.K247 = "選擇持續性治療條2的顏色。";
VUHDO_I18N_TT.K248 = "選擇持續性治療條3的顏色。";
VUHDO_I18N_TT.K249 = "選擇持續性治療方塊1的顏色。";
VUHDO_I18N_TT.K250 = "選擇持續性治療方塊2的顏色。";
VUHDO_I18N_TT.K251 = "選擇持續性治療方塊3的顏色。";
VUHDO_I18N_TT.K252 = "選擇持續性治療方塊4的顏色。";
VUHDO_I18N_TT.K253 = "選擇持續性治療方塊5的顏色。";
VUHDO_I18N_TT.K254 = "選擇持續性治療的剩餘持續時間非常短的顏色。";
VUHDO_I18N_TT.K255 = "選擇何時要套用警告顏色和顯示小數點 (1/10 秒)。";
VUHDO_I18N_TT.K256 = "持續性治療的次數和時間文字顯示外框。";
VUHDO_I18N_TT.K257 = "持續性治療的次數和時間文字顯示陰影。";
VUHDO_I18N_TT.K258 = "持續性治療的剩餘持續時間小於左側的設定時，顯示警告顏色。";
VUHDO_I18N_TT.K260 = "持續性治療快跳完時，淡出持續性治療的圖示/方塊。";
VUHDO_I18N_TT.K261 = "選擇自訂減益的顏色。";
VUHDO_I18N_TT.K262 = "顯示減益圖示和飛入動畫。";
VUHDO_I18N_TT.K263 = "選擇要看到哪些減益。";
VUHDO_I18N_TT.K264 = "選擇要看到哪些自訂增益和減益。";
VUHDO_I18N_TT.K265 = "面板精靈會幫助你設定面板群組，只需要點幾下。";
VUHDO_I18N_TT.K266 = "使用圖示來顯示自訂減益。";
VUHDO_I18N_TT.K267 = "使用條列顏色來顯示自訂減益。";
VUHDO_I18N_TT.K268 = "顯示圖示的動畫效果。";
VUHDO_I18N_TT.K269 = "在圖示上顯示剩餘持續時間。";
VUHDO_I18N_TT.K270 = "移動來更改自訂增益/減益圖示的縮放大小。";
VUHDO_I18N_TT.K271 = "移動來更改自訂增益/減益同時顯示數量的最大值。";
VUHDO_I18N_TT.K272 = "選擇玩家獲得自訂減益時播放的音效。";
VUHDO_I18N_TT.K273 = "使用圖示來顯示自訂增益/減益。";
VUHDO_I18N_TT.K274 = "使用條列顏色來顯示自訂增益/減益。";
VUHDO_I18N_TT.K275 = "顯示圖示的動畫效果。";
VUHDO_I18N_TT.K276 = "在圖示上顯示剩餘持續時間。";
VUHDO_I18N_TT.K279 = "選擇玩家獲得減益時播放的音效。";
VUHDO_I18N_TT.K280 = "將選擇的設定套用到面板。";
VUHDO_I18N_TT.K281 = "使用額外的面板來顯示載具，寵物也會顯示在這個面板。所有的滑鼠點擊都會以載具/寵物為目標。";
VUHDO_I18N_TT.K282 = "使用額外的面板來顯示寵物。";
VUHDO_I18N_TT.K283 = "使用額外的面板來顯示玩家目標。玩家目標很類似主坦克，但只有你看得到。";
VUHDO_I18N_TT.K284 = "使用額外的面板來顯示主坦克。";
VUHDO_I18N_TT.K285 = "所有團隊成員都不要分組，是一種簡單但直觀的檢視方式。";
VUHDO_I18N_TT.K286 = "所有團隊成員依據角色分組: 進戰 DPS、近戰坦克、遠程 DPS、治療者。";
VUHDO_I18N_TT.K287 = "所有團隊成員依據職業分組。";
VUHDO_I18N_TT.K288 = "所有團隊成員依據隊伍編號分組 (1-8)。";
VUHDO_I18N_TT.K289 = "隱藏遊戲內建的暴雪寵物框架。";
VUHDO_I18N_TT.K290 = "隱藏遊戲內建的暴雪目標框架。";
VUHDO_I18N_TT.K291 = "放開滑鼠按鍵時開始施放法術，而不是按下時。";
VUHDO_I18N_TT.K292 = "顯示標準的浮動提示資訊，而不是 VuhDo 的浮動提示資訊。";
VUHDO_I18N_TT.K298 = "勾選時，單人未組隊時會自動套用目前選擇的版面配置。";
VUHDO_I18N_TT.K299 = "勾選時，最多5人的隊伍會自動套用目前選擇的版面配置。";
VUHDO_I18N_TT.K300 = "勾選時，最多10人的團隊會自動套用目前選擇的版面配置。";
VUHDO_I18N_TT.K301 = "勾選時，最多25人的團隊會自動套用目前選擇的版面配置。";
VUHDO_I18N_TT.K302 = "勾選時，超過25人的團隊會自動套用目前選擇的版面配置。";
VUHDO_I18N_TT.K306 = "更改血量條的固定顏色。";
VUHDO_I18N_TT.K307 = "受到傷害時，血量條會發光而不是縮短。";
VUHDO_I18N_TT.K308 = "血量條垂直長，而不是水平增長。";
VUHDO_I18N_TT.K309 = "在血量條上顯示團隊標記圖示。";
VUHDO_I18N_TT.K310 = "血量條水平排列，而不是垂直排列。";
VUHDO_I18N_TT.K311 = "永遠將自己顯示在自己隊伍的最上方。(第一個血量條)。";
VUHDO_I18N_TT.K312 = "面板的對齊點設為中上。";
VUHDO_I18N_TT.K313 = "面板的對齊點設為中下。";
VUHDO_I18N_TT.K314 = "面板的對齊點設為左中。";
VUHDO_I18N_TT.K315 = "面板的對齊點設為右中。";
VUHDO_I18N_TT.K316 = "隊伍中的玩家依據最大血量排序。";
VUHDO_I18N_TT.K317 = "隊伍依據職業排序。";
VUHDO_I18N_TT.K318 = "選擇持續性治療條的寬度。";
VUHDO_I18N_TT.K325 = "持續性治療圖示顯示在血量條的左上方。";
VUHDO_I18N_TT.K326 = "持續性治療圖示顯示在血量條的右下方。";
VUHDO_I18N_TT.K327 = "持續性治療圖示顯示在血量條的左下方。";
VUHDO_I18N_TT.K328 = "持續性治療圖示顯示在血量條的右下方。";
VUHDO_I18N_TT.K329 = "持續性治療圖示顯示在血量條的左下方。";
VUHDO_I18N_TT.K331 = "使用單純的材質顯示持續性治療圖示。";
VUHDO_I18N_TT.K337 = "設定如何顯示持續性治療圖示。";
VUHDO_I18N_TT.K338 = "設定如何顯示持續性治療條。";
VUHDO_I18N_TT.K339 = "移動來更改整個面板的縮放大小。";
VUHDO_I18N_TT.K340 = "血量文字不要顯示縮寫，例如: 14537 而不是 14.5k。";
VUHDO_I18N_TT.K341 = "在血量條上顯示玩家名字。";
VUHDO_I18N_TT.K342 = "在血量條上顯示玩家職業名稱。";
VUHDO_I18N_TT.K343 = "選擇玩家名字最多顯示幾個字。";
VUHDO_I18N_TT.K344 = "選擇血量條上玩家名字的字體。";
VUHDO_I18N_TT.K345 = "點擊血量條時保持當前的姿勢型態和目標對象，不勾選時會自動變更姿勢型態。";
VUHDO_I18N_TT.K346 = "啟用法術資訊的浮動提示資訊。";
VUHDO_I18N_TT.K347 = "讓滑鼠點擊 \"穿透\" 面板，以便選取目標、走位。勾選時，將無法顯示誰是隊長...等等，這時請改用右鍵點擊。";
VUHDO_I18N_TT.K348 = "鎖定治療面板。";
VUHDO_I18N_TT.K349 = "敵方目標的法術選項。";
VUHDO_I18N_TT.K350 = "在自訂減益圖示上顯示次數數字。";
VUHDO_I18N_TT.K351 = "自訂減益對齊血量條的左上。";
VUHDO_I18N_TT.K352 = "自訂減益對齊血量條的右上。";
VUHDO_I18N_TT.K353 = "自訂減益對齊血量條的左下。";
VUHDO_I18N_TT.K354 = "自訂減益對齊血量條的右下。";
VUHDO_I18N_TT.K355 = "調整自訂減益圖示垂直方向的位置。";
VUHDO_I18N_TT.K356 = "調整自訂減益圖示水平方向的位置。";
VUHDO_I18N_TT.K357 = "在名稱文字中顯示寵物/載具擁有者的名字。";
VUHDO_I18N_TT.K358 = "設定戰鬥結束後的智慧型施法功能。";
VUHDO_I18N_TT.K359 = "選擇智慧型施法使用的組合按鍵。";
VUHDO_I18N_TT.K360 = "戰鬥中自動戰復死亡的玩家 (德魯伊限定)";
VUHDO_I18N_TT.K361 = "目標條顯示在血量條的左側。"
VUHDO_I18N_TT.K362 = "目標條顯示在血量條的右側。"
VUHDO_I18N_TT.K363 = "選擇受到傷害時閃爍的敏感度，較大的數值表示較常閃爍 (受到較少的傷害)。";
VUHDO_I18N_TT.K364 = "血量超過不要緊的門檻時隱藏血量文字。";
VUHDO_I18N_TT.K365 = "載入法術配置時，也要套用持續性治療的設定 (面板 => HoT 圖示)。";
VUHDO_I18N_TT.K366 = "治療時，將治療對象選取為當前目標。";
VUHDO_I18N_TT.K367 = "選擇要偵測哪些類型的即將治療。";
VUHDO_I18N_TT.K376 = "隊伍對齊面板下方 (靠右對齊，當上面選擇 \"水平\" 時)。";
VUHDO_I18N_TT.K377 = "選擇面板邊框材質。";
VUHDO_I18N_TT.K378 = "選擇面板邊框邊緣大小。";
VUHDO_I18N_TT.K379 = "選擇面板邊框內縮大小。";
VUHDO_I18N_TT.K380 = "在一般團隊/隊伍框架中不要顯示自己。";
VUHDO_I18N_TT.K382 = "名字和血量文字顯示外框，而不是陰影。";
VUHDO_I18N_TT.K383 = "增益追蹤時忽略寵物。";
VUHDO_I18N_TT.K384 = "依據 \"移動!\" 的設定順序排列團隊。只有上面的順序設為 \"寬鬆\" 時，此選項才有效。";
VUHDO_I18N_TT.K385 = "選擇玩家缺少這個增益時，要套用的血量條顏色。";
VUHDO_I18N_TT.K386 = "缺少這個增益時變化條列顏色。";
VUHDO_I18N_TT.K387 = "提高這個增益的優先權。";
VUHDO_I18N_TT.K388 = "降低這個增益的優先權。";
VUHDO_I18N_TT.K389 = "選擇持續性治療方塊6的顏色。";
VUHDO_I18N_TT.K390 = "反向排序。";
VUHDO_I18N_TT.K391 = "選擇團隊標記圖示的大小。";
VUHDO_I18N_TT.K392 = "對齊點設為左上。";
VUHDO_I18N_TT.K393 = "對齊點設為右上。";
VUHDO_I18N_TT.K394 = "對齊點設為左下。";
VUHDO_I18N_TT.K395 = "對齊點設為右下。";
VUHDO_I18N_TT.K396 = "對齊點設為左。";
VUHDO_I18N_TT.K397 = "對齊點設為上。";
VUHDO_I18N_TT.K398 = "對齊點設為下。";
VUHDO_I18N_TT.K399 = "對齊點設為右。";
VUHDO_I18N_TT.K400 = "調整水平方向的位置。";
VUHDO_I18N_TT.K401 = "調整垂直方向的位置。";
VUHDO_I18N_TT.K402 = "設定團隊標記圖示和過量治療文字。";
VUHDO_I18N_TT.K403 = "儲存目前的法術配置。";
VUHDO_I18N_TT.K404 = "選擇已有的法術配置。";
VUHDO_I18N_TT.K405 = "隱藏遊戲內建的暴雪專注目標框架。";
VUHDO_I18N_TT.K406 = "不要顯示持續性治療的剩餘次數。";
VUHDO_I18N_TT.K407 = "用文字顯示持續性治療的剩餘次數。";
VUHDO_I18N_TT.K408 = "在圖示周圍用三角形顯示持續性治療的剩餘次數，最多顯示 4 個 (代表 4 次或更多)。";
VUHDO_I18N_TT.K409 = "單人未組隊時隱藏面板。";
VUHDO_I18N_TT.K410 = "在最多5人的隊伍時隱藏面板。";
VUHDO_I18N_TT.K411 = "設定團隊目標圖示的顏色。";
VUHDO_I18N_TT.K412 = "複製這些預設的設定值到所有自訂減益。";
VUHDO_I18N_TT.K413 = "選擇這個自訂減益的顏色。";
VUHDO_I18N_TT.K414 = "選擇要顯示的團隊圖示。";
VUHDO_I18N_TT.K415 = "選擇過量治療文字顏色。";
VUHDO_I18N_TT.K416 = "使用條列顏色/文字顏色顯示團隊圖示。";
VUHDO_I18N_TT.K417 = "只顯示在 面板=>其他 中啟用的團隊圖示，並且使用顏色來顯示。";
VUHDO_I18N_TT.K418 = "選擇這個團隊圖示的顏色。";
VUHDO_I18N_TT.K419 = "坦克模式只會監控當前仇恨對象的仇恨值情況，敵人偶爾選取玩家為目標的情況會被忽略。";
VUHDO_I18N_TT.K420 = "牧師限定選項: 顯示護盾剩餘量的圖示。這是 '實驗性' 的功能。";
VUHDO_I18N_TT.K421 = "選擇血量全滿時的顏色。";
VUHDO_I18N_TT.K422 = "選擇血量中等時的顏色。";
VUHDO_I18N_TT.K423 = "選擇血量很低時的顏色。"
VUHDO_I18N_TT.K425 = "設定團補的更新頻率，可能會影響系統效能。";
VUHDO_I18N_TT.K426 = "選擇兩個單位被視為同一個團補的範圍。";
VUHDO_I18N_TT.K427 = "選擇最大血量，超過時會被認為是不值得使用團補治療法術的目標。";
VUHDO_I18N_TT.K428 = "選擇團補人數的最小值，剛好足以作為團補治療對象。";
VUHDO_I18N_TT.K429 = "選擇團補人數的最小值，這是很好的團補治療對象。"
VUHDO_I18N_TT.K430 = "團補治療法術是由自己身上擴散出去的 (不是從施法對象)。";
VUHDO_I18N_TT.K431 = "團補治療法術是由被施放法術的對象身上擴散出去的 (不是從你自己，例如: 治療之環)";
VUHDO_I18N_TT.K432 = "全部的團隊成員都可以受到法術效果 (治療鍊、治療之環)。";
VUHDO_I18N_TT.K433 = "只有施法對象和同一個小隊的成員能夠受到法術效果 (治療禱言)。";
VUHDO_I18N_TT.K435 = "顯示目前團補治療的足夠單位數量 (每個單位會有團補持續性治療圖示)";
VUHDO_I18N_TT.K436 = "顯示共用冷卻時間條。";
VUHDO_I18N_TT.K437 = "直接從施法對象的周圍偵測團補。";
VUHDO_I18N_TT.K438 = "從施法對象跳到最靠近、最需要被治療的對象來偵測團補。"
VUHDO_I18N_TT.K439 = "範圍治療能補到的最多人數。";
VUHDO_I18N_TT.K440 = "選擇團補人數被評為中等時的顏色。";
VUHDO_I18N_TT.K441 = "選擇團補人數被評為良好時的顏色。";
VUHDO_I18N_TT.K443 = "選擇共用冷卻時間條的顏色。"
VUHDO_I18N_TT.K444 = "最多15人的團隊時會自動啟用目前選擇的版面配置。";
VUHDO_I18N_TT.K446 = "從忽略清單中選擇減益。";
VUHDO_I18N_TT.K447 = "將地城搜尋器設定為坦克的玩家顯示在主坦克清單。";
VUHDO_I18N_TT.K448 = "為你的群體治療法術設定團補偵測。";
VUHDO_I18N_TT.K451 = "在增益監控上使用滑鼠滾輪，自動補上所有缺少的增益。";
VUHDO_I18N_TT.K452 = "選擇已有的狀態群組，或輸入新的名稱。";
VUHDO_I18N_TT.K453 = "選擇特別的觸發，或輸入增益/減益的名稱。";
VUHDO_I18N_TT.K454 = "選擇這個事件/觸發的顏色。";
VUHDO_I18N_TT.K455 = "選擇這個事件的預設圖示。選擇 \"- 無 / 預設 -\" 時會顯示增益/減益自己原本的圖示。";
VUHDO_I18N_TT.K456 = "選擇條列的指示器，像是圖示和條列。";
VUHDO_I18N_TT.K457 = "設定狀態群組。狀態群組是由增益、減益和其他暫時性效果所組成的群組，擁有較高的優先權。例如可以將狀態群組設定成持續性治療圖示，用更節省空間的方式來顯示多個增益。";
VUHDO_I18N_TT.K458 = "用更節省空間的方式來顯示多個增益。";
VUHDO_I18N_TT.K459 = "輸入新狀態群組的名稱來建立，或是將目前的狀態群組複製過去。";
VUHDO_I18N_TT.K460 = "輸入增益、減益或持續性治療名稱。";
VUHDO_I18N_TT.K461 = "選擇狀態列的值為低的顏色。";
VUHDO_I18N_TT.K462 = "選擇狀態列的值為中的顏色。";
VUHDO_I18N_TT.K463 = "選擇狀態列的值為高的顏色。";
VUHDO_I18N_TT.K464 = "選擇要使用這個指示器顯示的狀態群組。";
VUHDO_I18N_TT.K465 = "啟用 Clique 插件的相容模式。更改後需要重新載入介面才會生效。";
VUHDO_I18N_TT.K466 = "不論距離多遠都要掃描所有單位。";
VUHDO_I18N_TT.K467 = "只掃描和你處於同一個地圖的單位。";
VUHDO_I18N_TT.K468 = "只掃描最多100碼範圍內的單位。";
VUHDO_I18N_TT.K469 = "只掃描最多40碼範圍內的單位。";
VUHDO_I18N_TT.K470 = "掃描天賦樹來預估判斷團隊角色，可能會和其他插件相衝突。";
VUHDO_I18N_TT.K471 = "條列由右向左增長。";
VUHDO_I18N_TT.K472 = "單位受到嚴重傷害時，閃爍血量條。";
VUHDO_I18N_TT.K473 = "使用原本的圖示來顯示持續性治療方塊。";
VUHDO_I18N_TT.K474 = "使用光滑材質來顯示持續性治療方塊。";
VUHDO_I18N_TT.K475 = "切換到第一專精時，自動啟用設定檔。";
VUHDO_I18N_TT.K476 = "切換到第二專精時，自動啟用設定檔。";
VUHDO_I18N_TT.K477 = "重置各種設定，恢復成預設值。";
VUHDO_I18N_TT.K478 = "返回前一畫面。";
VUHDO_I18N_TT.K479 = "只有這個文字輸入框中的法術沒有冷卻時間時，才會顯示團補。留空白則總是會顯示團補。";
VUHDO_I18N_TT.K480 = "移動來更改設定選項面板的大小。";
VUHDO_I18N_TT.K481 = "設定持續性治療次數/時間文字。";
VUHDO_I18N_TT.K482 = "調整持續性治療文字大小。";
VUHDO_I18N_TT.K483 = "替選取的面板選擇狀態群組，會取代一般的血條狀態群組。";
VUHDO_I18N_TT.K485 = "不要在 \"我負責的\" 面板中顯示你的目標。";
VUHDO_I18N_TT.K486 = "鎖定設定檔，以避免不小心被取代。";
VUHDO_I18N_TT.K487 = "自動取代已有的設定檔，不要顯示取代/複製/放棄的確認對話框。";
VUHDO_I18N_TT.K488 = "只有已死亡的玩家才顯示方向。";
VUHDO_I18N_TT.K489 = "顯示其他團隊成員的距離。";
VUHDO_I18N_TT.K490 = "使用箭頭顯示超出範圍玩家的方向。";
VUHDO_I18N_TT.K491 = "獲得減益後，顯示自訂減益名稱約2秒。";
VUHDO_I18N_TT.K492 = "替戰鬥中斷線又登入回來的團隊有效成員建立巨集，需要2個空的角色專用巨集欄位。"
VUHDO_I18N_TT.K493 = "選擇方向箭頭的大小。"
VUHDO_I18N_TT.K494 = "選擇目的設定檔。";
VUHDO_I18N_TT.K495 = "將目前設定檔中的所有自訂減益，匯出到這個角色的所有設定檔中。";
VUHDO_I18N_TT.K496 = "將目前設定檔中的所有自訂減益，匯出到選擇的設定檔中。";
VUHDO_I18N_TT.K497 = "將目前設定檔中的所有自訂減益，匯出到其他所有的設定檔中。";
VUHDO_I18N_TT.K498 = "重複點擊時放棄目前正在施放的法術，開始新的施法。";
VUHDO_I18N_TT.K499 = "選擇治療面板的框架層級。";
VUHDO_I18N_TT.K500 = "使用組合在一起的增益。目前只有薩滿的 \"元素呼喚\"。";
VUHDO_I18N_TT.K501 = "啟用按鈕外觀 ButtonFacade 的相容性。更改後需要重新載入介面才會生效。";
VUHDO_I18N_TT.K502 = "只有在戰鬥中要鎖定面板。";
VUHDO_I18N_TT.K503 = "在能量條右上顯示持續性治療。";
VUHDO_I18N_TT.K504 = "在能量條左上顯示持續性治療。";
VUHDO_I18N_TT.K505 = "在血量條右下顯示持續性治療，和能量條重疊。";
VUHDO_I18N_TT.K506 = "在血量條左下顯示持續性治療，和能量條重疊。";
VUHDO_I18N_TT.K507 = "選擇右側條的寬度。";
VUHDO_I18N_TT.K508 = "選擇左側條的寬度。";
VUHDO_I18N_TT.K509 = "沒有超出範圍也要顯示方向箭頭。";
VUHDO_I18N_TT.K510 = "選擇持續性治療方塊7的顏色。";
VUHDO_I18N_TT.K511 = "隱藏遊戲內建的暴雪標準團隊框架。";
VUHDO_I18N_TT.K512 = "建立 VuhDo 內部的按鍵設定。不需要空的巨集欄位，VuhDo 面板之外可以有不同的按鍵設定。";
VUHDO_I18N_TT.K513 = "持續性治療結束前，短暫的閃爍這個持續性治療圖示。";
VUHDO_I18N_TT.K514 = "顯示自訂減益的浮動提示資訊。";
VUHDO_I18N_TT.K515 = "顯示玩家的最大血量。";
VUHDO_I18N_TT.K516 = "停用以避免暴雪標準 UI 的執行時期錯誤。如果你沒有遇到任何問題，可以啟用這個選項。";
VUHDO_I18N_TT.K517 = "對齊點設為中間。";
VUHDO_I18N_TT.K518 = "調整文字大小。";
VUHDO_I18N_TT.K519 = "選擇字體。";
VUHDO_I18N_TT.K520 = "選擇文字和文字陰影 (背景) 的顏色。";
VUHDO_I18N_TT.K521 = "啟用文字陰影。";
VUHDO_I18N_TT.K522 = "啟用文字外框。";
VUHDO_I18N_TT.K523 = "顯示從玩家獲得減益開始到現在的經過時間，而不是減益的剩餘持續時間。";
VUHDO_I18N_TT.K524 = "啟用戰鬥記錄分析，會大幅加快血量更新速度。";
VUHDO_I18N_TT.K525 = "載入和儲存不同的按鍵配置。";
VUHDO_I18N_TT.K526 = "匯出不同的設定到其他設定檔。";
VUHDO_I18N_TT.K527 = "神禦之盾的剩餘吸收量為牧師補血量的 60% 時才顯示，停用這個選項時會在 100% 一開始就顯示。";
VUHDO_I18N_TT.K528 = "增益/減益的剩餘時間顯示最後100秒，而不是只有10秒。";
VUHDO_I18N_TT.K529 = "設定減益時間和次數的位置和文字顏色。";
VUHDO_I18N_TT.K530 = "自動使用工程學的 Glove tinker。";
VUHDO_I18N_TT.K531 = "停用消除鋸齒。";
VUHDO_I18N_TT.K532 = "依據目標的屬性使用右邊其中一種顏色。";
VUHDO_I18N_TT.K533 = "使用職業顏色來顯示目標。";
VUHDO_I18N_TT.K534 = "使用固定顏色來顯示目標。";
VUHDO_I18N_TT.K535 = "使用漸層色來顯示目標。";
VUHDO_I18N_TT.K536 = "選擇已經是其他玩家的目標，對你來說是無效目標的顏色。";
VUHDO_I18N_TT.K537 = "選擇你的目標條的顏色。";
VUHDO_I18N_TT.K538 = "選擇要出現這個範圍法術圖示的總共治療量。";
VUHDO_I18N_TT.K539 = "只顯示你能施放的範圍法術。";
VUHDO_I18N_TT.K540 = "從需要補血的血量中扣除來自其他玩家的即將治療。";
VUHDO_I18N_TT.K541 = "冷卻中的法術不會顯示團補建議。";
VUHDO_I18N_TT.K543 = "讓你的範圍治療法術自動補到好的對象。";
VUHDO_I18N_TT.K544 = "前方多少角度的錐形範圍內，法術是有效的 (360 = 整圈)。對於追蹤黎明曙光很有幫助 (設為 180)。";
VUHDO_I18N_TT.K545 = "選擇這個持續性治療圖示的縮放大小，只對排列在血條周圍的持續性治療圖示有效。"
VUHDO_I18N_TT.K546 = "隱藏遊戲內建的團隊管理工具。";
VUHDO_I18N_TT.K547 = "只有不是瞬發的法術才要扣掉即將治療。";
VUHDO_I18N_TT.K548 = "完全隱藏不存在的單位 (目標、專注目標和戰鬥時不在的團隊成員)。";
VUHDO_I18N_TT.K549 = "勾選時，最多20人的團隊會自動套用目前選擇的版面配置。";
VUHDO_I18N_TT.K550 = "顯示20人團隊來做測試。";
VUHDO_I18N_TT.K551 = "勾選時，最多30人的團隊會自動套用目前選擇的版面配置。";
VUHDO_I18N_TT.K552 = "顯示30人團隊來做測試。";
VUHDO_I18N_TT.K553 = "將選擇的設定檔設為帳號中所有新角色的預設設定檔。";
VUHDO_I18N_TT.K554 = "將選擇的按鍵配置設為帳號中所有新角色的預設按鍵配置。";
VUHDO_I18N_TT.K555 = "使用 Clique 相容模式時，也能綁定 VuhDo 的選單指令。";
VUHDO_I18N_TT.K556 = "使用額外的面板來顯示首領戰的 NPC (例如: 泰克塔碎片、綠苞子巨人的香菇)。";
VUHDO_I18N_TT.K557 = "自訂標籤功能的主體。請確保返回值是 true 或 false。範例: return (\"你的名字\" == VUHDO_unitInfo[\"name\"])";
VUHDO_I18N_TT.K558 = "非戰鬥中隱藏增益監控。";
VUHDO_I18N_TT.K559 = "選擇集中值條的顏色。";
VUHDO_I18N_TT.K560 = "選擇星能條的顏色。";
VUHDO_I18N_TT.K561 = "選擇元能條的顏色。";
VUHDO_I18N_TT.K562 = "選擇瘋狂條的顏色。";
VUHDO_I18N_TT.K563 = "選擇魔怒條的顏色。";
VUHDO_I18N_TT.K564 = "選擇武僧的顏色。";
VUHDO_I18N_TT.K565 = "選擇惡魔獵人的顏色。";
VUHDO_I18N_TT.K566 = "選擇魔痛條的顏色。";
VUHDO_I18N_TT.K567 = "輸入開始施放 '群體復活' 時要顯示的聊天文字。";
VUHDO_I18N_TT.K568 = "設定法術追蹤。法術追蹤會追蹤特定的法術施放到哪些對象身上，可以使用法術追蹤來建立狀態群組，或使用預設的 '法術追蹤' 狀態群組，例如當作持續性治療圖示或指示器。";
VUHDO_I18N_TT.K569 = "啟用追蹤神聖牧師的 '聖光顯跡' 天賦。可以使用對應的預設狀態群組 '聖光顯跡' 來顯示指示器。";
VUHDO_I18N_TT.K570 = "持續時間為多少時，要顯示法術追蹤圖示。";
VUHDO_I18N_TT.K571 = "當法術是由我施放時，要追蹤法術。";
VUHDO_I18N_TT.K572 = "當法術是由其他人施放時，要追蹤法術。";
VUHDO_I18N_TT.K573 = "勾選時，最多3人的隊伍會自動套用目前選擇的版面配置。";
VUHDO_I18N_TT.K574 = "顯示3人隊伍來做測試。";
VUHDO_I18N_TT.K575 = "顯示15人團隊來做測試。";
VUHDO_I18N_TT.K576 = "圖示作用時顯示發光效果。";
VUHDO_I18N_TT.K577 = "條列作用時顯示發光效果。"; 
VUHDO_I18N_TT.K578 = "選擇圖示的發光顏色。";
VUHDO_I18N_TT.K579 = "選擇條列的發光顏色。";
VUHDO_I18N_TT.K580 = "選擇和滑鼠右鍵一起使用的組合按鍵，來將減益圖示加入黑名單。"
VUHDO_I18N_TT.K581 = "在血條上顯示玩家暱稱。";
VUHDO_I18N_TT.K582 = "將選取的單位設為目標。";
VUHDO_I18N_TT.K583 = "持續性治療結束前，淡出所有持續性治療圖示。";
VUHDO_I18N_TT.K584 = "持續性治療結束前，閃爍所有持續性治療圖示。";
VUHDO_I18N_TT.K585 = "選擇喚能師的顏色";
VUHDO_I18N_TT.K586 = "只顯示文字，沒有圖示。";
VUHDO_I18N_TT.K587 = "只顯示即將施放的法術，必須使用法術 ID 不可使用法術名稱。";
VUHDO_I18N_TT.K588 = "只顯示友方單位即將施放的法術。";
VUHDO_I18N_TT.K589 = "只顯示敵方單位即將施放的法術。";
VUHDO_I18N_TT.K590 = "顯示所有即將施放的法術。";
VUHDO_I18N_TT.K591 = "只顯示首領/NPC 即將施放的法術。";
VUHDO_I18N_TT.K592 = "在血量條上顯示非公開性的光環圖示。";
VUHDO_I18N_TT.K593 = "選擇非公開性的光環圖示的大小。";
VUHDO_I18N_TT.K594 = "將寵物排列在最後面。";
VUHDO_I18N_TT.K595 = "顯示玩家的有效血量 (包含護盾的血量)。";
VUHDO_I18N_TT.K596 = "更改表示玩家受到流血減益效果影響的顏色。";
VUHDO_I18N_TT.K597 = "只有當減益效果可自行移除時才播放聲音。";
VUHDO_I18N_TT.K598 = "選擇持續性治療方塊8的顏色。";
VUHDO_I18N_TT.K599 = "選擇持續性治療方塊9的顏色。";
VUHDO_I18N_TT.K600 = "友方單位顯示減益圖示。";
VUHDO_I18N_TT.K601 = "敵方單位顯示減益圖示。";
VUHDO_I18N_TT.K602 = "敵方單位顯示你施放的減益。";
VUHDO_I18N_TT.K603 = "敵方單位顯示其他人施放的減益。";
VUHDO_I18N_TT.K604 = "使用漸層的職業顏色。";
VUHDO_I18N_TT.K605 = "使用漸層色。";
VUHDO_I18N_TT.K606 = "使用最多漸層色。";
VUHDO_I18N_TT.K607 = "更改有狂怒增益的敵人的顏色。";
VUHDO_I18N_TT.K608 = "忽略敵人身上可驅散的增益。";
VUHDO_I18N_TT.K609 = "載入法術配置時，只套用持續性治療的欄位設定 (面板 => HoT 圖示 => 順序)。";

-- TBCC game version specific strings (tooltip IDs begin at K900)

VUHDO_I18N_TT.K900 = "使用 LibHealComm-4.0 顯示即將治療預估。";

VUHDO_I18N_DEFAULT_PROFILE = "預設設定檔";
VUHDO_I18N_DEFAULT_LAYOUT = "預設按鍵配置";
VUHDO_I18N_APPLY_TO_ALL = "全部套用";
VUHDO_I18N_TEST = "測試";
VUHDO_I18N_ADD = "新增";
VUHDO_I18N_SELECT = "選擇";
VUHDO_I18N_NEW_COLOR = "新顏色";
VUHDO_I18N_OLD_COLOR = "原本的顏色";
VUHDO_I18N_HIDE_CHARGES = "隱藏次數";
VUHDO_I18N_POWERS = "能量";
VUHDO_I18N_HOT_COLORS = "持續性治療圖示";
VUHDO_I18N_ICONS = "圖示";
VUHDO_I18N_COUNTDOWN = "冷卻時間";
VUHDO_I18N_APPLIANCES = "次數";
VUHDO_I18N_FADE_OUT = "淡出";
VUHDO_I18N_POWER_TYPES = "能量類型";
VUHDO_I18N_THREAT = "仇恨";
VUHDO_I18N_MISC = "其他";
VUHDO_I18N_PANEL_WIZARD = "面板精靈";
VUHDO_I18N_PRIV_TANKS = "我負責的";
VUHDO_I18N_ICON = "圖示";
VUHDO_I18N_ANIMATION = "動畫";
VUHDO_I18N_STORE = "保存";
VUHDO_I18N_SAVE = "儲存";
VUHDO_I18N_DELETE = "刪除";
VUHDO_I18N_APPLY = "套用";
VUHDO_I18N_ADDITIONAL_PANELS = "額外面板";
VUHDO_I18N_UNSORT = "不排序";
VUHDO_I18N_ROLES = "角色";
VUHDO_I18N_CLASSES = "職業";
VUHDO_I18N_GROUPS = "隊伍";
VUHDO_I18N_MAIN_PANEL = "主面板";
VUHDO_I18N_PARTY = "隊伍";
VUHDO_I18N_PET = "寵物";
VUHDO_I18N_TARGET = "目標";
VUHDO_I18N_HIDE_STANDARD = "隱藏遊戲內建";
VUHDO_I18N_HOT_TARGETING = "整體掃描";
VUHDO_I18N_OR_ENTER_PROFILE_NAME = "... 或輸入設定檔名稱";
VUHDO_I18N_LEFT = "左";
VUHDO_I18N_RIGHT = "右";
VUHDO_I18N_CHECK_FOR_AGGRO = "檢查當前仇恨對象";
VUHDO_I18N_CURR = "目前";
VUHDO_I18N_BAR_COLOR = "條列顏色";
VUHDO_I18N_INV_GROWTH = "反向";
VUHDO_I18N_VERTICAL = "垂直";
VUHDO_I18N_RAID_ICON = "團隊圖示";
VUHDO_I18N_YOU_FIRST = "自己優先";
VUHDO_I18N_IICONSI = "[圖示]";
VUHDO_I18N_ISQUARESI = "[方塊]";
VUHDO_I18N_HOT_ORDER = "持續性治療順序";
VUHDO_I18N_TEXT_POSITION = "文字位置";
VUHDO_I18N_FLAGS = "標籤";
VUHDO_I18N_SHOW_TEXT = "顯示文字";
VUHDO_I18N_KEYS = "按鍵";
VUHDO_I18N_SPEC_2 = "專精 2";
VUHDO_I18N_SPEC_1 = "專精 1";
VUHDO_I18N_MANAGE_KEYS = "管理按鍵配置";
VUHDO_I18N_INSTANT_2 = "瞬發法術2";
VUHDO_I18N_INSTANT_1 = "瞬發法術1";
VUHDO_I18N_TRINKET_2 = "飾品 2";
VUHDO_I18N_TRINKET_1 = "飾品 1";
VUHDO_I18N_TRIGGER_WHAT = "使用什麼...";
VUHDO_I18N_ALSO_OUT_FIGHT = "非戰鬥中";
VUHDO_I18N_ALSO_HOTS = "持續性治療";
VUHDO_I18N_KEEP_STANCE = "保持姿勢形態";
VUHDO_I18N_AUTO_TRIGGER = "自動使用";
VUHDO_I18N_SPELL_ADVICE = "使用遊戲標準的按鍵設定來指定法術的按鍵\n( 從 Esc > 選項 > 按鍵綁定 > 巫毒)。";
VUHDO_I18N_SAVE_AS = "另存新檔...";
VUHDO_I18N_MOVE = "移動!";
VUHDO_I18N_SPELLS = "法術";
VUHDO_I18N_PANELS = "面板";
VUHDO_I18N_BUFFS = "增益";
VUHDO_I18N_ICON_SCALE = "圖示縮放大小";
VUHDO_I18N_REFRESH_AGGRO = "更新頻率";
VUHDO_I18N_PANEL_SCALE = "面板縮放大小";
VUHDO_I18N_MAX_CHARS = "最大字元數 (0=全部)";
-- #+v1.178
VUHDO_I18N_HOSTILE = "敵方";
VUHDO_I18N_HOSTILE_TITLE = "[敵方]";
VUHDO_I18N_HOSTILE_ADVICE_1 = "輸入法術名稱或 target/focus/assist"
VUHDO_I18N_HOSTILE_ADVICE_2 = "請 '不要' 輸入巨集名稱/其他常數!!!"
VUHDO_I18N_HOSTILE_ADVICE_3 = "將 '無法' 自動使用飾品/瞬發法術!!!"
-- Slider
VUHDO_I18N_WARN_PREC_AT = "警告/精確度";
VUHDO_I18N_MAX_NO_DE_BUFFS = "最多增益/減益數量";
VUHDO_I18N_BRIGHTNESS = "亮度";
VUHDO_I18N_RAID_ICON_SCALE = "團隊圖示縮放大小";
VUHDO_I18N_NAME_TEXT_SIZE = "名字文字大小";
VUHDO_I18N_LIFE_TEXT_SIZE = "血量文字大小";
-- Color swatches
VUHDO_I18N_BUFF_OKAY = "沒問題";
VUHDO_I18N_BUFF_LOW = "時間快到";
VUHDO_I18N_BUFF_MISSING = "缺少";
VUHDO_I18N_OUT_OF_RANGE = "超出範圍";
VUHDO_I18N_COOLDOWN = "冷卻中";
VUHDO_I18N_EMPTY_GROUP = "空的隊伍";
VUHDO_I18N_PANEL_BACKGROUND = "面板背景";
VUHDO_I18N_SWATCH_BORDER = "色塊邊框";
VUHDO_I18N_PANEL_BORDER = "面板邊框";
VUHDO_I18N_2ND_CHARGE = "2次";
VUHDO_I18N_3RD_CHARGE = "3次";
VUHDO_I18N_4TH_CHARGE = "4次";
VUHDO_I18N_BAR_1 = "條列 1";
VUHDO_I18N_BAR_2 = "條列 2";
VUHDO_I18N_BAR_3 = "條列 3";
VUHDO_I18N_SQUARE_1 = "方塊 1";
VUHDO_I18N_SQUARE_2 = "方塊 2";
VUHDO_I18N_SQUARE_3 = "方塊 3";
VUHDO_I18N_SQUARE_4 = "方塊 4";
VUHDO_I18N_SQUARE_5 = "方塊 5";
VUHDO_I18N_EMERGENCY = "緊急";
VUHDO_I18N_NO_EMEGENCY = "不緊急";
VUHDO_I18N_IRRELEVANT = "不要緊";
VUHDO_I18N_INCOMING = "即將治療";
VUHDO_I18N_MANA = "法力";
VUHDO_I18N_RAGE = "怒氣";
VUHDO_I18N_ENERGY = "能量";
VUHDO_I18N_RUNES = "符能";
VUHDO_I18N_DEAD = "死亡";
VUHDO_I18N_OFFLINE = "離線";
VUHDO_I18N_CHARMED = "被魅惑";
VUHDO_I18N_POISON = "中毒";
VUHDO_I18N_DISEASE = "疾病";
VUHDO_I18N_CURSE = "詛咒";
VUHDO_I18N_MAGIC = "魔法";
VUHDO_I18N_HEADER = "標題";
VUHDO_I18N_TARGET_NAME = "目標名字";
VUHDO_I18N_BORDER = "邊框";
VUHDO_I18N_ANOUNCE_RESURRECTION = "復活通報";
VUHDO_I18N_FILTER = "過濾方式";
VUHDO_I18N_FOCUS = "專注目標";
VUHDO_I18N_BUFF = "增益";
VUHDO_I18N_OTHERS = "其他人";
VUHDO_I18N_1 = " 1";
VUHDO_I18N_2 = " 2";
VUHDO_I18N_3 = " 3";
VUHDO_I18N_4 = " 4";
VUHDO_I18N_5 = " 5";
VUHDO_I18N_6 = " 6";
VUHDO_I18N_7 = " 7";
VUHDO_I18N_8 = " 8";
VUHDO_I18N_10 = " 10";
VUHDO_I18N_20 = " 20";
VUHDO_I18N_25 = " 25";
VUHDO_I18N_30 = " 30";
VUHDO_I18N_40 = " 40";
VUHDO_I18N_DEBUFF_DEFAULTS = "增益/減益預設";
VUHDO_I18N_ITEXTUREI = "[材質]";
VUHDO_I18N_BAR = "條列";
VUHDO_I18N_HOTS_2 = "持續治療#2";
VUHDO_I18N_PET_CLASS = "寵物職業";
VUHDO_I18N_CLASS_COLORS = "職業顏色";
VUHDO_I18N_HOT_CHARGES = "持續性治療次數";
VUHDO_I18N_TEXT_COLOR = "文字顏色";
VUHDO_I18N_BACK_COLOR = "背景顏色";
VUHDO_I18N_HOT_BARS = "持續治療條";
VUHDO_I18N_OUTLINE = "外框";
VUHDO_I18N_SHADOW = "陰影";
VUHDO_I18N_WARNING = "警告";
VUHDO_I18N_EXPIRY_WARNING = "快結束時警告";
VUHDO_I18N_COUNTDOWN_OFF = "冷卻時間: 關";
VUHDO_I18N_SECS = "秒";
VUHDO_I18N_SECS_10 = "1/10秒";
VUHDO_I18N_FULL_DURATION = "完整時間";
VUHDO_I18N_TOOLS = "工具";
VUHDO_I18N_TIMER = "時間";
VUHDO_I18N_SOUND = "音效";
VUHDO_I18N_STORE_DELETE = "儲存/刪除";
VUHDO_I18N_DEBUFF_SOUND = "減益音效";
VUHDO_I18N_MOUSE_UP = "放開滑鼠";
VUHDO_I18N_REACTION_ON = "動作時機";
VUHDO_I18N_UNIT = "單位";
VUHDO_I18N_SOLIDD = "固定色";
VUHDO_I18N_HORIZONTAL = "水平";
VUHDO_I18N_FLAT_TEXTURE = "平面";
VUHDO_I18N_HOT_ICONS = "HoT 圖示";
VUHDO_I18N_TARGET_OF_TARGET = "目標的目標";
VUHDO_I18N_VERBOSE = "完整";
VUHDO_I18N_1_DOT = "1.";
VUHDO_I18N_2_DOT = "2.";
VUHDO_I18N_3_DOT = "3.";
VUHDO_I18N_4_DOT = "4.";
VUHDO_I18N_5_DOT = "5.";
VUHDO_I18N_6_DOT = "6.";
VUHDO_I18N_7_DOT = "7.";
VUHDO_I18N_8_DOT = "8.";
VUHDO_I18N_9_DOT = "9.";
VUHDO_I18N_10_DOT = "10.";
VUHDO_I18N_11_DOT = "11.";
VUHDO_I18N_12_DOT = "12.";
VUHDO_I18N_13_DOT = "13.";
VUHDO_I18N_14_DOT = "14.";
VUHDO_I18N_15_DOT = "15.";
VUHDO_I18N_16_DOT = "16.";
VUHDO_I18N_KEY_BINDINGS = "按鍵綁定";
VUHDO_I18N_MOUSE_WHEEL = "滑鼠滾輪";
VUHDO_I18N_TOOLTIP_INFO = "法術資訊";
-- #+1.197
VUHDO_I18N_EDGE_SIZE = "邊緣大小";
VUHDO_I18N_EDGE_INSETS = "邊緣內縮";
-- #+1.204
VUHDO_I18N_IGNORE_PETS = "忽略寵物";
VUHDO_I18N_PANEL_MODEL = "面板模組";
-- #+1.207
VUHDO_I18N_OVERHEAL_TEXT = "過量治療文字";
-- #+1.210
VUHDO_I18N_NO_STACKS = "次數: 關";
VUHDO_I18N_NUMBER_STACKS = "文字";
VUHDO_I18N_TRIANGLE_STACKS = "三角";
VUHDO_I18N_HIDE_PANELS = "隱藏面板";
VUHDO_I18N_SOLO = "單人";
VUHDO_I18N_CLICK_THROUGH = "點擊穿透";
VUHDO_I18N_IHEALTH_BARI = "[血量條]";
VUHDO_I18N_SQUARE_6 = "方塊 6";
VUHDO_I18N_GLOSSY = "光滑";
VUHDO_I18N_DAMAGE_FLASH = "受傷閃爍";
VUHDO_I18N_SENSIVITY = "靈敏度";
VUHDO_I18N_HIDE_IRRELEVANT = "隱藏不要緊";
VUHDO_I18N_ALGINMENT = "對齊";
VUHDO_I18N_BOTTOM = "下";
VUHDO_I18N_PET_OWNERS = "寵物主人";
VUHDO_I18N_BATTLE_REZ = "戰復";
-- #+1.232
VUHDO_I18N_DEBUFF_LIST = "增益/減益清單";
VUHDO_I18N_DEBUFF_EDIT_BOX = "輸入新的增益或減益名稱";
-- #+1.233
VUHDO_I18N_BUTTON = "按鈕";
VUHDO_I18N_TANK_MODE = "坦克模式";
-- #+1.237
VUHDO_I18N_CLUSTER_SCANNER = "團補掃描";
VUHDO_I18N_FAIR_THRESHOLD = "中等值";
VUHDO_I18N_GOOD_THRESHOLD = "良好值";
VUHDO_I18N_SOURCE_SPELL = "法術來源";
VUHDO_I18N_SOURCE_MINE = "玩家";
VUHDO_I18N_SOURCE_ALL = "目標";
VUHDO_I18N_DEST_SPELL = "施放對象";
VUHDO_I18N_DEST_RAID = "團隊";
VUHDO_I18N_DEST_PARTY = "隊伍";
VUHDO_I18N_CLUSTERS = "團補";
VUHDO_I18N_LOW = "很低";
VUHDO_I18N_FAIR = "中等";
VUHDO_I18N_GOOD = "良好";
VUHDO_I18N_HEALTH_LEVEL = "血量 <";
VUHDO_I18N_CLUSTER_FINDER = "團補尋找器";
VUHDO_I18N_OTHER_HOTS = "其他玩家的持續性治療";
VUHDO_I18N_EMPTY_HOTS = "空的";
VUHDO_I18N_COUNTER = "計數";
VUHDO_I18N_GLOBAL_COOLDOWN = "共用冷卻";
VUHDO_I18N_GCD = "GCD";
-- #+1.238
VUHDO_I18N_DISPLAY_OPTIONS = "顯示選項";
VUHDO_I18N_RADIAL = "區域";
VUHDO_I18N_CHAINED = "連線";
VUHDO_I18N_CHAINED_MAX_JUMP = "治療對象的最多數量";
VUHDO_I18N_TIMES = "";
VUHDO_I18N_SOURCE_DESTINATION = "來源/對象";
VUHDO_I18N_HIGH = "高";
-- #+1.251
VUHDO_I18N_15 = " 15";
VUHDO_I18N_LOAD_HOTS = "載入 HoT";
VUHDO_I18N_IGNORE_LIST = "忽略清單";
VUHDO_I18N_FIVE_MAN_MTS = "5 人主坦";
VUHDO_I18N_FILTER_ONLY = "只有過濾";
VUHDO_I18N_LIFE_COLORS = "血量顏色";
VUHDO_I18N_SMART_WHEEL = "智慧滾輪";
VUHDO_I18N_PASTE = "貼上";
VUHDO_I18N_COPY = "複製";
-- #+1.252
VUHDO_I18N_BOUQUETS = "狀態群組";
VUHDO_I18N_SELECT_OR_ENTER_BOUQUET = "選擇狀態群組 ...";
VUHDO_I18N_NEW = "新增";
VUHDO_I18N_BOUQUET_DETAILS = "狀態群組詳細內容";
VUHDO_I18N_HIGHEST_PRIO = "最高優先權";
VUHDO_I18N_LOWEST_PRIO = "最低優先權";
VUHDO_I18N_ENTER_DE_BUFF_OR_SPECIAL = "選擇特殊事件 ...";
VUHDO_I18N_ITEM = "項目";
VUHDO_I18N_SELECT_DEFAULT_ICON = "選擇預設圖示";
VUHDO_I18N_MINE = "我的";
VUHDO_I18N_GRADIENT = "漸層";
VUHDO_I18N_INDICATORS = "指示器";
VUHDO_I18N_COPIED_BOUQUET = "已複製狀態群組 ";
VUHDO_I18N_BOUQUET_ALREADY_EXISTS = ": 狀態群組已經存在，請先輸入不同的名稱。";
VUHDO_I18N_CREATED_NEW_BOUQUET = "建立新的狀態群組: ";
VUHDO_I18N_DELETED_BOUQUET = "已刪除狀態群組: ";
VUHDO_I18N_BOUQUET_NOT_FOUND = ": 無法找到這個狀態群組。";
VUHDO_I18N_SELECT_STORE_BOUQUET_FIRST = "請先選擇狀態群組";
VUHDO_I18N_SELECT_A_PROFILE = "選擇設定檔";
VUHDO_I18N_PROFILES = "設定檔";
VUHDO_I18N_EDIT_BUTTON = "編輯...";
VUHDO_I18N_MORE_BUTTON = "更多...";
VUHDO_I18N_DONE_BUTTON = "完成";
VUHDO_I18N_BASIC = "基本";
VUHDO_I18N_ADVANCED = "進階";
VUHDO_I18N_EXPERT = "專家";
VUHDO_I18N_COMPACT = "精簡";
VUHDO_I18N_REALLY_DELETE_PROFILE = "設定檔確定刪除";
VUHDO_I18N_MUST_ENTER_SELECT_PROFILE = "必須先輸入/選擇名稱。";
VUHDO_I18N_DELETED_PROFILE = "已刪除設定檔";
VUHDO_I18N_TURN_AXIS = "旋轉";
VUHDO_I18N_DO_NOT_EDIT_BOUQUET = "通用: 請不要更改詳細內容!";
VUHDO_I18N_OR_NEW_BOUQUET_NAME = "... 或新的狀態群組名稱";
VUHDO_I18N_OR_ENTER_DEBUFF_HOT = "... 或輸入增益/減益/持續性治療名稱";
VUHDO_I18N_TALENT_TREES = "天賦樹";
VUHDO_I18N_SCAN = "掃描";
VUHDO_I18N_INFINITE = "不限距離";
VUHDO_I18N_SAME_ZONE = "相同區域";
VUHDO_I18N_100_YARDS = "100 碼";
VUHDO_I18N_40_YARDS = "40 碼";
VUHDO_I18N_LIFE_TEXT = "血量文字";
VUHDO_I18N_BACK = "返回";
VUHDO_I18N_CLIQUE_COMPAT_MODE = "Clique支援";
VUHDO_I18N_CLIQUE_PASSTHROUGH = "Clique共用";
VUHDO_I18N_RESET = "重置";
VUHDO_I18N_DEBUFF_COLORS = "減益顏色";
VUHDO_I18N_BUFFS_HOTS = "增益/持續性治療";
VUHDO_I18N_BUFF_WATCH = "增益監控";
VUHDO_I18N_CUSTOM_DEBUFFS = "自訂減益";
VUHDO_I18N_DEFAULT_BOUQUETS = "預設狀態群組";
VUHDO_I18N_EVERYTHING = "全部";
VUHDO_I18N_LANGUAGE = "語言";
VUHDO_I18N_PANEL_POSITIONS = "面板位置";
VUHDO_I18N_PER_PANEL_SETTINGS = "每個面板設定";
VUHDO_I18N_MINUTE = "分。";
VUHDO_I18N_MSEC = "毫秒";
VUHDO_I18N_PEOPLE = " 人";
VUHDO_I18N_RESET_CLASS_COLORS = "將會重置自訂的職業顏色設定。\n是否要繼續?" ;
VUHDO_I18N_RESET_DEBUFF_COLORS = "將會重置自訂的減益顏色設定。\n是否要繼續?";
VUHDO_I18N_RESET_RAID_ICON_COLORS = "將會重置自訂的團隊目標顏色設定。\n是否要繼續?";
VUHDO_I18N_RESET_BUFF_WATCH = "將會重置全部的增益監控設定。\n是否要繼續?";
VUHDO_I18N_RESET_CUSTOM_DEBUFFS = "將會重置全部的自訂減益和相關設定。\n是否要繼續?";
VUHDO_I18N_RESET_DEFAULT_BOUQUETS = "將會重置全部的 '預設'  狀態群組\n(自訂的除外)。是否要繼續?";
VUHDO_I18N_RESET_INDICATORS = "將會重置自訂的指示器設定。\n是否要繼續?";
VUHDO_I18N_RESET_ALL = "!!!警告: 將會重置整個插件，\n恢復成最初的預設值!!!\n是否要繼續?" ;
VUHDO_I18N_RESET_LANGUAGE = "更改遊戲語言後，將會重置全部的設定\n(很重要!!!)。是否要繼續?";
VUHDO_I18N_RESET_PANEL_POSITIONS = "將會重置面板的位置。是否要繼續?";
VUHDO_I18N_RESET_PER_PANEL_SETTINGS = "將會重置每個面板設定。是否要繼續?";
-- 2.17
VUHDO_I18N_LOCK = "鎖定";
VUHDO_I18N_QUIET_MODE = "無需確認";
VUHDO_I18N_SETTINGS = "設定";
VUHDO_I18N_ACTIVATE_DUE_GRP_SIZE = "依據隊伍大小啟用";
VUHDO_I18N_CUSTOM_HEALTH_BAR_BOUQUET = "自訂血量條狀態群組";
VUHDO_I18N_CUSTOM_SETTINGS = "自訂設定";
VUHDO_I18N_DISTANCE = "距離";
VUHDO_I18N_DEAD_ONLY = "只有死亡";
VUHDO_I18N_DIRECTION = "方向";
VUHDO_I18N_IF_OOR_SHOW = "單位超出範圍時顯示...";
VUHDO_I18N_DEBUFF_NAME = "減益名稱";
-- 2.18
VUHDO_I18N_DISABLE = "停用";
VUHDO_I18N_DC_RESTORE = "斷線保護";
VUHDO_I18N_EXPORT_CUSTOM_DEBUFFS = "匯出自訂減益";
VUHDO_I18N_EXPORT_TO_PROFILE = "匯出到設定檔:";
VUHDO_I18N_THIS_TOONS = "這個角色";
VUHDO_I18N_SELECTED = "選擇的";
VUHDO_I18N_ALL = "全部";
VUHDO_I18N_REPLACE = "取代";
VUHDO_I18N_SLOT = "欄位";
VUHDO_I18N_SWIFTMEND_INDICATOR =  "特殊點";
VUHDO_I18N_MOUSEOVER_HIGHLIGHTER =  "滑鼠指向";
VUHDO_I18N_OUTER_BORDER =  "外部";
VUHDO_I18N_SHIELD_ABSORPTION =  "護盾狀態";
VUHDO_I18N_BACKGROUND_BAR =  "條列背景";
VUHDO_I18N_THREAT_MARKS =  "仇恨值標記";
VUHDO_I18N_HEALTH_BAR =  "血量條";
VUHDO_I18N_UNDEFINED =  "<n/a>";
VUHDO_I18N_DOWN =  "下";
VUHDO_I18N_THREAT_BAR =  "仇恨值條";
VUHDO_I18N_O_REALLY =  "哦，確定?";
VUHDO_I18N_BORDER_WIDTH =  "寬度";
VUHDO_I18N_AGGRO_LINE =  "獲得仇恨線";
VUHDO_I18N_YES =  "是";
VUHDO_I18N_INNER_BORDER =  "內部";
VUHDO_I18N_MANA_BAR =  "法力條";
-- 2.65
VUHDO_I18N_LINK_SPELL_COOLDOWN = "連結到法術冷卻";
VUHDO_I18N_RAID = "團隊";
VUHDO_I18N_FRAME_STRATA = "框架層級";
VUHDO_I18N_VERY_LOW = "非常低";
VUHDO_I18N_LOW = "低";
VUHDO_I18N_MEDIUM_LOW = "中等低";
VUHDO_I18N_MEDIUM = "中等";
VUHDO_I18N_MEDIUM_HIGH = "中等高";
VUHDO_I18N_HIGH = "高";
VUHDO_I18N_VERY_HIGH = "非常高";
VUHDO_I18N_ULTRA = "超級";
VUHDO_I18N_STOP_CAST = "停止施法";
-- 2.67
VUHDO_I18N_COMBINED_BUFF = "綜合";
VUHDO_I18N_OPTIONS = "選項";
VUHDO_I18N_CUSTOM_ADDONS = "自訂插件";
VUHDO_I18N_CLIQUE = "Clique";
VUHDO_I18N_BUTTON_FACADE = "Masque\n支援";
-- 2.70
VUHDO_I18N_MANA_BAR_HEIGHT = "法力條高度";
VUHDO_I18N_SIDE_LEFT_WIDTH = "左側寬度";
VUHDO_I18N_SIDE_RIGHT_WIDTH = "右側寬度";

VUHDO_I18N_AMBIGUOUS_MACRO = "警告: 巨集名稱 |cffffffff\"%s\"|r 容易和法術名稱混淆! 請重新命名巨集!";
VUHDO_I18N_KEYBOARD_GLOBAL = "共用按鍵";
VUHDO_I18N_KEYBOARD_LOCAL = "專用按鍵";

VUHDO_I18N_LOCAL_KEY_ASSIGNMENTS = "專用鍵盤設定";
VUHDO_I18N_S_M_C_OR_CONSTANT = "法術、巨集、自訂名稱，或 target/focus/assist";
VUHDO_I18N_CURRENT_ASSIGNMENT = "目前設定";
VUHDO_I18N_CLEAR_BINDING = "清除綁定";
VUHDO_I18N_MACRO_EDITOR = "VuhDo 巨集編輯器";
VUHDO_I18N_ACCEPT = "接受";
VUHDO_I18N_DISCARD = "放棄";
VUHDO_I18N_LKA_HINT_1 = "在巨集中使用這些文字來代替: |c00000000vuhdo|r => 單位自己, |c00000000vdname|r => 單位的名字";
VUHDO_I18N_LKA_HINT_2 = "|c00000000vdtarget, vdtargettarget|r => 單位的目標/目標的目標，|c00000000vdpet|r => 單位的寵物，範例: /cast [@vuhdo] 快速治療";
VUHDO_I18N_LKA_CUSTOM_MACRO_DISCARDED = "已放棄自訂巨集文字。";
VUHDO_I18N_NAME_CHANGE_DISCARDED = "已放棄物品名稱變更。";
VUHDO_I18N_LKA_TYPE_CHANGED = "VuhDo 自訂巨集、法術或魔獸巨集的類型已經變更。\n是否要放棄自訂巨集文字? ";
VUHDO_I18N_ASSIGN_ABORTED = "已取消指派。";
VUHDO_I18N_LKA_PRESS_ASSIGN_KEY = "按下要指派的按鍵!";
VUHDO_I18N_LKA_SUCCESS_ASSIGNED = "按鍵已指派完成。";
VUHDO_I18N_LKA_ASSIGNED_CLEARED = "按鍵已指派完成。\"%s\" 的指派已清除!";
VUHDO_I18N_LKA_BIND_CLEARED = "綁定已清除完成。";
VUHDO_I18N_LKA_NEW_BIND = "<新增綁定>";
VUHDO_I18N_LKA_EDITED_MACRO = "已編輯巨集: ";
VUHDO_I18N_FLASH = "閃爍";
VUHDO_I18N_SHOW_TOTAL = "顯示總量";
VUHDO_I18N_ALIVE_TIME = "存在時間";
VUHDO_I18N_PARSE = "分析";
VUHDO_I18N_TEXT_SHADOW = "文字/陰影";
VUHDO_I18N_COMBAT_LOG = "戰鬥記錄";
VUHDO_I18N_ICON_TEXT_SETTINGS = "文字設定:";
VUHDO_I18N_DISCARD_CHANGES_CONFIRM = "總共已經更改了 %d 項設定。\n是否確定要 '放棄' 變更?";
VUHDO_I18N_PROFILE_NOT_EXISTS = "錯誤: 名稱為 \"%s\" 的設定檔不存在。";
VUHDO_I18N_PROFILE_EXPORTED_TO = "自訂減益已匯出到設定檔 %s";
VUHDO_I18N_ADDED_X_TO_Y = "新增 %s 到 %s。";
VUHDO_I18N_NOT_SELECTED = "<尚未選擇>";
VUHDO_I18N_CUDE_EXPORT_DONE = "自訂減益匯出完成。";
VUHDO_I18N_REALLY_EXPORT_CUDES = "是否確定要匯出到設定檔中?";
VUHDO_I18N_KEY_LAYOUTS = "按鍵配置";
VUHDO_I18N_EXPORT = "匯出";
VUHDO_I18N_LOAD_SAVE = "載入/儲存";
VUHDO_I18N_MISCELLANEOUS = "其他";
VUHDO_I18N_PUMP_AEGIS = "補放護盾";
VUHDO_I18N_TEXT_OPTIONS = "文字選項";
VUHDO_I18N_VISUALS = "視覺效果";
VUHDO_I18N_SHIELDS = "護盾";
VUHDO_I18N_RESET_PER_KEY_LAYOUTS = "將會重置按鍵和按鈕的配置設定，\n是否要繼續?";
VUHDO_I18N_SELECT_KEY_LAYOUT_FIRST = "請先選擇按鍵配置。";
VUHDO_I18N_DELETED_KEY_LAYOUT = "已刪除按鍵配置: \"%s\"";
VUHDO_I18N_OVERWRITE_CURR_KEY_LAYOUT_QUESTION = "將會覆蓋取代當前的按鍵配置，\n是否要繼續?";
VUHDO_I18N_DELETE_KEY_LAYOUT_QUESTION = "是否確定要刪除按鍵配置 \"%s\"?";
VUHDO_I18N_ENTER_KEY_LAYOUT_NAME = "請輸入按鍵配置的名稱。";
VUHDO_I18N_OVERWRITE_KEY_LAYOUT_QUESTION = "名稱為 %s 的按鍵配置已經存在，\n是否要覆蓋取代原有的?";
VUHDO_I18N_KEY_LAYOUT_SAVED = "已儲存按鍵配置: \"%s\"";
VUHDO_I18N_GLOVES = "Gloves";
VUHDO_I18N_MONO = "單色";
VUHDO_I18N_FRIEND_FOE = "友方/敵方";
VUHDO_I18N_FIENDLY = "友方";
VUHDO_I18N_NEUTRAL = "中立";
VUHDO_I18N_ENEMY = "敵方";
VUHDO_I18N_TAPPED = "無效的";
VUHDO_I18N_SQUARE_7 = "方塊 7";

VUHDO_I18N_HP = "血量";
VUHDO_I18N_KNOWN_ONLY = "只有我的";
VUHDO_I18N_MINUS_INCOMING = "-即將治療";
VUHDO_I18N_AOE_ADVICE = "團補建議";
VUHDO_I18N_CONE = "錐形";
VUHDO_I18N_DEGREES = "角度";
VUHDO_I18N_RAID_MANAGER = "團隊管理";

VUHDO_I18N_CAST_TIME_ONLY = "非瞬發";
VUHDO_I18N_EMPTY_BUTTONS = "空按鈕";
VUHDO_I18N_HEALTH_COLOR = "血量顏色";

VUHDO_I18N_HIDE = "隱藏";
VUHDO_I18N_LEAVE_ALONE = "保留原樣";
VUHDO_I18N_READY_CHECK = "準備確認";

VUHDO_I18N_HIDE_OUT_OF_COMBAT = "戰鬥中";
VUHDO_I18N_IMPORT = "匯入";
VUHDO_I18N_IMPORT_STRING_INVALID = "匯入的字串無效。";
VUHDO_I18N_REALLY_IMPORT = "是否確定要匯入?\n\n只應該匯入來自於可信賴的已知來源的字串。\n千萬不要匯入來自於不可信賴來源的字串。";

VUHDO_I18N_LUNAR_POWER = "星能";
VUHDO_I18N_MAELSTROM = "元能";
VUHDO_I18N_INSANITY = "瘋狂";
VUHDO_I18N_FURY = "魔怒";
VUHDO_I18N_PAIN = "魔痛";
VUHDO_I18N_SPEC_3 = "專精 3";
VUHDO_I18N_SPEC_4 = "專精 4";

VUHDO_I18N_ANNOUNCE_MASS_RES = "群體復活通報";

VUHDO_I18N_SPELL_TRACE = "法術追蹤";
VUHDO_I18N_SPELL_TRACE_EDIT_BOX = "輸入要追蹤的法術名稱或ID";
VUHDO_I18N_SPELL_TRACE_LIST = "法術追蹤清單";
VUHDO_I18N_DURATION = "持續時間";
VUHDO_I18N_SEC = "秒";
VUHDO_I18N_TRAIL_OF_LIGHT = "聖光顯跡";

VUHDO_I18N_BAR_GLOW_COLOR = "條列發光";
VUHDO_I18N_ICON_GLOW_COLOR = "圖示發光";
VUHDO_I18N_BLACKLIST_KEY_MODIFIES = "忽略清單組合按鍵";

VUHDO_I18N_NICKNAME = "Details!\n暱稱"

VUHDO_I18N_SHOW_OVERSHIELD = "顯示\n過量護盾";
VUHDO_I18N_OVERSHIELD_BAR = "過量護盾條";

VUHDO_I18N_SHOW_HEAL_ABSORB = "顯示\n治療吸收量";
VUHDO_I18N_HEAL_ABSORB_BAR = "治療吸收量條";

VUHDO_I18N_PLAYER = "玩家單位";
VUHDO_I18N_TARGET = "目標單位"
VUHDO_I18N_TARGET_TARGET = "目標的目標單位"
VUHDO_I18N_FOCUS_UNIT = "專注目標單位";
VUHDO_I18N_MOUSEOVER = "滑鼠指向單位";
VUHDO_I18N_MOUSEOVER_TARGET = "滑鼠指向單位的目標";
VUHDO_I18N_MOUSEOVER_TARGET_TARGET = "滑鼠指向單位的目標的目標";
VUHDO_I18N_TARGET_HARM = "目標單位 (僅限敵方)";
VUHDO_I18N_TARGET_TARGET_HARM = "目標的目標單位 (僅限敵方)";
VUHDO_I18N_FOCUS_HARM = "專注目標單位 (僅限敵方)";
VUHDO_I18N_MOUSEOVER_HARM = "滑鼠指向單位 (僅限敵方)";
VUHDO_I18N_MOUSEOVER_TARGET_HARM = "滑鼠指向單位的目標 (僅限敵方)";
VUHDO_I18N_MOUSEOVER_TARGET_TARGET_HARM = "滑鼠指向單位的目標的目標 (僅限敵方)";

VUHDO_I18N_CLOCK = "時鐘";

VUHDO_I18N_TEXT_ONLY = "只有文字";

VUHDO_I18N_SHOW_FRIENDLY = "顯示\n友方";
VUHDO_I18N_SHOW_ENEMY = "顯示\n敵方";
VUHDO_I18N_SHOW_ALL = "全部顯示";
VUHDO_I18N_BOSS_ONLY = "只有首領";

VUHDO_I18N_X = "X";
VUHDO_I18N_Y = "Y";

VUHDO_I18N_PRIVATE_AURAS = "非公開性的光環";

VUHDO_I18N_PETS_LAST = "寵物最後";

VUHDO_I18N_SHOW_EFFECTIVE = "有效血量";
VUHDO_I18N_DEBUFF_IGNORE_IMPORTED = "減益效果忽略清單已匯入成功。";

VUHDO_I18N_BLEED = "流血";

VUHDO_I18N_SQUARE_8 = "方塊 8";
VUHDO_I18N_SQUARE_9 = "方塊 9";
VUHDO_I18N_SHOW_ON_FRIENDLY = "友方\n顯示";
VUHDO_I18N_SHOW_ON_HOSTILE = "敵方\n顯示";
VUHDO_I18N_HOSTILE_SPELL_SOURCE = "敵方單位法術來源";

VUHDO_I18N_SEARCH_OPTIONS = "搜尋選項";

VUHDO_I18N_CLASS_GRADIENT_COLORS = "職業漸層色";
VUHDO_I18N_CLASS_GRADIENTS = "職業\n漸層";
VUHDO_I18N_LIFE_GRADIENT = "血量\n漸層";
VUHDO_I18N_MAX_COLOR = "最多顏色";

VUHDO_I18N_ENRAGE = "狂怒";
VUHDO_I18N_PURGEABLE_BUFFS = "可驅散\n增益";

VUHDO_I18N_LOAD_HOTS_ONLY_SLOTS = "只有欄位";