local _;

local VUHDO_PRIVATE_AURA_ORIENTATION_COMBO = {
	{ "HORIZONTAL", VUHDO_I18N_HORIZONTAL },
	{ "VERTICAL", VUHDO_I18N_VERTICAL },
};

local VUHDO_PRIVATE_AURA_DURATION_POSITION_COMBO = {
	{ "BOTTOM", VUHDO_I18N_PRIVATE_AURA_DURATION_BELOW },
	{ "TOP", VUHDO_I18N_PRIVATE_AURA_DURATION_ABOVE },
	{ "LEFT", VUHDO_I18N_LEFT },
	{ "RIGHT", VUHDO_I18N_RIGHT },
};

--
function VUHDO_privateAuraOrientationComboOnLoad(aComboBox)

	VUHDO_setComboModel(aComboBox, "VUHDO_PANEL_SETUP.#PNUM#.PRIVATE_AURA.orientation", VUHDO_PRIVATE_AURA_ORIENTATION_COMBO);

	return;

end



--
function VUHDO_privateAuraDurationPositionComboOnLoad(aComboBox)

	VUHDO_setComboModel(aComboBox, "VUHDO_PANEL_SETUP.#PNUM#.PRIVATE_AURA.durationPosition", VUHDO_PRIVATE_AURA_DURATION_POSITION_COMBO);

	return;

end