----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "zhTW" then
    return
end

local BtWQuests = BtWQuests
local i = {
    {
        name = "至暗之夜",
        type = "expansion",
        link = "btwquests:expansion:11",
    },
    {
        name = "戰教派",
        type = "chain",
        link = "btwquests:chain:120001",
        path = "至暗之夜",
    },
    {
        name = "戰教派",
        type = "quest",
        restrictions = 923,
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90764,
        },
        path = "至暗之夜 > 戰教派",
        tooltip = "quest:90764",
    },
    {
        name = "戰教派",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90759,
        },
        path = "至暗之夜 > 戰教派",
        tooltip = "quest:90759",
    },
    {
        name = "避免譴責",
        type = "quest",
        restrictions = 923,
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90761,
        },
        path = "至暗之夜 > 戰教派",
        tooltip = "quest:90761",
    },
    {
        name = "避免譴責",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90760,
        },
        path = "至暗之夜 > 戰教派",
        tooltip = "quest:90760",
    },
    {
        name = "暮光高地",
        type = "quest",
        restrictions = 923,
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90763,
        },
        path = "至暗之夜 > 戰教派",
        tooltip = "quest:90763",
    },
    {
        name = "暮光高地",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90762,
        },
        path = "至暗之夜 > 戰教派",
        tooltip = "quest:90762",
    },
    {
        name = "至暗之夜服飾",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90765,
        },
        path = "至暗之夜 > 戰教派",
        tooltip = "quest:90765",
    },
    {
        name = "經認可的薩拉塔斯信徒",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90766,
        },
        path = "至暗之夜 > 戰教派",
        tooltip = "quest:90766",
    },
    {
        name = "更多末日",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90767,
        },
        path = "至暗之夜 > 戰教派",
        tooltip = "quest:90767",
    },
    {
        name = "廢話少說",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90768,
        },
        path = "至暗之夜 > 戰教派",
        tooltip = "quest:90768",
    },
    {
        name = "刃多雷之怒",
        type = "chain",
        link = "btwquests:chain:120010",
        path = "至暗之夜",
    },
    {
        name = "博學者奧姆里克",
        type = "npc",
        link = "btwquests:chain:120010",
        scrollTo = {
            type = "npc",
            id = 248153,
        },
        path = "至暗之夜 > 刃多雷之怒",
    },
    {
        name = "追尋繼續",
        type = "quest",
        link = "btwquests:chain:120010",
        scrollTo = {
            type = "quest",
            id = 92630,
        },
        path = "至暗之夜 > 刃多雷之怒",
        tooltip = "quest:92630",
    },
    {
        name = "憎惡挑戰",
        type = "quest",
        link = "btwquests:chain:120010",
        scrollTo = {
            type = "quest",
            id = 92631,
        },
        path = "至暗之夜 > 刃多雷之怒",
        tooltip = "quest:92631",
    },
    {
        name = "憤怒試煉",
        type = "quest",
        link = "btwquests:chain:120010",
        scrollTo = {
            type = "quest",
            id = 92632,
        },
        path = "至暗之夜 > 刃多雷之怒",
        tooltip = "quest:92632",
    },
}

BtWQuestsDatabase:AddSearchBuckets({
    ["斯"] = { i[10], },
    ["博"] = { i[14], },
    ["飾"] = { i[9], },
    ["徒"] = { i[10], },
    ["末"] = { i[11], },
    ["挑"] = { i[16], },
    ["地"] = { i[7], i[8], },
    ["刃"] = { i[13], },
    ["免"] = { i[5], i[6], },
    ["夜"] = { i[1], i[9], },
    ["煉"] = { i[17], },
    ["試"] = { i[17], },
    ["話"] = { i[12], },
    ["的"] = { i[10], },
    ["服"] = { i[9], },
    ["惡"] = { i[16], },
    ["責"] = { i[5], i[6], },
    ["認"] = { i[10], },
    ["薩"] = { i[10], },
    ["塔"] = { i[10], },
    ["續"] = { i[15], },
    ["拉"] = { i[10], },
    ["尋"] = { i[15], },
    ["繼"] = { i[15], },
    ["譴"] = { i[5], i[6], },
    ["追"] = { i[15], },
    ["克"] = { i[14], },
    ["可"] = { i[10], },
    ["里"] = { i[14], },
    ["姆"] = { i[14], },
    ["奧"] = { i[14], },
    ["者"] = { i[14], },
    ["更"] = { i[11], },
    ["學"] = { i[14], },
    ["暮"] = { i[7], i[8], },
    ["日"] = { i[11], },
    ["怒"] = { i[13], i[17], },
    ["雷"] = { i[13], },
    ["暗"] = { i[1], i[9], },
    ["多"] = { i[11], i[13], },
    ["少"] = { i[12], },
    ["憤"] = { i[17], },
    ["廢"] = { i[12], },
    ["教"] = { i[2], i[3], i[4], },
    ["派"] = { i[2], i[3], i[4], },
    ["信"] = { i[10], },
    ["高"] = { i[7], i[8], },
    ["避"] = { i[5], i[6], },
    ["說"] = { i[12], },
    ["憎"] = { i[16], },
    ["之"] = { i[1], i[9], i[13], },
    ["經"] = { i[10], },
    ["光"] = { i[7], i[8], },
    ["至"] = { i[1], i[9], },
    ["戰"] = { i[2], i[3], i[4], i[16], },
})
