----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "koKR" then
    return
end

local BtWQuests = BtWQuests
local i = {
    {
        name = "한밤",
        type = "expansion",
        link = "btwquests:expansion:11",
    },
    {
        name = "내부의 이교도",
        type = "chain",
        link = "btwquests:chain:120001",
        path = "한밤",
    },
    {
        name = "내부의 이교도",
        type = "quest",
        restrictions = 923,
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90764,
        },
        path = "한밤 > 내부의 이교도",
        tooltip = "quest:90764",
    },
    {
        name = "내부의 이교도",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90759,
        },
        path = "한밤 > 내부의 이교도",
        tooltip = "quest:90759",
    },
    {
        name = "비난을 피하는 법",
        type = "quest",
        restrictions = 923,
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90761,
        },
        path = "한밤 > 내부의 이교도",
        tooltip = "quest:90761",
    },
    {
        name = "비난을 피하는 법",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90760,
        },
        path = "한밤 > 내부의 이교도",
        tooltip = "quest:90760",
    },
    {
        name = "황혼의 고원",
        type = "quest",
        restrictions = 923,
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90763,
        },
        path = "한밤 > 내부의 이교도",
        tooltip = "quest:90763",
    },
    {
        name = "황혼의 고원",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90762,
        },
        path = "한밤 > 내부의 이교도",
        tooltip = "quest:90762",
    },
    {
        name = "한밤의 옷차림",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90765,
        },
        path = "한밤 > 내부의 이교도",
        tooltip = "quest:90765",
    },
    {
        name = "증명된 잘아타스의 신도",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90766,
        },
        path = "한밤 > 내부의 이교도",
        tooltip = "quest:90766",
    },
    {
        name = "짙어지는 파멸의 전조",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90767,
        },
        path = "한밤 > 내부의 이교도",
        tooltip = "quest:90767",
    },
    {
        name = "교단 색출",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90768,
        },
        path = "한밤 > 내부의 이교도",
        tooltip = "quest:90768",
    },
    {
        name = "렌도레이의 분노",
        type = "chain",
        link = "btwquests:chain:120010",
        path = "한밤",
    },
    {
        name = "마법학자 엄브릭",
        type = "npc",
        link = "btwquests:chain:120010",
        scrollTo = {
            type = "npc",
            id = 248153,
        },
        path = "한밤 > 렌도레이의 분노",
    },
    {
        name = "계속되는 추적",
        type = "quest",
        link = "btwquests:chain:120010",
        scrollTo = {
            type = "quest",
            id = 92630,
        },
        path = "한밤 > 렌도레이의 분노",
        tooltip = "quest:92630",
    },
    {
        name = "끔찍한 시련의 연속",
        type = "quest",
        link = "btwquests:chain:120010",
        scrollTo = {
            type = "quest",
            id = 92631,
        },
        path = "한밤 > 렌도레이의 분노",
        tooltip = "quest:92631",
    },
    {
        name = "분노의 시련",
        type = "quest",
        link = "btwquests:chain:120010",
        scrollTo = {
            type = "quest",
            id = 92632,
        },
        path = "한밤 > 렌도레이의 분노",
        tooltip = "quest:92632",
    },
}

BtWQuestsDatabase:AddSearchBuckets({
    ["피"] = { i[5], i[6], },
    ["의"] = { i[2], i[3], i[4], i[7], i[8], i[9], i[10], i[11], i[13], i[16], i[17], },
    ["혼"] = { i[7], i[8], },
    ["신"] = { i[10], },
    ["출"] = { i[12], },
    ["도"] = { i[2], i[3], i[4], i[10], i[13], },
    ["옷"] = { i[9], },
    ["단"] = { i[12], },
    ["하"] = { i[5], i[6], },
    ["색"] = { i[12], },
    ["황"] = { i[7], i[8], },
    ["한"] = { i[1], i[9], i[16], },
    ["짙"] = { i[11], },
    ["추"] = { i[15], },
    ["련"] = { i[16], i[17], },
    ["시"] = { i[16], i[17], },
    ["브"] = { i[14], },
    ["끔"] = { i[16], },
    ["찍"] = { i[16], },
    ["어"] = { i[11], },
    ["법"] = { i[5], i[6], i[14], },
    ["적"] = { i[15], },
    ["노"] = { i[13], i[17], },
    ["난"] = { i[5], i[6], },
    ["림"] = { i[9], },
    ["밤"] = { i[1], i[9], },
    ["속"] = { i[15], i[16], },
    ["타"] = { i[10], },
    ["학"] = { i[14], },
    ["는"] = { i[5], i[6], i[11], i[15], },
    ["계"] = { i[15], },
    ["잘"] = { i[10], },
    ["릭"] = { i[14], },
    ["엄"] = { i[14], },
    ["마"] = { i[14], },
    ["자"] = { i[14], },
    ["고"] = { i[7], i[8], },
    ["파"] = { i[11], },
    ["을"] = { i[5], i[6], },
    ["되"] = { i[15], },
    ["레"] = { i[13], },
    ["된"] = { i[10], },
    ["분"] = { i[13], i[17], },
    ["렌"] = { i[13], },
    ["연"] = { i[16], },
    ["이"] = { i[2], i[3], i[4], i[13], },
    ["증"] = { i[10], },
    ["조"] = { i[11], },
    ["전"] = { i[11], },
    ["스"] = { i[10], },
    ["교"] = { i[2], i[3], i[4], i[12], },
    ["지"] = { i[11], },
    ["아"] = { i[10], },
    ["원"] = { i[7], i[8], },
    ["비"] = { i[5], i[6], },
    ["부"] = { i[2], i[3], i[4], },
    ["멸"] = { i[11], },
    ["명"] = { i[10], },
    ["내"] = { i[2], i[3], i[4], },
    ["차"] = { i[9], },
})
