----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "zhCN" then
    return
end

local BtWQuests = BtWQuests
local i = {
    {
        name = "至暗之夜",
        type = "expansion",
        link = "btwquests:expansion:11",
    },
    {
        name = "密教的渗透",
        type = "chain",
        link = "btwquests:chain:120001",
        path = "至暗之夜",
    },
    {
        name = "密教的渗透",
        type = "quest",
        restrictions = 923,
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90764,
        },
        path = "至暗之夜 > 密教的渗透",
        tooltip = "quest:90764",
    },
    {
        name = "密教的渗透",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90759,
        },
        path = "至暗之夜 > 密教的渗透",
        tooltip = "quest:90759",
    },
    {
        name = "避责之策",
        type = "quest",
        restrictions = 923,
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90761,
        },
        path = "至暗之夜 > 密教的渗透",
        tooltip = "quest:90761",
    },
    {
        name = "避责之策",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90760,
        },
        path = "至暗之夜 > 密教的渗透",
        tooltip = "quest:90760",
    },
    {
        name = "暮光高地",
        type = "quest",
        restrictions = 923,
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90763,
        },
        path = "至暗之夜 > 密教的渗透",
        tooltip = "quest:90763",
    },
    {
        name = "暮光高地",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90762,
        },
        path = "至暗之夜 > 密教的渗透",
        tooltip = "quest:90762",
    },
    {
        name = "午夜教袍",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90765,
        },
        path = "至暗之夜 > 密教的渗透",
        tooltip = "quest:90765",
    },
    {
        name = "萨拉塔斯的虔信徒",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90766,
        },
        path = "至暗之夜 > 密教的渗透",
        tooltip = "quest:90766",
    },
    {
        name = "末日加倍",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90767,
        },
        path = "至暗之夜 > 密教的渗透",
        tooltip = "quest:90767",
    },
    {
        name = "剪除邪教",
        type = "quest",
        link = "btwquests:chain:120001",
        scrollTo = {
            type = "quest",
            id = 90768,
        },
        path = "至暗之夜 > 密教的渗透",
        tooltip = "quest:90768",
    },
    {
        name = "朗多雷的怒火",
        type = "chain",
        link = "btwquests:chain:120010",
        path = "至暗之夜",
    },
    {
        name = "魔导师乌布里克",
        type = "npc",
        link = "btwquests:chain:120010",
        scrollTo = {
            type = "npc",
            id = 248153,
        },
        path = "至暗之夜 > 朗多雷的怒火",
    },
    {
        name = "追捕继续",
        type = "quest",
        link = "btwquests:chain:120010",
        scrollTo = {
            type = "quest",
            id = 92630,
        },
        path = "至暗之夜 > 朗多雷的怒火",
        tooltip = "quest:92630",
    },
    {
        name = "可憎护手",
        type = "quest",
        link = "btwquests:chain:120010",
        scrollTo = {
            type = "quest",
            id = 92631,
        },
        path = "至暗之夜 > 朗多雷的怒火",
        tooltip = "quest:92631",
    },
    {
        name = "愤怒试炼",
        type = "quest",
        link = "btwquests:chain:120010",
        scrollTo = {
            type = "quest",
            id = 92632,
        },
        path = "至暗之夜 > 朗多雷的怒火",
        tooltip = "quest:92632",
    },
}

BtWQuestsDatabase:AddSearchBuckets({
    ["除"] = { i[12], },
    ["责"] = { i[5], i[6], },
    ["剪"] = { i[12], },
    ["午"] = { i[9], },
    ["渗"] = { i[2], i[3], i[4], },
    ["徒"] = { i[10], },
    ["末"] = { i[11], },
    ["透"] = { i[2], i[3], i[4], },
    ["地"] = { i[7], i[8], },
    ["光"] = { i[7], i[8], },
    ["夜"] = { i[1], i[9], },
    ["密"] = { i[2], i[3], i[4], },
    ["多"] = { i[13], },
    ["的"] = { i[2], i[3], i[4], i[10], i[13], },
    ["萨"] = { i[10], },
    ["试"] = { i[17], },
    ["教"] = { i[2], i[3], i[4], i[9], i[12], },
    ["愤"] = { i[17], },
    ["继"] = { i[15], },
    ["袍"] = { i[9], },
    ["手"] = { i[16], },
    ["拉"] = { i[10], },
    ["斯"] = { i[10], },
    ["憎"] = { i[16], },
    ["可"] = { i[16], },
    ["塔"] = { i[10], },
    ["克"] = { i[14], },
    ["避"] = { i[5], i[6], },
    ["师"] = { i[14], },
    ["追"] = { i[15], },
    ["里"] = { i[14], },
    ["邪"] = { i[12], },
    ["导"] = { i[14], },
    ["续"] = { i[15], },
    ["暮"] = { i[7], i[8], },
    ["日"] = { i[11], },
    ["炼"] = { i[17], },
    ["捕"] = { i[15], },
    ["暗"] = { i[1], },
    ["火"] = { i[13], },
    ["魔"] = { i[14], },
    ["乌"] = { i[14], },
    ["倍"] = { i[11], },
    ["雷"] = { i[13], },
    ["怒"] = { i[13], i[17], },
    ["信"] = { i[10], },
    ["至"] = { i[1], },
    ["虔"] = { i[10], },
    ["护"] = { i[16], },
    ["布"] = { i[14], },
    ["之"] = { i[1], i[5], i[6], },
    ["策"] = { i[5], i[6], },
    ["加"] = { i[11], },
    ["朗"] = { i[13], },
    ["高"] = { i[7], i[8], },
})
