-- Postal Locale File
-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/postal/localization/

local AL3 = LibStub("AceLocale-3.0")
local debug = false
--[===[@debug@
debug = true
--@end-debug@]===]

local L = AL3:NewLocale("Postal", "enUS", true, debug)
if L then
L["|cffeda55fAlt-Click|r to send this item to %s."] = true
L["|cffeda55fControl-Click|r to attach similar items."] = true
L["|cffeda55fCtrl-Click|r to return it to sender."] = true
L["|cffeda55fShift-Click|r to take the contents."] = true
L[ [=[|cFFFFCC00*|r A default recipient name can be specified by right clicking on a button.
|cFFFFCC00*|r Which bags are used by this feature can be set in the main menu.]=] ] = true
L[ [=[|cFFFFCC00*|r Feature is not supported for mail sent with money attached or sent COD.
|cFFFFCC00*|r Feature is not supported for mail sent with stackable items attached.
|cFFFFCC00*|r Forward button will be disabled in these cases.]=] ] = true
L[ [=[|cFFFFCC00*|r Selected mail will be batch opened or returned to sender by clicking Open or Return.
|cFFFFCC00*|r You can Shift-Click 2 checkboxes to mass select every mail between the 2 checkboxes.
|cFFFFCC00*|r You can Ctrl-Click a checkbox to mass select or unselect every mail from that sender.
|cFFFFCC00*|r Select will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r Select will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = true
L[ [=[|cFFFFCC00*|r Shift-Click to take item/money from mail.
|cFFFFCC00*|r Ctrl-Click to return mail.
|cFFFFCC00*|r Alt-Click to move an item from your inventory to the current outgoing mail (same as right click in default UI).]=] ] = true
L[ [=[|cFFFFCC00*|r Simple filters are available for various mail types.
|cFFFFCC00*|r Shift-Click the Open All button to override the filters and take ALL mail.
|cFFFFCC00*|r OpenAll will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r OpenAll will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = true
L[ [=[|cFFFFCC00*|r This module will list your contacts, friends, guild mates, alts and track the last 10 people you mailed.
|cFFFFCC00*|r It will also autocomplete all names in your BlackBook.]=] ] = true
L["A button that collects all attachments and coins from mail."] = true
L["Add check boxes to the inbox for multiple mail operations."] = true
L["Add Contact"] = true
L["Add multiple item mail tooltips"] = true
L["Adds a contact list next to the To: field."] = true
L["AH-related mail"] = true
L["All Alts"] = true
L["Allows you to copy the contents of a mail."] = true
L["Allows you to forward the contents of a mail."] = true
L["Allows you to quickly attach different trade items types to a mail."] = true
L["Alts"] = true
L["Armor Enchantment"] = true
L["Auto-Attach similar items on Control-Click"] = true
L["Autofill last person mailed"] = true
L["Auto-Send on Alt-Click"] = true
L["BlackBook"] = true
L["Block incoming trade requests while in a mail session."] = true
L["CarbonCopy"] = true
L["Chat Output"] = true
L["Choose"] = true
L["Clear list"] = true
L["Cloth"] = true
L["Collected"] = true
L["Contacts"] = true
L["Cooking"] = true
L["Copy From"] = true
L["Copy this mail"] = true
L["Default"] = true
L["Default recipient:"] = true
L["Delete"] = true
L["Devices"] = true
L["Disable Blizzard's auto-completion popup menu"] = true
L["DoNotWant"] = true
L["Elemental"] = true
L["Enable Alt-Click to send mail"] = true
L["Enable for backpack"] = true
L["Enable for bag four"] = true
L["Enable for bag one"] = true
L["Enable for bag three"] = true
L["Enable for bag two"] = true
L["Enable for reagent bag"] = true
L["Enchanting"] = true
L["Exclude randoms you interacted with"] = true
L["Explosives"] = true
L["Express"] = true
L["Forward"] = true
L["Friends"] = true
L["Guild"] = true
L["Help"] = true
L["Herb"] = true
L["In Progress"] = true
L["Inscription"] = true
L["Item Enchantment"] = true
L["Jewelcrafting"] = true
L["Keep free space"] = true
L["Leather"] = true
L["Materials"] = true
L["Metal & Stone"] = true
L["Mouse click short cuts for mail."] = true
L["Name auto-completion options"] = true
L["New Profile"] = true
L["New Profile Name:"] = true
L["Non-AH related mail"] = true
L["Not all messages are shown, refreshing mailbox soon to continue Open All..."] = true
L["Not taking more items as there are now only %d regular bagslots free."] = true
L["Open"] = true
L["Open All"] = true
L["Open all Auction cancelled mail"] = true
L["Open all Auction expired mail"] = true
L["Open all Auction successful mail"] = true
L["Open all Auction won mail"] = true
L["Open all mail with attachments"] = true
L["Open all Outbid on mail"] = true
L["Open mail from the Postmaster"] = true
L["OpenAll"] = true
L["Opening Speed"] = true
L["Optional Reagents"] = true
L["Other"] = true
L["Other options"] = true
L["Part %d"] = true
L["Parts"] = true
L["Please post bugs or suggestions at the CurseForge forums thread at |cFF00FFFFhttp://www.curseforge.com/wow/addons/postal/issues|r. When posting bugs, indicate your locale and Postal's version number v%s."] = true
L["Prints the amount of money collected during a mail session."] = true
L["Processing Message"] = true
L["Profile"] = true
L["QuickAttach"] = true
L["Rake"] = true
L["Reagent"] = true
L["Recently Mailed"] = true
L["Refreshing mailbox..."] = true
L["Remove Contact"] = true
L["Reset Profile"] = true
L["Return"] = true
L["Select"] = true
L["Set subject field to value of coins sent if subject is blank."] = true
L["Shows a clickable visual icon as to whether a mail will be returned or deleted on expiry."] = true
L["Skipping"] = true
L["Some Messages May Have Been Skipped."] = true
L["Thaumaturge Vashreen"] = true
L["The Postmaster"] = true
L["There are %i more messages not currently shown."] = true
L["There are %i more messages not currently shown. More should become available in %i seconds."] = true
L["Trade Goods"] = true
L["TradeBlock"] = true
L["Use Mr.Plow after opening"] = true
L["Use Postal's auto-complete"] = true
L["Verbose mode"] = true
L["Weapon Enchantment"] = true
L["Wire"] = true

    if GetLocale() == "enUS" or GetLocale() == "enGB" then
        return
    end
end

L = AL3:NewLocale("Postal", "zhCN")
if L then
L["|cffeda55fAlt-Click|r to send this item to %s."] = "|cffeda55fAlt+点击|r将该物品发送给%s。"
L["|cffeda55fControl-Click|r to attach similar items."] = "|cffeda55fCtrl+点击|r附加类似物品。"
L["|cffeda55fCtrl-Click|r to return it to sender."] = "|cffeda55fCtrl+点击|r将信退给发件人。"
L["|cffeda55fShift-Click|r to take the contents."] = "|cffeda55fShift+点击|r获得该邮件的内容副本。"
L[ [=[|cFFFFCC00*|r A default recipient name can be specified by right clicking on a button.
|cFFFFCC00*|r Which bags are used by this feature can be set in the main menu.]=] ] = "|cFFCC00*|r 默认收件人姓名可以通过右键单击按钮来指定。|cFFCC00*|r 此功能使用的包可以设置在主菜单中。"
L[ [=[|cFFFFCC00*|r Feature is not supported for mail sent with money attached or sent COD.
|cFFFFCC00*|r Feature is not supported for mail sent with stackable items attached.
|cFFFFCC00*|r Forward button will be disabled in these cases.]=] ] = [=[|cFFFFCC00*|r 不支持发送附带资金的付款取信邮件。
|cFFFFCC00*|r 不支持附带可堆叠物品的邮件。
|cFFFFCC00*|r 在这些情况下，转发按钮将被禁用。]=]
L[ [=[|cFFFFCC00*|r Selected mail will be batch opened or returned to sender by clicking Open or Return.
|cFFFFCC00*|r You can Shift-Click 2 checkboxes to mass select every mail between the 2 checkboxes.
|cFFFFCC00*|r You can Ctrl-Click a checkbox to mass select or unselect every mail from that sender.
|cFFFFCC00*|r Select will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r Select will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r 選定的信件將批次開啟或通過點擊打開或返回來退還給發件人。
|cFFFFCC00*|r 您可以Shift-點擊兩個複選框來選擇兩個複選框之間的所有信件。
|cFFFFCC00*|r 您可以按Ctrl-點擊一個複選框來選定或取消選定一切來自該發件人的信件。
|cFFFFCC00*|r 選擇 永遠不會刪除任何信件(當所有附在信件的物品和金錢被提取後，遊戲會自動刪除郵箱裡沒有文字的信件) 。
|cFFFFCC00*|r 選擇 將跳過CoD信件和暴雪的信件。
|cFFFFCC00*|r 關閉 訊息模式 選項來停止當開啟信件時在聊天框的洗頻。]=]
L[ [=[|cFFFFCC00*|r Shift-Click to take item/money from mail.
|cFFFFCC00*|r Ctrl-Click to return mail.
|cFFFFCC00*|r Alt-Click to move an item from your inventory to the current outgoing mail (same as right click in default UI).]=] ] = [=[|cFFFFCC00*|r Shift+点击取走信中的金币或者物品。
|cFFFFCC00*|r Ctrl+点击退信。
|cFFFFCC00*|r Alt+点击背包中的物品，将其添加到附件中（同游戏本身的右键点击）。]=]
L[ [=[|cFFFFCC00*|r Simple filters are available for various mail types.
|cFFFFCC00*|r Shift-Click the Open All button to override the filters and take ALL mail.
|cFFFFCC00*|r OpenAll will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r OpenAll will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r 簡單的篩選器可用於篩選各種信件類型。
|cFFFFCC00*|r Shift-點擊 收取全部 按鈕將覆蓋所有的篩選器，並提取所有的信件。
|cFFFFCC00*|r 收取全部 永遠不會刪除任何信件(當所有附在信件的物品和金錢被提取後，遊戲會自動刪除郵箱裡沒有文字的信件) 。
|cFFFFCC00*|r 收取全部 將跳過付款取件信件和暴雪的信件。
|cFFFFCC00*|r 關閉 訊息模式 選項來停止當開啟信件時在聊天框的洗頻。]=]
L[ [=[|cFFFFCC00*|r This module will list your contacts, friends, guild mates, alts and track the last 10 people you mailed.
|cFFFFCC00*|r It will also autocomplete all names in your BlackBook.]=] ] = [=[|cFFFFCC00*|r该模块将列出你所有的联系人、好友、公会成员、小号和你最近发送邮件的10个人。
|cFFFFCC00*|r同时还将自动完成通讯簿中的所有名字。]=]
L["A button that collects all attachments and coins from mail."] = "收取所有邮件的附件和金币。"
L["Add check boxes to the inbox for multiple mail operations."] = "增加可选框以便于对多个邮件进行操作。"
L["Add Contact"] = "添加联系人"
L["Add multiple item mail tooltips"] = "添加多个物品的邮件提示"
L["Adds a contact list next to the To: field."] = "添加联系人列表到收件人栏。"
L["AH-related mail"] = "拍卖相关邮件"
L["All Alts"] = "全部小号"
L["Allows you to copy the contents of a mail."] = "允许你复制信的内容物。"
L["Allows you to forward the contents of a mail."] = "允许您转发邮件的内容。"
L["Allows you to quickly attach different trade items types to a mail."] = "允许您将不同类型的贸易物品快速附加到邮件中。"
L["Alts"] = "小号"
L["Armor Enchantment"] = "盔甲附魔"
L["Auto-Attach similar items on Control-Click"] = "Ctrl+点击自动附加相同物品"
L["Autofill last person mailed"] = "自动填写最后的收件人"
L["Auto-Send on Alt-Click"] = "Alt+点击自动发送"
L["BlackBook"] = "黑名单"
L["Block incoming trade requests while in a mail session."] = "在进行邮件操作中阻止交易请求。"
L["CarbonCopy"] = "复本"
L["Chat Output"] = "聊天输出"
L["Choose"] = "选择"
L["Clear list"] = "清空列表"
L["Cloth"] = "布"
L["Collected"] = "已收取"
L["Contacts"] = "联系人"
L["Cooking"] = "烹饪"
L["Copy From"] = "从…复制"
L["Copy this mail"] = "复制这封信"
L["Default"] = "违约"
L["Default recipient:"] = "默认收件人："
L["Delete"] = "删除"
L["Devices"] = "设备"
L["Disable Blizzard's auto-completion popup menu"] = "关闭暴雪的自动完成弹出菜单"
L["DoNotWant"] = "不想要"
L["Elemental"] = "元素"
L["Enable Alt-Click to send mail"] = "允许 Alt+点击发送邮件"
L["Enable for backpack"] = "为行囊启用"
L["Enable for bag four"] = "为背包4启用"
L["Enable for bag one"] = "为背包1启用"
L["Enable for bag three"] = "为背包3启用"
L["Enable for bag two"] = "为背包2启用"
L["Enable for reagent bag"] = "启用试剂袋"
L["Enchanting"] = "附魔"
L["Exclude randoms you interacted with"] = "防止你随意地受到影响"
L["Explosives"] = "爆炸物"
L["Express"] = "快件"
L["Forward"] = "转发"
L["Friends"] = "好友"
L["Guild"] = "公会"
L["Help"] = "帮助"
L["Herb"] = "草药"
L["In Progress"] = "处理中"
L["Inscription"] = "铭文"
L["Item Enchantment"] = "物品附魔"
L["Jewelcrafting"] = "珠宝加工"
L["Keep free space"] = "保留背包空间"
L["Leather"] = "皮革"
L["Materials"] = "材料"
L["Metal & Stone"] = "金属&矿石"
L["Mouse click short cuts for mail."] = "鼠标快捷方式。"
L["Name auto-completion options"] = "姓名自动完成选项"
L["New Profile"] = "新配置文件"
L["New Profile Name:"] = "新配置文件名称："
L["Non-AH related mail"] = "非拍卖相关邮件"
L["Not all messages are shown, refreshing mailbox soon to continue Open All..."] = "尚有邮件未能显示，请重整收件匣后继续开启…"
L["Not taking more items as there are now only %d regular bagslots free."] = "无法拿取更多物品，目前仅有%d个背包位置。"
L["Open"] = "打开"
L["Open All"] = "打开所有"
L["Open all Auction cancelled mail"] = "打开所有取消拍卖的邮件"
L["Open all Auction expired mail"] = "打开所有拍卖过期的邮件"
L["Open all Auction successful mail"] = "打开所有拍卖成功的邮件"
L["Open all Auction won mail"] = "打开所有赢得拍卖的邮件"
L["Open all mail with attachments"] = "打开所有带有附件的邮件"
L["Open all Outbid on mail"] = "打开所有超过出价的邮件"
L["Open mail from the Postmaster"] = "打开来自邮政长的邮件"
L["OpenAll"] = "打开所有"
L["Opening Speed"] = "收信速度"
L["Optional Reagents"] = "可选材料"
L["Other"] = "其他"
L["Other options"] = "其他选项"
L["Part %d"] = "第%d组"
L["Parts"] = "部件"
L["Please post bugs or suggestions at the CurseForge forums thread at |cFF00FFFFhttp://www.curseforge.com/wow/addons/postal/issues|r. When posting bugs, indicate your locale and Postal's version number v%s."] = "请到 CurseForge 的论坛|cFF00FFFFhttp://www.curseforge.com/wow/addons/postal/issues|r 报告 Bug 或者提交建议。报告 Bug 时请说明 Postal 的版本 v%s。"
L["Prints the amount of money collected during a mail session."] = "显示在一次邮件操作中所收到的金币。"
L["Processing Message"] = "正在处理邮件"
L["Profile"] = "配置文件"
L["QuickAttach"] = "快速附加"
L["Rake"] = "收款显示"
L["Reagent"] = "施法材料"
L["Recently Mailed"] = "最近邮寄"
L["Refreshing mailbox..."] = "重新整理邮箱…"
L["Remove Contact"] = "删除联系人"
L["Reset Profile"] = "重置配置文件"
L["Return"] = "退信"
L["Select"] = "选择"
L["Set subject field to value of coins sent if subject is blank."] = "在主题为空时将主题自动填充为金币数量。"
L["Shows a clickable visual icon as to whether a mail will be returned or deleted on expiry."] = "显示一个可点击的图标以确定邮件将被退回或是到期删除。"
L["Skipping"] = "忽略"
L["Some Messages May Have Been Skipped."] = "部分邮件可能被忽略。"
L["Thaumaturge Vashreen"] = "魔术师瓦西里恩"
L["The Postmaster"] = "邮政长"
L["There are %i more messages not currently shown."] = "还有%i或更多的邮件没有显示。"
L["There are %i more messages not currently shown. More should become available in %i seconds."] = "当前还有%i条信息没有显示。将在%i秒内显示。"
L["Trade Goods"] = "贸易品"
L["TradeBlock"] = "阻止交易"
L["Use Mr.Plow after opening"] = "打开邮件后使用 Mr.Plow 插件进行背包整理"
L["Use Postal's auto-complete"] = "使用 Postal 的自动完成"
L["Verbose mode"] = "消息模式"
L["Weapon Enchantment"] = "武器附魔"
L["Wire"] = "填充标题"

    return
end

L = AL3:NewLocale("Postal", "zhTW")
if L then
L["|cffeda55fAlt-Click|r to send this item to %s."] = "|cffeda55fAlt-點擊: |r將物品寄給%s。"
L["|cffeda55fControl-Click|r to attach similar items."] = "|cffeda55fCtrl-點擊|r附加類似物品。"
L["|cffeda55fCtrl-Click|r to return it to sender."] = "|cffeda55fCtrl-點擊: |r返回信件。"
L["|cffeda55fShift-Click|r to take the contents."] = "|cffeda55fShift-點擊: |r收取信件。"
L[ [=[|cFFFFCC00*|r A default recipient name can be specified by right clicking on a button.
|cFFFFCC00*|r Which bags are used by this feature can be set in the main menu.]=] ] = "|cFFCC00*|r 預設收件者姓名可以通過右鍵按鍵按鍵按鍵來指定。|cFFCC00*|r 此功能使用的包可以設置在主功能表中。"
L[ [=[|cFFFFCC00*|r Feature is not supported for mail sent with money attached or sent COD.
|cFFFFCC00*|r Feature is not supported for mail sent with stackable items attached.
|cFFFFCC00*|r Forward button will be disabled in these cases.]=] ] = [=[|cFFFFCC00*|r 不支援附加金錢或發送 COD 的郵件。
|cFFFFCC00*|r 不支援附加可堆疊物品的郵件。
|cFFFFCC00*|r 在這些情況下無法使用轉寄按鈕。]=]
L[ [=[|cFFFFCC00*|r Selected mail will be batch opened or returned to sender by clicking Open or Return.
|cFFFFCC00*|r You can Shift-Click 2 checkboxes to mass select every mail between the 2 checkboxes.
|cFFFFCC00*|r You can Ctrl-Click a checkbox to mass select or unselect every mail from that sender.
|cFFFFCC00*|r Select will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r Select will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r 点击打开或者退信，被选中的邮件会被批量打开或退回。
|cFFFFCC00*|r Shift+点击分别点击2封信的复选框，会将这2封信之前的所有新选中。
|cFFFFCC00*|r Ctrl+点击一封信的复选框，可以将所有来自该发件人的信选中或者取消选中。
|cFFFFCC00*|r 选中则不删除任何邮件（游戏默认当一封没有任何文字的信中的附件被取走之后自动删除该邮件）。
|cFFFFCC00*|r 选中将跳过付款取信的邮件以及来自暴雪的邮件。
|cFFFFCC00*|r 关闭消息模式，取信时聊天窗口将不再显示信息。]=]
L[ [=[|cFFFFCC00*|r Shift-Click to take item/money from mail.
|cFFFFCC00*|r Ctrl-Click to return mail.
|cFFFFCC00*|r Alt-Click to move an item from your inventory to the current outgoing mail (same as right click in default UI).]=] ] = [=[|cFFFFCC00*|r Shift-點擊將從郵件拿取物品/金錢。
|cFFFFCC00*|r 按Ctrl -點擊將退還信件。
|cFFFFCC00*|r 按Alt-點擊一件物品將從您的背包移到目前的外寄信件（等同UI預設的右鍵點擊 ） 。
|cFFFFCC00*|r 用滑鼠滾輪滾動收件匣。]=]
L[ [=[|cFFFFCC00*|r Simple filters are available for various mail types.
|cFFFFCC00*|r Shift-Click the Open All button to override the filters and take ALL mail.
|cFFFFCC00*|r OpenAll will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r OpenAll will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r各种邮件类型都有简单的过滤条件可用。
|cFFFFCC00*|rShift+点击“打开所有”按钮可以忽略这些过滤并收取所有邮件。
|cFFFFCC00*|r打开所有功能将不会删除任何邮件（无内容邮件将在附件和金钱被收取后自动删除）。
|cFFFFCC00*|r打开所有功能将会阻止付款取信邮件和暴雪发送的邮件。
|cFFFFCC00*|r请关闭详细信息选项来取消打开邮件时的聊天窗口信息。]=]
L[ [=[|cFFFFCC00*|r This module will list your contacts, friends, guild mates, alts and track the last 10 people you mailed.
|cFFFFCC00*|r It will also autocomplete all names in your BlackBook.]=] ] = [=[|cFFFFCC00*|r 此模組將您的聯絡人名單，朋友，公會隊友，分身，並追踪過去您曾郵寄的10人。
|cFFFFCC00*|r 它也將自動填寫已在您的黑名單內所有的名字。]=]
L["A button that collects all attachments and coins from mail."] = "一個收取全部附件及金錢的按鈕。"
L["Add check boxes to the inbox for multiple mail operations."] = "增加勾選框以供多重信件指令使用。"
L["Add Contact"] = "新增聯絡人"
L["Add multiple item mail tooltips"] = "新增多個物品的郵件提示框"
L["Adds a contact list next to the To: field."] = "在收件人輸入框旁邊添加一個聯絡列表。"
L["AH-related mail"] = "拍賣相關信件"
L["All Alts"] = "所有分身"
L["Allows you to copy the contents of a mail."] = "允許你複製信的內容物。"
L["Allows you to forward the contents of a mail."] = "讓你轉寄郵件的內容。"
L["Allows you to quickly attach different trade items types to a mail."] = "允許您將不同類型的交易物品快速附加到郵件中。"
L["Alts"] = "分身"
L["Armor Enchantment"] = "盔甲附魔"
L["Auto-Attach similar items on Control-Click"] = "Ctrl+點擊時自動附加相似物品"
L["Autofill last person mailed"] = "自動填寫最後曾郵寄的人名"
L["Auto-Send on Alt-Click"] = "Alt-點擊 自動發送"
L["BlackBook"] = "聯絡人名冊"
L["Block incoming trade requests while in a mail session."] = "在處理信件期間拒絕交易要求。"
L["CarbonCopy"] = "複本"
L["Chat Output"] = "聊天內容 輸出"
L["Choose"] = "選取"
L["Clear list"] = "清空列表"
L["Cloth"] = "布料"
L["Collected"] = "已領取"
L["Contacts"] = "聯絡人"
L["Cooking"] = "烹飪"
L["Copy From"] = "複製自"
L["Copy this mail"] = "複製這封信"
L["Default"] = "全局設定"
L["Default recipient:"] = "預設收件者："
L["Delete"] = "刪除"
L["Devices"] = "設備"
L["Disable Blizzard's auto-completion popup menu"] = "停用內建彈出自動完成的選單"
L["DoNotWant"] = "不想要"
L["Elemental"] = "元素"
L["Enable Alt-Click to send mail"] = "開啟Alt-點擊 發送信件"
L["Enable for backpack"] = "在背包啟用"
L["Enable for bag four"] = "在背包四啟用"
L["Enable for bag one"] = "在背包一啟用"
L["Enable for bag three"] = "在背包三啟用"
L["Enable for bag two"] = "在背包二啟用"
L["Enable for reagent bag"] = "啟用試劑袋"
L["Enchanting"] = "附魔"
L["Exclude randoms you interacted with"] = "防止你隨意地受到影響"
L["Explosives"] = "爆炸物"
L["Express"] = "快速收發"
L["Forward"] = "轉寄"
L["Friends"] = "好友"
L["Guild"] = "公會"
L["Help"] = "說明"
L["Herb"] = "草藥"
L["In Progress"] = "正在處理"
L["Inscription"] = "銘文"
L["Item Enchantment"] = "物品附魔"
L["Jewelcrafting"] = "珠寶製作"
L["Keep free space"] = "保持背包空位"
L["Leather"] = "皮革"
L["Materials"] = "材料"
L["Metal & Stone"] = "金屬與石頭"
L["Mouse click short cuts for mail."] = "點擊快速收發信件。"
L["Name auto-completion options"] = "名字自動完成選項"
L["New Profile"] = "新設定檔"
L["New Profile Name:"] = "新設定檔名稱:"
L["Non-AH related mail"] = "非拍賣相關信件"
L["Not all messages are shown, refreshing mailbox soon to continue Open All..."] = "尚有郵件未能顯示，請重整收件匣後繼續開啟..."
L["Not taking more items as there are now only %d regular bagslots free."] = "無法拾取更多物品，因目前只有%d個背包空位。"
L["Open"] = "開啟"
L["Open All"] = "收取全部"
L["Open all Auction cancelled mail"] = "打開所有取消拍賣的信件"
L["Open all Auction expired mail"] = "打開所有拍賣過期的信件"
L["Open all Auction successful mail"] = "打開所有拍賣成功的信件"
L["Open all Auction won mail"] = "打開所有赢得拍賣的信件"
L["Open all mail with attachments"] = "打開所有帶有附件的信件"
L["Open all Outbid on mail"] = "打開所有超過出價的信件"
L["Open mail from the Postmaster"] = "從Postmaster開啟郵件"
L["OpenAll"] = "收取全部"
L["Opening Speed"] = "收取速度"
L["Optional Reagents"] = "額外材料"
L["Other"] = "其他"
L["Other options"] = "其他選項"
L["Part %d"] = "分組%d"
L["Parts"] = "零件"
L["Please post bugs or suggestions at the CurseForge forums thread at |cFF00FFFFhttp://www.curseforge.com/wow/addons/postal/issues|r. When posting bugs, indicate your locale and Postal's version number v%s."] = "回報 bug 和建議請到 CurseForge 網站相關頁面 |cFF00FFFFhttp://www.curseforge.com/wow/addons/postal/issues|r。回報 bug 時請註明你所使用的介面語言和 Postal 版本編號 v%s。"
L["Prints the amount of money collected during a mail session."] = "顯示這次收取的金錢。"
L["Processing Message"] = "正在處理訊息"
L["Profile"] = "設定檔"
L["QuickAttach"] = "快速附加"
L["Rake"] = "報告"
L["Reagent"] = "材料"
L["Recently Mailed"] = "最近寄出的郵件"
L["Refreshing mailbox..."] = "重新整理收件匣..."
L["Remove Contact"] = "移除聯絡人"
L["Reset Profile"] = "重置設定檔"
L["Return"] = "返回"
L["Select"] = "選擇"
L["Set subject field to value of coins sent if subject is blank."] = "如果「主題:」空白，則欄位自動填寫寄件金額。"
L["Shows a clickable visual icon as to whether a mail will be returned or deleted on expiry."] = "視覺顯示點擊圖示是否郵件將被退回或刪除期滿。"
L["Skipping"] = "略過"
L["Some Messages May Have Been Skipped."] = "部份訊息可能會被略過。"
L["Thaumaturge Vashreen"] = "魔術師瓦西里恩"
L["The Postmaster"] = "郵政長"
L["There are %i more messages not currently shown."] = "有%i更多訊息沒有在目前顯示。"
L["There are %i more messages not currently shown. More should become available in %i seconds."] = "有%i更多訊息沒有在目前顯示。在%i秒內將會顯示更多。"
L["Trade Goods"] = "交易貨物"
L["TradeBlock"] = "拒絕交易"
L["Use Mr.Plow after opening"] = "在開啟郵件之後使用Mr.Plow 整理背包"
L["Use Postal's auto-complete"] = "使用Postal的自動完成"
L["Verbose mode"] = "訊息模式"
L["Weapon Enchantment"] = "武器附魔"
L["Wire"] = "自動填寫金額"

    return
end