if (GetLocale() ~= "zhTW") then
	return;
end
-- @EXACT = true: Translation has to be the exact(!) match in the clients language,
--                beacause it carries technical semantics
-- @EXACT = false: Translation can be done freely, because text is only descriptive
-- Class Names
-- @EXACT = false
VUHDO_I18N_WARRIORS="戰士"
VUHDO_I18N_ROGUES = "盜賊";
VUHDO_I18N_HUNTERS = "獵人";
VUHDO_I18N_PALADINS = "聖騎士";
VUHDO_I18N_MAGES = "法師";
VUHDO_I18N_WARLOCKS = "術士";
VUHDO_I18N_SHAMANS = "薩滿";
VUHDO_I18N_DRUIDS = "德魯伊";
VUHDO_I18N_PRIESTS = "牧師";
VUHDO_I18N_DEATH_KNIGHT = "死亡騎士";
VUHDO_I18N_MONKS = "武僧";
-- Group Model Names
-- @EXACT = false
VUHDO_I18N_GROUP = "隊伍";
VUHDO_I18N_OWN_GROUP = "我的隊伍";
-- Special Model Names
-- @EXACT = false
VUHDO_I18N_PETS = "寵物";
VUHDO_I18N_MAINTANKS = "主坦克";
VUHDO_I18N_PRIVATE_TANKS = "我負責的";
-- General Labels
-- @EXACT = false
VUHDO_I18N_OKAY = "確定";
VUHDO_I18N_CLASS = "職業";
VUHDO_I18N_PLAYER = "玩家";
-- VuhDoTooltip.lua
-- @EXACT = false
VUHDO_I18N_TT_POSITION = "|cffffb233位置:|r";
VUHDO_I18N_TT_GHOST = "<鬼魂>";
VUHDO_I18N_TT_DEAD = "<死亡>";
VUHDO_I18N_TT_AFK = "<暫離>";
VUHDO_I18N_TT_DND = "<勿擾>";
VUHDO_I18N_TT_LIFE = "|cffffb233血量:|r ";
VUHDO_I18N_TT_MANA = "|cffffb233法力值:|r ";
VUHDO_I18N_TT_LEVEL = "等級 ";
-- VuhDoPanel.lua
-- @EXACT = false
VUHDO_I18N_CHOOSE = "選擇";
VUHDO_I18N_DRAG = "拖曳";
VUHDO_I18N_REMOVE = "移除";
VUHDO_I18N_ME = "自己!";
VUHDO_I18N_TYPE = "類型";
VUHDO_I18N_VALUE = "數值";
VUHDO_I18N_SPECIAL = "特殊";
VUHDO_I18N_BUFF_ALL = "全部";
VUHDO_I18N_SHOW_BUFF_WATCH = "顯示增益監控";
-- Chat messages
-- @EXACT = false
VUHDO_I18N_COMMAND_LIST = "\n|cffffe566 - [ VuhDo 指令 ] -|r\n" ..
"|cffffe566opt|r[ions] - VuhDo 設定選項\n" ..
"|cffffe566res|r[et] - 重設面板位置\n" ..
"|cffffe566lock|r - 鎖定/解鎖面板\n" ..
"|cffffe566mm, map, minimap|r - 顯示/隱藏小地圖按鈕\n" ..
"|cffffe566compart|r[ment] - 顯示/隱藏插件選單圖示\n" ..
"|cffffe566show, hide, toggle|r - 開啟/關閉面板\n" ..
"|cffffe566load|r - [設定檔],[按鍵配置]\n" ..
"[broad]|cffffe566cast, mt|r[s] - 同步主坦克\n" ..
"|cffffe566role|r - 重置玩家角色\n" ..
"|cffffe566ab|r[out] - 關於這個插件\n" ..
"|cffffe566help,?|r - 指令說明\n";
VUHDO_I18N_BAD_COMMAND = "參數錯誤! 請輸入 '/vuhdo help' 或 '/vd ?' 瀏覽指令說明。";
VUHDO_I18N_CHAT_SHOWN = "|cffffe566已顯示|r。";
VUHDO_I18N_CHAT_HIDDEN = "|cffffe566已隱藏|r。";
VUHDO_I18N_MM_ICON = "小地圖按鈕";
VUHDO_I18N_MTS_BROADCASTED = "主坦克已經同步到團隊";
VUHDO_I18N_PANELS_SHOWN = "治療面板|cffffe566已顯示|r。";
VUHDO_I18N_PANELS_HIDDEN = "治療面板|cffffe566已隱藏|r。";
VUHDO_I18N_LOCK_PANELS_PRE = "面板位置";
VUHDO_I18N_LOCK_PANELS_LOCKED = "|cffffe566已鎖定|r。";
VUHDO_I18N_LOCK_PANELS_UNLOCKED = "|cffffe566已解鎖|r。";
VUHDO_I18N_PANELS_RESET = "面板位置已重置。";
-- Config Pop-Up
-- @EXACT = false
VUHDO_I18N_ROLE = "角色";
VUHDO_I18N_PRIVATE_TANK = "我負責的";
VUHDO_I18N_SET_BUFF = "設定增益";
-- Minimap
-- @EXACT = false
VUHDO_I18N_VUHDO_OPTIONS = "巫毒設定選項";
VUHDO_I18N_PANEL_SETUP = "設定選項";
VUHDO_I18N_MM_TOOLTIP = "左鍵: 面板設定\n右鍵: 選單";
VUHDO_I18N_TOGGLES = "開/關";
VUHDO_I18N_LOCK_PANELS = "鎖定面板";
VUHDO_I18N_SHOW_PANELS = "顯示面板";
VUHDO_I18N_MM_BUTTON = "小地圖按鈕";
VUHDO_I18N_CLOSE = "關閉";
VUHDO_I18N_BROADCAST_MTS = "同步主坦克";
-- Buff categories
-- @EXACT = false
-- Priest
-- Shaman
VUHDO_I18N_BUFFC_FIRE_TOTEM = "火焰圖騰";
VUHDO_I18N_BUFFC_AIR_TOTEM = "風之圖騰";
VUHDO_I18N_BUFFC_EARTH_TOTEM = "大地圖騰";
VUHDO_I18N_BUFFC_WATER_TOTEM = "水之圖騰";
VUHDO_I18N_BUFFC_WEAPON_ENCHANT = "武器強化";
VUHDO_I18N_BUFFC_WEAPON_ENCHANT_2 = "副手武器強化";
VUHDO_I18N_BUFFC_SHIELDS = "盾";
-- Paladin
VUHDO_I18N_BUFFC_BLESSING = "祝福";
VUHDO_I18N_BUFFC_SEAL = "聖印";
-- Druids
-- Warlock
VUHDO_I18N_BUFFC_SKIN = "皮膚";
-- Mage
VUHDO_I18N_BUFFC_ARMOR_MAGE = "護甲";
-- Death Knight
VUHDO_BUFFC_PRESENCE    = "領域";
-- Warrior
VUHDO_I18N_BUFFC_SHOUT = "怒氣";
-- Hunter
VUHDO_I18N_BUFFC_ASPECT = "守護";
-- Monk
VUHDO_I18N_BUFFC_STANCE = "姿勢";

-- Key Binding Headers/Names
-- @EXACT = false
BINDING_HEADER_VUHDO_TITLE = "VuhDo - 巫毒治療框架";
BINDING_NAME_VUHDO_KEY_ASSIGN_1 = "滑鼠指向法術 1";
BINDING_NAME_VUHDO_KEY_ASSIGN_2 = "滑鼠指向法術 2";
BINDING_NAME_VUHDO_KEY_ASSIGN_3 = "滑鼠指向法術 3";
BINDING_NAME_VUHDO_KEY_ASSIGN_4 = "滑鼠指向法術 4";
BINDING_NAME_VUHDO_KEY_ASSIGN_5 = "滑鼠指向法術 5";
BINDING_NAME_VUHDO_KEY_ASSIGN_6 = "滑鼠指向法術 6";
BINDING_NAME_VUHDO_KEY_ASSIGN_7 = "滑鼠指向法術 7";
BINDING_NAME_VUHDO_KEY_ASSIGN_8 = "滑鼠指向法術 8";
BINDING_NAME_VUHDO_KEY_ASSIGN_9 = "滑鼠指向法術 9";
BINDING_NAME_VUHDO_KEY_ASSIGN_10 = "滑鼠指向法術 10";
BINDING_NAME_VUHDO_KEY_ASSIGN_11 = "滑鼠指向法術 11";
BINDING_NAME_VUHDO_KEY_ASSIGN_12 = "滑鼠指向法術 12";
BINDING_NAME_VUHDO_KEY_ASSIGN_13 = "滑鼠指向法術 13";
BINDING_NAME_VUHDO_KEY_ASSIGN_14 = "滑鼠指向法術 14";
BINDING_NAME_VUHDO_KEY_ASSIGN_15 = "滑鼠指向法術 15";
BINDING_NAME_VUHDO_KEY_ASSIGN_16 = "滑鼠指向法術 16";
BINDING_NAME_VUHDO_KEY_ASSIGN_SMART_BUFF = "智慧型增益";
VUHDO_I18N_MOUSE_OVER_BINDING = "鍵盤按鍵法術";
VUHDO_I18N_UNASSIGNED = "(未指定)";
-- #+V1.89
VUHDO_I18N_NO = "否";
VUHDO_I18N_UP = "上";
VUHDO_I18N_VEHICLES = "載具";
-- #+v1.94
VUHDO_I18N_DEFAULT_RES_ANNOUNCE = "復活吧, vuhdo, 我的勇士!";
-- #v+1.151
VUHDO_I18N_MAIN_ASSISTS = "主助攻";
-- VUHDO_OPTIONS_FONT_NAME = "Interface\\AddOns\\VuhDo\\Fonts\\ariblk.ttf";
VUHDO_OPTIONS_FONT_NAME = GameFontNormal:GetFont();
-- #v+1.169
-- #+v1.184
VUHDO_I18N_BW_CD = "冷卻";
VUHDO_I18N_BW_GO = "GO!";
VUHDO_I18N_BW_LOW = "低";
VUHDO_I18N_BW_N_A = "|cffff0000N/A|r";
VUHDO_I18N_BW_RNG_RED = "|cffff0000機率觸發|r";
VUHDO_I18N_BW_OK = "確定";
VUHDO_I18N_BW_RNG_YELLOW = "|cffffff00機率觸發|r";
VUHDO_I18N_PROMOTE_RAID_LEADER = "提升為團隊隊長";
VUHDO_I18N_PROMOTE_ASSISTANT = "提升為助理";
VUHDO_I18N_DEMOTE_ASSISTANT = "移除助理權限";
VUHDO_I18N_PROMOTE_MASTER_LOOTER = "提升為主要分裝";
VUHDO_I18N_MT_NUMBER = "主坦克 #";
VUHDO_I18N_ROLE_OVERRIDE = "重新指定角色";
VUHDO_I18N_MELEE_TANK = "近戰-坦克";
VUHDO_I18N_MELEE_DPS = "近戰-DPS";
VUHDO_I18N_RANGED_DPS = "遠程-DPS";
VUHDO_I18N_RANGED_HEALERS = "遠程-治療";
VUHDO_I18N_AUTO_DETECT = "<自動偵測>";
VUHDO_I18N_PROMOTE_ASSIST_MSG_1 = "已提升 |cffffe566";
VUHDO_I18N_PROMOTE_ASSIST_MSG_2 = "|r 為助理。";
VUHDO_I18N_DEMOTE_ASSIST_MSG_1 = "已移除 |cffffe566";
VUHDO_I18N_DEMOTE_ASSIST_MSG_2 = "|r 助理權限。";
VUHDO_I18N_RESET_ROLES = "重置角色";
VUHDO_I18N_LOAD_KEY_SETUP = "載入按鍵配置";
VUHDO_I18N_BUFF_ASSIGN_1 = "增益 |cffffe566";
VUHDO_I18N_BUFF_ASSIGN_2 = "|r 已給 |cffffe566";
VUHDO_I18N_BUFF_ASSIGN_3 = "|r";
VUHDO_I18N_MACRO_KEY_ERR_1 = "錯誤: 法術的鍵盤按鍵滑鼠指向巨集字數超過上限: ";
VUHDO_I18N_MACRO_KEY_ERR_2 = "/256 字元)。請試著減少自動施放選項!!!";
VUHDO_I18N_MACRO_NUM_ERR = "角色所能擁有的巨集總數超過上限! 無法建立滑鼠指向巨集給: ";
VUHDO_I18N_SMARTBUFF_ERR_1 = "VuhDo: 戰鬥中無法使用智慧型增益!";
VUHDO_I18N_SMARTBUFF_ERR_2 = "VuhDo: 沒有目標可供施放增益 ";
VUHDO_I18N_SMARTBUFF_ERR_3 = " 位玩家超出範圍無法施放 ";
VUHDO_I18N_SMARTBUFF_ERR_4 = "VuhDo: 沒有可以施放的增益。";
VUHDO_I18N_SMARTBUFF_OKAY_1 = "VuhDo: 正在施放增益 |cffffffff";
VUHDO_I18N_SMARTBUFF_OKAY_2 = "|r 給 ";
-- #+v1.189
VUHDO_I18N_UNKNOWN = "未知";
VUHDO_I18N_SELF = "自己";
VUHDO_I18N_MELEES = "近戰";
VUHDO_I18N_RANGED = "遠程";
-- #+1.196
VUHDO_I18N_OPTIONS_NOT_LOADED = ">>> 沒有載入 VuhDo 設定選項插件! <<<";
VUHDO_I18N_SPELL_LAYOUT_NOT_EXIST_1 = "錯誤: 法術配置設定 \"";
VUHDO_I18N_SPELL_LAYOUT_NOT_EXIST_2 = "\" 不存在。";
VUHDO_I18N_AUTO_ARRANG_1 = "隊伍人數已經變更為 ";
VUHDO_I18N_AUTO_ARRANG_2 = "。自動切換版面配置: \"";
-- #+1.209
VUHDO_I18N_OWN_GROUP_LONG = "我的隊伍";
VUHDO_I18N_TRACK_BUFFS_FOR = "追蹤增益 ...";
VUHDO_I18N_NO_FOCUS = "[沒有專注目標]";
VUHDO_I18N_NOT_AVAILABLE = "[ N/A ]";
-- #+1.237
VUHDO_I18N_TT_DISTANCE = "|cffffb233距離:|r";
VUHDO_I18N_TT_OF = " - ";
VUHDO_I18N_YARDS = "碼";
-- #+1.252
VUHDO_I18N_PANEL = "面板";
VUHDO_I18N_BOUQUET_AGGRO = "標籤: 仇恨";
VUHDO_I18N_BOUQUET_OUT_OF_RANGE = "標籤: 超出範圍";
VUHDO_I18N_BOUQUET_IN_RANGE = "標籤: 在範圍內";
VUHDO_I18N_BOUQUET_IN_YARDS = "標籤: 距離 < 碼";
VUHDO_I18N_BOUQUET_OTHER_HOTS = "標籤: 其他玩家的持續性治療";
VUHDO_I18N_BOUQUET_DEBUFF_MAGIC = "標籤: 法術減益";
VUHDO_I18N_BOUQUET_DEBUFF_DISEASE = "標籤: 疾病減益";
VUHDO_I18N_BOUQUET_DEBUFF_POISON = "標籤: 中毒減益";
VUHDO_I18N_BOUQUET_DEBUFF_CURSE = "標籤: 詛咒減益";
VUHDO_I18N_BOUQUET_CHARMED = "標籤: 魅惑";
VUHDO_I18N_BOUQUET_DEAD = "標籤: 死亡";
VUHDO_I18N_BOUQUET_DISCONNECTED = "標籤: 離線";
VUHDO_I18N_BOUQUET_AFK = "標籤: 暫離";
VUHDO_I18N_BOUQUET_PLAYER_TARGET = "標籤: 玩家目標";
VUHDO_I18N_BOUQUET_MOUSEOVER_TARGET = "標籤: 滑鼠指向單一";
VUHDO_I18N_BOUQUET_MOUSEOVER_GROUP = "標籤: 滑鼠指向隊伍";
VUHDO_I18N_BOUQUET_HEALTH_BELOW = "標籤: 血量 < %";
VUHDO_I18N_BOUQUET_MANA_BELOW = "標籤: 法力值 < %";
VUHDO_I18N_BOUQUET_THREAT_ABOVE = "標籤: 威脅值 > %";
VUHDO_I18N_BOUQUET_NUM_IN_CLUSTER = "標籤: 群組 >= 玩家";
VUHDO_I18N_BOUQUET_CLASS_COLOR = "標籤: 永遠使用職業顏色";
VUHDO_I18N_BOUQUET_ALWAYS = "標籤: 永遠固定顏色";
VUHDO_I18N_SWIFTMEND_POSSIBLE = "標籤: 能快速治療";
VUHDO_I18N_BOUQUET_MOUSEOVER_CLUSTER = "標籤: 群組，滑鼠指向";
VUHDO_I18N_THREAT_LEVEL_MEDIUM = "標籤: 威脅值，高";
VUHDO_I18N_THREAT_LEVEL_HIGH = "標籤: 威脅值，OT";
VUHDO_I18N_BOUQUET_STATUS_HEALTH = "狀態列: 血量 %";
VUHDO_I18N_BOUQUET_STATUS_MANA = "狀態列: 法力值 %";
VUHDO_I18N_BOUQUET_STATUS_OTHER_POWERS = "狀態列: 非法力值 %";
VUHDO_I18N_BOUQUET_STATUS_INCOMING = "狀態列: 獲得治療 %";
VUHDO_I18N_BOUQUET_STATUS_THREAT = "狀態列: 威脅值 %";
VUHDO_I18N_BOUQUET_NEW_ITEM_NAME = "-- 在這裡輸入增益/減益 --";
VUHDO_I18N_DEF_BOUQUET_TANK_COOLDOWNS = "坦克冷卻";
VUHDO_I18N_DEF_BOUQUET_PW_S_WEAKENED_SOUL = "真言術:盾 & 虛弱靈魂";
VUHDO_I18N_DEF_BOUQUET_MONK_STAGGER = "武僧醉仙緩勁";
VUHDO_I18N_DEF_BOUQUET_BORDER_MULTI_AGGRO = "邊框: 多邊 + 仇恨";
VUHDO_I18N_DEF_BOUQUET_BORDER_MULTI = "邊框: 多邊";
VUHDO_I18N_DEF_BOUQUET_BORDER_SIMPLE = "邊框: 單一";
VUHDO_I18N_DEF_BOUQUET_SWIFTMENDABLE = "能快速治療";
VUHDO_I18N_DEF_BOUQUET_MOUSEOVER_SINGLE = "滑鼠指向: 單一";
VUHDO_I18N_DEF_BOUQUET_MOUSEOVER_MULTI = "滑鼠指向: 多個";
VUHDO_I18N_DEF_BOUQUET_AGGRO_INDICATOR = "仇恨指示器";
VUHDO_I18N_DEF_BOUQUET_CLUSTER_MOUSE_HOVER = "群組: 滑鼠指向";
VUHDO_I18N_DEF_BOUQUET_THREAT_MARKS = "威脅值: 標記";
VUHDO_I18N_DEF_BOUQUET_BAR_MANA_ALL = "法力條: 所有能量";
VUHDO_I18N_DEF_BOUQUET_BAR_MANA_ONLY = "法力條: 只有法力";
VUHDO_I18N_DEF_BOUQUET_BAR_THREAT = "威脅值: 狀態列";
VUHDO_I18N_CUSTOM_ICON_NONE = "- 無 / 預設 -";
VUHDO_I18N_CUSTOM_ICON_GLOSSY = "光滑";
VUHDO_I18N_CUSTOM_ICON_MOSAIC = "馬賽克";
VUHDO_I18N_CUSTOM_ICON_CLUSTER = "群組";
VUHDO_I18N_CUSTOM_ICON_FLAT = "直線";
VUHDO_I18N_CUSTOM_ICON_SPOT = "點";
VUHDO_I18N_CUSTOM_ICON_CIRCLE = "圓";
VUHDO_I18N_CUSTOM_ICON_SKETCHED = "輪廓";
VUHDO_I18N_CUSTOM_ICON_RHOMB = "菱形";
VUHDO_I18N_ERROR_NO_PROFILE = "錯誤: 沒有這個名稱的設定檔: ";
VUHDO_I18N_PROFILE_LOADED = "已載入設定檔: ";
VUHDO_I18N_PROFILE_SAVED = "已儲存設定檔: ";
VUHDO_I18N_PROFILE_OVERWRITE_1 = "設定檔";
VUHDO_I18N_PROFILE_OVERWRITE_2 = "是由其他角色所使用";
VUHDO_I18N_PROFILE_OVERWRITE_3 = "\n- 取代: 覆蓋並取代已有的設定檔。\n- 複製: 建立並儲存新的複本，保留原有的設定檔。";
VUHDO_I18N_COPY = "複製";
VUHDO_I18N_OVERWRITE = "取代";
VUHDO_I18N_DISCARD = "放棄";
-- 2.0, alpha #2
VUHDO_I18N_DEF_BAR_BACKGROUND_SOLID = "背景: 固定顏色";
VUHDO_I18N_DEF_BAR_BACKGROUND_CLASS_COLOR = "背景: 職業顏色";
-- 2.0 alpha #9
VUHDO_I18N_BOUQUET_DEBUFF_BAR_COLOR = "標籤: 減益，根據設定";
-- 2.0 alpha #11
VUHDO_I18N_DEF_BOUQUET_BAR_HEALTH = "血量 (通用，漸層)";
VUHDO_I18N_UPDATE_RAID_TARGET = "標籤: 團隊目標顏色";
VUHDO_I18N_BOUQUET_OVERHEAL_HIGHLIGHT = "顏色: 顯示標示過量治療";
VUHDO_I18N_BOUQUET_EMERGENCY_COLOR = "顏色: 緊急";
VUHDO_I18N_BOUQUET_HEALTH_ABOVE = "標籤: 血量 > %";
VUHDO_I18N_BOUQUET_RESURRECTION = "標籤: 復活";
VUHDO_I18N_BOUQUET_STACKS_COLOR = "顏色: 層數";
-- 2.1
VUHDO_I18N_DEF_BOUQUET_BAR_HEALTH_SOLID = "血量 (通用，固定顏色)";
VUHDO_I18N_DEF_BOUQUET_BAR_HEALTH_CLASS_COLOR = "血量 (通用，職業顏色)";
-- 2.9
VUHDO_I18N_NO_TARGET = "[沒有目標]";
VUHDO_I18N_TT_LEFT = " 左鍵: ";
VUHDO_I18N_TT_RIGHT = " 右鍵: ";
VUHDO_I18N_TT_MIDDLE = " 中鍵: ";
VUHDO_I18N_TT_BTN_4 = " 按鍵 4: ";
VUHDO_I18N_TT_BTN_5 = " 按鍵 5: ";
VUHDO_I18N_TT_WHEEL_UP = " 滾輪向上: ";
VUHDO_I18N_TT_WHEEL_DOWN = " 滾輪向下: ";
-- 2.13
VUHDO_I18N_BOUQUET_CLASS_ICON = "圖示: 職業";
VUHDO_I18N_BOUQUET_RAID_ICON = "圖示: 團隊標記";
VUHDO_I18N_BOUQUET_ROLE_ICON = "圖示: 角色";
-- 2.18
VUHDO_I18N_LOAD_PROFILE = "載入設定檔";
-- 2.20
VUHDO_I18N_DC_SHIELD_NO_MACROS = "這個角色已無可用的巨集欄位... d/c 盾已暫時停用。";
VUHDO_I18N_BROKER_TOOLTIP_1 = "|cffffff00左鍵|r 設定選項";
VUHDO_I18N_BROKER_TOOLTIP_2 = "|cffffff00右鍵|r 功能選單";
-- 2.54
VUHDO_I18N_HOURS = "小時";
VUHDO_I18N_MINS = "分";
VUHDO_I18N_SECS = "秒";
-- 2.65
VUHDO_I18N_BOUQUET_CUSTOM_DEBUFF = "圖示: 自訂減益";
-- 2.66
VUHDO_I18N_OFF = "關閉";
VUHDO_I18N_GHOST = "鬼魂";
VUHDO_I18N_RIP = "死亡";
VUHDO_I18N_DC = "斷線";
VUHDO_I18N_FOC = "專注";
VUHDO_I18N_TAR = "目標";
VUHDO_I18N_VEHICLE = "載具";
-- 2.67
VUHDO_I18N_BUFF_WATCH = "增益監控";
VUHDO_I18N_HOTS = "持續治療";
VUHDO_I18N_DEBUFFS = "減益";
VUHDO_I18N_BOUQUET_PLAYER_FOCUS = "標籤: 玩家專注目標";
-- 2.69
VUHDO_I18N_SIDE_BAR_LEFT = "左側";
VUHDO_I18N_SIDE_BAR_RIGHT = "右側";
VUHDO_I18N_OWN_PET = "我的寵物";
-- 2.72
VUHDO_I18N_SPELL = "法術";
VUHDO_I18N_COMMAND = "指令";
VUHDO_I18N_MACRO = "巨集";
VUHDO_I18N_ITEM = "物品";
-- 2.75
VUHDO_I18N_ERR_NO_BOUQUET = "\"%s\" 嘗試關聯 \"%s\" 但它不存在!";

VUHDO_I18N_BOUQUET_HEALTH_BELOW_ABS = "標籤: 血量 < k";
VUHDO_I18N_BOUQUET_HEALTH_ABOVE_ABS = "標籤: 血量 > k";
VUHDO_I18N_SPELL_LAYOUT_NOT_EXIST = "法術配置設定 \"%s\" 不存在。";

--VUHDO_I18N_ADDON_WARNING = "WARNING: Addon |cffffffff\"%s\"|r is enabled along with VuhDo, which may be problematic. Reason: %s";
--VUHDO_I18N_MAY_CAUSE_LAGS = "May cause severe lags.";

VUHDO_I18N_DISABLE_BY_MIN_VERSION = "!!! VUHDO 已被停用 !!! 此版本 (%s) 是給 %d 或更高的魔獸版本使用的 !!!"
VUHDO_I18N_DISABLE_BY_MAX_VERSION = "!!! VUHDO 已被停用 !!! 此版本 (%s) 是給 %d 或更低的魔獸版本使用的 !!!"

VUHDO_I18N_BOUQUET_STATUS_ALTERNATE_POWERS = "狀態列: 特殊能量 %"
VUHDO_I18N_BOUQUET_ALTERNATE_POWERS_ABOVE = "標籤: 特殊能量 > %";
VUHDO_I18N_DEF_ALTERNATE_POWERS = "職業特殊能量";
VUHDO_I18N_DEF_TANK_CDS_EXTENDED = "坦克冷卻延長";
VUHDO_I18N_BOUQUET_HOLY_POWER_EQUALS = "標籤: 我的聖能 ==";
VUHDO_I18N_DEF_PLAYER_HOLY_POWER = "玩家聖能";
VUHDO_I18N_CUSTOM_ICON_ONE_THIRD = "三份: 一";
VUHDO_I18N_CUSTOM_ICON_TWO_THIRDS = "三份: 二"
VUHDO_I18N_CUSTOM_ICON_THREE_THIRDS = "三份: 三";
VUHDO_I18N_DEF_ROLE_ICON = "角色圖示";

VUHDO_I18N_DEF_BOUQUET_TARGET_HEALTH = "血量 (通用，目標)";

VUHDO_I18N_TAPPED_COLOR = "標籤: 無效目標";
VUHDO_I18N_ENEMY_STATE_COLOR = "顏色: 友方/敵方";
VUHDO_I18N_FRIEND_STATUS = "標籤: 友方";
VUHDO_I18N_FOE_STATUS = "標籤: 敵方";
VUHDO_I18N_BOUQUET_STATUS_ALWAYS_FULL = "狀態列: 永遠滿的";
VUHDO_I18N_BOUQUET_STATUS_FULL_IF_ACTIVE = "狀態列: 啟動時滿的";
VUHDO_I18N_AOE_ADVICE = "圖示: 團補建議";
VUHDO_I18N_DEF_AOE_ADVICE = "團補建議";

VUHDO_I18N_BOUQUET_DURATION_ABOVE = "標籤: 持續時間 > 秒";
VUHDO_I18N_BOUQUET_DURATION_BELOW = "標籤: 持續時間 < 秒";
VUHDO_I18N_DEF_WRACK = "賽斯特拉: 毀壞";

VUHDO_I18N_DEF_DIRECTION_ARROW = "方向箭頭";
VUHDO_I18N_BOUQUET_DIRECTION_ARROW = "方向箭頭";
VUHDO_I18N_DEF_RAID_LEADER = "圖示: 團隊隊長";
VUHDO_I18N_DEF_RAID_ASSIST = "圖示: 團隊助理";
VUHDO_I18N_DEF_MASTER_LOOTER = "圖示: 主要分裝";
VUHDO_I18N_DEF_PVP_STATUS = "圖示: PvP 狀態";

VUHDO_I18N_GRID_MOUSEOVER_SINGLE = "格子: 滑鼠指向單一";
VUHDO_I18N_GRID_BACKGROUND_BAR = "格子: 背景條";
VUHDO_I18N_DEF_BIT_O_GRID = "Bit'o'Grid";
VUHDO_I18N_DEF_VUHDO_ESQUE = "Vuhdo'esque";


VUHDO_I18N_DEF_ROLE_COLOR = "角色顏色";
VUHDO_I18N_BOUQUET_ROLE_TANK = "標籤: 坦克角色";
VUHDO_I18N_BOUQUET_ROLE_DAMAGE = "標籤: 傷害輸出角色";
VUHDO_I18N_BOUQUET_ROLE_HEALER = "標籤: 治療者角色";

VUHDO_I18N_BOUQUET_STACKS = "標籤: 層數 >";
VUHDO_I18N_DEF_PLAYER_CHI = "玩家真氣";

VUHDO_I18N_BOUQUET_TARGET_RAID_ICON = "圖示: 目標的團隊標記";
VUHDO_I18N_BOUQUET_OWN_CHI_EQUALS = "標籤: 我的真氣 ==";
VUHDO_I18N_CUSTOM_ICON_FOUR_THIRDS = "三份: 四";
VUHDO_I18N_CUSTOM_ICON_FIVE_THIRDS = "三份: 五";
VUHDO_I18N_DEF_RAID_CDS = "團隊冷卻";
VUHDO_I18N_BOUQUET_STATUS_CLASS_COLOR_IF_ACTIVE = "標籤: 啟動時使用職業顏色";

VUHDO_I18N_LETHAL_POISONS = "致命毒藥";
VUHDO_I18N_NON_LETHAL_POISONS = "非致命毒藥";
VUHDO_I18N_DEF_COUNTER_SHIELD_ABSORB = "計數器: 所有盾吸收量 #k";
VUHDO_I18N_BUFFC_WEAPON_ENCHANT_OFF = "武器強化 (副手)";

VUHDO_I18N_DEF_PVP_FLAGS="PvP 標籤";
VUHDO_I18N_DEF_STATUS_SHIELD = "狀態列: 盾";

VUHDO_I18N_TARGET = "目標";
VUHDO_I18N_FOCUS = "專注目標";
VUHDO_I18N_DEF_STATUS_OVERSHIELDED = "狀態列: 過量盾";

-- 3.65
VUHDO_I18N_BOUQUET_OUTSIDE_ZONE = "標籤: 玩家區域，外面";
VUHDO_I18N_BOUQUET_INSIDE_ZONE = "標籤: 玩家區域，裡面";
VUHDO_I18N_BOUQUET_WARRIOR_TANK = "標籤: 坦克角色，戰士";
VUHDO_I18N_BOUQUET_PALADIN_TANK = "標籤: 坦克角色，聖騎士";
VUHDO_I18N_BOUQUET_DK_TANK = "標籤: 坦克角色，死亡騎士";
VUHDO_I18N_BOUQUET_MONK_TANK = "標籤: 坦克角色，武僧";
VUHDO_I18N_BOUQUET_DRUID_TANK = "標籤: 坦克角色，德魯伊";

-- 3.66
VUHDO_I18N_BOUQUET_PALADIN_BEACON = "聖騎士信標";
VUHDO_I18N_BOUQUET_STATUS_EXCESS_ABSORB = "狀態列: 過量吸收 %";
VUHDO_I18N_BOUQUET_STATUS_TOTAL_ABSORB = "狀態列: 總吸收 %";

-- 3.67
VUHDO_I18N_NO_BOSS = "[沒有 NPC]";
VUHDO_I18N_BOSSES = "NPC";

-- 3.71
VUHDO_I18N_BOUQUET_CUSTOM_FLAG = "自訂標籤";
VUHDO_I18N_ERROR_CUSTOM_FLAG_LOAD = "{VuhDo} 錯誤: 自訂標籤驗證器沒有載入:";
VUHDO_I18N_ERROR_CUSTOM_FLAG_EXECUTE = "{VuhDo} 錯誤: 自訂標籤驗證器沒有執行:";
VUHDO_I18N_ERROR_CUSTOM_FLAG_BLOCKED = "{VuhDo} 錯誤: 自訂標籤驗證器嘗試呼叫被禁用的函數，這是不允許的。請記得只能匯入來源可以信賴的字串。";
VUHDO_I18N_ERROR_INVALID_VALIDATOR = "{VuhDo} 錯誤: 無效的驗證器:";

-- 3.72
VUHDO_I18N_BOUQUET_DEMON_HUNTER_TANK = "標籤: 坦克角色，惡魔獵人";
VUHDO_I18N_DEMON_HUNTERS = "惡魔獵人";

-- 3.77
VUHDO_I18N_DEF_COUNTER_OVERFLOW_ABSORB = "計數器: 傳奇+ 過量吸收 #k";

-- 3.79
VUHDO_I18N_DEFAULT_RES_ANNOUNCE_MASS = "正在群體復活!";

-- 3.81
VUHDO_I18N_BOUQUET_OVERFLOW_COUNTER = "傳奇+詞綴 溢流";

-- 3.82
VUHDO_I18N_SPELL_TRACE = "圖示: 法術追蹤";
VUHDO_I18N_DEF_SPELL_TRACE = "法術追蹤";
VUHDO_I18N_TRAIL_OF_LIGHT = "圖示: 聖光顯跡";
VUHDO_I18N_DEF_TRAIL_OF_LIGHT = "聖光顯跡";

-- 3.83
VUHDO_I18N_BOUQUET_STATUS_MANA_HEALER_ONLY = "狀態列: 法力 % (治療者專用)";
VUHDO_I18N_DEF_BOUQUET_BAR_MANA_HEALER_ONLY = "法力條: 法力 (治療者專用)";

-- 3.98
VUHDO_I18N_BOUQUET_HAS_SUMMON_ICON = "圖示: 已召喚";
VUHDO_I18N_DEF_BOUQUET_HAS_SUMMON = "召喚狀態圖示";
VUHDO_I18N_DEF_BOUQUET_ROLE_AND_SUMMON = "角色 & 召喚狀態圖示";

-- 3.99
VUHDO_I18N_BOUQUET_IS_PHASED = "圖示: 鏡像";
VUHDO_I18N_BOUQUET_IS_WAR_MODE_PHASED = "圖示: 戰爭模式鏡像";
VUHDO_I18N_DEF_BOUQUET_IS_PHASED = "鏡像圖示";

-- 3.101
VUHDO_I18N_DEF_PLAYER_COMBO_POINTS = "玩家連擊點數";
VUHDO_I18N_BOUQUET_OWN_COMBO_POINTS_EQUALS = "標籤: 擁有的連擊點數 ==";
VUHDO_I18N_DEF_PLAYER_SOUL_SHARDS = "玩家靈魂裂片";
VUHDO_I18N_BOUQUET_OWN_SOUL_SHARDS_EQUALS = "標籤: 擁有的靈魂裂片 ==";
VUHDO_I18N_DEF_PLAYER_RUNES = "玩家符文";
VUHDO_I18N_BOUQUET_OWN_RUNES_EQUALS = "標籤: 擁有的符文 ==";
VUHDO_I18N_DEF_PLAYER_ARCANE_CHARGES = "玩家祕法充能";
VUHDO_I18N_BOUQUET_OWN_ARCANE_CHARGES_EQUALS = "標籤: 擁有的祕法充能 ==";
VUHDO_I18N_DEBUFF_BLACKLIST_ADDED = "新增 \"[%s] %s\" 到減益黑名單。";

-- 3.104
VUHDO_I18N_PLAY_SOUND_FILE_ERR = "無法播放音效 \"%s\": %s";
VUHDO_I18N_PLAY_SOUND_FILE_DEBUFF_ERR = "無法播放標準減益的音效 \"%s\"。請到 '巫毒設定選項 > 減益 > 標準 > 減益音效' 更改設定。";
VUHDO_I18N_PLAY_SOUND_FILE_CUSTOM_DEBUFF_ERR = "無法播放音效 \"%s\" (屬於自訂減益 \"%s\")。請到 '巫毒設定選項 > 減益 > 自訂' 更改設定。";

-- 3.122
VUHDO_I18N_BOUQUET_STATUS_POWER_TANK_ONLY = "狀態列: 能量 % (坦克專用)";
VUHDO_I18N_DEF_BOUQUET_BAR_MANA_TANK_ONLY = "法力條: 能量 (坦克專用)";

-- 3.131
VUHDO_I18N_DEF_COUNTER_HEAL_ABSORB = "數量: 所有治療吸收量 #k";
VUHDO_I18N_DEF_STATUS_HEAL_ABSORB = "狀態列: 治療吸收量";

-- 3.135
VUHDO_I18N_TRINKET_1 = "飾品 1";
VUHDO_I18N_TRINKET_2 = "飾品 2";

-- 3.139
VUHDO_I18N_EVOKERS = "喚能師";

-- 3.143
VUHDO_I18N_BUFFC_EARTH_SHIELD = "大地之盾 (自己)";

-- 3.150
VUHDO_I18N_ADDON_COMPARTMENT_ICON = "插件選單圖示現在是";

-- 3.152
VUHDO_I18N_SPELL_TRACE_SINGLE = "圖示: 法術追蹤 (單一)";

-- 3.154
VUHDO_I18N_SPELL_TRACE_INCOMING = "圖示: 法術追蹤 (即將)";
VUHDO_I18N_SPELL_TRACE_HEAL = "圖示: 法術追蹤 (治療)";

-- 3.157
VUHDO_I18N_TEXT_PROVIDER_OVERHEAL = "過量治療: <#nk>";
VUHDO_I18N_TEXT_PROVIDER_OVERHEAL_PLUS = "過量治療: +<#n>k";
VUHDO_I18N_TEXT_PROVIDER_INCOMING_HEAL = "即將治療: <#nk>";
VUHDO_I18N_TEXT_PROVIDER_SHIELD_ABSORB = "盾吸收總量: <#nk>";
VUHDO_I18N_TEXT_PROVIDER_HEAL_ABSORB = "治療吸收總量: <#nk>";
VUHDO_I18N_TEXT_PROVIDER_THREAT = "仇恨值: <#n>%";
VUHDO_I18N_TEXT_PROVIDER_CHI = "真氣: <#n>";
VUHDO_I18N_TEXT_PROVIDER_HOLY_POWER = "聖能: <#n>";
VUHDO_I18N_TEXT_PROVIDER_COMBO_POINTS = "連擊點數: <#n>";
VUHDO_I18N_TEXT_PROVIDER_SOUL_SHARDS = "靈魂裂片: <#n>";
VUHDO_I18N_TEXT_PROVIDER_RUNES = "符文: <#n>";
VUHDO_I18N_TEXT_PROVIDER_ARCANE_CHARGES = "祕法充能: <#n>";
VUHDO_I18N_TEXT_PROVIDER_MANA_PERCENT = "法力: <#n>%";
VUHDO_I18N_TEXT_PROVIDER_MANA_PERCENT_TENTH = "法力: <#n/10%>";
VUHDO_I18N_TEXT_PROVIDER_MANA_UNIT_OF = "法力: <#n>/<#n>";
VUHDO_I18N_TEXT_PROVIDER_MANA_KILO_OF = "法力: <#nk>/<#nk>";
VUHDO_I18N_TEXT_PROVIDER_MANA = "法力: <#n>";
VUHDO_I18N_TEXT_PROVIDER_MANA_KILO = "法力: <#nk>";
VUHDO_I18N_BOUQUET_STATUS_HEALTH_IF_ACTIVE = "狀態列: 血量 % (啟用時)";

VUHDO_I18N_DEF_COUNTER_ACTIVE_AURAS = "計數: 作用中的狀態群組光環 #k";

VUHDO_I18N_BOUQUET_EVOKER_REVERSION = "喚能師 逆轉 (無回音)";
VUHDO_I18N_BOUQUET_EVOKER_REVERSION_ECHO = "喚能師 逆轉 (回音)";
VUHDO_I18N_BOUQUET_EVOKER_DREAM_BREATH = "喚能師 夢境之息 (無回音)";
VUHDO_I18N_BOUQUET_EVOKER_DREAM_BREATH_ECHO = "喚能師 夢境之息 (回音)";
VUHDO_I18N_BOUQUET_EVOKER_ALL_ECHO = "喚能師所有持續性治療回音";

VUHDO_I18N_TRAIL_OF_LIGHT_NEXT = "標籤: 聖光顯跡 (下一個)";
VUHDO_I18N_DEF_TRAIL_OF_LIGHT_NEXT = "聖光顯跡 (下一個)";
VUHDO_I18N_BOUQUET_DEBUFF_BLEED = "標籤: 流血減益";

VUHDO_I18N_DEF_SPELL_TRACE_INCOMING = "法術追蹤 (即將到來)";

VUHDO_I18N_BOUQUET_CHI_HARMONY_ICON_MINE = "圖示: 真氣和諧 (我的)";
VUHDO_I18N_DEF_BOUQUET_CHI_HARMONY_ICON_MINE = "真氣和諧 (我的)";
VUHDO_I18N_BOUQUET_CHI_HARMONY_ICON_OTHERS = "圖示: 真氣和諧 (他人)";
VUHDO_I18N_DEF_BOUQUET_CHI_HARMONY_ICON_OTHERS = "真氣和諧 (他人)";
VUHDO_I18N_BOUQUET_CHI_HARMONY_ICON_BOTH = "圖示: 真氣和諧 (都有)";
VUHDO_I18N_DEF_BOUQUET_CHI_HARMONY_ICON_BOTH = "真氣和諧 (都有)";

VUHDO_I18N_BOUQUET_DEBUFF_ENRAGE = "標籤: 減益 狂怒";