local _,rematch = ...
local L = rematch.localization

--[[
    This file has all the localized strings pulled out from the code. It's generated by a script that will
    append any new strings (and the version it's from) to the end of the file. If any are missing, let me
    know and I can re-run the script to add any missing ones.

    To create localizations for other languages, copy this file and replace the nils with localized strings
    then reach out to me via PM or comment on wowinterface, curse; or leave a post at warcraftpets.com in
    the Rematch 5.0 thread. Thanks!
]]

-- Version: 5.0.0-beta-20 --

-- cards\notes.lua
L["Undo"] = nil
L["Delete Notes"] = nil
L["Do you want to delete notes for team %s\124r?"] = nil
L["Do you want to delete notes for pet %s%s\124r?"] = nil
L["Don't Ask When Deleting Notes"] = nil

-- cards\petCard.lua
L["Pet Card"] = nil
L["Damage\nTaken"] = nil
L["from"] = nil
L["abilities"] = nil
L["Possible Breeds"] = nil
L["Stats as \124cff0070ddRare\124r level 25"] = nil
L["All breed data pulled from %s%s\124r"] = nil
L["No known breeds :("] = nil
L["When this team loads, your current leveling pet will go in this spot."] = nil
L["When this team loads, this spot will be ignored."] = nil
L["When this team loads, a random high level pet will go in this spot."] = nil
L["The pets for this target are not recorded due to this target not being notable."] = nil
L["Hold [%s] to view more about this pet."] = nil
L["This is an opponent pet."] = nil

-- cards\petCardStats.lua
L["Revoked"] = nil
L["This pet has been revoked, which means Blizzard withdrew your ability to use this pet.\n\nThis commonly happens when a pet no longer meet a condition for ownership, such as the Core Hound Pup requiring an authenticator attached to the account."] = nil
L["Can't Summon"] = nil
L["Expansion"] = nil
L["The World of Warcraft expansion this pet is from."] = nil
L["New Pet"] = nil
L["This pet was recently added to your collection."] = nil
L["This is the pet marker you've chosen for this pet. You can change the marker from the pet's right-click menu."] = nil
L["Slotted"] = nil
L["This pet is currently slotted in one of the three battle pet slots."] = nil
L["Favorite"] = nil
L["This pet is marked as a favorite from its right-click menu."] = nil
L["Leveling"] = nil
L["This pet is in Rematch's leveling queue."] = nil
L["Breed"] = nil
L["Determines how stats are distributed. All breed data is pulled from your installed %s%s\124r addon."] = nil
L["Teams"] = nil
L["%s Click to find all teams that include this specific pet."] = nil
L["%d Teams"] = nil
L["Not Tradable"] = nil
L["This pet cannot be caged or given to others."] = nil
L["No Trade"] = nil
L["Unique"] = nil
L["Only one copy of this pet can be owned at a time."] = nil
L["Strongest Vs"] = nil
L["These are the pet types this pet is strongest against. One or more of this pet's attack abilities will deal extra damage to these pet types."] = nil
L["vs "] = nil
L["Species ID"] = nil
L["All versions of this pet share this unique identifying number."] = nil
L["%s Click to search for all versions of this pet."] = nil

-- chrome\bottombar.lua
L["Save As"] = nil
L["Rematch"] = nil
L["Remove Rematch From Journal"] = nil
L["Uncheck this to restore the default pet journal.\n\nYou can still use Rematch in its standlone window, accessed via key binding, /rematch command or from the Minimap button if enabled in options."] = nil
L["You can also double-click a pet to summon or dismiss it."] = nil
L["Save As..."] = nil
L["Save the currently loaded pets to a new team."] = nil
L["Quickly save the currently loaded pets and abilities to the loaded team."] = nil

-- chrome\chromeMixins.lua
L["%s%d %s"] = nil
L["Team"] = nil

-- chrome\minimap.lua
L["%s Toggle Window\n%s Load Favorite Team"] = nil
L["Favorite Teams"] = nil
L["%sNo favorite teams :("] = nil

-- chrome\toolbar.lua
L["UNIQUE_PETS"] = nil
L["TOTAL_PETS"] = nil
-- L["Unique Pets: %s%d\124r\nTotal Pets: %s%d\124r%s"] = nil
L["\n\n%s Click for details"] = nil

-- chrome\toolbarButtons.lua
L["All pets are at full health."] = nil
L["Pet Level %d %s"] = nil
L["%s Dismiss Pet"] = nil
L["Summon Random Pet"] = nil
L["Random favorite pet"] = nil
L["Random from all pets"] = nil
L["%s%s"] = nil

-- dialogs\dialogMixins.lua
L["Level"] = nil
L["Min:"] = nil
L["Max:"] = nil
L["Health"] = nil
L["%s %s or %s"] = nil
L["Allow any"] = nil
L["Expected Damage Taken:"] = nil
L["Minimum Level"] = nil
L["This is the minimum level preferred for a leveling pet.\n\nLevels can be partial amounts. Level 4.33 is level 4 with 33% xp towards level 5."] = nil
L["Maximum Level"] = nil
L["This is the maximum level preferred for a leveling pet.\n\nLevels can be partial amounts. Level 23.45 is level 23 with 45% xp towards level 24."] = nil
L["Minimum Health"] = nil
L["This is the minimum health preferred for a leveling pet.\n\nThe queue will prefer leveling pets with at least this much health (adjusted by expected damage taken if any chosen)."] = nil
L["Maximum Health"] = nil
L["This is the maximum health preferred for a leveling pet."] = nil
L["Allow low-health and low-level Magic or Mechanical pets to ignore the Minimum Health or Level, since their racials allow them to often survive a hit that would ordinarily kill them."] = nil
L["Expected Damage Taken"] = nil
L["The minimum health of pets can be adjusted by the type of damage they are expected to receive."] = nil
L["Damage Expected: %s"] = nil
L["Minimum Health: %d"] = nil
L["  For %s pets: \124cffffffff%d"] = nil
L["Search Icons"] = nil
L[" Add"] = nil
L[" Delete"] = nil
L[" Up"] = nil
L[" Down"] = nil
L["Delete"] = nil
L["Up"] = nil
L["Down"] = nil
L["Choose a group for this team"] = nil
L["Group:"] = nil
L["Wins:"] = nil
L["Losses:"] = nil
L["Draws:"] = nil
L["Total Battles: %s%s"] = nil
L["None"] = nil
L["Win Rate: %d%%"] = nil
L["Include Preferences"] = nil
L["Include Notes"] = nil
L["When teams/groups share the same name:"] = nil
L["Create a new copy"] = nil
L["Overwrite existing one"] = nil
L["Won"] = nil
L["Lost"] = nil
L["Draw"] = nil
L["%s%d\124r Battles for %s%d\124r Teams"] = nil

-- dialogs\importDialog.lua
L["Import Teams"] = nil
L["Load"] = nil
L["Press Ctrl+V to paste from clipboard"] = nil
L["Prioritize Breed For Imports"] = nil
L["When importing teams, prefer pets that match the breed even if higher levels of other breeds are available."] = nil
L["Only Load This Team"] = nil
L["This will only load the team and not save it.\n\nThis is for importing teams you intend to use just once. You can still save the team afterwards if you want to keep it."] = nil
L["This is not a valid team import"] = nil
L["Groups to import"] = nil
L["Teams to import"] = nil
L["Names already used"] = nil
L["Some teams or groups have names already used"] = nil
L["This team has the same name as an existing team"] = nil
L["Teams with existing name"] = nil
L["Some teams have the same name as existing teams"] = nil

-- dialogs\saveDialog.lua
L["Save Team"] = nil
L["Overwrite Team"] = nil
L["New Copy"] = nil
L["Overwrite"] = nil
L["Another team already has this name. Overwrite it or create a new copy?"] = nil
L["Old %s"] = nil
L["New %s"] = nil
L["Saving Loaded Team"] = nil
L["Save team?"] = nil
L["Pets have changed. Confirm you want to update the team with these new pets."] = nil
L["Update team from this:"] = nil
L["To this:"] = nil
L["Sending Team"] = nil
L["Not yet implemented\n\nSending teams directly to other Rematch users will be added later in the beta."] = nil
L["Targets"] = nil
L["Preferences"] = nil
L["Wins"] = nil
L["Create a new copy of this team"] = nil
L["Another team has this name."] = nil
L["Edit Team"] = nil
L["Receiving Team"] = nil
L["Name:"] = nil
L["New Team"] = nil
L["Someone sent you a group!"] = nil
L["Leveling Preferences"] = nil
L["Leveling preferences override which pets are picked first in the leveling queue. All criteria are optional."] = nil
L["Battles Won By This Team"] = nil

-- dialogs\scriptFilter.lua
L["Unnamed Pets"] = nil
L["-- Collected pets that still have their original name.\n\nreturn petInfo.isOwned and not petInfo.customName"] = nil
L["Partially Leveled"] = nil
L["-- Pets that have earned some xp in battle.\n\nreturn petInfo.xp and petInfo.xp>0"] = nil
L["Pets Without Rares"] = nil
L["-- Collected battle pets that have no rare version.\n\nif not rares then\n  rares = {}\n  for petID in AllPetIDs() do\n    if select(5,C_PetJournal.GetPetStats(petID))==4 then\n      rares[C_PetJournal.GetPetInfoByPetID(petID)]=true\n    end\n  end\nend\n\nif petInfo.canBattle and petInfo.isOwned and not rares[speciesID] then\n  return true\nend"] = nil
L["Polished Pet Charms"] = nil
L["-- Pets with Polished Pet Charms in their source.\n\nreturn (petInfo.sourceText or \"\"):match(\"item:163036\") and true"] = nil
L["Script Filter"] = nil
L["Test"] = nil
L["New Script Filter"] = nil
L["Script Name:"] = nil
L["Script filters create custom filters with Lua code.\nSee /docs/scriptfilters.txt for more information."] = nil
L["Delete Script Filter"] = nil
L["\nAre you sure you want to delete the script filter named %s%s\124r?\n\n"] = nil
L["Script Filter Error"] = nil
L["%sThe script filter just loaded has the following error and will not be used:"] = nil
L["line "] = nil

-- dialogs\summaryDialog.lua
L["Unique Pets In the Journal"] = nil
L["Total Collected Pets"] = nil
L["Unique Collected Pets"] = nil
L["Pets Not Collected"] = nil
L["Percent Collected"] = nil
L["Max Level Pets"] = nil
L["Average Pet Level"] = nil
L["Rare Quality Pets"] = nil
L["Pets In Teams"] = nil
L["Pet Collection"] = nil
-- L["Team with the most wins (%s%d\124r)"] = nil
L["Total"] = nil
L["Pets Collected"] = nil
L["Pets At Max Level"] = nil
L["Duplicate Collected Pets"] = nil
L["Average Battle Pet Level"] = nil
L["There are %s%d\124r unique pets in the journal"] = nil
L["You've collected %s%.1f%%\124r of them"] = nil

-- info\petInfo.lua
L["Unknown"] = nil
L["Leveling Pet"] = nil
L["Ignored Pet"] = nil
L["Random %s"] = nil
L["Random Pet"] = nil
L["Empty Pet Slot"] = nil
L["Not Notable"] = nil

-- info\targetData.lua
L["Menagerie"] = nil
L["Garrison"] = nil
L["Beasts of Fable"] = nil

-- info\targetInfo.lua
L["No Target"] = nil
L["%s (npc id %d)"] = nil

-- layout\definitions.lua
L["TAB_PETS"] = nil
L["TAB_TEAMS"] = nil
L["TAB_TARGETS"] = nil
L["TAB_QUEUE"] = nil
L["TAB_OPTIONS"] = nil

-- layout\frame.lua
L["Rematch can't be summoned during combat. Try again later"] = nil

-- layout\journal.lua
L["Use Rematch In Journal"] = nil
L["Check this to restore Rematch to the journal.\n\nYou can always use Rematch in its standalone window, accessed via key binding, /rematch command or from the Minimap button if enabled in options."] = nil

-- main\constants.lua
L["Toggle Rematch"] = nil
L["Rematch Team Notes"] = nil
L["Journal Is Locked"] = nil
L["Wrong Faction"] = nil
L["Wrong Covenant"] = nil
L["\124cffff2020Retrieving data..."] = nil
L["Random Team"] = nil

-- main\slash.lua
L["Reset Everything"] = nil
L["Reset everything?"] = nil
L["This will wipe all settings, teams, queue, etc (absolutely everything), and then reload the UI to start Rematch from scratch."] = nil
L["Warning: This cannot be undone!"] = nil
L["Delete All Teams"] = nil
L["Delete all teams?"] = nil
L["This will wipe all teams and groups.\n\nAre you sure you want to %sDELETE\124r all teams and groups permanently?"] = nil
L["Usage: Target an npc to create data for, enter a pet battle, and once in battle with opponent pets displayed, enter:\n\124cffffffff/rematch targetdata"] = nil
L["The team named \"%s\" can't be found."] = nil

-- menus\loadoutMenu.lua
L["Put Leveling Pet Here"] = nil
L["Stop Leveling This Slot"] = nil
L["Put Random Pet Here"] = nil
L["Stop Randomizing This Slot"] = nil
L["Ignore This Slot"] = nil
L["Stop Ignoring This Slot"] = nil
L["Any Type"] = nil
L["Set Notes"] = nil
L["Find Similar"] = nil
L["Find Teams"] = nil
L["Battle Pet Slot %d"] = nil

-- menus\menus.lua
L["Print TeamID"] = nil

-- menus\petFilterMenu.lua
L["In addition to the filters in this menu, you can further refine the pet list with the search box. Some search examples:\n\nPets: %sBlack Tabby\124r\nZones: %sSilithus\124r\nAbilities: %sSandstorm\124r\nText in abilities: %sBleed\124r\nLevels: %slevel=21-23\124r\nStats: %sspeed>300\124r\n\nSearches in \"quotes\" will limit results to only complete matches.\n\nSearch results will be sorted by relevance unless the option %sDon't Sort By Relevance\124r is checked in the Options tab."] = nil
L["In filter menus, checkbox groups assume if nothing is checked you want to view all choices.\n\nYou can also:\n\n%s[Shift]+Click\124r to check all except the box clicked.\n\n%s[Alt]+Click\124r to uncheck all except the box clicked."] = nil
L["Only Favorites"] = nil
L["Strong Vs"] = nil
L["Tough Vs"] = nil
L["Pet Marker"] = nil
L["Script"] = nil
L["Favorite Filters"] = nil
L["Export Pets"] = nil
L["Help"] = nil
L["Pet Filter"] = nil
L["Reset All"] = nil
L["Checkbox Groups"] = nil
L["Low Level (1-7)"] = nil
L["Mid Level (8-14)"] = nil
L["High Level (15-24)"] = nil
L["Max Level (25)"] = nil
L["Without Any 25s"] = nil
L["Moveset Not At 25"] = nil
L["All breed data is pulled from your installed %s%s\124r addon.\n\nThe breed \"New\" means the pet has no breed data. Keep your breed addon up to date to ensure it has the most recent breed data."] = nil
L["Not Leveling"] = nil
L["Tradable"] = nil
L["Can Battle"] = nil
L["Can't Battle"] = nil
L["One Copy"] = nil
L["Two+ Copies"] = nil
L["Three+ Copies"] = nil
L["In A Team"] = nil
L["Not In A Team"] = nil
L["Unique Moveset"] = nil
L["Shared Moveset"] = nil
L["Current Zone"] = nil
L["Hidden Pets"] = nil
L["Has Notes"] = nil
L["Then Sort By"] = nil
L["Reverse Sort"] = nil
L["Favorites First"] = nil
L["You can filter to a specific range of stats too. For example, search for:\n\n%shealth>500\124r\nor\n%sspeed=200-300\124r\n\nThe sort order is not ordinarily reset when filters are reset. The option %sReset Sort With Filters\124r in the Options tab will reset the sort when you reset the filters."] = nil
L["Finally Sort By"] = nil
L["Save Favorite Filter"] = nil
L["Save this Favorite Filter?"] = nil
L["Filters: %s%s\124r\n\nEnter a new name for this Favorite Filter:"] = nil
L["Filters: %s%s\124r\n\nEnter a name for this new Favorite Filter:"] = nil
L["Delete Favorite Filter"] = nil
L["\nAre you sure you want to delete the filter named %s%s\124r?\n\nFilters: %s%s\n\n"] = nil
L["Press Ctrl+C to copy to clipboard\n\n%sThese are pets currently listed. Adjust the filters to limit which to include."] = nil
L["Export Simple Pet List"] = nil
L["Rename Pet Marker"] = nil
L["Enter a new name"] = nil
L["Script Filters"] = nil
L["New Script"] = nil
L["Script filters are a way to create new pet filters with Lua code.\n\nSome knowledge of Lua is helpful to create them. See docs/scriptfilters.txt for more information."] = nil
L["Save Filter"] = nil
L["A filter must be active before it can be saved."] = nil
L["Total Pets: %d"] = nil
L["Distinct Pets: %d"] = nil
L["Species Name,Custom Name,Type,Collected,Favorite,Level,Rarity"] = nil
L[",Breed"] = nil

-- menus\petMenu.lua
L["Find Moveset"] = nil
L["Slotted pets can't be released."] = nil
-- L["You can rename Pet Markers from the Filter menu. Move the mouse over a Pet Marker in the Filter menu and click the gear button to rename."] = nil
L["Pet name too long.\nMaximum 16 characters."] = nil
L["Invalid name.\nNo numbers allowed."] = nil
L["Hide Pet"] = nil
L["Hide this pet?"] = nil
L["Are you sure you want to hide all versions of %s%s\124r?\n\n%sHidden pets will not show up in the pet list or searches. You can view or unhide these pets from the 'Other' pet filter."] = nil
L["Don't Ask When Hiding Pets"] = nil
L["Release this pet?"] = nil
L["Once released, this pet is gone forever!"] = nil
L["This pet is used in teams! "] = nil
L["Cage this pet?"] = nil
L["Don't Ask When Caging Pets"] = nil
L["This pet is used in teams!"] = nil
L["Show Pet"] = nil
L["Injured pets cannot be caged."] = nil
L["Slotted pets cannot be caged."] = nil
L["Remove from Leveling Queue"] = nil
L["Add to Leveling Queue"] = nil

-- menus\queueMenu.lua
L["Sort by:"] = nil
L["Ascending Level"] = nil
L["Median Level"] = nil
L["Descending Level"] = nil
L["In Teams First"] = nil
L["Rares First"] = nil
L["Active Sort"] = nil
L["The queue will automatically order pets by the sort criteria in the menu options above. The order of pets may automatically change as they gain xp or get added/removed from the queue.\n\nYou cannot manually change the order of pets and still keep the queue actively sorted."] = nil
L["Pause Preferences"] = nil
L["Suspend all criteria from default, team and group preferences.\n\nWhile preferences are paused, the top-most pet in the queue will be chosen if it can be loaded."] = nil
L["Fill Queue"] = nil
L["Fill the leveling queue with one of each version of a pet that can level from the filtered pet list, that you don't have a level 25 copy or one in the queue already."] = nil
L["Fill Queue More"] = nil
L["Fill the leveling queue with one of each version of a pet that can level from the filtered pet list, regardless whether you have any at level 25 or one in the queue already."] = nil
L["Empty Queue"] = nil
L["Remove all pets from the leveling queue."] = nil
L["Export Queue"] = nil
L["Export all pets in the leveling queue for later importing.\n\n%sNote\124r: Rematch will make a best guess what to import, but there's no guarantee the exact same pets will import, especially after they've leveled. This works best without many duplicates."] = nil
L["Import Queue"] = nil
L["Import pets to the queue that have been previously exported.\n\n%sNote\124r: Rematch will make a best guess what to import, but there's no guarantee the exact same pets will import, especially after they've leveled. This works best without many duplicates."] = nil
L["This is the leveling queue. Drag pets you want to level here.\n\nRight click any of the three battle pet slots and choose 'Put Leveling Pet Here' to mark it as a leveling slot you want controlled by the queue.\n\nWhile a leveling slot is active, the queue will fill the slot with the top-most pet in the queue. When this pet reaches level 25 (gratz!) it will leave the queue and the next pet in the queue will take its place.\n\nTeams saved with a leveling slot will reserve that slot for future leveling pets."] = nil
L["Move To Top Of Queue"] = nil
L["Move Pet In Queue"] = nil
L["Move To End Of Queue"] = nil
L["Empty queue?"] = nil
L["Are you sure you want to remove all pets from the leveling queue?"] = nil
L["Add these pets to the queue?"] = nil
L["More"] = nil
L["This will add %s%s\124r pets to the leveling queue."] = nil
L["Don't Ask When Filling Queue"] = nil
L["This is a lot of pets. You can be more selective by filtering pets."] = nil
L["Active Sort Enabled"] = nil
L["Turn off Active Sort and move pet?"] = nil
L["%s is already in the queue and Active Sort is enabled."] = nil
L["The queue controls the order of pets while it's actively sorted.\n\nTo move this pet within the queue, Active Sort needs to be turned off."] = nil
L["Don't Ask To Stop Active Sort"] = nil
L["Remove From Queue"] = nil
L["Remove %s from the leveling queue?"] = nil
L["Don't Ask For Queue Removal"] = nil
L["Import"] = nil
L["This is not a valid queue import"] = nil
L["Pets to add to queue"] = nil
L["Pets already in queue"] = nil
L["Pets that can't level"] = nil
L["Invalid pets"] = nil

-- menus\targetMenu.lua
L["Edit Target"] = nil
L["Load Random Pets"] = nil
L["Load Team"] = nil
L["These are the teams saved for %s."] = nil
L["The topmost team is the preferred team to load when you interact with this target."] = nil
L["No teams :("] = nil

-- menus\teamMenu.lua
-- L["Create Group"] = nil
L["Edit Group"] = nil
L["Move Group"] = nil
L["Delete Group"] = nil
L["Export Group"] = nil
L["Unload Team"] = nil
L["Move Team"] = nil
L["Load Target"] = nil
L["Share"] = nil
L["Delete Team"] = nil
L["Plain Text"] = nil
L["Export Team"] = nil
L["Send Team"] = nil
L["Sending teams is disabled due to Disabling Sharing in options.\n\nYou can still export and import teams, however."] = nil
L["Create New Group"] = nil
L["Team Herder"] = nil
L["Backup All Teams"] = nil
L["New Group"] = nil
L["Group"] = nil
L["Icon"] = nil
L["Group Name:"] = nil
L["Sort:"] = nil
L["By Name"] = nil
L["Sort By Name"] = nil
L["Sort teams in this group alphabetically."] = nil
L["By Wins"] = nil
L["Sort By Wins"] = nil
L["Sort teams in this group by how many times the team has won, if win records are tracked."] = nil
L["Custom Sort"] = nil
L["Sort teams in this group manually. New teams to this group are added to the end."] = nil
L["Show Tab For This Group"] = nil
L["Up to %d groups can be chosen to display as tabs along the right side of the Rematch window.\n\n%s%d of %d\124r possible tabs are shown."] = nil
L["\n\nYou will need to hide another group's tab before you can show a tab for this group."] = nil
L["Groups are categories you create for organizing your teams. Unlimited groups can be made but only %d can be shown as tabs."] = nil
L["Leveling preferences choose which pets are picked first in the leveling queue. All criteria are optional."] = nil
L["Group Leveling Preferences"] = nil
L["Delete this group?"] = nil
L["Also delete teams in this group"] = nil
L["All teams in this group will be deleted. %sThis cannot be undone!\124r"] = nil
L["%sAre you sure you want to %sdelete\124r this team? This cannot be undone."] = nil
L["Don't Ask When Deleting Teams"] = nil
L["Export Teams"] = nil
L["Hide Tab"] = nil
L["Show Tab"] = nil
L["%s%d of %d\124r tabs are currently shown.\n\nBefore the tab for this group can be shown, another one needs to be hidden."] = nil
L["Remove Favorite"] = nil
L["Set Favorite"] = nil
L["Done"] = nil
L["Pick a group to move teams to:"] = nil
L["While this window is on screen, click a team in the team list to move it to this group:"] = nil
L["When the cursor changes to a \124TInterface\\Cursor\\Crosshairs:16\124t over a team, click to move the team to the selected group."] = nil
L["No targets :("] = nil

-- panels\loadedTargetPanel.lua
L["Load a set of random high level pets. If the recent target's pets are known, random pets are preferred if they are strong vs and tough vs the opponent pets."] = nil
L["Add or remove teams from this target, or change the order of teams for this target."] = nil
L["Save New Team"] = nil
L["Create a new team for this target with the currently loaded pets."] = nil
L["Load the team saved to this target."] = nil
L["Save"] = nil

-- panels\loadedTeamPanel.lua
L["Counter to %s"] = nil

-- panels\loadoutPanel.lua
L["When this team loads, a pet from the leveling queue will go in this spot."] = nil
L["Ignored Slot"] = nil

-- panels\optionsList.lua
L["All Options"] = nil
L["Interaction Options"] = nil
L["On Target"] = nil
L["On Mouseover"] = nil
L["On Soft Interact"] = nil
L["Always Interact"] = nil
L["The default behavior is to perform the target or mouseover interaction once until you interact with another NPC with a saved team. Check this to always interact with NPCs that have a saved team not already loaded."] = nil
L["Prefer Uninjured Teams"] = nil
-- L["When you interact with an NPC that has more than one team saved to it, choose the team with no injured pets instead of the topmost team for the target. On Prompt To Load and Show Minimized Window options where you can choose which team to load, start with the healthiest team."] = nil
L["Show Window After Loading"] = nil
L["When a team is loaded from an interaction (target or mouseover) and the Rematch window is not on screen, summon the standalone Rematch window."] = nil
L["Only When Any Pets Injured"] = nil
L["If a team is loaded but no pets are injured, don't summon the Rematch window."] = nil
L["Standalone Window Options"] = nil
L["Anchor To"] = nil
-- L["Tab Anchor"] = nil
L["Use Custom Scale"] = nil
L["Keep Window On Screen"] = nil
L["Don't hide the standalone window when the ESCape key is pressed or most other times it would hide, such as going to the game menu."] = nil
L["Even For Pet Battles"] = nil
L["Keep the standalone window on the screen even when you enter pet battles."] = nil
L["Even Across Sessions"] = nil
L["If the standalone window was on screen when logging out, automatically summon it on next login."] = nil
L["Don't Minimize With ESC Key"] = nil
L["Don't minimize the standalone window when the ESCape key (or game menu key) is pressed."] = nil
L["Don't Minimize With Panel Tabs"] = nil
L["Don't let the Pets, Teams, Queue or Options tabs minimize the standalone window."] = nil
L["Lower Window Behind UI"] = nil
L["Push the standalone window back behind other parts of the UI so other parts of the UI can appear ontop."] = nil
L["Show Pets Tab While Minimized"] = nil
L["When the window has a Pets tab and is minimized, drop the Targets tab and keep the Pets tab visible."] = nil
L["Show Window After Battle"] = nil
L["Show the standalone Rematch window after leaving a pet battle."] = nil
L["But Not After PVP Battle"] = nil
L["Since pets don't remain injured in PVP battles, don't show the window when leaving a PVP battle."] = nil
L["Appearance Options"] = nil
L["Compact Pet List"] = nil
L["Display more pets in the pet list by using a more compact view of each pet."] = nil
L["Compact Team List"] = nil
L["Display more teams in the team list by using a more compact view of each team."] = nil
L["Compact Target List"] = nil
L["Display more targets in the target list by using a more compact view of each target."] = nil
L["Compact Queue List"] = nil
L["Display more pets in the queue by using a more compact view of each pet."] = nil
L["Hide Level At Max Level"] = nil
L["If a pet is level 25, don't show its level on the pet icon."] = nil
L["Hide Rarity Borders"] = nil
L["Don't color the icon border for pets you own in the same color as its rarity."] = nil
L["Show Ability Numbers"] = nil
L["In the ability flyout, show the numbers 1 and 2 to help with the common notation such as \"Pet Name 122\" to know which abilities to use."] = nil
L["On Loaded Abilities Too"] = nil
L["In addition to the flyouts, show the numbers 1 and 2 on loaded abilities."] = nil
L["Color Pet Names By Rarity"] = nil
L["Make the names of pets you own the same color as its rarity. Blue for rare, green for uncommon, etc."] = nil
L["Color Team Names By Group"] = nil
L["Make team names colored the same as the colors you've chosen for the groups they belong to."] = nil
L["Color Targets By Expansion"] = nil
L["Make notable target names colored after the expansion the target is from."] = nil
L["Behavior Options"] = nil
L["Card Speed"] = nil
L["Choose how quickly you prefer the pet card and notes to be shown when you mouseover a pet or notes button."] = nil
L["Tooltip Speed"] = nil
L["Collapse Lists With ESC Key"] = nil
L["When the ESCape key (or game menu key) is pressed, collapse any expanded list--such as this options list, teams or targets."] = nil
L["Toolbar Options"] = nil
L["Reverse Toolbar Buttons"] = nil
L["Reverse the order of the toolbar buttons (Revive Battle Pets, Battle Pet Bandages, Safari Hat, etc)."] = nil
L["Hide On Toolbar Right Click"] = nil
L["When a toolbar button is used with a right click, dismiss the Rematch window after performing its action."] = nil
L["Safari Hat Reminder"] = nil
L["When a pet is laoded below max level, draw attention to the Safari Hat button, including summoning the window if it's not on screen."] = nil
L["Display Unique Pets Total"] = nil
L["Instead of Total Pets in the collections button at the topleft, display a total of Unique Pets."] = nil
L["Pet Filter Options"] = nil
L["Use Level In Strong Vs Filter"] = nil
L["When doing a Strong Vs filter, take the level of the pet into account. If a pet is not high enough level to use a Strong Vs ability, do not list the pet.\n\n\124cffffffffNote:\124r A Strong Vs filter is sometimes useful for identifying pets you want to level or capture. This option will hide those pets while the Strong Vs filter is active."] = nil
L["Reset Filters On Login"] = nil
L["When logging in, start with all pets listed and no filters active."] = nil
L["Reset Sort With Filters"] = nil
L["When clearing filters, also reset the sort back to the default: Sort by Name, Favorites First."] = nil
L["Don't Reset Search With Filters"] = nil
L["When manually clearing filters, don't clear the search box too.\n\nSome actions, such as logging in or Find Similar, will always clear search regardless of this setting."] = nil
L["Sort By Chosen Name"] = nil
L["When pets are sorted by name, sort them by the name given with the Rename option instead of their original name."] = nil
L["Sort New Pets To Top"] = nil
L["When you learn new pets, temporarily sort them to the top of the pet list until you next close Rematch or choose Reset All from the filter menu."] = nil
L["Hide Non-Battle Pets"] = nil
L["Only list pets that can battle. Do not list pets like balloons, squires and other companion pets that cannot battle."] = nil
L["Allow Hidden Pets"] = nil
L["Allow the ability to hide specific pet species in the pet list with a 'Hide Pet' in the list's right-click menu.\n\nYou can view pets you've hidden from the Other -> Hidden Pets filter."] = nil
L["When exporting pets from the Export Pets filter menu item, only export a list of pets without details."] = nil
L["Don't Sort By Relevance"] = nil
L["When searching for pets by name, don't sort the results by relevance.\n\nWhen sorted by relevance, pets with the search term in their name are listed first, followed by term in notes, then abilities."] = nil
L["Breed Options"] = nil
L["Breed Source"] = nil
L["Breed Format"] = nil
L["Pet Card Options"] = nil
L["Card Background"] = nil
L["Flip Modifier Key"] = nil
L["Don't Flip On Mouseover"] = nil
L["When you mouseover the pet icon or type icon at the top of the pet card, don't flip to the back of the card. Instead, flip the card only by clicking the pet or type icon at the top of the pet card; or by the flip modifier key if defined."] = nil
L["Allow Pet Cards To Be Pinned"] = nil
L["When dragging a pet card to another part of the screen, pin the card so all future pet cards display in the same spot, until the pet card is moved again or the unpin button is clicked."] = nil
L["Always Show Health Bar"] = nil
L["On the pet card, always display the health bar if a pet can battle and has health. While unchecked, the health bar is only displayed for injured pets."] = nil
L["Always Show HP/XP Bar Text"] = nil
L["On the pet card health and experience bars, keep the status text always visible instead of requiring a mouseover to view."] = nil
L["Always Hide Possible Breeds"] = nil
L["When the pet card is not minimized, rather than list possible breeds across the bottom of the pet card, always put the list of possible breeds in the tooltip of the pet's breed stat button.\n\nNote: For uncollected pets that don't have a breed, this means possible breeds will not be visible."] = nil
L["Always Use Collected Stat"] = nil
L["When the pet card is not minimized, rather than list collected versions of a pet across the bottom of the pet card, use a collected button alongside other stats to display collected totals. Mouseover of the button will display the list of collected versions of the pet."] = nil
L["Show Expansion On Front"] = nil
L["Instead of displaying the expansion the pet is from on the back of the pet card, display it on the front alongside other stats."] = nil
L["Show Strongest Vs Stat"] = nil
L["On the pet card display the top three pet types the pet is strongest against, based on its abilities."] = nil
L["Show Species IDs Stat"] = nil
L["Display the numerical speciesID as a stat on pet cards."] = nil
L["Alternate Lore Font"] = nil
L["Use a more modern-looking font for lore text on the back of the pet card."] = nil
L["Use Pet Cards In Battle"] = nil
L["Use the pet card on the unit frames during a pet battle instead of the default tooltip."] = nil
L["Use Pet Cards For Links"] = nil
L["Use the pet card when viewing a link of a pet someone else sent you instead of the default link."] = nil
L["Notes Options"] = nil
L["Keep Notes On Screen"] = nil
L["Don't hide notes when changing tabs or closing Rematch."] = nil
L["Even When Escape Pressed"] = nil
L["Also don't hide notes when ESCape key is pressed."] = nil
L["Show Notes When Teams Load"] = nil
L["When a team with notes is loaded, display the notes for the team."] = nil
L["Show Notes In Battle"] = nil
L["If the loaded team has notes, display and lock the notes when you enter a pet battle."] = nil
L["Only Once Per Team"] = nil
L["Only display notes automatically the first time entering battle, until another team is loaded."] = nil
L["Notes Size"] = nil
L["Ability Tooltip Options"] = nil
L["Ability Background"] = nil
L["Show Ability IDs"] = nil
L["Show the ability ID for the ability being viewed in the ability tooltip."] = nil
L["Team Options"] = nil
L["Load Healthiest Pets"] = nil
L["When a team loads, if any pet is injured or dead and there's another version with more health \124cffffffffand identical stats\124r, load the healthier version.\n\nPets in the leveling queue are exempt from this option.\n\n\124cffffffffNote:\124r This is only when a team loads. It will not automatically swap in healthier pets when you leave battle."] = nil
L["Allow Any Version"] = nil
L["Instead of choosing only the healthiest pet with identical stats, choose the healthiest version of the pet regardless of stats."] = nil
L["After Battles Or Heals Too"] = nil
L["Also load healthiest pets after leaving a pet battle or using Revive Battle Pets or Battle Pet Bandage."] = nil
L["Always Show Team Tabs"] = nil
-- L["Show team tabs along the right side of the window even if you're not on the team panel."] = nil
L["Display Where Teams Dragged"] = nil
L["When a team is dragged to another group, print in the chat window where the team was moved to."] = nil
L["Enable Dragging To Move Teams"] = nil
L["Allow moving teams or groups by dragging them. When this is unchecked you can still move a team or group from its right-click menu."] = nil
L["Require Click To Drag Teams"] = nil
L["When dragging teams or groups to move them, release of the mouse button at the end of the drag will not move the team or group. A separate click is needed."] = nil
L["Prioritize Breed On Import"] = nil
L["When importing or receiving teams, fill the team with the best matched breed as the first priority instead of the highest level."] = nil
L["Remember Import Override"] = nil
L["Rather than resetting to 'Create a new copy' everytime a team is imported and another team shares the same name, remember the last-chosen option without resetting."] = nil
L["Random Pet Options"] = nil
L["Random Pet Rules"] = nil
L["Pick Aggressive Counters"] = nil
L["When using a Load Random Pets button for random pets to counter a target, prefer pets with more Strong attacks over pets that are Tough vs opponent attacks."] = nil
L["Random Abilities Too"] = nil
L["For random pets, choose random abilities too."] = nil
L["Warn For Pets Below Max Level"] = nil
L["Show a warning dialog when a random pet is chosen below level 25. (This is recommended if you're doing Family Familiar achievements with random pets.)\n\nWhen possible, random pets will be from a pool of your max-level pets. However, depending on your collected pets and the other random pet options you've chosen, the random pool may include pets not at max level."] = nil
L["Team Win Record Options"] = nil
L["Hide Win Record Text"] = nil
L["Hide the win record displayed to the right of each team.\n\nYou can still manually edit a team's win record from its right-click menu and automatic tracking (if enabled) will continue if win records are hidden."] = nil
L["Auto Track Win Record"] = nil
L["At the end of each battle, automatically record whether the loaded team won or lost.\n\nForfeits always count as a loss.\n\nYou can still manually update a team's win record at any time from its right-click menu."] = nil
L["For PVP Battles Only"] = nil
L["Automatically track whether the loaded team won or lost only in a PVP battle and never for a PVE battle."] = nil
L["Display Win-Loss Instead"] = nil
L["Instead of displaying the win percentage of a team to the right of the team list, display the total number of wins and losses in the format win-loss.\n\nTeam tabs that are sorted by win record will sort by total wins also."] = nil
L["Leveling Queue Options"] = nil
L["Show Extra Preferences Button"] = nil
L["When a leveling slot is loaded, show a preferences button above the loadout panel where pets are slotted, in addition to the one always shown at the top of the queue panel."] = nil
L["Sort Queue By Pet Name Too"] = nil
L["When the queue is sorted, sort pets by name also. Otherwise, pets will try to stay in the order they were added to the queue or moved."] = nil
L["Hide Leveling Pet Toast"] = nil
L["Don't display the popup 'toast' when a new pet is automatically loaded from the leveling queue."] = nil
L["Add Fill Queue More Option"] = nil
L["In addition to a 'More' button added to the Fill Queue dialog, add a Fill Queue More option to the Queue menu."] = nil
L["Prefer Living Pets"] = nil
L["When loading pets from the queue, skip dead pets and load living ones first."] = nil
L["And At Full Health"] = nil
L["Also prefer uninjured pets when loading pets from the queue."] = nil
L["Double Click To Send To Top"] = nil
L["When a pet in the queue panel is double clicked, send it to the top of the queue instead of summoning it."] = nil
L["Add Imported Pets To Queue"] = nil
L["When importing a team, automatically add any chosen pets to the leveling queue if they're below level 25."] = nil
L["Automatically Level New Pets"] = nil
L["When you capture or learn a pet that can level, automatically add it to the leveling queue."] = nil
L["Only Pets Without One At 25"] = nil
L["Only automatically add pets to the queue when you don't have a version already at 25 or in the queue."] = nil
L["Only Rare Pets"] = nil
L["Only automatically add rare pets to the leveling queue."] = nil
L["Random Pet When Queue Empty"] = nil
-- L["When the queue is empty and a team loads with leveling slots, load a random high-level pet in the leveling slots."] = nil
L["Confirmation Options"] = nil
L["Don't ask for confirmation when hiding a pet.\n\nYou can view hidden pets in the 'Other' pet filter."] = nil
L["If the pet doesn't belong to any teams, don't ask for confirmation when putting a pet in a cage."] = nil
L["Don't ask for confirmation when deleting a team."] = nil
L["Don't ask for confirmation when deleting notes from a pet or team."] = nil
L["Don't ask for confirmation when filling the queue from the Queue menu."] = nil
L["Don't ask to stop the Active Sort in the queue when moving a pet within the queue while it's enabled. Always turn off active sort."] = nil
L["Don't ask for confirmation when removing a pet from the leveling queue."] = nil
L["Don't Warn About Missing Pets"] = nil
L["Don't display a popup when a team loads and a pet within the team can't be found."] = nil
L["Don't Remind About Backups"] = nil
L["Don't show a popup offering to backup teams every once in a while. Generally, the popup appears sometime after the number of teams increases by 50."] = nil
L["Miscellaneous Options"] = nil
L["Use Default Journal"] = nil
L["Turn off Rematch integration with the default pet journal.\n\nYou can still use Rematch in its standalone window, accessed via key binding, /rematch command or from the Minimap button if enabled in options."] = nil
L["Keep Companion"] = nil
L["After a team is loaded, summon back the companion that was at your side before the load; or dismiss the pet if you had none summoned."] = nil
L["Use Minimap Button"] = nil
L["Place a button on the minimap to toggle Rematch and load favorite teams."] = nil
L["No Summon On Double Click"] = nil
L["Do nothing when pets within Rematch are double-clicked. The normal behavior of double click throughout Rematch is to summon or dismiss the pet."] = nil
L["Disable Sharing"] = nil
L["Disable the Send button and also block any incoming pets sent by others. Import and Export still work."] = nil
L["Help Options"] = nil
L["Hide Extra Help"] = nil
-- L["Hide the informational \"Help\" items found in many menus and on the pet card."] = nil
L["Hide Descriptive Tooltips"] = nil
L["Hide tooltips that describe what a button does."] = nil
L["Hide Toolbar Tooltips"] = nil
L["Hide tooltips for the toolbar buttons."] = nil
L["Hide Option Tooltips"] = nil
L["Hide tooltips for options like the one you're reading now."] = nil
L["Hide Truncated Tooltips"] = nil
L["Hide tooltips for team or target names when they're truncated (such as Sully \"The Pickle\" McL... instead of Sully \"The Pickle\" McLeary)."] = nil
L["About Rematch"] = nil
L["Version "] = nil

-- panels\optionsPanel.lua
L["Search Options"] = nil
L["The standalone window can be scaled from 50% to 200% of its normal size:"] = nil
L["When the standalone window is minimized or maximized, use the chosen corner/edge as the anchor."] = nil
L["Panel Tabs"] = nil
L["Choose which corner of the standalone Rematch window to anchor panel tabs such as Pets, Teams, Targets, etc.\n\nNote: Choosing a new anchor for the whole window will change the tabs anchor to match. You can change this tabs anchor again anytime."] = nil
L["Choose how quickly you prefer the tooltips (including pet ability tooltips) to be shown."] = nil
-- L["Tooltip Speed:"] = nil
L["Slow"] = nil
L["Slow Mouseover"] = nil
L["Wait three quarters of a second for the tooltip to appear when you mouseover a button with a tooltip."] = nil
L["Normal"] = nil
L["Normal Mouseover"] = nil
L["Wait a quarter of a second for the tooltip to appear when you mouseover a button with a tooltip."] = nil
L["Fast"] = nil
L["Fast Mouseover"] = nil
L["Immediately show the tooltip when you mouseover a button with a tooltip."] = nil
-- L["Card Speed:"] = nil
L["Wait three quarters of a second for the pet card or notes to appear when you mouseover a pet or notes button."] = nil
L["Wait a quarter of a second for the pet card or notes to appear when you mouseover a pet or notes button."] = nil
L["Immediately show the pet card or notes when you mouseover a pet or notes button."] = nil
L["On Click"] = nil
L["Only show the pet card or notes when you click a pet or notes button."] = nil
L["The modifier key that will flip the pet card over. Regardless of this setting, you can flip the pet card over by mouseover of the pet's icon at the top of the card."] = nil
L["The artwork displayed in the background on the front of pet cards."] = nil
L["Expansion Art"] = nil
L["Portrait Art"] = nil
L["Icon Art"] = nil
L["Type Art"] = nil
L["The artwork displayed in the background of ability tooltips."] = nil
L["Rules to apply when loading a random pet. The more strict rules will limit the pool of random pets to choose from.\n\nNote: When a team loads with random pets in all three slots, 'Lenient' rules are used regardless of this setting."] = nil
L["Strict"] = nil
L["Scrict Rules"] = nil
L["When a random pet is chosen, never pick pets saved in a team and never pick injured pets."] = nil
L["Normal Rules"] = nil
L["When a random pet is chosen, prefer pets not saved in a team and prefer uninjured pets."] = nil
L["Lenient"] = nil
L["Lenient Rules"] = nil
L["When a random pet is chosen, allow pets saved in a team and prefer uninjured pets."] = nil
L["Which enabled addon you want to use to supply breed data."] = nil
L["No breed information will be shown if this is selected. Rematch does not maintain its own breed data."] = nil
L["How breeds should display."] = nil
L["Letters"] = nil
L["Numbers"] = nil
L["Icons"] = nil
-- L["Interact On Target"] = nil
L["Choose the action to take when you target an NPC with a saved team that's not already loaded."] = nil
-- L["On Target:"] = nil
L["Do Nothing"] = nil
L["When targeting an NPC with a saved team not already loaded, do nothing."] = nil
L["Prompt To Load"] = nil
L["When targeting an NPC with a saved team not already loaded, show a prompt to load the save team."] = nil
L["Show Window"] = nil
L["When targeting an NPC with a saved team not already loaded, show the standalone Rematch window."] = nil
L["Auto Load"] = nil
L["When targeting an NPC with a saved team not already loaded, automatically load the saved team.\n\n%sWarning\124r: If you target with right click and immediately enter battle, it may be too late to load a team. %sAuto Load is not recommended for On Target.\124r Use On Mouseover for Auto Load instead."] = nil
-- L["Interact On Soft Interact"] = nil
L["Choose the action to take when you soft interact with an NPC with a saved team that's not already loaded.\n\n%sNote\124r: This option is only available if SoftTargetInteract cvar is fully enabled (3). It will be hidden otherwise."] = nil
-- L["On Soft Interact:"] = nil
L["When soft interactiong with an NPC with a saved team not already loaded, do nothing."] = nil
L["When soft interacting with an NPC with a saved team not already loaded, show a prompt to load the save team."] = nil
L["When soft interacting with an NPC with a saved team not already loaded, show the standalone Rematch window."] = nil
L["When soft interacting with an NPC with a saved team not already loaded, automatically load the saved team."] = nil
-- L["Interact On Mouseover"] = nil
L["Choose the action to take when the mouse moves over an NPC with a saved team that's not already loaded."] = nil
-- L["On Mouseover:"] = nil
L["When the mouse moves over an NPC with a saved team not already loaded, do nothing."] = nil
L["When the mouse moves over an NPC with a saved team not already loaded, show a prompt to load the save team."] = nil
L["When the mouse moves over an NPC with a saved team not already loaded, show the standalone Rematch window."] = nil
L["When the mouse moves over an NPC with a saved team not already loaded, automatically load the saved team."] = nil
L["Choose the size of the text in the pet and team notes."] = nil
L["Small"] = nil
L["Medium"] = nil
L["Large"] = nil
L["Adjust the relative size of the standalone Rematch window by changing its scale."] = nil

-- panels\petsPanel.lua
L["Search Pets"] = nil
L["Max Level Filter"] = nil
L["%s Level 25 pets\n%s Level 25 \124cff2090fdrare\124r pets"] = nil
L["Pets: %s%d"] = nil
L["Filters: %s%s"] = nil

-- panels\queuePanel.lua
L["Queue"] = nil
L["Leveling Pets: %s%d"] = nil
L["Active Sort:  %s %s%s"] = nil

-- panels\targetsPanel.lua
L["Search Targets"] = nil
L["No recent targets"] = nil

-- panels\teamsPanel.lua
L["Search Teams"] = nil
L["No favorite teams"] = nil
L["No ungrouped teams"] = nil
L["No teams in this group"] = nil

-- process\interact.lua
L["Load this team?"] = nil
L["This target"] = nil
L["%s has a saved team"] = nil

-- process\loadTeam.lua
L["Pets are missing"] = nil
L["Low level random pet"] = nil
L["Pets are missing in the team just loaded."] = nil
L["A low level random pet just loaded."] = nil

-- process\preferences.lua
L["Current Leveling Preferences"] = nil
L["Current"] = nil
L["Default"] = nil
L["Combined team, group and default preferences"] = nil
L["Loaded Team's Group Preferences"] = nil
L["No saved team loaded"] = nil
L["Group preferences are saved to the loaded team's group and override default preferences."] = nil
L["Loaded Team Preferences"] = nil
L["Team preferences are saved to the loaded team and override default and group preferences."] = nil
L["Default Preferences"] = nil
L["Base preferences regardless of team loaded"] = nil
L["Default preferences are always active (unless paused) regardless of team loaded."] = nil
L["Leveling preferences choose which pets are picked first in the leveling queue.\n\n"] = nil
L["Current Preferences:"] = nil
L["Minimum level"] = nil
L["Maximum level"] = nil
L["Minimum health"] = nil
L["  Allow any %s or %s\n"] = nil
L["  Expected damage taken: %s\n"] = nil
L["Maximum health"] = nil
L["None\n"] = nil
L["Pause"] = nil
L["\n%sPreferences are currently paused. \124rRight-click this button to resume preferences.\n"] = nil
L["Resume"] = nil
L["\n%s %sEdit Preferences\n%s %s Preferences"] = nil

-- process\queue.lua
L["%s has also been added to your leveling queue!"] = nil

-- process\send.lua
L["Send"] = nil
L["Enter the name of an online Rematch user:"] = nil
L["Send To:"] = nil
L["Sending, please wait..."] = nil
L["Incoming Rematch Team"] = nil
L["Someone"] = nil
L["%s%s has sent you a team!"] = nil
L["No response. This player is not online or doesn't have Rematch enabled."] = nil
L["Team successfully sent!"] = nil
L["They're busy. Try again later."] = nil
L["They're in combat. Try again later."] = nil
L["They have team sharing disabled."] = nil
L["There was an error. Try again later."] = nil

-- process\teamStrings.lua
L["any"] = nil
L["at least %d health"] = nil
L["allow low-level Magic or Mechanical pets"] = nil
L["expect %s damage"] = nil
L["at most %d health"] = nil
L["at least level %.f"] = nil
L["at most level %.f"] = nil
L["%s has been added to your leveling queue!"] = nil
L["Backup Teams"] = nil
L["You have %s%d\124r Rematch teams.\n\nWould you like to back them up now?"] = nil
L["Choosing Yes will export all teams to copy and paste in an email to yourself or someplace safe.\n\nYou can also do this at any time from the Teams button at the top of the Teams panel of Rematch."] = nil

-- process\toast.lua
L["Now leveling:"] = nil
L["Rematch's leveling queue is empty"] = nil
L["All done leveling pets!"] = nil

-- roster\filters.lua
L["Stats"] = nil
L["Favorites"] = nil
L["Types"] = nil
L["Sources"] = nil
L["Similar"] = nil
L["Moveset"] = nil
L["Sort"] = nil
L["Battle"] = nil
L["Quantity"] = nil
L["Notes"] = nil
L["Hidden"] = nil
L["Zone"] = nil

-- savedvars\savedGroups.lua
L["Ungrouped Teams"] = nil

-- templates\petListButton.lua
L["This pet cannot level.\n\nIt can't be added to the leveling queue."] = nil

-- tooltips\abilityTooltip.lua
L["Vs"] = nil
L["\124TInterface\\WorldMap\\Gear_64Grey:16:16:0:0:64:64:8:56:6:57\124t %sAbility ID: %d"] = nil

-- utils\utils.lua
L["Please Wait..."] = nil

-- Version: 5.0.1 --

-- cards\petCard.lua
L["Find Pets With This Ability"] = nil

-- menus\petMenu.lua
L["Start Leveling"] = nil

-- menus\teamMenu.lua
L["Are you sure you want to delete the group %s and all teams within it?"] = nil
L["Are you sure you want to delete the group %s? All of its teams will be moved to the %s group."] = nil

-- panels\optionsList.lua
L["When you interact with an NPC that has more than one team saved to it, choose the team with no injured pets instead of the topmost team for the target. On Prompt To Load and Show Window options where you can choose which team to load before loading, start with the healthiest team."] = nil
L["Prefer Minimized Window"] = nil
L["When the window is automatically summoned such as from an Interact Option or Safari Hat Reminder, summon the window in minimized mode."] = nil
L["Always Use Pet Satchel"] = nil
L["Rather than displaying all toolbar buttons in larger views of the addon, always use the Pet Satchel button to cycle through infrequently used toolbar buttons."] = nil
L["Hide Breed In Lists"] = nil
L["Hide the breeds displayed in lists. Breeds will still be visible in pet cards."] = nil
L["Hide Breed In Pet Slots"] = nil
L["Hide the breeds displayed on pet slots. Breeds will still be visible in pet cards."] = nil


-- Version: 5.0.2 --

-- menus\queueMenu.lua
L["Press Ctrl+C to copy to clipboard"] = nil

-- panels\optionsList.lua
L["Hide the informational \"Help\" items found in menus, pet cards, dialogs and elsewhere."] = nil
L["All Options Troubleshoot Export Reset"] = nil

-- panels\optionsPanel.lua
L["Export Options"] = nil
L["This is intended to help troubleshoot issues.\n\nMany options interact with other options. When reporting a problem this can help recreate the issue."] = nil
L["Reset Options"] = nil
L["Restore all options to default?"] = nil
L["This will restore all options in Rematch to default values and reload the UI.\n\nThis includes all settings in the Options panel but does not include teams, leveling queue or notes."] = nil
L["All Options:"] = nil
L["Reset"] = nil
L["Export"] = nil

-- Version: 5.0.4 --

-- chrome\toolbar.lua
L["Unique Pets: %s%d\124r\nTotal Pets: %s%d\124r\nUncollected Pets: %s%d\124r\nAverage Level: %s%.1f\124r%s"] = nil

-- menus\teamMenu.lua
L["Teams and Groups"] = nil
L["Teams can be organized into an unlimited number of collapsible groups. You can create new groups with %sCreate New Group\124r in this menu. Up to %d groups can be shown as tabs to act as bookmarks to these groups.\n\nBoth teams and groups can be rearranged with drag and drop. To easily move many teams to another group, use %sTeam Herder\124r in this menu.\n\nTeams with a %s beside their name contain at least one target.\nTeams with a %s beside their name contain a leveling preference.\nPets or targets with a %s beside their name belong to at least one team."] = nil

-- panels\optionsList.lua
L["Show Create New Group Tab"] = nil
L["When space permits, add a button at the bottom of team tabs to create a new group."] = nil
L["Show team tabs along the right side of the window even if you're not on the teams panel."] = nil
L["Never Show Team Tabs"] = nil
L["Never show team tabs along the right side of the window even if you're on the teams panel."] = nil
L["Target or pet is in a team"] = nil
L["Pet is in the leveling queue"] = nil
L["Team or pet has notes"] = nil
L["Team has at least one target"] = nil
L["Team or group has preferences"] = nil

-- panels\optionsPanel.lua
L["Import Options"] = nil
L["This will reset most options, set them to values pasted here, then reload the UI. %sUse this at your own risk!\124r Tinkering with these values can cause Rematch to become unstable and require a full reset."] = nil
L["This will reset most options!\nThis cannot be undone!"] = nil

-- Version: 5.0.5 --

-- panels\optionsList.lua
L["Hide Notes Button In Battle"] = nil
L["In the Battle UI, hide the notes \"micro\" button to show notes for the currently-loaded team. Enable this option if another addon wants to use the same space."] = nil
L["When the queue is empty and a team loads with leveling slots, put random pets that are not max level into the leveling slots."] = nil
L["Pick Random Max Level"] = nil
L["When the queue is empty and a team loads with leveling slots, put random max-level pets in the leveling slots."] = nil

-- Version: 5.1.0 --

-- chrome\toolbarButtons.lua
L["Safari Hat"] = nil

-- dialogs\dialogMixins.lua
L["Top %d Winning Teams"] = nil

-- dialogs\summaryDialog.lua
L["Rank teams by percentage won"] = nil
L["Pet Types"] = nil
L["Battles"] = nil

-- main\constants.lua
L["Pet Tags are a way to categorize pets for any meaning you choose. You can then filter by specific tags.\n\nTo tag a pet, right-click a pet in the pet list and choose a tag from the Pet Tags menu.\n\nTo easily tag multiple pets, choose the %sPet Herder\124r option in the main Filters menu.\n\nYou can rename a tag by moving the mouse over a tag in a Pet Tags menu and clicking the %s that appears to the right of the tag's name.\n\nFor instance you can rename %s to Wild Pets To Get, tag pets you'd like to capture with a %s, and the pet card and other places will use the new name for the tag."] = nil

-- menus\petFilterMenu.lua
L["Pet Tags"] = nil
L["Pet Herder"] = nil

-- panels\optionsList.lua
L["Badge Options"] = nil
L["Only Show Badges On Mouseover"] = nil
L["Hide all badges unless the mouse is over the pet, team or target.\n\nA badge is a non-interactive icon to the right of a list item to indicate some property such as whether it's leveling.\n\nWith this option enabled, the notes button, breed and win record are also hidden unless the mouse is over the list item."] = nil
L["Hide Team Badges %s"] = nil
L["Hide the %s badge on pets and targets that indicate the pet or target is saved in a team."] = nil
L["Hide Leveling Badges %s"] = nil
L["Hide the %s badge on pets that indicate the pet is in the leveling queue."] = nil
L["Hide Pet Tag Badges %s"] = nil
L["Hide the pet tag badges (such as %s %s %s etc) on pets to indicate what pet tag has been given to the pet."] = nil
L["Hide Target Badges %s"] = nil
L["Hide the %s badge on teams that indicate the team contains a target."] = nil
L["Hide Preference Badges %s"] = nil
L["Hide the %s badge on teams that indicate the team contains leveling preferences."] = nil
L["Hide Notes Badges %s"] = nil
L["Hide the %s badge/button on pets and teams that indicate the pet or team has saved notes."] = nil
L["Hide External Badges %s"] = nil
L["Try to hide any badges added to lists from an external source like a third-party addon. (Rematch has no control over what outside addons do, so some addon's badges may not hide with this option.)"] = nil
L["Larger Breed Text"] = nil
L["Increase the size of breed text (such as B/B or H/P) on pet list buttons and pet slots."] = nil
L["Combine Group Key"] = nil
L["Don't Ask To Remove From Queue"] = nil

-- panels\optionsPanel.lua
-- L["Combine Groups Key"] = nil
L["While dragging a team group in the team list, holding this modifier key when you click another group will combine the two groups by moving all teams in the group on the cursor into the clicked group."] = nil

-- process\dragFrame.lua
L["Combine Groups"] = nil
L["Combine team groups?"] = nil
L["This will move all teams from %s to %s, leaving the %s group empty."] = nil
L["This will move all teams from %s to %s and then delete the emptied %s group afterwards."] = nil
L["Don't Delete Empty Group"] = nil
L["You can also selectively move many teams with the Team Herder tool from the Teams button"] = nil

-- process\petHerder.lua
L["Now click on pets in the pet list to use this action on the pets"] = nil
L["Pick an action to use on multiple pets"] = nil
L["Then click on pets in the pet list to use this action on the pets"] = nil
L["Allow caging pets in a team"] = nil
L["When the cursor changes to a \124TInterface\\Cursor\\Crosshairs:16\124t over a pet, click the pet to use the chosen action"] = nil
L["You don't own this pet"] = nil
L["Injured pets can't be caged"] = nil
L["Slotted pets can't be caged"] = nil
L["This pet is not tradable"] = nil
L["This pet is in a team"] = nil
L["This pet can't level"] = nil
L["This pet has no pet tag"] = nil

-- utils\utils.lua
L["Cage Pet (Without Confirmation)"] = nil
L["Set/Remove Favorite"] = nil
L["Add/Remove From Leveling Queue"] = nil
L["Remove Pet Tags"] = nil
L["Set/Remove Pet Tag: %s"] = nil


-- Version: 5.1.2 --


-- menus\teamMenu.lua

L["This is a system group that cannot be deleted."] = nil
L["Delete Teams"] = nil
L["This group has no teams."] = nil
L["Delete Group Teams"] = nil
L["There are %s%d\124r teams in the group %s."] = nil
L["%sAre you sure you want to %sdelete\124r these teams? This cannot be undone."] = nil

-- panels\optionsList.lua

L["Mousewheel Speed"] = nil
L["Choose how quickly you prefer lists to scroll when you mousewheel up or down over a list."] = nil
L["Slow Mousewheel"] = nil
L["Scroll one line at a time."] = nil
L["Normal Mousewheel"] = nil
L["Scroll two lines at a time."] = nil
L["Medium Mousewheel"] = nil
L["Scroll roughly half a page at a time."] = nil
L["Fast Mousewheel"] = nil
L["Scroll nearly a whole page at a time."] = nil
L["Battle Pet Breed ID"] = nil
L["PetTracker"] = nil
